### PR TITLE
Adding tm_scope for REBOL language and removing REBOL from LICENSE_WHITE...

### PR DESCRIPTION
**Pull request by Oldes**
...LIST as now is license available in the Sublime-REBOL project.

### CODE REVIEW

**Comment by Oldes** [comment]
This would probably need Grammar submodule update to pass the test. The license is in the project now: Oldes/Sublime-REBOL@102402f

**Comment by pchaigno** [comment]
Could you update it in this pull request?

**Comment by Oldes** [comment]
What do you mean with the: *"Could you update it in this pull request?"* ?

**Comment by pchaigno** [comment]
I mean could you update the submodule for the Rebol grammar?
Otherwise, it should be updated with the next release :-)

**Comment by Oldes** [comment]
Unfortunately I don't know how to do it.. To be honest, I was not even able to pull the project with submodules on my Windows, because of file names used in many submodules (I had to exclude submodules).

**Comment by arfon** [comment]
:+1: thanks @Oldes.

**Comment by aroben** [comment]
Thank you!

**Pull request merged**
