### PR TITLE
More CMake samples

### LINKED ISSUE #1961: Particular CMakeLists.txt file not detected as CMake
https://github.com/serge-v/ctests/blob/fbce433d9fa09465a2b883a1e320a5e2c242ba97/departures/CMakeLists.txt is getting detected as `Text`, rather than `CMake`:

```console
$ bundle exec linguist CMakeLists.txt 
CMakeLists.txt: 29 lines (20 sloc)
  type:      Text
  mime type: text/plain
  language:  Text
```

/cc @serge-v

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
Fixes #1961 by adding six more CMake samples.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
Cherry-picked @pchaigno's sample from #1944.

**Comment by aroben** [comment]
Should any of the new samples have a `.txt` extension? (Does that even matter?)

**Comment by larsbrinkhoff** [comment]
I don't think it matters to the Bayesian classifier.

If it were needed, we also need to add `.txt` as a CMake extension.  But that would seem wrong.  I believe only the `CMakeLists.txt` file use the `.txt` extension, and the other CMake files conventionally use `.cmake`.

**Comment by bkeepers** [comment]
Sweet. Did you confirm that this fixes it?

**Comment by larsbrinkhoff** [comment]
@bkeepers Yes.

**Comment by bkeepers** [comment]
Awesome. Looks good to me! :+1:

**Pull request merged**
