### PR TITLE
support for leex (.xrl) / yecc (.yrl) files

### PR DESCRIPTION
**Pull request by lpil**
leex (http://www.erlang.org/doc/man/leex.html) is a regular expression based
lexical analyzer generator for Erlang, similar to lex or flex.

yecc (http://www.erlang.org/doc/man/yecc.html) is an LALR-1 parser generator
for Erlang, similar to yacc. Takes a BNF grammar definition as input, and
produces Erlang code for a parser.

It'd be great to have these understood by github. Is there anything else I need
to do ? :)

### CODE REVIEW

**Comment by pchaigno** [comment]
As per the [contribution guidelines to add a new language](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language), you'll need to link to examples on GitHub of `.xrl` and `.yrl` files (the more the better). If you could also add a sample file per extension, from real world applications, it'd be perfect!

**Comment by lpil** [comment]
Hi Paul, I've added 2 real world example. Thanks :)

**Comment by arfon** [comment]
> you'll need to link to examples on GitHub of .xrl and .yrl files (the more the better).

Hi @lpil - would you mind linking to some examples of 'in the wild' usage here? See our [contribution guidelines](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language) for how to do this.

**Comment by lpil** [comment]
Oh, sorry. I misunderstood. I added some real world examples to the repo. Should they be removed?

The yrl used in the compiler of the Elixir programming language: https://github.com/elixir-lang/elixir/blob/master/lib/elixir/src/elixir_parser.yrl

The xrl used in the compiler of the LFE programming language: https://github.com/rvirding/lfe/blob/develop/src/lfe_scan.xrl

**Comment by lpil** [comment]
Ping @arfon, what else can I do to help this get merged? Thanks :)

**Comment by pchaigno** [comment]
Actually, a GitHub search is expected for examples in the wild (From the contribution guidelines, `Open a pull request, linking to a GitHub search result showing in-the-wild usage.`). See #1561 for an example.

**Comment by lpil** [comment]
Ah, I misread. Thanks!

Will this suffice?

https://github.com/search?utf8=%E2%9C%93&q=extension%3Ayrl+Nonterminals&type=Code&ref=searchresults

https://github.com/search?utf8=%E2%9C%93&q=extension%3Axrl+rules&type=Code&ref=searchresults

**Comment by pchaigno** [comment]
From the second search, there are only 515 files but those are distributed across 308 repositories owned by 361 users. It will probably be sufficient but you'll have to wait for @arfon's answer to make sure; I'm not from GitHub ;)

**Comment by lpil** [comment]
Cool, thank you. I imagine it'll be hard to find many examples as these Erlang modules are only really used in compilers.

**Comment by arfon** [comment]
Thanks for providing the links to search results @lpil. This looks good to me!

**Comment by arfon** [comment]
@lpil - this will be live on GitHub in the next release of Linguist (in the next week or so)

**Comment by lpil** [comment]
Great, thank you. I'll be sure to read the instructions more clearly next time ;)

**Pull request merged**
