### PR TITLE
Add extension support for MusicXML (.mxl). Addresses issue #3641.

### PR DESCRIPTION
**Pull request by nolanholden**
The changes are:
1. add entry in `languages.yml` for MXL
2. add samples to `samples/MXL/`

Here is some in-the-wild usage:
https://github.com/search?p=3&q=extension%3Amxl+www.musicxml.org&type=Code&utf8=%E2%9C%93

*(Addresses issue #3641.)*

### CODE REVIEW

**Comment by pchaigno** [comment]
[I couldn't find many MusicXML files in-the-wild](https://github.com/search?utf8=%E2%9C%93&q=extension%3Amxl+xml+OR+version&type=Code). Most `.mxl` files appear to be ZIP archives.

**Comment by nolanholden** [comment]
My apologies, the first few pages are from a single user with compressed .mxl files.
find plenty of examples here: 

https://github.com/search?p=3&q=extension%3Amxl+www.musicxml.org&type=Code&utf8=%E2%9C%93
---
Here is a specific example from MIT Research lab's. It is a Johann Sebastian Bach MXL score:

- https://github.com/cuthbertLab/music21/blob/e523f802c002ad93085d66dcadb53d3752f6cb7c/music21/corpus/bach/bwv133.6.xml

Here are some test .mxl scores for a .NET MusicXML parser:
- https://github.com/vdaron/MusicXml.Net/tree/develop/MusicXml.Unit.Tests/TestData

Here are more, all different users:
- https://github.com/shanahdt/mus7921/blob/4513847a7c73748d66bbdb389527b0fd1045713f/corpus/Monody/Misc/syrinx.mxl
- https://github.com/morganecf/music21/blob/521ff85a3d757ca513fc9ff6927609e9c089240d/music21/corpus/luca/gloria.mxl
- https://github.com/rdhyee/ScoreDiff/blob/5f57d63ae99e1f7823e5a2a305c9b98a5c97a3b3/src/test_cases/bwv66.6.mxl
- https://github.com/bewest/music21-bewest.clone/blob/8975116677ce4feb6209933a03501984cbe2dbc5/music21/corpus/luca/gloria.mxl
- https://github.com/jonathanmarmor/homemadehouse/blob/a03e71cd49d202caadd1bbbc617477d4ca7f230b/output/tests/musicxml_test.mxl


Best regards,
Nolan

**Comment by nolanholden** [comment]
Hello, @pchaigno .
Updated above are plenty of in-the-wild MusicXML (.mxl) documents.
Please review when you have a chance.

Thank you!
-Nolan

**Comment by lildude** [comment]
> Updated above are plenty of in-the-wild MusicXML (.mxl) documents.

I'm afraid I disagree. 30 between 6 users (from your own search query) isn't sufficiently popular at this time.

**Comment by pchaigno** [comment]
Closing in favor of #4219. We'll monitor the popularity of the extension there.

If you have an improved search query compared to the one used in #4219, please post it here and I'll update #4219.

**Pull request closed without merging**
