### PR TITLE
add support for oracle PLSQL

### PR DESCRIPTION
**Pull request by Shoelace**
Plsql is a procedural language including SQL in Oracle RDBMS. 

i have seen previous attempts to get this support (ie #244 and #243) into linguist but it not there in the current version.. and the last comment was 1 year ago.

### CODE REVIEW

**Comment by arfon** [comment]
Hi @Shoelace. I'm trying to clean up some old Pull Requests on Linguist and this one is very out of date now. The good news is we've done a bunch of work on the heuristics since this Pull Request and they're now [used routinely](https://github.com/github/linguist/blob/master/lib/linguist/heuristics.rb). 

If this support for SQLPL and PLpgSQL is still of interest to you would you mind opening up a new Pull Request for review?

**Comment by chezwicker** [comment]
Looking to figure out if anything has been done to support PL/SQL syntax highlighting, anyone know what the status is?

**Comment by Shoelace** [comment]
@chezwicker I did have an update for this.. but as you can see i've been asked to update it to teh current release.. that'll take me a few days. maybe a week depending on "real work".  so stay tuned.

**Comment by chezwicker** [comment]
@Shoelace Good stuff, thanks! Any chance you could add _.plsql_ to the list of extensions while you're at it?

Out of curiosity, could you link the pull request when you're ready? I might contribute if I feel I get the overall picture... I'm generally happy to help, but I'm afraid would need an example and an explanation how to test to get started.

**Pull request closed without merging**
