### PR TITLE
Add support for RBI files

### PR DESCRIPTION
**Pull request by peterzhu2118**
## Description

`.rbi` files will be for Sorbet type definition. See [here](https://sorbet.org/docs/rbi) for more details. TLDR: Sorbet is a static typechecker for Ruby developed by Stripe that will open sourced soon, it uses `.rbi` (Ruby interface) files to define the structure of gems and Ruby code. These `.rbi` files are valid Ruby code that contain no method body.

## Checklist:

- [x] **I am associating a language with a new file extension.**
  - [ ] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      
      - https://github.com/search?q=extension%3Arbi+sig&type=Code
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      -  https://github.com/sorbet/sorbet-typed/blob/master/lib/ruby/all/open3.rbi
    - Sample license(s): [Apache 2](https://github.com/sorbet/sorbet-typed/blob/master/LICENCE)
  - [x] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am adding a new language.**
  - [ ] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  
  - [ ] I have included a syntax highlighting grammar: https://github-lightshow.herokuapp.com/
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

- [ ] **I am fixing a misclassified language**
  - [ ] I have included a new sample for the misclassified language:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am changing the source of a syntax highlighting grammar**
  
  - Old: https://github-lightshow.herokuapp.com/
  - New: https://github-lightshow.herokuapp.com/

- [ ] **I am updating a grammar submodule**
  

- [ ] **I am adding new or changing current functionality**
  
  - [ ] I have added or updated the tests for the new or changed functionality.

- [ ] **I am changing the color associated with a language**
  
  - [ ] I have obtained agreement from the wider language community on this color change.
    - [URL to public discussion]
    - [Optional: URL to official branding guidelines for the language]

### CODE REVIEW

**Comment by peterzhu2118** [comment]
Hey @lildude, thanks for taking at look at this PR!

1. I've updated the PR with the search. Here it is: https://github.com/search?q=extension%3Arbi+sig&type=Code. There's not that many placing using it right now (especially not in public repositories) because the typechecker is in a closed beta right now (will be open sourced soon).
2. I've updated the example to generated type definitions for `Open3` stdlib library from [sorbet/sorbet-typed](https://github.com/sorbet/sorbet-typed/blob/master/lib/ruby/all/open3.rbi).
3. See 2.
4. I'm not sure how I should place the license file. It has an Apache 2 license.
5. I've updated the ordering so that tests now pass. 

Please let me know how it looks and if there are other changes that need to be made.

**Comment by lildude** [comment]
Thanks. Re:

>     4\. I'm not sure how I should place the license file. It has an Apache 2 license.

We just need it mentioned in the "Sample license(s):" line in the template; we don't need the file itself.  The link on the "Sample source(s):" should also be updated to link to the actual source location.

**Comment by peterzhu2118** [comment]
Ah I just need to update it in the PR, I thought I needed to add it to the file. I've updated the PR with the link to the license.

**Comment by peterzhu2118** [comment]
FYI, [Sorbet is now open source 🎉](https://github.com/sorbet/sorbet).

**Pull request closed without merging**
