### PR TITLE
Add DataWeave language

### PR DESCRIPTION
**Pull request by menduz**
Usages:
https://github.com/search?p=1&q=extension%3Adwl+NOT+nothack&type=Code&utf8=%E2%9C%93

Documentation: https://mule4-docs.mulesoft.com/mule-user-guide/v/4.0/dataweave

### CODE REVIEW

**Comment by lildude** [comment]
Oooo, one thing... can you please cite the source of your examples? We need to know they're licensed under a friendly license.

I've withdrawn my approval for the moment.

**Comment by Alhadis** [comment]
@menduz You'll also need to resolve conflicts with the latest changes to `master`.

**Comment by menduz** [comment]
Hello! thanks for your reviews, the examples are taken from the grammar repository itself (MIT), those are part of the tmLanguage [test suite](https://github.com/mulesoft-labs/data-weave-tmLanguage/tree/2.0-release2/tests/cases). 

I've updated the git submodule to the latest version of the grammar.

**Comment by Alhadis** [comment]
Thanks! 😀 
 
> I've updated the git submodule to the latest version of the grammar.

Ah, just for future reference: Linguist will automatically update each grammar module right before a new release, so there's no need for contributors to update grammars manually. ;) Just telling you know to save submitting another PR in future. ;-)

**Comment by pchaigno** [comment]
> Also, I'm utterly flabbergasted at how many people have posted reactions to this pull-request. 😮 I recall it was about ~23 a few hours after submission, it's since climbed past 60. Must be a record. 😀 

@Alhadis That's usually a sign that a link to the PR was posted on social medias :-)

**Comment by Alhadis** [comment]
Got it. =)

Suppose I'd better add an icon for DataWeave in [`file-icons`](https://github.com/file-icons/atom), eh? ;)

**Comment by menduz** [comment]
@Alhadis I'd like to help but I didn't find where the actual icon should go.

```svg
<svg viewBox="0 0 26 26" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <path fill="#087299" d="M24.725 10.743l-8.223 11.743-2.281-3.257 1.221-1.744L16.502 19l5.781-8.257L20 7.486l1.221-1.743 3.504 5zm-14.166-.233L7.221 5.743 6 7.486l4.559 6.512L13 10.51l-1.221-1.743-1.22 1.743z"></path>
    <path fill="#00A3E0" d="M21.221 5.743L9.498 22.486 1.275 10.743 6 4l1.221 1.743-3.504 5L9.498 19 20 4l1.221 1.743z"></path>
</svg>
```

That's our icon

**Comment by Alhadis** [comment]
@menduz New icons are requested at [`file-icons/source`](https://github.com/file-icons/source), but it's a process I do by hand to ensure quality (I nitpick with a graphics editor, so it's really not something anybody can submit a PR for).

Thanks for the icon! 😀

**Pull request merged**
