### PR TITLE
Rename HTML+Django to Jinja

### LINKED ISSUE #5265: Jinja templates are detected as HTML files
## Describe the bug
Github is marking [my repository](https://github.com/starcraft66/infrastructure) that doesn't contain a single line of HTML as containing 75% HTML. I ran linguist on the repo locally and according to the output, it is considering all files with the `.j2` extension as HTML files:
```
HTML:
roles/tdude.core/templates/issue.j2
roles/tdude.elk/templates/docker-compose.yml.j2
roles/tdude.elk/templates/elasticsearch.yml.j2
roles/tdude.elk/templates/journalbeat.yml.j2
roles/tdude.elk/templates/kibana.yml.j2
roles/tdude.elk/templates/logstash.yml.j2
roles/tdude.elk/templates/pipelines/cisco-syslog.conf.j2
roles/tdude.elk/templates/pipelines/journalbeat.conf.j2
roles/tdude.elk/templates/pipelines/lancache.conf.j2
roles/tdude.elk/templates/pipelines/output.conf.j2
roles/tdude.elk/templates/pipelines/syslog.conf.j2
roles/tdude.gitlab/templates/docker-compose.yml.j2
roles/tdude.kerio/templates/docker-compose.yml.j2
roles/tdude.lolisafe/templates/config.js.j2
roles/tdude.lolisafe/templates/docker-compose.yml.j2
roles/tdude.matrix/templates/coturn/coturn.service.j2
roles/tdude.matrix/templates/coturn/turnserver.conf.j2
roles/tdude.matrix/templates/docker-compose.yml.j2
roles/tdude.matrix/templates/element/config.json.j2
roles/tdude.matrix/templates/matrix-appservice-webhooks/appservice-registration-webhooks.yaml.j2
roles/tdude.matrix/templates/matrix-appservice-webhooks/config.yml.j2
roles/tdude.matrix/templates/matrix-appservice-webhooks/database.json.j2
roles/tdude.matrix/templates/matrix-media-repo/media-repo.yaml.j2
roles/tdude.matrix/templates/mjolnir/mjolnir.yaml.j2
roles/tdude.matrix/templates/nginx/matrix.conf.j2
roles/tdude.matrix/templates/synapse/config.logging.j2
roles/tdude.mediaserver/templates/docker-compose.yml.j2
roles/tdude.mediaserver/templates/jackett.j2
roles/tdude.mediaserver/templates/radarr.j2
roles/tdude.mediaserver/templates/sonarr.j2
roles/tdude.mediaserver/templates/tautulli.j2
roles/tdude.mediaserver/templates/varken.j2
roles/tdude.minecraft-discord-bridge/templates/config.json.j2
roles/tdude.minecraft-discord-bridge/templates/docker-compose.yml.j2
roles/tdude.monitoring/templates/docker-compose.yml.j2
roles/tdude.monitoring/templates/prometheus-node-exporter.j2
roles/tdude.monitoring/templates/prometheus.yml.j2
roles/tdude.ndppd/templates/ndppd.conf.j2
roles/tdude.statusfy/templates/docker-compose.yml.j2
roles/tdude.traefik/templates/docker-compose.yml.j2
roles/tdude.traefik/templates/http.toml.j2
roles/tdude.traefik/templates/traefik.toml.j2
roles/tdude.wireguard/templates/interface.conf.j2
```

This is obviously not the case as all of the `.j2` files in my repo are templates yaml, json and other configuration files.

### Expected behaviour
Jinja templates should be classified as "Jinja templates" or something more descriptive that isn't HTML. Alternatively, linguist could drill down further in the file name and classify `.html.j2` files as HTML, `.yaml.j2` files as YAML, `.json.j2` files as JSON etc.

### Related discussion
@lildude pointed out in https://github.com/github/linguist/issues/5047 that jinja2 templates "are part of the "HTML+Django" language which is part of the HTML group of languages". This is obviously a bug, there's nothing about files ending in `.j2` that makes them "HTML+Django" specific. In my case, Ansible roles in my repo make significant use of jinja2 that has nothing to do with HTML or Django.

### PR DESCRIPTION
**Pull request by Nixinova**
All file extensions listed are Jinja. Nunjucks was previously removed in #5167.

Django has no unique file extension ([src](https://stackoverflow.com/questions/2035362/django-template-file-extension-preference)).

~~Remove all Django aliases as Django is a separate language – Is this okay?~~

Ungroup from HTML as Jinja is not only used for HTML (resolve #5265).

### CODE REVIEW

**Review by Alhadis — APPROVED** [review]

**Review by lildude — CHANGES_REQUESTED** [review]
Can you please put back the aliases. These have been in place for a really long time and are actively used.

**Comment by lildude** [comment]
Thanks. You missed off adding back `htmldjango` so I've done it as it's definitely still used: https://github.com/search?q=htmldjango+language%3Amarkdown&type=code I couldn't find any uses of `html+django/jinja` so I've left that one "missing".

**Comment by lildude** [comment]
🤦 I've just noticed that this isn't needed as the original `html+django/jinja` which is now without the trailing `/jinja` already covers this. Reverting.

**Review by lildude — APPROVED** [review]

**Comment by lildude** [comment]
> 🤦 I've just noticed that this isn't needed as the original `html+django/jinja` which is now without the trailing `/jinja` already covers this. Reverting.

And now I look into it, I should have trusted my first instinct... `html+django` is not treated like `htmldjango` or `html django`:

```console
$ hub checkout -q https://github.com/github/linguist/pull/5267
From github.com:github/linguist
 * [new ref]             refs/pull/5267/head -> jinja
$ bundle exec irb
irb(main):001:0> require_relative "lib/linguist"
=> true
irb(main):002:0> Linguist::Language.find_by_alias('html+django')
=> #<Linguist::Language name=Jinja>
irb(main):003:0> Linguist::Language.find_by_alias('htmldjango')
=> nil
irb(main):004:0> Linguist::Language.find_by_alias('html django')
=> nil
irb(main):005:0> 
```

Reverting my revert 😁

**Pull request merged**
