### PR TITLE
Add script to generate a reader-friendly grammar list

### PR DESCRIPTION
**Pull request by Alhadis**
Users who encounter syntax highlighting errors on GitHub are apt to report them here, unaware that Linguist isn't directly responsible for the actual highlighting. This may be partly due to the fact the [site's own help articles](https://help.github.com/articles/creating-and-highlighting-code-blocks/) point to Linguist as its *"source of language recognition and syntax highlighting"*.

Currently, we lack anything better to direct users to who want to report syntax highlighting errors. @arfon [put it best](https://github.com/github/linguist/issues/3186#issuecomment-244610844):

> I mean, [this list](https://github.com/github/linguist/tree/master/vendor/grammars) is the source of truth here but the idea of sending people to a folder of Git submodules is literally the least user-friendly thing I think I've ever thought of...

My suggestion was to maintain a list of repository links in the form of a `README.md` file, which would be programmatically updated whenever grammars are added or removed. This PR is an implementation of that suggestion.

Some things that're missing:
* **We need to tie this into a build step:**  
I'm not familiar with Bundler or Rake, so I don't know where or how to go about having this script called when `bundle exec rake` is called. Somebody help, please? =)
* **A better preamble for the readme:**  
I only added it as a placeholder to verify that rerunning the script wouldn't chop it off each time it executed. Feel free to replace the wording with something you feel is more appropriate.

**NOTE:** ~~I've yet to investigate why some of the grammars aren't being included (such as Perl). Will look into this soon.~~ Resolved by 3247d46.

### CODE REVIEW

**Comment by pchaigno** [comment]
> I'm not familiar with Bundler or Rake, so I don't know where or how to go about having this script called when bundle exec rake is called. Somebody help, please? =)

Wouldn't it be sufficient to tie this to `convert-grammar --add`?
It might also be time we make a script to remove grammars (to remove the submodule, the lines in `grammars.yml`, and update this list).

**Comment by Alhadis** [comment]
I could easily do that, but... I kinda thought that's what `prune-grammars.rb` does...

**Comment by pchaigno** [comment]
`prune-grammars.rb` only removes grammar from `grammars.yml` when their scopes are not used. It could actually benefit from a script that *entirely* removes the grammar. We can make the script to remove grammars in a second time/PR though.

**Comment by Alhadis** [comment]
Agreed. Right now, we could have something to divert syntax-related queries to, heh. =)

Apropos of annoying questions, [thoughts on this](https://github.com/github/linguist/pull/3149)? It's beginning to get mouldy.

**Comment by Alhadis** [comment]
@pchaigno The reason I thought to leave it to a `bundle rake` step was so the list would only be updated for the public once a release was cut. So there's no risk of users reporting issues to the wrong repositories if a grammar's been swapped out, but not showing results on GitHub yet. =)

**Comment by pchaigno** [comment]
Good thinking! I think the easiest solution will be to add it to [the instructions to release a new version](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#releasing).

**Comment by Alhadis** [comment]
Sounds good. =) I'll leave that to you or @arfon to take care of, haha.

**Comment by arfon** [comment]
Sorry for taking a frikin' eternity to look at this @Alhadis. This is looking pretty good and agreed we should hook this into some other part of the build/docs for contributing so people know to run this when adding a new grammar.

I just made my own branch with this PR and current `master` and it looks like it's tripping up on [L80](https://github.com/github/linguist/pull/3192/files#diff-db68bd961ab0ce17baa056c59024741dR80) when  scope is `text.groff`. The error is 
```
./script/list-grammars:83:in `block in to_markdown': undefined method `chomp' for nil:NilClass (NoMethodError)```

It's not immediately clear what's going on here.

Adding a couple of lines to print out some debug information:

```
      else
        puts scope if @sources[scope].nil?
        next if @sources[scope].nil?
        submodule = @submodules[@sources[scope].chomp("/")]
        next unless submodule
        short_url = submodule[:short]
        long_url  = submodule[:url]
      end```

it looks like it's these two grammars causing issues:

```
source.dosbatch
text.groff
```

Any ideas what might be going on here? 😕

**Comment by Alhadis** [comment]
Ah, it might've been because it was waiting [on this](https://github.com/github/linguist/pull/3189/files). The `dosbatch` grammar was weird in that it was using a targeted subdirectory... I'm not sure what the hell's the deal with `text.groff` though (perhaps a lingering vestige of the old manpage grammar?)

I've synced with master. Could you try again?

**Comment by Alhadis** [comment]
Can't reproduce; the list updated perfectly fine. Must've been because of the issue I mentioned, then. =)

I should mention that choosing grammars with non-standard grammar locations will cause issues, as was the case with the DOSBatch grammar. Such cases will need to be [explicitly handled here](https://github.com/github/linguist/pull/3192/files#diff-db68bd961ab0ce17baa056c59024741dR62), but in the case of DOSBatch, I knew the grammar needed replacing... so I purposefully left it out.

**Comment by arfon** [comment]
> Can't reproduce; the list updated perfectly fine. Must've been because of the issue I mentioned, then. =)

Re-cloned the repo and checked out this PR and I can't reproduce it either. Go figure. I've made a new PR with these changes and some small additions over in #3307

**Comment by Alhadis** [comment]
I blame submodules. Always blame submodules.

**Comment by arfon** [comment]
> I blame submodules. Always blame submodules.

Thinkin' the same thing.

**Pull request closed without merging**
