### PR TITLE
Add AngelScript scriping language

### PR DESCRIPTION
**Pull request by ifarbod**
From http://angelcode.com/angelscript:

>The AngelCode Scripting Library, or AngelScript as it is also known, is an extremely flexible cross-platform scripting library designed to allow applications to extend their functionality through external scripts. It has been designed from the beginning to be an easy to use component, both for the application programmer and the script writer.
For the script writer the scripting language follows the widely known syntax of C/C++, but without the need to worry about pointers and memory leaks. Contrary to most scripting languages, AngelScript uses the common C/C++ datatypes for more efficient communication with the host application.

The selected color is also from the same website.

It's basically a C/C++-like language, so I guess there's no need for a custom grammar.
[Here](https://github.com/search?utf8=%E2%9C%93&q=extension%3Aangelscript+NOT+nothack&type=Code&ref=searchresults)'s a search result with some angelscript files.

### CODE REVIEW

**Comment by codecat** [comment]
Hi, is this PR abandoned? I'd like to contribute to this, if possible.

**Comment by ifarbod** [comment]
@codecat I couldn't fix those issues from Travis, Feel free to continue this whatsoever.

**Comment by codecat** [comment]
Well it looks like Travis is failing because you've added a `.asc` file while it is expecting a `.as` file:

```
  1) Failure:

TestSamples#test_ActionScript_has_samples [/home/travis/build/github/linguist/test/test_samples.rb:77]:

Missing samples in "samples/AngelScript/*.as". See https://github.com/github/linguist/blob/master/CONTRIBUTING.md
```

I mentioned the ambiguity with Actionscript in #3841 too, and I'm wondering if there's a procedure to solve that issue?

**Comment by lildude** [comment]
Closing in favour of https://github.com/github/linguist/pull/3844

**Pull request closed without merging**
