### PR TITLE
Add `.jav` to list of Java extensions

### PR DESCRIPTION
**Pull request by bl-ue**
See https://github.com/search?q=extension%3Ajav&type=Code for proof.

Also see https://github.com/microsoft/vscode/blob/94c9ea46838a9a619aeafb7e8afd1170c967bb55/extensions/java/package.json#L18-L21.

## Checklist:

- [x] **I am associating a language with a new file extension.**
  - [x] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      https://github.com/search?q=extension%3Ajav&type=Code
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am adding a new language.**
  - [ ] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  
  - [ ] I have included a syntax highlighting grammar: https://github-lightshow.herokuapp.com/
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

- [ ] **I am fixing a misclassified language**
  - [ ] I have included a new sample for the misclassified language:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am changing the source of a syntax highlighting grammar**
  
  - Old: https://github-lightshow.herokuapp.com/
  - New: https://github-lightshow.herokuapp.com/

- [ ] **I am updating a grammar submodule**
  

- [ ] **I am adding new or changing current functionality**
  
  - [ ] I have added or updated the tests for the new or changed functionality.

- [ ] **I am changing the color associated with a language**
  
  - [ ] I have obtained agreement from the wider language community on this color change.
    - [URL to public discussion]
    - [Optional: URL to official branding guidelines for the language]

### CODE REVIEW

**Review by lildude — CHANGES_REQUESTED** [review]
Please follow the contributing guidelines for adding an extension and put back and fill in the original PR template.

**Comment by bl-ue** [comment]
Done.

**Comment by bl-ue** [comment]
The contributing guidlines for adding a new extension say this:

>Add at least one sample for your extension to the samples directory in the correct subdirectory. We prefer examples of real-world code showing common usage. The more representative of the structure of the language, the better.

but there's no `.jav` code that isn't identical to `.java` code because they're synonymous extensions.

**Comment by lildude** [comment]
We still need a sample as it's used to train the classifier in the event another language with a `.jav` extension is added in the future.

**Comment by lildude** [comment]
Thinking about it, nevermind. I think we'll be ok without a sample.

**Comment by bl-ue** [comment]
ping @lildude can we merge? :)

**Review by lildude — APPROVED** [review]

**Pull request merged**
