### PR TITLE
Update color for Groovy to match the logo on the website

### PR DESCRIPTION
**Pull request by yogurtearl**
Change color for Groovy Language

Current: `#e69f56`
Proposed: `#4298b8`

From the Groovy logo on the groovy website:
https://github.com/apache/groovy-website/blob/f51c26b05f90edc05873a2a1ec676a8f58fe4f7c/site/src/site/assets/css/style.css#L487

Current Color:
image

Proposed Color in taken from the website:
image

- [x] **I am changing the color associated with a language**
  
  - [x] I have obtained agreement from the wider language community on this color change.
    - [Thread on groovy mailing list](https://lists.apache.org/thread.html/r1a75b0955b5cfb1119b944f76ef65d8533ea5edbb57fec531c1e74cc%40%3Cusers.groovy.apache.org%3E) 
    - See color on https://groovy-lang.org/

### CODE REVIEW

**Comment by jnorthr** [comment]
cool idea - just do it !

**Comment by lildude** [comment]
If https://github.com/github/linguist/pull/5384 gets enough community support it'll bring Java and Groovy closer to each other again 😁

**Comment by GavinRay97** [comment]
> If #5384 gets enough community support it'll bring Java and Groovy closer to each other again 😁

If not coordinated -- that is absolutely hilarious.
Please pick one or the other I guess haha.

**Comment by lildude** [comment]
I'm going to accept this colour change and lock comments on this issue once merged. If there are any disagreements or opinions about the colour change, they need to be discussed in the community discussion linked in the OP and not in this repo as this is a community requested and supported change, not a GitHub/Linguist initiated change.

Note, I'll accept the Java colour change in https://github.com/github/linguist/pull/5384 too under the same circumstances once it gets a community-based discussion link (/cc @ZacSweers as the author of that PR). When that happens both languages will still have similar looking colours:

### Old

- Groovy: `#e69f56`
- Java: `#b07219`

### New

- Groovy: `#4298b8`
- Java: `#2a6277`

**Review by lildude — APPROVED** [review]

**Comment by GavinRay97** [comment]
Ruh-roh

**Pull request merged**
