### PR TITLE
Herb

### PR DESCRIPTION
**Pull request by yoidog**
## Description
Hello, this pull requests adds support for my own language [Herb](https://github.com/yoidog/Herb) with the extension `.herb`, this is my first time and i'm excited, thanks. 😄

## Checklist:
- [x] **I am adding language support with a new file extension.**
- [x] The new extension is used in hundreds of repositories on GitHub.com.
  - Search results for the extension:
    - https://github.com/search?q=extension%3Aherb+NOT+XML+NOT+HTML&type=Code
- [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [https://github.com/yoidog/herbSamples/tree/main/Samples](https://github.com/yoidog/herbSamples/tree/main/Samples)
    - Sample license(s):
       - [https://github.com/yoidog/herbSamples/blob/main/license](https://github.com/yoidog/herbSamples/blob/main/license)
  - [x] I have included a syntax highlighting grammar: [https://github.com/yoidog/herb-syntax-highlighting](https://github.com/yoidog/herb-syntax-highlighting)

### CODE REVIEW

**Comment by Nixinova** [comment]
> The new extension is used in hundreds of repositories on GitHub.com (they aren't Herb language.)

This checkbox is a requirement to being added to Linguist.
The language does not have usage on GitHub so this PR should be closed until it does.

**Comment by yoidog** [comment]
> ## Description
> Hello, this pull requests adds support for my own language [Herb](https://github.com/yoidog/Herb) with the extension `.herb`, this is my first time and i'm excited, thanks. 😄
> 
> ## Checklist:
> * [x]  **I am adding language support with a new file extension.**
> * [x]  The new extension is used in hundreds of repositories on GitHub.com.
>   
>   * Search results for the extension:
>     
>     * https://github.com/search?q=extension%3Aherb+not+xml&type=Code
> * [x]  I have included a real-world usage sample for all extensions added in this PR:
>   
>   * Sample source(s):
>     
>     * https://github.com/yoidog/herbSamples/tree/main/Samples
>   * Sample license(s):
>     
>     * https://github.com/yoidog/herbSamples/blob/main/license
>   * [x]  I have included a syntax highlighting grammar: https://github.com/yoidog/herb-syntax-highlighting

**Comment by yoidog** [comment]
> > The new extension is used in hundreds of repositories on GitHub.com (they aren't Herb language.)
> 
> This checkbox is a requirement to being added to Linguist. The language does not have usage on GitHub so this PR should be closed until it does.

I checked it!

**Comment by Nixinova** [comment]
> I checked it!

Just checking it doesn't make it true.
The language needs to be used in hundreds of repositories and there are only 35 .herb files, which is not enough for inclusion.

**Comment by lildude** [comment]
As pointed out by @Nixinova, usage is no where near meeting our [documented requirements](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language) or even the [temporarily relaxed requirements](https://github.com/github/linguist/issues/5756) so I'm closing this PR. Please feel free to create a new one when popularity meets our requirements in future.

**Pull request closed without merging**
