### PR TITLE
Add RTF grammar

### PR DESCRIPTION
**Pull request by nwhetsell**
This pull request adds a grammar for RTF files.

~~**NOTE:** I haven’t been able to run script/update-ids due to issue #4449.~~

## Checklist:
- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      -  https://github.com/search?q=extension%3Artf+NOT+nothack
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample sources:
      - https://github.com/Microsoft/testfx/blob/master/Templates/CSharp/Desktop/DesktopTemplateLicense.rtf
      - https://github.com/apple/foundationdb/blob/master/packaging/msi/LICENSE.rtf
    - Sample licenses:
      - https://github.com/Microsoft/testfx/blob/master/LICENSE (MIT)
      - https://github.com/apple/foundationdb/blob/master/LICENSE (Apache 2.0)
  - [x] I have included a syntax highlighting grammar: https://github-lightshow.herokuapp.com/?utf8=✓&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fnwhetsell%2Flanguage-rtf%2Fmaster%2Fgrammars%2Frtf.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fapple%2Ffoundationdb%2Fmaster%2Fpackaging%2Fmsi%2FLICENSE.rtf
  - [x] I have updated the heuristics to distinguish my language from others using the same extension. (N/A)

### CODE REVIEW

**Comment by Alhadis** [comment]
Shouldn't we have registered this using its full name, `Rich Text Format`?

**Comment by lildude** [comment]
Ooops. Yes, that makes sense. Didn't even think of it. 🤦‍♂️

**Comment by lildude** [comment]
I'll do that now.

**Comment by lildude** [comment]
@Alhadis done - https://github.com/github/linguist/pull/4456

**Pull request merged**
