### PR TITLE
Add Support for EBNF

### PR DESCRIPTION
**Pull request by sanssecours**
Hi,

this pull request adds support for the [Extended Backus–Naur form](https://en.wikipedia.org/wiki/Extended_Backus–Naur_form). [Here](https://github.com/search?utf8=✓&q=extension%3Aebnf+NOT+nothack&type=Code&ref=searchresults) is a link that shows the usage of the language at GitHub.

If I should change anything in this pull request, then please just comment below. Thank you.

Kind regards,
  René

### CODE REVIEW

**Comment by Alhadis** [comment]
@sanssecours You'll now need to rebase against master and regenerate the language IDs, as well as apply any revisions requested earlier.

**Comment by sanssecours** [comment]
> @sanssecours You'll now need to rebase against master and regenerate the language IDs, as well as apply any revisions requested earlier.

Okay – The updated code should be ready now.

**Comment by Alhadis** [comment]
LGTM. Should I merge, @arfon?

**Comment by arfon** [comment]
👍 thanks

**Pull request merged**
