### PR TITLE
Add .cnf to INI

### PR DESCRIPTION
**Pull request by eggplants**
## Description

I would like to add `.cnf` extension as INI.

`.cnf` is used for [MySQL Option File](https://dev.mysql.com/doc/refman/8.0/en/option-files.html#option-file-syntax) and [OpenSSL CONF library configuration file](https://www.openssl.org/docs/manmaster/man5/config.html).

## Checklist:
- [x] **I am associating a language with a new file extension.**
  - [x] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      - https://github.com/search?q=path%3A*.cnf+mysqld+NOT+nothack&type=code
    - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - <https://github.com/mysql/mysql-shell/blob/037114f/unittest/data/config/my.cnf>
        - `GNU General Public License, version 2.0`
      - <https://github.com/nodejs/node/blob/66da32c/deps/openssl/openssl/apps/openssl.cnf>
        - `MIT License` 
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

### CODE REVIEW

**Review by Alhadis — APPROVED** [review]
Distribution appears to check out (searching for `.cnf` files yields [~109k results](https://github.com/search?q=path%3A**%2F%3F*.cnf&type=code&p=1), most of which appear to be MySQL configs.

**Review by lildude — CHANGES_REQUESTED** [review]
Can you please add another `.cnf` sample, maybe one demonstrating the OpenSSL conf file? This one sample you've added seems to be influencing the classifier such that it is now detecting a `.pro` file as INI:

```
Proguard/proguard-rules2.pro BAD (INI)
```

Hopefully another sample will be enough to correct this 🤞

**Comment by lildude** [comment]
😢 that didn't do the trick so I've bumped the number of allowed failures.

**Review by lildude — APPROVED** [review]

**Comment by lildude** [comment]
> Please ⌘+R my memory: does Linguist's classifier take comments into consideration when analysing keyword frequency?

Yes, and thanks to the tokenizer, it detects it as a comment so ignores things after the hash when classifying. With `LINGUIST_DEBUG=2` you'll see lines like this (I forced this by adding `.cnf` to the Proguard entry):

```console
$ LINGUIST_DEBUG=2 bundle exec bin/github-linguist samples/INI/my.cnf
samples/INI/my.cnf: 107 lines (93 sloc)
  type:      Text
  mime type: text/plain
                    #       INI  Proguard
               #   19    29.260         -
              ##    1         -     4.395
               -   18         -    28.547
              .7    1     6.651         -
            .log    1     6.651         -
            .pid    1     6.651         -
           .sock    3    23.248         -
               /   28   302.228         -
               :    2         -     1.737
               ;    2         -     2.936
               =   47   612.767         -
          AES256    1     6.651         -
               C    1     7.344         -
     CAMELLIA256    1     6.651         -
        COMMENT#   28     1.506         -
        COMMENT;    1     8.848         -
CaseSensitiveOpt    1     6.651         -
[...]
win_path_with_po    1     6.651         -
       INI =  -2044.596 +  -5.312 =  -2049.908
  Proguard =  -4755.497 +  -6.852 =  -4762.349
  language:  INI
$
```

Stripping the GPL license comment makes no difference:

```console
$ LINGUIST_DEBUG=2 bundle exec bin/github-linguist samples/INI/my.cnf
samples/INI/my.cnf: 107 lines (93 sloc)
  type:      Text
  mime type: text/plain
                    #       INI  Proguard
               #   19    29.260         -
              ##    1         -     4.395
               -   18         -    28.547
              .7    1     6.651         -
            .log    1     6.651         -
            .pid    1     6.651         -
           .sock    3    23.248         -
               /   28   302.228         -
               :    2         -     1.737
               ;    2         -     2.936
               =   47   612.767         -
          AES256    1     6.651         -
               C    1     7.344         -
     CAMELLIA256    1     6.651         -
        COMMENT#   28     1.506         -
        COMMENT;    1     8.848         -
CaseSensitiveOpt    1     6.651         -
[...]
win_path_with_po    1     6.651         -
       INI =  -2044.596 +  -5.312 =  -2049.908
  Proguard =  -4755.497 +  -6.852 =  -4762.349
  language:  INI
$
```

> The problematic sample you mentioned earlier began with the GPL, so it left me wondering…

Yeah, this shouldn't make a difference as pointed out above, but I removed the GPL license text and tested again locally and it didn't make a difference. I still got the same failure that needed the number bump.

**Pull request merged**
