### PR TITLE
Add Malbolge

### PR DESCRIPTION
**Pull request by KrzysztofSzewczyk**
C'mon, how didn't Linguist have the hardest programming language in existence implemented yet?

## Description
This pull request is adding Malbolge support to linguist.

## Checklist:
- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com - well, yes, but technically there is no way to prove it - look below.
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Inside the repository
  
  - [x] I have included a syntax highlighting grammar: https://github-lightshow.herokuapp.com/ (I didn't, because it doesn't apply)
  - [x] I have updated the heuristics to distinguish my language from others using the same extension. (no such language)

Malbolge is really, really widely known, but it's very hard to search for Malbolge programs on github. If some helpful soul wants to pass this pull request, here's some additional info:

Malbolge program can consist ONLY of characters from this xlat, from official interpreter:

```

const char xlat1[] =
  "+b(29e*j1VMEKLyC})8&m#~W>qxdRp0wkrUo[D7,XTcA\"lI"
  ".v%{gJh4G\\-=O@5`_3i<?Z';FNQuY]szf$!BS/|t:Pn6^Ha";

```

...and it has extension of `.mb`

The language is widely known:

1. [TIO.run supports it](https://tio.run/#malbolge)
2. [45 answers on codegolf](https://codegolf.stackexchange.com/search?q=Malbolge+is%3Aanswer) (very small amount because Malbolge is, let's say, inpractical)
3. It has [wikipedia page](https://en.wikipedia.org/wiki/Malbolge)
4. If you haven't heard of Malbolge ever before I bet you haven't visited any social network and googled since then.

picture

PS: Samples are released on GPLv3 license.

### CODE REVIEW

**Comment by KrzysztofSzewczyk** [comment]
Update: I've shaved samples directory by a couple of megabytes, because this many samples aren't needed anyway.

**Comment by KrzysztofSzewczyk** [comment]
@pchaigno Could I get a review?

**Comment by KrzysztofSzewczyk** [comment]
Done, the PR is building now.

**Comment by KrzysztofSzewczyk** [comment]
@lildude @Alhadis could I get a review?

**Comment by Alhadis** [comment]
> Malbolge is really, really widely used

I'd be interested in seeing your source for this claim.

Like any hacker who's read an XKCD strip, I'm aware of Malbolge and the absurd difficulty it imposes on people trying to code in it. Therefore, I find it impossible that the language is "widely used" for anything other than novelty scripting and golfing.

**Comment by KrzysztofSzewczyk** [comment]
The same goes for Brainfuck, but you (the Linguist contributors) decided to pull it anyway.

**Comment by Alhadis** [comment]
There are currently [325 Brainfuck repositories](https://github.com/search?q=language%3ABrainfuck+NOT+nothack&type=Repositories) indexed on GitHub, so it fulfils our usage criteria.

**Comment by KrzysztofSzewczyk** [comment]
@Alhadis we're not able to index the Malbolge ones, because we can't really search for just .mb extension and it's hard to search fromo characters in xlat I provided.

**Comment by Alhadis** [comment]
Then how were you able to deduce that Malbolge is, as you say, *"really, really widely used"*? Unless you meant to say *"really, really widely **known**"*, which is different to being widely in-use. 😉

For the record,  out of [81,681 indexed `.mb` files](https://github.com/search?q=extension%3Amb+NOT+nothack&type=Code) I was able to harvest [2,785 results](https://github.com/Alhadis/Silos/blob/mb/urls.log#L2785), most of which turned out to be binary. Those that weren't were an assortment of [random text formats](https://github.com/Alhadis/Silos/tree/mb/files), with the only Malbolge files being a pair of [Hello](https://github.com/Alhadis/Silos/blob/c0989d628f0b8f0d54500358f7ecee93844c609a/files/hello-world.mb) [World](https://github.com/Alhadis/Silos/blob/c0989d628f0b8f0d54500358f7ecee93844c609a/files/helloworld2.mb) files. Which, to be frank, is exactly what I expected to find.

If you're curious, the script I used to collate search results is [here](https://github.com/Alhadis/Harvester).

**Comment by KrzysztofSzewczyk** [comment]
That's a derp moment. I meant "known".

**Comment by Alhadis** [comment]
> BTW, the script seems kinda wrong, because it didn't index [this](https://github.com/KrzysztofSzewczyk/codegolf-submissions) at all.

For reasons that are neither easy to explain nor relevant, the script is limited in the number of files it can collect, and which subsets it has access to. Suffice to say I didn't mean to provide an exhaustive list of files, but rather to convey the lack of real world Malbolge usage as a response to your (apparently miscommunicated) argument about the language having widespread use.

To be eligible for recognition on GitHub, a language must have sufficient usage as observed across public repositories. Strictly speaking, we don't determine eligibility based solely on notability. Heck, notability and popularity typically go hand-in-hand most of the time. For Malbolge's case, however, it's renown is founded purely on its gimmick of being impossible to read or write.

I hope this is making sense.

**Comment by KrzysztofSzewczyk** [comment]
If this PR is not passing, please close it.

**Pull request closed without merging**
