### PR TITLE
Language recognition with file path pattern (regex)

### PR DESCRIPTION
**Pull request by Varun-garg**
Fixes vscode config json files on github. Github shows errors for comments in vscode files. This can be fixed by classifying them as jsonc. broken vscode config files are included.

## Description
Added a feature for language recognition with file path pattern (regex). example pattern: `'\.vscode\/.*\.json$'`

## Checklist:
- [x] **I am fixing a misclassified language**
  - [x] I have included a new sample for the misclassified language:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

### CODE REVIEW

**Comment by Varun-garg** [comment]
Heu @lildude , thanks for follow up, won't extension take precedence before heuristics?

**Comment by lildude** [comment]
> won't extension take precedence before heuristics?

Yup, that's why we have heuristics 😄 - they're used to differentiate one or more uses of the same extension. So in this case, the `.json` extension would need to be added to "JSON with Comments" (it's already associated with JSON) and then a heuristic is needed to differentiate the two.

**Comment by Varun-garg** [comment]
Ah, regex to detect comments in json is hard to implement for me.

**Comment by Varun-garg** [comment]
@lildude Sorry for replying late. On second thoughts I was wondering if we are going to scan if the json file has comments and switch to jsonc, we are basically allowing all json files to have comments (unlike hardcoded files / patterns). Can't we just enable comments in json and ditch jsonc?

**Pull request closed without merging**
