### PR TITLE
Added NetLinx language.

### PR DESCRIPTION
**Pull request by amclain**
NetLinx is a language developed by [AMX](http://amx.com/) for programming control system hardware.

[NetLinx code in the wild:](https://github.com/search?q=extension%3Aaxs+extension%3Aaxi+NOT+nothack&ref=searchresults&type=Code&utf8=%E2%9C%93)
2,165 code results

### CODE REVIEW

**Comment by Phasesaber** [comment]
Over 300 added since then, I think there are enough people using it to add!

**Comment by pchaigno** [comment]
@amclain I'm not from GitHub but I can help prepare the pull request for review. You should add sample files for the two `NetLinx+ERB` extensions? Could you also update the branch?

**Comment by amclain** [comment]
@pchaigno I've added the samples and updated the branch. Thanks!

**Comment by pchaigno** [comment]
@amclain Looks good to me. You just have to wait for a reviewer from GitHub now ;)

**Pull request merged**
