### PR TITLE
Add Pony language

### PR DESCRIPTION
**Pull request by manveru**
https://github.com/search?utf8=%E2%9C%93&q=extension%3Apony+new&type=Code&ref=searchresults

### CODE REVIEW

**Comment by jemc** [comment]
+1 - It would be great if my pony projects could start seeing syntax highlighting, especially https://github.com/jemc/pony-zmq, which is becoming fairly complex.

In terms of adoption, it's also worth noting that [exercism.io](https://github.com/jemc/pony-zmq) will soon have [a Pony track of exercises](https://github.com/exercism/xpony).

**Comment by Asmod4n** [comment]
+1 - Pony is one of the more promising languages around.

**Comment by arfon** [comment]
Hi @manveru. Thanks for opening up this Pull Request. As per the [contributing guidelines](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language) we try to only add new languages to Linguist when they have a significant level of adoption (hundreds of repositories) and by the looks of things there are currently only [~200 `.pony` files on GitHub](https://github.com/search?utf8=%E2%9C%93&q=extension%3Apony+new&type=Code&ref=searchresults).

Please feel free to open a new PR in the future as adoption increases.

**Comment by darach** [comment]
1. Linguist is also used by libraries.io. So linguist is now a point of bottleneck
2. With a fast growing community we would like to see syntax highlighted code. It's not a big ask
3. With almost 1000 followers on the core ponyc repo, its already evident that its popular enough
4. The quantity of repositories is not a good measure of significance for a new language, or its quality.
5. The sooner highlighting and libraries.io is in place, the better for tracking adoption rates.

Please reconsider the guidelines for pony and other programming languages that are clearly not hobby projects or side projects for inclusion in github as soon as possible or improve the contributing guidelines so that false measures of significance ( quantity, LOC, number of files ) don't preclude adding languages at an early stage of adoption.

It would be more polite, and a far better way to support new developer communities who can then benefit simply by levelling the field and offering our users the same experience on github as established languages. The lack of highlighting may actually hurt, hinder or diminish adoption rates.

As such, github is offering a disservice to its users, many of whom are polyglots, at the cost of them,
the new languages themselves, and commercial github users ( such as me ) with public and private repos where all the languages I use benefit from highlighting.

@manveru Thanks for the PR. You're a champion! :)

@arfon Please reconsider

**Comment by andrew** [comment]
@manveru @darach I'd be happy to merge a pr of the changes to `lib/linguist/languages.yml` to https://github.com/librariesio/languages to enable some Pony bits on https://libraries.io, of course once GitHub starts marking repos languages as `Pony` everything will start working automatically.

**Comment by darach** [comment]
Thanks @andrew. Pints soon!

**Comment by sylvanc** [comment]
+1 :)

**Comment by SeanTAllen** [comment]
+1.

Well said @darach.

**Comment by jonas-l** [comment]
+1

**Comment by kamilchm** [comment]
:+1:

**Comment by jemc** [comment]
CI failure looks unrelated ("An error occurred while installing byebug (7.0.0), and Bundler cannot continue").

**Comment by arfon** [comment]
Thanks for the comment @darach. 

I'm not sure that I agree with your comments about 'false measures of significance' but clearly Pony us gaining some significant community interest and so I'm happy to revisit this.

> CI failure looks unrelated ("An error occurred while installing byebug (7.0.0), and Bundler cannot continue").

@jemc yep, let's get this merged and I'll try and dig into the Travis stuff later.

This change will go live in the next release of Linguist (next week some time).

**Comment by darach** [comment]
@arfon +1

Tip of the hat to you for reopening and reconsidering. I do hope the contribution policy can be adapted to clarify what is reasonable and what isn't such that there's no ( or at least less ) ambiguity on what determines significance. Clearly the maintenance burden of a gazillion hobby projects isn't tenable or scalable but there needs to be some wiggle room for serious and promising languages like pony who may be light on significance by a single measure alone.

**Comment by lispmeister** [comment]
+1
I think we'll see some significant adoption soon.

**Comment by wilmerwalton** [comment]
+1 - Pony compares nicely with Go, Rust, OCaml, and Erlang. It is the highest performing actor language, while eliminating manual actor management.

**Pull request merged**
