### PR TITLE
Add rebar-related files as erlang.

### PR DESCRIPTION
**Pull request by dpiddy**
`rebar.config` and `rebar.lock`/`rebar.config.lock` are akin to `Gemfile` and `Gemfile.lock` for Erlang, used by the [rebar](http://www.rebar3.org/) tool.

### CODE REVIEW

**Comment by gjtorikian** [comment]
Looks like you'll definitely need to commit sample files, according to the test:

> Missing sample in "samples/Erlang/filenames/rebar.lock"

The shell error might be fixed by https://github.com/github/linguist/pull/2299; I wouldn't worry about it for this PR.

**Comment by dpiddy** [comment]
Added them. Sorry about that, I tried running tests locally but maybe got sidetracked by the shell failure.

**Comment by arfon** [comment]
@dpiddy - would you mind rebasing against `master`? The build is now fixed up.

**Comment by dpiddy** [comment]
Done!

**Comment by arfon** [comment]
@dpiddy - should we add `rebar.config.lock` also? There looks to be a bunch of these: https://github.com/search?l=&q=require+filename%3Arebar.lock&ref=advsearch&type=Code&utf8=%E2%9C%93

**Comment by dpiddy** [comment]
@arfon yeah, added. Getting failures like this now:

```
  1) Failure:
TestClassifier#test_classify_ambiguous_languages [/Users/dan/Projects/ruby/linguist/test/test_classifier.rb:53]:
/Users/dan/Projects/ruby/linguist/samples/Erlang/filenames/rebar.config.lock
[["JSON", -2112.7576908263964], ["Erlang", -2501.5084453755526]].
Expected: "Erlang"
  Actual: "JSON"
```

will try and fix but any tips appreciated.

**Comment by dpiddy** [comment]
Well, travis seems to be fine with it so maybe not an issue.

**Comment by pchaigno** [comment]
> Well, travis seems to be fine with it so maybe not an issue.

@dpiddy That's because #2299 was just merged ;) (see @gjtorikian's comment)

**Comment by dpiddy** [comment]
@pchaigno I meant the classifier failure I pasted above. I'm getting these two failures locally but like I said travis seems ok:

```
  1) Failure:
TestClassifier#test_classify_ambiguous_languages [/Users/dan/Projects/ruby/linguist/test/test_classifier.rb:53]:
/Users/dan/Projects/ruby/linguist/samples/Erlang/filenames/rebar.config.lock
[["JSON", -2112.7576908263964], ["Erlang", -2501.5084453755526]].
Expected: "Erlang"
  Actual: "JSON"

  2) Failure:
TestBlob#test_language [/Users/dan/Projects/ruby/linguist/test/test_blob.rb:519]:
rebar.config.lock.
Expected: "Erlang"
  Actual: "JSON"
```

**Comment by pchaigno** [comment]
Oh, okay. That's usually because you need to regenerate the samples. Try `bundle exec rake samples` in your local copy.

**Comment by dpiddy** [comment]
Thanks, that did it! All good now.

**Comment by arfon** [comment]
:+1: thanks @dpiddy

**Pull request merged**
