### PR TITLE
Switch to MagicPython for Python sources

### LINKED ISSUE #2691: Drop language-python and adopt MagicPython
https://github.com/MagicStack/MagicPython

this would fix #2660 without having to wait for language-python

### PR DESCRIPTION
**Pull request by berdario**
This might fix #2691 and #2660

### CODE REVIEW

**Comment by arfon** [comment]
@berdario - would you mind agreeing to the CLA please?

**Comment by berdario** [comment]
Done.

Let me know if this works as expected: there doesn't seem to be integration tests with the grammars, and the only instructions for contributors mention to check if the grammar is working properly in the editor of our choice (and that's obviously the case)

**Comment by arfon** [comment]
@berdario - thanks! Would you mind showing the improvements using Lightshow? https://github-lightshow.herokuapp.com/

**Comment by berdario** [comment]
Last time I tried, Lightshow is non functional.

I'll try again

**Comment by berdario** [comment]
Yes, Lightshow is broken in some way:

https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2FMagicStack%2FMagicPython%2Fmaster%2Fgrammars%2FMagicPython.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fberdario%2Fresumable-urlretrieve%2Fmaster%2Fresumable%2F__init__.py&code=

It believes that the grammar is a YAML file, while instead it's in CSON format. And obviously the grammar works just fine in my Atom editor

([this is the wrong rendering](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fatom%2Flanguage-python%2Fmaster%2Fgrammars%2Fpython.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fberdario%2Fresumable-urlretrieve%2Fmaster%2Fresumable%2F__init__.py&code=) with the old grammar, btw)

**Comment by arfon** [comment]
@aroben - any ideas what is going on here?

**Comment by aroben** [comment]
Yeah this is a bug in Lightshow. It does some very dumb detection to try to figure out what format a grammar is in. It expects CSON grammars to start with a single or double quote character, and since this one doesn't it's falling into the YAML code path.

**Comment by pchaigno** [comment]
@aroben Wouldn't relying on the extension work better?

**Comment by aroben** [comment]
Yes, that would definitely be better in this case. We have to do some content detection when the grammar is POSTed from the textarea, but even then we could try parsing in all formats and return the first one that works.

**Comment by berdario** [comment]
People that are going to paste a grammar, know in which syntax it has been written in, so I'd rather add a drop-down select, rather than guessing

**Comment by pchaigno** [comment]
I agree that a drop-down select might be simpler for POSTed grammars :+1: 
If the user doesn't select anything, we can always default to more sophisticated approaches.

Any way Lightshow could be decorrelated from the parsing code and published in open source?
It would make it easier to track issues and test improvement propositions :smiley:

**Comment by aroben** [comment]
> Any way Lightshow could be decorrelated from the parsing code and published
> in open source?
> It would make it easier to track issues and test improvement propositions

I'll try to think of ways to do that.

**Comment by kirbyfan64** [comment]
Bump? It'd be really cool if this got merged soon...

**Comment by pchaigno** [comment]
I took @berdario's Lightshow example and changed the grammar to go around the bug - I removed the first comment line, added double quotes and made it [a Gist](https://gist.githubusercontent.com/pchaigno/1252e31c6675fd63494b/raw/32ea2069d26ff32a8b609c984cd8bc88cc27dd39/MagicPython.cson). We can now see how MagicPython improves syntax highlighting:
- [Lightshow example with the current grammar, language-python](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fatom%2Flanguage-python%2Fmaster%2Fgrammars%2Fpython.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fberdario%2Fresumable-urlretrieve%2Fmaster%2Fresumable%2F__init__.py&code=);
- [Lightshow example with MagicPython](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgist.githubusercontent.com%2Fpchaigno%2F1252e31c6675fd63494b%2Fraw%2F32ea2069d26ff32a8b609c984cd8bc88cc27dd39%2FMagicPython.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fberdario%2Fresumable-urlretrieve%2Fmaster%2Fresumable%2F__init__.py&code=).

Clearly, MagicPython does a better job at highlighting this file.

@aroben Any news on the bug and/or making Lightshow open source?

**Comment by arfon** [comment]
Replaced by #2796

**Comment by aroben** [comment]
> @aroben Any news on the bug and/or making Lightshow open source?

No news, but I did file an issue to track this internally.

**Comment by pchaigno** [comment]
Cool, thanks!

**Pull request closed without merging**
