### PR TITLE
Add Wren

### PR DESCRIPTION
**Pull request by whmsft**
## Description

Adds [Wren](https://wren.io) programming language with the `.wren` extension 

I found this language is used by a good amount of people (it's even in the [tic-80](https://tic80.com) console) so why not in Linguist!

## Checklist:
- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3Awren+KEYWORDS+NOT+nothack
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - https://github.com/oschettler/lines/blob/6fd7a4fdebf0267c3c2ca185519fcd46a9e4aafc/main.wren
    - Sample license(s): MIT
  - [x] I have included a syntax highlighting grammar: [[URL to grammar repo]](https://github.com/Nelarius/vscode-wren)
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

### CODE REVIEW

**Review by lildude — CHANGES_REQUESTED** [review]
Please follow the instructions for adding a new language detailed in the CONTRIBUTING.md

**Comment by whmsft** [comment]
> 

what am i missing?

**Comment by whmsft** [comment]
now i have added `language_id`, now anything left?

**Comment by whmsft** [comment]
I have added to `grammars.yml` now anything?

**Review by lildude — CHANGES_REQUESTED** [review]
> what am i missing?

A grammar for the syntax highlighting. The license for it. The vendor/README.md update for the language and grammar. The fact that you've added a "hello world" sample when the guide clearly asks you not to.

> now i have added `language_id`, now anything left?

As above.

> I have added to `grammars.yml` now anything?

Now you're just guessing and fumbling in the dark 😁 - that dart grammar most definitely doesn't provide syntax highlighting for Wren using the `source.wren` scope. 

Please read the documents and add a grammar properly - you can re-use a grammar if it provides the syntax highlighting you want. Save yourself some time by running the tests locally too. 😉

**Comment by whmsft** [comment]
It was my first time doing something like this.. 
> you're just guessing and fumbling in the dark 😁

Yep 😅😳

> Please read the documents and add a grammar properly - you can re-use a grammar if it provides the syntax highlighting you want.

OK i will try doing it some other time...

**Comment by lildude** [comment]
https://github.com/Nelarius/vscode-wren should do the trick for syntax highlighting.

**Review by lildude — APPROVED** [review]

**Comment by whmsft** [comment]
Thanks!

**Comment by whmsft** [comment]
Well, how much time does it really take to show up on github.com?

**Comment by lildude** [comment]
You should see it now (I've just deployed), however it'll will require a new push to a repo for it to detected on that repo.

**Comment by whmsft** [comment]
Ok thanks!

**Comment by ConfusedSky** [comment]
This is awesome! It's funny how I was literally looking into how to add wren as a language to github, and it looks like the work has quite literally *just* been done.

**Pull request merged**
