### PR TITLE
add .boot to clojure extensions

### PR DESCRIPTION
**Pull request by shaunlebron**
[Boot](http://boot-clj.com/) is a build tool for clojure.  The `.boot` files are just clojure files though.  Would be nice to have those highlighted accordingly on github.

### CODE REVIEW

**Comment by pchaigno** [comment]
The Travis build is failing because the first extension corresponds to the primary extension. Only the following extensions should be sorted. So, `.boot` should come after `.clj`.

**Comment by shaunlebron** [comment]
thanks @pchaigno :)

**Comment by pchaigno** [comment]
Could you also add a sample for this extension in `samples/Clojure/`?

**Comment by shaunlebron** [comment]
added a sample

**Comment by arfon** [comment]
:+1: thanks @shaunlebron and @pchaigno. This should be live on GitHub next week sometime.

**Comment by shaunlebron** [comment]
cool, thanks @arfon

**Pull request merged**
