### PR TITLE
Add syntax highlighting for svelte

### LINKED ISSUE #4321: Syntax Highlighting support for Svelte.
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

Syntax Highlighting isn't supported for [Svelte](https://svelte.technology/).

### Last modified on:
2018-11-11

### Expected language:
Svelte

### Detected language:
None

### PR DESCRIPTION
**Pull request by umanghome**
Resolves #4321 by adding syntax highlighting to .svelte files. Reopening after changes made to #4323.

## Checklist:

- [ ] **I am associating a language with a new file extension.**
  - [ ] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      
      - https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?q=extension%3Asvelte+NOT+nothack&type=Code
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample license(s):
		- `TodoMVC.svelte`: Unlicensed
  
  - [x] I have included a syntax highlighting grammar: https://github-lightshow.herokuapp.com/
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

- [ ] **I am fixing a misclassified language**
  - [ ] I have included a new sample for the misclassified language:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am changing the source of a syntax highlighting grammar**
  
  - Old: https://github-lightshow.herokuapp.com/
  - New: https://github-lightshow.herokuapp.com/

- [ ] **I am updating a grammar submodule**
  

- [ ] **I am adding new or changing current functionality**
  
  - [ ] I have added or updated the tests for the new or changed functionality.

- [ ] **I am changing the color associated with a language**
  
  - [ ] I have obtained agreement from the wider language community on this color change.
    - [URL to public discussion]
    - [Optional: URL to official branding guidelines for the language]

### CODE REVIEW

**Comment by lildude** [comment]
As just discovered and mentioned in https://github.com/github/linguist/pull/4481, Travis CI doesn't support draft PRs yet, so once this is ready to go, you'll either need to push another commit after making this a real PR or we'll need to close and re-open it to trigger the build.

**Comment by umanghome** [comment]
This PR should be squash-merged.

**Comment by umanghome** [comment]
@pchaigno I've updated the PR, let me know if it's still missing anything.

**Comment by umanghome** [comment]
@lildude I've added another example. Let me know if it's still trivial, I'll ask someone from the community to add one.

**Comment by lildude** [comment]
@umanghome looks good to me. Thanks.

**Pull request merged**
