### PR TITLE
Create association with OpenEdge .w files

### PR DESCRIPTION
**Pull request by MaickelHubner**

### CODE REVIEW

**Comment by lildude** [comment]
Please merge this into https://github.com/github/linguist/pull/3647 or vice-versa so everything is in a single PR.

**Comment by MaickelHubner** [comment]
@lildude how I do this?

**Comment by lildude** [comment]
As this PR has more changes than https://github.com/github/linguist/pull/3647, the easiest thing to do is merge your `patch-1` branch into your `master` branch.

You can do this from the CLI:

```
$ git clone https://github.com/MaickelHubner/linguist
$ git merge patch-1
$ git push origin master
```

Or create yourself a pull request within your own repo ([this link](https://github.com/MaickelHubner/linguist/compare/master...MaickelHubner:patch-1?expand=1) will start the process for you) and merge all via the GitHub UI.

You should find this PR will update to reflect the changes from both PRs once your master branch has been updated.

You can then safely delete the `patch-1` branch.

**Comment by MaickelHubner** [comment]
@lildude done

**Comment by lildude** [comment]
Nice!! Thanks.  One more request: are you able to cut down the sized of the samples or find smaller, yet quite diverse samples?  The ones in this PR are pretty big and contain a fair amount of duplication within the basic structure - for example, all those different menu options within the `menu.w`

**Comment by MaickelHubner** [comment]
@lildude in my MHMoney directory (https://github.com/MaickelHubner/MHMoney) there are several .w programs. You can search for what you find most appropriate in terms of size to use.
Hugs

**Comment by lildude** [comment]
Little nudge @MaickelHubner... as you know your own code better than I do, and given you have a _lot_ of files in that repo, it's best if you picked smaller and more diverse examples than for me to attempt it.

Also, I can't find a license for any of your code. Linguist can only accept samples licensed under one of these licenses https://github.com/github/linguist/blob/master/vendor/licenses/config.yml#L1-L12

**Comment by MaickelHubner** [comment]
@lildude, attached a very basic file
[test-win.zip](https://github.com/github/linguist/files/1359071/test-win.zip)

**Comment by lildude** [comment]
We need the samples included in the PR itself so it can be merged into Linguist, ie you need to `git rm` the two heeeawg files, and then `git add` a few smaller, and more diverse, samples.  This needs to be done on the branch you're using for this PR, in this case it's the master branch of your fork of github/linguist.

The samples can't be zip files either. They need to be readable.

**Comment by MaickelHubner** [comment]
@lildude I do not understand anything about GIT.
I do not know how to change my PR.
When I tried to do this in the past I shit everything and had to do it all over again.
Can you do this for me?
Thank you,

**Comment by MaickelHubner** [comment]
I'm making all the changes here through the github website. I do not use git add commands or git rm ...

**Comment by MaickelHubner** [comment]
If so, you can cancel this request. I thought it would be an easy thing to do (even if I did not understand anything about github) but I've been bothering about it for months without success ...

**Comment by lildude** [comment]
> Can you do this for me?

Not at the moment as I don't have access to your repo. You can however [add me as a contributor](https://help.github.com/articles/inviting-collaborators-to-a-personal-repository/) and I can then make changes directly within your repo which will in turn show up here.

**Comment by MaickelHubner** [comment]
done (Y)

**Comment by lildude** [comment]
Got it. Before I go ahead and make changes, I need to know what license the files are licensed under. I can't see any mention of a license in the repo now the files themselves.

They need to be licensed under one of these https://github.com/github/linguist/blob/master/vendor/licenses/config.yml#L1-L12 for us to include them in Linguist.

**Comment by lildude** [comment]
If you're unsure of a license to use, or not comfortable setting one on your own repo, feel free to find and suggest some other repos we can take samples from that have one of the allowed licenses.

**Comment by MaickelHubner** [comment]
@lildude I do not understand. This test-win.w file is new. Where should I put this license?

**Comment by lildude** [comment]
You don't need to put the license anywhere, just let us know what license the code is licensed under.  If you really want, you can add a note about the license to the sample in a comment.

**Comment by MaickelHubner** [comment]
Ok. The test-win.w file is unlicensed.

**Comment by lildude** [comment]
@MaickelHubner I've switched out the large samples for your smaller test-win.w file.

**Comment by lildude** [comment]
I've also relaxed the regex in the heuristic to match more files as the `C-Win` part limits things quite considerably.

**Comment by MaickelHubner** [comment]
Cool!!! Thanks

**Pull request merged**
