### PR TITLE
Bump rugged to latest release

### PR DESCRIPTION
**Pull request by adelcambre**
Need this for this fix: https://github.com/libgit2/libgit2/pull/3000

/cc @vmg @simonsj

### CODE REVIEW

**Comment by vmg** [comment]
Looks good.

**Comment by vmg** [comment]
(you'll need to bump linguist now ;))

**Comment by arfon** [comment]
> (you'll need to bump linguist now ;))

@adelcambre - I'm happy to do this if you like?

**Comment by adelcambre** [comment]
@arfon I need to do it in GitRPC first, so I can handle it.

**Comment by arfon** [comment]
:+1:

**Comment by adelcambre** [comment]
@arfon I was confused, but it would be awesome if you can release a new linguist. I'll handle getting it bumped in github.com/gitrpc after that.

**Pull request merged**
