### PR TITLE
Add Wollok Language

### PR DESCRIPTION
**Pull request by javierfernandes**

### CODE REVIEW

**Comment by pchaigno** [comment]
Please see the [contribution guidelines on how to add a new language to Linguist](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language). In particular, the requirements and how to add the grammar ;)

**Comment by javierfernandes** [comment]
Hi @pchaigno 
I'm really sorry. I didn't noticed the contribution guide :(
I was basing my changes in some other PRs manually

I have now followed the guide.

Again apologies for wasting your time

I hope it's now fine.

Thanks!

**Comment by pchaigno** [comment]
No problem. I'm not part of GitHub staff anyway. I just a contributor here, like you :smile: 
You will also need to show that Wollok is sufficiently used on GitHub (usually a GitHub search showing as many files as possible is enough).

**Comment by arfon** [comment]
> You will also need to show that Wollok is sufficiently used on GitHub (usually a GitHub search showing as many files as possible is enough).

:+1: yes, please construct a search to show usage on GitHub: https://github.com/search/advanced

**Comment by arfon** [comment]
:flags: flagging this as stale :flags:

**Comment by javierfernandes** [comment]
Sorry, @arfon was is the minimum number of files it should hit for including this change ?

Here is the search

https://github.com/search?utf8=%E2%9C%93&q=var+extension%3Awlk+extension%3Awpgm+extension%3Awtest&type=Code&ref=searchresults

For the moment it is just hitting 63 files.
That number will increase, since it is new language that is starting to be used.

**Comment by arfon** [comment]
> That number will increase, since it is new language that is starting to be used.

OK thanks @javierfernandes. I'm afraid this doesn't currently meet our [contributing guidelines](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language) for adding a new language. I'm happy to revisit this as adoption increases.

**Comment by javierfernandes** [comment]
Ok. Thanks !

I'll get back once we have more usages :)

**Comment by fdodino** [comment]
Hi @arfon, we have now about 1,1K uses
https://github.com/search?utf8=%E2%9C%93&q=var+extension%3Awlk+extension%3Awpgm+extension%3Awtest&type=Code&ref=searchresults

(Wollok was adopted last year in 5 different universities of Argentina).
Could you reconsider the possibility ?
Many thanks !

**Comment by arfon** [comment]
Quite possibly - unfortunately I'm the wrong person to ask this through as I'm no longer a maintainer of Linguist.

I'd suggest taking a look at the readme to see who the current maintainers are :-)




On Sat, Jul 1, 2017 at 1:37 AM +0100, "Fernando Dodino" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @arfon<https://github.com/arfon>, we have now about 1,1K uses
https://github.com/search?utf8=%E2%9C%93&q=var+extension%3Awlk+extension%3Awpgm+extension%3Awtest&type=Code&ref=searchresults

(Wollok was adopted last year in 5 different universities of Argentina).
Could you reconsider the possibility ?
Many thanks !

**Comment by fdodino** [comment]
Ok @arfon, thanks anyway and see you in a next occasion.

Hi @pchaigno, 
we have now about 1,1K uses
https://github.com/search?utf8=%E2%9C%93&q=var+extension%3Awlk+extension%3Awpgm+extension%3Awtest&type=Code&ref=searchresults

(Wollok was adopted last year in 5 different universities of Argentina, and we will increase usage since we will moving all our SVN repos to github education repositories, I think near 800 students per year will be attending our Wollok courses).
Could you reconsider the possibility ?
Many thanks !

**Comment by pchaigno** [comment]
@fdodino Sorry for the long delay. It looks like there are enough users for the [`.wlk`](https://github.com/search?utf8=%E2%9C%93&q=var+OR+method+extension%3Awlk&type=Code) extension, but not for [`.wtest`](https://github.com/search?utf8=%E2%9C%93&q=var+OR+method+extension%3Awtest&type=Code) and [`.wpgm`](https://github.com/search?utf8=%E2%9C%93&q=var+OR+method+extension%3Awpgm&type=Code). You could submit a pull request to add Wollock as a language with the `.wlk` extension, and we can reconsider the other extensions when the usage grows.

**Comment by fdodino** [comment]
Many many thanks! I'll do this next days.
Cheers!

**Pull request closed without merging**
