### PR TITLE
Not going to be staff for much longer.

### PR DESCRIPTION
**Pull request by arfon**
@pchaigno @larsbrinkhoff @Alhadis - I'm afraid I'm deserting you all and heading off to [STScI in Baltimore](http://hubblesite.org/newscenter/archive/releases/2016/44/) to do something new. My last day at GitHub will be 4th November.

In the short term this means that I'm no-longer going to be able to push new versions of Linguist to GitHub, in the longer-term I probably won't be active on the project at all 😿 

I'm opening up this PR to give you all a heads up. I'm currently soliciting interest internally (at GitHub) for a new maintainer from our side.

It's been an absolute pleasure working with you all on Linguist. Thanks for your eternal patience and awesome contributions. We literally wouldn't have been able to do this without you.

/ cc @github/open-source

### CODE REVIEW

**Comment by Alhadis** [comment]
:( Well that's a real kick in the nuts. We'll all miss you!

(The next maintainer better be as damn near friendly as you :p)

**Comment by larsbrinkhoff** [comment]
Good luck with your new job!

**Comment by Alhadis** [comment]
Give your old one to me, I'll give it a good home... lel.

**Comment by arfon** [comment]
> :( Well that's a real kick in the nuts. We'll all miss you!

Yeah, it's been a fun ride for sure. It's been an absolute pleasure working with you @Alhadis, @larsbrinkhoff and @pchaigno ❤️. I'm going to stick around on the project for another couple of months to make sure there's a seamless transition but from tomorrow I won't be merging PRs or cutting new gems.

The good news is that I've found four of the finest GitHubbers to help maintain Linguist from the GitHub side. 

Introducing @brandonblack, @lildude, @LizzHale and @MikeMcQuaid ✨

**Comment by Alhadis** [comment]
Haha, @MikeMcQuaid will remember me. 👍  He [gave some encouragement](https://github.com/Homebrew/brew/issues/784#issuecomment-241674517) about learning to write Ruby, which I **[ended up](https://github.com/github/linguist/pull/3192)** **[doing](https://github.com/github/linguist/pull/3193)**. How'd I do, Mike? =)

**Comment by pchaigno** [comment]
@arfon Back to the stars I see :-)
Congrats for your new job and good luck for your first day!

Thanks @brandonblack, @lildude, @LizzHale and @MikeMcQuaid for taking over :bow:

**Comment by MikeMcQuaid** [comment]
@Alhadis You did well 😁. Just a note that I'm not going to be maintaining this as my role has changed and the others seem to be doing a good job. Thanks all!

**Pull request merged**
