### PR TITLE
Add "asm" as alias for assembly

### PR DESCRIPTION
**Pull request by tobiasvl**
Adds the much-used abbreviation "asm" as an alias for Assembly.

## Description
Assembly only has one alias right now: "nasm". That's the name of an assembler. The abbreviation "asm", however, is widely used for assembly as a whole, and it's used as filetype names in both Vim and Emacs modelines.

## Checklist:

- [ ] **I am associating a language with a new file extension.**
  - [ ] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      
      - https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am adding a new language.**
  - [ ] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a syntax highlighting grammar.
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [x] **I am fixing a misclassified language**
  - [ ] I have included a new sample for the misclassified language:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am changing the source of a syntax highlighting grammar**
  
  - Old: https://github-lightshow.herokuapp.com/
  - New: https://github-lightshow.herokuapp.com/

- [x] **I am adding new or changing current functionality**
  
  - [ ] I have added or updated the tests for the new or changed functionality.

### CODE REVIEW

**Comment by pchaigno** [comment]
@lildude Since there's already the `.asm` file extension, will adding `asm` as an alias change anything on github.com?

**Comment by tobiasvl** [comment]
I do have one real-world case in favor of this alias:

In one of my (private) repos, I have an assembly file in a repo with the `.inc` file extension. This extension is associated with several languages, including assembly and C++. The file is erroneously recognized as C++.

In order to get both assembly syntax highlighting in Vim (and other editors) and linguist classification as assembly, I need to add two identifiers: One modeline with "asm" for Vim syntax highlighting, and one modeline (or `.gitattributes` linguist entry) with "assembly". This seems highly unnecessary for a commonly used abbreviation.

**Comment by pchaigno** [comment]
Oh, right, we use aliases for modelines too.
LGTM!

**Comment by lildude** [comment]
> @lildude Since there's already the .asm file extension, will adding asm as an alias change anything on github.com?

Nope.

**Pull request merged**
