### PR TITLE
Remove GPL Licensed Samples

### PR DESCRIPTION
**Pull request by sahildua2305**
I am submitting this PR to make sure I keep getting feedback while I am making the changes. Please let me know if I am doing anything wrong.

- Updated samples for C language

I removed two large sample files containing 700+ lines and haven't added any file with approx same number of lines. Is that an issue? Should I add new samples files of approximately same size as the ones that I remove?

[EDIT]

- Added `fudge_node.c` [Source](https://github.com/jezze/fudge/blob/master/src/modules/pipe/main.c) | [License](https://github.com/jezze/fudge/blob/master/LICENCE)
- Added `array.c` [Source](https://github.com/Lodifice/array/blob/master/array.c) | [License](https://github.com/Lodifice/array/blob/master/LICENSE)
- Added `array.h` [Source](https://github.com/Lodifice/array/blob/master/array.h) | [License](https://github.com/Lodifice/array/blob/master/LICENSE)
- Added `custom_extensions.c` [Source](https://github.com/thewintersun/boringssl/blob/master/ssl/custom_extensions.c) | License (mentioned at the top of the file)

/cc @arfon @pchaigno

### CODE REVIEW

**Comment by arfon** [comment]
Thanks for opening this PR @sahildua2305!

> I removed two large sample files containing 700+ lines and haven't added any file with approx same number of lines. Is that an issue? Should I add new samples files of approximately same size as the ones that I remove?

That should be OK. 

Give that the goal of this effort is to replaced GPL-licensed sample files, can you share in this PR the origin (and license) of the samples you're replacing them with?

**Comment by sahildua2305** [comment]
Sure @afron. I am sharing the required information here.

- Added `fudge_node.c` [Source](https://github.com/jezze/fudge/blob/master/src/modules/pipe/main.c) | [License](https://github.com/jezze/fudge/blob/master/LICENCE)
- Added `array.c` [Source](https://github.com/Lodifice/array/blob/master/array.c) | [License](https://github.com/Lodifice/array/blob/master/LICENSE)
- Added `array.h` [Source](https://github.com/Lodifice/array/blob/master/array.h) | [License](https://github.com/Lodifice/array/blob/master/LICENSE)
- Added `code.c` [Source](https://github.com/TC432/c_stuff/blob/144c16cfef90deccf61bf72ebba937522b7d16d3/code.c) | License not mentioned (Should such cases be considered safe for redistribution under MIT?)

Please have a look at these new sample files and let me know if I need to mention any more information about these. :)

**Comment by arfon** [comment]
> Added code.c Source | License not mentioned (Should such cases be considered safe for redistribution under MIT?)

@sahildua2305 - no, unfortunately we can't use samples without a license. Can we swap this one out?

**Comment by sahildua2305** [comment]
@arfon Done. I have removed the file without License and added a new one that I found. I have added it's source in the first comment with others.

**Comment by arfon** [comment]
OK thanks @sahildua2305. This is looking great so far. Are you planning on adding more replacement samples in this PR or do you plan to do this on a per-language-per-PR basis?

**Comment by sahildua2305** [comment]
I will prefer per-language-per-PR, if that's fine. @arfon Let me know :)

**Comment by arfon** [comment]
Sounds good to me. So is this one ready to merge?

**Comment by sahildua2305** [comment]
@arfon Yes, from my side :+1:

**Pull request merged**
