### PR TITLE
xBase .ch

### PR DESCRIPTION
**Pull request by arfon**
This is work in progress to replace #2498.

### CODE REVIEW

**Comment by arfon** [comment]
/ cc @vszakats

**Comment by vszakats** [comment]
Thank you very much @arfon, looking very good.

**Comment by arfon** [comment]
@vszakats - this change will be live in the next release of Linguist (later this week or early next week)

**Comment by vszakats** [comment]
Awaiting to see this go live, much appreciated. I'll report in case I see anything.
Thank you @arfon!

**Comment by sopenefendi** [comment]
O..thank you

**Pull request merged**
