### PR TITLE
A legit linguist website

### PR DESCRIPTION
**Pull request by bkeepers**
http://github.github.io/linguist/ is currently just a list of languages and colors. @alysonla was asking about docs on languages last night, which was just enough motivation for me to start working on it.

---

linguist_colors

## TODO

- [x] Add search
- [ ] Click on language to show more details
- [ ] Show interpreters
- [ ] Show filenames
- [ ] Add documentation on highlighting in Markdown (/cc @gjtorikian, https://github.com/github/linguist/pull/2353)
- [ ] Show syntax highlighting via https://github-lightshow.herokuapp.com/

## Questions

- What else would be useful?
- This currently uses JavaScript to fetch the latest `languages.yml` from master and build the listing. I'm wondering if `languages.yml` should be copied into the `gh-pages` branch so a static page can be generated for each language. This could be automated so `script/release` copies it to the `gh-pages` branch.

/cc @arfon @aroben

### CODE REVIEW

**Comment by pchaigno** [comment]
Awesome! :sparkles: 

> What else would be useful?

One thing that, IMO, would be particularly useful, is a link to the grammar GitHub uses for each language.
Many users came to Linguist lately for syntax highlighting issues (#2581, #2577, #2563, etc.). And, even if an entry was added for this in the Common Issues of GitHub Help, it is still not very straightforward to find the grammar (you have to get the `tm_scope` in [`languages.yml`](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml), then find the corresponding submodule in [`grammars.yml`](https://github.com/github/linguist/blob/master/grammars.yml) and finally get the actual link in [`vendor/grammars/`](https://github.com/github/linguist/tree/master/vendor/grammars)).

**Comment by bkeepers** [comment]
> …a link to the grammar GitHub uses for each language

Yeah, that'd be great. It will be interesting to implement in Pages or JavaScript, so that might be an argument for doing something with `script/release` to copy the data to the `gh-pages` branch.

**Comment by bkeepers** [comment]
- [x] Add search

linguist-search

**Comment by gjtorikian** [comment]
@bkeepers Totally awesome. 

> What else would be useful?

Mind if I put up an implementation of [the color proximity test](https://github.com/github/linguist/blob/1241b20ba174395b0bed88965b0d6cd3c743a2cf/test/test_color_proximity.rb)? I'm thinking people can toss hex numbers in the site and see if it conflicts with anything before opening up a PR / playing with CI. If that feels too busy for the site I'm totally fine not including it either.

**Comment by bkeepers** [comment]
> Mind if I put up an implementation of the color proximity test?

Not at all! That'd be awesome.

Another thing I was thinking is it might be cool to have a "Add a language" link on the site that takes you to a page that collects the language info, helps you pick a color and come up with the search URLs to show usage, and then redirect to a new PR page with the details filled out.

**Comment by arfon** [comment]
:heart: @bkeepers - this is a great idea. We should probably included the docs on 'how Linguist integrates into GitHub.com': https://github.com/github/linguist/issues/2331

**Comment by arfon** [comment]
Closing this as stale.

**Pull request closed without merging**
