### PR TITLE
Added syntax definition for Fantom language

### PR DESCRIPTION
**Pull request by rkoeninger**
[Fantom](http://fantom.org) was a pre-existing language in linguist.

Added [rkoeninger/sublime-fantom](https://github.com/rkoeninger/sublime-fantom) as a submodule
Added license for `sublime-fantom`
Specified `tm_scope` for Fantom
Provided better color for Fantom derived from official logo

### CODE REVIEW

**Comment by pchaigno** [comment]
@rkoeninger You'll also need to update the submodule to point to your fork's last commit.

**Comment by rkoeninger** [comment]
Submodule updated.

**Comment by pchaigno** [comment]
Do you have any sample Fantom file from a real application under permissive license we could use (`samples/Fantom/`)? We currently don't have any sample for Fantom :/

**Comment by rkoeninger** [comment]
Added a couple of samples under very permissive license.

**Pull request merged**
