### PR TITLE
Detect a special header that marks any file type as generated

### PR DESCRIPTION
**Pull request by cespare**
This is a first attempt at a solution for #2724.

This change has the downside of reading + line-splitting all data in all files, instead of just some files as before.

A better solution would just peek the first, say, 200 bytes from the file and look for the header there. But the FileBlob interface is extremely limited. Should I extend it?

Thanks.

### CODE REVIEW

**Comment by cespare** [comment]
I accepted the CLA. How do I get the check to rerun?

**Comment by pchaigno** [comment]
> I accepted the CLA. How do I get the check to rerun?

Try to close and reopen ;)

We should also check the performance impact of this change...

**Comment by logiclrd** [comment]
It would be awesome if there were a way to configure this in `.gitattributes`. We have an in-house code generator that puts text at the top of every file, but that text does not read "Code generated by", and we don't really want to change it to say that because we'd have to regenerate every single project, which, across all branches of our entire codebase, amounts to tens of thousands of files.

**Comment by cespare** [comment]
Friendly ping.

**Comment by arfon** [comment]
Thanks for the ping @cespare. 

> This change has the downside of reading + line-splitting all data in all files, instead of just some files as before.

On reflection I'm not sure that we should proceed with this PR for this reason. I realise it's not idea but I think I'd rather us continue with the current pattern, that is, if there's a new file type we should be marking as `generated?` then let us know and we'll add support for it.

**Comment by cespare** [comment]
@arfon this is not a good resolution. Like @logiclrd, we have various internal generated files that are not in widespread use. They would not justify changes to the `generated?` check. Instead, there needs to be some generic mechanism.

As I mentioned above, this solution could be fixed if the FileBlob interface allowed for peeking files. Can we discuss that? I understand that this PR is too expensive as-is -- I had hoped that opening it would be the start of some fruitful discussion.

Or, let's consider some alternative mechanism such as gitattributes proposed by @logiclrd.

**Comment by arfon** [comment]
> As I mentioned above, this solution could be fixed if the FileBlob interface allowed for peeking files. Can we discuss that? I understand that this PR is too expensive as-is -- I had hoped that opening it would be the start of some fruitful discussion.

**Comment by arfon** [comment]
> As I mentioned above, this solution could be fixed if the FileBlob interface allowed for peeking files. Can we discuss that? I understand that this PR is too expensive as-is -- I had hoped that opening it would be the start of some fruitful discussion.

Sorry, my bad @cespare. I'm trying to clean up a bunch of issues and PRs on Linguist right now and I realise I didn't address this point.

> Or, let's consider some alternative mechanism such as gitattributes proposed by @logiclrd.

Ultimately I believe that a solution using `.gitattributes` data would be a good solution here but as outlined in https://github.com/github/linguist/issues/1792 and https://github.com/github/linguist/issues/2206 we don't get have support for reading in `.gitattributes` data on our application servers.

**Pull request closed without merging**
