### PR TITLE
Add mcfunction language

### PR DESCRIPTION
**Pull request by Arcensoth**
## Description
This is an interesting case of "language" that originates from [Minecraft server commands](https://minecraft.gamepedia.com/Commands). The [mcfunction file format](https://minecraft.gamepedia.com/Function) is essentially a collection of server commands, one per line, with additional comment support and some unique runtime properties. The idea is simple, but the underlying command system is complex enough to warrant discussion about whether mcfunction should be considered a type of programming language. In any case: mcfunction files are both written and distributed in plain text, naturally giving way to open-source collaboration.

The search results listed in the checklist provide proof that mcfunction is being used across a reasonable number of repositories. There's even an open-source [language server](https://github.com/Levertion/mcfunction-langserver) in development that includes extensive support for the mcfunction format.

I ran linguist dev on the [language-mcfunction](https://github.com/Arcensoth/language-mcfunction) repository to get [a breakdown of the results](https://gist.github.com/Arcensoth/8e2fab33d63f8282eea61550f8c62a06#file-linguist-language-mcfunction-results-txt) and to ensure my changes are functional.

## Checklist:
- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      - `mcfunction`:
        - [Using suggested `nothack`](https://github.com/search?q=extension%3Amcfunction+NOT+nothack&type=Code)
        - [Using keyword `tellraw`](https://github.com/search?q=extension%3Amcfunction+tellraw&type=Code)
        - [Using keyword `setblock`](https://github.com/search?q=extension%3Amcfunction+setblock&type=Code)
        - [Using keyword `area_effect_cloud`](https://github.com/search?q=extension%3Amcfunction+area_effect_cloud&type=Code)
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - `showcase.mcfunction` from [language-mcfunction](https://github.com/Arcensoth/language-mcfunction/tree/master/tests)
    - Sample license(s): [MIT](https://github.com/Arcensoth/language-mcfunction/blob/master/LICENSE)
  - [x] [I have included a syntax highlighting grammar](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fgithub.com%2FArcensoth%2Flanguage-mcfunction%2Fblob%2Fmaster%2Fmcfunction.tmLanguage.json&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2FArcensoth%2Flanguage-mcfunction%2Fblob%2Fmaster%2Ftests%2Feverything.mcfunction&code=)
  - I have updated the heuristics to distinguish my language from others using the same extension.
  	- Note: there are no other languages using the extension `mcfunction`

### CODE REVIEW

**Comment by Arcensoth** [comment]
Not sure why the build "errored" as opposed to failing or passing. Looks like it got part way through `script/travis/before_install` and then died for no apparent reason:

https://travis-ci.org/github/linguist/jobs/494397050#L1494

**Comment by pchaigno** [comment]
Yes, there's something missing. Did you use the provided script to add the grammar as per the contribution guidelines? Did you get any error message?

**Comment by Arcensoth** [comment]
Yes I followed the contribution guidelines thoroughly. I ran the script, and it was successful. I was able to run linguist and get a breakdown afterwards.

I cross-referenced with some other language PR's ([here](https://github.com/github/linguist/pull/4421) and [here](https://github.com/github/linguist/pull/4400)) and couldn't find any evidence of what's missing here.

**Comment by pchaigno** [comment]
Maybe you forgot to commit the submodule itself then. It should be under `vendor/grammars/name of the grammar repo`.

**Comment by Arcensoth** [comment]
Nice catch. But because language-mcfunction has received commits since I submitted the PR, I'm now facing a problem where the cached license is outdated. And apparently the language is not sorted correctly, but IIRC it was a script that added it. (?) Anyway, I'll fix and try again.

**Comment by Arcensoth** [comment]
This may or may not be worth consideration, but there is an inconsistency between `vendor/README.md` and `lib/linguist/languages.yml` regarding how languages are sorted by name. As far as I can tell, the latter sorts upper-case first whereas the latter disregards case and mixes them together.

**Comment by pchaigno** [comment]
> As far as I can tell, the latter sorts upper-case first whereas the latter disregards case and mixes them together.

[Indeed](https://github.com/github/linguist/blob/e4560984058b4726010ca4b8f03ed9d0f8f464db/script/list-grammars#L37). @Alhadis What do you think? Let's sort case-sensitively?

**Comment by Arcensoth** [comment]
Thanks for reviewing!

Small suggestion for `CONTRIBUTING.md`: add a step for [Testing](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#testing) under the [Adding an extension to a language](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-an-extension-to-a-language) and sections [Adding a language](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language). I think it could reduce the number of questions as a result of Travis errors, and also encourage contributors to submit cleaner PRs. :)

**Comment by Alhadis** [comment]
> @Alhadis What do you think? Let's sort case-sensitively?

Sorry, I missed this. Yes, let's. Case-sensitive is strange and feels very machine-line.

**Pull request merged**
