### PR TITLE
Http

### PR DESCRIPTION
**Pull request by arfon**
Replaces https://github.com/github/linguist/pull/1952

### CODE REVIEW

**Comment by arfon** [comment]
@aroben - is there an easy way to update the ref for the grammar submodule? From what I've read there's no trivial way to update just a single submodule.

**Comment by aroben** [comment]
> is there an easy way to update the ref for the grammar submodule?

The easiest way is `git submodule update --remote -- vendor/grammars/Sublime-HTTP`. The manual way to do it is:

```console
$ cd vendor/grammars/Sublime-HTTP
$ git fetch
$ git checkout origin/master
```

**Comment by arfon** [comment]
Awesome. Thanks @aroben

**Comment by aroben** [comment]
:heart: seeing that license test fail and then go green after you updated the submodule.

**Comment by arfon** [comment]
:100: - yeah that's pretty awesome.

**Comment by arfon** [comment]
Thanks @pchaigno & @aroben

**Comment by pchaigno** [comment]
I had the same issue and couldn't find how to solve it.
Thanks @aroben and @arfon.

**Pull request merged**
