### PR TITLE
remove reason from ocaml group

### LINKED ISSUE #4684: ReasonML detected as Ocaml
I think it happens because reason is in the `ocaml` group.

I know and agree that reason is just a syntax for ocaml but seprate detection will give some benfits such as searching through trending repos, know that how much of a monorepo, or a library which uses both reason and ocaml is written in reason / ocaml.

### PR DESCRIPTION
**Pull request by amiralies**
Closes #4684

### CODE REVIEW

**Comment by amiralies** [comment]
@jordwalke do you agree with this?

**Comment by jordwalke** [comment]
I think your argument about knowing how much of a repo is written in either Reason or OCaml is a nice feature. It would be cool if eventually there were some higher level Github/linguist feature available to be able to group based on language semantics and not just syntax, but until then I support this change.

**Comment by ryyppy** [comment]
Just to be sure to comply to the CONTRIBUTING guidelines:

## Checklist

- [X] **I am adding new or changing current functionality**
  - [ ] I have added or updated the tests for the new or changed functionality.

Goal was to display Reason as its own language instead of showing it as OCaml.
This is ready for review, the Reason community would be super happy to see this merged 😄

\cc @lildude

**Comment by ryyppy** [comment]
@pchaigno awesome, thanks for chiming in! I don't have push rights to this branch, but the Reason logo / most recognizable color in the Reason ecosystem is `#dd4b39` (orange-red) .

@amiralies could you add this color to the Reason config?

**Comment by rafaelfesi** [comment]
@ryyppy Why was it added as **"Reason"** instead of **"ReasonML"**?

**Comment by ryyppy** [comment]
Reason is the official language name, ReasonML is the "googleable name" afaik. kinda similarly on how go / rust call themselves rustlang / golang

**Comment by rafaelfesi** [comment]
Thanks for the explanation, @ryyppy.

**Pull request merged**
