### PR TITLE
Add OpenGL shading language (GLSL)

### PR DESCRIPTION
**Pull request by julik**
This is the language used for writing OpenGL shaders, which are becoming much more mainstream lately.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
@julik Why did you put GLSL in the C group?

**Comment by julik** [comment]
Because the syntax looks very C-like to me and I could not find a neat guide on how to pick a different (probably better) group

**Comment by pchaigno** [comment]
Yep, it's not really clear what it is... (see #1548)
I'll open a pull request to add a comment on that.

**Comment by larsbrinkhoff** [comment]
Thanks!

My view is that GLSL should not be in any group.  I have opened #2196 to see what the *Staff* thinks.

**Pull request closed without merging**
