### PR TITLE
Add Ethereum Vyper smart contract language

### PR DESCRIPTION
**Pull request by davidhq**
I noticed that [there was a discussion](https://github.com/github/linguist/pull/5749) about adding [Vyper language](https://vyper.readthedocs.io).

[SublimeEthereum](https://github.com/davidhq/SublimeEthereum) repo is currently used for Solidity and Vyper grammars [in SublimeText](https://packagecontrol.io/packages/Ethereum) and the same repo (branch _liguist_) is used by linguist for `source.solidity`.

Because I saw that pull request which included quite incorrect grammar for Vyper (basically just Python), I commented and pointed to more correct grammar which can be used. Today I also revisited that grammar and brought it up to speed so it's now complete and in sync with current version of Vyper:

Screenshot 2022-02-10 at 04 16 10

Language is still rather small (I believe) so you please evaluate criteria for its inclusion as you see fit. Vyper is one of the languages that helps move billions through the emerging stateful Internet of value, even if amount of files or repos on GitHub might be low. Vyper is used a) for prototyping b) as a complementary language to Solidity for subset of smart contracts (see one example of mixing `.sol` and `.vy` inside [this repo](https://github.com/ribbon-finance/governance/tree/main/contracts)). 

Here is a time chart of proxied general interest for Solidity:

Screenshot 2022-02-09 at 23 32 24

as said `.vy` files often appear alongside many more `.sol` files in repos... so I guess one way to look at Vyper is through the similar exponential graph... interest is rising and many thousands (soon millions) of people see `.vy` files on GitHub and probably wonder why they are missing the syntax highlighting... and so I do think it would be beneficial if linguist did apply highlighting to Vyper source code whenever possible / convenient.

regards

## Checklist:

- [x] **I am adding a new language.**
  - [X] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?q=extension%3Avy&type=Code
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):    
      - [URL to each sample source, if applicable]
      - https://github.com/vyperlang/vyper/tree/master/examples  →  included in samples/Vyper in linguist repo
    - Sample license(s):
    - https://github.com/vyperlang/vyper/blob/master/LICENSE
  
  - [X] I have included a syntax highlighting grammar: https://github.com/davidhq/SublimeEthereum/blob/linguist/Vyper.YAML-tmLanguage
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

### CODE REVIEW

**Review by lildude — CHANGES_REQUESTED** [review]
Just a nit: please add and fill in the original template to the OP. You can keep your current explanation, but we need the template, especially the part about where the samples have come from and their licenses.

Otherwise, this looks good.

**Comment by lildude** [comment]
We don't need the actual sample LICENSE and NOTICE files, just a link and wording in the right places in the template in the OP. The samples are used to train the classifier and we don't want the content of the Apache license and the NOTICE file to influence the classification 😁

**Comment by davidhq** [comment]
> We don't need the actual sample LICENSE and NOTICE files, just a link and wording in the right places in the template in the OP. The samples are used to train the classifier and we don't want the content of the Apache license and the NOTICE file to influence the classification 😁

okay, removed them... but according to the original LICENSE these files are supposed to be present that's why I did it... I believe it will be no problem though, so I removed them now.

> Oh wait, looks like we've got test failures cos we're missing the relevant line in the README

This one I can't figure out! "_"

**Comment by davidhq** [comment]
> > This one I can't figure out! "_" What relevant line please?
> 
> I've highlighted the pertinent bit:
> 
> ```
> 1) Failure:
> /opt/hostedtoolcache/Ruby/2.6.9/x64/bin/bundle:23:in `load'
> /opt/hostedtoolcache/Ruby/2.6.9/x64/bin/bundle:23:in `<main>'
> Tasks: TOP => default => test
> (See full trace by running task with --trace)
> TestGrammars#test_readme_file_is_in_sync [/home/runner/work/linguist/linguist/test/test_grammars.rb:42]:
> Grammar list is out-of-date. Run `script/list-grammars`. <------ 👋 RUN ME TO FIX THE PROBLEM 👇
> --- expected
> +++ actual
> @@ -501,6 +501,7 @@
>  - **Visual Basic .NET:** [peters-ben-0007/VBDotNetSyntax](https://github.com/peters-ben-0007/VBDotNetSyntax)
>  - **Volt:** [textmate/d.tmbundle](https://github.com/textmate/d.tmbundle)
>  - **Vue:** [vuejs/vue-syntax-highlight](https://github.com/vuejs/vue-syntax-highlight)
> +- **Vyper:** [davidhq/SublimeEthereum](https://github.com/davidhq/SublimeEthereum)
>  - **Wavefront Material:** [Alhadis/language-wavefront](https://github.com/Alhadis/language-wavefront)
>  - **Wavefront Object:** [Alhadis/language-wavefront](https://github.com/Alhadis/language-wavefront)
>  - **Web Ontology Language:** [textmate/xml.tmbundle](https://github.com/textmate/xml.tmbundle)
> ```
> 
> That script will add the missing line (the one with a `+` at the beginning) to the `vendor/README.md` file.

ok [did it but](https://github.com/github/linguist/pull/5772/commits/3511dee3350b642051aa17531d91a72952d5ceb1) may I ask where this test run info was / is available from within this pull request thread?

Screenshot 2022-02-10 at 17 34 25

According to this I should see the info somewhere but I don't

Screenshot 2022-02-10 at 17 50 02

Thank you for the help!

**Comment by lildude** [comment]
> ok [did it but](https://github.com/github/linguist/pull/5772/commits/3511dee3350b642051aa17531d91a72952d5ceb1) may I ask where this test run info was / is available from within this pull request thread?

It's in the test failure [here](https://github.com/github/linguist/runs/5139118258?check_suite_focus=true) which you can find by clicking the red X next to the `58720da` commit above:

CleanShot 2022-02-10 at 17 02 20

It would have also been shown in the list of tests run, but would have been cleared as soon as you pushed your next commit and replaced with the view you see which is waiting for me to approve the run.  So if you pushed again before checking, you're likely to have missed it.

**Comment by davidhq** [comment]
> > ok [did it but](https://github.com/github/linguist/pull/5772/commits/3511dee3350b642051aa17531d91a72952d5ceb1) may I ask where this test run info was / is available from within this pull request thread?
> 
> It's in the test failure [here](https://github.com/github/linguist/runs/5139118258?check_suite_focus=true) which you can find by clicking the red X next to the `58720da` commit above:
> 
> CleanShot 2022-02-10 at 17 02 20
> 
> It would have also been shown in the list of tests run, but would have been cleared as soon as you pushed your next commit and replaced with the view you see which is waiting for me to approve the run. So if you pushed again before checking, you're likely to have missed it.

makes sense, thank you

**Comment by Nixinova** [comment]
A dozen samples is a bit overkill since this is the only `.vy` language.

**Comment by lildude** [comment]
Don't worry about the commits (we squash them all on merge) so if the files etc look good, then that's fine.

**Comment by davidhq** [comment]
> Don't worry about the commits (we squash them all on merge) so if the files etc look good, then that's fine.

too late, I moved fast and broke things

**Comment by davidhq** [comment]
Active / correct pull request now here https://github.com/github/linguist/pull/5778

**Pull request closed without merging**
