### PR TITLE
Add Arend language

### PR DESCRIPTION
**Pull request by ice1000**
## Checklist:
- [x] **I am adding a new language.**
  - [ ] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  Search with `func`: https://github.com/search?q=extension%3Aard+func+NOT+nothack&type=Code
      -  Search with `import`: https://github.com/search?q=extension%3Aard+import+NOT+nothack&type=Code
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - https://github.com/ice1k/linguist/blob/arend/samples/Arend/SeqColimit.ard
    - Sample license(s):
  
  - [x] I have included a syntax highlighting grammar: https://github-lightshow.herokuapp.com/
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

### CODE REVIEW

**Comment by ice1000** [comment]
Also, running `script/bootstrap` also requires `libssl-dev` on ubuntu, which is not installed by default. It took me about half an hour to figure this out, since the error I saw is "cannot find target to make", instead of "cannot find OpenSSL".

**Comment by ice1000** [comment]
The license is the MIT license

**Comment by ice1000** [comment]
Yay! I made the CI passes!

**Comment by ice1000** [comment]
I hope so, let's see.

**Comment by ice1000** [comment]
There are 300+ files in the search result now :)

**Comment by ice1000** [comment]
There's now 340 😟 not much.

**Comment by ice1000** [comment]
Now 360

**Comment by pchaigno** [comment]
Those 360 files make up 27 repositories by 19 users. So it looks like this is growing, albeit very slowly. I'm going to close this issue, but don't hesitate to ping me to reopen if you think we've reached the required threshold of hundreds of repositories.

**Comment by ice1000** [comment]
Now 406

**Comment by pchaigno** [comment]
@ice1000 It's good that you're keeping an eye on the number of files, but I don't think it's very useful to post it here unless the number of repositories significantly went up (e.g., +100) or the number of files itself went up (e.g., +1000).

**Comment by ice1000** [comment]
Ok

**Comment by ice1000** [comment]
How do I count the repositories? Is there an API?

**Comment by pchaigno** [comment]
You can use [Harvester](https://github.com/Alhadis/Harvester).

**Comment by ice1000** [comment]
> @ice1000 It's good that you're keeping an eye on the number of files, but I don't think it's very useful to post it here unless the number of repositories significantly went up (e.g., +100) or the number of files itself went up (e.g., +1000).

Hi! It looks like there's 1.8k Arend files now!

Search results: https://github.com/search?q=path%3A*.ard+AND+%28import+OR+func%29&type=code

**Pull request closed without merging**
