### PR TITLE
add ".sol" extension to "Solidity"

### PR DESCRIPTION
**Pull request by drortirosh**
"Solidity" is defined, but it wasn't currently associated with its extension `.sol`.
No other language is currently associated with this extension.

## Checklist:

- [ x] **I am associating a language with a new file extension.**
  - [x ] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      
      - https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3Asol+contract+payable+pragma+solidity
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am adding a new language.**
  - [ ] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  
  - [ ] I have included a syntax highlighting grammar: https://github-lightshow.herokuapp.com/
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

- [ ] **I am fixing a misclassified language**
  - [ ] I have included a new sample for the misclassified language:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am changing the source of a syntax highlighting grammar**
  
  - Old: https://github-lightshow.herokuapp.com/
  - New: https://github-lightshow.herokuapp.com/

- [ ] **I am updating a grammar submodule**
  

- [ ] **I am adding new or changing current functionality**
  
  - [ ] I have added or updated the tests for the new or changed functionality.

- [ ] **I am changing the color associated with a language**
  
  - [ ] I have obtained agreement from the wider language community on this color change.
    - [URL to public discussion]
    - [Optional: URL to official branding guidelines for the language]

### CODE REVIEW

**Comment by Alhadis** [comment]
@drortirosh Did you do a search for "Solidity" to see if this has been brought up before? 😉

**Comment by drortirosh** [comment]
Did a search and didn't find any PR in that.
Also did a search and didn't find any conflicting language that claim the .Sol extension

**Comment by Alhadis** [comment]
[Here's one](https://github.com/github/linguist/pull/3973), and the discussion there will hopefully explain the complicated reasons behind the lack of Solidity highlighting on GitHub. 😉

The matter of Solidity support has been brought up many, *many* times in the past. It's blocked on technical limitations in Linguist's design, I'm afraid.

**Comment by pchaigno** [comment]
@drortirosh [Closed pull requests](https://github.com/github/linguist/pulls?utf8=%E2%9C%93&q=is%3Apr+solidity+is%3Aclosed+extension) are not displayed by default in search results.

**Comment by lildude** [comment]
Closing as this has been discussed and explained numerous times and referenced above too.

**Pull request closed without merging**
