### PR TITLE
more samples for Modelica language,

### LINKED ISSUE #2486: wrong language: Modelica
From the list of trending repositories mainly written in Modelica language:
https://github.com/trending?l=modelica
almost all are correct, but the following repos are wrongly detected as Modelica:
https://github.com/twitter/effectivescala
https://github.com/asamardzic/tempo

Some typical characteristics of Modelica files:
- First line of the file starts with the word `within`.
- Last line of the file starts with the word `end`.
- Frequent keywords are `package`, `model`, `function`, `extends`, `parameter`, `input`, `output`, `protected`, `equation`, `algorithm`, `connect`, `annotation`, `Modelica.SIunits`.

Examples of correct Modelica files are here:
https://github.com/modelica/Modelica
https://github.com/iea-annex60/modelica-annex60
https://github.com/xogeny/ModelicaBook/tree/master/ModelicaByExample

As suggested by the guidelines for contributing, I'll add some more sample files.

### PR DESCRIPTION
**Pull request by thorade**
this might fix #2486

### CODE REVIEW

**Comment by pchaigno** [comment]
It won't fix the issue you reported unfortunately :/
If you think the current samples for Modelica aren't representative enough we can still add these new samples though.

**Comment by thorade** [comment]
@xogeny @mtiller 
Some of the files I suggest to use as samples were taken from this repository:
https://github.com/xogeny/ModelicaBook
Could you confirm this PR may be merged as it is?

**Comment by xogeny** [comment]
This is @xogeny (obviously).  I'm very much in favor of including Modelica fragments and I'm happy to contribute samples from my book.  I agree to the terms of the CLA.  Please let me know if there is something else you need form me in order to accept this PR.

Thanks!

**Comment by thorade** [comment]
@pchaigno 
Even though this will not fix #2486, it is still a nice (and representative) addition.
So, unless there are other disadvantages, please merge!

**Comment by arfon** [comment]
:+1: thanks @thorade

**Pull request merged**
