### PR TITLE
An example comparison for docs

### PR DESCRIPTION
**Pull request by todotcom**

### CODE REVIEW

**Comment by gjtorikian** [comment]
Seems to be a mistake.

**Comment by arfon** [comment]
screen shot 2015-06-22 at 9 38 30 pm

Don't break the docs dude :trollface:

**Comment by gjtorikian** [comment]
I know, the flippin' irony.

**Comment by yowalee90** [comment]
image

**Comment by timeisnow** [comment]
Thank u  u were a goof
d fuck tho

**Comment by todotcom** [comment]
no one break intentionally. sorry for inconvenience. No need to reply with bad words. 
Bad words shows your sick mentality. 
Educated by not cultured.

**Pull request closed without merging**
