### PR TITLE
Add script to alphabetise submodule list

### PR DESCRIPTION
**Pull request by Alhadis**
This PR adds a script to sort the contents of [`.gitmodules`](https://github.com/github/linguist/blob/master/.gitmodules) each time a new grammar is added.

## Description
We see this all the time:

This happens because newly-registered submodules are always added at the very bottom of the `.gitmodules` file, meaning that merging one PR usually blocks the next one until the submitter has resolved conflicts manually. This slows everybody down: a user has to fix the conflicts themselves, then @lildude needs to approve the changes later.

We can remedy this simply by forcing the submodule list to be alphabetised (case-sensitively). A test has been added to ensure that manually-added modules still get ordered correctly.

As of this writing, there are currently nine PRs sitting open which have conflicting module-lists: [`#4030`](https://github.com/github/linguist/pull/4030#partial-timeline-marker), [`#4005`](https://github.com/github/linguist/pull/4005#partial-timeline-marker), [`#3983`](https://github.com/github/linguist/pull/3983#partial-timeline-marker), [`#3869`](https://github.com/github/linguist/pull/3869#partial-timeline-marker), [`#3802`](https://github.com/github/linguist/pull/3802#partial-timeline-marker), [`#3772`](https://github.com/github/linguist/pull/3772#partial-timeline-marker), [`#3764`](https://github.com/github/linguist/pull/3764#partial-timeline-marker), [`#3689`](https://github.com/github/linguist/pull/3689#partial-timeline-marker), [`#3720`](https://github.com/github/linguist/pull/3720#partial-timeline-marker).

I haven't even bothered to count how many that are *closed* which have had similar conflicts. :wink: 

## Checklist:
- [X] **I am adding new or changing current functionality**
  - [X] I have added or updated the tests for the new or changed functionality.

### CODE REVIEW

**Comment by pchaigno** [comment]
> I haven't even bothered to count how many that are closed which have had similar conflicts. :wink:

Who, you scared me. For a second, I read `I have even` :astonished:

**Comment by Alhadis** [comment]
BTW, I ran into a few issues when testing the updated `add-grammar` script:

1. Docker wasn't installed, so I had to `sudo apt-get install docker`

2. Docker *still* wasn't installed, so I had to double-check what the hell the `docker` package was, and found out the correct name is actually `docker-ce` (??!)

3. The correct Docker was installed, but it complained about inadequate permissions:

~~~
Warning: failed to get default registry endpoint from daemon (Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.35/info: dial unix /var/run/docker.sock: connect: permission denied). Using system default: https://index.docker.io/v1/
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.35/images/create?fromImage=linguist%2Fgrammar-compiler&tag=latest: dial unix /var/run/docker.sock: connect: permission denied
~~~

This makes for some pretty unfriendly UX; should the scripts be updated to deal with these hurdles? Even bailing early in `add-grammar` would be preferable to bailing halfway, because each of the above three errors left the repository with half-registered grammar modules... :disappointed:

**Comment by lildude** [comment]
> This makes for some pretty unfriendly UX; should the scripts be updated to deal with these hurdles? Even bailing early in add-grammar would be preferable to bailing halfway, because each of the above three errors left the repository with half-registered grammar modules... 😞

Yeah, I thought this may have been a problem too. Wanna open an issue so we can track and not forget this?

**Comment by Alhadis** [comment]
Done. :wink: See #4056.

**Pull request merged**
