### PR TITLE
[WIP] extracting license information

### PR DESCRIPTION
**Pull request by arfon**
This Pull Request is mainly an exercise in documentation - we're using the `Licensed` gem to 
extract the licenses of the grammars that Linguist depends upon and place them in 
`vendor/license/grammar/...`

Unfortunately as a result of this audit we've had to remove a number of grammars that don't 
have a permissive license that's compatible with Linguist including:

- https://github.com/Cykey/Sublime-Logos
- https://github.com/Red-Nova-Technologies/autoitv3-tmbundle
- https://github.com/Shammah/boo-sublime
- https://github.com/austinwagner/sublime-sourcepawn
- https://github.com/cdwilson/nesC.tmbundle
- https://github.com/gingerbeardman/monkey.tmbundle
- https://github.com/laughedelic/sublime-idris
- https://github.com/lunixbochs/x86-assembly-textmate-bundle
- https://github.com/nanoant/assembly.tmbundle
- https://github.com/puppet-textmate-bundle/puppet-textmate-bundle
- https://github.com/wmertens/sublime-nix
- https://github.com/steinwaywhw/ats-mode-sublimetext
- https://github.com/psicomante/CLIPS-sublime
- https://github.com/Siddley/Creole
- https://github.com/beefsack/GDScript-sublime
- https://github.com/zmthy/grace-tmbundle
- https://github.com/idleberg/InnoSetup-Sublime-Text
- https://github.com/mulander/oracle.tmbundle.git
- https://github.com/goblindegook/sublime-text-pig-latin
- https://github.com/tbuser/openscad.tmbundle

### CODE REVIEW

**Comment by arfon** [comment]
Obviously we need to try and find replacement grammars that are compatible with our [license whitelist](https://github.com/github/linguist/blob/065c809dd5026e1cb27d7a08318d385d4a89dd5c/test/test_grammars.rb#L14-L25). Any assistance on that would be :sparkles:

**Comment by arfon** [comment]
/ cc @bkeepers @mlinksva

**Comment by bkeepers** [comment]
👍 thanks for pushing this over the finish line. There are a few things I think still need to be done:

- [ ] run `script/licensed cache` whenever a new grammar is added
- [ ] run `script/licensed verify` as part of CI

We can also probably clean up some of the custom tests now that it's part of the licensed check.

**Comment by copumpkin** [comment]
What? Why was the Nix grammar removed?

**Comment by copumpkin** [comment]
So I guess anything GPL'd is automatically out? cc @wmertens

**Pull request merged**
