### PR TITLE
Assign handlebars a color for the language bar.

### PR DESCRIPTION
**Pull request by tarebyte**
I noticed that [Handlebars](http://handlebarsjs.com/) didn't have a color for the language bar.

I used the orange from the [Handlebars T-Shirt](http://devswag.com/collections/handlebars/products/handlebars-t-shirt-1) on DevSwag.

Thanks!

Also I hope it was ok, I found some trailing white space and removed it :grin:

### CODE REVIEW

**Comment by pchaigno** [comment]
Isn't Handlebars often found with HTML code? Because this color seems very close to HTML's...

**Comment by bkeepers** [comment]
> I used the orange from the Handlebars T-Shirt on DevSwag.

Hah, awesome strategy.

I agree with @pchaigno, we should probably make it distinguishable from html.

**Comment by tarebyte** [comment]
Yeah they are really similar, I didn't even notice. Any suggestion for a color then? Or should I just close the PR?

**Comment by bkeepers** [comment]
Adding a color would be good, I don't have any suggestions.

This got me thinking that there isn't an easy way to see all the colors, so I hacked up a quick `gh-pages` branch that shows all the languages and their colors: http://github.github.io/linguist/

**Comment by larsbrinkhoff** [comment]
@bkeepers You might want to exclude those languages that don't have `color`, but do have the `group` element.

**Comment by tarebyte** [comment]
@bkeepers I just inverted the original color, not sure why the build is failing

**Comment by tarebyte** [comment]
@bkeepers @pchaigno I rebased master onto my branch and the CI is back to passing

**Comment by pchaigno** [comment]
> This got me thinking that there isn't an easy way to see all the colors, so I hacked up a quick gh-pages branch that shows all the languages and their colors: http://github.github.io/linguist/

@bkeepers :+1:

**Comment by arfon** [comment]
:+1:

**Comment by tarebyte** [comment]
:heart_eyes:

**Pull request merged**
