### PR TITLE
Add new entry for Sublime Text config files

### PR DESCRIPTION
**Pull request by Alhadis**
Follow-up of #3267 and #2662, both of which concern the misclassification of Sublime Text's configuration files as "JavaScript". These files are most certainly not JavaScript... the only thing distinguishing them from JSON is support for JS comments.

Because many of them *do* contain comments, using the JSON grammar to provide highlighting will produce a lot of incorrect, messy highlighting. I've added a separate entry to group them under JSON, but use the JavaScript grammar for highlighting.

Linguist's submodules have a healthy abundance of Sublime configs already, so the samples I added were simply copied from `vendor/grammars`.

With @keplersj's help, I was able to collate a list of normative references for each documented format. Some were undocumented altogether; presumably deprecated filenames supported in older versions.

**EDIT:** [Relevant PR for CSON that still needs reviewing](https://github.com/github/linguist/pull/3175)

| File extension         | Format                         | Results:          358,824 |
|------------------------|--------------------------------|--------------------------:|
| `.sublime-build`       | [JSON + Comments][Build]       | [11,601][Build-2]         |
| `.sublime-commands`    | [JSON + Comments][Commands]    | [25,177][Commands-2]      |
| `.sublime-completions` | [JSON][Completions]            | [9,659][Completions-2]    |
| `.sublime-keymap`      | [JSON][Keymap]                 | [56,300][Keymap-2]        |
| `.sublime-macro`       | [JSON][Macro]                  | [8,639][Macro-2]          |
| `.sublime-menu`        | [JSON + Comments][Menu]        | [38,843][Menu-2]          |
| `.sublime-mousemap`    | JSON - Undocumented            | [5,479][Mousemap-2]       |
| `.sublime-project`     | [JSON][Project]                | [53,241][Project-2]       |
| `.sublime-settings`    | [JSON][Settings]               | [98,640][Settings-2]      |
| `.sublime-theme`       | JSON - Undocumented            | [5,896][Theme-2]          |
| `.sublime-workspace`   | [JSON][Workspace]              | [44,000][Workspace-2]     |
| `.sublime_metrics`     | JSON - Undocumented            | [ 121][Metrics-2]         |
| `.sublime_session`     | [JSON][Session] - Undocumented | [1,228][Session-2]        |

[Build]:         http://docs.sublimetext.info/en/latest/reference/build_systems/basics.html#file-format-of-sublime-build-files
[Commands]:      http://docs.sublimetext.info/en/latest/reference/command_palette.html#file-format-of-sublime-commands-files
[Completions]:   http://docs.sublimetext.info/en/latest/reference/completions.html#file-format
[Keymap]:        http://docs.sublimetext.info/en/latest/customization/key_bindings.html
[Macro]:         http://docs.sublimetext.info/en/latest/extensibility/macros.html?highlight=JSON
[Menu]:          http://docs.sublimetext.info/en/latest/customization/menus.html#file-format
[Project]:       http://docs.sublimetext.info/en/latest/file_management/file_management.html#projects
[Session]:       http://www.bigjason.com/blog/cleaning-up-sublime-text-2-recent-projects#step-3-remove-unwanted-projects
[Settings]:      http://docs.sublimetext.info/en/latest/customization/settings.html#format
[Workspace]:     http://docs.sublimetext.info/en/latest/file_management/file_management.html#projects

[Build-2]:       https://github.com/search?q=extension%3Asublime-build+NOT+nothack&type=Code
[Commands-2]:    https://github.com/search?q=extension%3Asublime-commands+NOT+nothack&type=Code
[Completions-2]: https://github.com/search?q=extension%3Asublime-completions+NOT+nothack&type=Code
[Keymap-2]:      https://github.com/search?q=extension%3Asublime-keymap+NOT+nothack&type=Code
[Macro-2]:       https://github.com/search?q=extension%3Asublime-macro+NOT+nothack&type=Code
[Menu-2]:        https://github.com/search?q=extension%3Asublime-menu+NOT+nothack&type=Code
[Mousemap-2]:    https://github.com/search?q=extension%3Asublime-mousemap+NOT+nothack&type=Code
[Project-2]:     https://github.com/search?q=extension%3Asublime-project+NOT+nothack&type=Code
[Settings-2]:    https://github.com/search?q=extension%3Asublime-settings+NOT+nothack&type=Code
[Theme-2]:       https://github.com/search?q=extension%3Asublime-theme+NOT+nothack&type=Code
[Workspace-2]:   https://github.com/search?q=extension%3Asublime-workspace+NOT+nothack&type=Code
[Metrics-2]:     https://github.com/search?q=extension%3Asublime_metrics+NOT+nothack&type=Code
[Session-2]:     https://github.com/search?q=extension%3Asublime_session+NOT+nothack&type=Code

### CODE REVIEW

**Comment by keplersj** [comment]
I'd be interested in knowing how many of these files actually have comments in them. I still suggest using the JSON 5 syntax highlighter instead of the JSON highlighter just because the former supports comment and the latter does not.

**Comment by keplersj** [comment]
As well, if my math follows about 1.5% of files identified as JavaScript on GitHub are these Sublime config files.

**Comment by Alhadis** [comment]
> I'd be interested in knowing how many of these files actually have comments in them. I still suggest using the JSON 5 syntax highlighter instead of the JSON highlighter just because the former supports comment and the latter does not.

Ah, *THAT* would be the reason these files were categorised as JavaScript in the first place.

Right, TMTOWTDI. @arfon, if it's alright, I'm going to define a new entry *just* for these Sublime config files... I'm sure many users will be complaining about the sudden lack of comment highlighting, but I don't want these things continuing to skew stats like this.

**Comment by Alhadis** [comment]
Alright, it's done. Only one grammar can be assigned per language, which is why a new entry is necessary.

To play it safe, I decided to keep using the JavaScript grammar, rather than JSON5's grammar. It feels more future-proof.

**Comment by arfon** [comment]
:+1: looks good. Did we (I mean you @Alhadis 😁) update the `language_id` appropriately for this new language?

**Comment by Alhadis** [comment]
We/I did! =) I did so by hand though... let me know if there was something else I should've done.

Sorry, I would've answered this 10 hours earlier had the entire region not been without electricity yesterday. ⚡️

**Comment by arfon** [comment]
@Alhadis - because of [this PR](https://github.com/github/linguist/pull/3258) I think we'll need to bump this now.

> We／I did! =) It was done by hand though... let me know if there was something else I should've done.

There's `set-language-ids --update` which will set the value if there isn't one present. This script could do with some TLC though as the update process is less than ideal.

**Comment by pchaigno** [comment]
> There's set-language-ids --update which will set the value if there isn't one present. This script could do with some TLC though as the update process is less than ideal.

Shouldn't be a problem once we start using hash ids ;)

**Comment by Alhadis** [comment]
> @Alhadis - because of [this PR](https://github.com/github/linguist/pull/3258) I think we'll need to bump this now.

Haha, yeah, I figured there'd be a race involved between these two PRs. All the more reason to use hashed IDs. =)

Done.

**Comment by arfon** [comment]
> Haha, yeah, I figured there'd be a race involved between these two PRs. All the more reason to use hashed IDs. =)

😆 yes.

**Comment by Alhadis** [comment]
@arfon Any [feedback on this](https://github.com/github/linguist/pull/3175)? This is arguably skewing statistics much worse than the Sublime config files were.

**Pull request merged**
