### PR TITLE
Add Avro IDL support

### PR DESCRIPTION
**Pull request by Epokhe**
Adding Avro IDL support

https://avro.apache.org/docs/current/idl.html

One thing: When I tried to integrate the [original repo for this grammar](https://github.com/Jason3S/avro.tmLanguage/), I noticed Linguist expects a specific folder structure. So I had to create a separate repository following the structure, having the same MIT license with the original one. Does this sound okay to you?

## Checklist:

- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3Aavdl+NOT+nothack
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - https://github.com/keybase/client/blob/master/protocol/avdl/keybase1/user.avdl
    - Sample license(s):
      - BSD 3-Clause
  
  - [x] I have included a syntax highlighting grammar: https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fgithub.com%2FEpokhe%2Favro.tmLanguage%2Fblob%2Fmaster%2Fsyntaxes%2Favro.tmLanguage.json&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fkeybase%2Fclient%2Fblob%2Fmaster%2Fprotocol%2Favdl%2Fkeybase1%2Fuser.avdl&code=

### CODE REVIEW

**Comment by lildude** [comment]
> So I had to create a separate repository following the structure, having the same MIT license with the original one. Does this sound okay to you?

That's fine if you don't mind keeping the repo around indefinitely. Alternatively, if you prefer, I can push changes to this branch which pulls in the original grammar and adds it to the list at: https://github.com/github/linguist/blob/5ccd5d125e761c2f79aced74184685e7516c5d5b/tools/grammars/compiler/data.go#L43-L48

I can rebuild the grammar-compiler container whilst I do this and push it once this PR has been merged.

The sample file you've included looks like a "Hello world" kind of file rather than something from the real world.

Can you please replace this with a real-world example licensed under a liberal license and update the template to point to the original file (not the file in your fork of this repo) and state its license.

**Comment by Epokhe** [comment]
I don't have a problem with keeping the repo around, but for simplicity I would prefer the approach you suggested.

I actually tried that `GrammarsInNonStdPath` method first and I remember after trying to rebuild locally(I have no idea what I'm doing) it was complaining that avro-avsc-json-schema.json was not a grammar file or something like that. I have assumed multiple .json files create problems and haven't checked further. Maybe I missed something.

I will update the example in a moment.

**Comment by Epokhe** [comment]
@lildude Changed the PR description with a real real-world example. Replaced the file in the sample directory as well.

**Comment by Epokhe** [comment]
@lildude Do you need anything else from me? I'm not sure if you want to do `GrammarsInNonStdPath` method or go with the current state.

**Comment by lildude** [comment]
No, thanks. I'll try push my changes up in the next few days.

**Comment by lildude** [comment]
> No, thanks. I'll try push my changes up in the next few days.

Done.

**Review by pchaigno — APPROVED** [review]

**Pull request merged**
