### PR TITLE
Replace JSX grammar

### LINKED ISSUE #3775: Javascript/JSX single-quote/apostrophe breaks syntax highlighting
Basically, this is the issue https://i.gyazo.com/45d9921e631ea8274d97c4af9c062628.png

### PR DESCRIPTION
**Pull request by pchaigno**
This pull request changes the JSX grammar to use https://github.com/babel/babel-sublime as discussed in #3779.

## Description

[Our current JSX grammar](https://github.com/github-linguist/language-babel) is locked to an old version because of a bug in the upstream grammar. With 632 commits behind the upstream to date, we're sure to miss important fixes and updates. Keeping the fork up-to-date is difficult because we have to watch out for PCRE incompatibilities in regular expressions.

This pull request changes the JSX grammar to use [babel/babel-sublime](https://github.com/babel/babel-sublime). As discussed in #3779, the only issue is we have to change the scope to avoid a conflict with JavaScript.

~~@lildude I'm guessing Lightshow is still blocked by the security review... Any chance you could check on your side if the grammar applies correctly and if it fixes #3775?~~

Fixes #3775 (cf. [example 1](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fgithub.com%2Fgithub-linguist%2Fbabel-sublime%2Fblob%2Fmaster%2FJavaScript%2520%28Babel%29.tmLanguage&grammar_text=&code_source=from-text&code_url=&code=%27use+strict%27%3B%0D%0A%0D%0Aconst+React+%3D+require%28%27react%27%29%0D%0A%0D%0Amodule.exports+%3D+React.createClass%28%7B%0D%0A++render%3A+function%28%29+%7B%0D%0A++++let+%7Bfeeds%2C+log%7D+%3D+this.props%3B%0D%0A%0D%0A++++log.info%28feeds%29%3B%0D%0A++++return+%3Cdiv+className%3D%22feed-list%22%3E%0D%0A++++++%3Ch3%3ENews+Feed%27s%3C%2Fh3%3E%0D%0A++++++%3Cul%3E%0D%0A++++++++%7Bfeeds.map%28function%28feed%29+%7B%0D%0A++++++++++return+%3Cli+key%3D%7Bfeed.name%7D+className%3D%7Bfeed.fetched+%3F+%27loaded%27+%3A+%27loading%27%7D%3E%0D%0A++++++++++++%7Bfeed.data+%26%26+feed.data.length+%3E+0+%3F%0D%0A++++++++++++++%3Cspan%3E%7Bfeed.name%7D+%3Cspan+className%3D%27light%27%3E%28%7Bfeed.data.length%7D%29%3C%2Fspan%3E%3C%2Fspan%3E%0D%0A++++++++++++++%3A+%27feed.name%27+%7D%0D%0A++++++++++%3C%2Fli%3E%0D%0A++++++++%7D%29%7D%0D%0A++++++%3C%2Ful%3E%0D%0A++++%3C%2Fdiv%3E%3B%0D%0A++%7D%0D%0A%7D%29%3B), [example 2](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fgithub.com%2Fgithub-linguist%2Fbabel-sublime%2Fblob%2Fmaster%2FJavaScript%2520%28Babel%29.tmLanguage&grammar_text=&code_source=from-text&code_url=&code=import+%27js%2Fweb.jsx%27%3B%0D%0Aimport+%27console.jsx%27%3B), [example 3](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fgithub.com%2Fgithub-linguist%2Fbabel-sublime%2Fblob%2Fmaster%2FJavaScript%2520%28Babel%29.tmLanguage&grammar_text=&code_source=from-text&code_url=&code=import+React+from+%27react%27%3B%0D%0A%0D%0Avar+ExampleApplication+%3D+React.createClass%28%7B%0D%0A++render%3A+function%28%29+%7B%0D%0A++++var+elapsed+%3D+Math.round%28this.props.elapsed++%2F+100%29%3B%0D%0A++++var+seconds+%3D+elapsed+%2F+10+%2B+%28elapsed+%25+10+%3F+%27%27+%3A+%27.0%27+%29%3B%0D%0A++++var+message+%3D%0D%0A++++++%27React+has+been+successfully+running+for+%27+%2B+seconds+%2B+%27+seconds.%27%3B%0D%0A%0D%0A++++return+%3Cp%3E%7Bmessage%7D%3C%2Fp%3E%3B%0D%0A++%7D%0D%0A%7D%29%3B%0D%0A%0D%0Avar+start+%3D+new+Date%28%29.getTime%28%29%3B%0D%0A%0D%0AsetInterval%28function%28%29+%7B%0D%0A++ReactDOM.render%28%0D%0A++++%3CExampleApplication+elapsed%3D%7Bnew+Date%28%29.getTime%28%29+-+start%7D+%2F%3E%2C%0D%0A++++document.getElementById%28%27container%27%29%0D%0A++%29%3B%0D%0A%7D%2C+50%29%3B), and [example 4](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fgithub.com%2Fgithub-linguist%2Fbabel-sublime%2Fblob%2Fmaster%2FJavaScript%2520%28Babel%29.tmLanguage&grammar_text=&code_source=from-text&code_url=&code=const+a+%3D+%5B%22I%27m%22%2C+%22foo%22%5D%3B%0D%0A%0D%0Aswitch+%28true%29+%7B%0D%0A++case+%2FI%27m+foo%2F.test%28a.join%28%27+%27%29%29%3A%0D%0A++++console.log%28true%29%3B%0D%0A++++break%3B%0D%0A%7D)).

- [x] **I am changing the source of a syntax highlighting grammar**
  
  - Old: https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fgithub.com%2Fgithub-linguist%2Flanguage-babel%2Fblob%2Fmaster%2Fgrammars%2FBabel%2520Language.json&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fgithub%2Flinguist%2Fblob%2Fmaster%2Fsamples%2FJSX%2Fsample.jsx&code=
  - New: https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fgithub.com%2Fgithub-linguist%2Fbabel-sublime%2Fblob%2Fmaster%2FJavaScript%2520%28Babel%29.tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fgithub%2Flinguist%2Fblob%2Fmaster%2Fsamples%2FJSX%2Fsample.jsx&code=

### CODE REVIEW

**Comment by lildude** [comment]
I've taken a quick look at the difference in grammars and the babel/babel-sublime grammar produces quite different syntax highlighting for the simple example mentioned in https://github.com/github/linguist/issues/3775#issuecomment-364367226:

screen shot 2018-08-12 at 12 03 38

Interestingly, the current grammar doesn't show the problem either, but does render it quite differently:

screen shot 2018-08-12 at 12 04 17

The first example of those I reference in https://github.com/github/linguist/issues/3775#issuecomment-322459597 fails quite horribly with the babel/babel-sublime:

screen shot 2018-08-12 at 12 08 24

... vs our current grammar:

screen shot 2018-08-12 at 12 09 53

**Comment by pchaigno** [comment]
@lildude - @kivikakk [mentioned the same highlighting issue in #4168](https://github.com/github/linguist/issues/4168#issuecomment-411670055), and it looks like it's coming from Lightshow. I'll wait for her go to update the original post with links to Lightshow.

**Comment by kivikakk** [comment]
@lildude @pchaigno As of now, this issue should be fixed. Here's the simple case rendering properly.

image

**Comment by pchaigno** [comment]
Thanks @kivikakk!

@lildude I've updated the original post with the appropriate links to Lightshow. Ready for review!

**Comment by lildude** [comment]
@pchaigno it certainly looks better, but still noticeably different:

compare

Not sure if this is a grammar or Lightshow difference though and if it's significantly different that peeps will notice.

**Comment by Alhadis** [comment]
It's a grammar difference. If this grammar is anything like the `language-babel` grammar, then many of the scopes will differ to `language-javascript`. Most of the discrepancies are minor, but function calls in particular are being scoped strangely:

~~~js
obj.methodName( arg ); /*
    ^^^^^^^^^^ - entity.name.function.js (Current)
               - variable.function.js (Babel grammar)
*/
~~~

**Offending lines:** [#2375](https://github.com/github-linguist/babel-sublime/blob/b660229af521a3cd2556845ac774d943caed704c/JavaScript%20(Babel).tmLanguage#L2375), [#2408](https://github.com/github-linguist/babel-sublime/blob/b660229af521a3cd2556845ac774d943caed704c/JavaScript%20(Babel).tmLanguage#L2408)

**Comment by pchaigno** [comment]
Yep, I've seen the missing colors for HTML tags but I thought it was worth it since it fixes the previous bugs? Maybe we can report the discrepancies upstream if they're not already.

**Comment by Alhadis** [comment]
I doubt upstream will be interested in accepting changes, since that's imposing the same unexpected (and apparently arbitrary) colour changes on users of the `babel-sublime` package. Part of why so many grammars continue to have incorrect scope-choices is because there's little incentive to justify the changes (beyond grammar-specific semantics few end-users care about).

Remember, these scopes dictate what users have to put in their stylesheets and preference files to tweak the colour choices...

**Comment by Alhadis** [comment]
@pchaigno It should be safe to perform a simple search-and-replace for the following patterns:

| Search for: | Replace with: |
| ------ | --------- |
| `<string>variable.function.js</string>` | `<string>entity.name.function.js</string>` |
| `<string>meta.tag.jsx entity.name.tag.jsx</string>` | `<string>entity.name.tag.html.jsx</string>` |

I believe including `.html` as a scope for JSX tags will adjust the highlighting to better match what we have currently, as that's the scope being used by our `language-babel` fork.

**Comment by pchaigno** [comment]
> I doubt upstream will be interested in accepting changes, since that's imposing the same unexpected (and apparently arbitrary) colour changes on users of the `babel-sublime` package. Part of why so many grammars continue to have incorrect scope-choices is because there's little incentive to justify the changes (beyond grammar-specific semantics few end-users care about).

I was referring to the lack of HTML highlighting rather than scope names :stuck_out_tongue_winking_eye:

> It should be safe to perform a simple search-and-replace for the following patterns:

Hm, is that something we could upstream?

**Comment by Alhadis** [comment]
Hold on, I just noticed [there are spaces](https://github.com/github-linguist/babel-sublime/blob/b660229af521a3cd2556845ac774d943caed704c/JavaScript%20(Babel).tmLanguage#L1366-L1371) inside some of the scope names. Specifically, the ones affecting the HTML highlighting. Is that legal in XML TextMate grammars?

Because it's been known to screw with selector matching in Atom, so I wonder if it might be having an adverse effect on Lightshow too... :\

> Hm, is that something we could upstream?

Nope. We're performing a mass change of dozens of scope names, which goes back to my previous point. 😉

**Comment by pchaigno** [comment]
> Hold on, I just noticed there are spaces inside some of the scope names. Specifically, the ones affecting the HTML highlighting. Is that legal in XML TextMate grammars?

Looks like they're trying to define two scope names (separated by a white space) for the matched tokens... I'm surprised that even works with Sublime Text.

> Nope. We're performing a mass change of dozens of scope names, which goes back to my previous point.

Right, my bad; I read a bit quickly.

**Comment by budmc29** [comment]
Any updates on this? I'm happy to help getting this merged.

**Comment by pchaigno** [comment]
I've updated the modified version of the babel-sublime grammar hosted at github-linguist/babel-sublime to change scope names as per @Alhadis' suggestions and to fix the double scope names. Here is the result:
sans titre
Old is the previous grammar; New is the new grammar before the scope name changes; newer is the last version.

It's not perfect because we'll have to update the scope names if the grammar is updated, but at least it fixes #3775.

**Comment by peterbe** [comment]
Disclaimer; I haven't studied the details of this PR but I see that it was merged about a month ago and I'm still seeing busted display of JSX `.js` files. E.g. https://github.com/peterbe/whatsdeployed/pull/41/files

**Comment by kivikakk** [comment]
Indeed, `src/App.js` ain't looking too hot in that PR: https://github.com/peterbe/whatsdeployed/pull/41/files#diff-14b1e33d5bf5649597cdc0e4f684dadd

> because I quietly think JSX/React/Redux is one whole […] joke

Let's avoid this kind of language use going forward.

**Comment by Alhadis** [comment]
>
> *Let's avoid this kind of language use going forward.*

Don't worry, only between the privacy of two emails would I talk like that
in an otherwise  professional setting. :p

I'm still determined to put an end to all these awful grammar discrepancies
and engine-dependent  syntax issues.....

**Comment by kivikakk** [comment]
> Don't worry, only between the privacy of two emails would I talk like that in an otherwise professional setting. :p

I'm not sure what you mean here, but to be clear: it's not acceptable in the context of the Linguist project, which is where the comment (still) appears.

**Comment by Alhadis** [comment]
Slight corrections to be made, here:


> *“it's not acceptable in the context of the Linguist project.”*


Wrong. It's not acceptable in the contexts of *any*  community project.  I
make an effort not to let my hyperactive, irreverent attitue become
visibile whilst coding...

*which is where the comment (still) appears*


And this concerns me, what comment are you referring to?  It wasn't [being
shown here](
https://github.com/peterbe/whatsdeployed/pull/41/files#diff-14b1e33d5bf5649597cdc0e4f684dadd
).

**Comment by kivikakk** [comment]
> And this concerns me, what comment are you referring to?

Ah, your comment made immediately prior to mine -- https://github.com/github/linguist/pull/4223#issuecomment-434918879.

**Comment by Alhadis** [comment]
Wonderful. Went through that entire exchange entirely unaware my resoinses were being forwaarded  to the originating thread. ...and I'm damn sure I cicked on **.Reply** and not **Reply all**...

Obviously not though... :rolleyes 
screen shot 2018-11-01 at 3 26 02 pm

Yep, I' am a retard.

**Comment by Alhadis** [comment]
Gonna go back to working on something so I don't feel like an idiot. ^_^

**Comment by lildude** [comment]
> Disclaimer; I haven't studied the details of this PR but I see that it was merged about a month ago and I'm still seeing busted display of JSX `.js` files. E.g. https://github.com/peterbe/whatsdeployed/pull/41/files

That's probably because there hasn't been a Linguist release made since this PR was merged so you're still looking at the old behaviour. I aim to make a new release approximately monthly and today would make it exactly a month since the last release 😁

I'll try find time in the next week.

**Comment by mythmon** [comment]
As a follow up to the last comment, we're still seeing the same syntax highlighting problems on whatsdeployed PRs. [This PR](https://github.com/peterbe/whatsdeployed/pull/81) is extremely hard to review since most of the lines are covered in red backgrounds.

We've seen this problem pretty continuously over the last few months. I think it is a regression based on this change, and that nothing has happened in the last few months.

**Comment by lildude** [comment]
@mythmon This is happening because of the apostrophe right at the beginning of the JSX content and is essentially a continuation of https://github.com/github/linguist/issues/3044.  We're attempting to get this fixed in the upstream grammar in https://github.com/github/linguist/issues/3044

**Pull request merged**
