### PR TITLE
Add GAML file extension

### PR DESCRIPTION
**Pull request by RoiArthurB**
## Description

This PR adds syntax support for the [GAMA-platform](https://gama-platform.github.io/) programming language name _GAML_ !

GAMA is a modeling and simulation development environment for building spatially explicit agent-based simulations.

## Checklist:

- [x] **I am associating a language with a new file extension.**
  - [x] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      
      - https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3Agaml+NOT+nothack
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - https://github.com/gama-platform/gama/blob/master/msi.gama.models/models/Tutorials/3D/models/Model%2003.gaml
      - https://github.com/gama-platform/gama/blob/master/msi.gaml.architecture.simplebdi/models/BDI%20Architecture/models/GoldMiner_BDI.gaml
      - https://github.com/gama-platform/gama/blob/master/msi.gama.models/models/Tutorials/Incremental%20Model/models/Incremental%20Model%207.gaml
      - https://github.com/gama-platform/gama/blob/master/msi.gama.models/models/Tutorials/Predator%20Prey/models/Model%2013.gaml
      - https://github.com/gama-platform/gama/blob/master/msi.gama.models/models/Tutorials/Road%20Traffic/models/Model%2007.gaml
    - Sample license(s):
      - GPL 3 : https://github.com/gama-platform/gama/blob/master/LICENSE

### CODE REVIEW

**Comment by RoiArthurB** [comment]
@lildude Hi! I'm trying to find a color which is not too close to any other one. I'm sad because the one I know is detected too close to another one..
Is there a way to generate any available color?

**Comment by RoiArthurB** [comment]
Ok, just found one ^^

**Comment by RoiArthurB** [comment]
@pchaigno Hi ! 
Should I add anything more or my PR is complete? :smiley:

**Comment by hqnghi88** [comment]
We are reviewing this request from over the world. Please keep it open.
Thanks

**Comment by AlexisDrogoul** [comment]
Hi @pchaigno !

Thanks for your answer. We haven't designed any Atom, Sublime or TextMate grammar for GAML yet, but being officially promoted will certainly motivate us to do so !

Cheers
Alexis

**Comment by RoiArthurB** [comment]
Hello all,

I've planned to work on a Sublime grammar (and so I could work on Atom and TextMate's one). I don't have any deadline, but if it could improve the PR, I can work on it quite quickly ^^

Regards,
RoiArthurB

**Comment by RoiArthurB** [comment]
Hello @lildude @pchaigno I've merged my repo with your last commit.
Everything is ready to merge on your repo now :smile:

**Comment by pchaigno** [comment]
Hm. One thing I missed: we're going to need links to the original copies of the samples you used.

**Comment by RoiArthurB** [comment]
Every samples come from the official Gama documentation's tutorial : https://gama-platform.github.io/wiki/Tutorials
You also can find them (and more) on the Gama repository here : https://github.com/gama-platform/gama/tree/master/msi.gama.models/models

**Comment by pchaigno** [comment]
Could you point to the exact files used? Searching by names, I could only find one of them and it had many different instances...

**Comment by RoiArthurB** [comment]
Sure here you go : 

 - https://github.com/RoiArthurB/linguist/blob/master/samples/GAML/3dTutorial.gaml
   - https://github.com/gama-platform/gama/blob/master/msi.gama.models/models/Tutorials/3D/models/Model%2003.gaml
   - https://gama-platform.github.io/wiki/ThreeD_step3#complete-model

 - https://github.com/RoiArthurB/linguist/blob/master/samples/GAML/bdiAgents.gaml
   - https://github.com/gama-platform/gama/blob/master/msi.gaml.architecture.simplebdi/models/BDI%20Architecture/models/GoldMiner_BDI.gaml
   - https://gama-platform.github.io/wiki/BDIAgents_step5#complete-model

 - https://github.com/RoiArthurB/linguist/blob/master/samples/GAML/incrementalGIS.gaml
   - https://github.com/gama-platform/gama/blob/master/msi.gama.models/models/Tutorials/Incremental%20Model/models/Incremental%20Model%207.gaml
   - https://gama-platform.github.io/wiki/IncrementalModel_step7#complete-model

 - https://github.com/RoiArthurB/linguist/blob/master/samples/GAML/luneraysFlu.gaml
   - https://gama-platform.github.io/wiki/LuneraysFlu_step5#complete-model

 - https://github.com/RoiArthurB/linguist/blob/master/samples/GAML/predatorPrey.gaml
   - https://github.com/gama-platform/gama/blob/master/msi.gama.models/models/Tutorials/Predator%20Prey/models/Model%2013.gaml
   - https://gama-platform.github.io/wiki/PredatorPrey_step12#complete-model

 - https://github.com/RoiArthurB/linguist/blob/master/samples/GAML/roadTraffic.gaml
   - https://github.com/gama-platform/gama/blob/master/msi.gama.models/models/Tutorials/Road%20Traffic/models/Model%2007.gaml
   - https://gama-platform.github.io/wiki/RoadTrafficModel_step7#complete-model

**Comment by RoiArthurB** [comment]
Hi @lildude 

What do you mean by "the links to the original source of the samples"? I've already linked every sample to the corresponding file in the main repo of the project, isn't it enough?
Also yes, only one of all my sample could be enough, I just wanted to be the more complete as possible, but anyone of them is a _real-world usage sample_ (tutorial more exactly) of what a gaml file looks like.

For the license stuff, I'll let @AlexisDrogoul precise it because I'm not sure on that stuff :smile:

**Comment by lildude** [comment]
> What do you mean by "the links to the original source of the samples"? I've already linked every sample to the corresponding file in the main repo of the project, isn't it enough?

I mean put the content of your comment at https://github.com/github/linguist/pull/4549#issuecomment-512721532 into the appropriate place in the template in place of the current links. The template currently links to the files in your fork of Linguist, _not_ the original sources.

The license info would need to go into the apt location in the template too - it appears to be GPL 3 from a quick look.

**Comment by RoiArthurB** [comment]
Updated :smiley:

**Comment by Alhadis** [comment]
> The slight variation from Harvester can be attributed to using different methods to obtain the info, time, and the fact search will only return 1000 results and they can vary slightly each time a search is performed - I have no idea why.

When Harvester runs, it collects results yielded by the three different "Sort" methods:

Figure 1

Whatever determines the "Best Match" criteria ultimately impacts a third of what Harvester's able to collect. It combs all three sort methods in an effort to reach past the 1000-files-per-search limit, which only matters when there's more than 3,000 results for a search.

> Using my own script (it's nearly ready for all to use), I get these stats:

Oh, thank christ. Finally, we can get some server-side support for this. 😀

**Comment by lildude** [comment]
> Oh, thank christ. Finally, we can get some server-side support for this. 😀

Nope. It's only using the public API with normal user permissions now 😁.

**Comment by Alhadis** [comment]
Erh, you mean the RESTful API? I wasn't aware open-ended searches were possible without specifying a user, org, and/or repository to search within. Was this something that changed more recently?

**Comment by lildude** [comment]
> Erh, you mean the RESTful API? 

Yup. https://developer.github.com/v3/search/#search-code

> I wasn't aware open-ended searches were possible without specifying a user, org, and/or repository to search within. Was this something that changed more recently?

Not that I'm aware of. You do need to be authenticated to perform the search, but that's about it.

**Comment by Alhadis** [comment]
> Not that I'm aware of. You do need to be authenticated to perform the search, but that's about it.

That wasn't the case in, uh, 2016 when I first wrote the Harvester script. Just realised that was was yonks ago, so a "recent" change actually means "anything that happened in the last 3 years". 😅

**Comment by RoiArthurB** [comment]
Hi everyone ! :smile: 
So everything is ready to merge now or should I do something else? ^^

**Comment by RoiArthurB** [comment]
@lildude @pchaigno :up:

**Comment by agrignard** [comment]
Great news! Thank you all for the big effort to make it happened.

Do we have to make another step to see the GAML tag in the repository? I don't see it yet (e.g this repo https://github.com/CityScope/CS_Simulation_GAMA is mainly developed using .gaml files)

**Comment by lildude** [comment]
There is nothing you can do yet. I need to make a new release and deploy that to GitHub.com before it'll take effect. I hope to do that this week or early next.

**Pull request merged**
