### PR TITLE
Added ASN.1 language package

### PR DESCRIPTION
**Pull request by ajLangley12**
https://github.com/search?utf8=✓&q=ASN.1+extension%3Aasn+extension%3Aasn1&type=Code&ref=advsearch&l=&l=

I'd opened a pull request previously (#3148) but was having a hard time rebasing and ultimately had to open a new one because it was easier to create a fresh repo.

### CODE REVIEW

**Comment by pchaigno** [comment]
Looks like there are lots of `README.ASN1` text files, so maybe we should add it to [the filenames of the Text entry in `languages.yml`](https://github.com/github/linguist/blob/0dd78704f7ee1310a72866f59d7c8d1c812a55af/lib/linguist/languages.yml#L3815)?

@ajLangley12 [Are these](https://github.com/search?o=desc&q=extension%3Aasn+NOT+sequence+NOT+begin&ref=searchresults&s=indexed&type=Code&utf8=%E2%9C%93) ASN.1 files too?

**Comment by ajLangley12** [comment]
To the first question, sure. As for the second part of your question, many of those are ASN.1 files, but some, I think, are not. For example, [this file](https://github.com/svn2github/ncbi_tk/blob/c26b0da655d35c2ed970abcfc491ddf63f6332ec/src/objtools/readers/unit_test/gvfreader_test_cases/rw224_indel.asn), to the best of my knowledge, is not. 
[This file](https://github.com/nikamajinkya/Wireshark/blob/2674c83078c00a145929b97e75f9100d5f980d8a/epan/dissectors/asn1/rrc/InformationElements.asn), however, is valid ASN.1.

**Comment by ajLangley12** [comment]
I did some research on the .asn file extension. Supposedly, this file extension is also associated with something called a Atlantis Word Processor Sound Scheme file. With the exception of the `::=` operator, it doesn't look like these files have anything in common with the ASN.1 syntax.

**Comment by ajLangley12** [comment]
PR has been open for a while. What can I do to get this merged?

**Comment by pchaigno** [comment]
The PR has been open for less than a week so that's (unfortunately) not a while around here :stuck_out_tongue_winking_eye: 
I'm currently checking whether it will have a negative impact on the classification of `.asn` files. I should have an answer soon. Please be patient :-)

**Comment by ajLangley12** [comment]
Ah, cool. Sorry to be a bother. Just wanted to make sure :)

**Comment by pchaigno** [comment]
I downloaded all files from [this search query](https://github.com/search?utf8=%E2%9C%93&q=extension%3Aasn+data+str+label). From this, it looks like Atlantis Word Processor Sound Scheme files are only used in 36 repositories (35 users). I think we can keep the `.asn` extension without too much negative impact.

@arfon Is this pull request :+1: for you?

**Comment by arfon** [comment]
> @arfon Is this pull request 👍 for you?

👍

**Comment by pchaigno** [comment]
@ajLangley12 Thank you for your contribution! It should be live on github.com with the next release (usually every couple weeks).

**Pull request merged**
