### PR TITLE
Add the Whitespace language

### PR DESCRIPTION
**Pull request by mhsjlw**
This pull request adds the [Whitespace language](https://en.wikipedia.org/wiki/Whitespace_(programming_language)) with examples taken from [the official whitespace website](http://web.archive.org/web/20150507121743/http://compsoc.dur.ac.uk/whitespace/examples.php). It does **not** add grammar support mostly because I am unable to figure out a way to make TextMate, Sublime Text or Atom display Whitespace like the example given on Wikipedia: ![Wiki example] (https://upload.wikimedia.org/wikipedia/commons/3/3c/Whitespace_in_vim2.png) 

Relevance of the language is shown [here](https://github.com/search?utf8=%E2%9C%93&q=extension%3Aws+NOT+nothack&type=Code&ref=searchresults), at around 34,000 results, although I am not sure if these are all relevant to Whitespace.  If anyone has any ideas for implementing a grammar file that renders above I am happy to adopt it into this pull request. If anything is out of place or I haven't done something properly, please tell me, I am open to suggestions and fixes, although I've tried my best to follow the guidelines for contributing.

### CODE REVIEW

**Comment by Alhadis** [comment]
Whitespace is for wimps. I write everything on one line.

**Comment by Alhadis** [comment]
To give you something more intelligent:

I think you'll find most esoteric languages (like Whitespace) command very little usage on GitHub, and the [contribution notes](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language) state that a language needs to be in use in hundreds of repositories. The `.ws` extension isn't necessarily Whitespace-specific, and most results I'm seeing tend to look [like this](https://github.com/Nolenthar/WWA2/blob/d87c258a74da203e4dfd3bc01a19518285a3a338/Main/src/vanillaScripts/scripts/game/behavior_tree/tasks/custom/btTaskToadBackProjectiles.ws).

Regarding highlighting: syntax highlighting is provided using a [TextMate-compatible grammar](http://manual.macromates.com/en/language_grammars), which is easy to write if you're savvy with regular expressions. Bear in mind though, the colour choices used for grammars vary from theme-to-theme, and the theme GitHub uses for its syntax highlighting doesn't have much support for background colours. Which is what you'd need to fall back on in order to get whitespace highlighted (if at all).

**Comment by mhsjlw** [comment]
I have looked into writing TextMate compatible grammar and have been unable to figure out how to highlight spaces and tabs as multiple characters at a time, but as it seems this won't be merged I won't bother trying.

**Comment by Alhadis** [comment]
Pssst:

```coffee
name: "Whitespace"
scopeName: "source.whitespace"
fileTypes: ["ws"]
patterns: [{
	match: "\t+"
	name: "tabs.are.better-than-spaces.whitespace"
},{
	match: "\x20+"
	name: "spaces.are-for-alignment-and-wimps-who-can't-indent.whitespace"
}]
```

Of course, each will need to have `name` attributes whose scopes receive correct highlighting.

**Comment by mhsjlw** [comment]
```cson
'scopeName': 'source.whitespace'
'name': 'Whitespace'
'fileTypes': ['ws']
'patterns': [
  {
    'match': '\t'
    'name': 'whitespace.char.tab'
  },
  {
    'match': '\u0020'
    'name': 'whitespace.char.space'
  },
  {
    'match': '\n'
    'name': 'whitespace.char.return'
  },
  {
    'match': '\r'
    'name': 'whitespace.char.return'
  }
 ]
```

That's as far as I got. I couldn't figure out how to highlight the selections. Any suggestions on where I can put them, and test them out before adding them to this pull request?

**Comment by Alhadis** [comment]
First of all, you won't be able to highlight newlines. I'm afraid that's a limitation in the TextMate grammar engine itself... it highlights a document one line at a time. The reasons are performance related.

Second, in order for whitespace to show up in a user's syntax theme, you'll need to supply highlighting. Going to go out on a limb and assume you're using Atom.

**Steps: The lazy, soon-to-be-deprecated way**
1. Create a new Less file in your package's `styles/` directory.
2. Fill it out like this:  
```less
atom-text-editor::shadow, :root{
	.source.whitespace{
		.char.tab{
			background: #f00 !important; // Tab colour
		}

		.char.space{
			background: #00f !important; // Space colour
		}
	}
}
```

**Comment by mhsjlw** [comment]
Awesome! Will this method also work with GitHub's ace editor? Or is it atom-specific

Thank you

**Comment by Alhadis** [comment]
No, it's strictly Atom-specific.

Bear in mind this isn't normally the way how grammars apply highlighting - it's up to the user's syntax theme to apply the necessary colour palette. However... in this particular case, it's a lot different, due to the "esoteric" (read: completely retarded) nature of the language in question. So a hack like this is necessary.

If you publish a package for that, I'd be happy to give you a more future-proof way of adding syntax highlighting. The `::shadow` selector is on its way out and will eventually be dropped from Chromium, so it's best if you do things the "right" way (which is fiddlier).

**Comment by nixel2007** [comment]
please correct me, but AFAIK you can set the highlighting stile by ace_mode. and ace_mode leads to some repo with js and css

**Comment by mhsjlw** [comment]
I've started here, https://github.com/mhsjlw/language-whitespace and @nixel2007 I'll look into that. Not sure if the maintainers will like that though :smile:

**Comment by Alhadis** [comment]
... that's... something altogether different, dude. You can't tell the Ace editor exactly what styles it uses, it just picks from an existing palette.

It might be possible to [leverage some existing scopes](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-text&grammar_url=&grammar_text=%22name%22%3A+%22Sandbox%22%0D%0A%22scopeName%22%3A+%22sandbox%22%0D%0A%22fileTypes%22%3A+%5B%22sand.box%22%5D%0D%0A%22patterns%22%3A+%5B%7B%0D%0A%09%22match%22%3A+%22A%2B%22%0D%0A%09%22name%22%3A+%22invalid.illegal%22%0D%0A%7D%2C%7B%0D%0A%09%22match%22%3A+%22B%2B%22%0D%0A%09%22name%22%3A+%22markup.inserted%22%0D%0A%7D%5D%0D%0A&code_source=from-text&code_url=&code=AAAA%0D%0ABBBB), but that's awfully hacky and not guaranteed to look as prominent as you'd like.

**Comment by mhsjlw** [comment]
Yeah, that [looks a little strange](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-text&grammar_url=&grammar_text=%22name%22%3A+%22Sandbox%22%0D%0A%22scopeName%22%3A+%22sandbox%22%0D%0A%22fileTypes%22%3A+%5B%22sand.box%22%5D%0D%0A%22patterns%22%3A+%5B%7B%0D%0A%09%22match%22%3A+%22%5C+%22%0D%0A%09%22name%22%3A+%22invalid.illegal%22%0D%0A%7D%2C%7B%0D%0A%09%22match%22%3A+%22%5Ct%22%0D%0A%09%22name%22%3A+%22markup.inserted%22%0D%0A%7D%5D%0D%0A&code_source=from-text&code_url=&code=Say+hello.+++%0D%0A+++%09++%09+++%0D%0A%09%09++++%09%0D%0A+++%09%09++%09+%09%0D%0A%09%09++++%09+%0D%0A+++%09%09+%09%09++%0D%0A%09%09++++%09%09%0D%0A+++%09%09+%09%09++%0D%0A%09%09++++%09++%0D%0A+++%09%09+%09%09%09%09%0D%0A%09%09++++%09+%09%0D%0A+++%09+%09%09++%0D%0A%09%09++++%09%09+%0D%0A+++%09+++++%0D%0A%09%09++++%09%09%09%0D%0A+++%09%09%09+%09%09%09%0D%0A%09%09++++%09+++%0D%0A+++%09%09+%09%09%09%09%0D%0A%09%09++++%09++%09%0D%0A+++%09%09%09++%09+%0D%0A%09%09++++%09+%09+%0D%0A+++%09%09+%09%09++%0D%0A%09%09++++%09+%09%09%0D%0A+++%09%09++%09++%0D%0A%09%09++++%09%09++%0D%0A+++%09+++++%0D%0A%09%09++++%09%09+%09%0D%0A+++%09%09+%09%09%09%09%0D%0A%09%09++++%09%09%09+%0D%0A+++%09%09++%09%09+%0D%0A%09%09++++%09%09%09%09%0D%0A+++%09+++++%0D%0A%09%09++++%09++++%0D%0A+++%09%09%09++%09%09%0D%0A%09%09++++%09+++%09%0D%0A+++%09%09%09++++%0D%0A%09%09++++%09++%09+%0D%0A+++%09%09++++%09%0D%0A%09%09++++%09++%09%09%0D%0A+++%09%09+++%09%09%0D%0A%09%09++++%09+%09++%0D%0A+++%09%09++%09+%09%0D%0A%09%09++++%09+%09+%09%0D%0A+++%09%09%09++%09%09%0D%0A%09%09++++%09+%09%09+%0D%0A+++%09++++%09%0D%0A%09%09++++%09+%09%09%09%0D%0A++++%0D%0A%09%09+++++%0D%0A%0D%0A+%09+%09%09%09+%09%09%09+%09%09%09++%09++%09%09+%09++%09+%09%09%09+%09+++%09%09++%09+%09%0D%0A%0D%0A+%09+%09%09+%09%09%09++%09%09++%09+%09+%09%09%09+%09%09%09+%09%09+%09%09+++%09%09+%09++%09+%09%09+%09%09%09++%09%09++%09+%09%0D%0A%0D%0A%0D%0A%0D%0A%0D%0A+++%09%09++++%09+%09%09++%09+++%09%09++%09++%0D%0A%09+++%0D%0A%09%0D%0A%0D%0A+++%09%09%09+%09%09%09+%09%09%09++%09++%09%09+%09++%09+%09%09%09+%09+++%09%09++%09+%09%0D%0A+%0D%0A+%09%09%09+%0D%0A+%0D%0A%09++%09%09%09+%09%09%09+%09%09%09++%09++%09%09+%09++%09+%09%09%09+%09+++%09%09++%09+%09+%09+%09%09%09%09%09+%09%09++%09+%09+%09%09+%09%09%09++%09%09++%09++%0D%0A%09%0D%0A+++++%09%0D%0A%09+++%0D%0A+%0D%0A+%09%09%09+%09%09%09+%09%09%09++%09++%09%09+%09++%09+%09%09%09+%09+++%09%09++%09+%09%0D%0A%0D%0A+++%09%09%09+%09%09%09+%09%09%09++%09++%09%09+%09++%09+%09%09%09+%09+++%09%09++%09+%09+%09+%09%09%09%09%09+%09%09++%09+%09+%09%09+%09%09%09++%09%09++%09++%0D%0A+%0D%0A%0D%0A+%0D%0A%0D%0A%0D%0A%09%0D%0A%0D%0A+++%09%09%09++%09++%09%09++%09+%09+%09%09++++%09+%09%09++%09++%0D%0A+%0D%0A++%0D%0A+%09%0D%0A%09+%09%09%09+%0D%0A++++%09+%09+%0D%0A%09++%09%0D%0A%09++%09%09%09++%09++%09%09++%09+%09+%09%09++++%09+%09%09++%09+++%09+%09%09%09%09%09+%09%09++%09+%09+%09%09+%09%09%09++%09%09++%09++%0D%0A+%0D%0A%0D%0A+++%09%0D%0A%09+++%0D%0A+%0D%0A+%09%09%09++%09++%09%09++%09+%09+%09%09++++%09+%09%09++%09++%0D%0A%0D%0A+++%09%09%09++%09++%09%09++%09+%09+%09%09++++%09+%09%09++%09+++%09+%09%09%09%09%09+%09%09++%09+%09+%09%09+%09%09%09++%09%09++%09++%0D%0A+%0D%0A%0D%0A+++%09%0D%0A%09+++++++%0D%0A%09%09+%0D%0A%09%0D%0A%0D%0A+++%09%09+%09%09%09++%09%09++%09+%09+%09%09%09+%09%09%09+%09%09+%09%09+++%09%09+%09++%09+%09%09+%09%09%09++%09%09++%09+%09%0D%0A+++%09+%09+%0D%0A+++%09%09+%09%0D%0A%09%0D%0A++%09%0D%0A++%0D%0A%09)

**Comment by Alhadis** [comment]
Aye, and that's assuming the background colours remain associated with those scopes forever. Who's to say GitHub won't do a revamp of their site's syntax colouring scheme, and drop background colours from scopes altogether?

In other words, the best you can get is a flaky solution that looks like crap anyway.

**Comment by mhsjlw** [comment]
Ok. So it's not worth trying to add syntax highlighting (my original analysis). Should we just leave this pull request to die, or is there any chance someone will still want it.

**Comment by Alhadis** [comment]
Nah mate, shoot it in the head.

**Comment by Alhadis** [comment]
Anyway, for posterity's sake, a more *future-proof* way of injecting styling into Atom's text editor might be something like this:

```javascript
atom.workspace.observeTextEditors(editor => {
	const checkWhitespace = () => {
		const id = "whitespace-syntax-shiv";
		const el = editor.element;
		
		if(el.querySelector("#"+id))
			return;
		
		let style = document.createElement("style");
		style.id  = id;
		
		style.textContent = `
			:host .source.whitespace .char.tab{
				background: #f00 !important;
			}
			
			:host .source.whitespace .char.space{
				background: #00f !important;
			}
		`;
		
		el.shadowRoot.appendChild(style);
	};
	
	editor.onDidChangeGrammar(checkWhitespace);
	editor.onDidStopChanging(checkWhitespace);
});
```

Which works for small styling tweaks. If you needed anything heftier, you're better off adjusting that code to attach an external stylesheet instead.

**Comment by Alhadis** [comment]
BTW, I feel I should stress that the syntax highlighting isn't the main problem here. The problem is the Whitespace language doesn't have enough widespread usage on GitHub (as it would appear).

So even *if* the highlighting were working on GitHub, that still wouldn't have any bearing on this PR's chances of getting accepted. =)

**Pull request closed without merging**
