### PR TITLE
Add colours to many languages

### LINKED ISSUE #5003: List of languages without a colour
Continuing from #4506. 49% (280) languages currently do not have a language assigned and show as grey (a lot of these are grouped languages that GitHub shows ungrouped in search results).

List generated with https://gist.github.com/wopian/8639e5d24119cbd99548b73c18321686

## Early Sidenotes

- Languages without a logo or no other clear branding are being skipped. 

- If the language has no logo and is developed by a sole company, their logo/brand is used.

- If a logo consists of multiple colours, I've listed them by most dominant (or in the case of Blitz, least blinding).

- Will try and do 2 or more letters per day.

## Key

🙅 = No logo, no brand or lack of info for language
❓ = No suitable colour, but is grouped into a language that has a colour

### Numbers

- [ ] 4D `#004289` (source: [brand](https://4d.com))

### A

- [ ] ~ABNF~ 🙅
- [ ] ~ASL~ 🙅
- [ ] ~ASN.1~ 🙅 
- [ ] Adobe Font Metrics `#fa0f00` (source: Adobe)
- [ ] Alpine Abuild `#0D597F` (grouped in `Shell`, source: [Alpine logo](#0D597F))
- [ ] Altium Designer `#A89663` (source: [Altium Designer logo](https://en.wikipedia.org/wiki/Altium_Designer))
- [ ] Ant Build System `#A9157E` (source: [Apache Ant logo](https://en.wikipedia.org/wiki/Apache_Ant))
- [ ] ApacheConf `#D12127` (source: [Apache logo](http://httpd.apache.org/docs/2.4/configuring.html)
- [x] ~Apollo Guidance Computer (grouped in `Assembly`)~ #5001
- [ ] ~AsciiDoc~ 🙅 Blue header? https://asciidoc.org/
- [ ] Augeas `#9CC134`, `#65a703` or `#ebf8d5` (source: [logo and brand](https://augeas.net/docs/language.html))
- [ ] Avro IDL `#0040FF` (source: [Apache Avro logo](https://avro.apache.org/docs/1.9.2/idl.html))
- [ ] ~Awk~ 🙅

### B

- [ ] ~Befunge~ 🙅
- [ ] BibTeX (grouped in `TeX`) ❓ Use green from `Tex`? (logo is black text)
- [x] ~Bison (grouped in `Yacc`) ❓ Use colour from `Yacc`? (logo is a black & white image)~ #5001
- [ ] ~BitBake~ 🙅
- [ ] BlitzBasic `#00D8FF`, `#00FFAE` (source: [Blitz BASIC logo](https://en.wikipedia.org/wiki/Blitz_BASIC) - jeez)
- [ ] Bluespec `#12223C` (source: [Bluespec logo](https://github.com/bluespec))
- [ ] Brightscript `#662D91` (source: [Roko Brightscript logo](https://developer.roku.com/en-gb/docs/references/brightscript/language/brightscript-language-reference.md))

### C

- [ ] C-ObjDump ❓ Use colour from `C`?
- [ ] C2hs Haskell (grouped in `Haskell`) ❓ Use purple from `Haskell`?
- [ ] ~CLIPS~ 🙅 Maybe http://www.clipsrules.net/ https://sourceforge.net/projects/clipsrules/
- [ ] CMake `#A3A3A3`, `#01BD00`, `#3132B9` or `#DA3434` (source: [logo](https://en.wikipedia.org/wiki/CMake))
- [ ] ~COBOL~ 🙅
- [ ] COLLADA `#F1A42B` (source: [logo](https://en.wikipedia.org/wiki/COLLADA))
- [ ] ~CSV~ 🙅
- [ ] ~CWeb~ 🙅
- [ ] Cabal Config `#483465` (source: [brand colours](https://www.haskell.org/cabal/))
- [ ] Cap'n Proto `#C42727` (source: [brand colours](https://capnproto.org/))
- [ ] CartoCSS ❓ Use colour from `CSS`?
- [ ] ~Charity~ 🙅
- [ ] ChucK `#3F8000`, `#80FF00` or `#FF8500` (source: [logo](https://en.wikipedia.org/wiki/ChucK))
- [ ] Closure Templates (grouped in `HTML`) ❓ Use colour from `Closure` or `HTML`?
- [ ] Cloud Firestore Security Rules `#FFCA28`, `#FFA000` or `#F57C00` (source: [Firebase branding](https://firebase.google.com/brand-guidelines))
- [ ] ~CoNLL-U~ 🙅
- [ ] CodeQL `#5C31FF`, `#5c31ff` or `#151046` (source: https://semmle.com/codeql)
- [x] ~ColdFusion CFC (grouped in `ColdFusion`)~ #5001
- [ ] ~Cool~ 🙅
- [ ] Coq `#CFB486` or `#CCA073` (source: [logo](https://en.wikipedia.org/wiki/Coq))
- [ ] Cpp-ObjDump ❓ Use colour from `C++`?
- [ ] ~Creole~ 🙅
- [ ] Csound `#343433` (source: [logo](https://csound.com/))
- [ ] Csound Document `#343433` (source: [logo](https://csound.com/))
- [ ] Csound Score `#343433` (source: [logo](https://csound.com/))
- [ ] ~Cycript~ 🙅
- [ ] Cython `#3572A5` (grouped in `Python`)
- [ ] ~cURL Config (grouped in `INI`)~ 🙅

### D

- [ ] D-ObjDump ❓ Use colour from `D`?
- [ ] ~DIGITAL Command Language~ 🙅
- [ ] ~DNS Zone~ 🙅
- [ ] ~DTrace~ 🙅 Appears to have a mascot that uses an orange/pink/purple theme
- [ ] Darcs Patch (source: [logo](https://en.wikipedia.org/wiki/Darcs), but its a gradient from white to 100% green)
- [ ] ~Diff~ 🙅
- [ ] DirectX 3D File (source: [logo](https://en.wikipedia.org/wiki/DirectX), another white to green gradient)
- [ ] ~desktop~ 🙅
- [ ] ~dircolors~ 🙅

### E

- [ ] ~EBNF~ 🙅
- [ ] ECLiPSe `#AFEEFF`, `#00FFFF` or `#0057D7` (grouped in `prolog`, source: [logo and brand](http://eclipseclp.org/))
- [x] ~EJS (grouped in `HTML`)~ #5001
- [ ] ~EML~ 🙅
- [ ] ~Eagle~ 🙅
- [ ] Easybuild `#2A72ED`, `#069406` or `#B50811` (grouped in `Python`, source: [logo](https://easybuild.readthedocs.io/en/latest/))
- [ ] Ecere Projects `#913960` (grouped in `JavaScript`) Configuration for `eC` (use same as language itself)
- [ ] EditorConfig `#E0EFEF`, `#FEFEFE` or `#FFF2F2` (grouped in `INI`, source: [logo and brand](https://editorconfig.org/))
- [ ] ~Edje Data Collection~ 🙅
- [ ] ~edn~ 🙅

### F

- [ ] FIGlet Font `#FFDDBB` (source: [brand](http://www.figlet.org/))
- [ ] Filebench WML `#FFC000` (source: [org logo](https://github.com/filebench))
- [ ] ~Filterscript (grouped in `RenderScript`)~ 🙅
- [ ] ~Formatted~ 🙅
- [ ] Fortran Free Form `#4d41b1` (grouped in `Fortran`, source: same as `Fortran`)
- [ ] fish `#4AAE47` or `#4A9BC8` (grouped in `Shell`, source: [logo](https://fishshell.com/))

### G

- [ ] GAMS `#F39619` or `#2b1a02` (source: [logo](https://www.gams.com/img/gams_logo.svg))
- [ ] GAP `#0000ff` or `#ccffff` (source: [site](https://www.gap-system.org))
- [ ] GCC Machine Description `#FFCFAB`, `#AB9A7E` or `#F39105` (source: [logo](https://en.wikipedia.org/wiki/GNU_Compiler_Collection))
- [ ] ~GDB~ 🙅 Black & white logo
- [ ] GEDCOM `#003058` OR `#86B940`, `#9C947A` or `#BBB7B1` (first source: [logo of LDS Church (developers)](https://en.wikipedia.org/wiki/The_Church_of_Jesus_Christ_of_Latter-day_Saints), second source: [logo of FamilySearch (operated by LDS and uses GEDCOM today)](https://en.wikipedia.org/wiki/GEDCOM#Versions)
- [ ] GLSL `#5586A4` (source: [openGL brand](https://www.khronos.org/legal/trademarks/))
- [ ] ~GN~ 🙅 Generate Ninja - No logo or branding
- [ ] Genshi `#cc0000` or `#D5200C` (source: [branding and Edgewall logo](https://genshi.edgewall.org/))
- [ ] Gentoo Ebuild `#beb8db`, `#54487a` or `#9400FF` (grouped in `Shell`, source: [brand](https://www.gentoo.org/))
- [ ] Gentoo Eclass `#beb8db`, `#54487a` or `#9400FF` (grouped in `Shell`, source: [brand](https://www.gentoo.org/))
- [ ] Gerber Image `#D01F25` or #D20B00` (source: [logo or branding](https://www.ucamco.com/en/gerber))
- [ ] Gettext Catalog `#a42e2b` (source: [GNU branding](https://www.gnu.org/software/gettext/manual/index.html))
- [ ] Git Attributes `#F44D27` (grouped in `INI`, source: [logo](https://git-scm.com/))
- [ ] Git Config `#F44D27` (grouped in `INI`, source: [logo](https://git-scm.com/))
- [ ] Glyph Bitmap Distribution Format `#fa0f00` (source: Adobe)
- [ ] Grace `#615f8b` (source: [brand](http://gracelang.org/applications/))
- [ ] Gradle `#02303A` (source: [logo and brand](https://gradle.org/))
- [ ] ~Graph Modeling Language~ 🙅
- [ ] GraphQL `#e10098` (source: [logo](https://graphql.org/img/logo.svg))
- [ ] Graphviz (DOT) ❓ [complex logo](https://graphviz.org/) with conflicting site branding (and a different favicon logo)
- [ ] Groovy Server Pages (grouped in `Groovy`) `#76A8B8` (source: [repo logo](https://github.com/apache/groovy)) OR `#4298B8` or `#46A5C8` (source: [branding and site logo](https://groovy-lang.org/))
  - Groovy itself is orange on Linguist for some reason and I don't think it ever had an orange logo or branding going on - so may want to opt for Groovy's orange or raise an issue with Groovy maintainers/users

### H

- [ ] HAProxy `#3D6DA5` (source: [centre square from logo](https://www.haproxy.org/))
- [ ] HCL `#000000` (source: [logo and brand](https://www.hashicorp.com/))
- [ ] ~HLSL~ 🙅 No logo, proprietary shader language for DirectX by Microsoft
- [ ] HTML+Django `#20AA76` or `#0C4B33` (grouped in `HTML`, source: [branding](https://www.djangoproject.com/))
- [ ] HTML+ECR `#000100` or `#2E1052` (grouped in `HTML`, source: [logo (matching Crystal on Linguist) or brand accent](https://crystal-lang.org/api/0.35.1/ECR.html))
- [ ] HTML+EEX `#6e4a7e` (grouped in `HTML`, source: [logo (matching Elixir on Linguist)](https://elixirschool.com/en/lessons/specifics/eex/))
- [ ] HTML+ERB `#701516` (grouped in `HTML`, source: matching Ruby on Linguist)
- [ ] HTML+PHP `#4F5D95` (grouped in `HTML`, source: matching PHP on Linguist)
- [ ] HTML+Razor `#512BD4` (grouped in `HTML`, source: [.NET logo](https://github.com/dotnet) and [branding](https://dotnet.microsoft.com/))
- [ ] ~HTTP~ 🙅
- [ ] HXML `#f68712` or `#DF7B12` (source: [Haxe logo](https://haxe.org/manual/compiler-usage-hxml.html))
- [ ] ~HyPhy~ 🙅

### I

- [ ] ~INI~ 🙅
- [ ] ~IRC log~ 🙅
- [ ] Ignore List `#F44D27` (grouped in `INI`) (source: [logo](https://git-scm.com/)) `.gitignore`
- [ ] Inform 7 ❓ [complex logo](http://inform7.com/)
- [ ] Inno Setup `#264b99` (source: [brand](https://jrsoftware.org/isinfo.php))
- [ ] Isabelle ROOT `#FEFE00`, `#CECEE7` or `#CE4A4A` (grouped in `Isabelle`, source: yellow matching Isabelle on Linguist, [other two from logo](https://isabelle.in.tum.de/))

### J

- [x] ~JFlex (grouped in `Lex`)~ #5001
- [ ] JSON `#3e3e3e` (source: average of gradient logo](https://www.json.org/json-en.html))
- [ ] JSON with Comments `#3e3e3e` (grouped in `JSON`) ❓ Same as JSON
- [ ] JSON5 `#267CB9` (source: [branding](https://json5.org/))
- [ ] JSONLD `#0C479C` (source: [logo](https://github.com/json-ld)
- [ ] JSX `#f1e05a` (grouped in `JavaScript`, source: matching Javascript on Linguist)
- [ ] Jasmin ❓ [complex logo](http://jasmin.sourceforge.net/)
- [ ] Java Properties `#b07219` (source: matching Java on Linguist)
- [ ] Java Server Pages `#b07219` OR `#f98200` or `#FEB940` (grouped in `Java`, source: matching Java on Linguist OR [Jakarta logo or branding](https://jakarta.ee/))
  - Java Server Pages appears to have been rebranded[(https://en.wikipedia.org/wiki/Jakarta_Server_Pages) as Jakarta Server Pages at some point
- [ ] JavaScript+ERB `#701516` (grouped in `JavaScript`, source: matching Ruby on Linguist)
- [ ] Jison `#56B3CB` (grouped in `Yacc`, source: [logo and branding](https://zaa.ch/jison/docs/)) 
- [ ] Jison Lex `#56B3CB` (grouped in `Lex`, source: [logo and branding](https://zaa.ch/jison/docs/)) 

### K

- [ ] KiCad Layout `#2f4aaa`, `#1a2a60` or `#f77300` (source: [logo](https://gitlab.com/kicad))
- [ ] KiCad Legacy Layout `#2f4aaa`, `#1a2a60` or `#f77300` (source: [logo](https://gitlab.com/kicad))
- [ ] KiCad Schematic `#2f4aaa`, `#1a2a60` or `#f77300` (source: [logo](https://gitlab.com/kicad))
- [ ] Kit `#2deada`, `#1dba9d` or `#227d6b` (source: [logo](https://www.kitlang.org/))

### L

- [ ] ~LTspice Symbol~ 🙅
- [ ] LabVIEW `#fede06` (source: [logo](https://en.wikipedia.org/wiki/LabVIEW#/media/File:LabVIEW_Logo.jpg))
- [ ] ~Lean~ 🙅
- [ ] LilyPond `#587E55` (source: average of [logo](https://lilypond.org/))
- [ ] ~Limbo~ 🙅
- [ ] ~Linker Script~ 🙅
- [ ] ~Linux Kernel Module~ 🙅
- [ ] Liquid `#3399cc` (source: [branding](https://shopify.github.io/liquid/))
- [ ] Literate Agda `#315665`) (grouped in `Agda`, source: same as Agda in Linguist)
- [ ] Literate CoffeeScript `#244776` (grouped in `CoffeeScript`, source: same as CoffeeScript in Linguist)
- [ ] Literate Haskell `#5e5086` (grouped in `Haskell`, source: same as Haskell in Linguist)
- [ ] ~Logos~ 🙅
- [ ] ~Logtalk~ 🙅 [solid black logo](https://github.com/LogtalkDotOrg)
- [ ] ~LoomScript~ 🙅 [solid black logo](http://loomsdk.com/)

### M

- [ ] M
- [ ] M4
- [ ] M4Sugar (grouped in `M4`)
- [ ] MUF (grouped in `Forth`)
- [ ] Mako
- [ ] Mathematica
- [ ] Maven POM
- [ ] MediaWiki
- [ ] Microsoft Developer Studio Project
- [ ] MiniD
- [ ] Modelica
- [ ] Modula-2
- [ ] Module Management System
- [ ] Monkey
- [ ] Moocode
- [ ] MoonScript
- [ ] Motorola 68K Assembly (grouped in `Assembly`)
- [ ] Muse
- [ ] Mustache (grouped in `HTML`)
- [ ] Myghty
- [ ] mupad

### N

- [ ] NASL
- [ ] NEON
- [ ] NL
- [ ] NPM Config (grouped in `INI`)
- [ ] NSIS
- [ ] Nginx
- [ ] Ninja
- [x] ~NumPy (grouped in `Python`)~ #5001
- [ ] nanorc (grouped in `INI`)

### O

- [ ] ObjDump
- [ ] Object Data Instance Notation
- [ ] Opa
- [ ] Open Policy Agent
- [ ] OpenCL (grouped in `C`)
- [ ] OpenEdge ABL
- [ ] OpenRC runscript (grouped in `Shell`)
- [ ] OpenSCAD
- [ ] OpenStep Property List
- [ ] OpenType Feature File
- [ ] Org
- [ ] Ox

### P

- [ ] PLpgSQL
- [ ] POV-Ray SDL
- [ ] Parrot Assembly (grouped in `Parrot`)
- [ ] Parrot Internal Representation (grouped in `Parrot`)
- [ ] Pic (grouped in `Roff`)
- [ ] Pickle
- [ ] PicoLisp
- [ ] PlantUML
- [ ] Pod
- [ ] Pod 6
- [ ] Pony
- [ ] PostCSS (grouped in `CSS`)
- [ ] Proguard
- [ ] Protocol Buffer
- [ ] Public Key
- [ ] Pure Data
- [ ] Python console (grouped in `Python`)
- [ ] Python traceback (grouped in `Python`)

### Q

- [ ] QMake

### R

- [ ] RDoc
- [ ] REALbasic
- [ ] REXX
- [ ] RMarkdown
- [ ] RPC
- [ ] RPM Spec
- [ ] Raw token data
- [ ] Readline Config (grouped in `INI`)
- [ ] Redcode
- [ ] Regular Expression
- [ ] ~RenderScript~ 🙅
- [ ] Rich Text Format
- [ ] RobotFramework
- [ ] Roff Manpage (grouped in `Roff`)
- [ ] reStructuredText

### S

- [ ] SMT
- [ ] SPARQL
- [ ] SQL
- [ ] SQLPL
- [ ] SSH Config (grouped in `INI`)
- [ ] STON (grouped in `Smalltalk`)
- [ ] SWIG
- [ ] Sage
- [ ] Scaml (grouped in `HTML`)
- [ ] Scilab
- [ ] ShaderLab
- [ ] ShellSession
- [ ] Sieve
- [ ] Smali
- [ ] Smarty
- [ ] Spline Font Database
- [ ] Stata
- [ ] SubRip Text
- [ ] SugarSS (grouped in `CSS`)

### T

- [ ] TLA
- [ ] TOML
- [ ] TSQL
- [ ] TSV
- [ ] TSX (grouped in `TypeScript`)
- [ ] TXL
- [ ] Tcsh (grouped in `Shell`)
- [ ] Tea
- [ ] Texinfo
- [ ] Text
- [ ] Textile
- [ ] Thrift
- [ ] Turtle
- [ ] Type Language

### U

- [x] ~Unified Parallel C (grouped in `C`)~ #5001
- [ ] Unity3D Asset
- [ ] Unix Assembly (grouped in `Assembly`)
- [ ] UrWeb

### V

- [ ] Vim Help File
- [ ] Vim Snippet

### W

- [ ] Wavefront Material
- [ ] Wavefront Object
- [ ] Web Ontology Language
- [ ] WebIDL
- [ ] WebVTT
- [ ] Wget Config (grouped in `INI`)
- [ ] Windows Registry Entries
- [ ] World of Warcraft Addon Data

### X

- [ ] X BitMap (grouped in `C`)
- [ ] X Font Directory Index
- [ ] X PixMap (grouped in `C`)
- [ ] XCompose
- [ ] XML
- [ ] XML Property List (grouped in `XML`)
- [ ] XPages
- [ ] XProc
- [ ] XS
- [ ] Xojo
- [ ] Xtend

### Y

- [ ] YANG

### Z
- [ ] Zeek
- [ ] Zimpl

### PR DESCRIPTION
**Pull request by Nixinova**
## Description
Adds colours to pretty much all languages (100+) that are without one currently.
Resolves #5003 (mostly)

## Checklist:

- [x] **I am changing the color associated with a language**
  
  - [ ] I have obtained agreement from the wider language community on this color change.

## Colours

- 4D: `#004289` from [logo on 4d.com](https://us.4d.com/)
- Adobe Font: `#fa0f00` from Adobe logo
- Alpine Abuild: `#0D597F` from [Apine logo](https://wiki.alpinelinux.org/)
- Altium Designer: `#A89663`: from [logo](https://en.wikipedia.org/wiki/File:Altium_Designer_Logo.png)
- Ant Build: `#A9157E` from [Ant logo](https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Apache-Ant-logo.svg/250px-Apache-Ant-logo.svg.png)
- ApachiConf: `#D12127`: from [Apache logo](http://httpd.apache.org/docs/2.4/configuring.html)
- Augeas: `#9CC134` from [logo](https://augeas.net/docs/language.html)
- AsciiDoc: `#73a0c5` from [branding](https://asciidoc.org/)
- Avro IDL: `#0040FF` from [avro logo](https://avro.apache.org/docs/1.9.2/idl.html)
- BitBake `#00bce4` from [developer logo](http://www.openembedded.org/wiki/Main_Page) enwp.org/BitBake
- BLitzBasic: `#00FFAE` from [logo](https://en.wikipedia.org/wiki/File:BlitzBasicLogo.gif)
- Bluespecs; `#12223c`: from [logo](https://github.com/bluespec)
- BibTeX: `#778899` from [branding](http://www.bibtex.org/)
- BrightScript `#662D91`: from [branding](https://developer.roku.com/en-gb/docs/references/brightscript/language/brightscript-language-reference.md)
- Cabal Config: `#483465` from [branding](https://www.haskell.org/cabal/)
- Capn Proto `#c42727` from [branding](https://capnproto.org/)
- Chuck: `#3f8000` from [logo](https://commons.wikimedia.org/wiki/File:ChucK_logo2.jpg)
- CLIPS: `#00a300` from [logo](http://www.clipsrules.net/AboutCLIPS.html)
- Cloud Firebase *: `#FFA000` from [branding](https://firebase.google.com/brand-guidelines)
- Collada: `#F1A42B` from [logo](https://en.wikipedia.org/wiki/File:COLLADA_logo_vect.svg)
- Coq: `#d0b68c` from [logo](https://coq.inria.fr/)
- CodeQL: `#140f46` from [branding](https://semmle.com/codeql)
- Cmake: `#DA3434` from [logo](https://commons.wikimedia.org/wiki/File:Cmake.svg)
- CSound `#1a1a1a` from [logo](https://csound.com/)
- CSound Document `#1a1a1a` from [logo](https://csound.com/)
- CSound Score: `#1a1a1a` from [logo](https://csound.com/)
- CSV: `#237346`: from MS Excel branding
- Cweb `#00007a` from [book title](https://www-cs-faculty.stanford.edu/~knuth/cweb.html)
- Darcs Patch: `#8eff23` from [logo](https://en.wikipedia.org/wiki/Darcs#/media/File:Darcs-logo.png)
- DirectX 3D: `#aace60` from [DirectX9 logo](https://en.wikipedia.org/wiki/File:Directx9.png)
- Easybuild `#069406` from [logo/branding](https://docs.easybuild.io/en/latest/)
- Ecere Project: `#913960` from eC
- Eclipse: `#001d9d` from [logo](http://eclipseclp.org)
- EditorConfig: `#fff1f2`: from [logo](https://editorconfig.org)
- FIlebench-WML: `#F6B900` from [org logo](https://github.com/filebench)
- Figlet: `#FFDDBB` from [branding](http://www.figlet.org/)
- Fish: `#4aae47` from [logo](https://fishshell.com/)
- Fortran Freeform `#4d41b1` from Fortran
- Gap: `#0000cc` from [logo](https://www.gap-system.org/)
- Gams: `#f49a22` from [logo](https://www.gams.com/)
- GCC: `#ffcfab` from [logo](https://commons.wikimedia.org/wiki/File:GNU_Compiler_Collection_logo.svg)
- Gedcom: `#003058` from [dev logo](https://en.wikipedia.org/wiki/File:SymbolofLatter-daySaintchurch.png) [[not joking](https://www.familysearch.org/developers/docs/guides/gedcom#:~:text=GEDCOM%20is%20also%20the%20name,tree%20software%20programs%20and%20websites.)]
- Genshi `#951531` from [tagline](https://genshi.edgewall.org/)
- Gentoo Ebuild: `#9400ff`: From [Gentoo branding](https://Gentoo.org)
- Gentoo Eclass: `#9400ff`: From [Gentoo branding](https://Gentoo.org)
- Gerber: `#D20B00` from [branding](https://ucamco.com/en/gerber)
- Git Attributes: `#F44D27`: from [Git logo](https://git-scm.com)
- Git Config: `#F44D27`: from [Git logo](https://git-scm.com)
- GLSL: `#5686a5`: from [OpenGL logo](https://commons.wikimedia.org/wiki/File:OpenGL_logo_(2D).svg)
- Grace: `#615f8b` from [branding](http://gracelang.org/)
- Gradle: `#02303a`: from [logo](https://Gradle.org)
- Graphviz DOT: `#2596be`: From lines in [logo](https://en.wikipedia.org/wiki/File:GraphvizLogo.png)
- Groovy Server Pages: `#4298b8`: From new Groovy #5418
- HaProxy: `#106da9` from [logo](https://www.haproxy.org/)
- HLSL: `#aace60`: from DirectX logo (HLSL uses Direct3D)
- HTML+ECR: `#2e1052`: From [ECR branding](https://crystal-lang.org/api/0.35.1/ECR.html)
- HTML+EEX: `#6e4a7e`: From [EEX branding](https://elixirschool.com/en/lessons/specifics/eex)
- HTML+ERB: `#701516`: From Ruby
- HTML+PHP: `#4f5d95`: From PHP
- HTML+Razor: `#512be4`: From .[NET logo](https://commons.wikimedia.org/wiki/File:.NET_Logo.svg)
- HTTP `#005c9c`: From [logo](https://en.m.wikipedia.org/wiki/File:HTTP_logo.svg)
- HXML: `#f68712`: From [HAXE logo](https://haxe.org)
- INI: `#d1dbe0`: from [Windows file icon](https://en.wikipedia.org/wiki/File:INI_file_icon.png)
- Ignore List: `#000000`: black as in blacklist
- Inno Setup: `#264b99`: from [branding](http://jrsoftware.org/isinfo.php)
- Isabelle root: `#FEFE00` from Isabelle
- Jasmin: `#d03600`: from fish in [logo](http://jasmin.sourceforge.net)
- JSON with Comments: `#292929`: from JSON
- JSON5: `#267CB9`: From https://json5.org
- JSONLD: `#0c479c`: From https://json-ld.org
- Java Properties: `#2A6277`: from new Java #5384
- Java Server Pages: `#2A6277`: from new Java #5384
- JavaScript+ERB: `#f1e05a`: from JS
- Jison: `#56b3cb` from [logo](https://web.archive.org/web/20180101091202/http://zaa.ch/jison)
- Jison Lex: `#56b3cb` from [Jison logo](https://web.archive.org/web/20180101091202/http://zaa.ch/jison)
- KiCad Layout: `#2f4aab`: From [KiCad logo](https://gitlab.com/kicad)
- KiCad Legacy Layout: `#2f4aab`: From [KiCad logo](https://gitlab.com/kicad)
- KiCad Schematic: `#2f4aab`: From [KiCad logo](https://gitlab.com/kicad)
- Labview `#fede06`: from [logo](https://en.wikipedia.org/wiki/File:LabVIEW_Logo.jpg)
- Literate Agda: `#315665`: from Agda
- Literate Coffeescript: `#244776` from Coffeescript
- Literate Haskell: `#5e5086` from Haskell
- Logtalk `#295b9a` from [branding](https://logtalk.org/)
- Mako `#7e858d`: from [logo](https://www.makotemplates.org/)
- Mathematica: `#dd1100` from [logo](https://www.wolfram.com/mathematica/)
- Modelica: `#de1d31` from [accent color](https://modelica.org/)
- Modula2: `#10253f` from [logo](https://www.modula2.org/)
- Moonscript `#ff4585`: from [logo](https://github.com/leafo/moonscript)
- Motorola 48k Asm: `#005daa` from [motorola logo](https://en.wikipedia.org/wiki/Motorola#/media/File:Motorola.svg)
- Mupad: `#244963` from part of [logo](https://en.wikipedia.org/wiki/File:MuPADCube.png)
- Nginx: `#009639` from [logo](https://www.nginx.com/)
- NPM Config: `#cb3837`: from [npm logo](https://commons.wikimedia.org/wiki/File:Npm-logo.svg)
- Nanorc: `#2d004d`: from [Nano logo](https://commons.wikimedia.org/wiki/File:Gnu-nano.svg)
- OpenCL: `#ed2e2d` from [prominent logo colour](https://developer.nvidia.com/opencl)
- OpenPolicyAgent: `#7d9199` from [logo](https://www.openpolicyagent.org/)
- OpenEdge `#5ce600` from [dev logo](https://en.wikipedia.org/wiki/File:OpenEdge_logo.png)
- OpenScad `#e5cd45`: From [logo](https://openscad.org/)
- PLpgSQL: `#336790`: form [logo](https://commons.wikimedia.org/wiki/File:Postgresql_elephant.svg)
- Picolisp: `#6067af` from [logo](https://picolisp.com/wiki/?home)
- PostCSS: `#dc3a0c` from [logo](https://github.com/postcss/postcss)
- Pov Ray: `#6bac65` from part of [logo](https://commons.wikimedia.org/wiki/File:Povray_logo_sphere.png)
- Python console: `#3572A5`: from Python
- Python traceback: `#3572A5`: from Python
- RDoc: `#701516`: From Ruby
- ReStructuredText: `#141414`: From [text logo](https://docutils.sourceforge.io/rst.html)
- Rexx: `#d90e09` from [logo](https://en.wikipedia.org/wiki/File:Rexx-img-lg.png)
- RMarkdown: `#198ce7`: From R
- Robot Framework: `#00c0b5` from [branding](https://robotframework.org/)
- Roff Manpage: `#ecdebe`: From Roff
- Scilab `#ca0f21`: from [logo](https://www.scilab.org/)
- SQL: `#e38c00`: from [MySQL logo](https://download.logo.wine/logo/MySQL/MySQL-Logo.wine.png)
- SQLPL: `#e38c00`: from [MySQL logo](https://download.logo.wine/logo/MySQL/MySQL-Logo.wine.png)
- ShaderLab: `#222c37`: from [Unity logo](https://commons.wikimedia.org/wiki/File:Official_unity_logo.png)
- Smarty: `#f0c040` from [logo](https://en.wikipedia.org/wiki/File:Smarty-logo.png)
- SparQL: `#0c4597` from [apparent logo](https://www.google.com/search?q=SPARQL+logo&tbm=isch)
- Stata: `#1a5f91` from [logo](https://www.stata.com/why-use-stata/)
- SubRip Text: `#9e0101`: From [branding](http://zuggy.wz.cz)
- SugarSS: `#2fcc9f`: from [logo](https://github.com/postcss/sugarss)
- Textile: `#ffe7ac`: form [logo](https://textile-lang.com/)
- TOML: `#9c4221`: From [logo](https://TOML.io)
- Thrift: `#D12127`: from [Apache logo](http://httpd.apache.org/docs/2.4/configuring.html)
- TSQL: `#e38c00` from [MySQL logo](https://download.logo.wine/logo/MySQL/MySQL-Logo.wine.png)
- TSV: `#237346`: from MS Excel branding
- TSX: `#2b7489`: From TypeScript
- TXL `#0178b8`: From [logo](https://www.txl.ca/)
- TLA: `#4b0079` from [logo](https://en.wikipedia.org/wiki/File:TLA%2B_logo_splash_image.png)
- Unity Asset: `#222c37`: from [Unity logo](https://commons.wikimedia.org/wiki/File:Official_unity_logo.png)
- UrWeb: `#ccccee` from [branding](http://www.impredicative.com/ur/)
- Vim Help: `#199f4b` from Vim
- Vim snippit: `#199f4b` from Vim
- Web Ontology: `#5b70bd` from [apparent logo](https://www.google.com/search?q=web+ontology+Language+logo&tbm=isch)
- WIndows Registry: `#52d5ff` from [editor logo](https://en.wikipedia.org/wiki/File:Registry_Editor_icon.png)
- WoW Addon: `#f7e43f` form [logo text](https://upload.wikimedia.org/wikipedia/en/thumb/9/91/WoW_Box_Art1.jpg/220px-WoW_Box_Art1.jpg)
- Wikitext: `#fc5757`: From [MediaWiki logo](https://commons.wikimedia.org/wiki/File:MediaWiki-2020-logo.svg)
- XML: `#0060ac`: From [logo](https://w3.org/Icons/XML/xml.svg)
- XML Property List: `#0060ac`: From XML
- Xojo: `#81bd41` from [logo](https://www.xojo.com/)
- Xtend `#24255d`: From [logo](https://commons.wikimedia.org/wiki/File:Xtend-logo-c.png)
- Zimpl: `#d67711` from [branding](https://zimpl.zib.de/)

### CODE REVIEW

**Comment by lildude** [comment]
I'm going to be a PITA and ask you to please list the reasoning for each of the colours selected in the OP for easy reference later.

**Comment by Nixinova** [comment]
> I'm going to be a PITA and ask you to please list the reasoning for each of the colours selected in the OP for easy reference later.

Done

**Comment by Nixinova** [comment]
I think I can (try to) get through all of #5003...

**Comment by Nixinova** [comment]
Looked through all the languages and added colours.

**Review by lildude — APPROVED** [review]
Nothing glaringly wrong with these. Thanks. 🙇

**Pull request merged**
