### PR TITLE
Add Archimate

### PR DESCRIPTION
**Pull request by rogerkohler**
Added Archimate to the list

## Description

Archimate is a modeling tool used for Enterprise Architecture efforts standardized by The Open Group.

## Checklist:

- [ ] **I am adding a new language.**
  - [ ] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AARCHIMATE
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - https://github.com/rogerkohler/MapaAplicacionesBci
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

### CODE REVIEW

**Comment by rogerkohler** [comment]
https://github.com/search?utf8=%E2%9C%93&q=extension%3Aarchimate+NOT+nothack&type=Code [507 code results]

**Comment by pchaigno** [comment]
This is an XML format, it should be added as a new extension for XML.
Please also follow the contribution guidelines.

**Comment by lildude** [comment]
This is also no popular enough for inclusion at this time.

**Comment by pchaigno** [comment]
Closing in favor of #4219. We'll monitor the popularity of the extension there.

If you have an improved search query compared to the one used in #4219, please post it here and I'll update #4219.

**Comment by pchaigno** [comment]
If #4222 is accepted, it should automatically classify most `.archimate` files as XML and we won't require this pull request anymore.

**Pull request closed without merging**
