### PR TITLE
Release v7.17.0

### PR DESCRIPTION
**Pull request by lildude**
It's been a while, but I've finally managed to carve out time to make a new release.

- [x] Gem pushed to RubyGems & GitHub Package Registry 
- [x] Deployed to GitHub.com - this will happen on 20 Oct '21
- [x] Grammars deployed to Syntax highlighting service - highlighting won't be 💯 up-to-date until this happens - this will happen on 20 Oct '21
- [x] Deployed to Lightshow

### CODE REVIEW

**Comment by lildude** [comment]
Took advantage of the [new auto-release note generation too](https://github.blog/changelog/2021-10-04-improvements-to-github-releases-public-beta/) using the defaults. Check 'em out - https://github.com/github/linguist/releases/tag/v7.17.0 - very 😍

**Comment by davidhq** [comment]
Hi! Is there approximate date for new release, do grammar authors need to do anything or will latest commits be picked up ? thank you

**Comment by lildude** [comment]
> Hi! Is there approximate date for new release

Early Feb at the earliest, but it depends on my workload at the time.

> do grammar authors need to do anything or will latest commits be picked up ? thank you

Nope. It happens automatically.

PS. 7.18.0 is the latest, released on 15 Dec 2021.

**Comment by davidhq** [comment]
> > Hi! Is there approximate date for new release
> 
> Early Feb at the earliest, but it depends on my workload at the time.

Nice, thank you

> 
> > do grammar authors need to do anything or will latest commits be picked up ? thank you
> 
> Nope. It happens automatically.

great

> 
> PS. 7.18.0 is the latest, released on 15 Dec 2021.

yes, I saw later, 
thank you again

**Comment by davidhq** [comment]
One more question perhaps - is there a 100% faithful way to test the grammar?

I found this https://github-lightshow.herokuapp.com/ and it's ok but for example `entity.name.type.class` should be colored brown instead of red.. I see `entity.name.type.class` in javascript 

```javascript
class Something { }
```

I couldn't find a way to make 100% sure how my grammar will impact minor colors so any advice would be great and then I can double-check in next days.

**Comment by lildude** [comment]
> One more question perhaps - is there a 100% faithful way to test the grammar?

Not really. Lightshow is the closest we've got.

> I found this https://github-lightshow.herokuapp.com/ and it's ok but for example `entity.name.type.class` should be colored orange
> 
> ```js
> class Something { }
> ```
> 
> instead of red (as it is in thos heroku app).
> 
> I couldn't find a way to make 100% sure how my grammar will impact minor colors so any advice would be great and then I can double-check in next days.

I'm not that well versed in writing grammars but @Alhadis is and he's got this [great reference](https://github.com/Alhadis/language-etc/blob/master/samples/lists/scope-previews.nanorc) for how the Textmate scope names match colours on GitHub.

There's also the important notes at https://github.com/github/linguist/pull/4568#issuecomment-513739638 to keep in mind regarding the ordering of the scopes.

If you want further help, please open a new [discussion](https://github.com/github/linguist/discussions) as this topic is no longer related to this release.

**Comment by Alhadis** [comment]
> I found this https://github-lightshow.herokuapp.com/ and it's ok but for example entity.name.type.class should be coloured orange

Lightshow's styling has been out-of-sync with that of GitHub for a while now, something made worse since the introduction of dark mode and deuteranopia support.

There might also be another reason for the discrepancy you're seeing, but it's very convoluted to explain unless you have an understanding of PrettyLights and how TextMate selectors differ from CSS selectors. I actually recently started work on an Atom theme to bring up-to-date styling to my editor so I can preview grammars more accurately as I work on them, although there's nothing to show yet.

Feel free to e-mail me directly if you don't want to open a [new discussion](https://github.com/github/linguist/discussions) for this. As @lildude mentioned, this thread is not the appropriate place for such a topic.

**Comment by davidhq** [comment]
OK thank you very much @lildude and @Alhadis ! Sorry for hijacking this thread a bit.
I might send an email next week when I get into finishing touches for an update.
@lildude this is awesome - https://github.com/Alhadis/language-etc/blob/master/samples/lists/scope-previews.nanorc , thank you

**Pull request merged**
