### PR TITLE
Improve Turing sample

### PR DESCRIPTION
**Pull request by MathBunny**
Improved the Turing sample code with commands including graphics, audio, conditionals, if statements, etc. This is a follow up from [here.](https://github.com/github/linguist/issues/2940)

### CODE REVIEW

**Comment by Alhadis** [comment]
Hey mate, glad you're willing to share!

Just a note, though: we prefer multiple fixtures, and there's often a mix of both complex and simple files. So the file should be added separately. =)

**Comment by MathBunny** [comment]
Hey. Thanks! I'm going to fix it in a bit and I'll try again :)

**Comment by Alhadis** [comment]
No problem. =)

BTW, there's no syntax highlighting for Turing on GitHub. I searched for an existing grammar, but nobody appears to have written one. Guess that's up to me, haha. I'll try to make time to research the language and write one up. =)

Is there a specification for the language I can use as reference?

**Comment by MathBunny** [comment]
Ah. Yeah :( I wish I could help you. Perhaps check [this link.](http://compsci.ca/holtsoft/doc/)

**Comment by MathBunny** [comment]
Just a question, do I just add the new file? Is that all, or do I have to modify another file for the linguist to know that I added a new sample program for Turing? Thanks!

**Comment by Alhadis** [comment]
Ah, that's perfect! Thanks!

No no, just add the file as you would normally. Linguist uses whatever's kept in the relevant sample directories. =) You should revert the changes to the original file so it becomes this again:

```
% Accepts a number and calculates its factorial

function factorial (n: int) : real
    if n = 0 then
        result 1
    else
        result n * factorial (n - 1)
   end if
end factorial

var n: int
loop
    put "Please input an integer: " ..
    get n
    exit when n >= 0
    put "Input must be a non-negative integer."
end loop

put "The factorial of ", n, " is ", factorial (n)
```

**Comment by MathBunny** [comment]
Awesome, thanks! This was fun. What is the GitHub CLA? Do I have to do that?

**Comment by Alhadis** [comment]
Ah, [details are here](https://cla.github.com/github/linguist/accept/MathBunny). It's just a standard process every contributor needs to agree to... a bit like an EULA, really. =)

**Comment by MathBunny** [comment]
Okay, I accepted. Is this all? :)

**Comment by Alhadis** [comment]
Yep, that's all! =) Now we wait for a maintainer of the project to accept your PR.

I'm just an obsessive contributor who likes to help, I'm not staff or anything, haha.

**Comment by MathBunny** [comment]
Awesome!! Ah, I would've guessed you were staff or something :p Thanks for your help!

**Comment by Alhadis** [comment]
Haha, no problem. ^^

The staff are busy as hell running around constantly, so it's good to get things sorted as much as possible so their todo list doesn't pile up with writing explanations to lingering PRs.

**Comment by MathBunny** [comment]
Makes sense  :) It's great that you're volunteering your time!

**Comment by arfon** [comment]
👍 looks good, thanks @MathBunny. Also, thanks @Alhadis for steering this PR!

@MathBunny - this change to Linguist won't be live on the site for at least another week - we generally release a new gem every couple of weeks.

**Comment by MathBunny** [comment]
Awesome! Thanks everyone :) It was fun

**Pull request merged**
