### PR TITLE
Support for JSCAD files

### PR DESCRIPTION
**Pull request by matiasinsaurralde**
[Github search results](https://github.com/search?utf8=%E2%9C%93&q=extension%3Ajscad+NOT+qqqqqq&type=Code&ref=searchresults) for .jscad files.

More information:
http://openjscad.org/

### CODE REVIEW

**Comment by pchaigno** [comment]
Nice pull request :+1: 

For the reviewers: I count 96 projects using `.jscad` files among 81 users.

**Comment by matiasinsaurralde** [comment]
@pchaigno Thank you!

**Comment by arfon** [comment]
Thanks @matiasinsaurralde - this will be live when we cut a new Linguist gem (very soon)

**Comment by matiasinsaurralde** [comment]
@arfon Cool!

**Pull request merged**
