### PR TITLE
Update Julia definitions to use Atom instead of TextMate

### PR DESCRIPTION
**Pull request by ararslan**
Currently linguist uses our TextMate plugin for its Julia definitions, which isn't well maintained and has more than its fair share of issues. The Atom plugin for Julia, [atom-language-julia](https://github.com/JuliaEditorSupport/atom-language-julia), is actively maintained and used. Thus we'd like to switch our linguist definitions to use atom-language-julia instead of Julia.tmbundle to ensure that things keeping looking good in the GitHub web UI.

Please let me know whether I've set this up correctly; I wasn't able to find explicit documentation in this repository regarding how to change the grammar that's used for an existing language.

### CODE REVIEW

**Comment by ararslan** [comment]
> No submodule mapping found in .gitmodules for path 'vendor/grammars/Julia.tmbundle'

I removed Julia.tmbundle from .gitmodules. Is it looking somewhere else as well?

**Comment by pchaigno** [comment]
> I removed Julia.tmbundle from .gitmodules. Is it looking somewhere else as well?

You'll also need to remove the reference to the submodule: https://stackoverflow.com/a/1260982/6884590.
We also have a Ruby script to automatically replace a grammar: `./script/add-grammar --replace Julia.tmbundle https://github.com/JuliaEditorSupport/atom-language-julia`

**Comment by ararslan** [comment]
Great, thanks for the tip! Running that is giving me an error though:
```
Cloning into '/Users/alex/Projects/linguist/vendor/grammars/atom-language-julia'...
remote: Counting objects: 585, done.
remote: Total 585 (delta 0), reused 0 (delta 0), pack-reused 585
Receiving objects: 100% (585/585), 196.98 KiB | 1018.00 KiB/s, done.
Resolving deltas: 100% (270/270), done.
OK vendor/grammars/atom-language-julia (source.julia.console, source.julia)
script/list-grammars:81:in `block in to_markdown': undefined method `chomp' for nil:NilClass (NoMethodError)
	from script/list-grammars:65:in `each'
	from script/list-grammars:65:in `to_markdown'
	from script/list-grammars:96:in `update_readme'
	from script/list-grammars:105:in `<main>'
```

**Comment by ararslan** [comment]
Also, a little off topic, but I was trying to test this grammar using Lightshow, and it's just giving me a blank page. I gave it [this grammar URL](https://github.com/JuliaEditorSupport/atom-language-julia/blob/master/grammars/julia.cson) and [this file URL](https://github.com/JuliaLang/julia/blob/master/base/channels.jl).

**Comment by pchaigno** [comment]
> Great, thanks for the tip! Running that is giving me an error though:
```
Cloning into '/Users/alex/Projects/linguist/vendor/grammars/atom-language-julia'...
remote: Counting objects: 585, done.
remote: Total 585 (delta 0), reused 0 (delta 0), pack-reused 585
Receiving objects: 100% (585/585), 196.98 KiB | 1018.00 KiB/s, done.
Resolving deltas: 100% (270/270), done.
OK vendor/grammars/atom-language-julia (source.julia.console, source.julia)
script/list-grammars:81:in `block in to_markdown': undefined method `chomp' for nil:NilClass (NoMethodError)
	from script/list-grammars:65:in `each'
	from script/list-grammars:65:in `to_markdown'
	from script/list-grammars:96:in `update_readme'
	from script/list-grammars:105:in `<main>'
```

@ararslan Did you run it on this PR's branch or on the master branch? If you ran it on this branch, I'm guessing it doesn't like that the previous grammar is already half-removed. The best is probably to just finish removing the submodule now (`git rm path_to_submodule`).
<br>

> Also, a little off topic, but I was trying to test this grammar using Lightshow, and it's just giving me a blank page. I gave it [this grammar URL](https://github.com/JuliaEditorSupport/atom-language-julia/blob/master/grammars/julia.cson) and [this file URL](https://github.com/JuliaLang/julia/blob/master/base/channels.jl).

@aroben Any idea why Lightshow is failing on [this](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgithub.com%2FJuliaEditorSupport%2Fatom-language-julia%2Fblob%2Fmaster%2Fgrammars%2Fjulia.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2FJuliaLang%2Fjulia%2Fblob%2Fmaster%2Fbase%2Fchannels.jl&code=)? I tried removing the first key/value ("comment"), but then I get another error message.

**Comment by ararslan** [comment]
> Did you run it on this PR's branch or on the master branch? If you ran it on this branch, I'm guessing it doesn't like that the previous grammar is already half-removed.

I did `git reset --hard origin/master` and then ran the script. After that failed I reset the branch to sync with this PR, removed the submodule, and built successfully. I didn't push that to the PR though because I figured it'd be better to let the script do it, in case I missed anything when doing it manually. I'll try the script again with a fresh clone.

**Comment by ararslan** [comment]
I haven't been able to get the script to work locally, so I just finished up doing it manually.

**Comment by lildude** [comment]
> @aroben Any idea why Lightshow is failing on this? I tried removing the first key/value ("comment"), but then I get another error message.

@aroben doesn't work for GitHub anymore so no longer has access to the code. I'll add it to my Todo list of things to check.

**Comment by lildude** [comment]
> Any idea why Lightshow is failing on this? I tried removing the first key/value ("comment"), but then I get another error message.

Yup... we use a very very crude and horrible method of detecting the grammar file type (XML/JSON/CSON/YAML) and in the case of this grammar, we're falling through to the last resort assumption of YAML as the CSON detection expects the first character to be a quote. We assume all keys in CSON files are quoted and none of the keys in this grammar are quoted. And as this isn't valid YAML, we fail attempting to parse it as YAML too.

I didn't realise we did it this way until now. I'm gonna change it as it's 🤢

**Comment by lildude** [comment]
For reference, we've hit this before: https://github.com/github/linguist/issues/2924 and https://github.com/github/linguist/pull/2703#issuecomment-155533991 before it.

**Comment by Alhadis** [comment]
> I didn't realise we did it this way until now. I'm gonna change it as it's 🤢

@lildude Any progress? This has driven me insane for almost two years running now. My current hack is to prepend my grammar with `'a': 'b'` and upload it to PasteBin... 😢

Worse-comes-to-worse, you could at least add a "this isn't YAML" heuristic by checking for the presence of a hard tab. 😜 Some of us do use tabs, y'know.

**Comment by lildude** [comment]
> @lildude Any progress?

Yup. I've got a hack in place in my local dev that does the trick, but it's only slightly less 🤢 than the current implementation 😁

I plan to do things "proper" when I've got more time to concentrate on it... I've got a few long flights coming up so I might do it then.

**Comment by Alhadis** [comment]
> but it's only slightly less 🤢 than the current implementation 😁

Let me guess... a `try{ yaml } catch { cson }` hack? 😀

Don't worry, I would've done the same, hahahah.

**Comment by lildude** [comment]
> Let me guess... a `try{ yaml } catch { cson }` hack? 😀

Almost, I just went the other way round 😆

**Comment by Alhadis** [comment]
Close enough! CSON is a hundreds times better than YAML anyway. 😝

The world needs a `libcson` library so it can carry on existing once CoffeeScript has fully carked it.

**Comment by Alhadis** [comment]
@lildude Dumb question: is there any reason we can't add a dropdown to select the input format? The auto-detect could be the default, but users could have the option of manually selecting a syntax, rather than being at the mercy of hacky guesswork.

**Comment by lildude** [comment]
That's what I plan to do, though I was going to remove the auto-detection as I'd imagine most grammar authors would known the format of their grammar file thus making the auto-detection redundant.

**Comment by ararslan** [comment]
Thanks so much for working on that, @lildude. I don't intend to rush you or anything, but out of curiosity do you have a time estimate on that? It'd be nice to see a preview of how GitHub's Julia highlighting will look with this in place instead of the TextMate definition. I'm not in a hurry, just wondering.

**Comment by lildude** [comment]
@ararslan I'm flying to San Francisco today so will have tons of time on my hands. Assuming all goes well, I plan to spend some of that time sorting out Lightshow.

In the mean time, you can see how it'll look [here](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgist.githubusercontent.com%2Flildude%2F57cdeba70a0b066c6bbf784a05886408%2Fraw%2Fb2886d60f6b018350a0aa7d5112f7fee83708d2d%2Fjulia.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2FJuliaLang%2Fjulia%2Fblob%2Fmaster%2Fbase%2Fchannels.jl&code=) - I took the grammar and wrapped the `comment` key in quotes.

**Comment by ararslan** [comment]
Beautiful! Thanks so much, @lildude!

Looks like now I just have to figure out how to solve the failures here...

**Comment by pchaigno** [comment]
@ararslan You need to add the submodule to the Linguist repository: `git submodule add https://github.com/JuliaEditorSupport/atom-language-julia vendor/grammars/atom-language-julia`.

**Comment by ararslan** [comment]
> An error occurred while generating the build script.

😕 Any ideas?

**Comment by pchaigno** [comment]
Wow, that new! @lildude Any idea?

**Comment by ararslan** [comment]
Appears to be an issue with Travis. I've just seen it on another repository a moment ago.

**Comment by lildude** [comment]
Yup, looks like a transient issue on Travis. I "fixed" it by kicking off the builds again 😆 .

The only outstanding issue is the license has been incorrectly detected by the version of Licensed we're using (reminds me, I can update that now) which isn't correctly detecting the license as MIT.

Please feel free to add the hash (`53714285caad3c480ebd248c490509695d10404b`) to the [whitelist](https://github.com/ararslan/linguist/blob/248bf241f4956760f342e68f2424317c4df36348/test/test_grammars.rb#L12) and manually change `other` to `mit` in `vendor/licenses/grammar/atom-language-julia.txt`.

**Comment by ararslan** [comment]
Thanks so much! The tests are finally passing. :)

**Comment by Alhadis** [comment]
> I think you hit all of the possible issues with grammars in this pull request 

Don't worry, [I caught the one he missed](https://github.com/github/linguist/issues/3884). 😉

**Comment by pchaigno** [comment]
@Alhadis I've seen. Nice catch!

**Comment by Alhadis** [comment]
Scratch that, he really did find them all. -_- Updated issue with the graphical equivalent of audibly hitting your head against a wall.

**Comment by ararslan** [comment]
Thanks everyone for the help! Looking forward to seeing this go live. :)

**Comment by ararslan** [comment]
Is there anything else that needs to happen here before this can be merged?

**Comment by Alhadis** [comment]
@lildude Good to merge?

**Comment by Alhadis** [comment]
Awesome! Thank you so much, BTW! 😀

@ararslan Thanks for your patience and contribution!

**Comment by ararslan** [comment]
Thanks everyone for your sagely guidance!

**Pull request merged**
