### PR TITLE
Add syntax highlighting for Turing

### PR DESCRIPTION
**Pull request by Alhadis**
[Turing](https://en.wikipedia.org/wiki/Turing_%28programming_language%29) doesn't have a grammar, [so I wrote one](https://github.com/Alhadis/language-turing).

I've also changed the language's colour from a bright, garish green to a more suitable red:

Figure 1 Figure 2

**Rationale:** Red is the colour used in [Turing's logo](https://en.wikipedia.org/wiki/File:Turing_logo.gif), and it also reflects the language's Canadian heritage. The shade of red I picked is the same one used by the [flag of Ontario](https://upload.wikimedia.org/wikipedia/commons/8/88/Flag_of_Ontario.svg), the state where the Turing language was conceived (and continues to be taught).

Do I get a Turing award for this?

### CODE REVIEW

**Comment by arfon** [comment]
:boom: 🎉

**Comment by pchaigno** [comment]
@Alhadis I think you forgot to change the [`tm_scope` key](https://github.com/Alhadis/linguist/blob/302e329120b4f060166c15509ee8c7001cbab917/lib/linguist/languages.yml#L3745) for Turing :bowtie:

**Comment by larsbrinkhoff** [comment]
@Alhadis Did you know it's possible to add more commits to a pull request?  You can even do a force push to rewrite its history entirely.

**Comment by Alhadis** [comment]
Of course, but that's not going to help if a PR's already been merged upstream.

**Comment by larsbrinkhoff** [comment]
Oh!  Right.

**Comment by Alhadis** [comment]
@MathBunny Just a heads up I spent several days going through Turing's documentation to write up an original TextMate-compatible grammar just so it'd have correct highlighting on GitHub.

You're welcome. I accept fruit-baskets and hot Canadian mail-brides as thanks. No avocados or women outside the 26-34 age bracket, please.

**Comment by MathBunny** [comment]
@Alhadis Haha thanks! Lots of students will thank you now 👍

**Pull request merged**
