### PR TITLE
Add Csound languages

### PR DESCRIPTION
**Pull request by nwhetsell**
This pull request adds grammars and supporting files for [Csound](https://csound.github.io) languages.

Here are links to GitHub search results showing in-the-wild usage.

* [Csound orchestra (.orc) files containing `nchnls`](https://github.com/search?utf8=✓&q=extension%3Aorc+nchnls&type=Code&ref=searchresults), 2,000+ code results. Searching for [just the extension](https://github.com/search?utf8=✓&q=extension%3Aorc+NOT+nothack&type=Code&ref=searchresults) shows many results that seem to be related to an [Oil Runtime Compiler](https://github.com/bistromath/orc), about which I know very little. 

* [Csound user-defined opcode (.udo) files containing `opcode`](https://github.com/search?utf8=✓&q=extension%3Audo+opcode&type=Code&ref=searchresults), 188 repositories. The [.udo extension](https://github.com/search?utf8=✓&q=extension%3Audo+NOT+nothack&type=Code&ref=searchresults) seems to mean a “user-defined object” file in many contexts.

* [Csound document (.csd) files containing `CsoundSynthesizer`](https://github.com/search?utf8=✓&q=extension%3Acsd+CsoundSynthesizer&type=Code&ref=searchresults), 10,000+ code results. The [.csd extension](https://github.com/search?utf8=✓&q=extension%3Acsd+NOT+nothack&type=Code&ref=searchresults) also appears to be associated with [Cocos Studio](http://www.cocos2d-x.org/wiki/Cocos_Studio) files.

* [Csound score (.sco) files containing `i1`](https://github.com/search?utf8=✓&q=extension%3Asco+i1&type=Code&ref=searchresults), 3,000+ repositories. The [.sco extension](https://github.com/search?utf8=✓&q=extension%3Asco+NOT+nothack&type=Code&ref=searchresults) also seems to be associated with [SCO UNIX](https://en.wikipedia.org/wiki/OpenServer) and “scene object” files, apparently used in game development.

If additional sample files are needed, I can add more from the [User-Defined Opcode Database](http://www.csounds.com/udo/) and the [Csound manual repository](https://github.com/csound/manual/tree/master/examples).

### CODE REVIEW

**Comment by Alhadis** [comment]
Where did you acquire the sample files? Are they released under a permissive license?

**Comment by nwhetsell** [comment]
Files with a .udo extension are from http://www.csounds.com/udo/, and everything else is either directly from or (I believe) derived from examples in _The Canonical Csound Reference Manual_ (https://github.com/csound/manual/tree/master/examples).

_The Canonical Csound Reference Manual_ is licensed under the GNU Free Documentation License 1.2 (see https://github.com/csound/manual/blob/master/copying.txt and http://www.gnu.org/licenses/old-licenses/fdl-1.2.en.html), and I assumed that applied to the .udo files, but now I doubt that. There doesn’t seem to be any information at all about licensing in the User-Defined Opcode Database’s [About page](http://www.csounds.com/udo/about.html). The [Csound manual’s section on user-defined opcodes](http://csound.github.io/docs/manual/OrchUDO.html) says this: “You can find many ready made UDO’s (or contribute your own) at Csounds.com’s User Defined Opcode Database.”

I downloaded the “toot” samples from [here](http://www.csounds.com/toots/) thinking they were identical to the ones included in the Csound manual repository, but the toot samples are also on the [One Laptop per Child wiki](http://wiki.laptop.org/go/Csound_TOOTS) with this acknowledgment: “The 13 TOOTS were originally written by Richard Boulanger, Boston, Massachusetts USA March, 1991. The author has kindly agreed to allow for these to published in this Wiki.” That’s probably not a good sign.

If you prefer, I can remove the .udo files and toot samples, and add samples based solely on files in the FDL-licensed manual.

**Comment by Alhadis** [comment]
Better safe than sorry - any third-party material you're unsure of, it's best to jettison.

I'm unfamiliar with the FDL license, but I *do* know GNU licenses have a tendency to complicate issues far more than they need to be. @arfon would be able to clarify whether or not the FDL-licensed materials can be included as well, although the [license whitelist](https://github.com/github/linguist/blob/master/vendor/licenses/config.yml) leaves me doubting.

Just to confirm, I'm not staffing this repository, I'm just an obsessive contributor trying to help... =)

**Comment by nwhetsell** [comment]
Understood. I’ll replace the current samples with my own. When I do this, should I push everything so the old samples are removed and the new ones added to this pull request? Or should I do something like close this request, re-fork, and open a new pull request?

One more thing: The [language-csound](https://github.com/nwhetsell/language-csound) Atom package that provides the Csound grammars also includes [completions](https://github.com/nwhetsell/language-csound/blob/master/resources/opcode-completions.json) for Atom autocomplete. These completions are derived from the FDL-licensed Csound manual, but they’re _not_ used by the grammars. I figure I should mention this in case even the presence of FDL-licensed material in language-csound could complicate things here.

**Comment by Alhadis** [comment]
No no, no need for another PR. =) Just remove the samples in a new commit. When the PR gets merged into upstream, it'll squash everything into a single commit.

Don't worry about the package; it looks perfectly fine. I don't think Linguist or the highlighting engine even use anything beyond [syntax definitions](https://github.com/nwhetsell/language-csound/tree/master/grammars) anyway.

**Comment by nwhetsell** [comment]
I’ve replaced the old sample files with ones I wrote.

The `test.*` files are based on files included in the [Pygments](http://pygments.org) syntax highlighter:

* https://bitbucket.org/birkenfeld/pygments-main/src/tip/tests/examplefiles/test.csd
* https://bitbucket.org/birkenfeld/pygments-main/src/tip/tests/examplefiles/test.orc
* https://bitbucket.org/birkenfeld/pygments-main/src/tip/tests/examplefiles/test.sco

I [contributed](https://bitbucket.org/birkenfeld/pygments-main/src/tip/AUTHORS#AUTHORS-200) these files to Pygments, and Pygments is distributed under a 2-clause [BSD license](https://bitbucket.org/birkenfeld/pygments-main/src/tip/LICENSE).

The other samples are from a piece of music I wrote a decade ago.

**Comment by Alhadis** [comment]
Superb work! Now let's wait for a maintainer to check it out. =)

**Comment by nwhetsell** [comment]
Thanks!

**Comment by Alhadis** [comment]
@nwhetsell I see you're a fellow Atom user, so you may be heartened to know I've just added Csound support to the [latest release](https://github.com/DanBrooker/file-icons/releases/tag/v1.7.12) of the File-Icons package. =)
figure-1

**Comment by nwhetsell** [comment]
Cool!

**Comment by arfon** [comment]
Hi @nwhetsell, sorry it's taken me a while to get to this. Busy week...

Overall this PR is looking pretty good. I just have a couple of questions:

- I see that we've basically got three new 'languages' defined here: `Csound`, `Csound Document` and `Csound Score`. I'm curious if these could be combined into a single language definition of `Csound`? I see that all three have different grammar scopes so I'm guessing the answer is probably 'no' but I thought  I should check :smile:

> The .sco extension also seems to be associated with SCO UNIX and “scene object” files, apparently used in game development.

- Given this is a known clash on extensions - would you mind trying to find a couple of examples of these? We should probably add them to the PR as samples of the language they represent (assuming it's already known by Linguist)

**Comment by nwhetsell** [comment]
Hi @arfon, no worries!

> I see that we've basically got three new 'languages' defined here: Csound, Csound Document and Csound Score. I'm curious if these could be combined into a single language definition of Csound?

No (or at least I can’t think of how to go about it). Csound (Orchestra) and Csound Score are different languages, historically contained in different files. Csound Document (CSD) files are like containers for an orchestra and score. The relationship is somewhat analogous to JavaScript, CSS, and HTML (but Csound orchestras and scores have been around from Csound’s beginning, and CSDs came later).

> Given this is a known clash on extensions - would you mind trying to find a couple of examples of these?

The files I’ve seen that appear to be associated with SCO UNIX are makefiles with an sco extension: https://github.com/search?q=filename%3Amakefile.sco&type=Code.

Scene object files seem to be binary, but it appears to be a common practice to put them in a folder named SceneObj: https://github.com/search?q=extension%3Asco+path%3ASceneObj+NOT+nothack&type=Code.

**Comment by Alhadis** [comment]
3,055 files? Bloody hell, that's a lot.

@arfon Should I submit a pull request to address this? I'm happy to include a heuristic if necessary.

**Comment by nwhetsell** [comment]
@arfon Is there anything I should do to move this along?

**Comment by arfon** [comment]
>  although I'd still recommend adding it to the list of recognised Makefiles.

@Alhadis yeah that sounds like a good idea. Would you mind opening a Pull Request against `nwhetsell:master` implementing this change?

**Comment by nwhetsell** [comment]
I’ve added a makefile.sco in sample/Makefile/filenames. Many of the [Makefiles with an sco extension](https://github.com/search?q=filename%3Amakefile.sco&type=Code) appear to be part of libpng, so I just used makefile.sco from libpng. I believe the original is at https://sourceforge.net/p/libpng/code/ci/master/tree/scripts/makefile.sco.

libpng appears to have a permissive, but possibly non-standard, license, available at http://www.libpng.org/pub/png/src/libpng-LICENSE.txt and https://sourceforge.net/p/libpng/code/ci/master/tree/LICENSE.

I think the important bits are:

> ```
> The PNG Reference Library is supplied "AS IS".  The Contributing Authors
and Group 42, Inc. disclaim all warranties, expressed or implied,
including, without limitation, the warranties of merchantability and of
fitness for any purpose.  The Contributing Authors and Group 42, Inc.
assume no liability for direct, indirect, incidental, special, exemplary,
or consequential damages, which may result from the use of the PNG
Reference Library, even if advised of the possibility of such damage.

> Permission is hereby granted to use, copy, modify, and distribute this
source code, or portions hereof, for any purpose, without fee, subject
to the following restrictions:

>  1. The origin of this source code must not be misrepresented.

>  2. Altered versions must be plainly marked as such and must not
     be misrepresented as being the original source.

>  3. This Copyright notice may not be removed or altered from any
     source or altered source distribution.

> The Contributing Authors and Group 42, Inc. specifically permit, without
fee, and encourage the use of this source code as a component to
supporting the PNG file format in commercial products.  If you use this
source code in a product, acknowledgment is not required but would be
appreciated.
> ```

**Comment by Alhadis** [comment]
👆 I wish every contributor was as on-the-ball as this bloke. nwhetsell be killin' it.

**Comment by arfon** [comment]
Great Pull Request, many thanks @nwhetsell! This will be live in the next release of Linguist (next week sometime).

Thanks for the help with this @Alhadis.

**Pull request merged**
