### PR TITLE
Comment styles; don't choke on `#!/usr/bin/env foo=bar`

### PR DESCRIPTION
**Pull request by geoff-codes**
- Add `--` and `"` style single-line comments.
  - Rearrange `elsif`s so `"` comments don't interfere with removing double-quoted strings.
- Don't fail to detect valid `#!/usr/bin/env` shebangs which actually "`env`" environmental variables.

**Edit**:

---
- Add tests to test_tokenizer.rb to match tokenizer.rb.
- Add samples for `"` and `--` comments and complicated `env` shebangs.
- Also, add `.tool` as shell extension (basically, exactly as #1622).

### CODE REVIEW

**Comment by arfon** [comment]
@bkeepers - this looks :sparkles: to me. Whaddya think?

**Comment by bkeepers** [comment]
:+1:

**Comment by arfon** [comment]
Thanks @geoff-codes. Sorry it took so very long to get this merged.

This change should be live on GitHub in the next week or so.

**Comment by geoff-codes** [comment]
No problem :wink:. I know you guys are busy.

**Pull request merged**
