### PR TITLE
 Adding syntax higlighting and language for gmsh (3D mesh generator) …

### PR DESCRIPTION
**Pull request by SumeetSinha**
…gmESSI (Translator from gmsh to ESSI files), and Real-ESSI (University of California Davis Finite Element Program )

### CODE REVIEW

**Comment by SumeetSinha** [comment]
@Alhadis 

From where is this error coming from?
How to fix it ??

**Comment by brandonblack** [comment]
@SumeetSinha the previous build failure was my fault. I fix it and re-ran your build but it looks like you still have a few license related errors to solve.

**Comment by SumeetSinha** [comment]
@brandonblack Should I need to change my licenses. 

Which license I should have??

**Comment by SumeetSinha** [comment]
@pchaigno What does that mean **"link to search results on github.com showing in-the-wild usage for each extension you added"**

How to do that? is there some steps or elaborate explanation about the steps to achieve the same.

**Comment by pchaigno** [comment]
See details in [`CONTRIBUTING.md`](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language). Any search on github.com that shows a high number of files (usually >1,000) will do. It should be per extension and the search results should only contain files from the language you want to add (which is not always the case for conflicting extensions).

**Comment by SumeetSinha** [comment]
ESSI Grammer (.fei) = https://github.com/search?q=extension%3Afei+user%3ABorisJeremic&ref=searchresults&type=Code&utf8=%E2%9C%93

**Comment by SumeetSinha** [comment]
gmsh Grammer (.msh, .geo) https://github.com/search?utf8=%E2%9C%93&q=extension%3Ageo+extension%3Amsh++user%3Atehnick+user%3Acycheung&type=Code&ref=searchresults

**Comment by SumeetSinha** [comment]
Gmessi (.gmessi) :  https://github.com/search?utf8=%E2%9C%93&q=extension%3Agmessi+user%3ASumeetSinha&type=Code&ref=searchresults

**Comment by Alhadis** [comment]
* [`.gmessi`](https://github.com/search?q=extension%3Agmessi+NOT+nothack&type=Code): 3 results / 1 user
* [`.geo`](https://github.com/search?q=extension%3Ageo+NOT+nothack&type=Code): 18,379 results, but most of them related to GLSL, not GMSH.
* [`.fei`](https://github.com/search?q=extension%3Afei+NOT+nothack&type=Code): 1,801 results / 7 users / 8 repositories

**Users/repositories with `.fei`:**
- [BorisJeremic](https://github.com/BorisJeremic)
	- [Real-ESSI-Examples](https://github.com/BorisJeremic/Real-ESSI-Examples)
	- [Real-ESSI-Verification-Examples](https://github.com/BorisJeremic/Real-ESSI-Verification-Examples)
- [G4te-Keep3r](https://github.com/G4te-Keep3r)
	- [HowdyHackers](https://github.com/G4te-Keep3r/HowdyHackers)
- [GregTrevellick](https://github.com/GregTrevellick)
	- [FilesForEveryExtension](https://github.com/GregTrevellick/FilesForEveryExtension)
- [SumeetSinha](https://github.com/SumeetSinha)
	- [gmESSI](https://github.com/SumeetSinha/gmESSI)
- [andrew-kovrigin](https://github.com/andrew-kovrigin)
	- [EmCV](https://github.com/andrew-kovrigin/EmCV)
- [babakkamrani](https://github.com/babakkamrani)
	- [ESSI_Test_Suite](https://github.com/babakkamrani/ESSI_Test_Suite)
- [wufeifei](https://github.com/wufeifei)
	- [grw](https://github.com/wufeifei/grw)

I'm sorry, but this doesn't meet our criteria for adequate distribution. Please note the section in [`CONTRIBUTING.md`](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language) which states the distribution requirement:

> In most cases we prefer teach new file extension be **in use in hundreds of repositories before supporting them in Linguist**.

**Pull request closed without merging**
