### PR TITLE
Replace GPL licensed gml samples

### PR DESCRIPTION
**Pull request by sahildua2305**
Removed all GPL licensed .gml samples.

Sources of all added files are mentioned in the first line of every file.

@arfon Please have a look :smile:

### CODE REVIEW

**Comment by sahildua2305** [comment]
@arfon @pchaigno Please review this :smile:

**Comment by pchaigno** [comment]
Looks like the new files are way smaller than the old files (+447, -2315). Not sure if that could be an issue. @arfon ?

**Comment by sahildua2305** [comment]
@pchaigno I tried to minimize the difference. Couldn't find larger files with desired license. I'd appreciate help here. :)

**Comment by arfon** [comment]
> Looks like the new files are way smaller than the old files (+447, -2315). Not sure if that could be an issue. @arfon ?

If the tests are passing then I think we're OK. There are some issues with the Bayesian classifier and sample sizes but I think we're probably OK here.

**Comment by sahildua2305** [comment]
@arfon Can we then go ahead with this one?

**Pull request merged**
