### PR TITLE
Add the X10 language.

### PR DESCRIPTION
**Pull request by mandel**
Add support for the [X10 language](https://en.wikipedia.org/wiki/X10_%28programming_language%29).

According to [this search](https://github.com/search?o=asc&p=1&q=class+extension%3Ax10&ref=searchresults&s=indexed&type=Code&utf8=%E2%9C%93) there are a little bit less than 12,000 code results.

### CODE REVIEW

**Comment by mandel** [comment]
Do you plan to accept the Eclipse Public License (http://www.opensource.org/licenses/eclipse-1.0.php)?

**Comment by pchaigno** [comment]
@mandel There are plan to use licensee to help recognize the licenses, see #2568.

**Comment by mandel** [comment]
@pchaigno Thank you for the reference.

**Comment by arfon** [comment]
> @mandel There are plan to use licensee to help recognize the licenses, see #2568.

This PR already includes the Licensee changes. @benbalter - it looks like Licensee already [supports this license](https://github.com/benbalter/licensee/blob/master/vendor/choosealicense.com/_licenses/epl-1.0.txt) but perhaps the [`LICENSE` file](https://github.com/x10-lang/x10-highlighting/blob/master/LICENSE) in this repo isn't explicit enough to be detected?

**Comment by benbalter** [comment]
> but perhaps the LICENSE file in this repo isn't explicit enough to be detected?

Correct. You can either:

1. Copy the test of the license into the LICENSE file as described [in the usage instructions](http://choosealicense.com/licenses/epl-1.0/): 

  > Create a text file (typically named LICENSE or LICENSE.txt) in the root of your source code and copy the text of the license into the file.

2. Update the test to optimistically grep for `Eclipse Public License` in the license. 

Obviously the first option would be preferable, if you'd be willing to update the LICENSE file @mandel. :smile_cat:

**Comment by mandel** [comment]
Thank you for your advices.

I do not really understand the error message in Travis:
```
  1) Failure:
TestGrammars#test_submodules_have_approved_licenses [/home/travis/build/github/linguist/test/test_grammars.rb:96]:
The following submodules have unapproved licenses:
* vendor/grammars/X10: epl-1.0.
--- expected
+++ actual
@@ -1 +1 @@
-[]
+["vendor/grammars/X10: epl-1.0"]
```
It seams that `test_grammars` recognizes the Eclipse Public License but does not accept it, isn't it?
Following the previous discussion, I thought that the epl was part of the approved licenses.

ps: running `licensee` in my project returns:
```
License file: LICENSE
License: Eclipse Public License 1.0
Confidence: 99%
Method: Licensee::GitMatcher
```

**Comment by benbalter** [comment]
@mandel I opened up https://github.com/github/linguist/issues/2594 which adds more descriptive messages to those tests. Specifically, fo runapproved licenses, `epl-1.0` needs to be added to the `LICENSE_WHITELIST` in https://github.com/github/linguist/blob/master/test/test_grammars.rb#L20-L35.

@arfon you might want to check with `@github/legal` on EPL, if you haven't already accepted it.

**Comment by mandel** [comment]
Thanks. You don't have to bother adding the EPL to the list of allowed licenses. I switch to the apache-2.0.

**Comment by arfon** [comment]
> Thanks. You don't have to bother adding the EPL to the list of allowed licenses. I switch to the apache-2.0.

That certainly helps @mandel :smile:

**Comment by arfon** [comment]
Thanks for working on this @mandel - this will be live in the next release of Linguist (hopefully later this week)

**Comment by mandel** [comment]
Thanks

**Pull request merged**
