### PR TITLE
Add BUCK filename to Python in languages.yml

### PR DESCRIPTION
**Pull request by Dominator008**
BUCK is the filename for the build files of the Facebook Buck build system. BUCK files are valid Python files.

Eg.:
  https://github.com/GerritCodeReview/gerrit/blob/master/BUCK

Also add a missing sample for Pants / Bazel BUILD files. They are also valid Python files.

### CODE REVIEW

**Comment by arfon** [comment]
Thanks for this @Dominator008. Do [these](https://github.com/search?q=name+filename%3ABUCK&ref=searchresults&type=Code&utf8=%E2%9C%93) all look to be `BUCK` files too?

**Comment by Dominator008** [comment]
@afton I skimmed through them and yes they look to be `BUCK` files.

**Comment by arfon** [comment]
> @afton I skimmed through them and yes they look to be `BUCK` files.

OK great. Thanks for checking. @Dominator008 - this will be live on GitHub once we release a new Linguist gem which will be in the next week or so.

**Comment by Dominator008** [comment]
Thanks!

**Pull request merged**
