### PR TITLE
Add Pashmak programming language

### PR DESCRIPTION
**Pull request by parsampsh**
## Checklist:

- [ ] **I am associating a language with a new file extension.**
  - [ ] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      
      - https://github.com/search?q=extension%3A.pashm&type=code
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [x] **I am adding a new language.**
  - [ ] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [x] I have included a real-world usage sample for all extensions added in this PR:

  
  - [x] I have included a syntax highlighting grammar: https://github-lightshow.herokuapp.com/
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

- [ ] **I am fixing a misclassified language**
  - [ ] I have included a new sample for the misclassified language:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am changing the source of a syntax highlighting grammar**
  
  - Old: https://github-lightshow.herokuapp.com/
  - New: https://github-lightshow.herokuapp.com/

- [ ] **I am updating a grammar submodule**
  

- [ ] **I am adding new or changing current functionality**
  
  - [ ] I have added or updated the tests for the new or changed functionality.

- [ ] **I am changing the color associated with a language**
  
  - [ ] I have obtained agreement from the wider language community on this color change.
    - [URL to public discussion]
    - [Optional: URL to official branding guidelines for the language]

### CODE REVIEW

**Comment by parsampsh** [comment]
The Pashmak official organization is here: https://github.com/pashmaklang

**Comment by parsampsh** [comment]
What is workflow problem?

**Comment by parsampsh** [comment]
well. I fixed all of problems. but only this error is available and i don't know how to fix it:
- license needs review: MIT

**Comment by Nixinova** [comment]
https://github.com/github/linguist/issues/5107#issuecomment-774781832

**Comment by lildude** [comment]
As mentioned at https://github.com/github/linguist/issues/5107#issuecomment-742699195 we require a minimum usage level of at least 200 unique user/repo combinations for each extension.

You are a very very long way from meeting this:

- `.pashm`:

Total files found: 77
Unique public user/repos: 7
Unique owners: 4

- `.pashmt`:

Total files found: 206
Unique public user/repos: 1
Unique owners: 1

As you are so far from reaching the minimum level, I don't anticipate this to change in the near future so I'm going to close this PR.

Please feel free to re-open when usage has reached sufficient popularity.

**Comment by parsampsh** [comment]
Ok. I'll re-open this PR when minimum requirements was available.

**Pull request closed without merging**
