### PR TITLE
Roll back to language-clojure v0.10.0

### PR DESCRIPTION
**Pull request by aroben**
v0.11.0 seems to have introduced deeply nested `meta.expression.clojure` scopes.

```
* vendor/grammars/language-clojure cfc8a5c...bae6eee (6):
  < Prepare 0.12.0 release
  < Merge pull request #14 from joelash/master
  < Prepare 0.11.0 release
  < Merge pull request #13 from hanjos/proposed
  < Add initial spec
  < Add initial Travis CI config
```

/cc @vmg

### CODE REVIEW

**Comment by aroben** [comment]
See https://twitter.com/swannodette/status/568516306648977409.

Here's [the bug in Lightshow](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgithub.com%2Fatom%2Flanguage-clojure%2Fblob%2Fv0.11.0%2Fgrammars%2Fclojure.cson&grammar_text=&code_source=from-text&code_url=&code=%28deftest+unify-nil-lvar-1%0D%0A++%28let+%5Bx+%28lvar+%27x%29%0D%0A++++++++os+%28ext-no-check+empty-s+x+nil%29%5D%0D%0A++++%28is+%28%3D+%28unify+empty-s+nil+x%29+os%29%29%29%29%0D%0A%0D%0A%28deftest+unify-nil-lseq-1%0D%0A++%28let+%5Bx+%28lvar+%27x%29%5D%0D%0A++++%28is+%28%3D+%28unify+empty-s+nil+%28lcons+1+x%29%29+nil%29%29%29%29%0D%0A%0D%0A%28deftest+unify-nil-map-1%0D%0A++%28let+%5Bx+%28lvar+%27x%29%5D%0D%0A++++%28is+%28%3D+%28unify+empty-s+nil+%7B%7D%29+nil%29%29%29%29%0D%0A%0D%0A%3B%3B+-----------------------------------------------------------------------------%0D%0A%3B%3B+object%0D%0A%0D%0A%28deftest+unify-object-nil-1%0D%0A++%28is+%28%3D+%28unify+empty-s+1+nil%29%29%29%29%0D%0A) using the v0.11.0 grammar. And [here it is using the v0.10.0 grammar](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgithub.com%2Fatom%2Flanguage-clojure%2Fblob%2Fv0.10.0%2Fgrammars%2Fclojure.cson&grammar_text=&code_source=from-text&code_url=&code=%28deftest+unify-nil-lvar-1%0D%0A++%28let+%5Bx+%28lvar+%27x%29%0D%0A++++++++os+%28ext-no-check+empty-s+x+nil%29%5D%0D%0A++++%28is+%28%3D+%28unify+empty-s+nil+x%29+os%29%29%29%29%0D%0A%0D%0A%28deftest+unify-nil-lseq-1%0D%0A++%28let+%5Bx+%28lvar+%27x%29%5D%0D%0A++++%28is+%28%3D+%28unify+empty-s+nil+%28lcons+1+x%29%29+nil%29%29%29%29%0D%0A%0D%0A%28deftest+unify-nil-map-1%0D%0A++%28let+%5Bx+%28lvar+%27x%29%5D%0D%0A++++%28is+%28%3D+%28unify+empty-s+nil+%7B%7D%29+nil%29%29%29%29%0D%0A%0D%0A%3B%3B+-----------------------------------------------------------------------------%0D%0A%3B%3B+object%0D%0A%0D%0A%28deftest+unify-object-nil-1%0D%0A++%28is+%28%3D+%28unify+empty-s+1+nil%29%29%29%29%0D%0A).

In the v0.11.0 case you can see there are growing numbers of `<span class="pl-e">` elements on each line.

**Comment by aroben** [comment]
The bug doesn't seem to affect Atom.

**Comment by aroben** [comment]
https://github.com/atom/language-clojure/pull/13 is the only change between v0.10.0 and v0.11.0

**Comment by vmg** [comment]
Looks like a legit bug in the highlighter. I'll investigate tomorrow morning. The 0.13 changes look like quite an improvement and I'd like to bring them back.

**Pull request merged**
