### PR TITLE
strndup implementation for Windows

### LINKED ISSUE #4132: Failed to install the gem (build native extension) on Windows
I'm using ruby 2.4, and I already have ```charlock_holmes``` and ```rugged``` installed. Here is the error message:

Installing github-linguist 6.1.0 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
D:/workdir/vendor/gems/github-linguist-6.1.0/ext/linguist
C:/Ruby24-x64/bin/ruby.exe -r ./siteconf20180515-46084-zv96bg.rb extconf.rb
creating Makefile

current directory:
D:/workdir/vendor/gems/github-linguist-6.1.0/ext/linguist
make "DESTDIR=" clean

current directory:
D:/workdir/vendor/gems/github-linguist-6.1.0/ext/linguist
make "DESTDIR="
generating linguist-x64-mingw32.def
compiling lex.linguist_yy.c
tokenizer.l: In function 'linguist_yylex':
tokenizer.l:96:14: warning: implicit declaration of function 'strndup'
[-Wimplicit-function-declaration]
<sgml>[[:alnum:]_]+=\"            { feed_token(strndup(yytext, strlen(yytext) -
1), REGULAR_TOKEN); eat_until_unescaped('"'); return 1; }
              ^
tokenizer.l:6:23: note: in definition of macro 'feed_token'
     yyextra->token = (tok); \
                       ^~~
tokenizer.l:96:14: warning: incompatible implicit declaration of built-in
function 'strndup'
<sgml>[[:alnum:]_]+=\"            { feed_token(strndup(yytext, strlen(yytext) -
1), REGULAR_TOKEN); eat_until_unescaped('"'); return 1; }
              ^
tokenizer.l:6:23: note: in definition of macro 'feed_token'
     yyextra->token = (tok); \
                       ^~~
tokenizer.l:97:14: warning: incompatible implicit declaration of built-in
function 'strndup'
<sgml>[[:alnum:]_]+='             { feed_token(strndup(yytext, strlen(yytext) -
1), REGULAR_TOKEN); eat_until_unescaped('\''); return 1; }
              ^
tokenizer.l:6:23: note: in definition of macro 'feed_token'
     yyextra->token = (tok); \
                       ^~~
compiling linguist.c
linking shared-object linguist/linguist.so
lex.linguist_yy.o:lex.linguist_yy.c:(.text+0xe2d): undefined reference to
`strndup'
lex.linguist_yy.o:lex.linguist_yy.c:(.text+0x1109): undefined reference to
`strndup'
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:259: linguist.so] Error 1

make failed, exit code 2

Gem files will remain installed in
D:/workdir/vendor/gems/github-linguist-6.1.0
for inspection.
Results logged to
D:/workdir/vendor/extensions/x64-mingw32/2.4.0/github-linguist-6.1.0/gem_make.out

An error occurred while installing github-linguist (6.1.0), and Bundler cannot
continue.
Make sure that `gem install github-linguist -v '6.1.0'` succeeds before
bundling.

In Gemfile:
  copyright-header was resolved to 1.0.22, which depends on
    github-linguist

### PR DESCRIPTION
**Pull request by kivikakk**
Hopefully fixes #4132.

### CODE REVIEW

**Comment by kivikakk** [comment]
Ping for a review: @bkeepers, @lildude?

**Comment by kivikakk** [comment]
Thank you!

**Comment by lildude** [comment]
Hmmm, I'm not sure why this is suddenly a problem, but testing locally (macOS) for me is now failing with:

```

cd tmp/x86_64-darwin17/linguist/2.4.3
/usr/bin/make
compiling ../../../../ext/linguist/strndup.c
../../../../ext/linguist/strndup.c:14:31: error: unknown type name 'size_t'
char *strndup(const char *s1, size_t n)
                              ^
../../../../ext/linguist/strndup.c:16:16: warning: implicitly declaring library function 'calloc' with type 'void *(unsigned long, unsigned long)' [-Wimplicit-function-declaration]
  char *copy = calloc(n + 1, sizeof(char));
               ^
../../../../ext/linguist/strndup.c:16:16: note: include the header <stdlib.h> or explicitly provide a declaration for 'calloc'
../../../../ext/linguist/strndup.c:17:3: warning: implicitly declaring library function 'memcpy' with type 'void *(void *, const void *, unsigned long)' [-Wimplicit-function-declaration]
  memcpy(copy, s1, n);
  ^
../../../../ext/linguist/strndup.c:17:3: note: include the header <string.h> or explicitly provide a declaration for 'memcpy'
2 warnings and 1 error generated.
make: *** [strndup.o] Error 1
rake aborted!
Command failed with status (2): [/usr/bin/make...]
```

... which appears to be related to the changes in this PR.

**Comment by lildude** [comment]
The failure and warnings are resolved with:

```diff
--- a/ext/linguist/strndup.c
+++ b/ext/linguist/strndup.c
@@ -1,3 +1,7 @@
+#include <stddef.h>
+#include <stdlib.h>
+#include <string.h>
+
 #if defined(_WIN32) || defined(_WIN64)
 #include <math.h>
 char *strndup(const char *s1, size_t n)
```

... though I'm not a C expert so I'm not sure if this is the correct or best approach to take.

**Comment by kivikakk** [comment]
Ugh, gross! I think that change might not necessarily be sound — it's unclear how it would affect the Windows build, and I still (sigh) don't have a working Windows build system.

Even simpler fix:

```
diff --git a/ext/linguist/strndup.c b/ext/linguist/strndup.c
index 49128cf0..8a7879b9 100644
--- a/ext/linguist/strndup.c
+++ b/ext/linguist/strndup.c
@@ -8,13 +8,3 @@ char *strndup(const char *s1, size_t n)
        return copy;
 }
 #endif
-
-
-#if defined(__APPLE__)
-char *strndup(const char *s1, size_t n)
-{
-  char *copy = calloc(n + 1, sizeof(char));
-  memcpy(copy, s1, n);
-  return copy;
-}
-#endif
```

I'll open a PR!

**Comment by kivikakk** [comment]
→ #4175

**Pull request merged**
