### PR TITLE
Python also supports triple single-quotes for comments

### PR DESCRIPTION
**Pull request by techhat**
While this is not the norm in Python at large, it is supported, and is part of the style guide in @saltstack code.

### CODE REVIEW

**Comment by arfon** [comment]
:flags: flagging this as stale. @techhat - are you still interested in this?

**Comment by techhat** [comment]
@arfon of course I am. I apparently missed @pchaigno's pull request. I'll take a look now.

**Comment by techhat** [comment]
@arfon, the pull request has been updated.

**Comment by arfon** [comment]
@techhat - excellent. @pchaigno - thanks for the tests!

**Comment by techhat** [comment]
Thanks @arfon, sorry it took so long.

**Pull request merged**
