### PR TITLE
Switch F* grammar to a more up-to-date fork

### PR DESCRIPTION
**Pull request by hacklex**
Updated fstar grammar to support unpaired quotes ( ` ) in reveal_opaque calls

## Description
Highlighting was broken spectacularily in files containing lines like
```fstar
reveal_opaque (`%opaque_name) (opaque_name param);
reveal_opaque (`%opaque_name2) (opaque_name2 param2);
```

## Checklist:
- [x] **I am changing the source of a syntax highlighting grammar**
  - Old: https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2FFStarLang%2Fatom-fstar%2Fd7ee2f76a83b675392498ad0b0a0511d8310a30b%2Fgrammars%2Ffstar.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2FFStarLang%2FFStar%2F9cdb3fb8275ff759a1c8fb2134542abbe7530e54%2Fulib%2FFStar.Monotonic.Pure.fst&code=
  - New: https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fhacklex%2Fatom-fstar%2Ff66854d0f229d08b42afe1231cb354e049604c8b%2Fgrammars%2Ffstar.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2FFStarLang%2FFStar%2F9cdb3fb8275ff759a1c8fb2134542abbe7530e54%2Fulib%2FFStar.Monotonic.Pure.fst&code=

### CODE REVIEW

**Comment by hacklex** [comment]
Is anything wrong with my PR?

**Comment by hacklex** [comment]
Tests failed since I've forgot to update README.md; fixed that :)

**Comment by hacklex** [comment]
Can you please manually trigger the tests to re-run? It seems the tests were only executed about an hour ago (with the pull request being made almost a day ago)...

**Comment by Alhadis** [comment]
🤔 I've no knowledge of F*, but my gut's telling me there's a better way to fix the highlighting issue you've observed. What's so special about `reveal_opaque`, and what's the significance of backticks in F* Links to canonical references would help (I checked F*'s site, but couldn't find any formal specification for the language…)

**Comment by hacklex** [comment]
You're correct that it probably should be further improved to include the most general case for that quote syntax.

However, currently linguist references the dead atom-fstar which is terribly outdated. This leads to disaster whenever reveal_opaque is used.

I've never seen any other usages of unpaired backtick in F*. The reveal_opaque is indeed quite special, as it gives the z3 prover access to otherwise hidden facts (hiding facts saves lots of resources for the prover and becomes vital when the proofs grow too complex).

The point is, in the current state, github renders large chunks of F* code as if they were a single binary operator. 
I am positive that my fix isn't making anything worse, and is making rendering of 99% of reveal_opaque usage cases adequate.

Check out how the currently used grammar [corrupts big files that use opaques](https://github.com/FStarLang/FStar/blob/e500396011082f13f7a14310d5769554b3acebad/ulib/FStar.Monotonic.Seq.fst) :)

or, in short,
```fstar
some code;
reveal_opaque (`%some_opaque) (some_opaque var1 var2);
some more code;
reveal_opaque (`%some_opaque) (some_opaque var1 var2);
(from here) the code (looks fine);
```

**Comment by hacklex** [comment]
Alright. The updated grammar now treats the backtick character as a single-character operator, and thus we'll have no more problems with F* highlighting around quoted expressions. I consulted F* specialists in their slack chat, and we agreed that it would be the best solution.

What's important, is that with this fix, github will finally render F* source files properly.

Can we merge this? I'm okay with switching linguist back to the original atom-fstar repository as soon as they show any sign of being alive (by accepting or rejecting my pull request for example)...

**Review by Alhadis — APPROVED** [review]
All good. Just needed to bust the outdated license cache. 👍

**Comment by hacklex** [comment]
They merged my pull request into the original atom-fstar repository.

This PR is updated accordingly.

**Comment by hacklex** [comment]
@lildude Can you please review this? 

I've contacted the guy who has the rights to merge atom-fstar PRs, and had him merge my grammar fix.

The only change in this PR is the atom-fstar submodule update (same source, most recent commit to master).
Without this fix, [github highlighting of some FStar files is a disaster](https://github.com/hacklex/CuteCAS/blob/master/Fractions.Definition.fst)...

Thank you!

**Comment by lildude** [comment]
> @lildude Can you please review this?

There's nothing to review or do other than close this PR as as the [CONTRIBUTING.md states](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#fixing-syntax-highlighting):

> Once the bug has been fixed upstream, we'll pick it up for GitHub in the next release of Linguist.

Thanks for persisting with this. 

Closing as we don't need this.

**Comment by hacklex** [comment]
Oh. Okay... Sorry for persisting, but when is the next release of Linguist at least approximately?

**Comment by lildude** [comment]
I have no idea; when I find the time 😁. I've tried to keep things monthly in the past but my workload recently has meant I'm no longer able to keep up that cadence.

**Comment by hacklex** [comment]
Oh. I see. Say, do you know how github grabs your releases? Is it automatical? Or perhaps it builds it on its own from your master branch?

Sorry for persistence. Just that F* highlighting is currently just one big mess and I'm sad that nothing more could be done :(

**Comment by lildude** [comment]
> Say, do you know how github grabs your releases? Is it automatical?

I do… I do it manually myself, and it requires updating four different locations/services which takes a very long time, hence I need to find time to dedicate to it.

**Pull request closed without merging**
