### PR TITLE
Switch *BNF grammars and fix grammar compilation errors

### PR DESCRIPTION
**Pull request by Alhadis**
Fixes Alhadis/language-regexp#1 and Alhadis/language-grammars#1, both of which are issues @lildude reported after encountering problems while preparing Linguist 7.6.0.

## Description
This PR addresses some silly oversights on my behalf, and switches out our current ABNF and EBNF grammars to accommodate two grammars I wrote for each of those formats. The only reason I didn't propose them for replacement in #4595 is because I wanted to improve their handling of non-standard BNF syntax (something the existing grammars don't do well either...), but since it's blocking a release, I figure there's no room for my perfectionism here. 😅

## Checklist:
- [x] **I am changing the source of a syntax highlighting grammar**
  - ABNF: [Old](https://github-lightshow.herokuapp.com/?utf8=✓&scope=source.abnf&grammar_format=auto&grammar_url=&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2FTadiT7%2Fxiaomi_violet_dump%2F5edc11ebb2c4b5d9a4bfd5ebc335ee7e47f69f56%2Fsystem%2Fsystem%2Fusr%2Fsrec%2Fen-US%2Fcontacts.abnf&code=) (Yikes… 😨) | [New](https://github-lightshow.herokuapp.com/?utf8=✓&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2FAlhadis%2Flanguage-grammars%2Fmaster%2Fgrammars%2Fabnf.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2FTadiT7%2Fxiaomi_violet_dump%2F5edc11ebb2c4b5d9a4bfd5ebc335ee7e47f69f56%2Fsystem%2Fsystem%2Fusr%2Fsrec%2Fen-US%2Fcontacts.abnf&code=)
  - EBNF: [Old](https://github-lightshow.herokuapp.com/?utf8=✓&scope=source.ebnf&grammar_format=auto&grammar_url=&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fpythonesque%2Frust-parsegen%2Fd320380f86470d64cd8692af673a263ca9e30a1c%2Fsrc%2Fresources%2Fasn1.ebnf&code=) | [New](https://github-lightshow.herokuapp.com/?utf8=✓&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2FAlhadis%2Flanguage-grammars%2Fmaster%2Fgrammars%2Febnf.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fpythonesque%2Frust-parsegen%2Fd320380f86470d64cd8692af673a263ca9e30a1c%2Fsrc%2Fresources%2Fasn1.ebnf&code=)

- [x] **I am updating a grammar submodule**

/cc @lildude 🚀

### CODE REVIEW

**Comment by Alhadis** [comment]
@lildude Hope you don't mind if I squeeze in a just-in-time update of the Vim script grammar, which [adds roughly 134 new keywords](https://github.com/Alhadis/language-viml/commit/92391aca1f3bff519ac76456ce4b02b1e9219411) to the language. 😉

(I literally upgraded Vim earlier before and remembered I hadn't pulled updates from Vim's repo in a while...)

**Comment by pchaigno** [comment]
@Alhadis Is it expected that the new grammar for ABNF [highlights so little code](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2FAlhadis%2Flanguage-grammars%2Fmaster%2Fgrammars%2Fabnf.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2FTadiT7%2Fxiaomi_violet_dump%2F5edc11ebb2c4b5d9a4bfd5ebc335ee7e47f69f56%2Fsystem%2Fsystem%2Fusr%2Fsrec%2Fen-US%2Fcontacts.abnf&code=)? In particular, it doesn't seem to properly recognize comments.

**Comment by Alhadis** [comment]
That's because the file I linked to isn't a valid ABNF file. [This one is](https://github-lightshow.herokuapp.com/?utf8=✓&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2FAlhadis%2Flanguage-grammars%2Fmaster%2Fgrammars%2Fabnf.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fxiejianying%2Fdoubango%2Fblob%2F44182ba5294224e4ba0d562c2234b4fd139b3ba5%2Fbranches%2F2.0%2Fdoubango%2FtinySDP%2Fabnf%2Fsdp.abnf&code=), and you can see the difference in both the file's syntax *and* its highlighting.

(I forgot to include a *valid* ABNF example in addition to an *invalid* one... sorry, I was rushing to get this PR up 😓)

**Comment by Alhadis** [comment]
It's worth noting that *BNF notations are notoriously inconsistent in their usage, as the formats are designed to be digested by human readers and specification authors, *not* machines. So authors inevitably stray from the formal BNF syntax and invent their own twists... sometimes mixing elements of other notations, generally without rhyme or reason...

Also, this message keeps giving me a heart-attack. Is anybody else experiencing this when they go to post a comment?

**Comment by pchaigno** [comment]
> Also, this message keeps giving me a heart-attack. Is anybody else experiencing this when they go to post a comment?
> 
> 

I don't remember ever seeing this.

**Comment by Alhadis** [comment]
I've seen it a number of times tonight, each on different repositories. Sometimes the comment went through after I refreshed. No idea what's going on, but it keeps scaring me into thinking I've suddenly been banned.

Which, if that ever happens, will lead to my soul wither and waning, and my inevitable departure from this world to write TextMate grammars in the afterlife. 😢

**Comment by pchaigno** [comment]
If that happens, you can always send me patches by email and I'll apply them :p

More seriously, you should perhaps contact GitHub's support.

**Comment by Alhadis** [comment]
> If that happens, you can always send me patches by email and I'll apply them :p

I wonder if Ghost Mail is called Gmail in the afterlife...

> More seriously, you should perhaps contact GitHub's support.

Doubt they'd be enlightened by a *"Hey, your thing broke"*, so i have my browser's devtools primed to catch any front-end issues I can spot. 😜

(I'm only posting this spammy reply in the hopes of having something to catch)

**Pull request merged**
