### PR TITLE
Fix Fortran Capitalization

### PR DESCRIPTION
**Pull request by acidburn0zzz**
http://en.wikipedia.org/wiki/Fortran

### CODE REVIEW

**Comment by anonymouse64** [comment]
@arfon Is there any update on the process of renaming languages?

**Comment by arfon** [comment]
> @arfon Is there any update on the process of renaming languages?

I'm afraid I'm not at GitHub any longer so I don't know. / cc @TwP

**Comment by lildude** [comment]
@anonymouse64 Renaming languages is now possible, and has happened a few times since this PR was closed. @arfon even had fun doing this in a big rename bonanza in https://github.com/github/linguist/pull/3278 😁

The process? Submit a PR like this one with the new name and provide an explanation as to why we need the rename.

In this case, it appears to be just a case change so the impact should be negligible as language searching is case-insensitive.

**Comment by lildude** [comment]
So nothing to do. 🎉

**Pull request closed without merging**
