### PR TITLE
Adds proper grammar for the DM language.

### PR DESCRIPTION
**Pull request by PJB3005**
The DM language has been in Linguist for a long time, but always used the C++ lexer.

@seiyria

### CODE REVIEW

**Comment by pchaigno** [comment]
The grammar is [missing a license](https://travis-ci.org/github/linguist/jobs/120070655) ;)
Could you also show the improvement, using [Lightshow](https://github-lightshow.herokuapp.com/), on [this DM sample](https://github.com/github/linguist/blob/master/samples/DM/example.dm) (or any other sample)?

**Comment by PJB3005** [comment]
Alright amended to add a license, gonna show the difference now.

**Comment by PJB3005** [comment]
Uhm, Lightshow is giving me the following error when trying to use it:
`Error parsing YAML grammar: (<unknown>): did not find expected ',' or ']' while parsing a flow sequence at line 1 column 12`

The grammar is an Atom CSON grammar but it's seeing it as YAML for some reason.

**Comment by pchaigno** [comment]
@PJB3005 See #2924 ;)

**Comment by PJB3005** [comment]
Alright I'll update the grammar to add quotes for Lightshow, then.

**Comment by PJB3005** [comment]
[Before](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=source.c%2B%2B&grammar_url=https%3A%2F%2Fgithub.com%2Ftextmate%2Fc.tmbundle%2Fblob%2F5b5d366309e8a549ce6fff5bcd9aa57ffb6dae77%2FSyntaxes%2FC%252B%252B.plist&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fgithub%2Flinguist%2Fmaster%2Fsamples%2FDM%2Fexample.dm&code=)

[After](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgithub.com%2FPJB3005%2Fatomic-dreams%2Fblob%2Fmaster%2Fgrammars%2Fdream%2520maker.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fgithub%2Flinguist%2Fmaster%2Fsamples%2FDM%2Fexample.dm&code=)

**Comment by arfon** [comment]
Thanks for this contribution @PJB3005 :zap:. This will be live in the next release of Linguist (likely sometime in the next week).

**Comment by duncathan** [comment]
Oh this is lovely

**Pull request merged**
