### PR TITLE
Added LiveCode Script

### PR DESCRIPTION
**Pull request by PaulMcClernan**
https://github.com/livecode/livecode
https://github.com/search?utf8=✓&q=extension%3A+livecode&type=Code&ref=searchresults
https://github.com/search?utf8=✓&q=extension%3A+livecodescript&type=Code&ref=searchresults

### CODE REVIEW

**Comment by arfon** [comment]
[.livecode](https://github.com/search?utf8=%E2%9C%93&q=extension%3Alivecode+NOT+haaaaaaack&type=Code&ref=searchresults)
[.livecodescript](https://github.com/search?q=extension%3Alivecodescript+NOT+haaaaack&ref=searchresults&type=Code&utf8=%E2%9C%93)

Hi @PaulMcClernan. Thanks for opening this pull request. As far as I can tell there are only ~400 `.livecode`and `.livecodescript` files across a small number of repositories on GitHub which doesn't meet out [contributing guidelines](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language) for adding a new language.

Are there any other extensions we should be looking for or are these the most common extensions?

**Comment by PaulMcClernan** [comment]
Well that's disappointing. There are other extensions .mc (MetaCard original name of LiveCode) and .rev / Transcript (RunTime Revolution previous name of LiveCode) too. Also, as I said it's a decendant of HyperTalk (Apple's HyperCard), it's also almost Identical SuperTalk (SuperCard) and SenseTalk (TestPlant) and a few others (one from Oracle). AppleScript is similar in a lot of ways.
It's really a whole category of scripting language (XTalk):
https://en.wikipedia.org/wiki/XTalk

**Comment by PaulMcClernan** [comment]
How does one find out how many files with many repos they're across (still new to GitHub)?Thanks.

**Comment by arfon** [comment]
@Alhadis - any chance I could convince you to run some stats on these extensions to get the breakdown of number of repos etc?

**Comment by Alhadis** [comment]
Sure thing, give me a few minutes. :)

**Comment by Alhadis** [comment]
Alright, this looks to be an exhaustive list, because there were less than 1,000 results for each...

### `.livecodescript`
**18 repositories, 12 users:**  
* [gkarma/Dibs](https://github.com/gkarma/Dibs)
* [gmcrev/DropBoxAPI2livecode](https://github.com/gmcrev/DropBoxAPI2livecode)
* [HedgeHao/LiveCodeAndroidCustomSettings](https://github.com/HedgeHao/LiveCodeAndroidCustomSettings)
* [Himalayan-Academy/Siva-Siva-App](https://github.com/Himalayan-Academy/Siva-Siva-App)
* [livecode/livecode-ide](https://github.com/livecode/livecode-ide)
* [livecode/livecode](https://github.com/livecode/livecode)
* [LiveCodeWorld/lcw_Authoring](https://github.com/LiveCodeWorld/lcw_Authoring)
* [macMikey/csvToText](https://github.com/macMikey/csvToText)
* [macMikey/dropboxapi_v2](https://github.com/macMikey/dropboxapi_v2)
* [macMikey/phxDropboxLib](https://github.com/macMikey/phxDropboxLib)
* [montegoulding/scriptonlyui](https://github.com/montegoulding/scriptonlyui)
* [opn/lcw_Tools](https://github.com/opn/lcw_Tools)
* [PaulMcClernan/community.livecode.pgmcclernan.tennotchknob](https://github.com/PaulMcClernan/community.livecode.pgmcclernan.tennotchknob)
* [PaulMcClernan/community.livecode.widget.fivestars](https://github.com/PaulMcClernan/community.livecode.widget.fivestars)
* [PaulMcClernan/id3lib](https://github.com/PaulMcClernan/id3lib)
* [peter-b/atom-language-livecode](https://github.com/peter-b/atom-language-livecode)
* [RichardHerz/lcCardLayoutToWeb](https://github.com/RichardHerz/lcCardLayoutToWeb)

### `.livecode`
**75 users / 111 repositories:**  
* [123wifi/vouchermkt](https://github.com/123wifi/vouchermkt)
* [adeyiedeh/adeya](https://github.com/adeyiedeh/adeya)
* [adeyiedeh/helloworld1](https://github.com/adeyiedeh/helloworld1)
* [aditya1503/Multiple-audio-mobile](https://github.com/aditya1503/Multiple-audio-mobile)
* [angerangel/archimede](https://github.com/angerangel/archimede)
* [angerangel/LCR3D](https://github.com/angerangel/LCR3D)
* [angerangel/livecodeExif](https://github.com/angerangel/livecodeExif)
* [angerangel/TrIDGUI2](https://github.com/angerangel/TrIDGUI2)
* [antijingoist/Paper-Police-Chase](https://github.com/antijingoist/Paper-Police-Chase)
* [bhall2001/fastjson](https://github.com/bhall2001/fastjson)
* [bhall2001/moduops](https://github.com/bhall2001/moduops)
* [BrunoK1/Worksheet-Inventor](https://github.com/BrunoK1/Worksheet-Inventor)
* [bvlahos/Scripting-Calendars](https://github.com/bvlahos/Scripting-Calendars)
* [chstrong/lcCouchQueryBuilder](https://github.com/chstrong/lcCouchQueryBuilder)
* [chstrong/lcLibJson](https://github.com/chstrong/lcLibJson)
* [chstrong/lcSQLQueryBuilder](https://github.com/chstrong/lcSQLQueryBuilder)
* [chstrong/Penguin](https://github.com/chstrong/Penguin)
* [COMEL-Mobile/SFA](https://github.com/COMEL-Mobile/SFA)
* [CrumpLab/ExperimentsInLivecode](https://github.com/CrumpLab/ExperimentsInLivecode)
* [CuonDeveloper/cuon](https://github.com/CuonDeveloper/cuon)
* [daviderossato/Livecode-snippets](https://github.com/daviderossato/Livecode-snippets)
* [derbrill/animationEngine](https://github.com/derbrill/animationEngine)
* [derbrill/libdate](https://github.com/derbrill/libdate)
* [dholdaway/Catch-The-Train](https://github.com/dholdaway/Catch-The-Train)
* [digitalpomegranate/livecode-piwik](https://github.com/digitalpomegranate/livecode-piwik)
* [digitalpomegranate/livecode-wp-restapi](https://github.com/digitalpomegranate/livecode-wp-restapi)
* [digitalpomegranate/LiveCodeConference2016](https://github.com/digitalpomegranate/LiveCodeConference2016)
* [ekosmin/unplatform](https://github.com/ekosmin/unplatform)
* [extra-programming/GenVar](https://github.com/extra-programming/GenVar)
* [fedaykinofdune/BittrexAPI](https://github.com/fedaykinofdune/BittrexAPI)
* [Gianlo98/AdvenutureQuest](https://github.com/Gianlo98/AdvenutureQuest)
* [gkarma/Dibs](https://github.com/gkarma/Dibs)
* [GregOldham/V-Trac](https://github.com/GregOldham/V-Trac)
* [grifma/jikijitsu](https://github.com/grifma/jikijitsu)
* [handihealth/livecode_demo](https://github.com/handihealth/livecode_demo)
* [HedgeHao/LiveCodeAndroidCustomSettings](https://github.com/HedgeHao/LiveCodeAndroidCustomSettings)
* [HermanSchippers/child-neurology-anamnesis](https://github.com/HermanSchippers/child-neurology-anamnesis)
* [Himalayan-Academy/ha_RigApplication](https://github.com/Himalayan-Academy/ha_RigApplication)
* [Himalayan-Academy/Siva-Siva-App](https://github.com/Himalayan-Academy/Siva-Siva-App)
* [iMikie/Passion-Project](https://github.com/iMikie/Passion-Project)
* [iMikie/ThunderProject](https://github.com/iMikie/ThunderProject)
* [jmwright/apogee2_work_activity](https://github.com/jmwright/apogee2_work_activity)
* [junryl/NexsenseMobile](https://github.com/junryl/NexsenseMobile)
* [kmasz/LiveCode_CasparCG_client](https://github.com/kmasz/LiveCode_CasparCG_client)
* [lajunta/livenet](https://github.com/lajunta/livenet)
* [lbehmer/Fall2014-Experiment_1](https://github.com/lbehmer/Fall2014-Experiment_1)
* [livecode/livecode](https://github.com/livecode/livecode)
* [livecode/livecode-ide](https://github.com/livecode/livecode-ide)
* [livecodesebastien/livecode_gccxml_parser](https://github.com/livecodesebastien/livecode_gccxml_parser)
* [LiveCodeWorld/lcw_Authoring](https://github.com/LiveCodeWorld/lcw_Authoring)
* [LubbockLUG/CrossNotes](https://github.com/LubbockLUG/CrossNotes)
* [macMikey/phxDropboxLib](https://github.com/macMikey/phxDropboxLib)
* [MakeShyftRDA/u.m.p](https://github.com/MakeShyftRDA/u.m.p)
* [markkuit/lolgraphs](https://github.com/markkuit/lolgraphs)
* [matthewmaier/howstr](https://github.com/matthewmaier/howstr)
* [matthewmaier/onegoal](https://github.com/matthewmaier/onegoal)
* [matthewmaier/platyvue](https://github.com/matthewmaier/platyvue)
* [mauricev78/CT-SS](https://github.com/mauricev78/CT-SS)
* [mauricev78/CTpoV2](https://github.com/mauricev78/CTpoV2)
* [mauricev78/MVE-TEST](https://github.com/mauricev78/MVE-TEST)
* [MFernstrom/cfmldoc](https://github.com/MFernstrom/cfmldoc)
* [Mikumiku747/Hardware-Software-Helper](https://github.com/Mikumiku747/Hardware-Software-Helper)
* [montegoulding/livecode-external-templates](https://github.com/montegoulding/livecode-external-templates)
* [montegoulding/mergContact](https://github.com/montegoulding/mergContact)
* [montegoulding/mergZumero](https://github.com/montegoulding/mergZumero)
* [nakia010985/getdevicemodel](https://github.com/nakia010985/getdevicemodel)
* [nakia010985/ioswifissid](https://github.com/nakia010985/ioswifissid)
* [nataliearandia/2016_SIP_WAS_BSA_MakeupBuddy](https://github.com/nataliearandia/2016_SIP_WAS_BSA_MakeupBuddy)
* [nebbishOne/trackthing_android](https://github.com/nebbishOne/trackthing_android)
* [NS456/nsPropertyMapper](https://github.com/NS456/nsPropertyMapper)
* [OfunEx/video_player](https://github.com/OfunEx/video_player)
* [openhardwarecoza/OPHW-SW-AVRLoader](https://github.com/openhardwarecoza/OPHW-SW-AVRLoader)
* [opn/lcw_Tools](https://github.com/opn/lcw_Tools)
* [PaulMcClernan/id3lib](https://github.com/PaulMcClernan/id3lib)
* [PeterWAWood/LiveCode-ListProcessor](https://github.com/PeterWAWood/LiveCode-ListProcessor)
* [PeterWAWood/LiveCode-MiniTest](https://github.com/PeterWAWood/LiveCode-MiniTest)
* [PeterWAWood/LiveCode-Tests](https://github.com/PeterWAWood/LiveCode-Tests)
* [phil-LUCS/TF](https://github.com/phil-LUCS/TF)
* [psahores/applications](https://github.com/psahores/applications)
* [quartamsoftware/livecode-color-library](https://github.com/quartamsoftware/livecode-color-library)
* [readerly/foyl](https://github.com/readerly/foyl)
* [readerly/litfeeder](https://github.com/readerly/litfeeder)
* [renegadesteve/rsIsValid](https://github.com/renegadesteve/rsIsValid)
* [revig/revigniter](https://github.com/revig/revigniter)
* [rgho/libPredictGender](https://github.com/rgho/libPredictGender)
* [rgho/RevELO](https://github.com/rgho/RevELO)
* [rgho/revenue](https://github.com/rgho/revenue)
* [rgho/revFlights](https://github.com/rgho/revFlights)
* [rgho/revive](https://github.com/rgho/revive)
* [rgho/revolve](https://github.com/rgho/revolve)
* [RichardHerz/lcCardLayoutToWeb](https://github.com/RichardHerz/lcCardLayoutToWeb)
* [Ruyka/Project-Practice](https://github.com/Ruyka/Project-Practice)
* [simonasato/Hello_World](https://github.com/simonasato/Hello_World)
* [soapdog/firefoxos-sample-game-apple-catcher](https://github.com/soapdog/firefoxos-sample-game-apple-catcher)
* [stephenbigger/ChemKinetics](https://github.com/stephenbigger/ChemKinetics)
* [stephenbigger/FluAnisot](https://github.com/stephenbigger/FluAnisot)
* [stephenbigger/FluSpec](https://github.com/stephenbigger/FluSpec)
* [stevorobs3/Sudoku](https://github.com/stevorobs3/Sudoku)
* [toddgeist/LiveCodeUtils](https://github.com/toddgeist/LiveCodeUtils)
* [trevordevore/iosclipboard](https://github.com/trevordevore/iosclipboard)
* [trevordevore/SSH-External-for-LiveCode](https://github.com/trevordevore/SSH-External-for-LiveCode)
* [uhellstr/livecode.butterfly](https://github.com/uhellstr/livecode.butterfly)
* [uhellstr/livecode.gameoflife](https://github.com/uhellstr/livecode.gameoflife)
* [uhellstr/livecode.jsontest.oracleapex](https://github.com/uhellstr/livecode.jsontest.oracleapex)
* [uhellstr/livecode.lunarlander](https://github.com/uhellstr/livecode.lunarlander)
* [uhellstr/livecode.pixels](https://github.com/uhellstr/livecode.pixels)
* [uhellstr/livecode.snake](https://github.com/uhellstr/livecode.snake)
* [ViralAcademy/rigManager](https://github.com/ViralAcademy/rigManager)
* [vlbond/percentofmax](https://github.com/vlbond/percentofmax)
* [vmoscato/esperimentilivecode](https://github.com/vmoscato/esperimentilivecode)
* [vsha/mylab](https://github.com/vsha/mylab)

**Comment by PaulMcClernan** [comment]
Thanks, maybe I can convince more LiveCode users to put stuff up on GitHub.

**Pull request closed without merging**
