### PR TITLE
Add support for Thrift-generated PHP code.

### PR DESCRIPTION
**Pull request by askreet**
Thrift-generated PHP files start with;
```php
 <?php
 namespace Foo\Bar\Thrift;
 /**
  * Autogenerated by Thrift Compiler (0.9.3)
```

### CODE REVIEW

**Comment by askreet** [comment]
New tests are passing. How do I sign the CLA?

**Comment by pchaigno** [comment]
@askreet I think you can sign it here: https://cla.github.com.

**Comment by Alhadis** [comment]
> New tests are passing. How do I sign the CLA?

With a pen. Careful not to scratch your screen, and don't scroll while signing the form.

Alternatively, just follow the link @pchaigno gave and click **Sign in** in the top-right corner (if you're not already logged in). You should see a link pointing to an agreement somewhere. I'm only saying _"you should see"_ because I've totally forgotten what the agreement looked like back when I first accepted it:

Figure 1

**Comment by askreet** [comment]
> EDIT: Wait, the link to accept the CLA is showing in the build results. Did you miss that, or wasn't it showing earlier?

It wasn't showing at least as recently as yesterday afternoon. I see it now, signing.

**Comment by askreet** [comment]
> With a pen. Careful not to scratch your screen, and don't scroll while signing the form.

I've got one of those glass screens so I had to use a sharpie. How do I clear it after I sign? cmd+Z isn't doing anything!

**Comment by Alhadis** [comment]
> How do I clear it after I sign? cmd+Z isn't doing anything!

Crap, I knew I should've recommended a pencil.


> It wasn't showing at least as recently as yesterday afternoon. I see it now, signing.

Ah, that would explain it then. Thanks!

@brandonblack This is the second PR in the last few days where the build failure's neglected to show users the CLA link. Do you know if there's something going on with CI?

**Comment by askreet** [comment]
Anything else needed from me on this PR? Just want to be sure I'm not blocking this.

**Pull request merged**
