### PR TITLE
Add Astro language

### LINKED ISSUE #5459: Add Astro language
## Language name
**Astro**

## URL of example repository
https://github.com/snowpackjs/astro

## URL of syntax highlighting grammar
[My grammar](https://github.com/Nixinova/Astro-vscode/blob/main/grammars/astro.tmLanguage.yaml)  ([preview](https://github-lightshow.herokuapp.com/?utf8=y&scope=from-url&grammar_url=https://github.com/Nixinova/Astro-vscode/blob/main/grammars/astro.tmLanguage.yaml&code_source=from-url&code_url=https://github.com/Nixinova/NovaGrammars/blob/main/samples/index.astro))

## Most popular extensions
[.astro](https://github.com/search?q=extension%3Aastro&type=code) - 1006 repos - using Harvester I got through 467 files before being rate limited and had 101 unique repos, so extrapolating that there should be over 200 unique out of that 1K.

## Detected language
None

### PR DESCRIPTION
**Pull request by Nixinova**
Resolve #5459

## Description
Adds the language used in the [Astro](https://github.com/snowpackjs/astro) static site generator.

## Checklist:
- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - See #5459
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source: [snowpackjs/astro](https://github.com/snowpackjs/astro/blob/main/examples/starter/src/pages/index.astro)
    - Sample license(s): [MIT](https://github.com/snowpackjs/astro/blob/main/LICENSE)
  
  - [x] I have included a syntax highlighting grammar ~~([preview](https://github-lightshow.herokuapp.com/?utf8=y&scope=from-url&grammar_url=https://github.com/Nixinova/Astro-vscode/blob/main/grammars/astro.tmLanguage.yaml&code_source=from-url&code_url=https://github.com/Nixinova/NovaGrammars/blob/main/samples/index.astro))~~ <ins>([preview](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fgithub.com%2Fsnowpackjs%2Fastro%2Fblob%2Fmain%2Ftools%2Fvscode%2Fsyntaxes%2Fastro.tmLanguage.json&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2FNixinova%2FNovaGrammars%2Fblob%2Fmain%2Fsamples%2Findex.astro&code=))</ins>
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

### CODE REVIEW

**Comment by lildude** [comment]
From https://github.com/github/linguist/issues/5459

> .astro - 1006 repos - using Harvester I got through 467 files before being rate limited and had 101 unique repos, so extrapolating that there should be over 200 unique out of that 1K.

Close, but not quite yet:

Total files found: 1053
Unique public user/repos: 192
Unique owners: 163

**Comment by Nixinova** [comment]
10 hours later theres 1,297 code results - surely there's enough now.

**Comment by Nixinova** [comment]
Surely it'll be at 200 by, like, tomorrow then

**Comment by natemoo-re** [comment]
@Nixinova 👋🏻 Astro maintainer here, thanks for opening this PR! I'm having some trouble accessing your grammar to check it for correctness. At any rate, we'd definitely prefer to point to the [official Astro `tmLanguage` file](https://github.com/snowpackjs/astro/blob/main/tools/vscode/syntaxes/astro.tmLanguage.json) if possible.

**Comment by Nixinova** [comment]
> .astro - 1006 repos

Its now at [1404](https://github.com/search?q=extension%3Aastro&type=code) - Astro is growing very quickly. So surely theres 8 new repos in the last day - I can even count them manually: [1](https://github.com/rebelchris/astro-portfolio/commits/master) [2](https://github.com/3mam/site/commits/master) [3](https://github.com/ga-fleury/astro-test/commits/master) [4](https://github.com/SMccarrick/portfolio/commits/main) [5](https://github.com/bmpickford/bmpickford/commits/main) [6](https://github.com/murshidazher/astro-wheel-of-names/commits/main) [7](https://github.com/srimaniteja19/maniastro/commits/main) [8](https://github.com/Enoooch/glance/commits/main) - there.

> we'd definitely prefer to point to the official Astro tmLanguage file if possible.
Done

**Comment by lildude** [comment]
All good now:

Total files found: 1542
Unique public user/repos: 221
Unique owners: 194

**Review by lildude — APPROVED** [review]

**Comment by lildude** [comment]
Whoops, looks like someone forced the switch to the Astro provided grammar without checking the output and thus missed the fact it has syntax errors and thus doesn't compile:

```
- [ ] repository `vendor/grammars/astro` (from https://github.com/snowpackjs/astro) (8 errors)
    - [ ] Grammar conversion failed. File `tools/vscode/syntaxes/astro.tmLanguage.json` failed to parse: 13 error(s) decoding:

* 'Patterns[12].Patterns[1].Patterns[1].Captures' expected a map, got 'slice'
* 'Patterns[4].Captures' expected a map, got 'slice'
* 'Patterns[5].Captures' expected a map, got 'slice'
* 'Repository[astro-expressions].Patterns[0].BeginCaptures' expected a map, got 'slice'
* 'Repository[astro-expressions].Patterns[0].EndCaptures' expected a map, got 'slice'
* 'Repository[string-double-quoted].BeginCaptures' expected a map, got 'slice'
* 'Repository[string-double-quoted].EndCaptures' expected a map, got 'slice'
* 'Repository[string-single-quoted].BeginCaptures' expected a map, got 'slice'
* 'Repository[string-single-quoted].EndCaptures' expected a map, got 'slice'
* 'Repository[tag-id-attribute].Patterns[0].BeginCaptures' expected a map, got 'slice'
* 'Repository[tag-id-attribute].Patterns[0].EndCaptures' expected a map, got 'slice'
* 'Repository[tag-id-attribute].Patterns[1].BeginCaptures' expected a map, got 'slice'
* 'Repository[tag-id-attribute].Patterns[1].EndCaptures' expected a map, got 'slice'
```

**Comment by matthewp** [comment]
Thanks @lildude, I think we can make your deadline. Is there a tool you know of to verify the syntax is correct? Otherwise we'll just assume its all of these captures.

**Comment by Nixinova** [comment]
https://github.com/snowpackjs/astro/pull/926

**Comment by jasikpark** [comment]
Does the `git submodule` in the repo need to be updated now, or does linguist just pull the lastest version of the specified file?

**Comment by lildude** [comment]
> Does the `git submodule` in the repo need to be updated now, or does linguist just pull the lastest version of the specified file?

Nope. We update as part of making each release; that's how I spotted this.

Just pulled the latest SHA and things are looking much better - there are a couple of warnings about missing includes because the grammar is attempting to use scopes Linguist doesn't know about (they appear to be grammars supplied by VSCode), but that's not a major issue and only means some parts may not highlight as expected. 

Thanks for the quick turnaround everyone 🙇.

**Comment by matthewp** [comment]
Thanks @lildude, are you using Lightshow to test the grammar? If so we can improve it on our end using that.

**Comment by lildude** [comment]
@matthewp Nope. I'm using our [grammar compiler](https://github.com/github/linguist/tree/master/tools/grammars) (step 3i in the [release process](https://github.com/github/linguist/blob/master/docs/releasing.md)) and it has a bunch of checks. This is what picked up the problems with the grammar.

**Comment by jasikpark** [comment]
hopefully we can pull that in to lint our own grammar?

**Comment by jasikpark** [comment]
When I click on "Astro" in the language breakdown, I navigate to https://github.com/snowpackjs/astro/search?l=astro, but I get "astro language not found"... is there something wrong with our config or does a different project need Astro added too?

**Comment by Nixinova** [comment]
> astro language not found

GitHub Search isn't updated at the same time Linguist is and is synced less often.

**Comment by lildude** [comment]
Further to @Nixinova's response… search uses [go-enry](https://github.com/go-enry/go-enry) which lags behind Linguist updates by quite a margin as it's a manual process subject to someone noticing or wanting the latest Linguist languages. They're currently inline with Linguist v7.14.0.

**Pull request merged**
