### PR TITLE
Replace the Bro language with Zeek

### PR DESCRIPTION
**Pull request by jsiwek**
Bro was officially renamed to Zeek in [this announcement](https://blog.zeek.org/2018/10/renaming-bro-project_11.html).  The primary file extension will be
`.zeek`, but `.bro` is also still supported.  In either case, the language should now be identified as "Zeek" instead of "Bro".  The `master` branch of the main [Zeek repository](https://github.com/zeek/zeek) has already converted to using the `.zeek` extension.

The external grammar definition, "bro-sublime", is now "zeek-sublime".
The later has updates that reflect the name change and some further
improvements.  Lightshow comparisons:

[Real-world sample OLD source.bro](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fgithub.com%2Fzeek%2Fzeek-sublime%2Fblob%2F31b9b519d425f4e2652f8ce9da73350440725b73%2FSyntaxes%2FBro.tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fzeek%2Fzeek%2Fblob%2F9a461d26e41f42a3f8f461743120f4d06eb9e6ca%2Fscripts%2Fbase%2Fprotocols%2Fhttp%2Fmain.zeek&code=)
[Real-world sample NEW source.zeek](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fgithub.com%2Fzeek%2Fzeek-sublime%2Fblob%2Feeb44e99ddbfc7c3c188ece7410177daabe8dd39%2FZeek.tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fzeek%2Fzeek%2Fblob%2F9a461d26e41f42a3f8f461743120f4d06eb9e6ca%2Fscripts%2Fbase%2Fprotocols%2Fhttp%2Fmain.zeek&code=)
[Real-world sample source file](https://github.com/zeek/zeek/blob/9a461d26e41f42a3f8f461743120f4d06eb9e6ca/scripts/base/protocols/http/main.zeek)
[Real-world sample license](https://github.com/zeek/zeek/blob/9a461d26e41f42a3f8f461743120f4d06eb9e6ca/COPYING)

[Contrived sample OLD source.bro](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fgithub.com%2Fzeek%2Fzeek-sublime%2Fblob%2F31b9b519d425f4e2652f8ce9da73350440725b73%2FSyntaxes%2FBro.tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fzeek%2Fvim-zeek%2Fblob%2F15f5005e575d15753d882614d9d8db1dba2117d4%2Fexample.zeek&code=)
[Contrived sample NEW source.zeek](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fgithub.com%2Fzeek%2Fzeek-sublime%2Fblob%2Feeb44e99ddbfc7c3c188ece7410177daabe8dd39%2FZeek.tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fzeek%2Fvim-zeek%2Fblob%2F15f5005e575d15753d882614d9d8db1dba2117d4%2Fexample.zeek&code=)
[Contrived sample source file](https://github.com/zeek/vim-zeek/blob/15f5005e575d15753d882614d9d8db1dba2117d4/example.zeek)
[Contrived sample license](https://github.com/zeek/vim-zeek/blob/15f5005e575d15753d882614d9d8db1dba2117d4/LICENSE)

Both samples are included in this commit.

## Checklist:

- [x] **I am REPLACING an existing language name, adding a new file extension for it, and updating its grammar submodule all at once**
  - [ ] The new extension is used in hundreds of repositories on GitHub.com
      - Not yet, but as explained above, the language name itself is changing, so expect similar adoption eventually.  The original `.bro` extension is used within the order of a hundred repos just counting what's listed on our public, user-submitted [package repository](https://github.com/zeek/packages).
        - [GH .bro search results](https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3Abro+event)
        - [GH .zeek search results](https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3Azeek+event)

  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample sources + licenses listed above.
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.
    - N/A

### CODE REVIEW

**Comment by jsiwek** [comment]
@pchaigno Thanks, I added a sample `.bro`, but it's just identical to one of the `.zeek` samples.  Let me know if a unique file (or even symlink) is preferred.

**Comment by pchaigno** [comment]
Thanks. Having duplicate sample files is indeed very likely to skew the Bayesian classifier. If you can find a `.bro` file under permissive license that would be better. If you can't it's not a big issue, we can just continue without `.bro` samples.

**Comment by jsiwek** [comment]
Ok, added a different `.bro` file.  [Source file](https://raw.githubusercontent.com/zeek/zeek/release/2.6/scripts/base/protocols/dns/main.bro) and [license](https://raw.githubusercontent.com/zeek/zeek/release/2.6/COPYING).

**Comment by pchaigno** [comment]
Perfect! Thanks!

**Pull request merged**
