### PR TITLE
Updating source VB.NET syntax from my repo

### PR DESCRIPTION
**Pull request by AnthonyDGreen**
The maintainer of the current grammar no longer wishes to maintain it so I'd like to host the submodule instead.

### CODE REVIEW

**Comment by Alhadis** [comment]
I saw your work over at angryant0007/VBDotNetSyntax#8 ... have to say, I was damn impressed by your diligence. 👍  I can see you're serious about supporting this language properly, so it looks like the grammar will be in good hands.

Now, we can't merge this until the transfer has been made (otherwise, CI will try pulling the grammar from the wrong source, and complain of a missing dependency). You should also use the [`script/add-grammar`](https://github.com/github/linguist/blob/master/script/add-grammar#L61) tool to update the source's URL:

~~~console
script/add-grammar --replace=VBDotNetSyntax AnthonyDGreen/VBDotNetSyntax
~~~

This will take care of all the tedious deregistering and reregistering of each grammar. =)

**Comment by AnthonyDGreen** [comment]
I have had a lot of trouble trying to follow your instructions. Forgive me my ignorance but will these commands work on Windows? Which "transfer" are you speaking of?

I was conferring with my colleague Dustin Campbell, who implemented the [C# grammar](/dotnet/csharp-tmLanguage), and we agreed that we'll probably want to set up a parallel repo under the dotnet org for the VB grammar, rather than making my personal fork the source of truth.

angryant0007 accepted my PR on his repo already so that addresses my most immediate concerns (what's the timeframe for those changes appearing on GitHub?).

I'll close this PR and we can try again once we've created an official repo under the dotnet org to host this project moving forward. Thanks!

**Comment by AnthonyDGreen** [comment]
@Alhadis , is there something that needs to be done here for the changes on angryant0007's submodule to go live?

**Comment by Alhadis** [comment]
Hi @AnthonyDGreen,

Yes, all changes (both to this repository and its submodules) will become live on GitHub once there's been a new release of Linguist.

In other words, there's nothing to do but be patient until the next release. =) Linguist's release cycle isn't set in stone; you'd need to ask @lildude when the next gem is due to be cut.

**Pull request closed without merging**
