### PR TITLE
Alphabetise heuristics.

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
Rearrange heuristics and their tests in alphabetical order.

Also added checks to keep them in order.

### CODE REVIEW

**Comment by pchaigno** [comment]
:+1: 

@larsbrinkhoff Could you do the same for the tests?

@arfon The main benefit I see is that it'll reduce the number of conflicts between PRs adding new heuristic rules.

**Comment by larsbrinkhoff** [comment]
@pchaigno Good idea.  Done now.

**Comment by larsbrinkhoff** [comment]
Added checks to keep the files alphabetised.

**Comment by arfon** [comment]
Cheers @larsbrinkhoff. _A tidy repo is a happy repo_ :smile:

**Pull request merged**
