### PR TITLE
Add Cypher Query Language

### PR DESCRIPTION
**Pull request by 007vasy**
[All tests are ok](https://github.com/007vasy/linguist/actions/runs/3094216029/jobs/5007364537)

# Desciption
This ***PR*** adds the **_Cypher_** query language with the ```*.cypher``` and ```*.cyp``` extension. 

```*.cql``` is removed because:
  - not mentioned [here](https://groups.google.com/g/opencypher/c/PO5EnspBLs0)
  - not part of the [official recommendation](https://github.com/opencypher/openCypher/blob/2bc9428057e5373f5af184ff84cf1f8553b323d5/docs/style-guide.adoc#3-recommendations)
  - ambigous based on the [github search](https://github.com/search?q=extension%3Acql&type=code) 4-5 different languages use it

The language is a graph query language https://opencypher.org/ and it's ISO recognition is WIP

regarding `cypher` extension [There are already:](https://github.com/search?q=extension%3Acypher&type=code)
  - 12k code results
  - 411k package results
  - 915k topic results

regarding `cyp` extension [There are already:](https://github.com/search?q=extension%3Acyp&type=code)
  - 1.4k code results
  - 382k package results
  - 895k topic results

So It would be great to have syntax highlighting on github (and later search as well) :)

Godspeed!

## Checklist:

- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      - https://github.com/search?q=extension%3Acyp&type=Code
      - https://github.com/search?q=extension%3Acql&type=Code
      - https://github.com/search?q=extension%3Acypher&type=Code
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - `graphgems.*` 
        - https://github.com/neo4j/cypher-shell/blob/4.3/cypher-shell/src/test/resources/org/neo4j/shell/parser/graphgems.cypher
      - `db_export_res.cypher`:
        - https://neo4j.com/labs/apoc/4.1/export/cypher/
      - `load_from_json.cypher`:
        - https://neo4j.com/labs/apoc/4.1/import/load-json/
    - Sample license(s):
      - https://neo4j.com/docs/license/
      - https://github.com/neo4j/cypher-shell/blob/4.3/LICENSE.txt
    - Highlight license: 
      - https://github.com/fredbenenson/sublime-cypher/blob/master/LICENSE.txt
    - Language license:
      - https://github.com/opencypher/openCypher/blob/master/LICENSE
  - [x] I have included a syntax highlighting grammar: https://github.com/fredbenenson/sublime-cypher.git

### CODE REVIEW

**Comment by 007vasy** [comment]
@lildude fixed the tests:
[All tests are ok](https://github.com/007vasy/linguist/actions/runs/2900261640)

**Comment by 007vasy** [comment]
@lildude I want to make you proud!

**Review by lildude — CHANGES_REQUESTED** [review]
Please replace the `.cql` and `.cyp` files with real-world usage samples.

I recommend adding at least two real world highly representative samples for the `.cql` extension as this extension is already used by SQL and good representative samples will help the classifier make a better guess.

**Comment by 007vasy** [comment]
@lildude done

**Comment by lildude** [comment]
Wow! We don't need that many samples - two per extension is plenty. We also don't want duplicate content with different extensions as that doesn't train the classifier to differentiate between the extensions.

**Comment by 007vasy** [comment]
the thing is with Cypher that all 3 extension can be used, it does not matter which is used

**Comment by lildude** [comment]
> the thing is with Cypher that all 3 extension can be used

In that case we only need one unique and most representative sample per extension, except for `.cql` due to it already being in use. Three identical copies of seven files is excessive and adds no value.

**Comment by 007vasy** [comment]
@lildude done, left more examples for `.cql` and 1-1 for `.cyp` and `.cyhper`

**Comment by lildude** [comment]
Thanks. Please update the OP to point to the original source for each file and their relevant license.

I'll check the extensions meet our popularity requirements closer to merge time.

**Comment by 007vasy** [comment]
@lildude 
- updated OP
- added licenses
- removed one example

If you check the search results, it is going over by a mile to the popularity reqs

**Comment by 007vasy** [comment]
and thank you for your patience!

**Comment by adriens** [comment]
:heavy_plus_sign: :one: :ballot_box: :pray:

**Comment by adriens** [comment]
cf https://github.com/community/community/discussions/32466

**Comment by 007vasy** [comment]
@lildude is there anything else needed?

**Comment by 007vasy** [comment]
hi @lildude, @Alhadis what is the release schedule?

**Comment by lildude** [comment]
> hi @lildude, @Alhadis what is the release schedule?

There isn't one. I make an release when I've got the time somewhere close to the next release of GitHub Enterprise Server as it's not a quick process. I'm also holding off approving PRs which add new languages until I'm close to release as it takes a lot more time to review than simple fixes.

"Be patient my young Padawan".

**Comment by adriens** [comment]
> "Be patient my young Padawan".

AWESOME :rofl:

**Comment by 007vasy** [comment]
thanks for the update!

**Review by adriens — COMMENTED** [review]
OMG :open_mouth: You mean it will be availbale soon on GH ? When should I start to give it a try :grey_question:

**Comment by 007vasy** [comment]
the most probable point in time in the next github enterprise release, which could happen next week or 3 months from now

based on the [github enterprise release](https://enterprise.github.com/releases) schedule this could happen late october early november, best case

**Comment by adriens** [comment]
So let's :crossed_fingers: :cat:

**Comment by 007vasy** [comment]
@lildude can you at least allow the tests to run?

it should be fine I tested them on my fork, but I don't want to miss an other release window if possible

**Comment by adriens** [comment]
:crossed_fingers: :pray: :100:

**Review by lildude — APPROVED** [review]

**Comment by adriens** [comment]
Ready to :rocket: :grey_question:

**Comment by lildude** [comment]
Yes, but it won't appear on GitHub until I make a release.

**Comment by 007vasy** [comment]
@lildude do you have an estimate for a github release?

**Comment by lildude** [comment]
https://github.com/github/linguist/pull/6162

**Comment by adriens** [comment]
https://twitter.com/rastadidi/status/1593070750248075264

image

**Pull request merged**
