### PR TITLE
Add support for Cabal configuration files

### PR DESCRIPTION
**Pull request by Alhadis**
This PR adds support for [Cabal config files](https://www.haskell.org/cabal/users-guide/developing-packages.html), which are used to store metadata about Haskell projects (à la `package.json` in a JavaScript project).

## Description
Lack of support for Cabal was brought to my attention by @phadej in [`haskell-CI/haskell-ci#223`](https://github.com/haskell-CI/haskell-ci/pull/223), when I was correcting the language of some misclassified files:

> Technically they are Cabal configuration, so it's more like EDN or JSON than Clojure or JavaScript. I guess linguist doesn't know about Cabal files?

Syntax highlighting is already provided by our existing Haskell grammar.

## Checklist:
- [x] **I am adding a new language.**
	- [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
		- Search results for each extension:
			-	[`.cabal`](https://github.com/search?q=extension%3Acabal+NOT+nothack&type=Code): ~99,110 results
			-	[`cabal.config`](https://github.com/search?q=filename%3Acabal.config+NOT+nothack&type=Code): ~2,944 results
			-	[`cabal.project`](https://github.com/search?q=filename%3Acabal.project+NOT+nothack&type=Code): ~2,375 results
	- [x] I have included a real-world usage sample for all extensions added in this PR:
		- Sample source(s):
			-	`cabal.project`:  [Source](https://github.com/reflex-frp/reflex-platform/blob/b365d0b3f55ebcca0c6f8517b20cf5d0b7b1cd37/cabal.project) | [BSD3 clause](https://github.com/reflex-frp/reflex-platform/blob/f333fb43e3d5b47516131847757a2c9b2be09616/LICENSE)
			-	`cabal.config`:   [Source](https://github.com/ostapneko/gratte-papier/blob/a65f5389a62c5d16c99318c92d1004c18cdedd6c/cabal.config) | [MIT-licensed](https://github.com/ostapneko/gratte-papier/blob/201b910122327265b3f2fb242d75a1ee54b1b649/LICENSE)
			-	`line2pdf.cabal`: [Source](https://github.com/audreyt/line2pdf/blob/bbc304feb89689d2ce0d21582cc2b763e7210bbc/line2pdf.cabal) | [MIT-licensed](https://github.com/audreyt/line2pdf/blob/bbc304feb89689d2ce0d21582cc2b763e7210bbc/LICENSE)
			-	`defaults.cabal`: Generated by me using `cabal init` <sup><a href="#footnote-1">[1]</a></sup>

## Footnotes

<a name="footnote-1"></a>
<details><summary><sup><a href="#footnote-1">[1]</a></sup> – <code>cabal init</code> output</summary>

~~~console
λ linguist-sample: cabal init
-bash: cabal: command not found
λ linguist-sample: which cabal
λ linguist-sample: brew info $_
Error: No available formula with the name "cabal" 
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
λ linguist-sample: brew search $_
==> Formulae
cabal-install
λ linguist-sample: brew info cabal-install
cabal-install: stable 2.4.1.0 (bottled), HEAD
Command-line interface for Cabal and Hackage
https://www.haskell.org/cabal/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/cabal-install.rb
==> Dependencies
Required: ghc ✔
==> Options
--HEAD
        Install HEAD version
==> Analytics
install: 2,387 (30 days), 13,412 (90 days), 35,225 (365 days)
install_on_request: 972 (30 days), 4,476 (90 days), 14,917 (365 days)
build_error: 0 (30 days)
λ linguist-sample: brew install $_
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
No changes to formulae.

==> Downloading https://homebrew.bintray.com/bottles/cabal-install-2.4.1.0.high_sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring cabal-install-2.4.1.0.high_sierra.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/cabal-install/2.4.1.0: 7 files, 27.3MB
λ linguist-sample: cabal init
Config file path source is default config file.
Config file /Users/john/.cabal/config not found.
Writing default configuration to /Users/john/.cabal/config
Warning: Caught exception during _mirrors lookup:res_query: does not exist
(Connection refused)
Warning: No mirrors found for http://hackage.haskell.org/
Warning: The package list for 'hackage.haskell.org' does not exist. Run 'cabal
update' to download it.
Please choose version of the Cabal specification to use:
 * 1) 1.10   (legacy)
   2) 2.0    (+ support for Backpack, internal sub-libs, '^>=' operator)
   3) 2.2    (+ support for 'common', 'elif', redundant commas, SPDX)
   4) 2.4    (+ support for '**' globbing)
Your choice? [default: 1.10   (legacy)] 4
Package name? [default: linguist-sample] linguist-sample
Package version? [default: 0.1.0.0] v1.0.0
Couldn't parse v1.0.0, please try again!
Package version? [default: 0.1.0.0] 0.1.1.0 
Please choose a license:
   1) GPL-2.0-only
   2) GPL-3.0-only
   3) LGPL-2.1-only
   4) LGPL-3.0-only
   5) AGPL-3.0-only
   6) BSD-2-Clause
 * 7) BSD-3-Clause
   8) MIT
   9) ISC
  10) MPL-2.0
  11) Apache-2.0
  12) LicenseRef-PublicDomain
  13) NONE
  14) Other (specify)
Your choice? [default: BSD-3-Clause] 9
Author name? [default: Alhadis] 
Maintainer email? [default: gardnerjohng@gmail.com] 
Project homepage URL? https://github.com/github/linguist
Project synopsis? Example of a Cabal configuration file for GitHub Linguist
Project category:
 * 1) (none)
   2) Codec
   3) Concurrency
   4) Control
   5) Data
   6) Database
   7) Development
   8) Distribution
   9) Game
  10) Graphics
  11) Language
  12) Math
  13) Network
  14) Sound
  15) System
  16) Testing
  17) Text
  18) Web
  19) Other (specify)
Your choice? [default: (none)] 11
What does the package build:
   1) Library
   2) Executable
   3) Library and Executable
Your choice? 3
What is the main module of the executable:
 * 1) Main.hs (does not yet exist, but will be created)
   2) Main.lhs (does not yet exist, but will be created)
   3) Other (specify)
Your choice? [default: Main.hs (does not yet exist, but will be created)] 1
Source directory:
 * 1) (none)
   2) src
   3) Other (specify)
Your choice? [default: (none)] 2
What base language is the package written in:
 * 1) Haskell2010
   2) Haskell98
   3) Other (specify)
Your choice? [default: Haskell2010] 1
Add informative comments to each field in the cabal file (y/n)? [default: n] y

Guessing dependencies...

Generating LICENSE...
Generating Setup.hs...
Generating CHANGELOG.md...
Generating src/Main.hs...
Generating linguist-sample.cabal...

You may want to edit the .cabal file and add a Description field.
λ linguist-sample: 
~~~

</details>

### CODE REVIEW

**Comment by Alhadis** [comment]
@pchaigno You might want to add [`cabal-ghcjs.project`](https://github.com/search?q=filename%3Acabal-ghcjs.project+NOT+nothack&type=Code) to the popularity monitoring list. There are currently 68 results (~40 unique users), and many of them are relatively recent — it might be worth adding this as a supported filename in future.

**Comment by phadej** [comment]
> You might want to add [`cabal-ghcjs.project`](https://github.com/search?q=filename%3Acabal-ghcjs.project+NOT+nothack&type=Code) to the popularity monitoring lis

people are quite free to have different project files, and the names are definitely not consistent.

e.g. I have used https://github.com/haskell-servant/servant/blob/master/cabal.ghcjs.project (note the dot, not a dash).

If `linguist` support prefix extensions `cabal.` or/and `cabal-`; it would cover more use cases. But I understand that our preference for prefix is quite peculiar, because the single `*.cabal` file in the directory has a special meaning, independent of the actual name,

**Comment by Alhadis** [comment]
> If `linguist` support prefix extensions `cabal.` or/and `cabal-`; it would cover more use cases.

Unfortunately, it doesn't. 😞 We're currently limited to matching complete filenames only (and only as fixed strings; e.g., no regex-aware matching). This is a known limitation of Linguist, I'm afraid.

> people are quite free to have different project files, and the names are definitely not consistent.

Be that as it may, it's still worth keeping an eye on if over 40 users have used this particular filename to date. 👍

**Comment by pchaigno** [comment]
> @pchaigno You might want to add [`cabal-ghcjs.project`](https://github.com/search?q=filename%3Acabal-ghcjs.project+NOT+nothack&type=Code) to the popularity monitoring list. There are currently 68 results (~40 unique users), and many of them are relatively recent — it might be worth adding this as a supported filename in future.

I'm tagging this PR as *Pending Popularity* to remember to add it to #4219.

**Pull request merged**
