### PR TITLE
Add new language PowerBuilder

### PR DESCRIPTION
**Pull request by sahildua2305**
Copying search results from [here](https://github.com/github/linguist/issues/3014#issuecomment-228120275) in #3014 -

- PBL (Library files) [3,100 results](https://github.com/search?utf8=%E2%9C%93&q=NOT+nothack+extension%3Apbl&type=Code&ref=searchresults)
- PBT (Target files) [576 results](https://github.com/search?utf8=%E2%9C%93&q=NOT+nothack+extension%3Apbt&type=Code&ref=searchresults)
- SRW (Window source files) [1,500 results](https://github.com/search?utf8=%E2%9C%93&q=NOT+nothack+extension%3Asrw&type=Code&ref=searchresults)
- SRU (Custom user object source files) [2,460 results](https://github.com/search?utf8=%E2%9C%93&q=NOT+nothack+extension%3Asru&type=Code&ref=searchresults)
- SRP (Data pipeline source files) [6,500 results](https://github.com/search?utf8=%E2%9C%93&q=NOT+nothack+extension%3Asrp&type=Code&ref=searchresults)
- SRA (Application files) [663 results](https://github.com/search?utf8=%E2%9C%93&q=NOT+nothack+extension%3Asra&type=Code&ref=searchresults)
- SRJ (Project files) [1,200 results](https://github.com/search?utf8=%E2%9C%93&q=NOT+nothack+extension%3Asrj&type=Code&ref=searchresults)

I have been following the contributions guide available, but I have been able to add only the language to `languages.yml`. I am confused about adding grammar for a language. I need help in going ahead with this.

/cc @arfon @pchaigno

### CODE REVIEW

**Comment by nixel2007** [comment]
@sahildua2305 
>   1) Failure:
TestLanguage#test_all_languages_have_grammars [/home/travis/build/github/linguist/test/test_language.rb:377]:
The following languages' scopes are not listed in grammars.yml. Please add grammars for all new languages.
If no grammar exists for a language, mark the language with `tm_scope: none` in lib/linguist/languages.yml.
PowerBuilder source.powerbuilder
  2) Failure:
TestPedantic#test_nonprimary_extensions_are_sorted [/home/travis/build/github/linguist/test/test_pedantic.rb:15]:
.srw should come after .sru

**Comment by sahildua2305** [comment]
@nixel2007 Thanks.

I have set `tm_scope` to `none`. Is that going to be an issue? Having no grammar for this language?

**Comment by nixel2007** [comment]
@sahildua2305 
>Is that going to be an issue? Having no grammar for this language?

it's only mean that files will have no syntax highlighting\.

**Comment by sahildua2305** [comment]
@nixel2007 Okay, got it! How do I add grammar for this new language? I'm clueless about this. Can you please help?

**Comment by nixel2007** [comment]
@sahildua2305 you need to define TextMate-based grammar - http://manual.macromates.com/en/language_grammars

You can find some intro [here](http://docs.sublimetext.info/en/latest/extensibility/syntaxdefs.html).
And here you can see a tmLanguage-based and CSON-based grammar, developed for SublimeText and Atom: https://github.com/xDrivenDevelopment/sublime-language-1c-bsl/blob/master/1c.tmLanguage https://github.com/xDrivenDevelopment/atom-language-1c-bsl/blob/master/grammars/1c.cson

**Comment by sahildua2305** [comment]
Thanks a lot for the links. A great help!

So I will write either tmLanguage-based or CSON-based grammar for PowerBuilder. Since the contents of all these extensions vary, should I write different grammar rules for each of these extensions?

Also, if I write https://github.com/sahildua2305/powerbuilder-language/blob/master/1c.cson (for example) I will add this repo as a submodule, is that right?

**Comment by nixel2007** [comment]
> Since the contents of all these extensions vary, should I write different grammar rules for each of these extensions?

Looks like you are right. I don't know anything about PowerBuilder, maybe you need to focus on some "main" extension, where source code is presented? and don't inlcude some project settings or config stuff?

> Also, if I write https://github.com/sahildua2305/powerbuilder-language/blob/master/1c.cson (for example) I will add this repo as a submodule, is that right?

yep. and add a scope entry in languages.yml. maybe you'll need to add different entries to languages.yml with one language-group.

Also, if I remember it right, if you use a CSON-based grammar, there should be a atom-package. I think @pchaigno can correct me, if it doesn't. 

Also you can use a yaml2tmLanguage converter, like i did. I use YAML-file to write grammar (cause in yaml you don't need to \\\\\\escape\\\all\\\that\\\staff:
 https://github.com/xDrivenDevelopment/1c-syntax/blob/master/1c.YAML-tmLanguage
and that convert it to CSON via yamljs node package:
```
yaml2json --pretty 1c.YAML-tmLanguage > 1c.json
json2cson 1c.json > 1c.cson --2spaces
```
or conver to tmLanguage via
```javascript
	var plist = require('plist');
	var fs = require('fs');
	
	var jsonString = fs.readFileSync('./1c.json', 'utf8');
	var jsonObject = JSON.parse(jsonString);
	var plistString = plist.build(jsonObject);
	
	fs.writeFileSync('./1c.tmLanguage', plistString);
```

**Comment by sahildua2305** [comment]
@nixel2007 From what I have seen so far, writing grammar rules for a language is a complex task in itself. Is there any easy way to understand the procedure and to be able to write the grammar rules?

Or can I leave syntax highlighting for someone else to fix later and go ahead with adding this language?

**Comment by nixel2007** [comment]
@sahildua2305 you're right, writing a grammar is a complex task. but you can start with some easy regexps, that will make basic colours.

lets say, that your language will have a "powerbuild" key.

Than you can write something like this (scope: regexp):

```
keyword.operator.powerbuild: (?i)\b(grammarKey1|grammarKey2|...|grammarKeyN)\b
keyword.operator.powerbuild: (.|,|:|;) // punctoators of language
string.quoted.double.powerbuild: (\".*\")
support.function.powerbuild: (?i)\b(builtInFunction1|builtInFunction2|...|builtInFunctionN)\b
```

Just wrap it to keys and matches in CSON with header (name, scope, filetypes) and patterns and try it with https://github-lightshow.herokuapp.com/

**Comment by pchaigno** [comment]
@sahildua2305 @nixel2007 It looks like there are already a few PowerBuilder grammars in the wild: https://github.com/rolando3/language-powerbuilder and https://github.com/richard4339/powerbuilder.tmbundle. I opened issues for licensing terms, so hopefully we should be able to use one of those.

@sahildua2305 Could you check that they do a correct job using [Lightshow](https://github-lightshow.herokuapp.com/)?

**Comment by sahildua2305** [comment]
Thanks @pchaigno 

I am running a bit busy these days so sorry for delayed reply. I will check these grammars using Lightshow soon. Thanks for the links :smile:

**Comment by sahildua2305** [comment]
@pchaigno 

Looks like [this](https://github.com/richard4339/powerbuilder.tmbundle) grammar actually works for [sru](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgithub.com%2Frichard4339%2Fpowerbuilder.tmbundle%2Fblob%2Fmaster%2FSyntaxes%2FPowerbuilder.tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fdarioaxel%2FPowerScriptToKDMTransformer%2Fblob%2F07bf527194b73e133943221dc2199a9442d463eb%2Fresources%2Fadvanced%2Freal%2Fmyproject%2Flib%2Fcommon%2Fn_param.sru&code=),

**Comment by sahildua2305** [comment]
@pchaigno 

Looks like [this](https://github.com/richard4339/powerbuilder.tmbundle) grammar that you mentioned above actually works for [sru](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgithub.com%2Frichard4339%2Fpowerbuilder.tmbundle%2Fblob%2Fmaster%2FSyntaxes%2FPowerbuilder.tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fdarioaxel%2FPowerScriptToKDMTransformer%2Fblob%2F07bf527194b73e133943221dc2199a9442d463eb%2Fresources%2Fadvanced%2Freal%2Fmyproject%2Flib%2Fcommon%2Fn_param.sru&code=), [srw](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgithub.com%2Frichard4339%2Fpowerbuilder.tmbundle%2Fblob%2Fmaster%2FSyntaxes%2FPowerbuilder.tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fsebkirche%2Flibexport%2Fblob%2Fc2459a5399ff87f29344b3b0472b041ebb6f9246%2Fsources%2F115%2Fw_export.srw&code=), [sra](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgithub.com%2Frichard4339%2Fpowerbuilder.tmbundle%2Fblob%2Fmaster%2FSyntaxes%2FPowerbuilder.tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fsebkirche%2Flibexport%2Fblob%2Fc2459a5399ff87f29344b3b0472b041ebb6f9246%2Fsources%2F115%2Flibexport.sra&code=) and [srj](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgithub.com%2Frichard4339%2Fpowerbuilder.tmbundle%2Fblob%2Fmaster%2FSyntaxes%2FPowerbuilder.tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fsebkirche%2Flibexport%2Fblob%2Fc2459a5399ff87f29344b3b0472b041ebb6f9246%2Fsources%2F115%2Fmake_exe.srj&code=) extensions. And even better, this has MIT license now.

**Comment by sahildua2305** [comment]
I have forked that repo and added `.pbl` and `.pbt` extensions as well. Looks like it performs decent enough.
- [PBL](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgithub.com%2Fsahildua2305%2Fpowerbuilder.tmbundle%2Fblob%2Fmaster%2FSyntaxes%2FPowerbuilder.tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fsteven-maasch%2Fvisual-search%2Fblob%2Fd81becdd70cb9e6e33b6d4f148df79d72af590ba%2Fvs.pbl&code=)
- [PBT](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgithub.com%2Fsahildua2305%2Fpowerbuilder.tmbundle%2Fblob%2Fmaster%2FSyntaxes%2FPowerbuilder.tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fdavyxu%2Fcellorigin%2Fblob%2F5b46b37fda0437944930fb336466576b933fb92e%2Fserver%2Fcfg%2FService.pbt&code=)

@pchaigno Please review.

**Comment by sahildua2305** [comment]
@nixel2007 Can you please help me in including grammar rules for comments (//, # and /* /) [here](https://github.com/sahildua2305/powerbuilder.tmbundle/blob/master/Syntaxes/Powerbuilder.tmLanguage) just like they are included [here](https://github.com/rolando3/language-powerbuilder/blob/master/grammars/powerbuilder.cson#L15)?

**Comment by nixel2007** [comment]
@sahildua2305 i'll take a look soon. Tomorrow probably

**Comment by sahildua2305** [comment]
@pchaigno The grammar now includes the support for comments as well and seems to do a good job for all added extensions. Please have a look. :smile: 

Can I go ahead with this and add it?

**Comment by sahildua2305** [comment]
@pchaigno @arfon Please review this.

**Comment by pchaigno** [comment]
@sahildua2305 Please be patient. Reviews can take a long time as we all have other full time jobs/activities ;)

**Comment by sahildua2305** [comment]
Ah! I'm sorry @pchaigno. I'll be patient. Thanks!

**Comment by Alhadis** [comment]
Sahil, it's barely been ten days or so. I have pull requests that've been rotting in the sun for over **two months now**. I know how hard it is to be patient... but as frustrating as it can get after so long, try and imagine how many other issues a repository's maintainers are dealing with. And by "issues" I mean both on GitHub *and* in real life (work, family, money, etc).

**Comment by larsbrinkhoff** [comment]
Two months!  Hah, that's nothing...

**Comment by sahildua2305** [comment]
@Alhadis @larsbrinkhoff Sorry. I haven't been into open source for long. A good lesson to be patient. :)

**Comment by Alhadis** [comment]
Try moving down out where I live, and live off Internet speed that's fed through a straw. With the excruciating loading speed of shit Australian Internet, I sometimes can't tell if my pull request has been ignored, or the freaking thing never posted in the first place.

T E M P U S | F U G I T

**Comment by sahildua2305** [comment]
Never knew Australian internet was shitty :open_mouth:

**Comment by pchaigno** [comment]
@sahildua2305 Could you add a sample file (under permissive license) for each for the file extension you added? Also, it looks like the search results for [`.pbl`](https://github.com/search?utf8=%E2%9C%93&q=NOT+nothack+extension%3Apbl&type=Code&ref=searchresults), [`.srp`](https://github.com/search?utf8=%E2%9C%93&q=NOT+nothack+extension%3Asrp&type=Code&ref=searchresults), and [`.srj`](https://github.com/search?utf8=%E2%9C%93&q=NOT+nothack+extension%3Asrj&type=Code&ref=searchresults) mostly contain data files (numbers, text, and JSON). We should refine these search queries or remove the file extensions.
 
<br>
> I have pull requests that've been rotting in the sun for over two months now.

@Alhadis 19 months for me :stuck_out_tongue_closed_eyes:

**Comment by sahildua2305** [comment]
@pchaigno I just checked again. As you mentioned, even I think we can remove the `.pbl`, `.srp` and `.srj` extensions since these extensions are either json files (`.srj`) or text/data files (`.pbl` and `.srp`).

So I will go ahead and remove these extensions. I have added the samples for the rest of extensions. Please have a look.

**Comment by pchaigno** [comment]
We should find a color for PowerBuild. Otherwise, :+1: for me!

**Comment by sahildua2305** [comment]
@pchaigno What's the logic that goes behind finding the color for a language? Can it be any random color? How can I check whether I can use a particular color or not? Whether it matches with some other language or not?

**Comment by pchaigno** [comment]
> What's the logic that goes behind finding the color for a language? Can it be any random color?

See this comment for some guideline on [how to find a suitable color](https://github.com/github/linguist/pull/2298#issuecomment-90150424). In this case, we'll probably have to use a random color.

> How can I check whether I can use a particular color or not? Whether it matches with some other language or not?

By running [the test](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#testing).

**Comment by pchaigno** [comment]
@sahildua2305 I think we should merge this now and we can add the grammar latter, when the pull request is merged.

@arfon Is this :+1: for you?

**Comment by arfon** [comment]
> @arfon Is this 👍 for you?

:+1: :shipit:

**Comment by pchaigno** [comment]
Thanks @sahildua2305 !

**Comment by sahildua2305** [comment]
Thanks @arfon, @pchaigno and @nixel2007 for helping me throughout. :smile:

**Pull request merged**
