### PR TITLE
Samples from Rosetta Code project

### PR DESCRIPTION
**Pull request by pchaigno**
This pull request adds more than 11,000 sample files from [the Rosetta Code project](http://rosettacode.org). I wrote a [small Python script](https://gist.github.com/pchaigno/3905c8cecd5951f982c5) to copy the samples from [RosettaCodeData](https://github.com/acmeism/RosettaCodeData).

~~It also adds new extensions:~~
- ~~[`.ats`](https://github.com/search?utf8=%E2%9C%93&q=extension%3Aats+NOT+djhfdkjfhjbffjhdejdbnsjd&type=Code&ref=searchresults) for ATS~~
- ~~[`.idl`](https://github.com/search?utf8=%E2%9C%93&q=extension%3Aidl+NOT+djhfdkjfhjbffjhdejdbnsjd&type=Code&ref=searchresults) for IDL~~
- ~~[`.pascal`](https://github.com/search?utf8=%E2%9C%93&q=extension%3Apascal+NOT+djhfdkjfhjbffjhdejdbnsjd&type=Code&ref=searchresults) for Pascal~~
- ~~[`.psh`](https://github.com/search?utf8=%E2%9C%93&q=extension%3Apsh+NOT+djhfdkjfhjbffjhdejdbnsjd&type=Code&ref=searchresults) for PowerShell~~

~~and new interpreters:~~
- ~~[`dart`](https://github.com/search?utf8=%E2%9C%93&q=usr+bin+env+dart+extension%3Adart&type=Code&ref=searchresults) for Dart~~
- ~~[`racket`](https://github.com/search?utf8=%E2%9C%93&q=usr+bin+env+racket+extension%3Arkt&type=Code&ref=searchresults) for Racket~~
- ~~[`io`](https://github.com/search?utf8=%E2%9C%93&q=usr+bin+env+io+extension%3Aio&type=Code&ref=searchresults) for Io~~
- ~~[`factor`](https://github.com/search?utf8=%E2%9C%93&q=usr+bin+env+factor+extension%3Afactor&type=Code&ref=searchresults) for Factor~~
- ~~[`ocaml`](https://github.com/search?utf8=%E2%9C%93&q=usr+bin+env+ocaml+extension%3Aml&type=Code&ref=searchresults) for OCaml~~
- ~~[`rune`](https://github.com/search?utf8=%E2%9C%93&q=usr+bin+env+rune+extension%3Ae&type=Code&ref=searchresults) for E~~
- ~~[`csi`](https://github.com/search?utf8=%E2%9C%93&q=usr+bin+env+csi+extension%3Ascm&type=Code&ref=searchresults) for Scheme~~
- ~~[`runhaskell`](https://github.com/search?utf8=%E2%9C%93&q=usr+bin+env+runhaskell+extension%3Ahs&type=Code&ref=searchresults) for Haskell~~
- ~~[`instantfpc`](https://github.com/search?utf8=%E2%9C%93&q=usr+bin+env+instantfpc+extension%3Apas&type=Code&ref=searchresults) for Pascal~~
- ~~[`gosh`](https://github.com/search?utf8=%E2%9C%93&q=usr+bin+env+gosh+extension%3Ascm&type=Code&ref=searchresults) for Scheme~~
- ~~[`r6rs`](https://github.com/search?utf8=%E2%9C%93&q=r6rs+extension%3Ascm&type=Code&ref=searchresults) for Scheme~~

When the new samples had extensions or interpreters that were not widely used I changed them or removed the files.

### CODE REVIEW

**Comment by bkeepers** [comment]
Brilliant! I love the idea of using known samples like this.

I think I remember a conversation that our system team had concerning the memory usage of the linguist classifier (since it loads `samples.json` into memory when linguist is required). In a quick test on my machine, a fresh ruby process that has only required `linguist` takes up ~52MB in master and ~68MB with this branch.

@vmg @dbussink Is this a concern?

Since the classifier always runs against a known set of languages, we could store the sample data in separate files per language and lazily load it. Repositories typically have a lot of the same type of data, so we could use some kind of LRU cache to avoid churn.

The other option would be to implement (or find an existing implementation of) a classifier in C, keeping memory management out of Ruby land.

/cc #1572

**Comment by lazywei** [comment]
How is this PR going?

> The other option would be to implement (or find an existing implementation of) a classifier in C, keeping memory management out of Ruby land.

I think one possible solution is using the well-known liblinear / libsvm. The reasons:

(0) As mentioned, it's a good practice to generate features in advance and save the features into separate files. And using libsvm / liblinear can help with this: we can save the features into libsvm format, which is really useful for sparse data (e.g., bag-of-word). The loading and saving efforts will be reduced.
(1) liblinear / libsvm separates the training and predicting stages. That is, we can pre-train a SVM (or Logistic Regression) classifier and save its model file as we save the features in (0). Unless the user want to train their model for their own, they can just use our pre-trained classifier. The model file of libsvm / liblinear is very small (only saving information such as support vectors).
(2) The predicting stage of SVM or LogReg is very simple, which means we can even predict by ourself without using libsvm / liblinear as long as we have model file in (1). This implies that we can avoid extra external dependencies if the user is satisfied with our pre-trained classifier.

How do you think?

**Comment by larsbrinkhoff** [comment]
I guess the Forth heuristics doesn't match all of the samples?

**Comment by pchaigno** [comment]
@larsbrinkhoff Yes, that is why I reduced the scope in 7d6650a.

**Comment by pchaigno** [comment]
@arfon Is the memory usage of Linguist still an issue? If it is, maybe we could open an issue to start discussing possible solutions to overcome it...?

**Comment by arfon** [comment]
> @arfon Is the memory usage of Linguist still an issue? If it is, maybe we could open an issue to start discussing possible solutions to overcome it...?

I'll defer to @vmg on this one. @vmg - this PR is attractive as it adds a large, reliable source of samples data...but by doing this we're likely to increase the memory usage of Linguist (see @bkeepers [comment](https://github.com/github/linguist/pull/2117#issuecomment-74776022) above). 

I know that we had significant memory pressure in the past which made this a no-go but is this still the case?

**Comment by larsbrinkhoff** [comment]
@pchaigno I don't know about adding zillions of samples, but this PR has so many other goodies.  Please don't forget about it.

**Comment by Alhadis** [comment]
I'd love to know the size difference of converting spaces to tabs (the way nature intended).

`/optionated prick`.

**Comment by brandonblack** [comment]
> Since the classifier always runs against a known set of languages, we could store the sample data in separate files per language and lazily load it.

This sounds like a really sensible approach to me. @pchaigno what do you think about re-working this effort to lazy load in separate language files?

**Pull request closed without merging**
