### PR TITLE
Revert #1438: add file extensions with multiple segments

### PR DESCRIPTION
**Pull request by pchaigno**
This pull request reverts #1438.
In #1438 I removed all file extensions with multiple segments.
Linguist now support them so we can add them back :zap: 

It should also solve #1568.

### CODE REVIEW

**Comment by arfon** [comment]
Nice! For good housekeeping do you think we should add an example file for each extension @pchaigno ?

**Comment by pchaigno** [comment]
I added the two samples (`.cmake.in` and `.html.hl`) that were missing (I already added some in #1438).

I noticed that `.html.hl` files can be a mix of HTML and Clojure. Should they really be recognized as HTML? @cldwalker may have more information on these files.

**Comment by cldwalker** [comment]
@pchaigno They can be a mix of html and clojure. I chose html at the time because I didn't know if linguist supported syntax highlighting multiple languages for one file.

**Comment by pchaigno** [comment]
@cldwalker I think it's possible if a grammar for `HTML+Clojure` exists. Do you know one?

**Comment by cldwalker** [comment]
I'm not aware of a .html.hl [textmate grammar](https://github.com/github/linguist#syntax-highlighting). @alandipert Do you know of one? If not, it's currently set to render as html unless you'd like for it to stay as clojure

**Comment by larsbrinkhoff** [comment]
Cherry-picked the CMake sample for #1978.

**Comment by arfon** [comment]
This looks good to me. @bkeepers?

**Comment by bkeepers** [comment]
:+1:

**Comment by arfon** [comment]
Thanks @pchaigno

**Pull request merged**
