### PR TITLE
Release v7.14.0

### PR DESCRIPTION
**Pull request by lildude**
Time for a new release.

I aim to merge and deploy this early next week after I've recovered from my chocolate 🥚 coma 😆.

- [ ] Deployed to GitHub.com
- [ ] Grammars deployed to Syntax highlighting service - highlighting won't be 💯 up-to-date until this happens
- [ ] Deployed to Lightshow

### CODE REVIEW

**Comment by lildude** [comment]
I've skipped updating the Cobol grammar again but have submitted fixes to the upstream-upstream grammar repo in https://github.com/spgennard/vscode_cobol/pull/272 which may or may not make it into this release.

**Comment by Alhadis** [comment]
Just an FYI that I'm patching a few oversights in the `.gitconfig` and `.gitignore` grammars. Shouldn't take more than 15-30 minutes, but I thought I'd let you know just in case you're on the verge of cutting the next release.

**Comment by lildude** [comment]
I am. I'll wait 😄

**Comment by Alhadis** [comment]
> Shouldn't take more than 15-30 minutes

Figure 1

Okay, as a rule-of-thumb, whenever I give you a time estimation, it's usually give-or-take double of said duration. 😓

… sorry about this. 😢

**Comment by lildude** [comment]
Lemme know when you're done.

**Comment by Alhadis** [comment]
Of course! I'm testing each change thoroughly, because I don't want to introduce a regression at the last minute...

**Comment by Alhadis** [comment]
Nearly there! While you're waiting, [here's a cool feature](https://css-tricks.com/git-pathspecs-and-how-to-use-them/) of `.gitignore` files I didn't know existed until recently:

~~~gitignore
:(attr:vendored)vendored/*
:(attr:!vendored)not/vendored/*
:(exclude)*.spec.js
:(exclude)*.spec.js
:(exclude,literal)*.spec.js
:(glob)foo.*
:(icase)foo.*
:(literal)foo.*
:(top,icase,glob,attr:!vendored)src/components/*/*.jsx
:(top)foo.*
~~~

**Comment by Alhadis** [comment]
Okay, done! Fire away.

**Comment by lildude** [comment]
I'm not going to get the chance to deploy today before I finish and I'd prefer not to deploy on a Friday so I'll deploy on Monday.

**Comment by Alhadis** [comment]
Shit. Please tell me that wasn't my fault…

**Comment by lildude** [comment]
> Shit. Please tell me that wasn't my fault…

Nope. The day job needed to take priority this afternoon 😁

**Comment by lildude** [comment]
And we're now live with v7.14.0 across GitHub.com and Lightshow 🎉

**Comment by FAvE01** [comment]
release-v7.14.0

**Pull request merged**
