### PR TITLE
Add support for HLSL

### PR DESCRIPTION
**Pull request by kusma**
This adds support for DirectX HLSL language. Fixes issue #2841

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
Nice.  I did some work to add HLSL, but never quite finished.  I'll try to piggy-back it on your work.

**Comment by larsbrinkhoff** [comment]
`.fx` is also used by GLSL.  Did you check for conflicts?

**Comment by larsbrinkhoff** [comment]
There's also `.fxh` which seems to be used for HLSL header files.

**Comment by larsbrinkhoff** [comment]
I can't seem to find much FLUX code at all on GitHub.  Is there any?

On the other hand, I found [this JavaFX code](http://github.com/search?q=extension%3Afx+package+import+public+class&).

**Comment by kusma** [comment]
@larsbrinkhoff: Thanks for feedback.

Interesting point about .fx also being used for GLSL, I was not aware... I wonder why, though. Anyway, I don't think this patch series makes the situation any worse in that regard, though. So perhaps adding .fx to GLSL would be OK to be done as a follow-up?

I forgot about .fxh, I'll update the commit to include that. It seems [.hlsli is also used](https://github.com/search?utf8=%E2%9C%93&q=extension%3Ahlsl+%23include+AND+hlsli&type=Code&ref=searchresults)

About the FLUX code, I wasn't even aware of FLUX before I noticed my HLSL were misdiagnosed. And it seems to be an experimental language that only really lived for a very short time, according to https://plasma.cs.umass.edu/emery/flux.1.html (it's marked as unmaintained, and only ever reached v0.02)... So I would be surprised if there were any notable amounts of FLUX code on GitHub. But I don't want to be the one to remove someone else's contribution, so I tried to fix it up best as I could.

People who care about JavaFX can IMO add support for that. I don't know much about it besides it's existence...

So, unless you disagree with my assessments, I think updating HLSL to include .fxh and .hlsli is the way to go...

**Comment by larsbrinkhoff** [comment]
I'm not opposed to stating that I don't disagree!

**Comment by arfon** [comment]
@kusma - would you mind updating this thread with links to search queries demonstrating the usage of each of these extensions?

Thanks!

**Comment by kusma** [comment]
@arfon: Sure, here you go:

- [.fx](https://github.com/search?q=extension%3Afx+NOT+nothack&type=Code&ref=searchresults)
- [.fxh](https://github.com/search?q=extension%3Afxh+NOT+nothack&type=Code&ref=searchresults)
- [.hlsl](https://github.com/search?q=extension%3Ahlsl+NOT+nothack&type=Code&ref=searchresults)
- [.hlsli](https://github.com/search?q=extension%3Ahlsli+NOT+nothack&type=Code&ref=searchresults)

**Comment by arfon** [comment]
:+1: thanks @kusma. Sorry it took me a while to review this.

This will be live in the next release of Linguist (later this week sometime)

**Comment by kusma** [comment]
Cool, thanks! No problem with the timing, I'm not in a hurry ;)

**Comment by larsbrinkhoff** [comment]
Was it intentional to make `.fx` the primary file extension instead of e.g. `.hlsl`?

**Comment by kusma** [comment]
Hm, I started out with .fx, so I guess that's why. But I guess the primary extension should be .hlsl, yeah. So no, not intentional, and probably not ideal.

**Comment by kusma** [comment]
Hm, wait. Didn't I make HLSL the name of the language? I don't think I understand what the primary extension is. I just alphabetized the list of extensions... Was that wrong?

**Comment by larsbrinkhoff** [comment]
It's a well-kept secret that the first item in the extensions list is the primary extension. ;-)

https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L10

**Comment by arfon** [comment]
> https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L10-L12

Worst docs ever... :disappointed:

**Comment by kusma** [comment]
OK, I'll submit a patch to fix this :)

**Comment by kusma** [comment]
#2870 tries to remedy this. Sorry for the mistake!

**Comment by bleamika** [comment]
yes it's really too.. make me dubbing

**Pull request merged**
