### PR TITLE
languages.yml: Add settings.json to JSON with Comments list of files

### PR DESCRIPTION
**Pull request by perlun**
## Description
Essentially a followup to #4171, this adds a missing `jsonc` file name to the list.

Case in point: https://github.com/perlun/dotfiles/blob/master/vscode/settings.json; as seen right now, this file is not rendered very beautifully on GitHub:

image

Here are some more details about this file: https://code.visualstudio.com/docs/getstarted/settings#_settings-file-locations

## Checklist:

- [ ] **I am associating a language with a new file extension.**
  - [ ] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      
      - https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am adding a new language.**
  - [ ] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  
  - [ ] I have included a syntax highlighting grammar: https://github-lightshow.herokuapp.com/
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

- [ ] **I am fixing a misclassified language**
  - [ ] I have included a new sample for the misclassified language:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am changing the source of a syntax highlighting grammar**
  
  - Old: https://github-lightshow.herokuapp.com/
  - New: https://github-lightshow.herokuapp.com/

- [ ] **I am updating a grammar submodule**
  

- [ ] **I am adding new or changing current functionality**
  
  - [ ] I have added or updated the tests for the new or changed functionality.

- [ ] **I am changing the color associated with a language**
  
  - [ ] I have obtained agreement from the wider language community on this color change.
    - [URL to public discussion]
    - [Optional: URL to official branding guidelines for the language]

### CODE REVIEW

**Comment by smola** [comment]
`settings.json` is a very common file name beyond vscode, see [filename:settings.json](https://github.com/search?l=&p=96&q=filename%3Asettings.json&ref=advsearch&type=Code&utf8=%E2%9C%93). A considerable number of results is for vscode ([search query](https://github.com/search?utf8=%E2%9C%93&q=filename%3Asettings.json+path%3A.vscode&type=Code&ref=advsearch&l=&l=)) but many others do not look like it.

**Comment by Alhadis** [comment]
@smola is right. `settings.json` is far too generic a filename; comments aren't valid JSON, so authors need to know when there's an error in their syntax.

Microsoft should really be using `.jsonc` as an extension for their VSCode config files...

**Comment by pchaigno** [comment]
Note that you can use Linguist overrides to fix the issue in your repositories.

**Comment by perlun** [comment]
@pchaigno 

> Note that you can use Linguist overrides to fix the issue in your repositories.

Thanks for the suggestion. In case anyone is interested in doing the same, here's how I did it: https://github.com/perlun/dotfiles/commit/5530f1a9127e1085b38e86e4aa61229e8445d37f. Seems to be picked up by GitHub correctly, the file is now rendered much more beautifully. 🙇 

@Alhadis 

> @smola is right. `settings.json` is far too generic a filename; comments aren't valid JSON, so authors need to know when there's an error in their syntax.
> 
> Microsoft should really be using `.jsonc` as an extension for their VSCode config files...

Yeah, it's a tough balance in finding "good defaults". If you are _overly_ generic in patterns added, you might help some VSCode users but cause problems for others, like you describe. I can live with the decision suggested here, given that it's easy to add a manual Linguist override.

The matter has in fact been discussed briefly in the VSCode repository: https://github.com/microsoft/vscode/issues/79744, and the suggestion implied there (to support `settings.jsonc` in addition to `settings.json`) makes quite a bit of sense to me as a way to avoid causing too much pain for existing users. If anyone wants to push this further, I suggest making a new issue there or if you are bold & brave, a PR.

Closing this PR now, thanks for valuable feedback.

**Pull request closed without merging**
