### PR TITLE
Add PEG.js language

### LINKED ISSUE #5373: Support for PEG.js grammar files (.pegjs)
Honestly I'm surprised to see this seems to be missing considering the age and popularity of PEG.js. I didn't see any issues in this repository either 🤔 

## Language name
[`PEG.js`](https://pegjs.org/)

## URL of example repository
https://github.com/pegjs/pegjs/tree/master/examples

## URL of syntax highlighting grammar
There appear to be a number of grammars https://atom.io/packages/language-pegjs, https://github.com/alexstrat/PEGjs.tmbundle, https://github.com/telyn/Sublime-PEGjs

## Most popular extensions
`.pegjs`

## Detected language
Not clear what this is asking, but I think the answer is `pegjs`.

### PR DESCRIPTION
**Pull request by Nixinova**
## Description
Adds the [PEG.js](https://pegjs.org/) language, file extension `.pegjs`.
Resolves #5373

## Checklist:
- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension: [.pegjs](https://github.com/search?q=extension%3Apegjs&type=code) - 100K+
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source: [repo](https://github.com/cujojs/rest/blob/master/parsers/rfc5988.pegjs), MIT
  - [x] I have included a syntax highlighting grammar: [repo](https://github.com/alexstrat/PEGjs.tmbundle), [lightshow][lightshow]
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

 [lightshow]: https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Falexstrat%2FPEGjs.tmbundle%2Fmaster%2FSyntaxes%2FPEGjs.tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Faybarsgocerler%2Fecommerce-app%2F071633a95734219f01cddd77512915b10c9233c7%2Fnode_modules%2Fxcode%2Flib%2Fparser%2Fpbxproj.pegjs&code=

### CODE REVIEW

**Review by lildude — DISMISSED** [review]
Whoops. Looks like you forgot to commit the cached license file.

**Comment by lildude** [comment]
> Whoops. Looks like you forgot to commit the cached license file.

Scratch that. I now see the repo doesn't have a license and seems like it won't be getting one any time soon considering it was first requested in 2014 in https://github.com/alexstrat/PEGjs.tmbundle/issues/2 . We can't use a grammar without a license. 

Please find a different grammar.

**Comment by Alhadis** [comment]
> Please find a different grammar.

I'll see if I can write one for the [`language-grammars`](https://github.com/Alhadis/language-grammars) repository. Adding a PEG.js grammar has been on that repo's to-do list for a while now, anyway.

**Comment by Alhadis** [comment]
[All done](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=cson&grammar_url=https%3A%2F%2Fgithub.com%2FAlhadis%2Flanguage-grammars%2Fblob%2Fmaster%2Fgrammars%2Fpegjs.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fpegjs%2Fpegjs%2Fblob%2Fmaster%2Fsrc%2Fparser.pegjs&code=).

**Review by Alhadis — APPROVED** [review]
I've pushed changes to @Nixinova's branch which replaces `PEGjs.tmbundle` in favour of [`Alhadis/language-grammars@cbeecb8`](https://github.com/Alhadis/language-grammars/commit/cbeecb8a856f1536174a1f4370bc00285576bf40). @lildude, this LGTM. 👍

**Review by lildude — APPROVED** [review]
LGTM. Thanks peeps 🙇

**Pull request merged**
