### PR TITLE
change scope of dockerfile

### PR DESCRIPTION
**Pull request by kasperk81**
## Description
textmate grammar isn't maintained in seven years and fails to highlight new syntax https://github.com/asbjornenge/Docker.tmbundle/issues/39. changing scope to bash per @princemaple comment.

## Checklist:

- [ ] **I am adding a new extension to a language.**
  - [ ] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      
      - https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am adding a new language.**
  - [ ] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a syntax highlighting grammar: [URL to grammar repo]
      
  - [ ] I have added a color
    - Hex value: `#RRGGBB`
    - Rationale: 
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

- [ ] **I am fixing a misclassified language**
  - [ ] I have included a new sample for the misclassified language:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am changing the source of a syntax highlighting grammar**
  - Old: [URL to grammar repo]
  - New: [URL to grammar repo]

- [ ] **I am updating a grammar submodule**
  

- [ ] **I am adding new or changing current functionality**
  
  - [ ] I have added or updated the tests for the new or changed functionality.

- [ ] **I am changing the color associated with a language**
  
  - [ ] I have obtained agreement from the wider language community on this color change.
    - [URL to public discussion]
    - [Optional: URL to official branding guidelines for the language]

### CODE REVIEW

**Comment by princemaple** [comment]
Sorry I didn't make it clear. I thought the issue was filed against the sublime syntax, so I suggested using the `Dockerfile (with Bash)` sublime syntax instead. The GitHub syntax has nothing to do with sublime. If it was using the TM language file from the referenced repo (which has both TM language and sublime syntax), someone has to update the TM language file. I don't think there is any change that needed to be done here.

**Comment by kasperk81** [comment]
this is switching tm to sublime. linguist understands both syntaxes. so if sublime is newer and maintained, then we should switch to it.

**Comment by lildude** [comment]
You can't randomly change the `grammars.yml` file. It is automatically maintained based on the content of the grammar repos. This change also won't make any difference as the `tm_scope` defined in `languages.yml` is what will be used. If the grammar is no longer maintained and has bugs that won't be fixed, you should submit a PR to change the grammar (see CONTRIBUTING.md).

Closing this PR as it's the wrong approach to take.

**Comment by lildude** [comment]
> this is switching tm to sublime. linguist understands both syntaxes. so if sublime is newer and maintained, then we should switch to it.

Oh yes, Linguist only supports TextMate compatible Sublime grammars. Sublime 3 and later grammars are not TextMate compatible.

**Pull request closed without merging**
