### PR TITLE
Add support for record-jar files

### PR DESCRIPTION
**Pull request by Alhadis**
This pull-request adds support for the [record-jar](http://www.catb.org/esr/writings/taoup/html/ch05s02.html#id2906931) format, the best-known example of which (and the only one with sufficient distribution) is the [IANA language subtag registry](http://www.iana.org/assignments/language-subtag-registry/language-subtag-registry).

More background on this format can be found at a [7-year old repository of mine](https://github.com/Alhadis/Record-Jar), which actually does a pretty good job of explaining it.

## Distribution
* [528 code results](https://github.com/search?q=filename%3Alanguage-subtag-registry+extension%3Atxt+NOT+nothack&type=Code) (harvested [here](https://github.com/Alhadis/Silos/blob/language-subtag-registry/urls.log), with most dupes [removed](https://github.com/Alhadis/Silos/tree/0611414cb63b248df9b60ce2e10c9ecf29ec2571/files))
* [360 repositories](https://github.com/Alhadis/Silos/blob/0611414cb63b248df9b60ce2e10c9ecf29ec2571/repos.log#L360)
* [274 users](https://github.com/Alhadis/Silos/blob/0611414cb63b248df9b60ce2e10c9ecf29ec2571/users.log#L274)

## Syntax highlighting samples
* [`language-subtag-regsitry`](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=cson&grammar_url=https%3A%2F%2Fgithub.com%2FAlhadis%2Flanguage-etc%2Fblob%2Fmaster%2Fgrammars%2Frecord-jar.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fau-research%2FANDS-ResearchVocabularies-Registry%2Fblob%2F3378fec88737274b4d2ed51915918031a755b794%2Fconf%2Flanguage-subtag-registry&code=)
* [`nametable`](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=cson&grammar_url=https%3A%2F%2Fgithub.com%2FAlhadis%2Flanguage-etc%2Fblob%2Fmaster%2Fgrammars%2Frecord-jar.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgitlab.com%2Fesr%2Fascii%2F-%2Fraw%2Fmaster%2Fnametable&code=)

## Origin of sample
Freely distributed by IANA and released to the [public domain](http://bartoc.org/en/node/2022#access).

## Rationale for colour choice
I picked `#0673ba` from [IANA's logo](https://www.iana.org/_img/2015.1/iana-logo-homepage.svg), because record-jars (like most Unix text-file formats) don't have any "branding" so to speak.

### CODE REVIEW

**Comment by lildude** [comment]
> ## Origin of sample
> 
> Freely distributed by IANA and released to the [public domain](http://bartoc.org/en/node/2022#access).

Whooopsie, looks like we're missing a commit as there isn't a sample on this PR at the mo 😉

**Comment by Alhadis** [comment]
@lildude Whoops. Fixed.

**Comment by lildude** [comment]
Woah! It's hooog!! But I see it's pretty much the same file in every repo.

**Review by lildude — APPROVED** [review]

**Comment by Alhadis** [comment]
> Woah! It's hooog!! But I see it's pretty much the same file in every repo.

Holy _hell_, why didn't you tell me I was committing a 48,149-line sample??? :| That was supposedto be a *cropped* version of the database in the order of bytes, not minutes (spent waiting on your browser if you open the sample on GitHub). 😁

I'll make a note to remedy my brainfart later, because a 694.19 KB sample is simply unacceptable. Hell, _69.4_ KB would've been unacceptable.

Promise me you'll kick my arse if I do that ever again. 😜

**Comment by lildude** [comment]
> Promise me you'll kick my arse if I do that ever again. 😜

Promise 😆

**Pull request merged**
