### PR TITLE
Reclassify Protobuf as programming language

### PR DESCRIPTION
**Pull request by ZJvandeWeg**
Protobuf was first a markup language, but changed to a data type in 5633fd36683241a052461538f0c98657d2325c5d. However, it's a programming language
just as Cap'n Proto

## Checklist:

- [ ] **I am associating a language with a new file extension.**
  - [ ] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am adding a new language.**
  - [ ] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  
  - [ ] I have included a syntax highlighting grammar: https://github-lightshow.herokuapp.com/
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

- [X] **I am fixing a misclassified language**
  - [ ] I have included a new sample for the misclassified language:
   
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am changing the source of a syntax highlighting grammar**
  
  - Old: https://github-lightshow.herokuapp.com/
  - New: https://github-lightshow.herokuapp.com/
  
- [ ] **I am updating a grammar submodule**
  

- [ ] **I am adding new or changing current functionality**
  
  - [ ] I have added or updated the tests for the new or changed functionality.

### CODE REVIEW

**Comment by pchaigno** [comment]
Isn't it used only to serialized structured data? I'm not sure most GitHub users would want to see Protocol Buffer files counted in their language statistics...

**Comment by ZJvandeWeg** [comment]
@pchaigno No, for example: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/apis/deviceplugin/v1alpha/api.proto

That file is created by a user, which that by compiling a file will generate code for the languages of your choosing. The resulting, and thus generated code, is not included but the proto files itself are.

**Comment by Alhadis** [comment]
@ZJvandeWeg If it's a programming language, how does one perform loops or branching? Can you demonstrate a basic `if { … } else { … }` construct in Protocol Buffer? Does the language have any programmatic features?

A "data" language can also cover configuration files, which are written by hand (instead of being machine-generated).

**Comment by Alhadis** [comment]
Yacc *is* because it contains entire code chunks which can be passed through to the compiled output.

`sed` is an odd one, because it actually *is* a Turing-complete programming language, and people have even [programmed games](https://github.com/uuner/sedtris) using nothing but `sed` syntax.

**Comment by pchaigno** [comment]
@Alhadis I agree it's not a programming language, but why the change from markup to data?

**Comment by Alhadis** [comment]
How/why on earth would you consider this markup? 😕

**Comment by pchaigno** [comment]
I agree that's weird too, but it's not data, it's a description of how to format data, kind of like XSD.

**Comment by Alhadis** [comment]
Correct, like a configuration file. Those too, get lumped under the `data` umbrella.

**Comment by pchaigno** [comment]
> Correct, like a configuration file.

Fair enough.

**Comment by Alhadis** [comment]
@ZJvandeWeg I'd like to mention that if you want a non-detectable language type to appear in your repository's statistics, you can do so [using an override](https://github.com/github/linguist#detectable). Add this to your project's `.gitattributes` file (create one if it doesn't exist):

~~~shell
*.proto linguist-detectable=true
~~~

**Pull request closed without merging**
