### PR TITLE
Add support for cql and ddl files

### PR DESCRIPTION
**Pull request by joaquincasares**
The Cassandra Query Language is pretty similar to that of SQL with a few trivial changes. Whenever I try .sql file extensions it maps closely to what I would expect.

https://cassandra.apache.org/doc/cql3/CQL.html

Here are the change for .cql and, more broadly, .ddl files.

Thanks!

### CODE REVIEW

**Comment by joaquincasares** [comment]
I've added a sample file with both the .cql and .ddl extensions. Thanks!

**Comment by pchaigno** [comment]
Great! It looks good to me, you just have to wait for someone from GitHub to review and merge ;)

**Comment by joaquincasares** [comment]
Awesome! Thanks for helping!

**Comment by aroben** [comment]
Thanks @joaquincasares!

**Comment by joaquincasares** [comment]
Thanks for merging!

**Pull request merged**
