### PR TITLE
Release v7.9.0

### PR DESCRIPTION
**Pull request by lildude**
## Description

Just over a month since the last release so time for another.

- [x] Test deploy to GitHub.com locally and in staging
- [x] Deploy to GitHub.com
- [ ] Deploy grammar update to syntax highlighter
- [ ] 🎉 

/cc @rewinfrey 

_[ Template removed as it doesn't apply ]_

### CODE REVIEW

**Comment by lildude** [comment]
I'm going to use this opportunity to test the changes in https://github.com/github/linguist/pull/4730 too. 

/cc @smola

**Comment by lildude** [comment]
Linguist v7.9.0 is now live on GitHub.com.

**Comment by mahrud** [comment]
Do you have an estimate for when the next release would be? (Sorry for unearthing this thread!)

**Comment by lildude** [comment]
@mahrud  In the next week or two. I've already started the process so it's mostly testing and deploy queuing to do. I'll be opening the PRs etc today.

**Pull request merged**
