### PR TITLE
Add Microsoft AL Code Language

### PR DESCRIPTION
**Pull request by JeremyVyska**
Microsoft Dynamics 365 Business Central uses the AL Code language, which this PR adds support for the .AL files.

## Description
Hello!  First time contributor, so hopefully I've got it all correct.

Microsoft Dynamics 365 Business Central uses the AL Code language, which increasingly will grow as a presence in both public and private repositories, such as the repo run by the Microsoft team over at:  https://github.com/microsoft/AL

Currently, all .AL extension files are being detected as PERL across the platform.

I have added the new language to the language file.  The color is the branding logo color for the platform.  The syntax/grammar file repo I created uses the officially provided TM language syntax Microsoft publishes to us in the VSIX/Extension for AL Code Development.

The code samples in the Sample File are from an @ajkauffmann repo under the MIT License for training purposes:  https://github.com/ajkauffmann/ALCodeSamples

There are lots of in the wild examples now, as shown in this search:
https://github.com/search?q=extension%3Aal+dynamics&type=Code

There is still slow adoption of a uniform tagging of the projects to the language, so some repos can be found via:
https://github.com/topics/al-language
https://github.com/topics/dynamics-365-business-central

As far as I can tell, this passes all the `bundle exec rake test` checking that I can figure out.

## Checklist:

- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?q=extension%3Aal+field&type=Code
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - https://github.com/ajkauffmann/ALCodeSamples
    - Sample license(s):
  
  - [x] I have included a syntax highlighting grammar: https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FAL%2Fblob%2Fmaster%2Fgrammar%2Falsyntax.tmlanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fajkauffmann%2FALCodeSamples%2Fblob%2Fmaster%2FGitHub%2520AL%2520Issues%2FPages%2FALIssueList.al&code=

### CODE REVIEW

**Comment by JeremyVyska** [comment]
Apologies, I didn't spot that it included my tweak to script/grammar-compiler to make it work in my WSL1 environment.  Hopefully that individual change can be skipped over.

**Comment by JeremyVyska** [comment]
Additional code samples suggested by the community (@hougaard) to show adoption:
https://github.com/microsoft/ALAppExtensions

**Comment by JeremyVyska** [comment]
Hmm, still trying to verify the 'in the wild' methods to warrant the addition in a cleaner way for your team.

I realized that just about every AL Code project has a ".vscode/launch.json" file with a property in it, and this was the most compelling search result yet - every "Code" result appears to be the AL Code launch.json file, which means there are about 600-700 repositories with AL Code.

Search:  https://github.com/search?q=filename%3Alaunch.json+schemaUpdateMode

**Comment by pchaigno** [comment]
@JeremyVyska If you update the original post's template with a GitHub search query for AL Code files, we will then be able to use [Harvester](https://github.com/Alhadis/harvester) to count the number of repositories these files are in. We can then correlate that with your second approach to count the number of repositories :+1:

**Comment by JeremyVyska** [comment]
Apologies, missed a copy/paste on the template.  Fixed now.

Thanks for the review and confirmation it's looking good.  Let me know if you need anything at all - the team at Microsoft who made the language is available for any assistance we might need too.

**Comment by JeremyVyska** [comment]
Thanks for the tip about Harvester!  Took a little to learn to use it, but I was able to refine the search commands a bit more.   

I used both search techniques (the AL file type as search 1, the json technique as search 2) and managed to come up with some Unique repo lists for each.

I combined and deduped the lists, and have attached all the results.    Hope this simplifies the process - it's appreciated.
[unique-repos-1.txt](https://github.com/github/linguist/files/4906857/unique-repos-1.txt)
[unique-repos-2.txt](https://github.com/github/linguist/files/4906858/unique-repos-2.txt)
[unique-repos-cross-deduped.txt](https://github.com/github/linguist/files/4906859/unique-repos-cross-deduped.txt)
[al-harvest-1.txt](https://github.com/github/linguist/files/4906860/al-harvest-1.txt)
[al-harvest-2.txt](https://github.com/github/linguist/files/4906861/al-harvest-2.txt)

**Comment by JeremyVyska** [comment]
@pchaigno / @lildude - This was approved, but is now out of date.  Do I need to do the merge or will you do that as part of accepting this?

**Comment by lildude** [comment]
> Do I need to do the merge or will you do that as part of accepting this?

That's not a problem as we can click the "Update branch" button and it'll update your branch.

I've taken a quick look at this PR and `.al` is already associated with Perl and appears to be incredibly popular. We're going to need a heuristic added to this PR to differentiate between the two.

**Comment by JeremyVyska** [comment]
Oh jeez.  OK, I read that section of the CONTRIB and was really happy it didn't apply.  

Does this mean I need to help gather an army of Perl .al files versus Microsoft AL Code .al files for testing?  Do I need to learn how to make the Heuristic?   

I can certainly do a detailed guide on what .al files will contain.   In summary, it's Object Oriented, in a way, but the root of each file can only contain a limited prescribed list of object types.   In the Syntax highlighting from the Microsoft AL Code repo, this section:

```
		<dict>
			<key>match</key>
			<string>\b(?i:(CODEUNIT|PAGE|PAGEEXTENSION|PAGECUSTOMIZATION|DOTNET|ENUM|ENUMEXTENSION|VALUE|QUERY|REPORT|TABLE|TABLEEXTENSION|XMLPORT|PROFILE|CONTROLADDIN))\b</string>
			<key>name</key>
			<string>keyword.other.applicationobject.al</string>
		</dict>
```

That is the root of "applicationobjects" that are allowed.  If there isn't a non-indented line with 
```
[keyword] [number] ["name"][Linefeed]
{ 
```

then it be considered not a valid AL Code .al file.

**Comment by lildude** [comment]
> Does this mean I need to help gather an army of Perl .al files versus Microsoft AL Code .al files for testing?

Not really, but it will help you validate your heuristic. You could just use the samples in Linguist and this PR to start.

> Do I need to learn how to make the Heuristic?

You probably know how to do this already 😉 The heuristics are a series of regular expressions added to https://github.com/github/linguist/blob/master/lib/linguist/heuristics.yml to differentiate the languages for each extension. As you're only differentiating between two languages, you only need to ensure the MS AL regex is right and fallback to Perl as everything is currently assumed to be Perl.  @Alhadis is pretty good at these if you need a hand.

We'll also need tests for the heuristic too.

**Comment by JeremyVyska** [comment]
Roger - I will update the PR with new RegEx in the heuristics.yml.

What actions should I take to help with tests for the heuristics?

**Comment by lildude** [comment]
> What actions should I take to help with tests for the heuristics?

Something like the other tests, for example like this `.as` heuristic test should do the trick: https://github.com/github/linguist/blob/96ad1185828f44bb9b774328a584551ee57ed264/test/test_heuristics.rb#L64-L69

This uses the samples in the repo (and this PR) to verify the heuristic.

Oh yes, and the license file format has changed in master, so you'll need to run `bundle exec licensed cache -c vendor/licenses/config.yml`, add the new file and remove the old `vendor/licenses/grammar/AL.txt` file.

**Comment by JeremyVyska** [comment]
OK!   Licensing update merged and updated.  Heuristics Regex added (with Perl as the default 'fallback' - I checked over Perl AL files and the Regex is really AL Code specific), as well as the testing hooks added for .al files, I believe, to check if it's AL Code or Perl AutoLoader.

**Review by lildude — APPROVED** [review]
LGTM

**Comment by JeremyVyska** [comment]
Thank you @lildude - it's going to be awesome to get this merged and start seeing it flow through GH.

**Comment by borisimple** [comment]
Is there a chance that "AL Code" get renamed to "AL" only?
In Azure DevOps .al files are categorised as AL, not "AL Code".

**Comment by lildude** [comment]
> Is there a chance that "AL Code" gets renamed to "AL" only?

Sure. I don't have the bandwidth right now, but please feel free to submit a PR yourself.

**Comment by borisimple** [comment]
> > Is there a chance that "AL Code" gets renamed to "AL" only?
> 
> Sure. I don't have the bandwidth right now, but please feel free to submit a PR yourself.

Done that. is there anything else I should do to get this thing rolling? :)

**Comment by lildude** [comment]
Nope. https://github.com/github/linguist/pull/5023 is waiting for review from one of the external maintainers. Even once merged, it won't take effect on GitHub.com until I've made a new release.

**Pull request merged**
