### PR TITLE
Added interpreter "pike" for Pike.

### PR DESCRIPTION
**Pull request by Frigolit**
Fixes detection of Pike files without file extensions but with interpreter specified.

### CODE REVIEW

**Comment by pchaigno** [comment]
Hey @Frigolit! Could you add a sample file in `samples/Pike/` with this shebang?

**Comment by Frigolit** [comment]
There we go~ "/usr/bin/env pike" is preferred as distros tend to place it in either /usr/bin or /bin, and custom builds by default end up in /usr/local/bin.

**Comment by pchaigno** [comment]
Thanks. I'm not from GitHub so I can't say for sure but pull requests pretty straightforward like this one are usually merged quickly. So you just need to wait now :-)

**Comment by Frigolit** [comment]
Alrighty, thank you :)

**Comment by arfon** [comment]
Looks good. Thanks @Frigolit and @pchaigno. It will be another couple of weeks before this change is live on GitHub.

**Pull request merged**
