### PR TITLE
Highlight Brewfile as Ruby

### PR DESCRIPTION
**Pull request by josh**
Hey @arfon!

First time linguist contributor here! Does this look okay?

### CODE REVIEW

**Comment by pchaigno** [comment]
With a sample `Brewfile` in `samples/Ruby/filenames/` it will be perfect!
Sample files are used for testing (and training) so we consider it good practice to add a new sample for each new extension/filename ;)

**Comment by josh** [comment]
Added sample Brewfile.

**Comment by arfon** [comment]
> First time linguist contributor here!

:-) thanks @josh - looks great.

**Comment by arfon** [comment]
:+1: thanks. I'll probably cut a new gem early next week.

**Pull request merged**
