### PR TITLE
Add file extension for SnakeMake

### PR DESCRIPTION
**Pull request by nh13**
Previously a file name was defined for [SnakeMake](snakemake-wrappers.readthedocs.io): https://github.com/github/linguist/pull/1834

Currently, the canonical extension is `smk` (see [this discussion](https://groups.google.com/forum/#!topic/Snakemake/segLE-RlV_s) with the author (@johanneskoester) of SnakeMake, and the [FAQ](http://snakemake.readthedocs.io/en/stable/project_info/faq.html#how-do-i-enable-syntax-highlighting-in-vim-for-snakefiles)).

### CODE REVIEW

**Comment by lildude** [comment]
Sorry about the delay in getting to this PR. Unfortunately, this extension isn't popular enough on GitHub for this PR to be merged. At the moment, the stats are:

Total files found: 911
Unique public user/repos: 113
Unique owners: 95

As per the contributing guidelines at https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-an-extension-to-a-language "we prefer that extensions be in use in hundreds of repositories before supporting them in Linguist." This is close, but no cigar.

Accordingly, I'll added the "Pending popularity" label.

**Comment by johanneskoester** [comment]
To clarify, it should be both, `Snakefile` and `.smk` be considered the official way to detect Snakemake related files.
Maybe this is a misunderstanding, but it seems like it already works for .smk: https://github.com/snakemake-workflows/rna-seq-star-deseq2/blob/master/rules/align.smk

**Comment by lildude** [comment]
> Maybe this is a misunderstanding, but it seems like it already works for .smk: https://github.com/snakemake-workflows/rna-seq-star-deseq2/blob/master/rules/align.smk

That file is currently being detected as Python because you've asked for it to be detected as Python - https://github.com/snakemake-workflows/rna-seq-star-deseq2/blob/master/.gitattributes 😄

**Comment by johanneskoester** [comment]
Ah, I forgot about that. Thanks for the clarification!

**Comment by johanneskoester** [comment]
Ok, but still, you already do this automatically for files called "Snakefile". So, basically it is already in. What stands against also doing it for .smk?

**Comment by lildude** [comment]
> Ok, but still, you already do this automatically for files called "Snakefile". So, basically it is already in. What stands against also doing it for .smk?

As I mentioned before, popularity. Snakefile is a defined file that is waaaay more popular than the `.smk` extension and easily satisfies the "hundreds of repositories" requirement. `.smk` barely tips over 100 at the moment.

**Comment by johanneskoester** [comment]
Ok, I see, given that criterion, this is of course clear. However, both are for the same tool though (Snakemake). While many people just need a single `Snakefile`, they add these `.smk` files for modularization within the same repo. Shouldn't popularity rather be measured via the tool, hence taking the sum of Snakefile and .smk occurrences?

**Comment by lildude** [comment]
> Shouldn't popularity rather be measured via the tool, hence taking the sum of Snakefile and .smk occurrences?

Unfortunately not. Peeps can use whatever extension they like with most languages. Just because Python is popular, doesn’t mean we should accept `.foobar23` as a Python extension when a few peeps use it.

**Comment by johanneskoester** [comment]
Ok, I understand. We can wait then ;-).

**Comment by pchaigno** [comment]
Closing in favor of #4219. We'll monitor the popularity of the extension there.

If you have an improved search query compared to the one used in #4219, please post it here and I'll update #4219.

**Comment by pchaigno** [comment]
The `.smk` file extension is now popular enough for inclusion (see #4219). @nh13 Do you want me to reopen this pull request or would you prefer to resubmit as a new pull request?

**Comment by nh13** [comment]
Let’s reopen!

**Comment by pchaigno** [comment]
Ok! You'll need to add and fill in [our template for pull requests](https://github.com/github/linguist/blob/master/.github/PULL_REQUEST_TEMPLATE.md).

**Comment by nh13** [comment]
I’ll update the pr

**Comment by nh13** [comment]
@johanneskoester do you want to take this one over (in particular the checklist?)

**Comment by johanneskoester** [comment]
## Description


## Checklist:



- [x] **I am associating a language with a new file extension.**
  - [x] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      
      - https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3Asmk+snakemake
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - https://github.com/snakemake-workflows/rna-seq-kallisto-sleuth
      - https://github.com/snakemake-workflows/dna-seq-gatk-variant-calling
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am adding a new language.**
  - [ ] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  
  - [ ] I have included a syntax highlighting grammar: https://github-lightshow.herokuapp.com/
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

- [ ] **I am fixing a misclassified language**
  - [ ] I have included a new sample for the misclassified language:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am changing the source of a syntax highlighting grammar**
  
  - Old: https://github-lightshow.herokuapp.com/
  - New: https://github-lightshow.herokuapp.com/

- [ ] **I am updating a grammar submodule**
  

- [ ] **I am adding new or changing current functionality**
  
  - [ ] I have added or updated the tests for the new or changed functionality.

- [ ] **I am changing the color associated with a language**
  
  - [ ] I have obtained agreement from the wider language community on this color change.
    - [URL to public discussion]
    - [Optional: URL to official branding guidelines for the language]

**Comment by johanneskoester** [comment]
@nh13 here we go. Do you need anything else?

**Comment by pchaigno** [comment]
>  I have included a real-world usage sample for all extensions added in this PR:
    Sample source(s):
        https://github.com/snakemake-workflows/rna-seq-kallisto-sleuth
        https://github.com/snakemake-workflows/dna-seq-gatk-variant-calling

@johanneskoester @nh13 Could you add one or two files from these repositories to the pull request, under `samples/Python/`?

**Comment by johanneskoester** [comment]
@nh13 I don't think that I have access to your branch. Can you add one of the smk files from dna-seq-gatk-variant-calling?

**Comment by nh13** [comment]
Will do when I’m back from vacation in a week or so.

**Comment by nh13** [comment]
@johanneskoester added:
```
samples/Python/snakemake-calling.smk
samples/Python/snakemake-mapping.smk
```

I also added you as a collaborator :)

**Comment by johanneskoester** [comment]
Thanks a lot! I am looking forward to see this automatic highlighting Github and Atom.

**Pull request merged**
