### PR TITLE
Added Bookish Language

### PR DESCRIPTION
**Pull request by Pronner**
## Description

I added the Bookish Language (my own programming language).

## Checklist:

- [ ] **I am associating a language with a new file extension.**
  - [ ] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      
      - https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s): https://github.com/github/linguist/pull/6146
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [x] **I am adding a new language.**
  - [ ] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a syntax highlighting grammar: [URL to grammar repo]
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

- [ ] **I am fixing a misclassified language**
  - [ ] I have included a new sample for the misclassified language:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [] **I am changing the source of a syntax highlighting grammar**
  - Old: [URL to grammar repo]
  - New: [URL to grammar repo]

- [ ] **I am updating a grammar submodule**
  

- [ ] **I am adding new or changing current functionality**
  
  - [ ] I have added or updated the tests for the new or changed functionality.

- [ ] **I am changing the color associated with a language**
  
  - [ ] I have obtained agreement from the wider language community on this color change.
    - [URL to public discussion]
    - [Optional: URL to official branding guidelines for the language]

### CODE REVIEW

**Review by lildude — CHANGES_REQUESTED** [review]
Please follow the instructions in the CONTRIBUTING.md, pay special attention to usage requirements first.

**Comment by Pronner** [comment]
I'm guessing you're talking about the grammar?
I'm not sure where to put that...

**Comment by lildude** [comment]
> I'm guessing you're talking about the grammar?

No. I'm talking about the fact you've only completed step 1 of "Adding a language" and haven't filled in the template which even prompts you for the other steps needed.

But most importantly, you appear to have missed the first sentence in the "Adding a language" section... there are 7 files with the `.book` extension containing the word `bookish` and none of them look like the sample you proposed in https://github.com/github/linguist/pull/6146 (it's a terrible sample because it's a "hello world" which is rarely representative of real world usage) suggesting this is no where near ready for inclusion into Linguist. 

It's based on this that I'm going to close this PR. Please feel free to open a new PR when your language reaches the popularity requirements of this project.

**Comment by Pronner** [comment]
Well someone seems pissed at work today 💀💀

**Pull request closed without merging**
