### PR TITLE
add Limbo: language, samples

### PR DESCRIPTION
**Pull request by powerman**
I've no idea how to "Test the performance of the Bayesian classifier".
I don't know Ruby, but I've already provided PCRE for detecting at https://github.com/github/linguist/issues/2292#issuecomment-88268369 and may try to update heuristics.rb if someone tell me how to run and test it.

### CODE REVIEW

**Comment by powerman** [comment]
How exactly I'm supposed to fix conflict with Brainfuck's samples? Just copy all samples/Brainfuck/*.bf files to samples/Brainfuck/*.b?

**Comment by pchaigno** [comment]
To test your changes locally:
```
$ bundle install
$ bundle exec rake samples # trains the classifier
$ bundle exec rake # tests
```

For the `.b` Brainfuck sample, I think you can use [this file](https://github.com/windoze/brainfuck/blob/9ef0f6eef684da2fa27173f31d4622e56c83ff88/test/factor.b). It seems to be under GPL license.

**Comment by powerman** [comment]
Looks like this doesn't work:
```
$ bundle install
# To unbundle, run this file
echo install
sed 's/.//' >install <<'//GO.SYSIN DD install'
sed: can't read install: No such file or directory
//GO.SYSIN DD install
$ bundle exec rake samples
# To unbundle, run this file
echo exec
sed 's/.//' >exec <<'//GO.SYSIN DD exec'
sed: can't read exec: No such file or directory
//GO.SYSIN DD exec
echo rake
sed 's/.//' >rake <<'//GO.SYSIN DD rake'
sed: can't read rake: No such file or directory
//GO.SYSIN DD rake
echo samples
sed 's/.//' >samples <<'//GO.SYSIN DD samples'
sed: read error on samples: Is a directory
//GO.SYSIN DD samples
```

**Comment by powerman** [comment]
Added in last commit samples/Brainfuck/factor.b is “Submitted on behalf of a third-party or third parties: GitHub user windoze”.

**Comment by pchaigno** [comment]
> Looks like this doesn't work

Never seen these errors before :/
Maybe @arfon can help?

**Comment by powerman** [comment]
Ok, I've switched ruby from 1.9 to 2.0 (Gentoo provide such a feature), repeat all steps and now it works:
```
$ bundle exec rake
...
833 runs, 10233 assertions, 0 failures, 0 errors, 0 skips
```
Is this mean everything is fine and there is no needs in manually adding my regexps to heuristics.rb?

**Comment by pchaigno** [comment]
These are only the unit tests, they use the samples. Since these samples were used to train the classifier, we can be almost sure that the Bayesian classifier will recognize them correctly :/ 
To test your pull request completely you should test it against some Limbo repositories:
`bundle exec linguist ../path/to/repository --breakdown`.

**Comment by powerman** [comment]
Cool, I've checked several of my repos with Limbo code - looks like it works! :)

**Comment by arfon** [comment]
@pchaigno - adding another language with `.m` will mean that the heuristic will stop being used because of [this issue](https://github.com/github/linguist/issues/2042) right?

**Comment by pchaigno** [comment]
@arfon Ouch, you're right. Thanks! I had completely forgotten that :/

@powerman Could you add the heuristic you mentioned in #2292 for `.m` (`\w+\s*:\s*module\s*{`) at [`heuristics.rb#L187-L201`](https://github.com/github/linguist/blob/master/lib/linguist/heuristics.rb#L187-L201)?

**Comment by powerman** [comment]
Travis fails on before_install script while updating subrepos for some ruby versions and pass for others, so I suppose this RP is ok.

**Comment by arfon** [comment]
:+1: thanks @powerman. This change should be live on GitHub in the next week or so.

**Pull request merged**
