### PR TITLE
Add recognition and classification of WebAssembly

### PR DESCRIPTION
**Pull request by Alhadis**
This PR adds support for WebAssembly's textual representation on GitHub (`.wast` and `.wat`) files. Use of these files has spread substantially since the working group announced [cross-browser consensus](http://webassembly.org/roadmap/). In usual fashion, I've done what I could to collate in-the-wild examples:

* [`.wast`](https://github.com/Alhadis/Linguist-Silo/tree/wast): 4,705 files
* [`.wat`](https://github.com/Alhadis/Linguist-Silo/tree/wat) 25,812 files

The `wast` results were very promising; virtually every result was WebAssembly. The `wat` search, while offering a healthy amount of WebAssembly too, tossed up an unusual number of Makefiles and other junk related to "Watcom" (probably [Watcom C](https://en.wikipedia.org/wiki/Watcom_C/C%2B%2B0)…?) The biggest offender here are `makefile.wat` files, [which as you'll see](https://github.com/Alhadis/Linguist-Silo/tree/wat/files/Makefile), add up to nearly 800 unique variations from collated results (that's with duplicates removed).

## Licenses of example files
From **[WebAssembly/binaryen](https://github.com/WebAssembly/binaryen/)** ⇒ [Apache 2.0](https://github.com/WebAssembly/binaryen/blob/master/LICENSE)
+ [`imported-min.wast`](https://raw.githubusercontent.com/WebAssembly/binaryen/0b8acfc0139652d1c0f284c7650812a309574586/test/ctor-eval/imported-min.wast)
+ [`local-cse.wast`](https://raw.githubusercontent.com/WebAssembly/binaryen/1f1018564c472b75335bf4bddbf65cfebb226fb0/test/passes/local-cse.wast)
+ [`remove-unused-brs_shrink-level%3D1_ignore-implicit-traps.wast`](https://raw.githubusercontent.com/WebAssembly/binaryen/1f1018564c472b75335bf4bddbf65cfebb226fb0/test/passes/remove-unused-brs_shrink-level%3D1_ignore-implicit-traps.wast)

From **[bzar/wasm-intro](https://github.com/bzar/wasm-intro)** ⇒ [MIT/Expat license](https://github.com/bzar/wasm-intro/blob/master/LICENSE)
+ [`add.wat`](https://raw.githubusercontent.com/bzar/wasm-intro/d53c653b35649f9433ef5e7f5fff9da49483221b/wat/add.wat)
+ [`fibonacci.wat`](https://github.com/bzar/wasm-intro/blob/d53c653b35649f9433ef5e7f5fff9da49483221b/wat/fibonacci.wat)
+ [`print.wat`](https://raw.githubusercontent.com/bzar/wasm-intro/d53c653b35649f9433ef5e7f5fff9da49483221b/wat/print.wat)

From an **[old copy of the FreeType Project](https://github.com/aosm/X11/tree/f2829c6974ac3aacdf0c5e3f1d1c2818301cec0d/xc/extras/FreeType)** ⇒ [Unknown/Permissive license?](https://github.com/aosm/X11/blob/f2829c6974ac3aacdf0c5e3f1d1c2818301cec0d/xc/extras/FreeType/license.txt)
+ [`Makefile.wat`](https://raw.githubusercontent.com/aosm/X11/f2829c6974ac3aacdf0c5e3f1d1c2818301cec0d/xc/extras/FreeType/lib/arch/os2/Makefile.wat)

The [FreeType license](https://github.com/aosm/X11/blob/f2829c6974ac3aacdf0c5e3f1d1c2818301cec0d/xc/extras/FreeType/license.txt) has me uncertain, but it *seems* acceptable. Finding a `Makefile.wat` file that wasn't released under a copyleft or copyright license was difficult, though. What I've added might be all that we can find.

/cc @mlinksva for legal review.

### CODE REVIEW

**Comment by mlinksva** [comment]
@Alhadis the FreeType License is fine, but a copy of it does need to be retained. I don't see one in the PR.

**Comment by Alhadis** [comment]
Would you suggest I embedded it at the top or the bottom of the file? Or somewhere else altogether?

I didn't add the license as I was under the impression we limited that practice to language grammars, not fixtures.

**Comment by mlinksva** [comment]
Embedding it in a comment in the file would work, presumably on top. I looked at a few other examples here and that seemed to be the practice. In general if we have material in the repo that we're relying on a license for, the license needs to be complied with. For most licenses, that means retaining a copy of the license and any copyright notices.

**Comment by Alhadis** [comment]
Alright, thanks! License now embedded.

**Comment by Alhadis** [comment]
@lildude [This is me dealing with the merge button right now](https://www.youtube.com/watch?v=FHy8kW632dE).

**Comment by lildude** [comment]
See @Alhadis, I knew there was a reason for me to hold off approving... your last two commits would have missed the boat 😂

**Comment by pchaigno** [comment]
I'll try to resist the temptation to click before...

**Comment by Alhadis** [comment]
Sorry. Got distracted.

You can thank YouTube.

Breaking Point

**Pull request merged**
