### PR TITLE
Add support for Zil 

### PR DESCRIPTION
**Pull request by tclem**
By popular demand, adds support for Zil (both .zil and .zap extensions).

cc @nat, @textfiles, @dvdsgl

## Checklist:

- [X] **I am adding a new language.**
  - [X] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      - [`.zil`](https://github.com/search?q=extension%3Azil+NOT+nothack&type=Code)
      -  [`.zap`](https://github.com/search?q=extension%3Azap+NOT+nothack&type=Code)
  - [X] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - https://github.com/historicalsource/hitchhikersguide
      - https://github.com/historicalsource/planetfall
    - Sample license(s): Unknown
  
  - [x] I have included a syntax highlighting grammar: https://github-lightshow.herokuapp.com/
  - [ ] ~~I have updated the heuristics to distinguish my language from others using the same extension.~~ N/A, extension is unique to linguist as of writing.

cc @lildude for review/support, this is the first time I've opened a PR against linguist.

### CODE REVIEW

**Comment by dvdsgl** [comment]
Looks like we're all `SETG` and it's ready to go `GLOBAL`. You are `DEFMAC` for doing this. `.WORD`

**Comment by dcreager** [comment]
Squee!

**Comment by kivikakk** [comment]
LGTM.

**Comment by historicalsource** [comment]
Is there a way to activate this for the current source code?

**Comment by kivikakk** [comment]
@historicalsource It will take a little time to create a new version of Linguist, then deploy that within github.com; the process is underway!

**Comment by Alhadis** [comment]
Just curious, what does "ZAP" stand for? "Zork Assembly (Program?)"

**Pull request merged**
