### PR TITLE
add interpreter for hy

### PR DESCRIPTION
**Pull request by AlexFence**
I added a interpreter for hy, which is needed for shebangs to get detected.
## Description

The changes are rather simple, I also added a sample file.

I don't think that any of the checkboxes apply here, please correct me if I'm wrong, I am really unsure.
But this pull request doesn't introduce something new, it builds on what is alredy associated with hy.
## Checklist:

- [ ] **I am associating a language with a new file extension.**
  - [ ] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      
      - https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am adding a new language.**
  - [ ] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a syntax highlighting grammar.
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am fixing a misclassified language**
  - [ ] I have included a new sample for the misclassified language:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am changing the source of a syntax highlighting grammar**
  
  - Old: https://github-lightshow.herokuapp.com/
  - New: https://github-lightshow.herokuapp.com/

- [ ] **I am adding new or changing current functionality**
  
  - [ ] I have added or updated the tests for the new or changed functionality.

### CODE REVIEW

**Comment by pchaigno** [comment]
@lildude There are only [4 users](https://github.com/search?p=1&q=%22%2Fusr%2Fbin%2Fhy%22&type=Code) of this shebang. I'm not sure it's worth it...?

**Comment by AlexFence** [comment]
Please note that the hy docs even mention the ussage of shebang in their [quickstart](http://docs.hylang.org/en/stable/quickstart.html).
Also they use a different one than me, its actually around [600 peoploe](https://github.com/search?q=%22%2Fusr%2Fbin%2Fenv+hy%22&type=Code).

sorry for not stating that stuff in my initial pull request.

**Comment by pchaigno** [comment]
> Also they use a different one than me, its actually around [600 peoploe](https://github.com/search?q=%22%2Fusr%2Fbin%2Fenv+hy%22&type=Code).

Oh, right! My bad, I should have looked for the `/usr/bin/env` format.

You'll need to move the sample file to the `samples/Hy/filenames/` repository and to replace it with a more realistic one (from the search query for example, though it needs to be under a permissive license).

**Comment by pchaigno** [comment]
Oh, wait, you're right (and it's the second time I make that mistake). The sample file is in the right place, and the Travis CI build failure is unrelated to this pull request.

**Comment by AlexFence** [comment]
I hope this sample file is  okay.

I don't really know what to do about the failed test but yes, they are unrelated (maybe I should have mentioned that...).

**Comment by lildude** [comment]
The test failures appear to be caused by recent changes to licensee which has resulted in a slightly modified hash for the four licenses in question. I'll address this in #4152.

**Comment by AlexFence** [comment]
@lildude are any actions on my end needed? like pulling from master or something?

**Comment by lildude** [comment]
> @lildude are any actions on my end needed? like pulling from master or something?

Yup, you'll need to merge master into your branch to fix the failing tests for a start.

**Pull request merged**
