### PR TITLE
add support for Uno

### PR DESCRIPTION
**Pull request by kusma**
Uno is a fast, native dialect of C#, that includes a lot of
specialized functionality for graphics programming.

https://www.fusetools.com/learn/uno

### CODE REVIEW

**Comment by arfon** [comment]
Hi @kusma, thanks for opening this Pull Request. Please take a look at our [contributing guidelines](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language) for adding a new language.

**Comment by kusma** [comment]
@arfon: Are you referring to the lack of samples?

**Comment by arfon** [comment]
> @arfon: Are you referring to the lack of samples?

@kusma, yes, that and this step too please:

> Open a pull request, linking to a [GitHub search result](https://github.com/search?utf8=%E2%9C%93&q=extension%3Aboot+NOT+nothack&type=Code&ref=searchresults) showing in-the-wild usage.

**Comment by kusma** [comment]
Sure, makes sense. Sorry for omitting this the first time around.

However, it turns out, both .uno and .ux is a bit hard to link to: Some of the first pages of the search result for me goes to private repos, which will skew all page-numbers, making it very hard for me to know what other people will see. This is probably because I work at Fusetools, the company that develops the Uno language (and the UX file-format), so I see a lot of code in these that are not currently available to the general public. We're in the process of opening up our codebases, though, but in the mean-time I decided to do a bit more selective searches instead, by including only code from users that I can confirm is actually Uno and UX code:

Usage of .ux: https://github.com/search?p=1&q=extension%3Aux+user%3Afusetools+user%3AOutracks+user%3Abolav+user%3Adevmario+user%3AClidus+user%3Ayupferris+user%3Aalejandriadigital+user%3Aperhenrik+NOT+nothack&type=Code
Usage of .uno: https://github.com/search?p=1&q=extension%3Auno+user%3Afusetools+user%3AOutracks+user%3Abolav+user%3Adevmario+user%3AClidus+user%3Ayupferris+user%3Aalejandriadigital+user%3Aperhenrik+NOT+nothack&type=Code

**Comment by kusma** [comment]
@arfon: Is this better?

**Comment by arfon** [comment]
@kusma - this looks good. Thanks!

**Comment by arfon** [comment]
@kusma this will be live in the next release of Linguist (hopefully later this week if I manage to cut a new gem)

**Pull request merged**
