### PR TITLE
Replace Nix grammar

### PR DESCRIPTION
**Pull request by sambacha**
Change the submodule that linguist uses for Nix highlighting to an updated grammar syntax. Currently the one in use has issues and is not maintained.

## Description

Update to latest Nix grammar
Change submodule path, should be a drop in (hopefully).

## Checklist:

- [x] **I am changing the source of a syntax highlighting grammar**
  - Old: https://github.com/wmertens/sublime-nix
  - New: https://github.com/sambacha/nix-linguist

### CODE REVIEW

**Comment by sambacha** [comment]
```shell
~/gh-linguist# bundle exec rake test
install -c tmp/x86_64-linux-gnu/linguist/2.7.0/linguist.so lib/linguist/linguist.so
cp tmp/x86_64-linux-gnu/linguist/2.7.0/linguist.so tmp/x86_64-linux-gnu/stage/lib/linguist/linguist.so
/root/gh-linguist/vendor/gems/ruby/2.7.0/gems/charlock_holmes-0.7.7/lib/charlock_holmes/encoding_detector.rb:66: warning: instance variable encoding_list not initialized
Run options: --seed 28189

# Running:

........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

Finished in 26.240127s, 60.6704 runs/s, 1236.3507 assertions/s.

1592 runs, 32442 assertions, 0 failures, 0 errors, 0 skips

```

Let me know if anything needs to be done, thank you!

**Review by lildude — CHANGES_REQUESTED** [review]
You need to also commit the updated the cached license file. This should have been updated when you ran `script/add-grammar`. Please commit this updated file.

**Comment by sambacha** [comment]
> Looks like your grammar also has a synxtax error so fails to compile. You'd have seen this when you ran `script/add-grammar` script to replace the grammar 😉
> 
> ```
> 1 errors found in new grammar 'repository `vendor/grammars/nix-linguist` (from https://github.com/sambacha/nix-linguist.git[](https://github.com/sambacha/nix-linguist.git))':
> - Grammar conversion failed. File `nix.tmLanguage` failed to parse: XML syntax error on line 130: invalid character entity & (no semicolon)
> ```

Thank you for the feedback, much appreciated! Just pushed out the fixes, will check back when the CI is finished to see that it is 100%!

Cheers!

**Review by sambacha — COMMENTED** [review]
the fixes turned out to be easy for the grammar, just replacing `&` with `&#38;` and ensuring that I had installed ` libgit2-dev`

**Review by lildude — CHANGES_REQUESTED** [review]
Whoops. Looks like you've pulled in updates to the cached license files for other grammars. Please remove these.

And don't worry about force-pushing or merge commits; we squash all commits when merging the PR.

**Comment by sambacha** [comment]
> Whoops. Looks like you've pulled in updates to the cached license files for other grammars. Please remove these.
> 
> 
> 
> And don't worry about force-pushing or merge commits; we squash all commits when merging the PR.

Ahh, was unsure about this. Will do 🫡!

**Comment by sambacha** [comment]
Should be clean now, fixed up the dangling commit artifacts

**Review by sambacha — COMMENTED** [review]
Only Nix related changes now!

**Comment by sambacha** [comment]
closing in favor of https://github.com/github/linguist/pull/5953,  I am unable to 'address'' PR feedback as the requested changes dont appear (amended offending commit)

**Pull request closed without merging**
