### PR TITLE
Exclude obsidian.md preferences

### PR DESCRIPTION
**Pull request by sanjarcode**
Ignore `.obsidian` folder for stats, by adding it as a path exclusion.

## Description

When using https://obsidian.md/, a `.obsidian` folder is created inside the project (notes in this case) folder. It contains the plugins' source code, which of course, is not the focus of notes.

[Case - where this is happening](https://github.com/sanjar-notes/nodejs-notes/tree/b49a108cbf33207cf73dde3f9868f50bca6c061f)

## Checklist:

- [x] **I am adding new or changing current functionality**
  
  - [x] I have added or updated the tests for the new or changed functionality.

### CODE REVIEW

**Review by lildude — CHANGES_REQUESTED** [review]
Please add to the tests [here](https://github.com/github/linguist/blob/592bbedf73b35e55d55810cfb92c8e4c8fdabf56/test/test_file_blob.rb#L270).

**Comment by lildude** [comment]
> Please add to the tests [here](https://github.com/github/linguist/blob/592bbedf73b35e55d55810cfb92c8e4c8fdabf56/test/test_file_blob.rb#L270).

NM. I've done it for you 😁

**Review by lildude — APPROVED** [review]

**Comment by sanjarcode** [comment]
Thanks a lot @lildude

**Comment by lildude** [comment]
You won't see this take effect until I make and deploy the next release which I'm assuming to do in the next week or two.

**Pull request merged**
