### PR TITLE
Update master branch from upstream

### PR DESCRIPTION
**Pull request by Alhadis**

### CODE REVIEW

**Comment by Alhadis** [comment]
Shit, wrong order. Stupid GitHub.

**Comment by Alhadis** [comment]
@arfon Mind deleting this, please? I don't want to clog the repo's PR history with a brainfart.

**Comment by arfon** [comment]
@Alhadis you mean delete the PR?

**Comment by Alhadis** [comment]
Yes please. =)

**Comment by Alhadis** [comment]
I meant to merge the latest upstream changes into my fork, but... got the order wrong. *sigh*

**Comment by arfon** [comment]
For some reason the admin tools for deleting an issue aren't working properly. The PR is gone though but it's now orphaned as this issue...

**Comment by Alhadis** [comment]
Hey cool, I indirectly reported an issue with the site. :D Neat.

**Pull request closed without merging**
