### PR TITLE
Add NML Language

### PR DESCRIPTION
**Pull request by ThePNDA**
## Checklist:

- [ ] **I am associating a language with a new file extension.**
  - [ ] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      
      - https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  
  - [ ] I have included a syntax highlighting grammar: https://github-lightshow.herokuapp.com/
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

- [ ] **I am fixing a misclassified language**
  - [ ] I have included a new sample for the misclassified language:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am changing the source of a syntax highlighting grammar**
  
  - Old: https://github-lightshow.herokuapp.com/
  - New: https://github-lightshow.herokuapp.com/
  
- [ ] **I am updating a grammar submodule**
  

- [ ] **I am adding new or changing current functionality**
  
  - [ ] I have added or updated the tests for the new or changed functionality.

### CODE REVIEW

**Comment by ThePNDA** [comment]
### Hey, 
I'm new to GitHub and I'm trying to add this Language to Linguist. I've had problems with the Setup shown in "CONTRIBUTE.md". Due to that, I manually wrote this into the language.yml file, if anyone could help out to make this work, that would be great. I also haven't managed to get the samples uploaded that i wanted to include. And I have not understood how to add Syntax Highliting yet.
Some Info on this Filetype:
It gets used to make Ad-Ons to the game 'OpenTTD', so these files contain information about vehicles, cities, industries and much more. Extensions are .nml and .pnml and the standard compiler is called 'nmlc'.

I have attached a .zip containing 3 sample .pnml files and a notepad++ ,xml highlighter file, if that can help
[nml.zip](https://github.com/github/linguist/files/2430883/nml.zip)

**Comment by pchaigno** [comment]
@ThePNDA Thanks for the contribution and welcome to GitHub! We'll first need a search query showing in-the-wild usage, as per the template.

**Comment by ThePNDA** [comment]
@pchaigno Hey, im unsure if this is right, but this would be the search query: '**filename:.pnml grf**', this would show all header files, or main files for the files. 
Otherwise searching for just 'filename:.pnml' would bring some other results, though mostly only NML Language Files. Most others are Petri Net Markup Language Files, which I dont know anything about.

**Comment by pchaigno** [comment]
The correct syntax for that search query would be [`extension:pnml grf`](https://github.com/search?q=extension%3Apnml+grf). It doesn't look like NML is widespread enough though. Any other keywords we could use to extend the search query without matching other languages?

**Comment by pchaigno** [comment]
The new search query, [`extension:pnml grf OR template OR item OR switch OR replace OR FEAT`](https://github.com/search?q=extension%3Apnml+grf+OR+template+OR+item+OR+switch+OR+replace+OR+FEAT), returns only 26 repositories by 26 users, and that's including [a few XML files](https://github.com/search?p=47&q=extension%3Apnml+grf+OR+template+OR+item+OR+switch+OR+replace+OR+FEAT&type=Code).

**Comment by pchaigno** [comment]
Closing due to the low usage on GitHub.com. Let's revisit once usage is higher!

**Pull request closed without merging**
