### PR TITLE
Added syntax highlighting for ASN.1

### PR DESCRIPTION
**Pull request by ajLangley12**
https://github.com/search?utf8=✓&q=ASN.1+extension%3Aasn+extension%3Aasn1&type=Code&ref=advsearch&l=&l=

### CODE REVIEW

**Comment by Alhadis** [comment]
What the hell is ASN.1?

**Comment by ajLangley12** [comment]
https://en.wikipedia.org/wiki/Abstract_Syntax_Notation_One

It's a language used to send instructions between two different machines that don't necessarily share the same implementation language, in a really compressed format (it gets encoded into binary when sent.

**Comment by ajLangley12** [comment]
Sorry for the crappy pull request, I was having difficulties with the instruction for downloading the license.

**Comment by Alhadis** [comment]
Hrm, never heard of it, but it sounds like it's less of a language, and more of an established notation. Is that correct...? As in, it's as much of a language as ABNF grammars are...

**Comment by ajLangley12** [comment]
I believe you are correct.

**Comment by ajLangley12** [comment]
Please let me know if I need to change anything to reflect the difference in terminology.

**Comment by ajLangley12** [comment]
Looks like the travis build is hanging. Anything to do about this on my end?

**Pull request closed without merging**
