### PR TITLE
Release v5.3.1

### PR DESCRIPTION
**Pull request by kivikakk**
* Fix Perl/Pod disambiguation

/cc @Alhadis @lildude @dbussink

### CODE REVIEW

**Comment by Alhadis** [comment]
Sorry, was making my dinner.

**Comment by kivikakk** [comment]
@Alhadis not at all, this was quick! Thank you and I hope you enjoy(ed) dinner! 😺

**Comment by lildude** [comment]
@kivikakk Don't forget to update github/lightshow too. 🙇

**Comment by lildude** [comment]
Oh yes, and create a release and push the gem to rubygems. 🙇

**Comment by Alhadis** [comment]
Shouldn't that be handled automagically by a release script?

**Comment by kivikakk** [comment]
Release is pushed. TIL lightshow though!

**Comment by lildude** [comment]
> Shouldn't that be handled automagically by a release script?

Already on it. 😉

**Comment by kivikakk** [comment]
Lightshow upgraded. :+1:

**Pull request merged**
