### PR TITLE
Added imatix/GSL to the list of known languages.

### PR DESCRIPTION
**Pull request by sappo**
Here is a search query with the usage of .gsl files.

https://github.com/search?utf8=%E2%9C%93&q=extension%3Agsl+if&type=Code&ref=searchresults

A previous pull request has been made #1699.

### CODE REVIEW

**Comment by pchaigno** [comment]
Are [these files](https://github.com/search?utf8=%E2%9C%93&q=extension%3Agsl+if+set&type=Code&ref=searchresults) GSL too?

**Comment by sappo** [comment]
Not all of them, to ones from the GIANT/giant repository not.

**Comment by pchaigno** [comment]
Could you exclude those files from your original example search request?

**Comment by sappo** [comment]
@pchaigno this is a search query with the correct results though because of limitations of the github search or very well my understanding of it, it is not the entirety of files:

https://github.com/search?utf8=%E2%9C%93&q=extension%3Agsl+template+AND+if&type=Code&ref=searchresults

**Comment by arfon** [comment]
:flags: flagging this as stale :flags:

**Comment by pchaigno** [comment]
@arfon I count [552 `.gsl` GSL files](https://github.com/search?utf8=%E2%9C%93&q=extension%3Agsl+endif+OR+endfunction+or+endfor&type=Code&ref=searchresults) in 122 repositories from 90 users. However, there are also [889 `.gsl` non-GSL files](https://github.com/search?utf8=%E2%9C%93&q=extension%3Agsl+NOT+endif+OR+NOT+endfunction+OR+NOT+endfor&type=Code&ref=searchresults) which I'm unable to classify :/
What should we do?

**Comment by arfon** [comment]
> @arfon I count 552 .gsl GSL files in 122 repositories from 90 users. However, there are also 889 .gsl non-GSL files which I'm unable to classify :/
What should we do?

Given that GSL is barely at the level that we request in our [contributing guidelines](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language) and the struggle with identifying the other files I'm not sure we should proceed with this PR :-\

**Pull request closed without merging**
