### PR TITLE
Added .pck PLSQL file extension

### PR DESCRIPTION
**Pull request by jaredpetersen**
Added the .pck file extension to PLSQL. Fixes issue #2645.

In-the-wild usage of the file extension:
https://github.com/search?l=&q=create+extension%3Apck&ref=advsearch&type=Code&utf8=%E2%9C%93

### CODE REVIEW

**Comment by jaredpetersen** [comment]
The existing file extensions were not completely sorted alphabetically, which wasn't mentioned as a requirement in the contributing guidelines. I fixed the issue in my second commit. Will it be necessary for me to submit another pull request with all of the changes in a single commit?

**Comment by larsbrinkhoff** [comment]
You can rebase your pull request against Linguist's master branch.  This way, you can correct errors, merge or split commits, and add more changes as you see fit.

**Comment by jaredpetersen** [comment]
@larsbrinkhoff Thanks for your help!

**Comment by larsbrinkhoff** [comment]
You're welcome!

One thing though: The first position in `extensions` is special.  It's considered the "primary file extension".  (I'm not sure exactly what that means.)  So `.pls` should probably stay where it is.

**Comment by jaredpetersen** [comment]
Okay, made the change and rebased again! That information really should be publicly documented.

**Comment by jaredpetersen** [comment]
@larsbrinkhoff When do you think this can be reviewed and possibly merged into the repository?

**Comment by larsbrinkhoff** [comment]
@jaredpetersen Sorry, I'm not a GitHub staff member, so I don't have any say in the matter.  It looks good to me, though.

**Comment by arfon** [comment]
:+1: thanks folks. @jaredpetersen this will be live later this week when we cut a new Linguist gem.

**Comment by jaredpetersen** [comment]
Is this live yet? Linguist still isn't picking up on the language of my [PL/SQL repository](https://github.com/jaredpetersen/plsql-sample-webapp). The code is the same as the one used for the sample.

**Comment by arfon** [comment]
> Linguist still isn't picking up on the language of my PL/SQL repository. 

Linguist only updates languages when there are changes to the repo. I've just manually re-calculated the stats and they're showing up properly now.

**Comment by jaredpetersen** [comment]
> Linguist only updates languages when there are changes to the repo. I've just manually re-calculated the stats and they're showing up properly now.

Huh, interesting. That makes sense. Thanks for the help!

**Pull request merged**
