### PR TITLE
Add color for MLIR

### PR DESCRIPTION
**Pull request by jpienaar**
## Description

There is currently no color associated with MLIR, I'm changing it to match one of the colors of the logo of the MLIR project.

## Checklist:
- [x] **I am changing the color associated with a language**
  
  - [ ] I have obtained agreement from the wider language community on this color change.
    - https://www.blog.google/technology/ai/mlir-accelerating-ai-open-source-infrastructure/

### CODE REVIEW

**Comment by pchaigno** [comment]
That color is actually conflicting with MQL4's. From the Travis CI logs:
```
  1) Failure:
TestColorProximity#test_color_proximity [/home/runner/work/linguist/linguist/test/test_color_proximity.rb:21]:
The following 1 languages have failing color thresholds. Please modify the hex color.
- MQL4 (#62A8D6) is too close to ["5EA8DB", "62A8D6"]
```
Do you have other ideas of colors? If not, we could simply add it to #4506.

**Comment by jpienaar** [comment]
> That color is actually conflicting with MQL4's. From the Travis CI logs:
> 
> ```
>   1) Failure:
> TestColorProximity#test_color_proximity [/home/runner/work/linguist/linguist/test/test_color_proximity.rb:21]:
> The following 1 languages have failing color thresholds. Please modify the hex color.
> - MQL4 (#62A8D6) is too close to ["5EA8DB", "62A8D6"]
> ```
> 
> Do you have other ideas of colors? If not, we could simply add it to #4506.

The other colors used are #3775E0 (which is too close to MQL5[1] and Slash), #1B466C (I'm not sure I get `MLIR (#1B466C) is too close to ["244776", "1B466C"]`) and white (which may not work well on white background of GitHub). 

Is the closeness a problem if these two languages will rarely (ever?) end up in same repo? I can't dismiss the possibility though. But that may be irrelevant for current policy.

[1] Why does MQL4 and MQL5 have different colors? Given they are using the same tm_scope and  same grammar (but different file extensions) it seem unfortunate given the color different requirement. Esp. given different versions of Python or C++ do not have this difference. If MQL4 shared the same color as MQL5 then it would resolve the conflict on the current suggestion. But this is probably an aside.

**Comment by lildude** [comment]
> Is the closeness a problem if these two languages will rarely (ever?) end up in same repo?

Unfortunately, yes. I'm still waiting on the GitHub design team to get back to me about dropping this proximity enforcement. I prod the issue now and then but it's not really high on their priority list. Until we get the clearance, we're going to have to keep this enforcement in place. 

Whilst you won't be able to get the exact colours used by the language repo, a little tweaking should get you close.

**Comment by lildude** [comment]
I just did a quick test and `#5EC8DB` passes and isn't too far off `#5EA8DB`. You could experiment a bit more to possibly get closer if you want. Unfortunately, blue is really popular so there will almost always need to be a compromise or a lot of testing.

**Comment by jpienaar** [comment]
> I just did a quick test and `#5EC8DB` passes and isn't too far off `#5EA8DB`. You could experiment a bit more to possibly get closer if you want. Unfortunately, blue is really popular so there will almost always need to be a compromise or a lot of testing.

Yes I can imagine, thanks! I'm good with this suggestion.

> > Is the closeness a problem if these two languages will rarely (ever?) end up in same repo?
> 
> Unfortunately, yes. I'm still waiting on the GitHub design team to get back to me about dropping this proximity enforcement. I prod the issue now and then but it's not really high on their priority list. Until we get the clearance, we're going to have to keep this enforcement in place.

SG, that makes sense. I started typing a longer discussion about different approaches, but figured this would be the wrong spot for that :) Is there perhaps a bug I could follow along for this request? This would be for my own curiosity really as I'm happy enough with a distinct color.

**Comment by lildude** [comment]
> Is there perhaps a bug I could follow along for this request?

Unfortunately, not. All GitHub issues are currently on the private repo so not open to the public.

**Pull request merged**
