### PR TITLE
Better PAWN language detection

### PR DESCRIPTION
**Pull request by eider-i128**
Some PAWN language files are wrongly detected as OpenEdge ABL. This commit fixes it.

### CODE REVIEW

**Comment by pchaigno** [comment]
Is there a keyword or keywords that could be used to search for PAWN files on GitHub? (To see how many there are for each extension, as per [the contribution guidelines](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#i-want-to-add-support-for-the-x-programming-language).)

**Comment by eider-i128** [comment]
I think you can search it by "sa-mp" but you'll have to filter plugins etc. Please note that PAWN language was already supported by Linguist, this commit just improves it.

**Comment by pchaigno** [comment]
The requirement that a language must have some usage on GitHub before it's added is also used for extensions generally. Though it's more of an indication.

I was able to find [many `.inc` PAWN files](https://github.com/search?utf8=%E2%9C%93&q=extension%3Ainc+sa-mp&type=Code&ref=searchresults) with your indication but [only 2 for `.p`](https://github.com/search?utf8=%E2%9C%93&q=extension%3Ap+sa-mp&type=Code&ref=searchresults). Should I use another keyword for `.p`?

**Comment by eider-i128** [comment]
It's not common to use .p extension in SA-MP community, but as you can see from this official screen from CompuPhase - .p is default extension for PAWN files - http://www.compuphase.com/pawn/quincy.png

More informatiosn available here: http://www.compuphase.com/pawn/pawn.htm

**Comment by bkeepers** [comment]
Since there isn't a lot of usage with `.p`, and `.inc` is such a common extension, I'm :-1: on adding these extensions right now.  We can definitely reconsider in the future.

**Pull request closed without merging**
