### PR TITLE
Linguist colors webpage overhaul

### PR DESCRIPTION
**Pull request by MihajloNesic**
## Description
This PR overhauls the Linguist colors webpage. 
It adds more information about each language (like 'type' and 'color hex' and can be further extended) and a search bar.

It's using Bootstrap v4.5.2 that has been stored in `vendor` folder.

## Checklist:
No checklist about this 'feature'

### CODE REVIEW

**Comment by MihajloNesic** [comment]
I've added a feature where, if you click on the language card, the modal opens containing a list of the language extensions.

**Comment by MihajloNesic** [comment]
> 
> 
> This pull request has been automatically marked as stale because it has not had recent activity, and will be closed if no further activity occurs. If this pull request was overlooked, forgotten, or should remain open for any other reason, please reply here to call attention to it and remove the stale status. Thank you for your contributions.

I mean it's not an important PR, but it looks cool :)

**Comment by lildude** [comment]
Sorry about the delay @MihajloNesic. 

I didn't even know we had a Pages site for this repo and thinking about it, I don't think we need it any more. I believe it was created as a quick fix (the one and only commit on the branch even suggests this is a hack) when we had restrictions on which colours could be used, but these have been removed so a language can use any colour thus removing the need to see what colours are currently already taken.

I'll disable the Pages site later today.

**Comment by MihajloNesic** [comment]
Thank you for the response

**Pull request closed without merging**
