### PR TITLE
.qbs extension for QML.

### PR DESCRIPTION
**Pull request by jakepetroules**
[Qt build suite](http://doc.qt.io/qbs) (Qbs) is the [Qt Project](http://www.qt.io)'s new build system to eventually replace qmake. Qbs' project files are [written in QML using the .qbs extension](http://doc.qt.io/qbs/language-introduction.html).

Search results: https://github.com/search?utf8=✓&q=extension%3Aqbs+NOT+nothack&type=Code&ref=searchresults

Source: I am one of the core [Qbs developers](https://github.com/qtproject/qt-labs-qbs/graphs/contributors).

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
I estimate there are more than 600 repositories with `.qbs` files. :+1:

**Comment by jakepetroules** [comment]
Having .qbs first in the list makes it the primary file extension. I'm guessing .qml should be the primary extension.

> Absolutely. Let me fix that.

**Comment by jakepetroules** [comment]
Done!

**Comment by larsbrinkhoff** [comment]
You should also add a `.qbs` sample file to `samples/QML`.

I'm not a member of GitHub staff, so I can't approve the pull request myself.

**Comment by pchaigno** [comment]
@jakepetroules Thanks for the PR! It's better if the sample comes from a real application. It will be used to train the Bayesian classifier ;)
Also, I think you pushed the `main.cpp` file by mistake :-)

**Comment by jakepetroules** [comment]
Alright, I've switched out the sample for a real module file from qbs' own source code.

**Comment by pchaigno** [comment]
Looks good :+1: 
You just have to wait for someone from GitHub to review it now ;)

**Comment by jakepetroules** [comment]
@arfon merge please?

**Comment by arfon** [comment]
:+1: looks good. Thanks @jakepetroules. This will be live when we cut a new Linguist gem (probably next week sometime)

**Comment by jakepetroules** [comment]
Awesome, thanks! Looking forward to seeing it in action.

**Pull request merged**
