### PR TITLE
Add Clarity support

### PR DESCRIPTION
**Pull request by agraebe**
Adding support for the [Clarity Smart Contract language](https://clarity-lang.org/)

## Checklist:
- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - [Search results for `.clar` extension](https://github.com/search?utf8=%E2%9C%93&q=extension%3Aclar+NOT+nothack&type=Code&ref=searchresults)
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [Proof of Transfer consensus mechanism](https://github.com/blockstack/stacks-blockchain/blob/master/src/chainstate/stacks/boot/pox.clar)
      - [Bitcoin Naming Service](https://github.com/blockstack/stacks-blockchain/blob/master/src/chainstate/stacks/boot/bns.clar)
      - [Cost voting mechanism](https://github.com/blockstack/stacks-blockchain/blob/master/src/chainstate/stacks/boot/cost-voting.clar)
    - Sample license(s): GPL-3.0 (all)
  - [x] I have included a [syntax highlighting grammar](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=xml&grammar_url=https%3A%2F%2Fgithub.com%2Fhirosystems%2Fclarity.tmbundle%2Fblob%2Fmain%2FSyntaxes%2Fclarity.tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fblockstack%2Fstacks-blockchain%2Fmaster%2Fsrc%2Fchainstate%2Fstacks%2Fboot%2Fpox.clar&code=)
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

### CODE REVIEW

**Comment by lildude** [comment]
Usage isn't quite there yet:

Total files found: 1315
Unique public user/repos: 170
Unique owners: 117

**Comment by Alhadis** [comment]
> Unique public user/repos

I realised earlier that saying "unique user/repos" is redundant, since a repository can't logically be owned by more than one user. Perhaps we can simplify our docs by counting users only?

**Review by lildude — CHANGES_REQUESTED** [review]
Please address the test failure

**Comment by lildude** [comment]
> I realised earlier that saying "unique user/repos" is redundant, since a repository can't logically be owned by more than one user. Perhaps we can simplify our docs by counting users only?

I've been using this to allow for a bit more flexibility as it allows users to have multiple repos, with the added unique users hinting at if there's a few users disproportionately contributing to the total repos.

**Comment by agraebe** [comment]
> Usage isn't quite there yet:
> 
> Total files found: 1315 Unique public user/repos: 170 Unique owners: 117

Thanks for sharing! Is there a way to run this analysis on my end? I tried Harvester but hitting this issue: https://github.com/Alhadis/Harvester/issues/17#issuecomment-964500628

**Comment by agraebe** [comment]
@lildude could you please run the analysis again? and if you could help me with guidance on how to run it on my own, that'd be great.

thanks!

**Comment by lgalabru** [comment]
@lildude in parallel, we're also working on updating the Clarity LSP (https://github.com/hirosystems/clarity-lsp), to make it compatible with https://github.dev, and being on linguist would already be a great addition!
Any change you could give us the new numbers? Thank you so much for your help.

**Comment by lildude** [comment]
I'm not performing reviews of PRs or popularity checking until I've got the time to start working on the next release (likely to be in early Feb at the earliest).

**Comment by jdbender66** [comment]
Any update on the total count of Clarity :user/:repo? We had a lot of activity over the holidays and think we should be past the 200 threshold needed for inclusion in Linguist.

**Review by lildude — APPROVED** [review]
Approving this based on the temporary requirements detailed in https://github.com/github/linguist/issues/5756

**Review by lildude — CHANGES_REQUESTED** [review]
Whoops, looks like we've got CI failures that need addressing first.

**Comment by lildude** [comment]
> Whoops, looks like we've got CI failures that need addressing first.

Fixed it.

**Pull request merged**
