### PR TITLE
go: do not treat go.{mod,sum} modules files as generated

### PR DESCRIPTION
**Pull request by myitcv**
As a follow up to https://github.com/github/linguist/pull/4306#issuecomment-439986476, `go.{mod,sum}` modules files should not be treated as generated.

## Description

Per above.

## Checklist:

- [ ] **I am associating a language with a new file extension.**
  - [ ] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      
      - https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am adding a new language.**
  - [ ] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  
  - [ ] I have included a syntax highlighting grammar: https://github-lightshow.herokuapp.com/
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

- [x] **I am fixing a misclassified language**
  - [ ] I have included a new sample for the misclassified language:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am changing the source of a syntax highlighting grammar**
  
  - Old: https://github-lightshow.herokuapp.com/
  - New: https://github-lightshow.herokuapp.com/
  
- [ ] **I am updating a grammar submodule**
  

- [ ] **I am adding new or changing current functionality**
  
  - [ ] I have added or updated the tests for the new or changed functionality.

### CODE REVIEW

**Comment by myitcv** [comment]
@pchaigno I'll leave it to to you/one of the repo owners to do the revert. I only pushed up this PR in case you want to make a minimal change instead of reverting.

**Comment by myitcv** [comment]
The revert PR with links etc can be automatically generated from the old PR by someone with the right access. I don't have that option

**Comment by pchaigno** [comment]
I meant the [git revert command](https://git-scm.com/docs/git-revert), after which you can push to a pull request.

**Comment by myitcv** [comment]
Yes that's an option, but by far the easiest option is to auto-generate the revert PR from GitHub. On the assumption that's what's going to be most likely chosen here I'll close this PR

**Pull request closed without merging**
