### PR TITLE
Update tokenizer to flex 2.6.4

### PR DESCRIPTION
**Pull request by smola**
## Description

Re-generate tokenizer with flex 2.6.4 (current version on Ubuntu 20.04 and Homebrew).

This is just for mainteinance, to make smaller diffs for further tokenizer changes.

## Checklist:

_Checklist does not apply._

### CODE REVIEW

**Comment by lildude** [comment]
I have absolutely no idea what any of this means, but I can confirm it produces an identical `samples.json` file, so I'm happy with this. 😬 

I'm not sure if @Alhadis or @pchaigno have any more experience.

**Comment by smola** [comment]
Some more background:

` ext/linguist/lex.linguist_yy.{c,h}` are generated from `ext/linguist/tokenizer.l` using flex (by the way, you can use `rake flex`). Last time it was generated it was using flex 2.5.35, which is quite old now and not generally available in recent Ubuntu or macOS (Homebrew) versions.

I realized about this when trying to improve the tokenizer, and all changes I tried were generating these extra changes from the flex update. The change should be inocuous (or, apparently, maybe fixing some issues in non-amd64 arches). But I thought it would be better to create a separate PR for this initially. In the (unlikely) event that a bug is introduced by the flex update itself and not by some tokenizer change, we'll be grateful to find it's an independent commit that can be found with git bisect ;-)

**Comment by Alhadis** [comment]
After checking your branch out locally and recompiling, I see new warnings when running `bundle exec rake test`:

<details><summary>Show output</summary>

~~~diff
 install -c tmp/x86_64-openbsd/linguist/2.6.6/linguist.so lib/linguist/linguist.so
 cp tmp/x86_64-openbsd/linguist/2.6.6/linguist.so tmp/x86_64-openbsd/stage/lib/linguist/linguist.so
 /usr/local/lib/ruby/gems/2.6/gems/charlock_holmes-0.7.7/lib/charlock_holmes/encoding_detector.rb:66: warning: instance variable encoding_list not initialized
 msyscall db266b17000 a5000 error
+/usr/local/lib/ruby/2.6/forwardable/impl.rb:3: warning: method redefined; discarding old _valid_method?
+/usr/local/lib/ruby/gems/2.6/gems/forwardable-1.3.1/lib/forwardable/impl.rb:3: warning: previous definition of _valid_method? was here
+/usr/local/lib/ruby/2.6/forwardable/impl.rb:11: warning: method redefined; discarding old _compile_method
+/usr/local/lib/ruby/gems/2.6/gems/forwardable-1.3.1/lib/forwardable/impl.rb:13: warning: previous definition of _compile_method was here
+/usr/local/lib/ruby/2.6/forwardable.rb:116: warning: already initialized constant Forwardable::VERSION
+/usr/local/lib/ruby/gems/2.6/gems/forwardable-1.3.1/lib/forwardable/version.rb:3: warning: previous definition of VERSION was here
+/usr/local/lib/ruby/2.6/forwardable.rb:117: warning: already initialized constant Forwardable::FORWARDABLE_VERSION
+/usr/local/lib/ruby/gems/2.6/gems/forwardable-1.3.1/lib/forwardable/version.rb:4: warning: previous definition of FORWARDABLE_VERSION was here
+/usr/local/lib/ruby/2.6/forwardable.rb:122: warning: method redefined; discarding old debug
+/usr/local/lib/ruby/2.6/forwardable.rb:122: warning: method redefined; discarding old debug=
+/usr/local/lib/ruby/2.6/forwardable.rb:193: warning: method redefined; discarding old _delegator_method
+/usr/local/lib/ruby/gems/2.6/gems/forwardable-1.3.1/lib/forwardable.rb:198: warning: previous definition of _delegator_method was here
 Run options: --seed 11628

 # Running:

 ...............................................................................................................................................................................msyscall 9cf722df000 a5000 error
 ................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

 Finished in 105.667149s, 13.0126 runs/s, 264.4720 assertions/s.

 1375 runs, 27946 assertions, 0 failures, 0 errors, 0 skips
~~~

</details>

I had to run `bundle install` before I could regenerate the samples database, so it's possible the warnings aren't related. (The `msyscall db266b17000 a5000 error` certainly isn't; though it looks worrying, I haven't observed any difference in Linguist's functionality since I started seeing it a few months ago).

- **Platform:** OpenBSD 6.8-beta (snapshot #&#xFEFF;55)
- **Program versions:**
    - **Bundler:** 1.17.2
    - **Flex:** 2.5.39
    - **Ruby:** 2.6.6p146 (2020-03-31 revision 67876) [x86_64-openbsd]
    - **RubyGems:** 3.0.3

**Comment by smola** [comment]
@Alhadis I'll look into it. Did you check if these warnings appear on master when doing a clean build?

**Comment by smola** [comment]
@Alhadis Did you have a chance to verify if these warnings appear on a clean build from master?

I cannot reproduce this on OpenBSD. I get one warning from charlock_holmes (both in master and this branch): `/home/vagrant/linguist/vendor/ruby/2.6/gems/charlock_holmes-0.7.7/lib/charlock_holmes/encoding_detector.rb:66: warning: instance variable encoding_list not initialized`.

But I'm not getting all these `forwardable.rb` warnings.

I tried with:
* `OpenBSD 6.8 (GENERIC.MP) #98` (clean install with [this vagrant box](https://app.vagrantup.com/berdav/boxes/openbsd6.8))
* `ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-openbsd]`

**Comment by Alhadis** [comment]
Just did a fresh install/build of Linguist from your branch. Still getting noise:
 
<details>
 
```diff
 mkdir -p tmp/x86_64-openbsd/linguist/2.6.6
 cd tmp/x86_64-openbsd/linguist/2.6.6
 /usr/local/bin/ruby26 -I. ../../../../ext/linguist/extconf.rb
 creating Makefile
 cd -
 cd tmp/x86_64-openbsd/linguist/2.6.6
 /usr/local/bin/gmake
 compiling ../../../../ext/linguist/lex.linguist_yy.c
 compiling ../../../../ext/linguist/linguist.c
 compiling ../../../../ext/linguist/strndup.c
 linking shared-object linguist/linguist.so
 cd -
 mkdir -p tmp/x86_64-openbsd/stage/lib/linguist
 cp LICENSE tmp/x86_64-openbsd/stage/LICENSE
 mkdir -p tmp/x86_64-openbsd/stage/bin
 cp bin/git-linguist tmp/x86_64-openbsd/stage/bin/git-linguist
 cp bin/github-linguist tmp/x86_64-openbsd/stage/bin/github-linguist
 mkdir -p tmp/x86_64-openbsd/stage/ext/linguist
 cp ext/linguist/extconf.rb tmp/x86_64-openbsd/stage/ext/linguist/extconf.rb
 cp ext/linguist/lex.linguist_yy.c tmp/x86_64-openbsd/stage/ext/linguist/lex.linguist_yy.c
 cp ext/linguist/lex.linguist_yy.h tmp/x86_64-openbsd/stage/ext/linguist/lex.linguist_yy.h
 cp ext/linguist/linguist.c tmp/x86_64-openbsd/stage/ext/linguist/linguist.c
 cp ext/linguist/linguist.h tmp/x86_64-openbsd/stage/ext/linguist/linguist.h
 cp ext/linguist/strndup.c tmp/x86_64-openbsd/stage/ext/linguist/strndup.c
 cp ext/linguist/tokenizer.l tmp/x86_64-openbsd/stage/ext/linguist/tokenizer.l
 cp lib/linguist.rb tmp/x86_64-openbsd/stage/lib/linguist.rb
 cp lib/linguist/VERSION tmp/x86_64-openbsd/stage/lib/linguist/VERSION
 cp lib/linguist/blob.rb tmp/x86_64-openbsd/stage/lib/linguist/blob.rb
 cp lib/linguist/blob_helper.rb tmp/x86_64-openbsd/stage/lib/linguist/blob_helper.rb
 cp lib/linguist/classifier.rb tmp/x86_64-openbsd/stage/lib/linguist/classifier.rb
 cp lib/linguist/documentation.yml tmp/x86_64-openbsd/stage/lib/linguist/documentation.yml
 cp lib/linguist/file_blob.rb tmp/x86_64-openbsd/stage/lib/linguist/file_blob.rb
 cp lib/linguist/generated.rb tmp/x86_64-openbsd/stage/lib/linguist/generated.rb
 cp lib/linguist/grammars.rb tmp/x86_64-openbsd/stage/lib/linguist/grammars.rb
 cp lib/linguist/heuristics.rb tmp/x86_64-openbsd/stage/lib/linguist/heuristics.rb
 cp lib/linguist/heuristics.yml tmp/x86_64-openbsd/stage/lib/linguist/heuristics.yml
 cp lib/linguist/language.rb tmp/x86_64-openbsd/stage/lib/linguist/language.rb
 cp lib/linguist/languages.yml tmp/x86_64-openbsd/stage/lib/linguist/languages.yml
 cp lib/linguist/lazy_blob.rb tmp/x86_64-openbsd/stage/lib/linguist/lazy_blob.rb
 cp lib/linguist/popular.yml tmp/x86_64-openbsd/stage/lib/linguist/popular.yml
 cp lib/linguist/repository.rb tmp/x86_64-openbsd/stage/lib/linguist/repository.rb
 cp lib/linguist/samples.json tmp/x86_64-openbsd/stage/lib/linguist/samples.json
 cp lib/linguist/samples.rb tmp/x86_64-openbsd/stage/lib/linguist/samples.rb
 cp lib/linguist/sha256.rb tmp/x86_64-openbsd/stage/lib/linguist/sha256.rb
 cp lib/linguist/shebang.rb tmp/x86_64-openbsd/stage/lib/linguist/shebang.rb
 mkdir -p tmp/x86_64-openbsd/stage/lib/linguist/strategy
 cp lib/linguist/strategy/extension.rb tmp/x86_64-openbsd/stage/lib/linguist/strategy/extension.rb
 cp lib/linguist/strategy/filename.rb tmp/x86_64-openbsd/stage/lib/linguist/strategy/filename.rb
 cp lib/linguist/strategy/manpage.rb tmp/x86_64-openbsd/stage/lib/linguist/strategy/manpage.rb
 cp lib/linguist/strategy/modeline.rb tmp/x86_64-openbsd/stage/lib/linguist/strategy/modeline.rb
 cp lib/linguist/strategy/xml.rb tmp/x86_64-openbsd/stage/lib/linguist/strategy/xml.rb
 cp lib/linguist/tokenizer.rb tmp/x86_64-openbsd/stage/lib/linguist/tokenizer.rb
 cp lib/linguist/vendor.yml tmp/x86_64-openbsd/stage/lib/linguist/vendor.yml
 cp lib/linguist/version.rb tmp/x86_64-openbsd/stage/lib/linguist/version.rb
 install -c tmp/x86_64-openbsd/linguist/2.6.6/linguist.so lib/linguist/linguist.so
 cp tmp/x86_64-openbsd/linguist/2.6.6/linguist.so tmp/x86_64-openbsd/stage/lib/linguist/linguist.so
 /usr/local/lib/ruby/gems/2.6/gems/charlock_holmes-0.7.7/lib/charlock_holmes/encoding_detector.rb:66: warning: instance variable encoding_list not initialized
+msyscall 26140c7d000 a5000 error
+/usr/local/lib/ruby/2.6/forwardable/impl.rb:3: warning: method redefined; discarding old _valid_method?
+/usr/local/lib/ruby/gems/2.6/gems/forwardable-1.3.1/lib/forwardable/impl.rb:3: warning: previous definition of _valid_method? was here
+/usr/local/lib/ruby/2.6/forwardable/impl.rb:11: warning: method redefined; discarding old _compile_method
+/usr/local/lib/ruby/gems/2.6/gems/forwardable-1.3.1/lib/forwardable/impl.rb:13: warning: previous definition of _compile_method was here
+/usr/local/lib/ruby/2.6/forwardable.rb:116: warning: already initialized constant Forwardable::VERSION
+/usr/local/lib/ruby/gems/2.6/gems/forwardable-1.3.1/lib/forwardable/version.rb:3: warning: previous definition of VERSION was here
+/usr/local/lib/ruby/2.6/forwardable.rb:117: warning: already initialized constant Forwardable::FORWARDABLE_VERSION
+/usr/local/lib/ruby/gems/2.6/gems/forwardable-1.3.1/lib/forwardable/version.rb:4: warning: previous definition of FORWARDABLE_VERSION was here
+/usr/local/lib/ruby/2.6/forwardable.rb:122: warning: method redefined; discarding old debug
+/usr/local/lib/ruby/2.6/forwardable.rb:122: warning: method redefined; discarding old debug=
+/usr/local/lib/ruby/2.6/forwardable.rb:193: warning: method redefined; discarding old _delegator_method
+/usr/local/lib/ruby/gems/2.6/gems/forwardable-1.3.1/lib/forwardable.rb:198: warning: previous definition of _delegator_method was here
 Run options: --seed 459
 
 # Running:
 
 ......................................................................................................................................................msyscall 6595dc24000 a5000 error
 ...........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
 
 Finished in 250.319989s, 5.5010 runs/s, 112.1884 assertions/s.
 
 1377 runs, 28083 assertions, 0 failures, 0 errors, 0 skips
```
 
</details>

**Comment by smola** [comment]
@Alhadis It looks like a problem with your environment. I don't even have a `forwardable` gem installed. Installing it doesn't produce any warning either. Looking at the log, it looks like somehow conflicting versions are loaded? Does this happen on a clean build from github/linguist's master (not this branch)? I have a hard time wrapping my head around how this change could introduce these warnings.

**Comment by Alhadis** [comment]
Okay, that's weird. It works if I wipe `./vendor/gems` and rebuild...  but if I delete every other artefact, I get the aforementioned errors. Here're the commands I ran in order:

<details>
<summary>
<b>1. No untracked files in working directory, including <code>vendor/gems</code></b>

~~~sh
$ (script/bootstrap; brake samples test 2>&1) | tee /tmp/1.log

# Click to show output
~~~

</summary>

```
You are replacing the current local value of path, which is currently nil
Fetching gem metadata from https://rubygems.org/.......
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies.....
Fetching rake 13.0.1
Installing rake 13.0.1
Fetching public_suffix 4.0.6
Installing public_suffix 4.0.6
Fetching addressable 2.7.0
Installing addressable 2.7.0
Using bundler 1.17.2
Fetching byebug 11.1.3
Installing byebug 11.1.3 with native extensions
Fetching charlock_holmes 0.7.7
Installing charlock_holmes 0.7.7 with native extensions
Fetching coderay 1.1.3
Installing coderay 1.1.3
Fetching dotenv 2.7.6
Installing dotenv 2.7.6
Fetching escape_utils 1.2.1
Installing escape_utils 1.2.1 with native extensions
Fetching multipart-post 2.1.1
Installing multipart-post 2.1.1
Fetching ruby2_keywords 0.0.2
Installing ruby2_keywords 0.0.2
Fetching faraday 1.1.0
Installing faraday 1.1.0
Fetching mini_mime 1.0.2
Installing mini_mime 1.0.2
Fetching rugged 1.1.0
Installing rugged 1.1.0 with native extensions
Using github-linguist 7.11.1 from source at `.`
Fetching sawyer 0.8.2
Installing sawyer 0.8.2
Fetching octokit 4.19.0
Installing octokit 4.19.0
Fetching mini_portile2 2.4.0
Installing mini_portile2 2.4.0
Fetching nokogiri 1.10.10
Installing nokogiri 1.10.10 with native extensions
Fetching reverse_markdown 1.4.0
Installing reverse_markdown 1.4.0
Fetching thor 1.0.1
Installing thor 1.0.1
Fetching licensee 9.14.1
Installing licensee 9.14.1
Fetching parallel 1.19.2
Installing parallel 1.19.2
Fetching pathname-common_prefix 0.0.1
Installing pathname-common_prefix 0.0.1
Fetching ruby-xxHash 0.4.0.1
Installing ruby-xxHash 0.4.0.1
Fetching tomlrb 1.3.0
Installing tomlrb 1.3.0
Fetching licensed 2.14.1
Installing licensed 2.14.1
Fetching method_source 1.0.0
Installing method_source 1.0.0
Fetching minitest 5.14.2
Installing minitest 5.14.2
Fetching mocha 1.11.2
Installing mocha 1.11.2
Fetching plist 3.5.0
Installing plist 3.5.0
Fetching pry 0.13.1
Installing pry 0.13.1
Fetching rake-compiler 0.9.9
Installing rake-compiler 0.9.9
Fetching yajl-ruby 1.4.1
Installing yajl-ruby 1.4.1 with native extensions
Bundle complete! 12 Gemfile dependencies, 34 gems now installed.
Bundled gems are installed into `./vendor/gems`
mkdir -p tmp/x86_64-openbsd/linguist/2.6.6
cd tmp/x86_64-openbsd/linguist/2.6.6
/usr/local/bin/ruby26 -I. ../../../../ext/linguist/extconf.rb
creating Makefile
cd -
cd tmp/x86_64-openbsd/linguist/2.6.6
/usr/local/bin/gmake
compiling ../../../../ext/linguist/lex.linguist_yy.c
compiling ../../../../ext/linguist/linguist.c
compiling ../../../../ext/linguist/strndup.c
linking shared-object linguist/linguist.so
cd -
mkdir -p tmp/x86_64-openbsd/stage/lib/linguist
cp LICENSE tmp/x86_64-openbsd/stage/LICENSE
mkdir -p tmp/x86_64-openbsd/stage/bin
cp bin/git-linguist tmp/x86_64-openbsd/stage/bin/git-linguist
cp bin/github-linguist tmp/x86_64-openbsd/stage/bin/github-linguist
mkdir -p tmp/x86_64-openbsd/stage/ext/linguist
cp ext/linguist/extconf.rb tmp/x86_64-openbsd/stage/ext/linguist/extconf.rb
cp ext/linguist/lex.linguist_yy.c tmp/x86_64-openbsd/stage/ext/linguist/lex.linguist_yy.c
cp ext/linguist/lex.linguist_yy.h tmp/x86_64-openbsd/stage/ext/linguist/lex.linguist_yy.h
cp ext/linguist/linguist.c tmp/x86_64-openbsd/stage/ext/linguist/linguist.c
cp ext/linguist/linguist.h tmp/x86_64-openbsd/stage/ext/linguist/linguist.h
cp ext/linguist/strndup.c tmp/x86_64-openbsd/stage/ext/linguist/strndup.c
cp ext/linguist/tokenizer.l tmp/x86_64-openbsd/stage/ext/linguist/tokenizer.l
cp lib/linguist.rb tmp/x86_64-openbsd/stage/lib/linguist.rb
cp lib/linguist/VERSION tmp/x86_64-openbsd/stage/lib/linguist/VERSION
cp lib/linguist/blob.rb tmp/x86_64-openbsd/stage/lib/linguist/blob.rb
cp lib/linguist/blob_helper.rb tmp/x86_64-openbsd/stage/lib/linguist/blob_helper.rb
cp lib/linguist/classifier.rb tmp/x86_64-openbsd/stage/lib/linguist/classifier.rb
cp lib/linguist/documentation.yml tmp/x86_64-openbsd/stage/lib/linguist/documentation.yml
cp lib/linguist/file_blob.rb tmp/x86_64-openbsd/stage/lib/linguist/file_blob.rb
cp lib/linguist/generated.rb tmp/x86_64-openbsd/stage/lib/linguist/generated.rb
cp lib/linguist/grammars.rb tmp/x86_64-openbsd/stage/lib/linguist/grammars.rb
cp lib/linguist/heuristics.rb tmp/x86_64-openbsd/stage/lib/linguist/heuristics.rb
cp lib/linguist/heuristics.yml tmp/x86_64-openbsd/stage/lib/linguist/heuristics.yml
cp lib/linguist/language.rb tmp/x86_64-openbsd/stage/lib/linguist/language.rb
cp lib/linguist/languages.yml tmp/x86_64-openbsd/stage/lib/linguist/languages.yml
cp lib/linguist/lazy_blob.rb tmp/x86_64-openbsd/stage/lib/linguist/lazy_blob.rb
cp lib/linguist/popular.yml tmp/x86_64-openbsd/stage/lib/linguist/popular.yml
cp lib/linguist/repository.rb tmp/x86_64-openbsd/stage/lib/linguist/repository.rb
cp lib/linguist/samples.rb tmp/x86_64-openbsd/stage/lib/linguist/samples.rb
cp lib/linguist/sha256.rb tmp/x86_64-openbsd/stage/lib/linguist/sha256.rb
cp lib/linguist/shebang.rb tmp/x86_64-openbsd/stage/lib/linguist/shebang.rb
mkdir -p tmp/x86_64-openbsd/stage/lib/linguist/strategy
cp lib/linguist/strategy/extension.rb tmp/x86_64-openbsd/stage/lib/linguist/strategy/extension.rb
cp lib/linguist/strategy/filename.rb tmp/x86_64-openbsd/stage/lib/linguist/strategy/filename.rb
cp lib/linguist/strategy/manpage.rb tmp/x86_64-openbsd/stage/lib/linguist/strategy/manpage.rb
cp lib/linguist/strategy/modeline.rb tmp/x86_64-openbsd/stage/lib/linguist/strategy/modeline.rb
cp lib/linguist/strategy/xml.rb tmp/x86_64-openbsd/stage/lib/linguist/strategy/xml.rb
cp lib/linguist/tokenizer.rb tmp/x86_64-openbsd/stage/lib/linguist/tokenizer.rb
cp lib/linguist/vendor.yml tmp/x86_64-openbsd/stage/lib/linguist/vendor.yml
cp lib/linguist/version.rb tmp/x86_64-openbsd/stage/lib/linguist/version.rb
install -c tmp/x86_64-openbsd/linguist/2.6.6/linguist.so lib/linguist/linguist.so
cp tmp/x86_64-openbsd/linguist/2.6.6/linguist.so tmp/x86_64-openbsd/stage/lib/linguist/linguist.so
/home/Alhadis/Forks/linguist/vendor/gems/ruby/2.6/gems/charlock_holmes-0.7.7/lib/charlock_holmes/encoding_detector.rb:66: warning: instance variable encoding_list not initialized
Run options: --seed 36358

# Running:

.................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

Finished in 251.260928s, 5.4804 runs/s, 111.7683 assertions/s.

1377 runs, 28083 assertions, 0 failures, 0 errors, 0 skips
```

</details>

<details>
<summary>
<b>2. When I wipe every artefact <em>except</em> <code>vendor/gems</code></b>

~~~sh
$ (rm -rf .bundle Gemfile.lock tmp/ \
          lib/linguist/linguist.so \
          lib/linguist/samples.json \
          test/fixtures/ace_modes.json; \
   bundle exec samples test 2>&1) \
   | tee /tmp/2.log

# Click to show output
~~~
</summary>

```
mkdir -p tmp/x86_64-openbsd/linguist/2.6.6
cd tmp/x86_64-openbsd/linguist/2.6.6
/usr/local/bin/ruby26 -I. ../../../../ext/linguist/extconf.rb
creating Makefile
cd -
cd tmp/x86_64-openbsd/linguist/2.6.6
/usr/local/bin/gmake
compiling ../../../../ext/linguist/lex.linguist_yy.c
compiling ../../../../ext/linguist/linguist.c
compiling ../../../../ext/linguist/strndup.c
linking shared-object linguist/linguist.so
cd -
mkdir -p tmp/x86_64-openbsd/stage/lib/linguist
cp LICENSE tmp/x86_64-openbsd/stage/LICENSE
mkdir -p tmp/x86_64-openbsd/stage/bin
cp bin/git-linguist tmp/x86_64-openbsd/stage/bin/git-linguist
cp bin/github-linguist tmp/x86_64-openbsd/stage/bin/github-linguist
mkdir -p tmp/x86_64-openbsd/stage/ext/linguist
cp ext/linguist/extconf.rb tmp/x86_64-openbsd/stage/ext/linguist/extconf.rb
cp ext/linguist/lex.linguist_yy.c tmp/x86_64-openbsd/stage/ext/linguist/lex.linguist_yy.c
cp ext/linguist/lex.linguist_yy.h tmp/x86_64-openbsd/stage/ext/linguist/lex.linguist_yy.h
cp ext/linguist/linguist.c tmp/x86_64-openbsd/stage/ext/linguist/linguist.c
cp ext/linguist/linguist.h tmp/x86_64-openbsd/stage/ext/linguist/linguist.h
cp ext/linguist/strndup.c tmp/x86_64-openbsd/stage/ext/linguist/strndup.c
cp ext/linguist/tokenizer.l tmp/x86_64-openbsd/stage/ext/linguist/tokenizer.l
cp lib/linguist.rb tmp/x86_64-openbsd/stage/lib/linguist.rb
cp lib/linguist/VERSION tmp/x86_64-openbsd/stage/lib/linguist/VERSION
cp lib/linguist/blob.rb tmp/x86_64-openbsd/stage/lib/linguist/blob.rb
cp lib/linguist/blob_helper.rb tmp/x86_64-openbsd/stage/lib/linguist/blob_helper.rb
cp lib/linguist/classifier.rb tmp/x86_64-openbsd/stage/lib/linguist/classifier.rb
cp lib/linguist/documentation.yml tmp/x86_64-openbsd/stage/lib/linguist/documentation.yml
cp lib/linguist/file_blob.rb tmp/x86_64-openbsd/stage/lib/linguist/file_blob.rb
cp lib/linguist/generated.rb tmp/x86_64-openbsd/stage/lib/linguist/generated.rb
cp lib/linguist/grammars.rb tmp/x86_64-openbsd/stage/lib/linguist/grammars.rb
cp lib/linguist/heuristics.rb tmp/x86_64-openbsd/stage/lib/linguist/heuristics.rb
cp lib/linguist/heuristics.yml tmp/x86_64-openbsd/stage/lib/linguist/heuristics.yml
cp lib/linguist/language.rb tmp/x86_64-openbsd/stage/lib/linguist/language.rb
cp lib/linguist/languages.yml tmp/x86_64-openbsd/stage/lib/linguist/languages.yml
cp lib/linguist/lazy_blob.rb tmp/x86_64-openbsd/stage/lib/linguist/lazy_blob.rb
cp lib/linguist/popular.yml tmp/x86_64-openbsd/stage/lib/linguist/popular.yml
cp lib/linguist/repository.rb tmp/x86_64-openbsd/stage/lib/linguist/repository.rb
cp lib/linguist/samples.rb tmp/x86_64-openbsd/stage/lib/linguist/samples.rb
cp lib/linguist/sha256.rb tmp/x86_64-openbsd/stage/lib/linguist/sha256.rb
cp lib/linguist/shebang.rb tmp/x86_64-openbsd/stage/lib/linguist/shebang.rb
mkdir -p tmp/x86_64-openbsd/stage/lib/linguist/strategy
cp lib/linguist/strategy/extension.rb tmp/x86_64-openbsd/stage/lib/linguist/strategy/extension.rb
cp lib/linguist/strategy/filename.rb tmp/x86_64-openbsd/stage/lib/linguist/strategy/filename.rb
cp lib/linguist/strategy/manpage.rb tmp/x86_64-openbsd/stage/lib/linguist/strategy/manpage.rb
cp lib/linguist/strategy/modeline.rb tmp/x86_64-openbsd/stage/lib/linguist/strategy/modeline.rb
cp lib/linguist/strategy/xml.rb tmp/x86_64-openbsd/stage/lib/linguist/strategy/xml.rb
cp lib/linguist/tokenizer.rb tmp/x86_64-openbsd/stage/lib/linguist/tokenizer.rb
cp lib/linguist/vendor.yml tmp/x86_64-openbsd/stage/lib/linguist/vendor.yml
cp lib/linguist/version.rb tmp/x86_64-openbsd/stage/lib/linguist/version.rb
install -c tmp/x86_64-openbsd/linguist/2.6.6/linguist.so lib/linguist/linguist.so
cp tmp/x86_64-openbsd/linguist/2.6.6/linguist.so tmp/x86_64-openbsd/stage/lib/linguist/linguist.so
/usr/local/lib/ruby/gems/2.6/gems/charlock_holmes-0.7.7/lib/charlock_holmes/encoding_detector.rb:66: warning: instance variable encoding_list not initialized
msyscall f69eee0f000 a5000 error
/usr/local/lib/ruby/2.6/forwardable/impl.rb:3: warning: method redefined; discarding old _valid_method?
/usr/local/lib/ruby/gems/2.6/gems/forwardable-1.3.1/lib/forwardable/impl.rb:3: warning: previous definition of _valid_method? was here
/usr/local/lib/ruby/2.6/forwardable/impl.rb:11: warning: method redefined; discarding old _compile_method
/usr/local/lib/ruby/gems/2.6/gems/forwardable-1.3.1/lib/forwardable/impl.rb:13: warning: previous definition of _compile_method was here
/usr/local/lib/ruby/2.6/forwardable.rb:116: warning: already initialized constant Forwardable::VERSION
/usr/local/lib/ruby/gems/2.6/gems/forwardable-1.3.1/lib/forwardable/version.rb:3: warning: previous definition of VERSION was here
/usr/local/lib/ruby/2.6/forwardable.rb:117: warning: already initialized constant Forwardable::FORWARDABLE_VERSION
/usr/local/lib/ruby/gems/2.6/gems/forwardable-1.3.1/lib/forwardable/version.rb:4: warning: previous definition of FORWARDABLE_VERSION was here
/usr/local/lib/ruby/2.6/forwardable.rb:122: warning: method redefined; discarding old debug
/usr/local/lib/ruby/2.6/forwardable.rb:122: warning: method redefined; discarding old debug=
/usr/local/lib/ruby/2.6/forwardable.rb:193: warning: method redefined; discarding old _delegator_method
/usr/local/lib/ruby/gems/2.6/gems/forwardable-1.3.1/lib/forwardable.rb:198: warning: previous definition of _delegator_method was here
Run options: --seed 9277

# Running:

...............................................................................msyscall 28cf01d0000 a5000 error
..................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

Finished in 251.312783s, 5.4792 runs/s, 111.7452 assertions/s.

1377 runs, 28083 assertions, 0 failures, 0 errors, 0 skips
```

</details>

I suspect this is related to Ruby's package manager ("bundler" or whatever it's called). @lildude might know more about this error, but AFAICT, this is a non-issue. Disregard.

**Comment by lildude** [comment]
> @lildude might know more about this error

I have no idea why you have the forwardable gem installed but yes it definitely appears to be the cause of the messages, and yes, bundler doesn't clean up after itself automatically. You need to run `bundle clean` if you've installed gems outside of the Gemlock file etc.

I've tested this PR on macOS with a clean checkout and don't get any errors, though I notice it does fix one warning I get on `master`:

```
[...]
/usr/bin/make
compiling ../../../../ext/linguist/lex.linguist_yy.c
lex.linguist_yy.c:1879:1: warning: function 'yy_fatal_error' could be declared with attribute 'noreturn' [-Wmissing-noreturn]
{
^
1 warning generated.
compiling ../../../../ext/linguist/linguist.c
compiling ../../../../ext/linguist/strndup.c
[...]
```

**Review by lildude — APPROVED** [review]
LGTM. Thanks for this.

**Comment by Alhadis** [comment]
> I have no idea why you have the `forwardable` gem installed

That makes two of us. Ah well, at least there's no (real) issue.

LGTM too. 👍

**Review by Alhadis — APPROVED** [review]

**Review by JT0407 — COMMENTED** [review]
#

**Pull request merged**
