### PR TITLE
Added Ring Language Support

### PR DESCRIPTION
**Pull request by MahmoudFayed**
Added Ring Language Support - *.ring files

### CODE REVIEW

**Comment by arfon** [comment]
Hi @MahmoudFayed - thanks for starting this Pull Request. Please take a look at our [contributing guidelines](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language) to see what else is needed here - it looks like the entry in `languages.yml` is missing as is a link to a GitHub search demonstrating usage of `.ring`

**Comment by MahmoudFayed** [comment]
Hi @arfon - Thanks, I have already added the entry in languages.yml also the next link demostrating usage of .ring https://github.com/search?utf8=%E2%9C%93&q=extension%3Aring+NOT+nothack&type=Code&ref=searchresults

**Comment by arfon** [comment]
Hi @MahmoudFayed - thanks for the updates. Looking at your search result, I'm not sure all of these are the Ring language. [This one](https://github.com/gitpan/PerlMol/blob/bd5257d2e3b44d79420a528da86135e72c3eeefa/inc/BUNDLES/Chemistry-Ring-0.19/t/rings2/disconnected.ring) for example appears to be a molecular structure.

Would it be possible for you to construct a more specific search query only finding the correct file types?

**Comment by MahmoudFayed** [comment]
Hi @arfon - thanks for the feedback. I have already tried the next search to get the correct files : https://github.com/search?utf8=%E2%9C%93&q=extension%3Aring+see&type=Code&ref=searchresults

**Comment by arfon** [comment]
@MahmoudFayed - quoting from our [contributing guidelines](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language):

> We try only to add languages once they have some usage on GitHub. In most cases we prefer that each new file extension be in use in hundreds of repositories before supporting them in Linguist.

Looking at your search results it appears that the vast majority of these files are in the parent repo for the language https://github.com/ring-lang/ring

At this point I don't believe `Ring` meets our guidelines for adding it to Linguist as the usage is just too low. In the past we've periodically checked in on potential new languages and when they reach the required levels of adoption (hundreds of repos) we've then worked on adding the language to Linguist.

**Comment by MahmoudFayed** [comment]
@arfon Thanks for your feedback.

**Comment by arfon** [comment]
Closing this for now but let's revisit in a couple of months.

**Pull request closed without merging**
