### PR TITLE
Add HCL to languages.yml

### PR DESCRIPTION
**Pull request by sethvargo**
More information on HCL: https://github.com/hashicorp/hcl

### CODE REVIEW

**Comment by arfon** [comment]
Looks like there are other languages using `.hcl` too: https://github.com/davidw/hecl - https://github.com/search?utf8=%E2%9C%93&q=source+extension%3Ahcl&type=Code&ref=searchresults

We'll need to work out a good way we can disambiguate these two before merging this.

**Comment by arfon** [comment]
:flags: flagging this as stale :flags:

**Comment by sethvargo** [comment]
Hi @arfon 

Thanks for the ping. I'm not sure of a good way to distinguish between the other HCL extensions. I'd welcome any ideas.

**Comment by arfon** [comment]
The other files look to be `Hecl` which doesn't seem to have seen any updates since 2010. Also, a cursory search for `Hecl` files makes me think the level of usage is extremely low (tens of files).

I therefore think it's OK for us to merge this as-is.

Thanks for you patience @sethvargo - this should be live in the next release of Linguist.

**Pull request merged**
