### PR TITLE
Update test_generated.rb

### PR DESCRIPTION
**Pull request by MoeFarag**
## Description
Adds missing tests although fixtures exist

## Checklist:

- [ ] **I am associating a language with a new file extension.**
  - [ ] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      
      - https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am adding a new language.**
  - [ ] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  
  - [ ] I have included a syntax highlighting grammar: https://github-lightshow.herokuapp.com/
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

- [ ] **I am fixing a misclassified language**
  - [ ] I have included a new sample for the misclassified language:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am changing the source of a syntax highlighting grammar**
  
  - Old: https://github-lightshow.herokuapp.com/
  - New: https://github-lightshow.herokuapp.com/
  
- [ ] **I am updating a grammar submodule**
  

- [x] **I am adding new or changing current functionality**
  
  - [x] I have added or updated the tests for the new or changed functionality.

### CODE REVIEW

**Comment by pchaigno** [comment]
Those tests shouldn't actually be needed thanks to [`test_blob.rb`](https://github.com/github/linguist/blob/e4560984058b4726010ca4b8f03ed9d0f8f464db/test/test_blob.rb#L283-L284).

**Comment by MoeFarag** [comment]
Sorry, I'm not clear on how does this check the detection logic is correct?

**Comment by pchaigno** [comment]
The two lines I linked to verify that files in the `Generated/` directory are detected as generated.

**Comment by MoeFarag** [comment]
Ok, thanks for the clarifications. It is a bit interleaved if that fails, you'll need a bit of digging to see where it fails, but at least the integrity is not comprised. Feel free to close the PR if it doesn't make sense to you

**Pull request closed without merging**
