### PR TITLE
Change Inform7 grammar source

### PR DESCRIPTION
**Pull request by erkyrath**
The Inform 7 grammar module has been transferred to the [Interactive Fiction Technology Foundation][iftf].

[iftf]: https://iftechfoundation.org/

## Description
The Inform 7 grammar module has been updated to v1.0.3. The grammar has not changed; this just updates the metadata to reflect the new ownership.

## Checklist:

- [X] **I am changing the source of a syntax highlighting grammar**
  - Old: [URL to grammar repo](https://github.com/erkyrath/language-inform7)
  - New: [URL to grammar repo](https://github.com/iftechfoundation/language-inform7)

### CODE REVIEW

**Comment by erkyrath** [comment]
The check task is failing with "cached dependency record out of date", and I'm afraid I don't know what that means.

**Review by lildude — CHANGES_REQUESTED** [review]
> The check task is failing with "cached dependency record out of date", and I'm afraid I don't know what that means.

I means you didn't use the `script/add-grammar` to replace the grammar and thus didn't get the new updated cached license file. If you did, then you've forgotten to add it to this PR. Please run that script to replace the grammar and add the resulting license file to this PR.

**Comment by lildude** [comment]
> Please run that script to replace the grammar and add the resulting license file to this PR.

I've done this for you.

**Review by lildude — APPROVED** [review]

**Comment by erkyrath** [comment]
Thank you!

**Pull request merged**
