### PR TITLE
Added fastlane configuration files

### PR DESCRIPTION
**Pull request by KrauseFx**
[fastlane](https://fastlane.tools) is an established Continuous Delivery solution for iOS/Mac projects. The configuration files are similar to a `Podfile`, also Ruby based. 

Some examples:
- https://github.com/wikimedia/apps-ios-wikipedia/blob/master/fastlane/Fastfile
- https://github.com/wikimedia/apps-ios-wikipedia/blob/master/fastlane/Deliverfile
- https://github.com/artsy/eidolon/blob/master/fastlane/Fastfile
- https://github.com/fastlane/examples/blob/master/MindNode/Fastfile

The configuration files added with this pull request: `Fastfile`, `Deliverfile` and `Snapfile` :+1:

### CODE REVIEW

**Comment by pchaigno** [comment]
[735 `Fastfile` files](https://github.com/search?utf8=%E2%9C%93&q=filename%3AFastfile&type=Code&ref=searchresults) but only [80 `Snapfile` files](https://github.com/search?utf8=%E2%9C%93&q=filename%3ASnapfile&type=Code&ref=searchresults) and [62 `Deliverfile` files](https://github.com/search?utf8=%E2%9C%93&q=filename%3ADeliverfile).
@arfon What's the rule for filenames? Are the last two numbers enough?

**Comment by KrauseFx** [comment]
@pchaigno thanks for the quick reply. `Fastfile` definitely is the most important one. Just keep in mind, this is a deployment solution for iOS projects. Most companies have their iOS apps closed source and not publicly available.

**Comment by arfon** [comment]
> @arfon What's the rule for filenames? Are the last two numbers enough?

@pchaigno - based on @KrauseFx's comments I ran a quick staff search which gives me high-level stats for all files (not just public ones) and it looks like there are about 600 `Snapfile` and `Deliverfile` files on GitHub in total so I think we should include them all.

**Comment by pchaigno** [comment]
> it looks like there are about 600 Snapfile and Deliverfile files on GitHub in total so I think we should include them all.

Perfect!

@KrauseFx Could you add sample files for these three filenames?

**Comment by KrauseFx** [comment]
@arfon Great, thank you! :+1: 

@pchaigno Sure:

- [Fastfile](https://github.com/wikimedia/apps-ios-wikipedia/blob/master/fastlane/Fastfile)
- [Deliverfile](https://github.com/fastlane/examples/blob/master/SunApps/Deliverfile)
- [Snapfile](https://github.com/fastlane/examples/blob/master/SunApps/Snapfile)

Thanks again :+1:

**Comment by pchaigno** [comment]
Could you add them in the `samples/Ruby/filenames/` directory of this pull request?

**Comment by KrauseFx** [comment]
@pchaigno sure thing, added with https://github.com/KrauseFx/linguist/commit/fd4111cdbe383208a9f9efd498ddb6a88a05f96a

I saw the `Podfile` was missing there too, so I added an example `Podfile` as well :+1:

**Comment by pchaigno** [comment]
> I saw the Podfile was missing there too, so I added an example Podfile as well 

Great! Thanks! :zap:

**Comment by arfon** [comment]
:+1: thanks for this @KrauseFx

**Comment by KrauseFx** [comment]
Thank you @arfon for taking the time and merging the changes. Really appreciated :+1:

**Comment by arfon** [comment]
@KrauseFx - my pleasure. These changes will be live in the next release of Linguist

**Pull request merged**
