### PR TITLE
Grammar for AutoHotkey

### PR DESCRIPTION
**Pull request by pchaigno**
This pull request adds [a grammar](https://github.com/robertcollier4/AutoHotkey) for AutoHotkey as discussed in #1898.

### CODE REVIEW

**Comment by aroben** [comment]
Thanks! Could you see about getting a license added to the grammar?

**Comment by pchaigno** [comment]
I just asked @robertcollier4 in #1898.

**Comment by robertcollier4** [comment]
I have added UNLICENSE.txt to the root of the AutoHotKey github repo.
https://github.com/robertcollier4/AutoHotkey/commit/a2207359782c564a9a3bfe5142d7b5a250d9b18b

**Comment by arfon** [comment]
Thanks @robertcollier4 and @pchaigno. This should be live on GitHub in the next couple of weeks.

**Pull request merged**
