### PR TITLE
Add varlink grammar

### PR DESCRIPTION
**Pull request by haraldh**
Added the [varlink](https://varlink.org) grammar and a sample.

## Checklist:
- [x] **I am adding a new language.**
  - [ ] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?utf8=%E2%9C%93&q=extension%3Avarlink+NOT+notahack
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - https://github.com/varlink/com.redhat.system/blob/master/src/com.redhat.system.varlink
    - Sample license(s):
      - MIT and Apache
  - [x] I have included a syntax highlighting grammar.
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

### CODE REVIEW

**Comment by haraldh** [comment]
```
$ script/licensed --module /home/harald/git/linguist/vendor/grammars/language-varlink
Caching licenes for linguist:
  grammar dependencies:
caching /home/harald/git/linguist/vendor/grammars/language-varlink
    Using language-varlink ()
License caching complete!
* linguist grammar dependencies: 1
```
But...
```
$ script/licensed status
[…]
Warnings:

/home/harald/git/linguist/vendor/licenses/grammar/language-varlink.txt:
  - cached license data missing
```

**Comment by lildude** [comment]
The problem adding the license should be addressed with the changes coming in #4152.

The test failures appear to be caused by recent changes to licensee which has resulted in a slightly modified hash for the four licenses in question. I'll address this in #4152 too.

**Comment by lildude** [comment]
Merging master into your branch should fix the failing tests.

**Comment by haraldh** [comment]
rebased on master... checks are ok now

**Comment by haraldh** [comment]
ping

**Comment by lildude** [comment]
Pong!

Unfortunately, `varlink` doesn't currently meet the "hundreds of repositories" requirement detailed in [Adding a Language](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-an-extension-to-a-language) yet.

I've tagged this PR accordingly. You're welcome to leave this PR open pending an increase in popularity or close it and reopen it when things have picked up.

**Comment by haraldh** [comment]
Thanks... let's hope varlink takes off 😄

**Comment by pchaigno** [comment]
Closing in favor of #4219. We'll monitor the popularity of the extension there.

If you have an improved search query compared to the one used in #4219, please post it here and I'll update #4219.

**Pull request closed without merging**
