### PR TITLE
Add smalltalk samples

### PR DESCRIPTION
**Pull request by jecisc**
(Issue: https://github.com/github/linguist/issues/3244)

### CODE REVIEW

**Comment by jecisc** [comment]
Can someone help me to understand how to correct the build?

**Comment by pchaigno** [comment]
It looks like the build is failing because of an unrelated issue.
Sorry about that. We'll try to fix it as soon as possible.

**Comment by jecisc** [comment]
I asked a question on the issue. Maybe you should look at it before merging: https://github.com/github/linguist/issues/3244

**Comment by Haroenv** [comment]
Shouldn't `samples/Smalltalk/renderSeasideExampleOn..st` have only one dot? (`samples/Smalltalk/renderSeasideExampleOn.st`)

**Comment by Alhadis** [comment]
Nope... it's pretty much the same as having a filename of `renderSeasideExampleOn.`.

It *does* look a little sloppy though... boeie.

**Comment by jecisc** [comment]
Smalltalk does not have source files. The code is in memory. When we need to use a version manager as github we export the code as file with 1 file/method and the file name is the name of the method. 
`renderContentOn..st` is the file name for the method `renderContentOn: aCanvas`.
So the `.` is needed.

**Comment by Alhadis** [comment]
There you go. We've both been told.

**Comment by Haroenv** [comment]
Okay, didn't know about the inner workings, just saw that there was only one file and it could've been erroneous

**Comment by pchaigno** [comment]
Percentage of HTML with and without this PR for the repositories from #3244:

Repository | Before | After | Expected
---|---|---|---
[DuneSt/MaterialDesignLite](https://github.com/DuneSt/MaterialDesignLite) | 4.43% | 0.25% | 0%
[jecisc/SeasideComponents](https://github.com/jecisc/SeasideComponents) | **8.31%** | 0% | 0%
[jecisc/WebPokedex](https://github.com/jecisc/WebPokedex) | 1.48% | 0.07% | 0%
[npasserini/iceberg](https://github.com/npasserini/iceberg) | 3.62% | 1.70% | 0%
[LeCoinEnBande/OOnoz](https://github.com/LeCoinEnBande/OOnoz) | **32%** | 23.93% | 23.76%
[DuneSt/ChartJs](https://github.com/DuneSt/ChartJs) | **57.33%** | **55.42%** | 0%
[DuneSt/PrismCodeDisplayer](https://github.com/DuneSt/PrismCodeDisplayer) | **96.60%** | 0.29% | 0%

Clearly an improvement! :tada: 

I think the high number of misclassified files for ChartJS is due to the fact that many of them are very small files (less than 5 lines). It's difficult for any strategy to correctly identify such files :/
Your best bet is to use [Linguist overrides](https://github.com/github/linguist#overrides) at this point.

**Comment by jecisc** [comment]
Thank you :)
"I think the high number of misclassified files for ChartJS is due to the fact that many of them are very small files (less than 5 lines)."
It is not call Smalltalk for nothing ;)

**Comment by arfon** [comment]
👍 thanks for these @jecisc. This change will be live in the next release of Linguist (next week sometime)

**Comment by philippeback** [comment]
This is great! Thx

**Pull request merged**
