### PR TITLE
Fixes #4113 : Adds .mir to YAML

### LINKED ISSUE #4113: LLVM MachineIR is identified as Mirah Language
## Preliminary Steps

Please confirm you have...
- [✅] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [✅] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [✅] considered implementing an [override](https://github.com/github/linguist#overrides),
- [✅] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

LLVM has a small obscure format known as MIR which stands for MachineIR. This is currently being recognized as Mirah language due to the file extension ``.mir``. This could be detected by using LLVM MIR's keywords like ``liveins:`` ``body:`` ``tracksRegLiveness`` and whatnot
### URL of the affected repository:

[LLVM-Mirror](https://github.com/llvm-mirror/llvm)

### Last modified on:

2018-04-23
### Expected language:

LLVM MachineIR
### Detected language:

Mirah

### PR DESCRIPTION
**Pull request by gabru-md**
This Pull request solves issue #4113 
It adds `.mir` in YAML category

## Description

 It adds `.mir` in YAML category and this PR also contains a sample code of the extension `.mir` used in LLVM projects.
The sample is taken from un-official LLVM Mirror on Github. 
The sample code is accompanied by LICENSE specified in the repository with the original link to source code also mentioned in comments.
## Checklist:

- [X] **I am associating a language with a new file extension.**
  - [X] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      
      - https://github.com/search?p=1&q=extension%3Amir+liveins+OR+tracksRegLiveness&type=Code&utf8=%E2%9C%93
  - [X] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [expected-floating-point-literal.mir](https://github.com/llvm-mirror/llvm/blob/b931375195077d79330792590733db7de9a8f1bd/test/CodeGen/MIR/NVPTX/expected-floating-point-literal.mir)
    - Sample license(s):
      - [LICENSE.TXT](https://github.com/llvm-mirror/llvm/blob/b931375195077d79330792590733db7de9a8f1bd/LICENSE.TXT)
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am adding a new language.**
  - [ ] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a syntax highlighting grammar.
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am fixing a misclassified language**
  - [ ] I have included a new sample for the misclassified language:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am changing the source of a syntax highlighting grammar**
  
  - Old: https://github-lightshow.herokuapp.com/
  - New: https://github-lightshow.herokuapp.com/

- [ ] **I am adding new or changing current functionality**
  
  - [ ] I have added or updated the tests for the new or changed functionality.

### CODE REVIEW

**Comment by gabru-md** [comment]
cc : @pchaigno

**Comment by gabru-md** [comment]
The build here is failing for two possible reasons, that I can understand:
- The extensions for `YAML` are not in correct order.
- According to `languages.yml` the `.mir` extension is for more than one language, therefore samples must be provided for both languages bearing the same `.mir` extension.

I went to the official [Mirah community Github](https://github.com/mirah) to get some examples, but all the files in their repositories have `.mirah` extensions. I am not sure, but it does seem to me that `.mir` is not a Mirah extension at all. See the Mirah Files on their github, links are given below
- [files in mirah/mmeta](https://github.com/mirah/mmeta/search?l=mirah)
- [files in mirah/mirah_model](https://github.com/mirah/mirah_model/search?l=mirah)
- [files in mirah/mirah](https://github.com/mirah/mirah/search?l=mirah)

cc : @pchaigno 

what should I do? should I remove `.mir` from Mirah?

**Comment by gabru-md** [comment]
@pchaigno I've got it confirmed that `.mir` is not an extension for Mirah and hence can be removed from Mirah's extensions in `languages.yml`.
I have already done that in my Pull Request here, Please review it.
Here is the link to the issue [where I got response from Mirah's Owner](https://github.com/mirah/mirah/issues/462) clarifying the doubt. :+1:

**Comment by pchaigno** [comment]
That file extension dates from the [initial versions of Linguist](https://github.com/github/linguist/commit/37243ec6bed3e697beeb874fc94efb9e42ca7f8c) (2011). It's probably fine to remove it given the usage. @lildude ?

**Comment by gabru-md** [comment]
Oh! It has been a bug for so long :open_mouth:

**Comment by gabru-md** [comment]
Any reviews on this PR @pchaigno @lildude ? :sweat_smile:

**Comment by RobQuistNL** [comment]
From what I understand the first item in the list should always be the main file extension. You can see this is the case for all other file extensions as well. (Example: https://github.com/gabru-md/linguist/blob/a12ce9b736321450108cfdced365ba146a2ffbfb/lib/linguist/languages.yml#L5063)

So the order should not be an issue either. Its probably because of the missing example files.

Please revert .yml to the top, add .mir in an alphabetical order, and then we should be good for this one IMHO :)

**Comment by gabru-md** [comment]
Okay. I'll do it. Wait for travis and then ping you.
:+1:

**Comment by gabru-md** [comment]
@pchaigno @lildude @RobQuistNL please review :)

**Comment by RobQuistNL** [comment]
LGTM :+1:

**Comment by gabru-md** [comment]
@pchaigno can you provide with a review please.
If there are any changes I should make or it this okay ?

**Comment by gabru-md** [comment]
@lildude @pchaigno can you please review. The PR has been opened for 13 days :sweat_smile:

**Comment by pchaigno** [comment]
> I don't review PRs until reviewed by another contributor anyway.

Yep, but on this one, I'm [waiting on an answer from you](https://github.com/github/linguist/pull/4126#issuecomment-387792326), @lildude :-)

**Comment by lildude** [comment]
> Yep, but on this one, I'm waiting on an answer from you, @lildude :-)

Whoops 😊  That's further down my backlog 😄 

> That file extension dates from the initial versions of Linguist (2011). It's probably fine to remove it given the usage. @lildude ?

Yup. Fine to remove it.

**Comment by gabru-md** [comment]
I'm sorry! I'll be patient. :sweat_smile: 
>Please be patient; Linguist is a hobby for all of the primary contributors and not our jobs.

**Comment by gabru-md** [comment]
Thank you!
I am happy contributing to Linguist.
I will be taking up more issues and help solving them. :clinking_glasses:

**Comment by pchaigno** [comment]
> I will be taking up more issues and help solving them. :clinking_glasses: 

We can certainly use the help!

**Pull request merged**
