### PR TITLE
Change Salt to programming per #2307

### PR DESCRIPTION
**Pull request by DavidJFelix**
- Add a color
- Remove group

### CODE REVIEW

**Comment by arfon** [comment]
Hi @DavidJFelix - thanks for this. Unfortunately this colour clashes with some others already in use:

```
  1) Failure:
TestColorProximity#test_color_proximity [/home/travis/build/github/linguist/test/test_color_proximity.rb:21]:
The following 1 languages have failing color thresholds. Please modify the hex color.
- SaltStack (#77BDF7) is too close to ["88ccff", "77BDF7"]
```

Can we find something that doesn't conflict?

**Comment by DavidJFelix** [comment]
I honestly didn't know that rule. How different does it have to be? Where can I see the current colors?

**Comment by DavidJFelix** [comment]
And tbh I don't mind any color

**Comment by bkeepers** [comment]
You can see the existing colors at http://github.github.io/linguist/. The current threshold is `0.5`, but to be honest, I don't really know what that means.

**Comment by DavidJFelix** [comment]
@bkeepers any suggestion for a less brute-force way to pick a color?

**Comment by DavidJFelix** [comment]
A link to the library being used with a 0.5 threshold http://libraries.io/rubygems/color-proximity

**Comment by pchaigno** [comment]
@DavidJFelix - @gjtorikian added the proximity test for colors in #2298. [He also described (comment)](https://github.com/github/linguist/pull/2298#issuecomment-90150424) how he chose the colors. I think it would be a good idea to follow this process for SaltStack.

**Comment by DavidJFelix** [comment]
@pchaigno I appreciate the help, but at this point I was thinking tearing my toenails off and offering them to Cthulhu in exchange for a color that passes is sounding like a more pleasurable option.

**Comment by DavidJFelix** [comment]
I just rebased to remove extraneous commits and also try to wake travis-ci up since it had a hiccup on the last commit.

**Comment by pchaigno** [comment]
> I was thinking tearing my toenails off and offering them to Cthulhu in exchange for a color that passes is sounding like a more pleasurable option

Rôo, it's not that complicated :P
Does SaltStack have a logo or symbol? Maybe a mascot? :smile:

**Comment by DavidJFelix** [comment]
Logo: 



Their color-scheme seems to be black/white with a python/blue yellow on sales material. You have to remember, salt is a DSL build with python through and through. Its templates use Jinja2, a templating language which can embed python. The fact that it shares colors with python along with the number of existing colors led me to the decision that it wasn't worth holding up the change I really wanted over one I didn't really care about.

To be honest, the color choosing process is more complicated than I'd like to be involved with. You have to remember that this project is a nexus for all languages, not just ruby. I'm not about to go through the process of getting ruby on my machine and having linguist run locally just to test if a color is allowed or not. Even if I was, using a fail/pass test hooked up to a fairly opaque formula as a guiding point for choosing one of 16M colors isn't a great starting point.

Take the following with a grain of salt (no pun intended) because it's entirely from a contributor perspective and may be way more effort than simply choosing a color yourselves every time:

I think ideally, the way to do this would be to generate some kind of hex color map every time the colors are changed (16 million isn't a big number for having a program automate this, but we could down sample a bit if needed). If the color passes, a 1 goes into into the address in a bitarray, if it fails, a 0 (this ought to gzip up pretty nicely). Since hex color space is 3 dimensional, a 2d image of it may not help visually. My opinion would be to host a HSV style color picker like this one: http://www.colorpicker.com/ which reads in the bit array and only displays colors that are still acceptable. It would need a second color picker with unrestricted colors that could set the background, to ensure that the holes in the chart can be properly contrasted. 

This is probably like killing a spider with a shotgun though. At least you'd be sure it was dead.

**Comment by pchaigno** [comment]
First, I should clarify that I'm not part of GitHub staff. So, this is only my own opinion.
<br/>

> To be honest, the color choosing process is more complicated than I'd like to be involved with.

If you don't have time or if you don't want to go through the whole process of making a change to Linguist, you can just open an issue and ask for that change, as you did in #2307. Nobody is forcing you to open a pull request and I think we can all understand that you don't have time to do it.
I'd be happy to do it. It would probably take more time though.
<br/>

> I think ideally, the way to do this would be to generate some kind of hex color map every time the colors are changed (16 million isn't a big number for having a program automate this, but we could down sample a bit if needed).

The current process and test are more complicated than that because we don't only want different colors, we actually want every two colors to be distinguishable to the human eye. That's why we use this *opaque* formula (#2298 explains how it was chosen).

@bkeepers pointed above to http://github.github.io/linguist/. This page displays all the colors in use and can help greatly to find an available color. If a color looks close to one on that page it will probably not pass the color proximity test.
<br/>

Of course, I understand that you don't have time to go through this process. I can do that for you, I'll just need pointers to colors we could use. I'm not sure it would be a good idea to use white (@arfon @bkeepers ?). The black colors are already taken by a few languages. Maybe we could try the python's colors. Do you have an image of that python?

**Comment by DavidJFelix** [comment]
@pchaigno please don't mistake my desire to improve process as abrasiveness. I **very much** appreciate the help, but I honestly feel like I'm taking crazy pills looking at all of these colors. I clearly have enough time for this, but I know for certain there are others who would not, and you're potentially turning them away with what I find to be unnecessary process and red tape.

> The current process and test are more complicated than that because we don't only want different colors, we actually want every two colors to be distinguishable to the human eye. That's why we use this opaque formula (#2298 explains how it was chosen).

I think you're misunderstanding my claim and subsequently my suggestion. My claim that the formula is opaque is not that it is some dark magic or closed-door discussion, but rather that it is not apparent as a reversible formula. While it the function certainly has source code and is documented there is currently no (reasonable) way for me to take the knowledge of the formula and convert it into usable information. Apart from exhaustively checking colors I *think might work* (IE guess and check), there is no meaningful way that I can take the function and make it useful to me. The process I proposed as an alternative is not to randomly choose a color that passes, but instead to generate a color picker that only has *valid colors* as options. We can use the same test that is currently used as a mechanism to generate that -- the only difference is that we have a machine exhaustively checking colors rather than me digging out my eyes with a spoon.

> @bkeepers pointed above to http://github.github.io/linguist/. This page displays all the colors in use and can help greatly to find an available color. If a color looks close to one on that page it will probably not pass the color proximity test.

Yes, he has. It certainly looks nice, and is a good way to eliminate colors I may want but again, the information isn't useful to me in coming up with a color from nothing. There's no way for me to look at a panel of 200 colors and easily pick a color that is **not** present. Firstly, I'm not a savant, so I can't keep 200 colors in my brain. Secondly this difficulty is exacerbated by the fact that proximity is accounted for in a 3 dimensional colorspace, so I'm not actually checking the page to determine if a color I want is there, but rather if a fuzzy approximation of it is there. I'm fighting shadows at this point. I have to search against 200 colors and some of their close relatives that I have no ability to fathom. To me, I look at this page and approximately all colors in the universe appear to be present, so looking at it and trying to come up with a new color is an utterly hopeless affair. See XKCD color survey:

[](http://blog.xkcd.com/2010/05/03/color-survey-results/)

> Of course, I understand that you don't have time to go through this process.

Again, I have plenty of time. I'm here still. But there is no process that I see available to complete this task before the heat death of the universe if I attempt without a tool. Again, sorry for ranting. Maybe I'm wrong and it's not hard, but if that were the case, surely somebody would silence my whining and pull a magical color from their hat. Nobody has done that though, which leads me to the assumption that it's not as easy as I'm being told.

> Do you have an image of that python?

If you ask people to name colors long enough, they go totally crazy.

**Comment by pchaigno** [comment]
> The process I proposed as an alternative is not to randomly choose a color that passes, but instead to generate a color picker that only has valid colors as options

You could propose that as a github-page for https://github.com/gjtorikian/color-proximity. Or even develop it if you have time. I think it's a really good idea and it would certainly fasten our process :-)
<br/>

> 376672e706e67

I thought you meant an actual python (the snake) :stuck_out_tongue_closed_eyes: 
<br/>

> Maybe I'm wrong and it's not hard, but if that were the case, surely somebody would silence my whining and pull a magical color from their hat. Nobody has done that though, which leads me to the assumption that it's not as easy as I'm being told.

[#646464](http://www.colorhexa.com/646464) from the Python logo works.

**Comment by DavidJFelix** [comment]
> You could propose that as a github-page for https://github.com/gjtorikian/color-proximity. Or even develop it if you have time. I think it's a really good idea and it would certainly fasten our process :-)

I have a script that walks through all colors and checks them against the distance check then writes the bool out to a bitarray. The tool uses python/colormath which alleges to use the same spec as the ruby library above. I'm pretty distanced from ruby development, so it may not coexist "nicely" with the test without some outside help. I'm still working on the visualization tool for it. Trying something js based.

> #646464 from the Python logo works.

Lasso is [#999999](http://www.colorhexa.com/999999) and SQF is [#3F3F3F](http://www.colorhexa.com/3f3f3f), which is why I hadn't chosen that color or one of their site's grey. If it works though, I'll patch it in work on the picker.

**Comment by DavidJFelix** [comment]
kewl. This should be good now.

**Comment by arfon** [comment]
:+1: thanks @DavidJFelix and @pchaigno.

This will be live on GitHub in the next week or so.

**Comment by DavidJFelix** [comment]
@afron is this live? I'm not seeing it in the composition bar chart.

**Comment by arfon** [comment]
> @afron is this live? I'm not seeing it in the composition bar chart.

Ugh, sorry. I've not managed to cut a new release yet. On my todo list.

**Comment by DavidJFelix** [comment]
no problem, just checking in

**Pull request merged**
