### PR TITLE
Add Carp language

### PR DESCRIPTION
**Pull request by hellerve**
This PR adds syntax support for the [Carp programming language](https://github.com/carp-lang/carp/)!

I’m guessing Carp is not popular enough as of yet (Harvest shows a measly 63 unique repositories by just 23 people); people seem to be excited about the language, but not using it enough just yet! I’ve done the work for adding the language anyway, understanding that you’ll defer merging this.

## Checklist:
- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      -  https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3Acarp+KEYWORDS+NOT+nothack
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s): [from the Carp compiler source](https://github.com/carp-lang/Carp/tree/master/examples)
    - Sample license(s): APache
  - [x] I have included a syntax highlighting grammar: https://github-lightshow.herokuapp.com/
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

Cheers

### CODE REVIEW

**Comment by hellerve** [comment]
Also, I’m open for any and all color suggestions. The current one doesn’t work apparently, which is fine by me.

**Comment by hellerve** [comment]
Update: We’ve moved up to 69 repos and 27 users. Still measly, but 6 repos and 4 people isn’t too bad for 9 days!

**Comment by pchaigno** [comment]
Thanks for the pull request @hellerve! I'll add this to #4219 to monitor usage.

**Comment by hellerve** [comment]
Alright, then I’ll stop coming back to check usage every once in a while :) Thanks!

**Comment by pchaigno** [comment]
Closing in favor of #4219. We'll monitor the popularity of the extension there.

**Pull request closed without merging**
