### PR TITLE
Cut release v4.3.0

### PR DESCRIPTION
**Pull request by arfon**
Changes since v4.2.6: https://github.com/github/linguist/compare/v4.2.6...561e62607020bc2eba696658eae504cdea625f09

Merged Pull Requests since v4.2.6:

Recommend updating grammars when releasing: https://github.com/github/linguist/pull/1963
Add missing ^ in regexp for Frege heuristic: https://github.com/github/linguist/pull/1970
Add a language grammar for Nit: https://github.com/github/linguist/pull/1973
Update Hy support by adding a reference to an Atom grammar: https://github.com/github/linguist/pull/1974
Grammar for HTTP highlighting: https://github.com/github/linguist/pull/1975
Use path for Generated? detection: https://github.com/github/linguist/pull/1976
Grammar for AutoHotKey: https://github.com/github/linguist/pull/1977
More CMake samples: https://github.com/github/linguist/pull/1978
New grammar for Racket: https://github.com/github/linguist/pull/1982
Add *.sagews to languages.yml: https://github.com/github/linguist/pull/1989
Support for web ontology language (OWL): https://github.com/github/linguist/pull/1995
Add FXML to languages.yml: https://github.com/github/linguist/pull/1996
Add pike interpreter for Pike: https://github.com/github/linguist/pull/1998
Heuristics for .cs files: C# and Smalltalk: https://github.com/github/linguist/pull/2003
Add Rexfile: https://github.com/github/linguist/pull/2005

### CODE REVIEW

**Comment by arfon** [comment]
/ cc @aroben & @bkeepers

**Comment by larsbrinkhoff** [comment]
Is this live now?

Is there a way to check which version of Linguist is running on GitHub?

**Comment by arfon** [comment]
No, it's not live yet sorry. Some of the changes to the internal API are causing difficulties with our search code. I'm probably not going to get a chance to look at this until tomorrow at the earliest.

> Is there a way to check which version of Linguist is running on GitHub?

It's almost always going to be the most recent release here (currently `v4.2.6`: https://github.com/github/linguist/releases

**Comment by larsbrinkhoff** [comment]
Thanks!

**Comment by arfon** [comment]
@larsbrinkhoff most of these changes are live now in https://github.com/github/linguist/pull/2015

**Pull request closed without merging**
