### PR TITLE
Add Language Skript (2)

### PR DESCRIPTION
**Pull request by BlockArchitech**
## Description

Add support for the language 'Skript'
## Checklist:
- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?q=extension%3Ask&type=Code - So I'd use cd.github.com, however no matter what language I choose it's not returning any results, so here's the standard GitHub search.
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  
  - [x] I have included a syntax highlighting grammar: https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fgithub.com%2FSkriptLang%2Fskript-grammar%2Fblob%2Fmain%2Fsource.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2FSkriptLang%2Fskript-grammar%2Fblob%2Fmain%2Ftest.sk&code=
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

## Note
This shouldn't be merged at the moment as the official Skript grammar isn't fully finished yet. It is however in a useable state, and using linguist from this fork does work.

Please See: https://github.com/SkriptLang/skript-grammar for more information

(cc: @Moderocky)

### CODE REVIEW

**Comment by BlockArchitech** [comment]
No idea what `cached dependency record not found` means, can someone please explain this?

**Comment by ADawesomeguy** [comment]
I think you might need to run `bundle exec licensed cache -c vendor/licenses/config.yml` but don't quote me.

**Comment by BlockArchitech** [comment]
This worked! Thanks!

**Comment by ADawesomeguy** [comment]
No problem! I had the same issue when submitting a language and one of the maintainers was kind enough to show me the command, otherwise I never would’ve known either 😁

**Comment by BlockArchitech** [comment]
Alright, grammar seems to be in a relatively working state, I'm going to flag this for review but I doubt it has enough popularity.

**Comment by BlockArchitech** [comment]
Yeah, don't think this grammar will ever be updated.

**Pull request closed without merging**
