### PR TITLE
Update languages.yml with *.sagews

### PR DESCRIPTION
**Pull request by davidabian**
Please mark *.sagews files as Sage. Thanks in advance.

### CODE REVIEW

**Comment by pchaigno** [comment]
@davidabian Do you have an example of `.sagews` file you could add as a sample?

For reviewers: I found [more than 500 samples on GitHub](https://github.com/search?utf8=%E2%9C%93&q=extension%3Asagews+if+OR+for+OR+def&type=Code&ref=searchresults) and seeing the extension it's unlikely that it will collide with another language.

**Comment by davidabian** [comment]
.sagews files (**Sage** **W**ork**s**heets) have the same features of .sage ones and, actually, every single file for Sage is based on Python. As you can read on [Wikipedia] (https://en.wikipedia.org/wiki/Sage_%28mathematics_software%29):

> Sage uses the Python programming language, supporting procedural, functional and object-oriented constructs.

Some examples can be found on my [personal Sage repository] (https://github.com/davidabian/sage).

**Comment by pchaigno** [comment]
> Some examples can be found on my personal Sage repository.

@davidabian Perfect! Could you add one of these in a `samples/Sage/` directory in your branch `patch-1` (this pull request)?

**Comment by davidabian** [comment]
@pchaigno Done.

**Comment by arfon** [comment]
:+1: looks good. Thanks for your contribution @davidabian. Also, please note, it will probably be another couple of weeks before this change is live on GitHub.

**Pull request merged**
