### PR TITLE
Auto increment language_id to avoid duplicates

### LINKED ISSUE #3211: Keep a MAX_LANGUAGE_ID somewhere to prevent language_id dups
As @TwP wrote in https://github.com/github/linguist/pull/3205#issuecomment-246774874, we need to:

> Regarding language ID reuse, keep a MAX_LANGUAGE_ID constant somewhere in the codebase would help ensure that language IDs are not reused in the scenario laid out by @pchaigno. The requirement being that all new language IDs must be larger than MAX_LANGUAGE_ID, and then increment MAX_LANGUAGE_ID after the new language is added.

Adding this here to remind me to do this.

### PR DESCRIPTION
**Pull request by pchaigno**
Fixes #3211.

Anyone has a better idea on where/how to store the `NEXT_LANGUAGE_ID`? The current way (in `languages.yml`) requires a few modifications to `language.rb` and tests, which I don't really like.

/cc @arfon @TwP

### CODE REVIEW

**Comment by arfon** [comment]
> Anyone has a better idea on where/how to store the `NEXT_LANGUAGE_ID`?

What about putting it in https://github.com/github/linguist/blob/master/lib/linguist/language.rb?

**Comment by pchaigno** [comment]
It might be an appropriate place to have this variable but I'm not sure it's a good place to have a generated value. `set-language-ids` will actually need to update the value in the file every time a language is added. This might be off-putting for users. I'm worried we'd end up with many pull requests where the `NEXT_LANGUAGE_ID` value isn't updated, either because the user didn't commit it or because they made the id change manually.

I don't have a strong opinion one way or the other, both solutions seem non-ideal to me. I'll go with the one that seems best to you.

**Comment by arfon** [comment]
> This might be off-putting for users. I'm worried we'd end up with many pull requests where the `NEXT_LANGUAGE_ID` value isn't updated, either because the user didn't commit it or because they made the id change manually.

So I actually think this is probably a good thing. It's a crappy thing from a contributor perspective but a good thing for maintainers as we want to be really careful about edits to these ids. Seeing the tests fail and then asking folks to update `NEXT_LANGUAGE_ID` seems like an OK workflow?

**Comment by pchaigno** [comment]
I'm not sure I explained myself properly. With both options, currently, if the contributors don't update `NEXT_LANGUAGE_ID` we won't see any test failing. We can/should add a test for that, but then this is something we can do whatever is the option we choose. Basically, I'm afraid with option 2 we see more often the tests failing because the contributors forgot to update the value...

**Comment by arfon** [comment]
> We can/should add a test for that, but then this is something we can do whatever is the option we choose.

Right, sorry, missed this.

> Basically, I'm afraid with option 2 we see more often the tests failing because the contributors forgot to update the value...

Yeah, although I really don't like all the exception logic that we currently have in this PR for skipping the `NEXT_LANGUAGE_ID: 422` key.

@bkeepers - do you have any suggestions here for what might be a better approach?

**Comment by bkeepers** [comment]
> @bkeepers - do you have any suggestions here for what might be a better approach?

I haven't been following along here very closely lately, so sorry if this has been discussed. One idea would be to avoid storing `NEXT_LANGUAGE_ID` at all and just randomly generating the ID when adding a new language. With a big enough integer, collisions should rarely happen. Code should have assertions that the ID is unique so it will fail if there ever is a collision.

Another variation of this would be to generate the ID off a hash of the original language name. 

```ruby

>> "Ruby".to_i(36)
=> 1299022
>> "Python".to_i(36)
=> 1570137287

"Ruby".hash
=> -1156080005327119894
"Python".hash
=> -2846398625042276484
```

I'm not sure the best method for hashing a string into an integer with the least likelihood of collisions, but I'm sure there's something straight forward.

**Comment by Alhadis** [comment]
> I'm not sure the best method for hashing a string into an integer with the least likelihood of collisions, but I'm sure there's something straight forward.

What about using the contents of *the entire file*? A script can still check for collisions, but their likelihood is drastically reduced.

**Comment by arfon** [comment]
Thanks for the suggestions @bkeepers and @Alhadis. Changing any of these language ids is contingent on us _not_ having used these ids yet in our search indexes. @TwP has the grant reindexing started/happened yet?

**Comment by bkeepers** [comment]
@arfon the existing ones could stay the same. But going forward it could generate and save random IDs instead of incrementing IDs.

**Comment by arfon** [comment]
> @arfon the existing ones could stay the same. But going forward it could generate and save random IDs instead of incrementing IDs.

Good point. Hadn't thought of that 😁

**Comment by pchaigno** [comment]
I don't know why, I was convinced we discussed this solution and dismissed it before :/

A hash or random id would certainly help reduce the number of collisions between pull requests.

> _Edit:_ you'd need to call `.abs` on those last two results and maybe modulo them to a smaller integer.

@bkeepers Is there a limit on the maximum value for the id??

**Comment by TwP** [comment]
> @bkeepers Is there a limit on the maximum value for the id??

The maximum value is a signed int32, and we should keep the values positive ... so it is `2^31 - 1`.

**Comment by arfon** [comment]
> What about using the contents of the entire `languages.yml`? A script can still check for collisions, but their likelihood is drastically reduced.

Yeah, that's a neat idea. What do you think @pchaigno?

> @arfon the existing ones could stay the same. But going forward it could generate and save random IDs instead of incrementing IDs.

I checked with @TwP today and the currently `language_id` values are already in our search indexes and so we're only talking about generating new ids here.

@pchaigno would you be able to update this PR with @Alhadis' suggestion (or a similar approach)?

**Comment by pchaigno** [comment]
I implemented @bkeepers' suggestion at #3284. Not sure why, but I as convinced we had already discussed and ruled out this idea in the previous PR :/

**Pull request closed without merging**
