### PR TITLE
Added Beluga language

### PR DESCRIPTION
**Pull request by marcelgoh**
Adding support for [Beluga](https://www.cs.mcgill.ca/~complogic/beluga/), a functional programming language designed for reasoning about formal systems.
## Description

Added grammar files, samples, and added Beluga to list of languages.
## Checklist:

- [x] **I am adding a new language.**
  - [ ] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  `.bel`: [~500 results with keyword "rec"](https://github.com/search?q=extension%3Abel+rec)
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - `jpath.bel`: [Link](https://github.com/Beluga-lang/Beluga/blob/master/examples/higher-order/jpath.bel)
    - Sample license(s):
      - `jpath.bel`: [GPL 3.0](https://github.com/Beluga-lang/Beluga/blob/master/LICENSE)
  
  - [x] I have included a syntax highlighting grammar: [Link to Lightshow](https://github-lightshow.herokuapp.com/?utf8=✓&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fgithub.com%2Fmarcelgoh%2Fbeluga-syntax%2Fblob%2Fmaster%2FBeluga.tmbundle%2FSyntaxes%2FBeluga.tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2FBeluga-lang%2FBeluga%2Fblob%2Fmaster%2Fexamples%2Ftyped-eval%2Ftpeval.bel&code=)
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

### CODE REVIEW

**Comment by pchaigno** [comment]
> I apologise for the needlessly many commits.

No worries. We're going to squash them at merge-time anyway.

> Would there be a simple fix for this?

Yes, you need to add a real-world usage sample as per the contribution guidelines.

**Comment by marcelgoh** [comment]
> > I apologise for the needlessly many commits.
> 
> No worries. We're going to squash them at merge-time anyway.
> 
> > Would there be a simple fix for this?
> 
> Yes, you need to add a real-world usage sample as per the contribution guidelines.

Hi! Thanks for considering my pull request! I think I managed to fix the problems I had earlier and the most recent commit seems to build.

**Comment by marcelgoh** [comment]
Would it be possible to add a colour for Beluga, as it is a programming language? What is the best way to choose a colour that doesn't conflict with others? I wasn't sure so I left it blank.

**Comment by marcelgoh** [comment]
> Using [Harvester](https://github.com/Alhadis/Harvester) and the search query you provided, I counted only 12 repositories among 10 users. That is not enough to meet our usage requirement of hundreds of repositories.
> 
> How old is Beluga? Are there any reason to believe usage will increase exponentially in the next months?

Work on Beluga has been ongoing since 2009. While the current usage is not enormous, I believe that exposure for Beluga will only increase in the future, as more and more languages incorporate features that the creators of Beluga have been working on (e.g. dependent types, contexts). And because the .bel extension is not used by any other programming languages, I thought it would be a safe addition to GitHub's languages.

**Comment by pchaigno** [comment]
Okay. Let's reopen this pull request once usage is in the hundreds. Don't hesitate to ping me if you think we're there and would like me to run Harvester again.

> And because the .bel extension is not used by any other programming languages, I thought it would be a safe addition to GitHub's languages.

That requirement stands for all extensions and languages, regardless of conflicts. If the extension was `.beluga` I might be less wary of adding it and would likely require less repositories than usual. But there's also a maintenance cost to any new extension and any new language, and we have to take that into account.

**Comment by marcelgoh** [comment]
> Okay. Let's reopen this pull request once usage is in the hundreds. Don't hesitate to ping me if you think we're there and would like me to run Harvester again.

Sounds good. Thanks for the help!!

**Pull request closed without merging**
