### PR TITLE
New repository for TypeScript grammar

### PR DESCRIPTION
**Pull request by pchaigno**
The Microsoft TypeScript grammar for Sublime Text is now hosted at [Microsoft/TypeScript-TmLanguage](https://github.com/Microsoft/TypeScript-TmLanguage). See Microsoft/TypeScript-Sublime-Plugin#610 for details.

### CODE REVIEW

**Comment by pchaigno** [comment]
I had to whitelist the MIT license the new repository uses.

I don't understand the new error... @Alhadis Any idea?

**Comment by Alhadis** [comment]
Which new error? This?

> The command "script/licensed verify" exited with 1.
> nothing changed, not updating cache
> Done. Your build exited with 1.

**Comment by pchaigno** [comment]
Yes. I'm guessing it has to do with the warning above:
```
Warnings:

vendor/licenses/grammar/TypeScript-TmLanguage.txt:

  - license needs reviewed: other.

287 dependencies checked, 1 warnings found.
```

**Comment by Alhadis** [comment]
Oh, I've seen that numerous times... I thought you kicked up something else.

No clue, sir. :( The license-recognition stuff is well outside my field of understanding.

**Comment by lildude** [comment]
This is going to be the same issue we saw in https://github.com/github/linguist/pull/3782 and should also be resolved when I update licensed (once the pending PR is merged). 

:+1: to manually setting the license to MIT in the license file.

**Comment by pchaigno** [comment]
> :+1: to manually setting the license to MIT in the license file.

Done.

**Pull request merged**
