### PR TITLE
Grammar for AutoIt from Sublime Text package

### PR DESCRIPTION
**Pull request by pchaigno**
This pull request adds a grammar for AutoIt ([demonstration on Lightshow](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgithub.com%2FAutoIt%2FSublimeAutoItScript%2Fblob%2Fmaster%2FAutoIt.tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2FTheDcoder%2FIRC-Bot-Base-for-AutoIt%2Fblob%2Fmaster%2FBot.au3&code=)).

/cc @TheDCoder

### CODE REVIEW

**Comment by TheDcoder** [comment]
#779

**Comment by pchaigno** [comment]
Looks like the Travis build is failing because there isn't a `sublime-autoit.txt` license file in `vendor/licenses/`.
@arfon Is there a new additional step required when adding a grammar?

**Comment by TheDcoder** [comment]
Issue: #627

**Comment by arfon** [comment]
> @arfon Is there a new additional step required when adding a grammar?

@pchaigno - yeah, there is sorry. You need to run `script/licensed`. At the moment this generates a lot of unnecessary changes to license files so if you run this make sure you only add the new file that's generated for this grammar.

**Comment by pchaigno** [comment]
@arfon Done :zap:

**Comment by TheDcoder** [comment]
Can be merged now! :D

**Comment by arfon** [comment]
Thanks for this contribution @pchaigno :zap:. This will be live in the next release of Linguist (likely sometime in the next week).

**Comment by TheDcoder** [comment]
@arfon Actually, I was the one who identified the issue but I did not have the skill to create a PR lol.

**Pull request merged**
