### PR TITLE
Fix Nixinova submodule issues

### PR DESCRIPTION
**Pull request by am11**
## Description

Nixinova submodule was manually added without using script, which results in it getting deleted from .gitmodules and grammers.yml files when other languages are added or deleted

<del>Also added a second positional argument in script/add-grammer, to override the repository name. In this case repo name is `tmLanguage` and the intended name is `Nixinova-tmLanguage`.</del>

Exact command used (after deinit the exiting submodule):
```sh
$ script/add-grammar https://github.com/Nixinova/tmLanguage Nixinova-tmLanguage
```

Fixes https://github.com/github/linguist/issues/5291

## Checklist:

- [x] **I am updating a grammar submodule**

### CODE REVIEW

**Comment by Nixinova** [comment]
A more descriptive title for this PR would be `Add optional output folder argument to script/add-grammar`.

**Comment by Alhadis** [comment]
> Also added a second positional argument in script/add-grammer, to override the repository name. In this case repo name is `tmLanguage` and the intended name is `Nixinova-tmLanguage`.

Erh, why not rename your repository to `nixinova-linguist-grammars` instead? Or `nixinova-grammars`, `nixinova-textmate`, etc… Moreover, this would break consistency between a repository's name and its submodule's name.

**Comment by am11** [comment]
> why not rename your repository to nixinova-linguist-grammars instead?

That's what I suggested to him in the original issue, twice.

> A more descriptive title for this PR would be

Not really, as I mentioned in the issue and in the description, the main problem with current master is that you did not use script/add-grammar and now it is causing problems for others.

**Comment by am11** [comment]
> why not rename your repository to nixinova-linguist-grammars instead?

That's what I suggested to him in the original issue, twice.

> A more descriptive title for this PR would be

Not really, as I mentioned in the issue and in the description, the main problem with current master branch is that when someone tries to add a new grammar, it deletes your grammar because it was not added properly using script/add-grammar script.

When we do try to add your grammar using script/add-grammar script, the linguist compiler gives 10+ fatal errors which were fixed by https://github.com/Nixinova/tmLanguage/pull/4. This PR is potentially updating the submodule to fix the repo state.

**Comment by Nixinova** [comment]
> this would break consistency between a repository's name and its submodule's name.

Well, there aren't any other repos in this called `tmLanguage` so just leaving this as-is would work.

**Comment by lildude** [comment]
Thanks for this @am11. As with @Alhadis, I'm not keen on allowing peeps to break the consistency between a repository's name and its submodule name as used by Linguist as it adds unnecessary complexity when trying to track problems down.

> Well, there aren't any other repos in this called `tmLanguage` so just leaving this as-is would work.

Indeed, however I'd much rather have you rename to a less-generic name which has less risk of clashing or causing confusion.

**Comment by am11** [comment]
@lildude, agreed; that was my first preference as well. I will update the PR when the repo is renamed.

**Comment by Nixinova** [comment]
Okay, fine, renamed my repo

**Review by Nixinova — CHANGES_REQUESTED** [review]
I had changed the repo name again to `Nova.tmLanguage` while you were doing this.

**Comment by am11** [comment]
> I had changed the repo name again to `Nova.tmLanguage` while you were doing this.

or

> I changed my mind (at least) one hour later and renamed again

otherwise timestamps and passing CI make no sense

**Comment by Nixinova** [comment]
It was changed literally 10sec later. See above, at how https://github.com/Nixinova/Nova.tmLanguage/issues/5 is located above your commit.

**Comment by am11** [comment]
Ah must be GH redirects. I committed 51 minutes after your comment https://github.com/github/linguist/pull/5292#issuecomment-811322602, then six CI legs ran.

**Comment by am11** [comment]
> It was changed literally 10sec later.  how Nixinova/Nova.tmLanguage#5 is located above your commit.

image

**Comment by Nixinova** [comment]
Not sure why you deleted your old comment as that would've been what happened.

**Comment by am11** [comment]
It was not relevant to your 10sec comment, which I read after the page refresh. The difference was one hour not 10 sec.

**Comment by lildude** [comment]
@am11 would you mind updating this PR for the final new repo name?

**Comment by lildude** [comment]
I think you need to pull master into your branch as you appear to be missing the NimLime grammar change just merged.

**Review by lildude — APPROVED** [review]
Lovely! Thanks all. 🙇

**Pull request merged**
