### PR TITLE
Add colors to semi-popular languages

### PR DESCRIPTION
**Pull request by phase**
These may not be the most popular, but they are still used a lot here on GitHub, and they deserve a color.

### CODE REVIEW

**Comment by phase** [comment]
`The command "script/travis/before_install" failed and exited with 1 during .` oh noes

**Comment by pchaigno** [comment]
For Travis, it's probably just a temp. failure. It happens sometimes. You can try to re-launch the build by closing/opening the issue.

Have you checked that the new colors don't conflict with [existing ones](http://github.github.io/linguist/)?

**Comment by phase** [comment]
@pchaigno I highly doubt that of the thousands of combinations out there, I made one that is the same as another. I took into account the name & what's it's used for. (Like Crystal is a light blue)

**Comment by pchaigno** [comment]
> I highly doubt that of the thousands of combinations out there, I made one that is the same as another.

Maybe not the exact same but something too close to be easily distinguish on the tiny statistic bar. It happened before so I think it's worth a quick check. It's especially important that it doesn't happen for two languages that are often found together (Makefile and C for instance).

**Comment by arfon** [comment]
Thanks for this @phase. Please do take a look at http://github.github.io/linguist/ to see if these colours are close to existing ones.

**Comment by phase** [comment]
I believe that none are similar to these, but I might have missed one.

**Comment by pchaigno** [comment]
I tested with @gjtorikian's new test from #2298 and it says it's okay too :zap:

**Comment by arfon** [comment]
> I tested with @gjtorikian's new test from #2298 and it says it's okay too :zap:

:+1:

**Comment by phase** [comment]
How long does it take for it to get updated? I was looking at https://github.com/phase/minekraft and the Kotlin still looks grey. When I did this to Diff in #2236, it looked like it was instant.

**Comment by arfon** [comment]
We have to cut a new gem so you probably just got lucky with timing last time :-) 

So to answer your question - this will probably be updated in the next week or so.

**Comment by phase** [comment]
Since this was over 3 years ago, I have no idea! I think it was due to there already being some languages that use black. At the time of this PR, black [wasn't used on the website](http://archive.is/nSbpn) that much.

**Pull request merged**
