### PR TITLE
Use Atom's HTML grammar instead of TextMate's

### PR DESCRIPTION
**Pull request by Alhadis**
This PR replaces the grammar used for HTML highlighting on GitHub.

## Description
This is a follow-up to [`mariozaizar/language-eml#15`](https://github.com/mariozaizar/language-eml/issues/15), where @pchaigno observed jarring error highlights being applied to HTML embedded in another grammar (see [`#4201`](https://github.com/github/linguist/pull/4201#issuecomment-422357959)). The spurious highlights in question are absent when using Atom's HTML grammar for highlighting.

Moreover, Atom's grammar has greatly improved visibility than TextMate's, and is likely to stay updated faster as the HTML spec itself evolves.

## Checklist:
- [x] **I am changing the source of a syntax highlighting grammar**  
  - [Before](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=text.html.basic&grammar_format=cson&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fatom%2Flanguage-html%2Fmaster%2Fgrammars%2Fhtml.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2F&code=)
  - [After](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=cson&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fatom%2Flanguage-html%2Fmaster%2Fgrammars%2Fhtml.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2F&code=)

No real difference in highlighting, apart from when embedded content is involved. Which, unfortunately, is impossible to demonstrate due to technical limitations of Lightshow.

/cc @50Wliu, @mariozaizar

### CODE REVIEW

**Comment by Alhadis** [comment]
Tests are great until you need to update 300+ assertions because a scope was added. 😢

Not to mention they're so painful to write, I actually wrote [an Atom command](https://github.com/Alhadis/.atom/blob/926465ffaba1cee0930f5b8fa3b43f1c4de87521/lib/commands/pull-requests.js#L23-L67) to generate them from a tokenised buffer's contents. Which had the oh-so-clever name of ["Spec-saver"](https://en.wikipedia.org/wiki/Specsavers). 👅

**Comment by Alhadis** [comment]
Build is failing because of [another license issue](https://travis-ci.org/github/linguist/jobs/432787048#L1577-L1578):

~~~
Warnings:
/home/travis/build/github/linguist/vendor/licenses/grammar/language-html.txt:
  - license needs reviewed: other.
310 dependencies checked, 1 warnings found.
The command "script/licensed status" exited with 1.
~~~

Tests passed locally though, so I don't know what's up with that...

**Comment by lildude** [comment]
> Tests passed locally though, so I don't know what's up with that...

The caching of the license hasn't detected the license is MIT so has set it to "other" when caching. The [`script/licensed status`](
https://github.com/github/linguist/blob/972052639a95d95276bc7ab25a68880a6652b263/.travis.yml#L14) test is picking this up.

We know this is MIT so feel free to set it manually in the license file.

**Comment by Alhadis** [comment]
> Copyright (c) 2014 GitHub Inc.

GitHub staff approving the use of GitHub-licensed software for use on GitHub.

Are you sure that's safe?

**Comment by lildude** [comment]
> Are you sure that's safe?

Not at all 😜

**Comment by 50Wliu** [comment]
No objections here!

**Pull request merged**
