### PR TITLE
Update escape_utils requirement to >= 1.1, < 1.3

### PR DESCRIPTION
**Pull request by greysteil**
Updates requirements on [escape_utils](https://github.com/brianmario/escape_utils) to permit the latest version.

Generated on my fork using [Dependabot](https://dependabot.com), if you want to automate this stuff for the future.

### CODE REVIEW

**Comment by lildude** [comment]
Thanks for the PR. Is there any special requirement or need for this newer, yet still restricted, update? 

If so, why the restriction on <1.3?

**Comment by greysteil** [comment]
Figured I knew less about the gem than you do - if you don't trust SemVer on it then I figured I'd keep your gemspec that way! I can update the upper bound to be `2.0` if you want?

**Comment by lildude** [comment]
Thanks, but I'm still curious about if there's a particular reason for this other than it's out of date. 

For context, Linguist is tightly tied to the gem versions used on GitHub.com so updating dependency versions needs to be properly considered.

**Comment by greysteil** [comment]
Was hoping to pull [this commit](https://github.com/brianmario/escape_utils/commit/10098ded5d61c80d4cb2285ab35a05c721df7f2e) into a project I'm working on, and Linguist is blocking me. Can obviously work around it if there are complexities to updating the gemspec here that I hadn't realised.

**Comment by lildude** [comment]
Hmmm that commit was included in escape_utils 1.1.1 which is what Linguist is pulling in already.

**Comment by greysteil** [comment]
Woah, hadn't realised they'd backported that. In that case I guess fine to close this.

**Pull request closed without merging**
