### PR TITLE
Replace haxe-sublime-bundle with haxe-TmLanguage

### PR DESCRIPTION
**Pull request by Gama11**
## Description

This replaces the Haxe grammar from [haxe-sublime-bundle](https://github.com/clemos/haxe-sublime-bundle), which hasn't been updated in a few years and not kept up with new Haxe 4 syntax as result, with [haxe-TmLanguage](https://github.com/vshaxe/haxe-TmLanguage). The grammar is based on the one from haxe-sublime-bundle, but includes a large number of fixes and enhancements. It's also used for the [Haxe VSCode extension](https://marketplace.visualstudio.com/items?itemName=nadako.vshaxe).

To demonstrate the differences, I've picked out a few of haxe-TmLanguage's [test cases](https://github.com/vshaxe/haxe-TmLanguage/tree/master/cases) for the lightshow comparison below.

## Checklist:
- [x] **I am changing the source of a syntax highlighting grammar**
  
  - [Old](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fgithub.com%2Fclemos%2Fhaxe-sublime-bundle%2Fblob%2Fmaster%2FHaxe.tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgist.githubusercontent.com%2FGama11%2Ff62d7d41f68ea3ae3790fa0b4965c1b6%2Fraw%2F450285aa3dae412a1fb170a58654431276497f10%2Fgistfile1.txt&code=)
  - [New](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fgithub.com%2Fvshaxe%2Fhaxe-TmLanguage%2Fblob%2Fmaster%2Fhaxe.tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgist.githubusercontent.com%2FGama11%2Ff62d7d41f68ea3ae3790fa0b4965c1b6%2Fraw%2F450285aa3dae412a1fb170a58654431276497f10%2Fgistfile1.txt&code=)

### CODE REVIEW

**Comment by Gama11** [comment]
It seems Travis is failing for reasons unrelated to my changes?

**Comment by lildude** [comment]
> It seems Travis is failing for reasons unrelated to my changes?

Yup. Looks like a problem building the rugged gem for some reason. Looking into it.

**Comment by lildude** [comment]
CI should pass once https://github.com/github/linguist/pull/4081 has been merged.

**Comment by Gama11** [comment]
Ok, CI is passing now. :)

**Comment by lildude** [comment]
I can't see any problems with this, but will leave it to @pchaigno or @Alhadis to double-check me before I give my final :+1:

**Pull request merged**
