### PR TITLE
Bump Charlock Holmes to 0.7.6

### PR DESCRIPTION
**Pull request by stanhu**

### CODE REVIEW

**Comment by lildude** [comment]
Is there a specific reason for this bump other than 0.7.6 was released three days ago?

**Comment by stanhu** [comment]
It allows charlock_holmes to be compiled against newer icu4c versions (https://github.com/brianmario/charlock_holmes/commit/b8418c4960edfa0735ebb846f1fca8fb4f9674b1). We had some build errors on MacOS due to that.

**Comment by stanhu** [comment]
To be clear, building charlock_holmes 0.7.5 fails badly with icu4c 61.1 due to https://github.com/brianmario/charlock_holmes/issues/126.

The workaround to fix this is:

```
gem install charlock_holmes -v '0.7.5' -- --with-cppflags=-DU_USING_ICU_NAMESPACE=1
```

It'd be helpful to release a new version just with the charlock_holmes package. :)

**Comment by lildude** [comment]
> It'd be helpful to release a new version just with the charlock_holmes package. :)

It's been a while since I last made a release and plan to make one this week or early next, time dependent.

**Comment by Alhadis** [comment]
> The workaround to fix this is:
>
> ~~~console
> gem install charlock_holmes -v '0.7.5' -- --with-cppflags=-DU_USING_ICU_NAMESPACE=1
> ~~~

@stanhu Either that isn't working, or I'm experiencing an unrelated install issue:

~~~
Fetching: charlock_holmes-0.7.5.gem (100%)
Building native extensions with: '--with-cppflags=-DU_USING_ICU_NAMESPACE=1'
This could take a while...
ERROR:  Error installing charlock_holmes:
        ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.3.0/gems/charlock_holmes-0.7.5/ext/charlock_holmes
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -r ./siteconf20180409-40516-18igzuh.rb extconf.rb --with-cppflags=-DU_USING_ICU_NAMESPACE=1
checking for main() in -licui18n... no
checking for main() in -licui18n... yes
checking for unicode/ucnv.h... yes
checking for main() in -lz... yes
checking for main() in -licuuc... yes
checking for main() in -licudata... yes
creating Makefile

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Library/Ruby/Gems/2.3.0/extensions/universal-darwin-17/2.3.0/charlock_holmes-0.7.5/mkmf.log

current directory: /Library/Ruby/Gems/2.3.0/gems/charlock_holmes-0.7.5/ext/charlock_holmes
make "DESTDIR=" clean

current directory: /Library/Ruby/Gems/2.3.0/gems/charlock_holmes-0.7.5/ext/charlock_holmes
make "DESTDIR="
compiling ext.c
compiling encoding_detector.c
compiling converter.c
compiling transliterator.cpp
In file included from transliterator.cpp:1:
In file included from ./common.h:9:
In file included from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/ruby.h:33:
In file included from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/ruby/ruby.h:24:
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/universal-darwin17/ruby/config.h:368:31: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
#define RUBY_ARCH "universal-"RUBY_PLATFORM_OS
                              ^
                               
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/universal-darwin17/ruby/config.h:369:35: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
#define RUBY_PLATFORM "universal."RUBY_PLATFORM_CPU"-"RUBY_PLATFORM_OS
                                  ^
                                   
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/universal-darwin17/ruby/config.h:369:55: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
#define RUBY_PLATFORM "universal."RUBY_PLATFORM_CPU"-"RUBY_PLATFORM_OS

3 errors generated.
make: *** [transliterator.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Library/Ruby/Gems/2.3.0/gems/charlock_holmes-0.7.5 for inspection.
Results logged to /Library/Ruby/Gems/2.3.0/extensions/universal-darwin-17/2.3.0/charlock_holmes-0.7.5/gem_make.out
~~~

Any help? 😢

**Pull request merged**
