### PR TITLE
Add Language: Imba

### PR DESCRIPTION
**Pull request by familyfriendlymikey**
## Checklist:
- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      -  https://github.com/search?q=extension%3Aimba+NOT+nothack&type=Code
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - https://github.com/familyfriendlymikey/game_of_life.imba
    - Sample license(s): MIT
  - [x] I have included a syntax highlighting grammar: https://github.com/familyfriendlymikey/imba-linguist-grammar
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension. (There is no other imba extension.)

### CODE REVIEW

**Comment by familyfriendlymikey** [comment]
Please let me know if there is anything I can do to help get this process going.

**Review by lildude — CHANGES_REQUESTED** [review]
Please replace the OP with the PR template, it's there for a reason. You're also going to need to find a different grammar or add a licence to the grammar as we can't accept grammars without a licence. The CONTRIBUTING.md file has a link to the acceptable licenses.

**Comment by lildude** [comment]
🤔 Try committing the updated submodule and run `bundle exec licensed cache -c vendor/licenses/config.yml`. This should detect the difference in SHAs and download the updated license file.

**Comment by familyfriendlymikey** [comment]
I couldn't get it to work. I didn't want to take up too much of your time so I just decided to redo everything from scratch, and take the opportunity to move the grammar and sample repositories to the official Imba account. Here's the new PR: https://github.com/github/linguist/pull/6130.

I hope you don't mind, I think it should be possible to diff this branch and the new PR so you don't have to read everything from scratch. Thanks again for all the help.

**Comment by lildude** [comment]
Closing in favour of https://github.com/github/linguist/pull/6130

**Pull request closed without merging**
