### PR TITLE
Add languages.yml entry and sample files for OGC Geography Markup Language (#2366)

### PR DESCRIPTION
**Pull request by vog**

### CODE REVIEW

**Comment by pchaigno** [comment]
Why do you want to define it as a new language if it's has the same syntax as XML?

**Comment by vog** [comment]
I'm not so familar with this project, and I'm afraid I don't understand the question. What else should I have done? Simply adding the samples without changing the languages.yml?

**Comment by pchaigno** [comment]
You can just add `.gml` to the list of extensions for XML and move the samples to `samples/XML/`. No need for a new GML entry here ;)

**Comment by vog** [comment]
But then these files would appear in GitHub as "XML" rather than "Geography Markup Language", wouldn't they?

**Comment by pchaigno** [comment]
> But then these files would appear in GitHub as "XML" rather than "Geography Markup Language", wouldn't they?

Yes they would. But, if we add `Geography Markup Language`, since it's a `data` language, it will not be displayed in the statistics of repositories (only in Explore and the search page).
<br/>

> There are so many XML formats out there that it would be confusing to treat them all the same.

It also means we can't define a language for each one of them ;) We have to find a balance.
I'm not from GitHub so I won't be the one taking that decision but I feel like it should be marked as XML because it's only a subset of XML and there aren't that many GML files on GitHub (compared to the [64 million POM files](https://github.com/search?utf8=%E2%9C%93&q=filename%3Apom.xml&type=Code&ref=searchresults) for instance).

**Comment by vog** [comment]
Okay, updated branch.

**Comment by pchaigno** [comment]
Could you also move the samples to `samples/XML/`? Thanks.

**Comment by vog** [comment]
Sorry, forgot that one. Fixed.

**Comment by arfon** [comment]
:+1: thanks for this and the discussion @vog and @pchaigno. This change will go live in the next release of Linguist.

**Pull request merged**
