### PR TITLE
Add '</' to Markdown heuristic.

### LINKED ISSUE #3172: Recognizing as "GCC Machine Description" a repository without language
Hello,

I created a file that has some commands interpreted by an application that I've done.
I've never seen this syntax anywhere and was surprised when the repository was marked as " GCC Machine Description".

[Here's the repository][1].

Is this normal?

[1]:https://github.com/reebr/f-id

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
Possibly also other HTML tags?

EDIT: Changed to just `</` and also include empty files.

Fixes #3172.

### CODE REVIEW

**Comment by Alhadis** [comment]
May as well open that up to include any HTML tag:

```rb
if /(^[-a-z0-9=#!\*\[|])|<\/\w+>/i.match(data)
```

**Comment by larsbrinkhoff** [comment]
Better yet?  Checked GCC sources for `</` in `.md` files.  Found none.

**Comment by nixel2007** [comment]
MD  may use divs for table of contents.

**Comment by larsbrinkhoff** [comment]
@nixel2007 Which "MD"?  Markdown or Machine Descriptions?

**Comment by nixel2007** [comment]
@larsbrinkhoff markdown

**Comment by nixel2007** [comment]
@larsbrinkhoff ah, sorry, i thought, you tried to find `</` in gcc markdown files

**Comment by larsbrinkhoff** [comment]
Changed the regexp and updated the pull request description accordingly.

**Comment by pchaigno** [comment]
It looks like we don't have tests for the `.md` heuristic rule yet. Should we add some?

**Comment by larsbrinkhoff** [comment]
Sure @pchaigno, I added a test.

**Comment by larsbrinkhoff** [comment]
@arfon I can't merge this.  Did something happen with my write access?

**Comment by arfon** [comment]
@larsbrinkhoff do you have 2fa enabled on your account? If not, you may have been kicked out of the `github` org 😊. We turned on [required 2fa](https://help.github.com/articles/requiring-two-factor-authentication-in-your-organization/) last week sometime I think.

**Comment by larsbrinkhoff** [comment]
@arfon No, I don't, so that explains it.

**Comment by arfon** [comment]
Any chance you can turn it on so I can add you back?

**Comment by larsbrinkhoff** [comment]
@arfon Done!

**Comment by arfon** [comment]
> @arfon Done!

👍 thanks. I've just invited you back - I think you'll need to accept the invite but after that your super-powers should be restored.

**Comment by Alhadis** [comment]
You mean you weren't using 2-factor authentication all along? :( Incorrigible.

**Comment by larsbrinkhoff** [comment]
@Alhadis Oh yeah?  I have a Symbian phone.  Take that!

**Pull request merged**
