### PR TITLE
New grammars for Prolog and ECLiPSe 

### PR DESCRIPTION
**Pull request by pchaigno**
This pull request changes the grammar for Prolog.
It also dissociate ECLiPSe (`.ecl` files) from Prolog to apply a distinct grammar.

The new grammar for Prolog is slightly better than the old one in term of scopes:
[Old grammar in Lightshow](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=source.prolog&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fpchaigno%2Fsublimeprolog%2Fmaster%2Fsupport%2FProlog.tmLanguage&grammar_text=&code_source=from-text&code_url=https%3A%2F%2Fraw.githubusercontent.com%2FINSA-Rennes%2FTP-Prolog%2Fff94c3431d11e37bb4fba745e928a1e386f35a46%2FTP7%2Fbaseauto.pro&code=%25+%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D+%0D%0A%25+SECTION+2%0D%0A%25+%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D+%0D%0Afromcity%28City%2C+piece%28NumPiece%2C+Nom%2C+City%29%29%3A-%0D%0A%09piece%28NumPiece%2C+Nom%2C+City%29.%0D%0A%0D%0Ainfospieces%28Nom%2C+Lieu%29%3A-%0D%0A%09piece%28_%2C+Nom%2C+Lieu%29.%0D%0A%0D%0Ainter%28Nom%2C+Lieu%29%3A-%0D%0A%09demandeFournisseur%28Nom%2C+Lieu%29%2C%0D%0A%09fournisseurReference%28_%2C+Nom%2C+Lieu%29.%0D%0A%0D%0Aunion%28Nom%2C+Lieu%29%3A-%0D%0A%09demandeFournisseur%28Nom%2C+Lieu%29.%0D%0Aunion%28Nom%2C+Lieu%29%3A-%0D%0A%09fournisseurReference%28_%2C+Nom%2C+Lieu%29%2C%0D%0A%09not%28demandeFournisseur%28Nom%2C+Lieu%29%29.%0D%0A%0D%0Adiff%28Nom%2C+Lieu%29%3A-%0D%0A%09demandeFournisseur%28Nom%2C+Lieu%29%2C%0D%0A%09not%28fournisseurReference%28_%2C+Nom%2C+Lieu%29%29.%0D%0A%0D%0Aprodcart%28uplet%28NumFourn1%2C+Nom%2C+Ville%2C+NumFourn2%2C+Piece%2C+Quantite%29%29%3A-%0D%0A%09fournisseurReference%28NumFourn1%2C+Nom%2C+Ville%29%2C%0D%0A%09livraison%28NumFourn2%2C+Piece%2C+Quantite%29.%0D%0A%0D%0Ajointure%28uplet%28NumFourn%2C+Nom%2C+Ville%2C+Piece%2C+Quantite%29%29%3A-%0D%0A%09fournisseurReference%28NumFourn%2C+Nom%2C+Ville%29%2C%0D%0A%09livraison%28NumFourn%2C+Piece%2C+Quantite%29.%0D%0A%0D%0AjointureSelect%28uplet%28NumFourn%2C+Nom%2C+Ville%2C+Piece%2C+Quantite%29%29%3A-%0D%0A%09jointure%28uplet%28NumFourn%2C+Nom%2C+Ville%2C+Piece%2C+Quantite%29%29%2C%0D%0A%09Quantite+%3E+350.%0D%0A%0D%0AjointureSelect2%28uplet%28NumFourn%2C+Nom%2C+Ville%2C+Piece%2C+Quantite%29%29%3A-%0D%0A%09livraison%28NumFourn%2C+Piece%2C+Quantite%29%2C%0D%0A%09Quantite+%3E+350%2C%0D%0A%09fournisseurReference%28NumFourn%2C+Nom%2C+Ville%29.) - [New grammar in Lightshow](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fpchaigno%2Fsublimeprolog%2Fmaster%2Fsupport%2FProlog.tmLanguage&grammar_text=&code_source=from-text&code_url=https%3A%2F%2Fraw.githubusercontent.com%2FINSA-Rennes%2FTP-Prolog%2Fff94c3431d11e37bb4fba745e928a1e386f35a46%2FTP7%2Fbaseauto.pro&code=%25+%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D+%0D%0A%25+SECTION+2%0D%0A%25+%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D+%0D%0Afromcity%28City%2C+piece%28NumPiece%2C+Nom%2C+City%29%29%3A-%0D%0A%09piece%28NumPiece%2C+Nom%2C+City%29.%0D%0A%0D%0Ainfospieces%28Nom%2C+Lieu%29%3A-%0D%0A%09piece%28_%2C+Nom%2C+Lieu%29.%0D%0A%0D%0Ainter%28Nom%2C+Lieu%29%3A-%0D%0A%09demandeFournisseur%28Nom%2C+Lieu%29%2C%0D%0A%09fournisseurReference%28_%2C+Nom%2C+Lieu%29.%0D%0A%0D%0Aunion%28Nom%2C+Lieu%29%3A-%0D%0A%09demandeFournisseur%28Nom%2C+Lieu%29.%0D%0Aunion%28Nom%2C+Lieu%29%3A-%0D%0A%09fournisseurReference%28_%2C+Nom%2C+Lieu%29%2C%0D%0A%09not%28demandeFournisseur%28Nom%2C+Lieu%29%29.%0D%0A%0D%0Adiff%28Nom%2C+Lieu%29%3A-%0D%0A%09demandeFournisseur%28Nom%2C+Lieu%29%2C%0D%0A%09not%28fournisseurReference%28_%2C+Nom%2C+Lieu%29%29.%0D%0A%0D%0Aprodcart%28uplet%28NumFourn1%2C+Nom%2C+Ville%2C+NumFourn2%2C+Piece%2C+Quantite%29%29%3A-%0D%0A%09fournisseurReference%28NumFourn1%2C+Nom%2C+Ville%29%2C%0D%0A%09livraison%28NumFourn2%2C+Piece%2C+Quantite%29.%0D%0A%0D%0Ajointure%28uplet%28NumFourn%2C+Nom%2C+Ville%2C+Piece%2C+Quantite%29%29%3A-%0D%0A%09fournisseurReference%28NumFourn%2C+Nom%2C+Ville%29%2C%0D%0A%09livraison%28NumFourn%2C+Piece%2C+Quantite%29.%0D%0A%0D%0AjointureSelect%28uplet%28NumFourn%2C+Nom%2C+Ville%2C+Piece%2C+Quantite%29%29%3A-%0D%0A%09jointure%28uplet%28NumFourn%2C+Nom%2C+Ville%2C+Piece%2C+Quantite%29%29%2C%0D%0A%09Quantite+%3E+350.%0D%0A%0D%0AjointureSelect2%28uplet%28NumFourn%2C+Nom%2C+Ville%2C+Piece%2C+Quantite%29%29%3A-%0D%0A%09livraison%28NumFourn%2C+Piece%2C+Quantite%29%2C%0D%0A%09Quantite+%3E+350%2C%0D%0A%09fournisseurReference%28NumFourn%2C+Nom%2C+Ville%29.)

The new package also contains a grammar for ECLiPSe.
ECLiPSe is a superset of Prolog which adds a few new constructs and functions.
[ECLiPSe syntax with Prolog grammar in Lightshow](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Falnkpa%2Fsublimeprolog%2Fmaster%2Fsupport%2FProlog.tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fgithub%2Flinguist%2Fmaster%2Fsamples%2FProlog%2For-constraint.ecl&code=)
[ECLiPSe syntax with dedicated grammar in Lightshow](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Falnkpa%2Fsublimeprolog%2Fmaster%2Fsupport%2FECLiPSe%2520Prolog.tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fgithub%2Flinguist%2Fmaster%2Fsamples%2FProlog%2For-constraint.ecl&code=)

### CODE REVIEW

**Comment by arfon** [comment]
:+1: awesome. Thanks @pchaigno

**Comment by arfon** [comment]
Before I merge - should we have a sample file here too?

**Comment by pchaigno** [comment]
I already have one in `samples/ECLiPSe/` (it was in `samples/Prolog/` before). Do you think I should add another one?

**Comment by arfon** [comment]
screen shot 2015-08-19 at 9 43 23 pm

Gah, sorry missed this :point_up:. This is good as-is.

**Pull request merged**
