### PR TITLE
Add CAP CDS language

### PR DESCRIPTION
**Pull request by manwithafox**
add CAP CDS language

## Checklist:
- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      - https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3Acds+entity+NOT+nothack
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - https://github.com/SAP-samples/cloud-cap-samples/blob/main/bookshop/db/schema.cds
      - https://github.com/SAP-samples/cloud-cap-samples/blob/main/bookshop/srv/admin-service.cds
      - https://github.com/SAP-samples/cloud-cap-samples/blob/main/bookshop/srv/cat-service.cds
      - https://github.com/SAP-samples/cloud-cap-samples/blob/main/bookshop/srv/user-service.cds
    - Sample license(s): Apache License 2.0
  - [x] I have included a syntax highlighting grammar: https://github.com/SAP/cds-textmate-grammar
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

### CODE REVIEW

**Comment by manwithafox** [comment]
@lildude Hi Colin
not sure how this PR gets reviewed - it's my first one. I see `linguist` as reviewer but nothing has happened so far.
Then I looked at other recent PRs and saw your name. Maybe you could review this? Would be great.
Best, Christian

**Comment by manwithafox** [comment]
@Alhadis
@larsbrinkhoff
@lildude (GitHub staff)
@pchaigno

Hi, could anyone of you pls review this PR? Thanks a lot.

**Comment by lildude** [comment]
There is no rush as these changes won't take effect until the next release is made. I'm really busy at the moment so can't dedicate much time to Linguist, but will get to it... eventually. Please be patient.

**Comment by manwithafox** [comment]
Ok. Thanks a lot for clarification. I just wanted to make sure that I didn't missed anything on my side that prevents the process to continue.

Cheers

**Comment by lildude** [comment]
> I just wanted to make sure that I didn't missed anything on my side that prevents the process to continue.

You'll find out when I review 😉. Assuming all tests pass (I assumed you've checked this locally already), you should be good. I've approved the test run in the mean time.

**Review by lildude — CHANGES_REQUESTED** [review]
Looks like a legit failure because you've forgotten to commit and put the change to .gitmodules after adding the grammar.

**Comment by manwithafox** [comment]
> Looks like a legit failure because you've forgotten to commit and put the change to .gitmodules after adding the grammar.

Done.

**Comment by lildude** [comment]
Whoops, looks like it's still not right:

```
[644](https://github.com/github/linguist/runs/6172460116?check_suite_focus=true#step:4:644)
Error updating vendor/grammars/cds-textmate-grammar
[645](https://github.com/github/linguist/runs/6172460116?check_suite_focus=true#step:4:645)
error: pathspec 'vendor/grammars/cds-textmate-grammar' did not match any file(s) known to git
```

**Comment by lildude** [comment]
I've just pushed a commit to fix it.

**Comment by manwithafox** [comment]
Thanks a lot!

**Comment by manwithafox** [comment]
Re-requested review.
(There was a pending change request that should be ok.)

**Review by lildude — APPROVED** [review]

**Pull request merged**
