### PR TITLE
Add the Solidity language without an associated extension

### PR DESCRIPTION
**Pull request by frangio**
As discussed in #2634 we can't associate the `.sol` extension with Solidity until the `not-a-language` feature is implemented.

Meanwhile, though, the language should be included in Linguist so that repositories can manually set the language via `.gitattributes`.

### CODE REVIEW

**Comment by veox** [comment]
What a coincidence! I've just decided to revisit this ([WIP repo/branch](https://github.com/veox/linguist/tree/add-solidity), no PR yet).

Decided to use [caktux/language-ethereum](https://github.com/caktux/language-ethereum) as grammar vendor there, but there doesn't seem to be much difference to davidhq/SublimeEthereum proposed here, when trying with [Lightshow](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgithub.com%2Fdavidhq%2FSublimeEthereum%2Fblob%2Fmaster%2FSolidity.tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fveox%2Flinguist%2Fblob%2F894bae2d7bfe80165aa69f6da2004ff8f94ed396%2Fsamples%2FSolidity%2Fpygments-example.sol&code=).

The provided examples seem to be from the ethereum.org website examples [e.g. the Crowdsale contract](https://github.com/ethereum/ethereum-org/blob/master/views/content/crowdsale.md#the-code).

Note that the ethereum-org repo is [blanket-licensed under GPLv3](https://github.com/ethereum/ethereum-org/blob/master/LICENSE), and there doesn't seem to be an exception for examples. This might not fit Linguist.

For that reason, I would have included [my own example](https://github.com/veox/linguist/commit/894bae2d7bfe80165aa69f6da2004ff8f94ed396) instead, which was specifically written to avoid licensing trouble.

**Comment by frangio** [comment]
@veox Awesome! Great thinking with the licensing issue.

Regarding the grammar choice, I just took the #2634 PR and removed the `.sol` extension so I haven't looked into it. However, caktux/language-ethereum is just an Atom port of davidhq/SublimeEthereum so they are basically the same.

Have you read the discussion in #2634? I created this PR because Linguist won't merge the language with the `.sol` extension associated. A heuristic is apparently not enough.

**Comment by veox** [comment]
@frangio yup, I've read PR #2634, and have submitted PR #3560, trying to take the notes into account. Maybe I'm naive, but I think sufficient classification is possible, and a `.gitattributes` in every Solidity repo won't be necessary.

**Comment by frangio** [comment]
AFAIU there is a deeper issue which is that many files on GitHub have a `.sol` extension yet they don't correspond to any language. This cannot be solved by a heuristic currently, because a heuristic returns a language, and in those cases it should report that there is no corresponding language. This is what is meant by the `not-a-language` feature @pchaigno mentions. My intention was to have the `.gitattributes` workaround available until this feature is implemented.

I may be willing to implement the feature but I've been waiting for input from the maintainers on the Solidity related PRs to ask what they have in mind. There's not even a tracking issue for it as far as I can tell.

**Comment by pchaigno** [comment]
If you can update this pull request, I'm 👍 with this approach. Might be easier to start from scratch though, lots of things changed since April.

**Comment by veox** [comment]
@frangio You're welcome to use my [`pygments-example.sol`](https://github.com/veox/linguist/blob/f9e7a097f8d41d13cf94295f8db0206627306859/samples/Solidity/pygments-example.sol) if you wish. :)

-----

Perhaps OT: that example intentionally has an unclosed comment open at the end of the file, meaning it needs modification prior to compiling. Otherwise, I've tried to include as much weird syntax as possible, to aid in highlighter development.

It is also not a "financial" application like `crowdsale.sol` is, which might alleviate some legal concerns.

**Comment by frangio** [comment]
Closed in favor of the updated #3755.

**Pull request closed without merging**
