### PR TITLE
Improve CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by mihaigalos**
## Description

This PR makes it clearer how to install `bundle` if not already present on the system.

## Checklist:

- [ ] **I am associating a language with a new file extension.**
  - [ ] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      
      - https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am adding a new language.**
  - [ ] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a syntax highlighting grammar: [URL to grammar repo]
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

- [ ] **I am fixing a misclassified language**
  - [ ] I have included a new sample for the misclassified language:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am changing the source of a syntax highlighting grammar**
  - Old: [URL to grammar repo]
  - New: [URL to grammar repo]

- [ ] **I am updating a grammar submodule**
  

- [ ] **I am adding new or changing current functionality**
  
  - [ ] I have added or updated the tests for the new or changed functionality.

- [ ] **I am changing the color associated with a language**
  
  - [ ] I have obtained agreement from the wider language community on this color change.
    - [URL to public discussion]
    - [Optional: URL to official branding guidelines for the language]

### CODE REVIEW

**Review by Alhadis — COMMENTED** [review]
This says the exact same thing, only with more words.

**Comment by mihaigalos** [comment]
> This says the exact same thing, only with more words.

It also gives instructions how to install `bundle` some prime-time instead of an afterthought.
Would have resolved a long conversation in the referenced PR easily.

**Comment by Alhadis** [comment]
The current documentation already lists Bundler as a [dependency](https://github.com/github/linguist/blob/f3f5de6288cd7b09eabc5a3b26df9c13add5a2bc/CONTRIBUTING.md):

> [Bundler](https://bundler.io/) v1.10.0 or newer is required for installing the Ruby gem dependencies.

Also, the line you've changed explains how to _upgrade_ Bundler, not install it. You've changed the meaning of this part entirely (this contradicts my earlier assessment, before I understood the affected section's context better).

**Comment by mihaigalos** [comment]
Feel free to improve or stop trolling.

**Pull request closed without merging**
