### PR TITLE
Add support for Cloud Firestore Security Rules

### PR DESCRIPTION
**Pull request by Alhadis**
This PR adds **Cloud Firestore Security Rules** (hereafter just "**Firestore Rules**") to the list of recognised languages on GitHub.com.

## Description
A user [unknowingly](https://github.com/file-icons/atom/issues/726) brought the language to my attention when he asked about adding Firebase's icon to `firebase.rules` files. Did some investigation, and found [~2,091 search results](https://github.com/search?q=filename%3Afirestore.rules+NOT+nothack&type=Code) for files named `firebase.rules`. I'm not sure if there are other names we should concern ourselves with. The contributor who brought this format to my attention [said](https://github.com/file-icons/atom/issues/726#issuecomment-385252787):

> afaik it could be any `*.rules` file, but the de facto standard is `firestore.rules` (at least for firestore). I haven't seen `*.rule` yet

## Checklist:
- [X] **I am adding a new language.**
- [X] The extension of the new language is used in hundreds of repositories on GitHub.com.
	- [Search results for each extension](https://github.com/search?q=filename%3Afirestore.rules+NOT+nothack&type=Code) (~2,091 results)
	- [Downloaded samples were almost completely Firestore Rules](https://github.com/Alhadis/Linguist-Silo/tree/firestore.rules)
- [X] I have included a real-world usage sample for all extensions added in this PR:
	- Sample [`firestore.rules`](https://github.com/YeFFreY/cheesecake-frontend/blob/b223342ee4df94a7acd8af5f2fc78310ebb4a242/firestore.rules) taken from [`YeFFreY/cheesecake-frontend`](https://github.com/YeFFreY/cheesecake-frontend), licensed under [MIT](https://github.com/YeFFreY/cheesecake-frontend/blob/c1e469ef72b2f803eb3512145dda9f34894ae292/package.json#L4).
- [X] I have included a syntax highlighting grammar.
	- [`jaysquared/atom-firestore-grammar`](https://github.com/jaysquared/atom-firestore-grammar/pull/2)
	- License: [MIT](https://github.com/jaysquared/atom-firestore-grammar/blob/e9aa4adc9c83147ff1e093bbea527778a02bcb4e/LICENSE#L1-L5)
- [ ] ~~I have included a change to the heuristics to distinguish my language from others using the same extension.~~ None needed, I don't think.

### CODE REVIEW

**Comment by Alhadis** [comment]
Also, think I solved that issue we've been having:

~~~console
λ linguist (cfssr): script/add-grammar https://github.com/jaysquared/atom-firestore-grammar
Checking docker is installed and running
$ docker ps
Registering new submodule: vendor/grammars/atom-firestore-grammar
$ git submodule add -f https://github.com/jaysquared/atom-firestore-grammar vendor/grammars/atom-firestore-grammar
$ script/grammar-compiler add vendor/grammars/atom-firestore-grammar
Confirming license
$ script/licensed --module /home/alhadis/Mirrors/linguist/vendor/grammars/atom-firestore-grammar
Updating grammar documentation in vendor/README.md
$ bundle exec rake samples
$ script/sort-submodules
$ script/list-grammars
  > script/list-grammars:81:in `block in to_markdown': undefined method `chomp' for nil:NilClass (NoMethodError)
  > 	from script/list-grammars:65:in `each'
  > 	from script/list-grammars:65:in `to_markdown'
  > 	from script/list-grammars:96:in `update_readme'
  > 	from script/list-grammars:105:in `<main>'
Command failed. Aborting.
λ linguist (cfssr): 
~~~
Since adding [this](https://github.com/github/linguist/pull/4120/files#diff-db68bd961ab0ce17baa056c59024741dL81), it hasn't had a single complaint about chomping anything I tell it to eat. =)

**Comment by Alhadis** [comment]
😀Haha! Yeah, now we just need to wait for the maintainer to approve it. 😉

Going by his recent activity, I'm wondering if I shouldn't try bugging him by e-mail... there's another user's PR that's waiting to be merged too...

**Comment by Alhadis** [comment]
Oh, and about this...

~~~yaml
  ace_mode: less
  codemirror_mode: css
  codemirror_mime_type: text/css
~~~

The highlighting applied by CodeMirror and Ace's CSS modes looks weirdly appropriate when applied to Firestore Rules, which is why I chose that over simply defaulting to plain-text. =)

**Comment by pchaigno** [comment]
> Going by his recent activity, I'm wondering if I shouldn't try bugging him by e-mail... there's another user's PR that's waiting to be merged too...

I'd try pinging him via GitHub.com (i.e., @hisusername) in a few days if he hasn't answered. That worked well for me in the past; I think many users receive an email notification when they're pinged. I try to keep cold-emails as a last resort.

**Comment by Alhadis** [comment]
Just so we're all clear, if you ever see me silent for over a month, it legitimately means I'm dead.

**Pull request merged**
