### PR TITLE
Add Macaulay2 language and samples

### PR DESCRIPTION
**Pull request by mahrud**
## Description
[Macaulay2](https://en.wikipedia.org/wiki/Macaulay2) is a computer algebra system cited in more than 2k papers with an interpreted high-level programming language. This PR adds a language entry and grammar for the Macaulay2 language.

Note: most (though not all) repositories using this extension are forks of the main Macaulay2 repository, therefore this list of [forks](https://github.com/Macaulay2/M2/network/members) of and [contributors](https://github.com/Macaulay2/M2/graphs/contributors) to that repository might help show its popularity.

## Checklist:
- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      -  Search for [extension=m2](https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3Am2+method+NOT+nothack)
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [FGLM.m2](https://github.com/Macaulay2/M2/blob/version-1.14/M2/Macaulay2/packages/FGLM.m2)
    - Sample license(s): GPL3
  - [x] I have included a syntax highlighting grammar: [Lightshow demo](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2FMacaulay2%2Flanguage-macaulay2%2Fmaster%2Fgrammars%2Fmacaulay2.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2FMacaulay2%2FM2%2Fversion-1.14%2FM2%2FMacaulay2%2Fpackages%2FFGLM.m2&code=)
  - ~~[ ] I have updated the heuristics to distinguish my language from others using the same extension.~~ N/A

### CODE REVIEW

**Comment by mahrud** [comment]
@jfairbank, seems like your [Sublime-Text-2-OpenEdge-ABL](https://github.com/jfairbank/Sublime-Text-2-OpenEdge-ABL) repository is removed and causing test failures.

**Comment by jfairbank** [comment]
@mahrud Thanks for the heads up. I had passed on ownership of that repo a few years ago (https://github.com/kevinmcdaniel/Sublime-Text-2-OpenEdge-ABL) and thought it had been updated here.

I can open a PR to change the repo URL, but I don't want to lock the owner into supporting something they might not be up for. @kevinmcdaniel is this something you're okay with?

Otherwise, I can just open a PR to remove my repo URL.

**Comment by mahrud** [comment]
I temporarily removed all OpenEdge ABL related lines to get the tests to finish and make sure there aren't any issues with the PR itself.

**Comment by mahrud** [comment]
I tried switching the OpenEdge ABL grammar repo to the newer one, but seems like it is different enough that a couple of tests failed. So I temporarily removed all OpenEdge ABL related lines to get the tests to finish and make sure there aren't any issues with the PR itself.

Feel free to cherry-pick the commit for a separate PR or (for the maintainers) feel free to revert it before merging.

**Comment by mahrud** [comment]
Thank you @lildude! I reverted the last commit and rebased on top of #4849. All tests pass. Let me know when you have a chance to have a look.

**Comment by mahrud** [comment]
Ahh, I saw the step, but I was hoping to get away with that since [3264](https://en.wikipedia.org/wiki/Steiner%27s_conic_problem) is kinda [symbolic](https://www.cambridge.org/core/books/3264-and-all-that/DC062983CC5F8B7CDD37CFEBCCA5FEA4) in my field. Can there be an exception? I checked, and there's a gap from 431 all the way to 51601661.

**Comment by mahrud** [comment]
I pushed the requested change.

**Comment by mahrud** [comment]
Just to be sure, is this PR only waiting to be merged into the next release, or is there still a change requested?

**Comment by Alhadis** [comment]
We're just waiting on @lildude to give his final 👍  of approval before we can merge. 😉

**Pull request merged**
