### PR TITLE
Support for two Norwegian text extensions

### PR DESCRIPTION
**Pull request by pchaigno**
This pull request adds support for two Text extensions mis-recognized as Mathematica (reported at #2137).

@arfon Could you send me a corpus of files from this search: https://github.com/search?o=asc&q=er+en+som+extension%3Ano+extension%3Anb&ref=searchresults&s=indexed&type=Code&utf8=%E2%9C%93 and one from https://github.com/search?o=desc&q=mathematica+extension%3Ano+extension%3Anb&ref=searchresults&s=indexed&type=Code&utf8=%E2%9C%93 to test this changes? Thanks.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
I'm starting to feel there should be some other way to identify `Text` files.  They can seemingly have just about any file extension.

**Comment by pchaigno** [comment]
Thanks @arfon for the samples!
After adding a new `.nb` text file (910d227) I get a 100% correct classifications on the two corpus.

**Comment by larsbrinkhoff** [comment]
Corpora! :-)

**Comment by pchaigno** [comment]
@larsbrinkhoff Thanks! I corrected it (I always thought it was the same for the plural).

**Comment by arfon** [comment]
@pchaigno - any chance you could bring this PR up to date with `master` :pray:

**Comment by pchaigno** [comment]
@arfon Done :bowtie:

**Comment by arfon** [comment]
:+1:

**Pull request merged**
