### PR TITLE
Add BASIC programming language

### PR DESCRIPTION
**Pull request by KrzysztofSzewczyk**
This pull requrest is adding BASIC programming language to be recognized.
There is VB, but there is no BASIC!

## Checklist:

- [ ] **I am associating a language with a new file extension.**
  - [ ] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      
      - https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [X] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      https://www.bamsoftware.com/hacks/qbasic/
      I'd say, 15 samples.
    - Sample license(s):
     Unknown. Author didn't provide information about software, so we can assume it's public domain.
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [X] **I am adding a new language.**
  - [ ] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      Well, I'd say github doesn't have a lot of BASIC repositories, but we know that this language is/was commonly used.
  - [X] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      Look up.
    - Sample license(s):  Look up.
  - [ ] I have included a syntax highlighting grammar.
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am fixing a misclassified language**
  - [x] I have included a new sample for the misclassified language:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [x] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am changing the source of a syntax highlighting grammar**
  
  - Old: https://github-lightshow.herokuapp.com/
  - New: https://github-lightshow.herokuapp.com/

- [ ] **I am adding new or changing current functionality**
  
  - [ ] I have added or updated the tests for the new or changed functionality.

### CODE REVIEW

**Comment by timofonic** [comment]
What about other BASIC-based languages?

- Pure Basic.
- Gambas.
etc.

2018-02-15 12:11 GMT-08:00 Krzysztof Szewczyk <notifications@github.com>:

**Comment by KrzysztofSzewczyk** [comment]
I think we need more generic name for BASIC family. QBasic was, and is popular today, (well, not so much today), and it isn't included on the list.

**Comment by timofonic** [comment]
Why a more generic name? What about specifically detecting each BASIC
dialect?

**Comment by KrzysztofSzewczyk** [comment]
Well, it would make .bas files recognized as BASIC. Maybe add QBasic?

**Pull request closed without merging**
