### PR TITLE
Add JRuby executable example, fixes #2412

### LINKED ISSUE #2412: syntax highlighting for jruby as an executable
Hi all,

I see that JRuby is listed as an alias for Ruby

https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L2802

but [this](https://github.com/shoes/shoes4/blob/master/shoes-swt/bin/shoes-swt) executable isn't getting syntax highlighted as ruby (like [this one](https://github.com/shoes/shoes4/blob/master/shoes-core/bin/shoes-picker) does). Not sure if this is a bug or something else but just thought I'd report.

If it's a small fix (like adding jruby to a list somewhere that it's not) I'd be happy to submit a PR.

### PR DESCRIPTION
**Pull request by yegortimoschenko**
This is supposed to fix JRuby executable detection. See #2412 for details.

### CODE REVIEW

**Comment by pchaigno** [comment]
@yegortimoschenko Thanks! Could you also add a sample for `rbx`? (It's better if it comes from a real application)

**Comment by yegortimoschenko** [comment]
@pchaigno Done! Drop me a line if you'd like a rebase.

**Comment by pchaigno** [comment]
It looks good to me. You'll have to wait for someone from GitHub to review it now ;)

For reviewers: [`jruby` examples](https://github.com/search?utf8=%E2%9C%93&q=usr+bin+%22env+jruby%22&type=Code&ref=searchresults) and [`rbx` examples](https://github.com/search?utf8=%E2%9C%93&q=usr+bin+%22env+rbx%22&type=Code&ref=searchresults).

**Comment by arfon** [comment]
:+1: thanks @yegortimoschenko. This will go live in the next release of Linguist (likely another week or so)

**Pull request merged**
