### PR TITLE
add language support for cairo v0.10 + earlier

### PR DESCRIPTION
**Pull request by 0xHyoga**
Opened new pull request as the earlier was giving me some issue, this one is compatible with earlier Cairo.

Replaced grammar for Cairo with the new v0.10.0 syntax. This new version of Cairo was released in September 2022 and introduced a few breaking features.

## Description

The grammar file is the same as the old file except it updates 3 main things:
1. Comments are no longer `#` and replaced it with `//`
2. Blocks start wtih `{` instead of `:` and end with `}` instead of `end`
3. Add `l1_handler` decoration

I migrated sample files to match new syntax.

## Checklist:
- [x] **I am changing the source of a syntax highlighting grammar**
  - Old: https://github.com/0xChqrles/atom-language-cairo
  - New: https://github.com/0xHyoga/atom-language-cairov0.1

### CODE REVIEW

**Review by lildude — CHANGES_REQUESTED** [review]
> I migrated sample files to match new syntax.

Please don't change the samples. These are used to train the classifier and will affect detection of files using the older syntax. It's better to add new samples for any new features or syntax.

**Comment by 0xHyoga** [comment]
I pushed again with the original sample files and duplicate of their newer cairo versions. Let me know anything else :)

**Comment by Alhadis** [comment]
@0xHyoga My [earlier suggestion](https://github.com/github/linguist/pull/6067#issuecomment-1247235831) was implying that you contribute a pull-request to the author of the current grammar (@0xChqrles is active on GitHub and his Cairo grammar doesn't at all appear to be unmaintained, so there's no good reason to replace it).

Moreover, updates to the existing grammar will merit no changes to Linguist, as all grammars are updated automatically when a new Linguist release is cut.

**Comment by lildude** [comment]
Closing in favour of support being added to the upstream grammar as recommended by @Alhadis

**Pull request closed without merging**
