### PR TITLE
exclude puphpet dir from language

### PR DESCRIPTION
**Pull request by Atriedes**

### CODE REVIEW

**Comment by bkeepers** [comment]
Hi @Atriedes, can you give us more context on what generates this and link to some repositories that have this file?

**Comment by Atriedes** [comment]
@bkeepers please take a look this repository : https://github.com/Atriedes/mabes

It detected as ruby because of puphpet

**Comment by bkeepers** [comment]
Ok, and is it a puphpet convention to vendor those files in your repository?

**Comment by Atriedes** [comment]
yes

**Comment by arfon** [comment]
Closing in favour of #2286

**Pull request closed without merging**
