### PR TITLE
Remove Arduino as a language

### PR DESCRIPTION
**Pull request by oldmud0**
See #3929 for the original issue.

### CODE REVIEW

**Comment by pchaigno** [comment]
@oldmud0 You'll also need to move the Arduino samples to `samples/C++/` and fix any other Arduino-specific test.

/cc @FredrikL who added Arduino as a separate entry in Linguist six years go (#89).

**Comment by oldmud0** [comment]
I'll finish the PR when I have time again. Thanks!

**Comment by lildude** [comment]
Nudgy nudge nudge 😉

**Comment by oldmud0** [comment]
Ouch, a virtual nudge never hurt so bad 😞

**Comment by oldmud0** [comment]
What should I do with this test?
https://github.com/github/linguist/blob/bee7e5561849055cd2f9c0a88c6b6b1a1b8e792b/test/test_repository.rb#L103-L113
It pertains to a folder structure that existed in the past, but which the present no longer contains.

**Comment by lildude** [comment]
> What should I do with this test?

Oooof, that's a bit of a ball-ache to change. That's testing the override in the `test/attributes` branch at https://github.com/github/linguist/blob/8f86998866f6f2c8aa14e0dd430e61fd25cff720/.gitattributes#L7

Thankfully that test uses that branch and the content of that branch which will still have a `samples/Arduino` directory after this PR has been merged so will continue to work.

Cleaning up that branch is on my todo list, so for the moment don't worry about it.

**Comment by lildude** [comment]
Thanks @oldmud0 and welcome to Linguist.

**Comment by oldmud0** [comment]
Thanks! I imagine when this change goes live, there will be quite a few people who will be surprised when their Arduino code is detected as "C++" instead of "Processing" as they may have previously believed.

**Comment by lildude** [comment]
> Thanks! I imagine when this change goes live, there will be quite a few people who will be surprised when their Arduino code is detected as "C++" instead of "Processing" as they may have previously believed.

Yeeeup. 😄

**Comment by felixdivo** [comment]
[Over here](https://github.com/boris-wenzlaff/arduino-python-can-serial-demo) it did not get detected at all.

**Comment by Alhadis** [comment]
Erh, yep, that definitely wasn't meant to happen:

Figure 1

This looks to be a caching issue on GitHub's side. Language stats get recalculated each time a change is made, though, so making a menial edit to [`arduino-python-can-serial-demo.ino`](https://github.com/boris-wenzlaff/arduino-python-can-serial-demo/blob/master/arduino-python-can-serial-demo.ino) should do the trick. =)

**Comment by pacifiquem** [comment]
too helpful.

**Pull request merged**
