### PR TITLE
Use a dedicated grammar for Emacs Lisp highlighting

### PR DESCRIPTION
**Pull request by Alhadis**
**I HAVE A PATHOLOGICAL OBSESSION WITH WRITING LANGUAGE GRAMMARS, _SOMEBODY PLEASE MAKE IT STOP!!!!!_**

Ahem. Seriously though, [this turned out well](https://github.com/Alhadis/language-emacs-lisp#emacs-lisp-support), and makes a number of noticeable improvements to Emacs Lisp files (particularly where function names contain keywords, like `list` or `load`).

[Lightshow preview is here](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=http%3A%2F%2Fpastebin.com%2Fraw%2FW5nEtzWm&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2FAlhadis%2F.files%2Fblob%2Fmaster%2F.emacs.d%2Finit.el&code=), and there's a scrubbable [before-and-after here](https://github.com/Alhadis/linguist/commit/cc5b37c8610a94ce736fc6e5e07c3c63b69d6d6d). Scroll to the bottom and click **Swipe**, and you'll be able to drag the slider to see the improvements to highlighting yourself.

And now to conclude a Lisp-related-anything with the proper footer:

))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))

### CODE REVIEW

**Comment by Alhadis** [comment]
Oh yeah, and I added `.spacemacs` as a recognised filename. There're [~4,545 results](https://github.com/search?utf8=%E2%9C%93&q=filename%3A.spacemacs+NOT+nothack&type=Code&ref=searchresults) for these things. They're a user-config file; the stuff they expect you to edit is what I used as a sample, with appropriate parts removed and shuffled around.

Probably could've brought that up in the PR instead of faff around and be a smart-arse, but hey, I'm only human.

**Comment by pchaigno** [comment]
LGTM

> I HAVE A PATHOLOGICAL OBSESSION WITH WRITING LANGUAGE GRAMMARS, SOMEBODY PLEASE MAKE IT STOP!!!!!

I'll stop you once you've replaced all our crappy grammars. Deal? :smile:

**Comment by Alhadis** [comment]
Deal ))))))))))))))))))))))

(That wasn't Lisp-related this time, I just went [full Russian](https://www.quora.com/Why-do-Russians-use-as-a-smiley-instead-of) instead)))))

**Comment by arfon** [comment]
> Lightshow preview is here, and there's a scrubbable before-and-after here. Scroll to the bottom and click Swipe, and you'll be able to drag the slider to see the improvements to highlighting yourself.

This raises the bar on my expectations of all future contributions 😁. Very nice 👏 

This looks good to me 👍 Thanks @Alhadis

**Comment by Alhadis** [comment]
When I see superior Emacs Lisp highlighting:

image

**Pull request merged**
