### PR TITLE
Release v7.7.0

### PR DESCRIPTION
**Pull request by lildude**
I've been waaaaay too busy of late so the release cadence has suffered again. I've got time now, so lets get a new release going. Here's v7.7.0.

Starting as a draft PR whilst I test it on GitHub.com.

### CODE REVIEW

**Comment by lildude** [comment]
Going to see if I can finally get this out today.

The GDScript grammar has removed the `GDScript.YAML-tmLanguage` file which we use for highlighting GDScript so I've not updated that grammar and have opened https://github.com/beefsack/GDScript-sublime/issues/30 for consideration of restoring the file or finding an alternate grammar.

**Comment by Alhadis** [comment]
@pchaigno You might want to hurry with adding the new M4 grammar... 😅

**Comment by lildude** [comment]
This is it. I've tested all of these changes and I'm queued up to deploy this within the next few hours.

**Comment by lildude** [comment]
These changes are now live on GitHub.com

**Comment by lildude** [comment]
> Some of the updated grammars aren't showing up on GitHub (compare [this](https://github.com/github/linguist/blob/master/.gitmodules) with [this](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=cson&grammar_url=https%3A%2F%2Fgithub.com%2FAlhadis%2Flanguage-etc%2Fblob%2Fmaster%2Fgrammars%2Fgitconfig.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fgithub%2Flinguist%2Fblob%2Fmaster%2F.gitmodules&code=), for example). Is this normal?

Yes. As I've not made the release yet, the grammar highlighting service won't be able to find the compiled grammars file at `https://github.com/github/linguist/releases/download/<VERSION>/linguist-grammars.tar.gz` so it is still using the older version, ie the one from v7.6.1.

**Comment by lildude** [comment]
I should probably start making the release completely here before updating GitHub.com to prevent this in future.

**Comment by gen-angry** [comment]
Quick Question: I have a private repo of mirc script files (the main reason I added a push for msl support). The 'language bar' up top still says '97% Batchfile' (a small batchfile I used to generate some stuff) like it did before this release.

Will this bar update itself eventually to include 'msl files' or do I need to trigger anything? Or am I misinterpreting what this release means.

Thanks :)

**Comment by lildude** [comment]
> Will this bar update itself eventually to include 'msl files' or do I need to trigger anything?

The language analysis only takes place when you push to the repo so it won't change until you make a change.

**Comment by Alhadis** [comment]
It's, erh, still doing that thing again where the latest syntax highlighting changes [aren't showing up](https://github.com/Alhadis/language-etc/blob/master/samples/configure.ac)… :\

Like last time, the newest grammar additions aren't listed in [Lightshow](https://github-lightshow.herokuapp.com/), suggesting it's the same deploy bug as before.

**Comment by lildude** [comment]
I'm still waiting for one more PR to be reviewed. I thought the latest release would be picked up automatically, but this isn't the case 😕 I'll update this PR when that PR has been merged.

**Comment by lildude** [comment]
@Alhadis I've branch deployed my PR for the syntax highlighting service and it has picked up the updated grammars now: 

Screenshot 2019-12-10 at 09 27 33

I need to give it a few hours before I can merge to be sure, but so far so good.

**Comment by Alhadis** [comment]
Music to my ears, @lildude. ❤️ Thank you!

**Comment by lildude** [comment]
No issues from sitting for the past few hours so I've merged and we're still looking good.

**Pull request merged**
