### PR TITLE
Classify builds, pkgproj, resx and sfproj as XML

### PR DESCRIPTION
**Pull request by jasonwilliams200OK**
* `.builds` (MSBuild): https://github.com/search?utf8=%E2%9C%93&q=extension%3Abuilds+xml&type=Code&ref=searchresults

* `.pkgproj` (Nuget): https://github.com/search?utf8=%E2%9C%93&q=extension%3Apkgproj+xml&type=Code&ref=searchresults

* `.resx` (Resource): https://github.com/search?utf8=%E2%9C%93&q=extension%3Aresx+xml&type=Code&ref=searchresults

* `.sfproj` (Azure Service Fabric): https://github.com/search?utf8=%E2%9C%93&q=extension%3Asfproj+xml&type=Code&ref=searchresults

### CODE REVIEW

**Comment by pchaigno** [comment]
There seem to be [many non-XML `.builds` files](https://github.com/search?p=56&q=extension%3Abuilds+NOT+xml&ref=searchresults&type=Code&utf8=%E2%9C%93). I'm not sure what they are...

**Comment by jasonwilliams200OK** [comment]
@pcantrell, they are simple text files. In my understanding, those will remain unhighlighted; or should I explicitly disambiguate them?

**Comment by jasonwilliams200OK** [comment]
I have added the disambiguation rule in `heuristics.rb`. PTAL. :)

**Comment by pcantrell** [comment]
@jasonwilliams200OK: I think you meant to ping @pchaigno?

**Comment by jasonwilliams200OK** [comment]
Yup sorry about that. Quick auto-complete is not always reliable. :)

**Comment by arfon** [comment]
Thanks for this contribution @jasonwilliams200OK :zap:. This will be live in the next release of Linguist (likely sometime in the next week).

**Pull request merged**
