### PR TITLE
Sqlllll

### PR DESCRIPTION
**Pull request by arfon**
Replaces https://github.com/github/linguist/pull/2082

### CODE REVIEW

**Comment by arfon** [comment]
I think this is looking in pretty good shape now. / cc @bkeepers for a review.

**Comment by bkeepers** [comment]
There are a lot of submodule changes that look unrelated. Was that intentional?

Everything else looks good to me. :+1:

**Comment by arfon** [comment]
Looks like I accidentally merged in the updates grammars here. Any objection to merging as-is?

**Comment by Shoelace** [comment]
great.. cant wait to see this live on github.. :)

**Pull request merged**
