### PR TITLE
Deadfish language

### PR DESCRIPTION
**Pull request by phase**
>Deadfish is a very odd interpreted programming language created by Jonathan Todd Skinner. It was released under public domain and was originally programmed in C, but now it has been since ported to many other programming languages.

It's an interesting language and it'd be sweet if Linguist had support for it. I put the extension as `.df`, though I assume it could be anything depending on the interpreter. You can read more about it [here](https://esolangs.org/wiki/Deadfish).

Type | Increment | Decrement | Square | Output
------- | ---------------- | ----------------- | ------------ | ---------
Standard Deadfish | i | d | s | o
XKCD variation | x | d | k | c

There aren't a lot of interpreters on GitHub, but [here are some](https://github.com/search?utf8=%E2%9C%93&q=deadfish).

### CODE REVIEW

**Comment by pchaigno** [comment]
Please see the [requirements to add a new language](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language). Could you link to a search on GitHub with examples of this language?

**Comment by phase** [comment]
@pchaigno The search is at the bottom. I couldn't find any files of it.

**Comment by pchaigno** [comment]
I'm afraid it won't be enough. The guidelines state `languages be in use in hundreds of repositories` :/

**Comment by bkeepers** [comment]
@phase thanks for the pull request! As @pchaigno points out, we like to wait until there is some adoption on GitHub before adding support for a language.

**Comment by phase** [comment]
Darn. We'll just have to wait till it's the most used language on GitHub. :D

**Pull request closed without merging**
