### PR TITLE
Add support for hoon

### PR DESCRIPTION
**Pull request by pkova**
## Checklist:

- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      -  https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3Ahoon
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [eyre.hoon](https://github.com/urbit/urbit/blob/874d380ad5d5e1bca0c22c498294572c6d160f51/pkg/arvo/sys/vane/eyre.hoon) [license](https://github.com/urbit/urbit/blob/874d380ad5d5e1bca0c22c498294572c6d160f51/LICENSE.txt)
      - [hoon.hoon](https://github.com/urbit/urbit/blob/874d380ad5d5e1bca0c22c498294572c6d160f51/pkg/arvo/sys/hoon.hoon) [license](https://github.com/urbit/urbit/blob/874d380ad5d5e1bca0c22c498294572c6d160f51/LICENSE.txt)
      - [canvas.hoon](https://github.com/yosoyubik/canvas/blob/efe708e5681930c6efaf8c5ca571594b0ae04831/urbit/app/canvas.hoon) [license](https://github.com/yosoyubik/canvas/blob/efe708e5681930c6efaf8c5ca571594b0ae04831/LICENSE.txt)
  - [x] I have included a syntax highlighting grammar: [preview](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fpkova%2Fhoon-grammar%2Fmaster%2Fhoon.tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Furbit%2Furbit%2F874d380ad5d5e1bca0c22c498294572c6d160f51%2Fpkg%2Farvo%2Fsys%2Fvane%2Feyre.hoon&code=)

### CODE REVIEW

**Review by lildude — CHANGES_REQUESTED** [review]
Looks like you missed adding the grammar license file. When you ran script/add-grammar it should have downloaded the file in a format we need.

**Comment by pkova** [comment]
Looks like I forgot to commit the grammar license, fixed and rebased.

**Review by lildude — CHANGES_REQUESTED** [review]
Oooff, I've just noticed that `samples/hoon/eyre.hoon` is massive. We really don't need such a large file. I think you can safely remove this file.

**Comment by lildude** [comment]
> Oooff, I've just noticed that `samples/hoon/eyre.hoon` is massive. We really don't need such a large file. I think you can safely remove this file.

I've done it.

**Review by lildude — APPROVED** [review]

**Comment by laudiacay** [comment]
chefs kiss

**Pull request merged**
