### PR TITLE
Change grammar used for Haskell highlighting

### PR DESCRIPTION
**Pull request by Alhadis**
#3146 reminded me the [Atom package](https://github.com/atom-haskell/language-haskell/issues/80) for Haskell support is frequently updated and well-maintained.

Surely enough, it fixes [the highlighting issue](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgithub.com%2Fatom-haskell%2Flanguage-haskell%2Fblob%2Fmaster%2Fgrammars%2Fhaskell.cson&grammar_text=&code_source=from-text&code_url=&code=--+Highlighted+as+comment%0D%0Aclass+X+y%0D%0A--+Not+highlighted+correctly) and probably others we don't know about, too.

### CODE REVIEW

**Comment by Alhadis** [comment]
inb4 CI reports an error with my attempt at submodule removal

**Comment by lierdakil** [comment]
Ouch. I don't think you want to use all grammars defined in language-haskell, some of those are for internal use (like limited subset for type tooltips highlighting, and a grammar for highlighting compiler output). Long story short, ignore `hint.*` grammars.

**Comment by pchaigno** [comment]
@lierdakil That's fine, with the pull request as is, we'll only use the `source.haskell` scope. Thanks for reviewing :+1:

**Comment by Alhadis** [comment]
@lierdakil That reminds me, I noticed these hints get listed in Atom's grammar-selector menu:

Figure 1

You might be surprised to know a grammar's `name` property is actually optional; only the `scopeName` seems to be required. Not specifying a `name` hides the grammar from being listed, which might be a better way of including "internal" grammars. =)

**Comment by lierdakil** [comment]
@Alhadis, right, that's my bad, I honestly didn't think twice about that when adding those ^_^"

**Comment by Alhadis** [comment]
Conflict fixed!

We need notifications for when a pending PR suddenly has conflicts... :(

**Comment by arfon** [comment]
:+1: :shipit:

**Pull request merged**
