### PR TITLE
Fetch libicu via Travis, switch back to container-based

### PR DESCRIPTION
**Pull request by meatballhat**
This is a test.  I don't understand the details of how the `bundle config
build.charlock_holmes` bit works/fails, so the intent here is to get a PR posted
for purposes of getting feedback via the full Travis machinery.

### CODE REVIEW

**Comment by meatballhat** [comment]
Appears to work (???) :smiley_cat:

**Comment by pchaigno** [comment]
Nice :+1:

**Comment by arfon** [comment]
Awesome. Thanks @meatballhat!

**Comment by meatballhat** [comment]
@arfon :heart_eyes_cat: :metal: thanks for the merge!

**Pull request merged**
