### PR TITLE
Add .geojson/.topojson as JSON extensions / Fix NCL colour

### PR DESCRIPTION
**Pull request by Alhadis**
The `.geojson` extension is quite well-established on GitHub by now (measuring in around [~901,874 results](https://github.com/search?utf8=%E2%9C%93&q=extension%3Ageojson+NOT+nothack&type=Code&ref=searchresults)), but even with the site's cool [interactive handling of `.geojson` files](https://github.com/blog/1528-there-s-a-map-for-that), they're still not picked up as actual JSON.

For instance, observe the missing language statistics for [this repository](https://github.com/benbalter/dc-maps).

=======

**EDIT:** I've also fixed the wrongly-quoted colour of the `NCL` language, [which currently displays in grey](https://github.com/Alhadis/NCL-SyntaxColouring).

### CODE REVIEW

**Comment by pchaigno** [comment]
> For instance, observe the missing language statistics for this repository.

JSON as a data language is not being counted in the statistics.

> EDIT: I've also fixed the wrongly-quoted colour of the NCL language, which currently displays in grey.

I guess it's okay here but it's usually a good idea to submit each fix/improvement in a separate PR ;)

**Comment by Alhadis** [comment]
> JSON as a data language is not being counted in the statistics.
Ah, right. Sorry, wasn't aware that data-languages were excluded from Linguist evaluation. My bad.

> I guess it's okay here but it's usually a good idea to submit each fix/improvement in a separate PR ;)
That's actually what I tried to do, haha. I submitted one pull request, did a fix in a separate commit, pushed that, and... well, here we are. I kinda shrugged and amended the original PR's title/body.

**Comment by pchaigno** [comment]
You have to use separate branches to do several pull requests ;)

**Comment by Alhadis** [comment]
Oh, dear. Am I going to hell?

(I said I was new to pull requests, hahah)

**Comment by Alhadis** [comment]
(That was an encrypted 6am way of asking "What should I do? Retract my pull request and start again?")

**Comment by arfon** [comment]
Looks good to me. @benbalter - this makes sense right?

**Comment by benbalter** [comment]
:+1:, you may also want to add `.topojson` which GitHub also supports (which is a subset of GeoJSON).

**Comment by arfon** [comment]
> you may also want to add `.topojson` which GitHub also supports (which is a subset of GeoJSON).

Good call. @Alhadis would you mind adding `.topojson` as an extension (and a sample file)?

**Comment by Alhadis** [comment]
@arfon @benbalter Done! Haha, I didn't even know that format existed. :D I need to get out more. Desire to visit Switzerland notwithstanding.

**Comment by arfon** [comment]
:+1: this is looking good. Thanks @Alhadis. This won't be live on GitHub for another week or so as we just cut a new Linguist gem yesterday.

**Comment by Alhadis** [comment]
Haha, no rush, mate! :D I'm honoured to have helped, thank you!

**Pull request merged**
