### PR TITLE
Exclude "dist" directory from language statistics

### PR DESCRIPTION
**Pull request by adius**
It is listed in a lot of .gitignore files, if this is any indicator that it should not be checked: https://github.com/search?utf8=%E2%9C%93&q=dist+filename%3Agitignore&type=Code&ref=searchresults

### CODE REVIEW

**Comment by pchaigno** [comment]
@adius Thanks for the pull request! Do you have a few examples of `dist` directories on github.com? I've looked up a few of the repositories from the search results, but none of them seem to actually have a `dist` directory.

**Comment by adius** [comment]
🙈 Yeah of course none of them have a `dist` directory, because having dist in your gitignore does exactly mean this: "Don't upload the directory to GitHub" 😂

So what I'm saying is, that if somebody uploads a `dist` directory it was probably accidentally or they explicitly wanted to bundle 3rd party files. In any way it should not be checked for language statistics!

**Comment by pchaigno** [comment]
> 🙈 Yeah of course none of them have a `dist` directory, because having dist in your gitignore does exactly mean this: "Don't upload the directory to GitHub" 😂

Hm, right :flushed: Don't know where my head's at.

I went through [a few of these directories](https://github.com/search?o=desc&q=path%3Adist+if&s=indexed&type=Code&utf8=%E2%9C%93) and, although the usage seems to vary a bit, I couldn't find a case where we wouldn't want to vendor it. So :+1: for me.

**Comment by Alhadis** [comment]
[Relevant](https://github.com/Alhadis/Accordion/blob/master/.gitattributes).

**Comment by arfon** [comment]
👍 thanks @adius

**Pull request merged**
