### PR TITLE
Add syntax for SARL language.

### PR DESCRIPTION
**Pull request by gallandarakhneorg**
SARL language: http://www.sarl.io

Signed-off-by: Stéphane Galland <galland@arakhne.org>

### CODE REVIEW

**Comment by pchaigno** [comment]
Please have a look at the [guidelines to add support for a new language to Linguist](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language). In particular, we'll need some evidence of in-the-wild usage across github.com.

**Comment by gallandarakhneorg** [comment]
The grammar and the samples are under Apache 2 License. The submodule included into this PR contains the license file: https://github.com/sarl/sarl-textmate/blob/master/LICENSE. The grammar license is also specified into the grammar file: https://github.com/sarl/sarl-textmate/blob/master/sarl.tmLanguage

Regarding the sample code, I have not put the license into the sample to mimic the samples of the other languages. The source of the sample is: https://github.com/sarl/sarl/tree/master/contribs/io.sarl.examples/io.sarl.examples.plugin/projects

Should I add some LICENSE file or comment to each of the sample files?

**Comment by gallandarakhneorg** [comment]
According to the provided guidelines, please find below the link to the Github search result:
https://github.com/search?q=io.sarl.lang.core&type=Code

**Comment by lildude** [comment]
Thanks for the clarification of the license for the samples @gallandarakhneorg. That's all we need for them.

However, there are a few other issues still outstanding:

1. It looks like your new grammar wasn't added using the `script/add-language` script as the grammar license hasn't been included in this PR.
2. You're adding SARL with the extension `.sarl` which doesn't return many [unique hits](https://github.com/search?utf8=%E2%9C%93&q=extension%3Asarl+NOT+nothack&type=Code), hence @pchaigno and my previous comments about it. Your sample search is referencing many many _other_ file types and languages and not specifically SARL. [Limiting your search to just the `.sarl` extension](https://github.com/search?utf8=%E2%9C%93&q=extension%3Asarl+io.sarl.lang.core&type=Code) returns even fewer hits.
3. There's a conflict with `.gitmodules` - you need up merge github/linguist's master into your fork.
3. There are still a few failing tests that need addressing - the errors in the tests should help you identify the problems and make the necessary fixes.

**Comment by pchaigno** [comment]
Closing in favor of #4219. We'll monitor the popularity of the extension there.

If you have an improved search query compared to the one used in #4219, please post it here and I'll update #4219.

**Pull request closed without merging**
