### PR TITLE
Add a C sample defining a large initialized array

### PR DESCRIPTION
**Pull request by ib**
This fixes github issue #5012.

- [X] **I am fixing a misclassified language**
  - [X] I have included a new sample for the misclassified language:
    - Sample source(s): `C/foo.h`
      - [URL to each sample source, if applicable]
    - Sample license(s): file created by me, any license you want
  - [X] I have included a change to the heuristics to distinguish my language from others using the same extension.

### CODE REVIEW

**Comment by lildude** [comment]
🤔 I'm not sure this is really solving the real issue here. The classifier uses real-world samples to try and guess the language based on how it is really used. This contrived sample is being added to deliberately sway the classifier and in turn may start causing legitimate Objective-C or C++ header files (I have no idea if there is such a thing) to be classified as C and thus only add to what is already a tricky problem as detailed in the ongoing discussion in https://github.com/github/linguist/issues/1626

**Comment by ib** [comment]
The sample is based on real-world headers: https://github.com/ib/gucharmap/tree/master/gucharmap: unicode-*.h

**Comment by lildude** [comment]
> The sample is based on real-world headers: https://github.com/ib/gucharmap/tree/master/gucharmap: unicode-*.h

Why not use one of the real-world files?

**Comment by smola** [comment]
The main problem here is that token frequency within documents leads to weird results in classification. For example, if a few more braces appear in C++ files, the classifier will be biased towards C++ when classifying pure C files that have many braces.

I think the right solution is going for the root problem: absolute frequency of tokens is suboptimal, and we should probably move to document frequency. I've been testing this approach and I think it should work decently (and faster). But it still requires some more verification.

**Comment by lildude** [comment]
Closing as this isn't a real world sample and is only being added to improperly influence the classifier. Recent and pending improvements to the classifier will also help towards addressing the original issue.

**Pull request closed without merging**
