### PR TITLE
Add ACS (Action Code Script)

### PR DESCRIPTION
**Pull request by agwilt**
ACS is a compiled language for the ZDoom game engine. From the ZDoom wiki:
> ACS (Action Code Script) is the scripting language that was originally created for Hexen by Raven Software and has been greatly expanded by ZDoom.

**Examples on [GitHub](https://github.com/search?utf8=%E2%9C%93&q=extension%3Aacs+NOT+nothack&type=Code&ref=searchresults):**
- alexey-lysiuk/Realm667-AAA
- dptetc/membrance2
- wormt/bcc
- coelckers/gzdoom
- dptetc/PC96-Doom
- csnxs/retromaze
- csnxs/hydrogen
- StrikerMan780/shadow-mavericks-multi-purpose-mod
- neonplayer/Rop
- skylerdavidson/real-guns-hardcore
- agwilt/zdoom-insurrection
- rheit/zdoom
- rheit/acc <-- Well, that's the standard ACS compiler ..
- and so on

**File extension:** .acs

### CODE REVIEW

**Comment by arfon** [comment]
Thanks for opening this Pull Request @agwilt. I'm trying to figure out if there are any other files using the `.acs` extension - is [this file](https://github.com/fingolfin/gap-osx-binary/blob/b7ea78241904c5eb6d3726fb1ee627b48592e1c0/lib/gap/small/id3/id8.acs) Action Code Script too?

**Comment by agwilt** [comment]
Oh, good point. That doesn't seem to be ACS. But the .acs extension doesn't seem to generally apply to that type of file, as they are all named things like id8.acs, id8.abm, id8.bn, etc.

**Comment by arfon** [comment]
> Oh, good point. That doesn't seem to be ACS. But the .acs extension obviously doesn't generally apply to that type of file, as they are all named things like id8.acs, id8.abm, id8.bn, etc.

The issue here is that as `ACS` is the first language to define `.acs` as a valid extension, that means that as currently implemented in this Pull Request *all* `.acs` files on GitHub will be classified as `ACS` by Linguist (which isn't what we want to do).

This isn't a show-stopper but it does mean that before we can consider merging this Pull Request we're going to have to audit what other languages are using the extension (e.g. I found some examples that were XML) and add `.acs` to those language definitions too.

@agwilt - if you're willing to do this that would make this process go significantly faster than if on of the core maintainers has to do this!

**Comment by pchaigno** [comment]
Using [this github.com search](https://github.com/search?utf8=%E2%9C%93&q=extension%3Aacs+Script&type=Code&ref=searchresults), I found 135 ACS repositories by 90 different users. It's not much for a conflicting file extension. @arfon Should we wait for a greater adoption of ACS on github.com?

**Comment by arfon** [comment]
> Using this github.com search, I found 135 ACS repositories by 90 different users. It's not much for a conflicting file extension. @arfon Should we wait for a greater adoption of ACS on github.com?

I think we should let this one sit for a while. This is lower than the required limits in our contributing guidelines.

**Comment by agwilt** [comment]
OK, that probably makes sense ...

Also, telling linguist that it's C results in sensible code highlighting.

**Comment by pchaigno** [comment]
Great to hear that you found a temporary solution!

I'm closing this pull request. Don't hesitate to reopen (or open a new pull request) when you think ACS has reached the requirement in-the-wild adoption (hundreds of repositories).

**Pull request closed without merging**
