### PR TITLE
Add Nasal programming language extension.

### PR DESCRIPTION
**Pull request by NikolaiVChr**
## Description

Add extension for Nasal language.
And yes, its used for hundreds of github repos.

## Checklist:

- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3Anas+func+NOT+nothack
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - https://github.com/NikolaiVChr/OpRedFlag/blob/master/emesary-damage-system/nasal/damage.nas
      - https://github.com/ChrisCalef/fgdata-without-aircraft/blob/b682dbff16534a858bfbdb3ad990dd7a9e8d55e8/Aircraft/Generic/DualControl/Instruments/KX165/kx165tso.nas
      - https://github.com/nanake/lame/blob/5ac0145e612c72a9417af7ac6f9d3b5b93671a2d/libmp3lame/i386/fftfpu.nas
      - https://github.com/nanake/lame/blob/5ac0145e612c72a9417af7ac6f9d3b5b93671a2d/libmp3lame/i386/cpu_feat.nas
    - Sample license(s): All are GPL 2.0
  
  - [x] I have included a syntax highlighting grammar: https://github.com/RenanMsV/nasal-vscode
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

### CODE REVIEW

**Comment by lildude** [comment]
I think we're going to need `.nas` added to another language and a heuristic as `.nas` appears to be quite popular and they don't all appear to be Nasal. From a quick look, quite a few appear to be Assembly.

> I have included a real-world usage sample for all extensions added in this PR:
> 
>   * Sample source(s): samples/Nasal/damage.nas
>     
>     * [URL to each sample source, if applicable]

Where did you get the sample from? We need the URL to that source in this section of the template.

Normally peeps want support for a language so they can have syntax highlighting on GitHub. How about adding https://github.com/RenanMsV/nasal-vscode to this PR? I'm guessing this is for the same language and seems to do a good job highlighting the sample you've included as can be seen [here](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fgithub.com%2FRenanMsV%2Fnasal-vscode%2Fblob%2Fmaster%2Fsyntaxes%2Fnasal.tmLanguage.json&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fgithub%2Flinguist%2Fblob%2F1c6c6a0e94362dc57271df7065846962c1353bce%2Fsamples%2FNasal%2Fdamage.nas&code=)

**Comment by NikolaiVChr** [comment]
I have updated the post.

But I am unsure how to update the heuristic.

**Comment by lildude** [comment]
> But I am unsure how to update the heuristic.

Sorry about the delay in getting back to this.

From a quick look at Nasal and Assembly, I think we might be OK with leaving it to the classifier as the two appear to be quite distinct from each other.

So the next steps would be to:

1. Add `.nas` to the list of extensions for "Assembly" 
2. Add two representative real-world samples of Assembly `.nas` files
3. Add another real-world representative sample of Nasal

All of this would happen in this PR.

If all goes well, all the tests should pass without any thing else, but we'll see 🤞.

**Comment by lildude** [comment]
I've finished off this PR. I've got the colour from the Nasal logo at https://wiki.flightgear.org/Nasal_Console

The only thing I've not done is add a syntax highlighting grammar as I've just noticed that the one I referenced before is licensed under the GPL which we can't use.

**Review by lildude — APPROVED** [review]

**Pull request merged**
