### PR TITLE
Added Xojo module

### PR DESCRIPTION
**Pull request by jimmckay**
Added Xojo module to replace incorrect VBDotNet module

## Description
Provides syntax coloring comparable to the coloring seen in the Xojo IDE
I am unsure if this qualifies as adding a language or reclassifying.
Xojo language was previously included, but only pointed at source.vbnet which may have been somewhat compatible in the past, but currently produces unsatisfactory results.

## Checklist:

- [x] **I am changing the source of a syntax highlighting grammar**
  
  - [Old highlighting](https://github-lightshow.herokuapp.com/?utf8=✓&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fangryant0007%2FVBDotNetSyntax%2Fmaster%2Fvbdotnet.tmLanguage&grammar_text=%7B%09scopeName+%3D+%27source.xojo%27%3B%0D%0A%09fileTypes+%3D+%28+%27xojo_code%27+%29%3B%0D%0A%09patterns+%3D+%28%0D%0A%09%09%7B%09name+%3D+%27keyword.control.xojo%27%3B%0D%0A%09%09%09match+%3D+%27%5Cb%28if%7Cthen%7Celse%7Celse+if%7Cend+if%7Cdo%7Cwhile%7Cwend%7Cfor%7Cnext%7Creturn%29%5Cb%27%3B%0D%0A%09%09%7D%2C%0D%0A%09%09%7B%09name+%3D+%27string.quoted.double.xojo%27%3B%0D%0A%09%09%09match+%3D+%27%22.*%22%27%3B%0D%0A%09%09%7D%2C%0D%0A%09%09%7B%09name+%3D+%27markup.italic.xojo%27%3B%0D%0A%09%09%09match+%3D+%27%5Cs*%23.*%24%27%3B%0D%0A%09%09%7D%0D%0A%09%29%3B%0D%0A%7D&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fjimmckay%2Fmacoslib%2Fmaster%2FExamples%2FAppIconExample.rbfrm&code=%27if+myAutoCompleteMenu%3C%3Enil+then+myAutoCompleteMenu.Close%0D%0Aif+myAutoCompleteMenu%3Dnil+or+myAutoCompleteMenu.Value%3Dnil+then+myAutoCompleteMenu+%3D+new+WeakRef%28new+ListBoxMenu%29%0D%0AListBoxMenu%28myAutoCompleteMenu.Value%29.Show%28self%2CAutoCompleteStrings%2Cx%2BTrueWindow.Left%2Bme.left%2Cy%2BTrueWindow.top%2Bme.top%29%0D%0A)
  - [New highlighting](https://github-lightshow.herokuapp.com/?utf8=✓&scope=from-url&grammar_format=xml&grammar_url=https%3A%2F%2Fpidog.com%2Fshare%2Fxojosyntax.xml&grammar_text=%7B%09scopeName+%3D+%27source.xojo%27%3B%0D%0A%09fileTypes+%3D+%28+%27xojo_code%27+%29%3B%0D%0A%09patterns+%3D+%28%0D%0A%09%09%7B%09name+%3D+%27keyword.control.xojo%27%3B%0D%0A%09%09%09match+%3D+%27%5Cb%28if%7Cthen%7Celse%7Celse+if%7Cend+if%7Cdo%7Cwhile%7Cwend%7Cfor%7Cnext%7Creturn%29%5Cb%27%3B%0D%0A%09%09%7D%2C%0D%0A%09%09%7B%09name+%3D+%27string.quoted.double.xojo%27%3B%0D%0A%09%09%09match+%3D+%27%22.*%22%27%3B%0D%0A%09%09%7D%2C%0D%0A%09%09%7B%09name+%3D+%27markup.italic.xojo%27%3B%0D%0A%09%09%09match+%3D+%27%5Cs*%23.*%24%27%3B%0D%0A%09%09%7D%0D%0A%09%29%3B%0D%0A%7D&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fjimmckay%2Fmacoslib%2Fmaster%2FExamples%2FAppIconExample.rbfrm&code=%27if+myAutoCompleteMenu%3C%3Enil+then+myAutoCompleteMenu.Close%0D%0Aif+myAutoCompleteMenu%3Dnil+or+myAutoCompleteMenu.Value%3Dnil+then+myAutoCompleteMenu+%3D+new+WeakRef%28new+ListBoxMenu%29%0D%0AListBoxMenu%28myAutoCompleteMenu.Value%29.Show%28self%2CAutoCompleteStrings%2Cx%2BTrueWindow.Left%2Bme.left%2Cy%2BTrueWindow.top%2Bme.top%29%0D%0A)

### CODE REVIEW

**Comment by Alhadis** [comment]
👋 Hey @jimmckay, thanks for the contribution. Always good to have a dedicated grammar for highlighting!

Could you point me to a screenshot of how the colouring looks in Xojo IDE?

**Comment by Alhadis** [comment]
The build is [failing](https://travis-ci.org/github/linguist/jobs/539021011#L1639-L1659) because the grammars list is out-of-date:

~~~diff
  1) Failure:
TestGrammars#test_readme_file_is_in_sync [/home/travis/build/github/linguist/test/test_grammars.rb:42]:
Grammar list is out-of-date. Run `script/list-grammars`.
--- expected
+++ actual
@@ -426,7 +426,7 @@
 - **XQuery:** [wcandillon/language-jsoniq](https://github.com/wcandillon/language-jsoniq)
 - **XS:** [textmate/c.tmbundle](https://github.com/textmate/c.tmbundle)
 - **XSLT:** [textmate/xml.tmbundle](https://github.com/textmate/xml.tmbundle)
-- **Xojo:** [angryant0007/VBDotNetSyntax](https://github.com/angryant0007/VBDotNetSyntax)
+- **Xojo:** [jimmckay/XojoSyntaxTM](https://github.com/jimmckay/XojoSyntaxTM)
~~~

Did you use the [`script/add-grammar`](https://github.com/github/linguist/blob/57d2da7e17fd7ed4477a6308094cc08431d4aa2d/script/add-grammar) script to add this grammar, or did you do so manually?

**Comment by jimmckay** [comment]
Here is a screenshot of the sample from Lightshow in Xojo.
xojo-syntax

I did use script/add-grammar to add it, but the VBDotNetSyntax was already present. I'm not sure if that might have broken something.

**Comment by jimmckay** [comment]
Looks like I pasted the wrong url in lightshow for the new syntax file.
Here is the correct url:
https://github-lightshow.herokuapp.com/?utf8=✓&scope=from-url&grammar_format=xml&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fjimmckay%2FXojoSyntaxTM%2Fmaster%2FXojo.tmLanguage&grammar_text=%7B%09scopeName+%3D+%27source.xojo%27%3B%0D%0A%09fileTypes+%3D+%28+%27xojo_code%27+%29%3B%0D%0A%09patterns+%3D+%28%0D%0A%09%09%7B%09name+%3D+%27keyword.control.xojo%27%3B%0D%0A%09%09%09match+%3D+%27%5Cb%28if%7Cthen%7Celse%7Celse+if%7Cend+if%7Cdo%7Cwhile%7Cwend%7Cfor%7Cnext%7Creturn%29%5Cb%27%3B%0D%0A%09%09%7D%2C%0D%0A%09%09%7B%09name+%3D+%27string.quoted.double.xojo%27%3B%0D%0A%09%09%09match+%3D+%27%22.*%22%27%3B%0D%0A%09%09%7D%2C%0D%0A%09%09%7B%09name+%3D+%27markup.italic.xojo%27%3B%0D%0A%09%09%09match+%3D+%27%5Cs*%23.*%24%27%3B%0D%0A%09%09%7D%0D%0A%09%29%3B%0D%0A%7D&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fjimmckay%2Fmacoslib%2Fmaster%2FExamples%2FAppIconExample.rbfrm&code=%27if+myAutoCompleteMenu%3C%3Enil+then+myAutoCompleteMenu.Close%0D%0Aif+myAutoCompleteMenu%3Dnil+or+myAutoCompleteMenu.Value%3Dnil+then+myAutoCompleteMenu+%3D+new+WeakRef%28new+ListBoxMenu%29%0D%0AListBoxMenu%28myAutoCompleteMenu.Value%29.Show%28self%2CAutoCompleteStrings%2Cx%2BTrueWindow.Left%2Bme.left%2Cy%2BTrueWindow.top%2Bme.top%29%0D%0A

**Comment by Alhadis** [comment]
> Here is the correct url:

Erm, when you do that, could you please use markdown links to embed the URL into the text? Like this:

~~~markdown
[Here is this correct url](https://github-lightshow.…/end-of-huge-url.html)
~~~

Smaller URLs are fine, but Lightshow permalinks are colossal and can make a thread very difficult to peruse in review. I've amended it for you (as well as the OP), but just a note for next time. =)

> I did use script/add-grammar to add it, but the VBDotNetSyntax was already present. I'm not sure if that might have broken something.

Possibly. Were you using the `--replace` switch to remove the old grammar first? Either way, it sounds like a bug; I'll make a note to investigate later.

You can fix the build failures manually if you prefer not to run the script. It's just a simple matter of editing [`vendor/README.md`](https://github.com/github/linguist/blob/master/vendor/README.md) with the following change:

~~~diff
--- expected
+++ actual
@@ -426,7 +426,7 @@
 - **XQuery:** [wcandillon/language-jsoniq](https://github.com/wcandillon/language-jsoniq)
 - **XS:** [textmate/c.tmbundle](https://github.com/textmate/c.tmbundle)
 - **XSLT:** [textmate/xml.tmbundle](https://github.com/textmate/xml.tmbundle)
-- **Xojo:** [angryant0007/VBDotNetSyntax](https://github.com/angryant0007/VBDotNetSyntax)
+- **Xojo:** [jimmckay/XojoSyntaxTM](https://github.com/jimmckay/XojoSyntaxTM)
~~~

**Comment by jimmckay** [comment]
Thanks @Alhadis , I'm obviously new here. I'll be sure to use markdown in the future. 
I fixed the readme.

**Comment by Alhadis** [comment]
All good! 😉 We all have to start somewhere.

Thanks for your patience and contribution, and welcome to Linguist! We'll get this merged once it's been given the green light by site-staff.

/cc @lildude

**Comment by jimmckay** [comment]
Awesome! Thanks for your help!

**Pull request merged**
