### PR TITLE
Release v5.1.0

### PR DESCRIPTION
**Pull request by lildude**
Changes since last release (https://github.com/github/linguist/compare/v5.0.11...v5.1.0)

- Update MD5 digest for testing under Ruby 2.4 (#3643)
- Support for Type Language (#3593)
- Add recognition and classification of WebAssembly (#3650)
- Improve running from cloned repo docs (#3669)
- Fix spelling of Perl 6 (#3672)
- Added syntax definition for Fantom language (#3660)
- Update vendor.yml: skeleton.css (#3682)
- Added Ring Language Support  (#3662)
- Add new language for the Easybuild framework (#3466)
- Add C sample (#3698)
- Add misclassified C sample (#3652)
- Register "cpanfile" as a Perl filename (#3704)
- Add xspec as XML file extension (#3702)
- Improve Pan language support (#3691)
- Add NCSA to license whitelist (#3714)
- fix Coq sample JsNumber.v (#3710)
- improve .ms disambiguation (Unix Assembly / MAXScript) (#3707)
- shell: add more interpreters (#3708)

... and an update to the latest version of all grammars.

### CODE REVIEW

**Comment by pchaigno** [comment]
And [34 grammars have been updated](https://github.com/pulls?page=1&q=is%3Apr+author%3Apchaigno+is%3Aclosed+ambiguous+OR+explicit+OR+compatible&utf8=%E2%9C%93) to fix discrepancies with the PCRE regex engine GitHub uses.

**Comment by lildude** [comment]
> Should this be a MINOR version update vs. PATCH? Do you consider support for new languages added functionality?

Good idea. I've not put too much thought into the versioning and I'm not sure what methodology/reasoning was used in the past but maybe now is a good time to start and to define a method for versioning the releases.

Think I should version this release as v5.1.0 instead?

**Comment by Caged** [comment]
5.1.0 seems good to me per semantic versioning :+1:

**Comment by goodmind** [comment]
how long it takes to update linguist on github?

**Comment by lildude** [comment]
Seconds once my PR there has been approved 😁 It's still pending approval so I'd expect it to be live by the end of next week.

**Comment by Alhadis** [comment]
Magical GitHub realm. Mortals not allowed.

Ssssh.

**Comment by lildude** [comment]
FYI: GitHub.com is now running with Linguist v5.1.0

**Comment by Alhadis** [comment]
~~~wast
(module i32)
(; WEW, HE'S RIGHT ;)
~~~

**Pull request merged**
