### PR TITLE
Add colour for HCL

### PR DESCRIPTION
**Pull request by tuunit**
## Description
Default color for HCL as decided by the Hashicorp Team: https://github.com/hashicorp/hcl/issues/577

## Checklist:
- [X] **I am changing the color associated with a language**
  
  - [x] I have obtained agreement from the wider language community on this color change.
    - https://github.com/hashicorp/hcl/issues/577

### CODE REVIEW

**Comment by Alhadis** [comment]
`#ccc` is simply the default colour GitHub assigns to languages that don't have one defined. If you intend to add a colour for HashiCorp Configuration Language (HCL), I'd suggest using one taken from HashiCorp's official branding instead.

**Comment by tuunit** [comment]
> `#ccc` is simply the default colour GitHub assigns to languages that don't have one defined. If you intend to add a colour for HashiCorp Configuration Language (HCL), I'd suggest using one taken from HashiCorp's official branding instead.

As HashiCorp doesn't have a official color branding for HCL. I raised an issue regarding the color in the official HCL repository.

**Comment by tuunit** [comment]
Hi @Alhadis, I got a reply from @crw (Technical Community Manager at Hashicorp) and they internally decided to use a purple colour.

**Review by lildude — APPROVED** [review]
LGTM. Thanks.

Note: this PR will not be merged until close to when the next release is made. See [here](https://github.com/github/linguist/blob/master/docs/troubleshooting.md#my-linguist-pr-has-been-merged-but-github-doesnt-reflect-my-changes) for more details.

**Comment by Alhadis** [comment]
> I got a reply from @crw (Technical Community Manager at Hashicorp) and they internally decided to use a purplish colour #844FBA.

Just for posterity, would you mind taking a screenshot of their response so that we have their response on record? (Feel free to blur out your e-mail address and/or name if you aren't comfortable making those details public)

**Comment by tuunit** [comment]
Hi @Alhadis,

the response is part of the linked issue: https://github.com/hashicorp/hcl/issues/577

@crw
https://www.linkedin.com/in/craigw/

image

**Comment by Alhadis** [comment]
Perfect, that's exactly what I had in mind. 👍 Thanks!

**Review by Alhadis — APPROVED** [review]

**Pull request merged**
