### PR TITLE
Adding @Alhadis to the maintainers list.

### PR DESCRIPTION
**Pull request by arfon**
@Alhadis has been doing some spectacular work on this project for many many months now. This PR is just reflecting reality.

Thanks for all of your work on Linguist @Alhadis ⚡️ 😍

### CODE REVIEW

**Comment by Alhadis** [comment]
My name is John Gardner and I admit I have a problem.

The problem being that I spend too much time on GitHub.

Actually, screw the part about that being a problem, I said nothing.

**Comment by Alhadis** [comment]
I guess that means I can [delete this](https://github.com/Alhadis/linguist) then... :(

Bye-bye firegoose.

**Comment by arfon** [comment]
> I guess that means I can delete this then... :(

Yup. Actually, pushing branches directly to `github/linguist` is preferred as your co-maintainers can then easily collaborate with you on them.

/ cc @pchaigno @larsbrinkhoff

**Comment by larsbrinkhoff** [comment]
Welcome to the team, @Alhadis!

**Comment by Alhadis** [comment]
Takk/tack/whatever :D

**Comment by pchaigno** [comment]
Congrats @Alhadis!

**Pull request merged**
