### PR TITLE
Grammars for 6 languages

### PR DESCRIPTION
**Pull request by pchaigno**
This is work in progress.

- TXL: [MikeHoffert/Sublime-Text-TXL-syntax](https://github.com/MikeHoffert/Sublime-Text-TXL-syntax) - [example](https://lightshow.githubapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2FMikeHoffert%2FSublime-Text-TXL-syntax%2Fmaster%2Ftxl.tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fgithub%2Flinguist%2Fmaster%2Fsamples%2FTXL%2FCal.txl&code=)
- G-Code: [robotmaster/sublime-text-syntax-highlighting](https://github.com/robotmaster/sublime-text-syntax-highlighting) - [example](https://lightshow.githubapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Frobotmaster%2Fsublime-text-syntax-highlighting%2Fmaster%2Fbin%2F%2528GCode%2529.tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fpchaigno%2Flinguist%2Fmaster%2Fsamples%2FG-code%2Fsquare.g&code=)
- Grace: [zmthy/grace-tmbundle](https://github.com/zmthy/grace-tmbundle) - [example](https://lightshow.githubapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fzmthy%2Fgrace-tmbundle%2Fmaster%2FSyntaxes%2FGrace.tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fgithub%2Flinguist%2Fmaster%2Fsamples%2FGrace%2Fgrace_IDE.grace&code=)
- Ox: [andreashetland/sublime-text-ox](https://github.com/andreashetland/sublime-text-ox) - [example](https://lightshow.githubapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fandreashetland%2Fsublime-text-ox%2Fmaster%2FOx.tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fgithub%2Flinguist%2Fmaster%2Fsamples%2FOx%2Fparticle.oxo&code=) (not great but it's a start)
- eC: [ecere/ec.tmbundle](https://github.com/ecere/ec.tmbundle) - [example](https://lightshow.githubapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fecere%2Fec.tmbundle%2Fmaster%2FSyntaxes%2FeC.tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fecere%2Fecere-sdk%2Fede06d24d3561996092a7d90b2423b9cae9f66b7%2Fide%2Fsrc%2Fdesigner%2FDesigner.ec&code=)

The following grammars have alternatives. I chose them based on the results from Lightshow and respect of [naming conventions](http://manual.macromates.com/en/language_grammars#naming_conventions) as a second factor, all opinions welcomed!
- LOLCODE: [marioaquino/LOLcode.tmbundle](https://github.com/marioaquino/LOLcode.tmbundle) - [example](https://lightshow.githubapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fmarioaquino%2FLOLcode.tmbundle%2Fmaster%2FSyntaxes%2FLolcode.tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fgithub%2Flinguist%2Fmaster%2Fsamples%2FLOLCODE%2FLOLTracer.lol&code=) - [alternative](https://lightshow.githubapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2FCodaFi%2FLOLCODE.tmLanguage%2Fmaster%2FLOLCODE.tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fgithub%2Flinguist%2Fmaster%2Fsamples%2FLOLCODE%2FLOLTracer.lol&code=)
- Inno Setup: [idleberg/InnoSetup-Sublime-Text](https://github.com/idleberg/InnoSetup-Sublime-Text) - [example](https://lightshow.githubapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fidleberg%2FInnoSetup-Sublime-Text%2Fmaster%2FInnoSetup.tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fcoapp-packages%2Fexpat%2F21e128c023ff2c55e05f230e5758e6a01e362c2f%2Fwin32%2Fexpat.iss&code=) - [alternative](https://lightshow.githubapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fshadyproject%2Fsublime-inno-setup%2Fmaster%2FIss.tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fcoapp-packages%2Fexpat%2F21e128c023ff2c55e05f230e5758e6a01e362c2f%2Fwin32%2Fexpat.iss&code=)

### CODE REVIEW

**Comment by aroben** [comment]
Nice! Thanks for all the example links.

**Comment by arfon** [comment]
@pchaigno - is this still work in progress or can this be merged?

**Comment by pchaigno** [comment]
Still work in progress.
@arfon I'll ping you when it's ready.

**Comment by pchaigno** [comment]
@Xe @wil93 Could I have your opinion on the two possible grammars for LOLCODE?

**Comment by Xe** [comment]
I like the latter more.

**Comment by wil93** [comment]
The first one seems more accurate. Sometimes it looks like the second one mixes up keywords and non-keywords (see numbers) also, for the single line `BTW` comment, only the first word is highlighted.

**Comment by pchaigno** [comment]
@Xe @wil93 I chose the first one because it looked like the single-line comments weren't highlighted correctly. Thank you for confirming that and for your comments! I'll stick with the first one then.

@arfon This PR is ready. I still have two other grammars with alternatives but I'll make new PRs to avoid pinging everyone into a single one.

**Comment by arfon** [comment]
:+1: thanks for this @pchaigno

**Comment by aroben** [comment]
This is now live on github.com.

**Pull request merged**
