### PR TITLE
Add Fennel

### PR DESCRIPTION
**Pull request by p00f**
## Description
Adds the [Fennel](https://fennel-lang.org) programming language

## Checklist:

- [ ] **I am associating a language with a new file extension.**
  - [ ] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      
      - https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [x] **I am adding a new language.**
I got 21 unique (non-fork) repos in the first 8 pages of the search results. Since there are 100 pages in the results, I think it meets the criteria.
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?q=extension%3Afnl&type=Code&l=&l=
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [The fennel repl](https://github.com/bakpakin/Fennel/blob/main/src/fennel/repl.fnl)
      - [Fennel utils](https://github.com/bakpakin/Fennel/blob/main/src/fennel/utils.fnl)
    - Sample license(s): MIT
  
  - [x] I have included a syntax highlighting grammar: https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fgithub.com%2Fkongeor%2Fvsc-fennel%2Fblob%2Fmaster%2Fsyntaxes%2Ffennel.tmLanguage.json&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fbakpakin%2FFennel%2Fblob%2Fmain%2Fsrc%2Ffennel%2Futils.fnl&code=
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension. -> Not applicable, extension is unique

- [ ] **I am fixing a misclassified language**
  - [ ] I have included a new sample for the misclassified language:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am changing the source of a syntax highlighting grammar**
  
  - Old: https://github-lightshow.herokuapp.com/
  - New: https://github-lightshow.herokuapp.com/

- [ ] **I am updating a grammar submodule**
  

- [ ] **I am adding new or changing current functionality**
  
  - [ ] I have added or updated the tests for the new or changed functionality.

- [ ] **I am changing the color associated with a language**
  
  - [ ] I have obtained agreement from the wider language community on this color change.
    - [URL to public discussion]
    - [Optional: URL to official branding guidelines for the language]

### CODE REVIEW

**Comment by p00f** [comment]
The colour `#fff3d7` is taken from https://fennel-lang.org

**Comment by p00f** [comment]
cc @technomancy @bakpakin

**Comment by lildude** [comment]
Usage checks out, just 😉:

Total files found: 2529
Unique public user/repos: 244
Unique owners: 182

**Comment by p00f** [comment]
Can you approve the tests?

**Comment by p00f** [comment]
Can you approve the checks?

**Comment by p00f** [comment]
The first one passed, sorry for merging again

**Review by lildude — APPROVED** [review]

**Comment by p00f** [comment]
Thanks!

**Comment by p00f** [comment]
Any idea when this will roll out?

**Comment by lildude** [comment]
I'm aiming for the week of 19 July.

**Comment by p00f** [comment]
Thanks

**Comment by p00f** [comment]
Should this be working by now (after 7.16.00 was released) ?

**Comment by lildude** [comment]
Not yet, as I'm not deploying to GitHub.com until tomorrow as stated in the release PR: https://github.com/github/linguist/pull/5489

**Comment by p00f** [comment]
Ah thanks

**Comment by lildude** [comment]
Now live.

**Comment by p00f** [comment]
Thanks!

**Pull request merged**
