### PR TITLE
add Vyper smart contract language (Ethereum)

### PR DESCRIPTION
**Pull request by davidhq**
Adding second Ethereum language Vyper (apart from Solidity)

Link to search of language use on github: https://github.com/search?q=extension%3Avy+NOT+struct&type=Code

Language documentation:
https://vyper.readthedocs.io/en/latest/index.html

## Checklist:

- [ ] **I am associating a language with a new file extension.**
  - [x] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      
      - https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  
  - [x] I have included a syntax highlighting grammar: https://github-lightshow.herokuapp.com/
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

- [ ] **I am fixing a misclassified language**
  - [ ] I have included a new sample for the misclassified language:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am changing the source of a syntax highlighting grammar**
  
  - Old: https://github-lightshow.herokuapp.com/
  - New: https://github-lightshow.herokuapp.com/
  
- [ ] **I am updating a grammar submodule**
  

- [ ] **I am adding new or changing current functionality**
  
  - [ ] I have added or updated the tests for the new or changed functionality.

### CODE REVIEW

**Comment by davidhq** [comment]
I was also surprised to see how little is Vyper used on GitHub for now ^_^ Vyper is ment as a big improvement to Solidity and it's only second (almost?) production-ready  Ethereum language (so two languages only for now, not more). A prominent rising project in the space - Uniswap exchange using Vyper tells us something though, I think it's worth 'coloring' the language and that was a signal for me to make a highlighter for the Sublime Ethereum package.

It's totally fair to reject this pull request at this time! I do suggest the following though:

- I will improve the highlighter itself a bit more
- will resolve test failures

/Microsoft/ could also consider adding this language a bit earlier than usual to show commitment to open source and ability to spot various trends :) It's not a random language.

Until soon :) thank you

**Comment by davidhq** [comment]
During the day I remembered something else: Just a bit of general thinking, not obvious at first ...

Smart Contracts are different ... usually there is just a few files per BIG project... so this is not like regular code when there are hundreds or thousands of files per mid-size project... 

For example MakerDAO (one of the biggest projects in space):

Single Collateral: https://github.com/makerdao/sai/tree/master/src
Multi Collateral: https://github.com/makerdao/dss/tree/master/src

This is all there... rather interesting. Your argument for Vyper is valid but what I just described is easy to miss and should also be considered. 

Thank you again for fixing Solidity highlighting again and talk later.

**Comment by pchaigno** [comment]
> Smart Contracts are different ... usually there is just a few files per BIG project... so this is not like regular code when there are hundreds or thousands of files per mid-size project...

That's not going to be an issue since our rule of thumb for inclusion in Linguist is in number of *repositories*, not files.

I'm closing this for now. Please reopen when Vyper reached the *hundreds of repositories* threshold.

**Comment by davidhq** [comment]
@pchaigno  Deal... but it does matter a bit: if there is 200 files currently, this could mean 100 repositories in this case while in other more usual programming languages it could mean something like 5 repos... I don't know where to see exactly how many repos are these 200 files that search returns... I would guess 50 or so... so how to get this number easily without writing some script to analyze the results?

**Comment by pchaigno** [comment]
> so how to get this number easily without writing some script to analyze the results?

@Alhadis did exactly that: https://github.com/Alhadis/Harvester.

**Comment by davidhq** [comment]
ok, so this is 'Harvester' that was mentioned above. thank you both and bye

**Comment by Th0rgal** [comment]
Has the addition of vyper been reconsidered since then? The development of the project continues and I think its recognition by github would be a low cost step towards its adoption.

**Comment by davidhq** [comment]
> Has the addition of vyper been reconsidered since then? The development of the project continues and I think its recognition by github would be a low cost step towards its adoption.

It is live since today

Add Vyper smart contract language #5778
https://github.com/github/linguist/pull/5778

Examples of live syntax highlighting (provided that `.gitattributes` with `*.vy linguist-language=Python` is not present)
https://github.com/vyperlang/vyper/blob/master/examples/tokens/ERC20.vy
https://github.com/vyperlang/vyper/blob/master/examples/crowdfund.vy

**Pull request closed without merging**
