### PR TITLE
Add Lex and Yacc languages

### LINKED ISSUE #2060: Common Lisp files ending in .l not being recognised
Please see https://github.com/hscells/CSC466 for example.

Thank you.

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
This adds the Lex and Yacc languages.

The new file extensions are mostly exclusive to these languages (the estimates in the table are conservative, because it's hard to search for Lex and Yacc), except for `.l`.

| Extension | Language Files | Total files | Comment
| --- | --- | --- | ---
| `.l` | [135k](https://github.com/search?p=100&q=extension%3Al+%25%25+OR+yy&ref=searchresults&type=Code&utf8=%E2%9C%93) | 403k | 16k Groff, 6k Lisp
| `.lex` | [9k](https://github.com/search?p=100&q=extension%3Alex+%25%25+OR+yy&ref=searchresults&type=Code&utf8=%E2%9C%93) | 17k
| `.yacc` | [294](https://github.com/search?q=extension%3Ayacc+%25%25&type=Code) | 390
| `.yy` | [3k](https://github.com/search?q=extension%3Ayy+%25%25&type=Code) | 5k
| `.bison` | [40](https://github.com/search?q=extension%3Abison+%25%25&type=Code) | 211

Also:
* Fixes #2060, #2379 which request [`.l` for Lisp](https://github.com/search?q=extension%3Al+defun+OR+defmacro&type=Code).
* Adds `.l` to Groff ([16k files](https://github.com/search?q=extension%3Al+th+OR+pp&&type=Code))
* Groups `JFlex` ("Java Flex") under Lex.
* Groups `Bison` ("GNU Yacc") under Yacc.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
Ping @arfon, @bkeepers.

**Comment by arfon** [comment]
@larsbrinkhoff - @pchaigno note [here](https://github.com/github/linguist/issues/2060#issuecomment-72371615) that a number of these look to be `C#` or `C/C++`. Should we be adding those too?

**Comment by larsbrinkhoff** [comment]
@arfon I answered [here](https://github.com/github/linguist/issues/2060#issuecomment-72375049) that most are actually Lex files with embedded C/C++/C#.  Adding `%%` to the search terms confirms this.

**Comment by larsbrinkhoff** [comment]
@arfon E.g. compare

https://github.com/search?utf8=%E2%9C%93&q=extension%3Al+namespace
vs
https://github.com/search?utf8=%E2%9C%93&q=extension%3Al+namespace+%25%25

and

https://github.com/search?utf8=%E2%9C%93&q=extension%3Al+include
vs
https://github.com/search?utf8=%E2%9C%93&q=extension%3Al+include+%25%25

**Comment by arfon** [comment]
:+1: Ok thanks for the extra information @larsbrinkhoff

**Pull request merged**
