### PR TITLE
need to import json module

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by pchaigno** [comment]
@MartinNowak Thanks for the pull request! What's the error you're trying to fix?
I'm surprised @arfon didn't need it when testing...?

**Comment by arfon** [comment]
I'm pretty sure I _don't_ need to do this myself. @MartinNowak are you running `bundle exec rake benchmark:generate`?

**Comment by arfon** [comment]
🎏 flagging this as stale 🎏

**Comment by brandonblack** [comment]
Closing since this has open questions that haven't been resolved. If we come back to this and decide we need it please re-open.

**Pull request closed without merging**
