### PR TITLE
Add support for RPM Spec files

### LINKED ISSUE #3121: Support RPM spec files
Please add support for RedHat Package Manager's `.spec` files as specified by http://www.rpm.org/max-rpm/s1-rpm-build-creating-spec-file.html

Thanks,
Veesa

### PR DESCRIPTION
**Pull request by Alhadis**
Okay, let's [try this again](https://github.com/github/linguist/pull/3160#issuecomment-242977022).

TAKE TWO

----

Fixes #3121.

Despite having a generic-looking extension, searching for [`.spec`](https://github.com/search?q=extension%3Aspec+NOT+nothack&type=Code) files yields strangely consistent results.

#### Sources:
- [`manos.spec`](https://github.com/jacksonh/manos/blob/300450cd5c8a146cdf5e9cbaa837ecccfd8ab951/release/manos.spec), [`spec.linux.spec`](https://github.com/caiguanhao/portablizer/blob/04f27664f6788814bfc63646c765985560b7fe00/spec.linux.spec): MIT/X11
- [`erlang-erlydtl.spec`](https://github.com/icheishvili/rpms/blob/6f88d5ee39ce3696b58563d8e3aac16c796a0c9f/erlang-erlydtl.spec)
- [`apache.spec`](https://github.com/sergiomb2/Apache-1.3_mod_perl/blob/496dbd64774ab4937a382fc49f87e75d2bbbd98e/rpmbuild/SPECS/apache.spec)
- [`any.spec`](https://github.com/datagraph/spira/blob/0c7d14e2fc5b0a4a7e3a1ea56c6c5243eb9cf9da/spec/types/any.spec): Unlicense

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
Again, possibly around 40% of all `.spec` files are not related to RPM:

https://github.com/github/linguist/pull/3160#issuecomment-241633010

**Comment by Alhadis** [comment]
... I was hoping of downloading these files and finding out something insightful before you got here, but Australian Internet speed had other ideas.

Should've known, eh?

**Comment by larsbrinkhoff** [comment]
I'll get those files using my Swedish internet superpowers.  But can you receive them?

**Comment by Alhadis** [comment]
Oh, I'm going through them right now. The downloads finished at ~6am but I finally lost consciousness at that point.

Most of these are just ad-hoc INI files, though many are also Ruby. Will post the [results here](https://github.com/Alhadis/Linguist-Heuristics) once I've finished analysing them.

**Comment by Alhadis** [comment]
Okay, I've gone through and analysed each file by hand; anything I didn't recognise or were too ambiguous was dumped into the [Unknown](https://github.com/Alhadis/Linguist-Heuristics/tree/spec/Results/Unknown) folder.

**Total files:** 2930
**Unique files:** 1389 (47.4% of total)

---------------------------------
| Type          |  Files |     % |
|---------------|-------:|------:|
| [Unknown]     |    515 | 37%   |
| [Ruby]        |    194 | 14%   |
| [Python]      |    190 | 13.6% |
| [Perl]        |    109 | 7.85% |
| [Erlang]      |    108 | 7.77% |
| [Java]        |     88 |…**C**…|
| [PostgreSQL]  |     76 |…**A**…|
| [RPM]         |     33 |…**N**…|
| [Assembly]    |     23 |…**'**…|
| [XML]         |     18 |…**T**…|
| [Markdown]    |     12 |…**B**…|
| [Binary/Data] |      5 |…**E**…|
| [JavaScript]  |      5 |…**F**…|
| [Make]        |      5 |…**U**…|
| [Diff]        |      3 |…**C**…|
| [JSON]        |      2 |…**K**…|
| [PHP]         |      2 |…**E**…|
| [TeX]         |      1 |…**D**…|
----------------------------------

[Assembly]: https://github.com/Alhadis/Linguist-Heuristics/tree/spec/Results/ASM
[Binary/Data]: https://github.com/Alhadis/Linguist-Heuristics/tree/spec/Results/Binary%20or%20Data
[Diff]: https://github.com/Alhadis/Linguist-Heuristics/tree/spec/Results/Diff
[Erlang]: https://github.com/Alhadis/Linguist-Heuristics/tree/spec/Results/Erlang
[JavaScript]: https://github.com/Alhadis/Linguist-Heuristics/tree/spec/Results/JS
[JSON]: https://github.com/Alhadis/Linguist-Heuristics/tree/spec/Results/JSON
[Java]: https://github.com/Alhadis/Linguist-Heuristics/tree/spec/Results/Java
[Make]: https://github.com/Alhadis/Linguist-Heuristics/tree/spec/Results/Make
[Markdown]: https://github.com/Alhadis/Linguist-Heuristics/tree/spec/Results/Markdown
[PHP]: https://github.com/Alhadis/Linguist-Heuristics/tree/spec/Results/PHP
[Perl]: https://github.com/Alhadis/Linguist-Heuristics/tree/spec/Results/Perl
[PostgreSQL]: https://github.com/Alhadis/Linguist-Heuristics/tree/spec/Results/PostgreSQL
[Python]: https://github.com/Alhadis/Linguist-Heuristics/tree/spec/Results/Python
[RPM]: https://github.com/Alhadis/Linguist-Heuristics/tree/spec/Results/RPM
[Ruby]: https://github.com/Alhadis/Linguist-Heuristics/tree/spec/Results/Ruby
[TeX]: https://github.com/Alhadis/Linguist-Heuristics/tree/spec/Results/TeX
[Unknown]: https://github.com/Alhadis/Linguist-Heuristics/tree/spec/Results/Unknown
[XML]: https://github.com/Alhadis/Linguist-Heuristics/tree/spec/Results/XML

Most of the recognisable results were either Python or Ruby, but I'm not convinced the extension's usage is prevalent enough in either language to warrant being added as an extension.

Thoughts?

**Comment by pchaigno** [comment]
Were you able to quantify how many of these files have a shebang or modeline? If they do, they won't be an issue and it looks like many of the Python and Ruby files do :smiley:

**Comment by Alhadis** [comment]
Modeline usage
============

Erlang
-------------
* [compiler.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Erlang/compiler.spec)
* [cover.spec.4](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Erlang/cover.spec.4)
* [eunit.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Erlang/eunit.spec)
* [hipe.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Erlang/hipe.spec)
* [jinterface.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Erlang/jinterface.spec)
* [syntax_tools.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Erlang/syntax_tools.spec)

Perl
------------
* [modByteString.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Perl/modByteString.spec)
* [modCompat.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Perl/modCompat.spec)
* [modCompilerSupport.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Perl/modCompilerSupport.spec)
* [modEvent.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Perl/modEvent.spec)
* [modException.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Perl/modException.spec)
* [modGFDB.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Perl/modGFDB.spec)
* [modGFDP.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Perl/modGFDP.spec)
* [modGFSB.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Perl/modGFSB.spec)
* [modGFSP.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Perl/modGFSP.spec)
* [modParser.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Perl/modParser.spec)
* [modTimer.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Perl/modTimer.spec)
* [modWeakDictionary.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Perl/modWeakDictionary.spec)
* [modWin32.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Perl/modWin32.spec)
* [modWord.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Perl/modWord.spec)

Ruby
-----------
* [action.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Ruby/action.spec)
* [action.spec.1](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Ruby/action.spec.1)
* [api.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Ruby/api.spec)
* [comp.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Ruby/comp.spec)
* [comp.spec.1](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Ruby/comp.spec.1)
* [constraint.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Ruby/constraint.spec)
* [content.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Ruby/content.spec)
* [contenter_uri.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Ruby/contenter_uri.spec)
* [copier.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Ruby/copier.spec)
* [env.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Ruby/env.spec)
* [env.spec.1](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Ruby/env.spec.1)
* [environment.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Ruby/environment.spec)
* [environment.spec.1](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Ruby/environment.spec.1)
* [error.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Ruby/error.spec)
* [event.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Ruby/event.spec)
* [example.spec.1](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Ruby/example.spec.1)
* [form_array.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Ruby/form_array.spec)
* [hash_ttl.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Ruby/hash_ttl.spec)
* [Match.spec.1](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Ruby/Match.spec.1)
* [Metadata.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Ruby/Metadata.spec)
* [MMCommon.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Ruby/MMCommon.spec)
* [observer.spec.2](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Ruby/observer.spec.2)
* [ParanoidPackrat.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Ruby/ParanoidPackrat.spec)
* [parse.spec.2](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Ruby/parse.spec.2)
* [pending_transition.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Ruby/pending_transition.spec)
* [phrase.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Ruby/phrase.spec)
* [PPCommon.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Ruby/PPCommon.spec)
* [PPConfig.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Ruby/PPConfig.spec)
* [PPIrb.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Ruby/PPIrb.spec)
* [red_steak.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Ruby/red_steak.spec)
* [selector.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Ruby/selector.spec)
* [sort.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Ruby/sort.spec)
* [sort.spec.2](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Ruby/sort.spec.2)
* [spider_csrf_test.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Ruby/spider_csrf_test.spec)
* [synch_async.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Ruby/synch_async.spec)
* [urlparse_test.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Ruby/urlparse_test.spec)
* [version_debian.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Ruby/version_debian.spec)
* [version_set.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Ruby/version_set.spec)

Python files WITHOUT modelines:
--------------------------------------------------
* [albumart-qt-w32.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Python/albumart-qt-w32.spec)
* [albumart-qt.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Python/albumart-qt.spec)
* [calc.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Python/calc.spec)
* [indentation.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Python/indentation.spec)
* [m64py.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Python/m64py.spec)
* [m64py.spec.1](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Python/m64py.spec.1)
* [main.spec.1](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Python/main.spec.1)
* [MapBom.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Python/MapBom.spec)
* [minimal.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Python/minimal.spec)
* [myclass.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Python/myclass.spec)
* [myclass.spec.1](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Python/myclass.spec.1)
* [opensesame.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Python/opensesame.spec)
* [process_multiple_lines.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Python/process_multiple_lines.spec)
* [process_single_line.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Python/process_single_line.spec)
* [random.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Python/random.spec)
* [spec.linux.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Python/spec.linux.spec)
* [spec.mac.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Python/spec.mac.spec)
* [spec.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Python/spec.spec)
* [spec.win.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Python/spec.win.spec)
* [WhereUsed.spec](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/Results/Python/WhereUsed.spec)

**Comment by larsbrinkhoff** [comment]
Well, 1% of 380000 files is still nearly four thousand files, which may well be "hundred of repositories".  But it does look like a typical "can of worms" file extension.

In my opinion, this is best driven by users.  If someone complains about a `.spec` file being misclassified, only then add support for that language.  So right now, RPM is on the table, and maybe a few top picks from @Alhadis's breakdown.

**Comment by Alhadis** [comment]
Erh, is anybody else able to [run this search](https://github.com/search?q=extension%3Aspec+NOT+nothack&type=Code) while signed out from GitHub? :| Try opening it in an incognito window; it's giving the old **"We could not perform this search; must include at least one user, organisation, or repository"** again.

I [recently started work](https://github.com/Alhadis/Harvester) on a tool to help with gathering files for Linguist-work, and noticed today it wasn't working anymore... :S

**Comment by larsbrinkhoff** [comment]
In my opinion, if you add Ruby and Python, and a nice heuristic for `.spec`, this would be good to go.

**Comment by Alhadis** [comment]
Actually, a heuristic wasn't necessary. :) [See here](https://github.com/Alhadis/Linguist-Heuristics/blob/spec/results.txt).

**Comment by larsbrinkhoff** [comment]
All the better!

@afron, what do you think?

**Comment by arfon** [comment]
:+1:

**Pull request merged**
