### PR TITLE
Add High Level Assembly language

### LINKED ISSUE #5169: High Level Assembly language is not recognized
Hello dear moderators. I have a repository with `*.hla` files, which is source code from the High Level Assembly programming language, also known as simply HLA. I want them to show up as just **Assembly**. But unfortunately Github does not mark the programming language in my repository. Please dear moderators fix this issue.

## Language name

High Level Assembly (a variant of Assembly Language)

## URL of example repository

https://github.com/Krebrov001/HLA-Projects

## URL of syntax highlighting grammar

https://github.com/Krebrov001/HLA-Projects/blob/master/hla.xml

## Most popular extensions

`*.hla`

## Detected language

Currently any `*.hla` files are not being detected as any language at all.

### PR DESCRIPTION
**Pull request by Nixinova**
Closes #5169.

Usage seems to check out: [search 'extension:hla'](https://github.com/search?p=8&q=extension%3Ahla&type=Code) shows 12K files.

[Sample](https://github.com/mcandre/hla/blob/cea2b64754194e5dfb19e1961c1d1048d5221a52/windows-stdlib/strings/str_cpyz.hla) under public domain.

Group under Assembly.

<s>Syntax highlighter provided in #5169: https://github.com/Krebrov001/HLA-Projects/blob/master/hla.xml. Added as gitmodule.</s>

### CODE REVIEW

**Comment by Nixinova** [comment]
Added the grammar but how do I get it to point to file `hla.xml`?

**Comment by Nixinova** [comment]
What am I missing? "Fetch grammar submodules" test just throws `Error: Process completed with exit code 1.` with no explanation.

**Comment by lildude** [comment]
Scroll up and you'll find the error:

```
Error updating vendor/grammars/High Level Assembly
error: pathspec 'vendor/grammars/High Level Assembly' did not match any file(s) known to git
```

You need to add the grammar as a submodule.

**Comment by Nixinova** [comment]
Did I not in 9c8aeb665370fef34b4fe0bfd0136bb28dc4d56a?

**Comment by Nixinova** [comment]
...I have to register the submodules via the command line, don't I...

**Comment by Nixinova** [comment]
[Lightshow](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=xml&grammar_url=https%3A%2F%2Fgithub.com%2FKrebrov001%2FHLA-Projects%2Fblob%2Fmaster%2Fhla.xml&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fgithub%2Flinguist%2Fblob%2F53c729ce381786d672fa92d5e0dcc37d130fd9ac%2Fsamples%2FHigh%2520Level%2520Assembly%2Fstr_cpyz.hla&code=%7B%25-+for+item+in+collections.all+%25%7D%0D%0A+%7B%25-+if+not+item.data.sitemapIgnore+%25%7D%0D%0A++%3Curl%3E%0D%0A++++%3Cloc%3Ehttps%3A%2F%2Fnixinova.com%7B%7B+item.data.permalink+%7C+replace%28%27.html%27%2C+%27%27%29+%7D%7D%3C%2Floc%3E%0D%0A++++%3Cchangefreq%3Ealways%3C%2Fchangefreq%3E%0D%0A++++%7B%25+if+item.data.date+%25%7D%3Clastmod%3E%7B%7B+item.data.date+%7D%7D%3C%2Flastmod%3E%7B%25+endif+%25%7D%0D%0A++%3C%2Furl%3E%0D%0A+%7B%25-+endif+%25%7D%0D%0A%7B%25-+endfor+%25%7D) throws `Error parsing XML grammar: Unimplemented element`; is that an issue?

**Comment by lildude** [comment]
> I have to register the submodules via the command line, don't I?..

Yup. Thankfully this is pure git so you won't need to fight dependencies etc.

**Comment by lildude** [comment]
> [Lightshow](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=xml&grammar_url=https%3A%2F%2Fgithub.com%2FKrebrov001%2FHLA-Projects%2Fblob%2Fmaster%2Fhla.xml&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fgithub%2Flinguist%2Fblob%2F53c729ce381786d672fa92d5e0dcc37d130fd9ac%2Fsamples%2FHigh%2520Level%2520Assembly%2Fstr_cpyz.hla&code=%7B%25-+for+item+in+collections.all+%25%7D%0D%0A+%7B%25-+if+not+item.data.sitemapIgnore+%25%7D%0D%0A++%3Curl%3E%0D%0A++++%3Cloc%3Ehttps%3A%2F%2Fnixinova.com%7B%7B+item.data.permalink+%7C+replace%28%27.html%27%2C+%27%27%29+%7D%7D%3C%2Floc%3E%0D%0A++++%3Cchangefreq%3Ealways%3C%2Fchangefreq%3E%0D%0A++++%7B%25+if+item.data.date+%25%7D%3Clastmod%3E%7B%7B+item.data.date+%7D%7D%3C%2Flastmod%3E%7B%25+endif+%25%7D%0D%0A++%3C%2Furl%3E%0D%0A+%7B%25-+endif+%25%7D%0D%0A%7B%25-+endfor+%25%7D) throws `Error parsing XML grammar: Unimplemented element`; is that an issue?

Yes, with the grammar. That is not a TextMate-compatible grammar.

**Comment by Nixinova** [comment]
> That is not a TextMate-compatible grammar.

Okay, will revert then

**Comment by lildude** [comment]
Can you please state in the original note of this PR where the sample files came from and the license of each.

Despite there being more than >12k files, they're concentrated in surprisingly few repos:

Total files found: 12618
Unique public user/repos: 71
Unique owners: 64

**Comment by Krebrov001** [comment]
@lildude Here is another syntax highlighting grammar for HLA programming language, this time for vim text editor:
https://github.com/jmahler/hla.vim
Maybe it would work?

**Comment by Nixinova** [comment]
I don't think thats in the right format for Linguist.

**Comment by lildude** [comment]
Yup, that won't work. The grammar needs to be a TextMate compatible grammar.

**Comment by Krebrov001** [comment]
@lildude I don't know what is a TextMate compatible grammar or how to create one. Can we have the language support without syntax highlighting for now, as far as the files are being recognized in the Languages section of a repository? Or maybe can you create a TextMate compatible grammar for me based on the Notepad++ or vim syntax highlighting files. I am yet unexperienced with such things.

**Comment by lildude** [comment]
Yes, we can add a language without a grammar. I'm not up to the task of creating a grammar, but maybe @Alhadis can.

That all said, there's no hurry as this language is still a looooong way from being popular enough for merging this PR.

**Comment by Nixinova** [comment]
Closing for now as it'll be a while until usage is enough.

**Comment by Krebrov001** [comment]
So I see that I would have to find out how to implement a language grammar by myself, for adding support for the HLA programming language? Can anyone provide me some directions about how to do that?

**Comment by Nixinova** [comment]
Create a tmLanguage grammar file to tokenise various aspects of the language. For example I have a few created at https://github.com/Nixinova/tmLanguage/tree/main/grammars.

**Pull request closed without merging**
