### PR TITLE
add syntax Latino

### PR DESCRIPTION
**Pull request by jarriztg**

### CODE REVIEW

**Comment by pchaigno** [comment]
From the contribution guidelines:

> Open a pull request, linking to a [GitHub search result](https://github.com/search?utf8=%E2%9C%93&q=extension%3Aboot+NOT+nothack&type=Code&ref=searchresults) showing in-the-wild usage.

**Comment by jarriztg** [comment]
And how can i do a pr in that link? 
I dont find the option to do it

**Comment by jarriztg** [comment]
In any repository or one 
specific?

**Comment by Alhadis** [comment]
How many people are using Latino? How many people have Latino code hosted on GitHub?
  
There are [7,429 results](https://github.com/search?q=extension%3Alat+NOT+nothack&type=Code), but I can't see any that are written in Latino.
  
Languages should be used by hundreds of people before they are registered on GitHub:
  
> We try only to add languages once they have some usage on GitHub. In most cases we prefer that each new file extension be in use in hundreds of repositories before supporting them in Linguist.

==============

Sabes cuántos repositorios en Github usan el lenguaje Latino?

Para poder aceptar la inclusión de un nuevo lenguaje en Linguist, este debe ser usado en cientos de repositorios, de lo contrario no será tenido en consideración.

Gracias.

**Comment by jarriztg** [comment]
Sin problema. Cerraré el pull request.

**Pull request closed without merging**
