### PR TITLE
.vhost as a Nginx extension

### PR DESCRIPTION
**Pull request by pchaigno**
This pull request adds `.vhost` as Nginx extension as asked for in #2201.
I also explicitly added `nginx.conf` as a filename (there was already a sample file).

See [examples on GitHub](https://github.com/search?p=1&q=extension%3Avhost+NOT+djdhfidkhfjskdjfkf&ref=searchresults&type=Code&utf8=%E2%9C%93).

### CODE REVIEW

**Comment by bkeepers** [comment]
Looks like it should also be an apache extension: https://github.com/patricksimpson/add-host/blob/7f94f9748bf6d5bc6c839ce44573b92264bf3708/config/apache.vhost

**Comment by pchaigno** [comment]
@bkeepers I added it. Hopefully, since these are configuration files, the Bayesian classifier will be able to distinguish them.

**Comment by arfon** [comment]
:+1: thanks @pchaigno. Sorry it's taken me _ages_ to get to this :crying_cat_face:

**Comment by pchaigno** [comment]
No worries ;)

**Pull request merged**
