### PR TITLE
Added support for Rascal to linguist

### PR DESCRIPTION
**Pull request by ahmadsalim**
This adds support for Rascal (http://www.rascal-mpl.org/) syntax highlighting and code detection to GitHub linguist, and thus fixes usethesource/rascal#152 .
The language is widely used in the wild, as seen in the following [GitHub search](https://github.com/search?utf8=%E2%9C%93&q=extension%3Arsc+NOT+nothack&type=Code&ref=searchresults), and this PR has support from the official Rascal team (cc: @DavyLandman).

Thank you in advance for your consideration.

### CODE REVIEW

**Comment by ahmadsalim** [comment]
Apologies for the many Travis runs, I had executed the testing locally in a wrong way before, but it should work correctly now.

**Comment by ahmadsalim** [comment]
Thanks 👍

**Comment by brandonblack** [comment]
@ahmadsalim this looks good. If you can take a moment to sort out the merge conflict, we'll pull this in. 👍

**Comment by ahmadsalim** [comment]
@brandonblack Thank you for the review, I have resolved the merge conflicts now. 👍

**Comment by ahmadsalim** [comment]
I just reran the script as required. I am unsure why it picked such a large language id.

**Comment by pchaigno** [comment]
> I am unsure why it picked such a large language id.

Language ids are generated randomly since #3284 was merged.

**Comment by DavyLandman** [comment]
From the rascal team we want to thank everyone involved in getting this merged in master 🎉 . Finally, our code has escaped the bleak black-white color scheme. Together with @ahmadsalim we are working on some small fixes, so in the future we might have a new pull request with an updated submodule pointer.

**Comment by pchaigno** [comment]
Changes to grammars (submodules) are automatically picked up by Linguist with each new release. There'll be no need to submit new pull request here for that :bowtie:

**Comment by Alhadis** [comment]
> Finally, our code has escaped the bleak black-white color scheme.

Yeah, your logo took its place [when I traced it in Illustrator](https://github.com/Alhadis/FileIcons/blob/51871d0bdd607b3617dd77c460aac8e419f7b682/svg/Rascal.svg).

Geen dank. =)

**Pull request merged**
