### PR TITLE
Add EusLisp

### PR DESCRIPTION
**Pull request by wkentaro**
GitHub search result: https://github.com/search?utf8=%E2%9C%93&q=extension%3Al+eus+euslisp+roseus&type=Code&ref=searchresults
EusLisp GitHub Repo: https://github.com/euslisp/EusLisp

### CODE REVIEW

**Comment by phase** [comment]
Your color is conflicting with Harbour, and you might want to check the [other errors](https://travis-ci.org/github/linguist/builds/61049406).

**Comment by larsbrinkhoff** [comment]
Also, most uses of `.l` may be Lex.

**Comment by wkentaro** [comment]
Hmm.. I'd like make `.l` files added syntax highlights as lisp filetype.
I also read #2060, and finally is that the only solution changing the extension to `.lisp` or `.lsp`?

**Comment by larsbrinkhoff** [comment]
Hello @wkentaro,

First, I'm not from GitHub, so I can't make any decisions on this.  However, this would be my advice:

Your search only results 74 files (currently).  If we do this:
https://github.com/search?q=extension%3Al+defun&type=Code
we find more than 6000 `.l` files which are probably Lisp.  That number if much more compelling for GitHub to make a change.

However, there are many other `.l` files which we need to consider.  Other users might complain if they were to display as `Lisp`.

Another option beside changing the file names may be to add a `.gitattributes` to your repository with this line:

    *.l linguist-language=Lisp

**Comment by wkentaro** [comment]
Thanks for your information, and these're very helpful for me.
Considering other `.l` files which is not `Lisp`, I think I should use `.gitattributes`.
I tried using it and in stats of number of codes it works:
image

but there is no syntax highlight.
Is that possible to add syntax highlights using `.gitattributes`?
image

**Comment by larsbrinkhoff** [comment]
> Is that possible to add syntax highlights using `.gitattributes`?

No, it's not.  You may use a "modeline" for that: https://github.com/github/linguist#using-emacs-and-vim-modelines

**Comment by wkentaro** [comment]
It works, and I think that's the best way for my request.
thanks!

**Comment by larsbrinkhoff** [comment]
You're welcome!

Also, you only need one of either `vim:...` or `-*- mode:...`.

**Pull request closed without merging**
