### PR TITLE
Add SPWN

### PR DESCRIPTION
**Pull request by krista-chan**
## Description

Adds support for SPWN
## Checklist:
- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%spwn+extract+NOT+nothack
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [SpeckyYT/APPL2](https://github.com/SpeckyYT/APPL2)
      - [SpeckyYT/LXR](https://github.com/SpeckyYT/LXR)
      - [SpeckyYT/spwn-endecode](https://github.com/SpeckyYT/spwn-endecode)
      - [Deltara3/spwn-is-even](https://github.com/Deltara3/spwn-is-even)
      - [arc-spwn/ash](https://github.com/arc-spwn/ash)
      - [Wyliemaster/spwn-rng](https://github.com/Wyliemaster/spwn-rng)
      - [FlowVix/SPWN-collections/src/hashmap.spwn](https://github.com/FlowVix/SPWN-collections/blob/main/src/hashmap.spwn)
      - [DexterHill0/spwn-dye](https://github.com/DexterHill0/spwn-dye)
    - Sample license(s):
      - https://github.com/arc-spwn/ash/blob/main/LICENSE
      - https://github.com/FlowVix/SPWN-collections/blob/main/LICENSE

### CODE REVIEW

**Comment by lildude** [comment]
Your search result returns only 206 files which is no where near meeting our inclusion requirements... your `extract` keyword doesn't even feature in your own samples 😁. Removing that keyword reveals a lot more results, however most don't appear to look like your samples from my naïve PoV. 

Also, is this the same language as https://github.com/Spu7Nix/SPWN-language? If so, why not use the grammar provided by the same peeps from https://github.com/Spu7Nix/SPWN-vscode?

**Comment by SpeckyYT** [comment]
Over here I'm getting 40k files with the spwn extension

**Comment by lildude** [comment]
@SpeckyYT 

> Over here I'm getting 40k files with the spwn extension

Are they all the proposed language?

As I asked in my previous comment:

> Removing that keyword reveals a lot more results, however most don't appear to look like your samples from my naïve PoV.
>
> Is this the same language as https://github.com/Spu7Nix/SPWN-language?

**Comment by SpeckyYT** [comment]
@lildude yes, that's the source repository of SPWN.

**Review by lildude — CHANGES_REQUESTED** [review]
See comments inline. Additionally, if you're going to use the grammar at https://github.com/Spu7Nix/SPWN-vscode, you're going to need to get the maintainer to license it. We can only accept repos with one of  [these licenses](https://github.com/github/linguist/blob/9b1023ed5d308cb3363a882531dea1e272b59977/vendor/licenses/config.yml#L4-L15).

Please update the OP to link directly to the source of each of the three samples you're adding too.

**Comment by lildude** [comment]
Nudge nudge. This PR is still waiting for changes to be implemented.

**Comment by krista-chan** [comment]
i'll close this for now -- we will reevaluate this in the near future

**Pull request closed without merging**
