### PR TITLE
Support for web ontology language (OWL)

### PR DESCRIPTION
**Pull request by phuicy**
The Web Ontology Language (OWL) is a family of knowledge representation languages for authoring ontologies, created by W3. 
The languages' syntax is simply "xml". 
The languages' file extension is ".owl". 

With this in mind the addition was trivial.

Thanks
Guy

### CODE REVIEW

**Comment by pchaigno** [comment]
Just out of curiosity, if it is highlighted as XML why do you want to add it as a language? why not add it as a new extension for XML?

**Comment by phuicy** [comment]
It is a widely used language, and it would interesting to be able search and gather stats about its use.
Also it is distinct from xml, it just uses for the xml syntax for interchange.

**Comment by pchaigno** [comment]
Okay, thanks for answering my question :-)

**Comment by arfon** [comment]
This looks good. Thanks @phuicy.

**Comment by arfon** [comment]
It'll be another week or so before these changes are live on GitHub.

**Comment by phuicy** [comment]
Brilliant thanks

**Pull request merged**
