### PR TITLE
Visual Basic 6.0 language (VB6) is not there in your software. All VB6 projects are wrongly detected as VBA. Please see my repositories by searching for VB6.

### PR DESCRIPTION
**Pull request by Gagniuc**
## Checklist:

- [x] **I am associating a language with a new file extension.**
  - [ ] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      
      - https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [x] **I am adding a new language.**
  - [ ] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  
  - [ ] I have included a syntax highlighting grammar: https://github-lightshow.herokuapp.com/
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

- [x] **I am fixing a misclassified language**
  - [ ] I have included a new sample for the misclassified language:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am changing the source of a syntax highlighting grammar**
  
  - Old: https://github-lightshow.herokuapp.com/
  - New: https://github-lightshow.herokuapp.com/

- [ ] **I am updating a grammar submodule**
  

- [ ] **I am adding new or changing current functionality**
  
  - [ ] I have added or updated the tests for the new or changed functionality.

- [ ] **I am changing the color associated with a language**
  
  - [ ] I have obtained agreement from the wider language community on this color change.
    - [URL to public discussion]
    - [Optional: URL to official branding guidelines for the language]

### CODE REVIEW

**Comment by Gagniuc** [comment]
Visual Basic 6.0 language is not there in your software. All VB6 projects are wrongly detected as VBA. Please see my repositories by searching for VB6. Please add VB6 programming language to the list.

**Comment by lildude** [comment]
Closing as this appears to be a request to add support for a language rather than you actually contributing the support.

Please open a new ["New language" issue using the dedicated option](https://github.com/github/linguist/issues/new/choose)

**Comment by lildude** [comment]
Come to think of it, this is expected: VB6 is an alias for VBA:

https://github.com/github/linguist/blob/3c3b037910006fc2f1a9bb34b2c4e9cde062206c/lib/linguist/languages.yml#L6481-L6494

**Comment by Gagniuc** [comment]
I advise you to look at this post, which is specific about your app: [https://www.vbforums.com/showthread.php?895552-GitHub-detects-VB6-as-VBA](https://www.vbforums.com/showthread.php?895552-GitHub-detects-VB6-as-VBA)

Notice that the .vbp extension is VB6 only.

**Comment by Gagniuc** [comment]
> Closing as this appears to be a request to add support for a language rather than you actually contributing the support.
> 
> Please open a new ["New language" issue using the dedicated option](https://github.com/github/linguist/issues/new/choose)

All done :)

**Pull request closed without merging**
