### PR TITLE
adding corezoid lang support https://new.corezoid.com/

### PR DESCRIPTION
**Pull request by dneprovets**
https://github.com/search?q=corezoid&type=Code

### CODE REVIEW

**Comment by Alhadis** [comment]
Please fill out the pull-request template.

**Comment by dneprovets** [comment]
# Description

I've added a corezoid structure json format of processes. This technology based on https://new.corezoid.com/

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [Х] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

I've tested changes by myself and it seems there are no problems.

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [Х] My code follows the style guidelines of this project
- [Х] I have performed a self-review of my own code
- [Х] I have commented my code, particularly in hard-to-understand areas
- [Х] I have made corresponding changes to the documentation
- [Х] My changes generate no new warnings
- [Х] I have added tests that prove my fix is effective or that my feature works
- [Х] New and existing unit tests pass locally with my changes
- [Х] Any dependent changes have been merged and published in downstream modules

**Comment by pchaigno** [comment]
I don't know where you got that template, but that's not ours. [The Linguist template](https://github.com/github/linguist/blob/master/.github/PULL_REQUEST_TEMPLATE.md) should have been prefilled when you opened this pull request.

**Comment by dneprovets** [comment]
I've added a corezoid structure json format of processes. This technology based on https://new.corezoid.com/

## Description


## Checklist:


- [ ] **I am associating a language with a new file extension.**
  - [ ] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      
      - https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=corezoid
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - samples/Corezoid/conv_466117_1539700423.json;
      - samples/Corezoid/conv_466118_1539700439.json;
      - samples/Corezoid/conv_466119_1539700450.json;
    - Sample license(s):
  
  - [ ] I have included a syntax highlighting grammar: https://github-lightshow.herokuapp.com/
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

- [ ] **I am fixing a misclassified language**
  - [ ] I have included a new sample for the misclassified language:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am changing the source of a syntax highlighting grammar**
  
  - Old: https://github-lightshow.herokuapp.com/
  - New: https://github-lightshow.herokuapp.com/
  
- [ ] **I am updating a grammar submodule**
  

- [ ] **I am adding new or changing current functionality**
  
  - [ ] I have added or updated the tests for the new or changed functionality.



@Alhadis sorry for inconvenient, it's my first try

**Comment by Alhadis** [comment]
These are just [JSON](https://en.wikipedia.org/wiki/JSON) files. Corezoid appears to be some sort of cloud integration system, and the files you're adding seem to be configuration or data samples.

Closing this as invalid, because it's already a supported file format.

**Pull request closed without merging**
