### PR TITLE
Add Jison-generated JavaScript to generated files

### PR DESCRIPTION
**Pull request by nwhetsell**
This pull request adds [Jison](https://zaa.ch/jison/)-generated JavaScript to generated files. (It also fixes a few minor typos in [lib/linguist/generated.rb](https://github.com/github/linguist/blob/master/lib/linguist/generated.rb).)

The first line of Jison-generated parsers usually begins with

```js
/* parser generated by jison 
```

This is written to parsers at [zaach/jison/lib/jison.js#L984](https://github.com/zaach/jison/blob/7653842e5120510b0b77484ac90d6c569cf146fd/lib/jison.js#L984).

The first line of Jison-generated standalone lexers usually begins with

```js
/* generated by jison-lex 
```

This is written to lexers at [zaach/jison-lex/regexp-lexer.js#L557](https://github.com/zaach/jison-lex/blob/28aa5ac329310ac74eff0d4259fcf594429134f7/regexp-lexer.js#L557) and [zaach/jison-lex/regexp-lexer.js#L573](https://github.com/zaach/jison-lex/blob/28aa5ac329310ac74eff0d4259fcf594429134f7/regexp-lexer.js#L573).

To test this, I added two files to the JavaScript samples. These are generated on macOS by `cd`-ing to the [examples folder of the GerHobbelt fork of Jison](https://github.com/GerHobbelt/jison/tree/master/examples) and entering in Terminal

```sh
node ../lib/cli.js ccalc-parse.y ccalc-lex.l
node ../../node_modules/jison-lex/cli.js ccalc-lex.l
```

Jison is distributed under the [MIT license](https://github.com/GerHobbelt/jison#license).

### CODE REVIEW

**Comment by pchaigno** [comment]
Thanks for the pull request!

For lexers, it looks like the `generated by` comment is [rarely at the first line](https://github.com/search?p=4&q=%22generated+by+jison-lex+%22+extension%3Ajs&ref=searchresults&type=Code&utf8=%E2%9C%93). Is there another way of detecting these files without going through all lines?

**Comment by nwhetsell** [comment]
The typical case is for Jison to put a parser and a lexer in the same JavaScript file. I didn’t look at all the results of the search, but of the ten results on the page from your link, seven are parsers with `parser generated by jison` in the first line:

* [ecofyphp-server/artifacts/queryparser/jison/ports/comments.js](https://github.com/ysahnpark/ecofyphp-server/blob/dc8062824ddfc7fe6453c3ddf27db96e570b8151/artifacts/queryparser/jison/ports/comments.js)
* [AnalisisNumericoApp/js/jison/ports/comments.js](https://github.com/lilarock3rs/AnalisisNumericoApp/blob/a37ef7b8a55c8f888a9d9a6e5102745a928d3847/js/jison/ports/comments.js)
* [pl-calculadora/calculator.js](https://github.com/LegolasArc/pl-calculadora/blob/fe44142f89b182546fbefbb69248e16bf54f27c1/calculator.js)
* [jquerysheet/parser/tsv/tsv.js](https://github.com/kinnch/jquerysheet/blob/3fa7837ade3c5a37c0cb839a3fa467353abb143a/parser/tsv/tsv.js)
* [spreedsheet_test/app/assets/javascripts/jquerysheet_3.1r2_meta/tsv/tsv.js](https://github.com/sheldondyck/spreedsheet_test/blob/1acd339ec709923b48e68a3922720c5fcaf92e88/app/assets/javascripts/jquerysheet_3.1r2_meta/tsv/tsv.js)
* [spreedsheet_test/app/assets/javascripts/jquerysheet_trunk/parser/tsv/tsv.js](https://github.com/sheldondyck/spreedsheet_test/blob/1acd339ec709923b48e68a3922720c5fcaf92e88/app/assets/javascripts/jquerysheet_trunk/parser/tsv/tsv.js)
* [spreedsheet_test/app/assets/stylesheets/jquerysheet_trunk/parser/tsv/tsv.js](https://github.com/sheldondyck/spreedsheet_test/blob/1acd339ec709923b48e68a3922720c5fcaf92e88/app/assets/stylesheets/jquerysheet_trunk/parser/tsv/tsv.js)

One ([galaxy-parser/lib/lexer.js](https://github.com/rameshvarun/galaxy-parser/blob/8d8bafce2460cd79b33664456e5d06b7e3af74b4/lib/lexer.js)) is a lexer with `/* generated by jison-lex` in the first line.

That leaves two ([caps/Caps.Web.UI/App/infrastructure/searchGrammer.js](https://github.com/apircher/caps/blob/647bf5bdf0c30eedf0b1cbcf096467a0ff98c83c/Caps.Web.UI/App/infrastructure/searchGrammer.js) and [xlint/lib/lint/css/css_value_parser/cssValueLexer.js](https://github.com/busykai/xlint/blob/dab9bbabf17c66bc2bc6c4bdfcd9251cfda20119/lib/lint/css/css_value_parser/cssValueLexer.js)) that would be missed by this pull request. searchGrammer.js is a parser without `parser generated by jison` in the first line for some reason; maybe it was modified after it was created. cssValueLexer.js is a lexer that was almost certainly modified (with a copyright notice) after it was created.

**Comment by mark666-dev** [comment]
- 

1. 

> Esta solicitud de extracción agrega JavaScript generado por [Jison](https://zaa.ch/jison/) a los archivos generados. (También corrige algunos errores tipográficos menores en [lib / linguist / generate.rb](https://github.com/github/linguist/blob/master/lib/linguist/generated.rb) ).
> 
> La primera línea de analizadores generados por Jison generalmente comienza con
> 
> ```js
> / * analizador generado por jison
> ```
> 
> Esto está escrito para los analizadores en [zaach / jison / lib / jison.js # L984](https://github.com/zaach/jison/blob/7653842e5120510b0b77484ac90d6c569cf146fd/lib/jison.js#L984) .
> 
> La primera línea de lexers independientes generados por Jison generalmente comienza con
> 
> ```js
> / * generado por jison-lex
> ```
> 
> Esto está escrito para lexers en [zaach / jison-lex / regexp-lexer.js # L557](https://github.com/zaach/jison-lex/blob/28aa5ac329310ac74eff0d4259fcf594429134f7/regexp-lexer.js#L557) y [zaach / jison-lex / regexp-lexer.js # L573](https://github.com/zaach/jison-lex/blob/28aa5ac329310ac74eff0d4259fcf594429134f7/regexp-lexer.js#L573) .
> 
> Para probar esto, agregué dos archivos a las muestras de JavaScript. Estos se generan en macOS entrando en `cd`la [carpeta de ejemplos de la bifurcación GerHobbelt de Jison](https://github.com/GerHobbelt/jison/tree/master/examples) e ingresando en Terminal
> 
> ```shell
> nodo ../lib/cli.js ccalc-parse.y ccalc-lex.l
> nodo ../../node_modules/jison-lex/cli.js ccalc-lex.l
> ```
> 
> Jison se distribuye bajo la [licencia MIT](https://github.com/GerHobbelt/jison#license) .

**Comment by mark666-dev** [comment]
/ * generado por jison-lex .diff

**Comment by mark666-dev** [comment]
https://github.com/github/linguist/pull/3393#pullrequestreview-384736060 patch

**Comment by mark666-dev** [comment]
> [# 3393 (revisión)](https://github.com/github/linguist/pull/3393#pullrequestreview-384736060) parche

**Pull request merged**
