### PR TITLE
Add ZenScript language support

### PR DESCRIPTION
**Pull request by jaredlll08**
## Description
ZenScript is a scripting language for Java. It is primarily used by [CraftTweaker](https://github.com/CraftTweaker/CraftTweaker), which is a Minecraft mod that allows users to change many aspects of the game using scripts. 

Many of the projects which use CraftTweaker (and in turn use ZenScript) are open source and on GitHub. It is not uncommon for these repos to solely consist of ZenScript files. Having syntax highlighting as well as language break downs for it would be very useful for these projects. 

## Checklist:

- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  [Using keyword: "NOT nothack"](https://github.com/search?q=extension%3Azs+NOT+nothack&type=Code)
      - [Using keyword: "recipes"](https://github.com/search?q=extension%3Azs+recipes&type=Code)
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [CraftTweaker example repo](https://github.com/CraftTweaker/CraftTweaker-Examples)
      - [SevTech Ages script file](https://github.com/DarkPacks/SevTech-Ages/blob/master/src/scripts/crafttweaker/integrations/wood.zs)
    - Sample license(s): 
      - [MIT](https://github.com/CraftTweaker/CraftTweaker-Examples/blob/master/LICENSE)
      - [GPL3.0](https://github.com/DarkPacks/SevTech-Ages/blob/master/LICENSE)
  
  - [x] I have included a syntax highlighting grammar: [Lightshow](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fgithub.com%2FCraftTweaker%2FZenScript-tmLanguage%2Fblob%2Fmaster%2Fzenscript.tmLanguage.json&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fjaredlll08%2Flinguist%2Fmaster%2Fsamples%2FZenScript%2Fsample.zs&code=) (Lightshow is currently offline, but I have tested this syntax on it before and it worked perfectly fine)
  -  I have updated the heuristics to distinguish my language from others using the same extension.
      - No other languages use the `.zs` extension.

### CODE REVIEW

**Comment by jaredlll08** [comment]
I'm not exactly sure how to fix the Travis issues, I haven't changed the license since it was made, so not sure how the cached data is out of date.

**Comment by pchaigno** [comment]
@jaredlll08 Thanks for your contribution! Do you get an error message if you run `script/licensed`?

@lildude Any idea what's happening to Lightshow?

**Comment by jaredlll08** [comment]
@pchaigno No error message, but I think that fixed the cache issue, lets wait and see what Travis says.

**Comment by jaredlll08** [comment]
Yip that seems to have solved it! Thanks!

**Comment by jaredlll08** [comment]
No idea on that error, I don't think it is anything I did, maybe it is due to that one repo (https://github.com/ajLangley12/language-asn1) not being available anymore?

**Comment by lildude** [comment]
> No idea on that error, I don't think it is anything I did, maybe it is due to that one repo (https://github.com/ajLangley12/language-asn1) not being available anymore?

Yup, looks like @ajlangley has 🔥 the `ajLangley12` user and thus access to the repo too. @ajlangley is this intentional? If so, we'll probably need to find a new grammar for ASN.1 - https://github.com/sparticvs/atom-language-asn1 might be a good alternative - or maintain a fork of the repo ourselves.

**Comment by ajlangley** [comment]
It was not my intention to make a breaking change to this repository, but I did delete the repository yesterday. I did not understand that it could not be safely deleted and that that was the only place where the package existed.

**Comment by ajlangley** [comment]
Contacted support, repo is restored.

**Comment by jaredlll08** [comment]
The username is still different, so the submodule will still fail. Not sure if this is something I need to fix in this PR, or if it will be handled by someone else.

**Comment by lildude** [comment]
> Not sure if this is something I need to fix in this PR, or if it will be handled by someone else.

It's best to update the submodule path in a new PR.

**Comment by jaredlll08** [comment]
I was more saying I wasn't sure if I needed to fix the submodule so that the Travis tests pass (to be honest nothing has changed that would invalidate the previous tests that were done), so that this PR can get merged.

**Comment by lildude** [comment]
@jaredlll08 merging master into your fork should solve the CI problems now.

**Comment by jaredlll08** [comment]
That seems to have solved it! Thanks!

**Comment by jaredlll08** [comment]
Not sure if I'm missing something, but would appreciate if this could get a review :)

**Comment by lildude** [comment]
@jaredlll08 looks like we've got some conflicts that need resolving now.

**Comment by jaredlll08** [comment]
@lildude should be good :)

**Pull request merged**
