### PR TITLE
Add Toit

### PR DESCRIPTION
**Pull request by snxx-lppxx**
## Checklist:

- [ ] **I am associating a language with a new file extension.**
  - [ ] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      
      - https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am adding a new language.**
  - [ ] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  
  - [ ] I have included a syntax highlighting grammar: https://github-lightshow.herokuapp.com/
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

- [ ] **I am fixing a misclassified language**
  - [ ] I have included a new sample for the misclassified language:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am changing the source of a syntax highlighting grammar**
  
  - Old: https://github-lightshow.herokuapp.com/
  - New: https://github-lightshow.herokuapp.com/

- [ ] **I am updating a grammar submodule**
  

- [ ] **I am adding new or changing current functionality**
  
  - [ ] I have added or updated the tests for the new or changed functionality.

- [ ] **I am changing the color associated with a language**
  
  - [ ] I have obtained agreement from the wider language community on this color change.
    - [URL to public discussion]
    - [Optional: URL to official branding guidelines for the language]

### CODE REVIEW

**Review by lildude — CHANGES_REQUESTED** [review]
Please follow the instructions in CONTRIBUTING.md for adding support for a new language.

**Comment by lildude** [comment]
Looks like usage is also a long long way from meeting our requirements.

**Comment by snxx-lppxx** [comment]
Hi @lildude, what should be done in this case?

**Comment by lildude** [comment]
You've not followed all the instructions on adding a new language as you've not got a language ID, the colour is incorrectly specified and the licence file for the grammar is missing. Following the instructions and add the hash to the colour will address those issues. You've also not filled in the template in the OP.

That said, the language won't be added until usage on GitHub meets the minimum usage levels also stated in the contributing docs so this PR will sit here until it does.

You can follow the instructions and complete the PR or close it and submit a new one once usage levels have grown, it's your choice.

**Comment by Nixinova** [comment]
> Looks like usage is also a long long way from meeting our requirements.

It has [2K+](https://github.com/search?q=extension%3Atoit&type=code) results, that seems okay or close to it

**Comment by snxx-lppxx** [comment]
Hi @lildude, you can reopen this PR? I will try to finish.

**Comment by lildude** [comment]
Closing this again as there's still been no progress on it. The overall usage is also still really low with only 839 files if we exclude the toitlang org.

Please submit a new PR once usage meets our requirements and you have the time to submit a complete PR.

**Pull request closed without merging**
