### PR TITLE
Added natvis extension to XML

### PR DESCRIPTION
**Pull request by krk**
natvis: https://docs.microsoft.com/en-us/visualstudio/debugger/create-custom-views-of-native-objects

https://github.com/search?utf8=%E2%9C%93&q=extension%3Anatvis+NOT+nothack&type=Code

### CODE REVIEW

**Comment by Alhadis** [comment]
Hey @krk, thanks for the pull request. 👋

The `.natvis` extension certainly meets our criteria of in-the-wild usage; however, we need confirmation that the sample you're adding is released under a permissive license. Could you cite your source for [this file](https://github.com/krk/linguist/blob/994ef52350456c2082506cd53c38d4ab794065a6/samples/XML/chrome.natvis)?

**Comment by krk** [comment]
I have included the Chromium licence text in the file.

**Comment by Alhadis** [comment]
LGTM. @lildude, any idea what's going on with Travis? The Ruby 2.1 job is hitting an error when installing dependencies:

~~~
Gem::InstallError: byebug requires Ruby version >= 2.2.0.
Using github-linguist 5.2.0 from source at .
An error occurred while installing byebug (9.1.0), and Bundler cannot continue.
Make sure that `gem install byebug -v '9.1.0'` succeeds before bundling.
The command "eval bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle} " failed 3 times.
The command "bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}" failed and exited with 5 during .
Your build has been stopped.
~~~

Others are fine, though, so I doubt it's related to the PR.

**Comment by lildude** [comment]
> @lildude, any idea what's going on with Travis?

Yup... the first four lines give it away. It's trying to install byebug and it looks like the minimum requirement has been bumped to Ruby 2.2.0 and we don't lock down to a specific version. It's definitely not related to this PR and probably not something we should attempting to install during testing anyway.

I'll open a PR in a mo to fix this. For the time being, I'm happy the other tests pass and doubt things will be any different for Ruby 2.1.0 so I'll approve this PR.

**Comment by lildude** [comment]
@krk CI should start passing once you pull the linguist/master into your branch.

**Comment by lildude** [comment]
Nudgy McNudge-face @krk. Could you please merge master into your branch so we can get a successful CI run. We can't merge the PR until then.

**Pull request merged**
