### PR TITLE
Update TOML grammar to latest.

### PR DESCRIPTION
**Pull request by mojombo**
This updates the TOML submodule to the latest commit, which includes proper behavior for TOML v0.4.0.

### CODE REVIEW

**Comment by pchaigno** [comment]
The grammars are updated automatically with each new release ;)

**Comment by arfon** [comment]
Hey @mojombo :wave:, thanks for this. As @pchaigno mentioned, we update the submodules automatically when we cut a new gem. I'll probably do this on Monday.

**Comment by arfon** [comment]
Looks like the TOML submodule got bumped in https://github.com/github/linguist/commit/63fc9dd6a5d0a551e73b5ce1c4c0861d3e88c624

**Comment by mojombo** [comment]
Ah! Didn't realize those were updated automatically. Thanks!

**Pull request closed without merging**
