### PR TITLE
Add CSV as data type to languages.yml

### PR DESCRIPTION
**Pull request by FarbodSalamat-Zadeh**
I've added CSV as a 'language' with the type `data`. I think it should be shown when searching files, as I'm sure others also find themselves searching for a particular string that may be in a CSV file. I've added CSV with the primary extension `.csv`, but also `.txt`.

### CODE REVIEW

**Comment by arfon** [comment]
@FarbodSalamat-Zadeh - thanks for adding this. I agree that searching for `CSV` files could be useful. I'd rather not add `.txt` as an extension here as it's already defined for `Text` and I'm not sure that our classifier will do a good job disambiguating these.

Would you be willing to update this Pull Request removing the `.txt` extension?

**Comment by FarbodSalamat-Zadeh** [comment]
Thanks for your reply @arfon , I'll update the pull request accordingly.

**Comment by pchaigno** [comment]
@FarbodSalamat-Zadeh The [Travis build](https://travis-ci.org/github/linguist/jobs/112164936) is currently failing because one of the sample files is incorrectly classified. Could you move `test/fixtures/Data/cars.csv` to `samples/CSV/`?

**Comment by FarbodSalamat-Zadeh** [comment]
@pchaigno I have moved the file to the updated path.

**Comment by pchaigno** [comment]
Hum, it's still failing because the file is hard-coded in tests: [`test_file_blob.rb#L155`](https://github.com/github/linguist/blob/master/test/test_file_blob.rb#L155). You'll need to change `fixture_blob("Data/cars.csv")` to `sample_blob("CSV/cars.csv")`.

**Comment by FarbodSalamat-Zadeh** [comment]
@pchaigno Applied the modifications - all checks pass now :)

**Comment by arfon** [comment]
:+1: thanks @FarbodSalamat-Zadeh and @pchaigno.

@FarbodSalamat-Zadeh - this will be live in the next release of Linguist (sometime this week)

**Pull request merged**
