### PR TITLE
Added new 'Wonkey' programming language

### PR DESCRIPTION
**Pull request by seyhajin**
Wonkey is a fork of Monkey2 programming language.

- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      -  https://github.com/wonkey-coders/wonkey/search?q=extension%3Awx+NOT+nothack
  - [x] I have included a real-world usage sample for all extensions added in this PR:
  - [ ] I have included a syntax highlighting grammar: https://github-lightshow.herokuapp.com/

### CODE REVIEW

**Comment by lildude** [comment]
> Wonkey is a fork of Monkey2 programming language.

🤔 and it appears to have only been forked within the last week which would suggest it would be no where near meeting the currently documented minimum requirement for inclusion:

> We try only to add new extensions once they have some usage on GitHub. In most cases we prefer that extensions be in use in hundreds of repositories before supporting them in Linguist.

Many of the files returned by your search don't look to be "Wonkey" and with a little refinement of the search, I think every single "Wonkey" file can be attributed to a single repo: https://github.com/wonkey-coders/wonkey

Unfortunately, this makes it far too early to even consider adding support to Linguist.

**Comment by seyhajin** [comment]
> > Wonkey is a fork of Monkey2 programming language.
> 
> 🤔 and it appears to have only been forked within the last week which would suggest it would be no where near meeting the currently documented minimum requirement for inclusion:
> 

It's a fork with extension and grammar changes.

> > We try only to add new extensions once they have some usage on GitHub. In most cases we prefer that extensions be in use in hundreds of repositories before supporting them in Linguist.
> 
> Many of the files returned by your search don't look to be "Wonkey" and with a little refinement of the search, I think every single "Wonkey" file can be attributed to a single repo: https://github.com/wonkey-coders/wonkey
> 
I targeted search into Wonkey repo

> Unfortunately, this makes it far too early to even consider adding support to Linguist.

I need syntax highlighting on Github :)

**Comment by lildude** [comment]
> I targeted search into Wonkey repo

That's the problem... we need popularity demonstrated across the _whole_ of GitHub. Your repo appears to be the only one using this language. One user is not sufficient to qualify for inclusion.

This PR will not be accepted until there is wide-spread usage across the whole of GitHub.

**Comment by Nixinova** [comment]
This PR should be closed as being far off being able to be added.

**Pull request closed without merging**
