### PR TITLE
Add the Common Workflow Language standard

### PR DESCRIPTION
**Pull request by mr-c**
Hello!

This PR adds support for the CWL open standards for portable data analysis tool and workflow descriptions

http://www.commonwl.org/

There are [over 4,800 CWL files on GitHub](https://github.com/search?utf8=%E2%9C%93&q=extension%3Acwl+cwlVersion&type=Code).

Thanks :-)

### CODE REVIEW

**Comment by pchaigno** [comment]
@mr-c There are also a [lot of TeX files under `.cwl`](https://github.com/search?utf8=%E2%9C%93&q=extension%3Acwl+begin&type=Code). Do you know what those are?

**Comment by mr-c** [comment]
@pchaigno I'm not a TeX expert, sorry. Some light searching shows they are associated with the TeXstudio IDE?

All Common Workflow Language files contain `cwlVersion: ` followed by the version of the spec on a line someplace in the file, so it shouldn't be hard to disambiguate.

**Comment by pchaigno** [comment]
There are around 1k `.cwl` TeX files so it probably mandates support. Since the two languages contain very different keywords, I'd expect the Bayesian classifier to do a pretty good job here. @kivikakk What do you think?

**Comment by kivikakk** [comment]
Strongly agree re: the Bayesian classifier! If we add a definition fro the TeX `.cwl`s and collect a few examples, it should be fine.

**Pull request merged**
