### PR TITLE
Add Wollok educational language

### PR DESCRIPTION
**Pull request by fdodino**
Hi, @pchaigno, again! :smile:

I followed all the rules as described [here](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language).
There were 2 changes I didn't explicitly make:
- licenses in vendor/README.md
- double quotes in languages.yml for gerber in lib/linguist/languages.yml

Related to PR #2678 , I did a new PR to add just .wlk files (next year I will try to add .wtest too as usage grows).

Wollok is an educational OO language: http://www.wollok.org/en/
It is used in several matters of different universities: UTN Buenos Aires (thttp://pdep.com.ar), UTN Delta, UNSAM (www.unsam.edu.ar), UNQ (www.unq.edu.ar)

Adding last query (2,875 results):

https://github.com/search?utf8=%E2%9C%93&q=extension%3Awlk+NOT+nothack&type=Code&ref=searchresults

This year we are moving to github classroom instead of SVN, so visibility will increase (over 600+ students will be using github and Wollok).

Many thanks for your patience!
Have a nice week!
Fernando

### CODE REVIEW

**Comment by fdodino** [comment]
Hi @lildude , thanks for replying!

I added a permissive license, if something more is needed just tell me.
Many thanks and nice week!

**Comment by lildude** [comment]
Thanks. Sadly, we I don't think we'll be able to accept this.  

I've taken another look and the license needs to be from the repo of the grammar and should automatically be pulled in by the `script/add-grammar` script.

Looking at the repo - https://github.com/uqbar-project/wollok - I've spotted two problems:

1. There doesn't appear to be a grammar within the repo, and
2. According to the README in repo you've reference, it is licensed under the LGPLv3 which is _not_ free enough for inclusion in Linguist, assuming it included a grammar.

**Comment by fdodino** [comment]
Now I understand much better.
I confused Wollok github repository with a grammar repository. 
LGPLv3 is Wollok language license, not Wollok grammar license.
I have to check where is Wollok grammar repository and come back again.
Thanks!

**Comment by lildude** [comment]
NP. Please keep in mind we can't accept any of the samples drawn from the actual language repo either as they're protected by LGPLv3 too unless explicitly exempted.

**Comment by lildude** [comment]
Just a quick nudge and to say...

> Please keep in mind we can't accept any of the samples drawn from the actual language repo either as they're protected by LGPLv3 too unless explicitly exempted.

Don't worry about the license for the sample files. We've cleared things with our legal department and we _can_ include samples of any license, however need to know the source of the sample and the license it's covered by either in the sample itself or within a comment in the PR adding the sample.

The grammar _does_ however need to be a permissive license.

**Comment by lildude** [comment]
Closing as stale. Please feel free to submit a new PR when you have the chance to implement all the suggestions.

**Pull request closed without merging**
