### PR TITLE
Add Danmakufu PH3

### PR DESCRIPTION
**Pull request by bluebear94**
A scripting language for Touhou-like STGs ([wiki](http://dmf.shrinemaiden.org/wiki/Main_Page) / [download page](http://www.geocities.co.jp/SiliconValley-Oakland/9951/pre/th_dnh_ph3.html)).

Usage:

* bluebear94/cy05 and nagakawa/cy06 (my projects; currently classified as Python due to scripts)
* [Search for Danmakufu](https://github.com/search?utf8=%E2%9C%93&q=danmakufu) - beware of false positives
* [More accurate search](https://github.com/search?utf8=%E2%9C%93&q=TouhouDanmakufu&type=Code&ref=searchresults)
* Repositories from @TheLandOfCodesAndApertures (particularly TheLandOfCodesAndApertures/arb-DNH-codes and /TheLandOfCodesAndApertures/Sparen_Sound_Library)
* ExPorygon/Ephemeral-Unnatural-Balance
* kitsune94/THRSS_1.00d_English (translation of a Touhou fangame)

(note: some of these files use different extensions, but I opted to include only the most common one `.dnh` here)

The grammar is from drake-irving/sublime-danmakufu.

### CODE REVIEW

**Comment by bluebear94** [comment]
Measures to try to get build to pass.

**Comment by bluebear94** [comment]
Anyone know how I can fix this error:

```
TestGrammars#test_local_scopes_are_in_sync [/home/travis/build/github/linguist/test/test_grammars.rb:79]:
The scopes listed for vendor/grammars/Sublime-DNH in grammars.yml don't match the scopes found in that repository.
Expected: ["source.danmakufu ph3"]
  Actual: ["source.danmakufu"]
```

**Comment by bluebear94** [comment]
Now I somehow get this error:

```
TestBlob#test_language [/home/travis/build/github/linguist/test/test_blob.rb:593]:
cutin.dnh.
Expected: "Danmakufu PH3"
  Actual: "Danmakufu"
```

**Comment by bluebear94** [comment]
I don't think there are many 0.12m repos on Github.

We could always come back to 0.12m later, but we'll need quite a few samples.

**Comment by pchaigno** [comment]
Using [this search](https://github.com/search?utf8=%E2%9C%93&q=extension%3Adnh+let&type=Code&ref=searchresults), I downloaded the 1,000 first files and they only come from 10 different repositories :/
I'm not sure that will be enough to add this language.
@arfon ?

**Comment by bluebear94** [comment]
@pchaigno We could always wait until 90 more repositories pop up.

**Comment by arfon** [comment]
> Using this search, I downloaded the 1,000 first files and they only come from 10 different repositories :/
I'm not sure that will be enough to add this language.
@arfon ?

@pchaigno - any chance you could check again for us?

**Comment by pchaigno** [comment]
The 1,637 files come from 12 repositories across 9 users :/
I managed to retrieve all of the [1,637 files](https://github.com/search?utf8=%E2%9C%93&q=extension%3Adnh+let&type=Code&ref=searchresults) by downloading the 1,000 first files for each Sort option (`Best match`, `Recently indexed` and `Least recently indexed`).

**Comment by arfon** [comment]
> The 1,637 files come from 12 repositories across 9 users :/

OK, this is still very low. @bluebear94 - I think we should close this PR for now and revisit in another few months. Is that OK with you?

**Comment by bluebear94** [comment]
Sure thing.

**Pull request closed without merging**
