### PR TITLE
Improved XQuery and JSONiq support

### PR DESCRIPTION
**Pull request by wcandillon**

### CODE REVIEW

**Comment by pchaigno** [comment]
You will also need a license on the grammar repository. See http://choosealicense.com to choose an OSS license ;)

**Comment by wcandillon** [comment]
done: https://github.com/wcandillon/language-jsoniq/blob/master/LICENSE

**Comment by pchaigno** [comment]
The submodule points to your repository before you add the grammar, you'll need to update it too :/

**Comment by wcandillon** [comment]
@pchaigno done :)

**Comment by pchaigno** [comment]
Looks good!
Could be good to show an example of improvement in [Lightshow](https://github-lightshow.herokuapp.com/) too for reviewers ;)

**Comment by wcandillon** [comment]
The list of improvements is quite big. In fact the original maintainer of the xquery grammar deprecated his package in favor of ours (https://github.com/arolle/atom-language-xquery). These new grammars are based on our ACE grammars which we find quite mature.

Here are some of the improvements. Support for proper JSON strings:
https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgithub.com%2Fwcandillon%2Flanguage-jsoniq%2Fblob%2Fmaster%2Fgrammars%2Fjsoniq.cson&grammar_text=&code_source=from-text&code_url=&code=%22%5Cnhello%5Cworld%22

Support proper switching from xquery to jsoniq syntax (not demoable via github-lightshow).

Support for enclosed expressions: https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgithub.com%2Fwcandillon%2Flanguage-jsoniq%2Fblob%2Fmaster%2Fgrammars%2Fjsoniq.cson&grammar_text=&code_source=from-text&code_url=&code=%3Cfoo+bar%3D%22hello+%7B1+%2B+1%7D+%7B%7B1%2B1%7D%7D+world%22%3E%3C%2Ffoo%3E

There are many more, strings are now supported properly and so on. The list of keywords is now up to date with XQuery 3.0.

**Comment by pchaigno** [comment]
Awesome!
You only have to wait for someone from GitHub to review this PR now!

**Comment by wcandillon** [comment]
@gjtorikian Can you take a look?

**Comment by gjtorikian** [comment]
I distinctly remember when XQuery support (and linting via workers) landed in Ace. Very cool stuff.

I'm a huge :+1:. Unfortunately, I actually don't know how our highlighting works in service of Linguist. :sweat_smile: @arfon @bkeepers Does this PR meet what we need for a new grammar?

**Comment by arfon** [comment]
> Does this PR meet what we need for a new grammar?

:+1: yep, looks good to me. Let's merge this in and cut a new gem next week that will include this change.

**Comment by wcandillon** [comment]
@gjtorikian good to see you! @arfon @pchaigno Thank you so much!

**Pull request merged**
