### PR TITLE
Add support for MQL4 and MQL5 languages

### PR DESCRIPTION
**Pull request by osorgin**
This pull request is essentially an updated PR [#3109 Add support for MQL4 and MQL5 languages](https://github.com/github/linguist/pull/3109) (closed now as outdated).
It includes the newly added [MQL5-sublime](https://github.com/mqsoft/MQL5-sublime) syntax which supports both MQL5 and MQL4 and has been published under a permissive license (MIT). I have also updated the language definitions according to the new `languages.yml` format. Other than that, this PR is identical to the old one.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
Would it be inappropriate to have just one MQL language with both the `.mq4` and `.mq5` extensions.  (Plus `.mqh` of course.)

**Comment by osorgin** [comment]
@larsbrinkhoff 
The languages are similar to each other, but programs written in MQL4 and MQL5 are not interchangeable by default because of fundamental differences between the corresponding platforms (MetaTrader 4 and MetaTrader 5). Basically, an MQL4 Expert Advisor will not work on MetaTrader 5 and vice versa. That's why I decided to make separate definitions for them. Anyway, I'll give more thought to it, but I would like to hear opinions of other maintainers.

**Comment by osorgin** [comment]
I guess the failing checks are related to issue #3225, but as I see there are conflicts with the base branch, is there any way I can resolve them myself?

**Comment by osorgin** [comment]
Hello guys, is there any problem I can solve here?

**Comment by pchaigno** [comment]
Yep, you'll need to update your branch with either `git merge master` or `git rebase master`. You'll need to update the master branch first: `git pull upstream master`.

**Comment by osorgin** [comment]
@pchaigno Done, thank you.

**Comment by osorgin** [comment]
@pchaigno I wonder if there any issues remaining which prevent this PR from being merged, or I just have to wait? Please let me know if I need to change something.

**Comment by larsbrinkhoff** [comment]
@pchaigno @arfon I think this is good to go.

**Comment by osorgin** [comment]
Sorry guys, one more question: any chance for these changes, if they are merged, to be included into the upcoming Linguist release? Or it would be the next after that?

**Comment by arfon** [comment]
@osorgin I've made an updated version of this PR over in #3295

**Pull request closed without merging**
