### PR TITLE
Use Atom's grammars instead of TextMate's when possible

### PR DESCRIPTION
**Pull request by Alhadis**
This PR drops a number of TextMate grammars in favour of Atom's:

* [textmate/c.tmbundle](https://github.com/textmate/c.tmbundle)       -> [atom/language-c](https://github.com/atom/language-c)
* [textmate/css.tmbundle](https://github.com/textmate/css.tmbundle)   -> [atom/language-css](https://github.com/atom/language-css)
* [textmate/html.tmbundle](https://github.com/textmate/html.tmbundle) -> [atom/language-html](https://github.com/atom/language-html)
* [textmate/java.tmbundle](https://github.com/textmate/java.tmbundle) -> [atom/language-java](https://github.com/atom/language-java)
* [textmate/json.tmbundle](https://github.com/textmate/json.tmbundle) -> [atom/language-json](https://github.com/atom/language-json)
* [textmate/make.tmbundle](https://github.com/textmate/make.tmbundle) -> [atom/language-make](https://github.com/atom/language-make)
* [textmate/objective-c.tmbundle](https://github.com/textmate/objective-c.tmbundle) -> [atom/language-objective-c](https://github.com/atom/language-objective-c)
* [textmate/perl.tmbundle](https://github.com/textmate/perl.tmbundle) -> [atom/language-perl](https://github.com/atom/language-perl)
* [textmate/php.tmbundle](https://github.com/textmate/php.tmbundle)   -> [atom/language-php](https://github.com/atom/language-php)
* [textmate/sql.tmbundle](https://github.com/textmate/sql.tmbundle)   -> [atom/language-sql](https://github.com/atom/language-sql)
* [textmate/toml.tmbundle](https://github.com/textmate/toml.tmbundle) -> [atom/language-toml](https://github.com/atom/language-toml)
* [textmate/xml.tmbundle](https://github.com/textmate/xml.tmbundle)   -> [atom/language-xml](https://github.com/atom/language-xml)

Atom's grammars are updated far more frequently than TextMate's, and it doesn't take much snooping around their commit logs to notice this. This is especially important for fast-paced languages like CSS, where new properties are being introduced very often.

### CODE REVIEW

**Comment by pchaigno** [comment]
I think we should still check for each grammar that it improves highlighting. While I agree that Atom grammar seem to be evolving faster, TextMate grammars may still be better at highlighting in some cases.
@arfon What do you think?

**Comment by Alhadis** [comment]
Well, it'd surprise me if they did, considering Atom's grammars were originally derived from TextMate's...

**Comment by pchaigno** [comment]
Grammars for these fast-paced languages tend to grow rapidly. Despite the large number of automated tests in Atom grammars (that's certainly a plus), they are often subject to regressions.
For example, take the issue atom/language-javascript#366. [The original TextMate grammar doesn't have the same issue](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgithub.com%2Ftextmate%2Fjavascript.tmbundle%2Fblob%2Fmaster%2FSyntaxes%2FJavaScript.plist&grammar_text=&code_source=from-text&code_url=&code=%2F%7B%22%7D%2F) (I think, thanks to @infininight's more conservative approach when it comes to merging pull requests), while [the Atom grammar still does](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgithub.com%2Fatom%2Flanguage-javascript%2Fblob%2Fmaster%2Fgrammars%2Fjavascript.cson&grammar_text=&code_source=from-text&code_url=&code=%2F%7B%22%7D%2F).

I'm not saying we should necessarily stick with TextMate's grammars. I even agree that in the long run we should probably move to Atom's grammars. But I think we should be careful and assess each grammar before switching.

**Comment by Alhadis** [comment]
Aye, I'm in no rush to get this merged.

**Comment by arfon** [comment]
> I'm not saying we should necessarily stick with TextMate's grammars. I even agree that in the long run we should probably move to Atom's grammars. But I think we should be careful and assess each grammar before switching.

That sounds about right to me. In principal I think we should be moving away from un-maintained older grammars as long as there's an improvement in the user experience (syntax-highlighting).

**Comment by Alhadis** [comment]
Well, [here's the first definite](https://github.com/atom/language-xml/pull/54) improvement. =)

I've been meaning to compile a full list, but tonnes of endeavours have my attention locked elsewhere.

(... in other words, I'm more than capable of flaggin' my own PR as stale, thaaank ye very much <3)

**Comment by Alhadis** [comment]
Okay, there's no way I'm picking through all these conflicts. Easiest thing to do would be to simply have another crack at it later. With evidence of improvement, to boot.

**Pull request closed without merging**
