### PR TITLE
Update julia highlighter

### PR DESCRIPTION
**Pull request by jeremiahpslewis**

### CODE REVIEW

**Comment by Alhadis** [comment]
I've read JuliaEditorSupport/atom-language-julia#244 and I see what you're trying to do. However, updating the grammar version manually isn't going to have any effect, because grammar updates are only reflected on GitHub after a new release of Linguist has been published. This happens automagically during the release process too (users don't have to worry about keeping Linguist's version of a grammar up-to-date).

**Comment by jeremiahpslewis** [comment]
Makes sense to pull changes rather than depend on per language pushes. Do you have a rough idea of when the next release will happen?

**Comment by Alhadis** [comment]
Only @lildude can answer that, but there's usually a new release once every 1.5-2 months, depending on his schedule and/or bandwidth. 😉 (Cutting a release is a tedious and fiddly procedure, from what I understand)

**Comment by jonathantneal** [comment]
Thanks, @Alhadis! I was about to do something similar, and this thread saved me time and let me set expectations. My thanks to you and everyone helping out!

**Pull request closed without merging**
