### PR TITLE
Add more Yarn 2 folders into vendor list

### PR DESCRIPTION
**Pull request by kidonng**
## Description

Add two Yarn 2 folders to vendor list: `.yarn/sdks` and `.yarn/versions`, accroding to [the list of files used by Yarn 2](https://yarnpkg.com/advanced/qa#which-files-should-be-gitignored).

## Checklist:
- [x] **I am adding new or changing current functionality**
	- [ ] I have added or updated the tests for the new or changed functionality.

### CODE REVIEW

**Review by Alhadis — CHANGES_REQUESTED** [review]
According to the link you provided, there's a couple other filenames it recommends be added to one's `.gitignore`:

> * `.yarn/unplugged` and `.yarn/build-state.yml` should likely always be ignored […]
> * `.yarn/cache` and `.pnp.*` may be safely ignored, but you'll need to run `yarn install` to regenerate them

So this brings the complete list of vendored paths to:

~~~yaml
# Yarn 2
- (^|/)\.pnp\.
- (^|/)\.yarn/cache/
- (^|/)\.yarn/plugins/
- (^|/)\.yarn/releases/
- (^|/)\.yarn/sdks/
- (^|/)\.yarn/unplugged/
- (^|/)\.yarn/versions/
~~~

**Comment by kidonng** [comment]
`.pnp.*` is already added in #4863. `cache` is already present at https://github.com/github/linguist/pull/4977/files#diff-7a4aecbd604d08120b884f4369388be6R13. About the `unplugged` one I thought it should be handled by `.gitignore`, but after thinking twice I guess it makes sense to include it as well.

**Comment by Alhadis** [comment]
Users won't always have a `.gitignore` file that covers every commonly-ignored filetype. Some users knowingly track such files in version control (e.g., `node_modules` directories). Whatever the reason, ignoring a file is a different matter to simply marking it as vendored (which only affects Linguist's language usage stats).

**Review by Alhadis — APPROVED** [review]

**Review by lildude — APPROVED** [review]

**Comment by yordis** [comment]
Hey there,

I am a bit confused about my project, I recently had to https://github.com/straw-hat-team/javascript-monorepo/blob/7569a753a785acb272d4bb0122085862a1f6e176/.gitattributes#L1-L3 which doesn't seem to work perfectly (or it doesn't at all).

Is this particular package being used at GitHub? If so, is it released with such changes or how can I verify that it works since I needed to manually do these things in my project?

Thanks in advanced,

**Comment by lildude** [comment]
> which doesn't seem to work perfectly (or it doesn't at all).

You've needed to implement an override ride because Kurdish only marks these dirs as generated and your `.yarn` contains others:

https://github.com/github/linguist/blob/80f3531e8a1014a23f4606458e5a528053ed3cac/lib/linguist/vendor.yml#L44-L49

This override should do the trick to mark everything as generated, but it won't affect the Search results returned when you click the languages in the sidebar. It only affects the percentages.

What makes you think you override isn't working?

**Comment by yordis** [comment]
> PS This really should have been a new discussion

My apologies, I am not sure it was an issue or something so I asked the question here: https://github.com/github/linguist/discussions/5738

**Pull request merged**
