### PR TITLE
Add HyPhy as language to Linguist

### PR DESCRIPTION
**Pull request by mbdoud**
[HyPhy] (http://hyphy.org/w/index.php/Main_Page) has a [frequently used] (https://github.com/search?utf8=%E2%9C%93&q=extension%3Abf+fprintf&type=Code&ref=searchresults) batch language on GitHub. It shares an extension, ``.bf``, with [brainfuck] (http://en.wikipedia.org/wiki/Brainfuck), and to avoid misclassification, HyPhy should be added as a language to Linguist. I initially brought this up in an [issue] (https://github.com/github/linguist/issues/2365).

### CODE REVIEW

**Comment by pchaigno** [comment]
Do you have larger sample files? They are used to train the Bayesian classifier so the more representative they are, the better the detection results will be.

**Comment by mbdoud** [comment]
Sure, I've added some more representative files.

**Comment by pchaigno** [comment]
Here are the results from the sample files provided by @arfon:

 | Brainfuck | HyPhy |
---- | ---- | ---- |
[971 Brainfuck files](https://github.com/search?utf8=%E2%9C%93&q=extension%3Abf+NOT+fprintf+NOT+xml+NOT+ExecuteCommands&type=Code&ref=searchresults) | 99.51% | **0.49%** |
[1,000 HyPhy files](https://github.com/search?utf8=%E2%9C%93&q=extension%3Abf+fprintf&type=Code&ref=searchresults) | 0.00% | 100.00% |

Looks safe to merge :+1:

**Comment by arfon** [comment]
:+1: thanks for the Pull Request @mbdoud and your assistance testing @pchaigno.

I'm going to try and cut a new Linguist gem later this week which will include this change.

**Comment by mbdoud** [comment]
Thanks for all  your help @arfon  and @pchaigno!

**Pull request merged**
