### PR TITLE
Add support for Turtle and SPARQL

### PR DESCRIPTION
**Pull request by danmichaelo**
Tried adding support for [Turtle](http://www.w3.org/TR/turtle/) and [SPARQL](http://www.w3.org/TR/sparql11-overview/). Got 3 errors when running the test suite both before and after adding my changes – at least the number of errors didn't increase :)

Extensions:
- [.ttl](https://github.com/search?utf8=%E2%9C%93&q=title+extension%3Attl&type=Code&ref=searchresults)
- [.sparql](https://github.com/search?utf8=%E2%9C%93&q=title+extension%3Asparql&type=Code&ref=searchresults)
- [.rq](https://github.com/search?utf8=%E2%9C%93&q=title+extension%3Arq&type=Code&ref=searchresults)

### CODE REVIEW

**Comment by pchaigno** [comment]
There is now a license on the grammar's repository!

@danmichaelo Could you update your pull request against master? It would ease the merge ;)

**Comment by danmichaelo** [comment]
Ok, so it's updated

**Comment by arfon** [comment]
:+1: - looks good. Thanks @danmichaelo and @pchaigno.

This probably won't be live on GitHub for another couple of weeks.

**Pull request merged**
