### PR TITLE
Add gradlew and a few other filenames to Shell

### PR DESCRIPTION
**Pull request by Dominator008**

### CODE REVIEW

**Comment by arfon** [comment]
Hi @Dominator008. Thanks for adding these. Would you mind linking to examples of usage (a GitHub [search result](https://github.com/search?utf8=%E2%9C%93&q=extension%3Aboot+NOT+nothack&type=Code&ref=searchresults)) for each of these new filenames?

**Comment by Dominator008** [comment]
Here they are:

[.bash_history](https://github.com/search?utf8=%E2%9C%93&q=name+filename%3A.bash_history&type=Code&ref=searchresults)
[.bash_logout
](https://github.com/search?utf8=%E2%9C%93&q=name+filename%3A.bash_logout&type=Code&ref=searchresults)
[.bash_profile](https://github.com/search?utf8=%E2%9C%93&q=name+filename%3A.bash_profile&type=Code&ref=searchresults)
[.bashrc](https://github.com/search?utf8=%E2%9C%93&q=name+filename%3A.bashrc&type=Code&ref=searchresults)
[PKGBUILD](https://github.com/search?utf8=%E2%9C%93&q=name+filename%3APKGBUILD&type=Code&ref=searchresults)
[gradlew](https://github.com/search?utf8=%E2%9C%93&q=name+filename%3Agradlew&type=Code&ref=searchresults)

**Comment by Dominator008** [comment]
Ping? Thanks.

**Comment by arfon** [comment]
Thanks for this contribution @Dominator008 :zap:. This will be live in the next release of Linguist (likely sometime in the next week).

**Pull request merged**
