### PR TITLE
Swap grammar used for CSS highlighting

### PR DESCRIPTION
**Pull request by Alhadis**
[Latest episode of my lifelong quest to leave the world a prettier place](https://github.com/atom/language-css/pull/99#event-918545418). =)

I started a pull request to Atom's CSS grammar intending to update some keyword lists, but got sidetracked after noticing how many inaccuracies there were in the grammar. One week-long snowball later, it avalanched into what was practically a full-rewrite. The [finished grammar](https://github.com/atom/language-css) is battle-hardened against even the most [absurd permutations of grammar](https://gist.github.com/Alhadis/49a3122e33e5064133c407b28c28905a#file-absurd-css).

A bunch of gists can [be found here](https://gist.github.com/Alhadis/49a3122e33e5064133c407b28c28905a), which also features a list of keywords that outline just how many keywords are missing from GitHub's current CSS highlighting. Compare that with the result of this PR:

- [[`list-types.css`](https://gist.github.com/Alhadis/49a3122e33e5064133c407b28c28905a/raw/4bc83dbac0240c8f259660b90e35904449c22af1/list-types.css)]: [Before](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=source.css&grammar_url=&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgist.github.com%2FAlhadis%2F49a3122e33e5064133c407b28c28905a%2Fraw%2F4bc83dbac0240c8f259660b90e35904449c22af1%2Flist-types.css&code=) → [After](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgithub.com%2Fatom%2Flanguage-css%2Fblob%2Fmaster%2Fgrammars%2Fcss.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgist.github.com%2FAlhadis%2F49a3122e33e5064133c407b28c28905a%2Fraw%2F4bc83dbac0240c8f259660b90e35904449c22af1%2Flist-types.css&code=)
- [[`tags-html.css`](https://gist.github.com/Alhadis/49a3122e33e5064133c407b28c28905a/raw/4bc83dbac0240c8f259660b90e35904449c22af1/tags-html.css)]: [Before](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=source.css&grammar_url=&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgist.github.com%2FAlhadis%2F49a3122e33e5064133c407b28c28905a%2Fraw%2F4bc83dbac0240c8f259660b90e35904449c22af1%2Ftags-html.css&code=) → [After](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgithub.com%2Fatom%2Flanguage-css%2Fblob%2Fmaster%2Fgrammars%2Fcss.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgist.githubusercontent.com%2FAlhadis%2F49a3122e33e5064133c407b28c28905a%2Fraw%2F4bc83dbac0240c8f259660b90e35904449c22af1%2Ftags-html.css&code=)
- [[`tags-mathml.css`](https://gist.github.com/Alhadis/49a3122e33e5064133c407b28c28905a/raw/4bc83dbac0240c8f259660b90e35904449c22af1/tags-mathml.css)]: [Before](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=source.css&grammar_url=&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgist.githubusercontent.com%2FAlhadis%2F49a3122e33e5064133c407b28c28905a%2Fraw%2F4bc83dbac0240c8f259660b90e35904449c22af1%2Ftags-mathml.css&code=) → [After](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgithub.com%2Fatom%2Flanguage-css%2Fblob%2Fmaster%2Fgrammars%2Fcss.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgist.githubusercontent.com%2FAlhadis%2F49a3122e33e5064133c407b28c28905a%2Fraw%2F4bc83dbac0240c8f259660b90e35904449c22af1%2Ftags-mathml.css&code=)
- [[`tags-svg.css`](https://gist.githubusercontent.com/Alhadis/49a3122e33e5064133c407b28c28905a/raw/4bc83dbac0240c8f259660b90e35904449c22af1/tags-svg.css)]: [Before](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=source.css&grammar_url=&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgist.githubusercontent.com%2FAlhadis%2F49a3122e33e5064133c407b28c28905a%2Fraw%2F4bc83dbac0240c8f259660b90e35904449c22af1%2Ftags-svg.css&code=) → [After](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgithub.com%2Fatom%2Flanguage-css%2Fblob%2Fmaster%2Fgrammars%2Fcss.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgist.githubusercontent.com%2FAlhadis%2F49a3122e33e5064133c407b28c28905a%2Fraw%2F4bc83dbac0240c8f259660b90e35904449c22af1%2Ftags-svg.css&code=)
- [[`properties.css`](https://gist.github.com/Alhadis/49a3122e33e5064133c407b28c28905a/raw/4bc83dbac0240c8f259660b90e35904449c22af1/properties.css)]: [Before](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=source.css&grammar_url=&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgist.github.com%2FAlhadis%2F49a3122e33e5064133c407b28c28905a%2Fraw%2F4bc83dbac0240c8f259660b90e35904449c22af1%2Fproperties.css&code=) → [After](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgithub.com%2Fatom%2Flanguage-css%2Fblob%2Fmaster%2Fgrammars%2Fcss.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgist.github.com%2FAlhadis%2F49a3122e33e5064133c407b28c28905a%2Fraw%2F4bc83dbac0240c8f259660b90e35904449c22af1%2Fproperties.css&code=)
- [[`numbers.css`](https://gist.github.com/Alhadis/49a3122e33e5064133c407b28c28905a/raw/4bc83dbac0240c8f259660b90e35904449c22af1/numbers.css)]: [Before](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=source.css&grammar_url=&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgist.github.com%2FAlhadis%2F49a3122e33e5064133c407b28c28905a%2Fraw%2F4bc83dbac0240c8f259660b90e35904449c22af1%2Fnumbers.css&code=) → [After](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgithub.com%2Fatom%2Flanguage-css%2Fblob%2Fmaster%2Fgrammars%2Fcss.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgist.github.com%2FAlhadis%2F49a3122e33e5064133c407b28c28905a%2Fraw%2F4bc83dbac0240c8f259660b90e35904449c22af1%2Fnumbers.css&code=)

Full proof-of-coverage can be found by browsing the grammar's [now 3,400+ line spec-file](https://github.com/atom/language-css/blob/master/spec/css-spec.coffee).

/cc @50wliu, @kivikakk

### CODE REVIEW

**Comment by Alhadis** [comment]
```
1) Failure:
TestGrammars#test_submodules_have_approved_licenses [/home/travis/build/github/linguist/test/test_grammars.rb:130]:
The following submodules have unapproved licenses:
* vendor/grammars/language-css: 304be6184f7f344d44a1d13bddf511019624fd22
The license must be added to the LICENSE_WHITELIST in /test/test_grammars.rb once approved..
--- expected
+++ actual
@@ -1 +1 @@
-[]
+["vendor/grammars/language-css: 304be6184f7f344d44a1d13bddf511019624fd22"]
```
Heh. Alright, what'd I forget to do this time...? >_> (Man, it HAS been a while since I touched work on Linguist, hasn't it...?)

**Comment by kivikakk** [comment]
I think it should be fine to add `"304be6184f7f344d44a1d13bddf511019624fd22", # language-css` to `HASH_WHITELIST` in the failing test file.

**Comment by Alhadis** [comment]
Yep, but it's puzzling why it would even be necessary. I mean, the license is just vanilla Expat/MIT... :\

**Comment by Alhadis** [comment]
(I believe that whitelisting generally isn't done unless it's an edge-case... although I could be wrong, I'm not sure if there've been changes to the `licensee` gem's behaviour...)

**Comment by kivikakk** [comment]
I assume it's the extra bits at the bottom of LICENSE.md that confuse it. `atom-language-rust` has an exemption but is pretty much vanilla MIT too.

**Comment by Alhadis** [comment]
I hear ya. Gonna shove a fistful of comprehension down its throat, then.

**Comment by kivikakk** [comment]
Looks like `vendor/licenses/config.yml` may need `language-css` added under reviewed/grammar too.

**Comment by Alhadis** [comment]
Good grief, this is why I'm not a lawyer.



... hold on. =)

**Comment by Alhadis** [comment]
Resolved. The grammar is [expressly distributed under the MIT license](https://github.com/atom/language-css/blob/5d4af/package.json#L14), so there's no sense in having it incorrectly categorised as `other`.

**Comment by kivikakk** [comment]
:+1:

**Comment by pchaigno** [comment]
> I assume it's the extra bits at the bottom of LICENSE.md that confuse it.

Yep, Licensee is very strict on that. The slightest modification causes the license to be unrecognized. I guess it's understandable, since very small modifications can change the whole meaning of the license.

> @pchaigno AIDERRR

We'd say *A l'aide !* in French ;)

**Pull request merged**
