### PR TITLE
Repoint razor-plus grammar submodule at new repo

### PR DESCRIPTION
**Pull request by bval**
New repo location for razor-plus grammar.

## Description
It appears that @austincummings has removed his `razor-plus` repo which contained the grammar used for identifying cshtml files as discussed in #3760. This has broken the build for linguist and is currently preventing other PRs from landing.

Because that project was MIT licensed I have pushed a copy of it to my GitHub account, indicated in the README it is unmaintained, and repointed the submodule to the new location. I am also open to just removing that grammar entirely, but it seemed like from the earlier issue users found this grammar useful.
## Checklist:

- [ ] **I am associating a language with a new file extension.**
  - [ ] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      
      - https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am adding a new language.**
  - [ ] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a syntax highlighting grammar: [URL to grammar repo]
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

- [ ] **I am fixing a misclassified language**
  - [ ] I have included a new sample for the misclassified language:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [x] **I am changing the source of a syntax highlighting grammar**
  - Old: https://github.com/austincummings/razor-plus
  - New: https://github.com/bval/razor-plus

- [ ] **I am updating a grammar submodule**
  

- [ ] **I am adding new or changing current functionality**
  
  - [ ] I have added or updated the tests for the new or changed functionality.

- [ ] **I am changing the color associated with a language**
  
  - [ ] I have obtained agreement from the wider language community on this color change.
    - [URL to public discussion]
    - [Optional: URL to official branding guidelines for the language]

### CODE REVIEW

**Comment by bval** [comment]
image

@lildude Always another yak to shave. The build is currently broken as this grammar disappeared. If you're cool repointing it to my account, I'll keep it online there, or I'm open to axing it entirely.

**Review by Alhadis — APPROVED** [review]

**Comment by lildude** [comment]
> Because that project was MIT licensed I have pushed a copy of it to my GitHub account, indicated in the README it is unmaintained, and repointed the submodule to the new location. 

If you prefer, we can add it to the [github-linguist](https://github.com/github-linguist) org. We've done this in the past for abandoned grammars whilst we wait for better alternatives.

Or, and probably better, we could switch to the actively maintained grammar in https://github.com/dotnet/razor-tooling/ (grammars are [here](https://github.com/dotnet/razor-tooling/tree/main/src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes) and should be picked up by the compiler though I've not tested this yet).

> I am also open to just removing that grammar entirely, but it seemed like from the earlier issue users found this grammar useful.

Yeah, we can't do that until we've got something else catering for the syntax highlighting just as well. Switching might be the best option for the long run.

**Comment by bval** [comment]
> > Because that project was MIT licensed I have pushed a copy of it to my GitHub account, indicated in the README it is unmaintained, and repointed the submodule to the new location.
> 
> If you prefer, we can add it to the [github-linguist](https://github.com/github-linguist) org. We've done this in the past for abandoned grammars whilst we wait for better alternatives.

That works for me. I'll initiate a repo transfer there if you have the ability to accept it. And update this PR with a commit pointing there when it's landed.

> Or, and probably better, we could switch to the actively maintained grammar in https://github.com/dotnet/razor-tooling/ (grammars are [here](https://github.com/dotnet/razor-tooling/tree/main/src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes) and should be picked up by the compiler though I've not tested this yet).

That sounds like the better option in the long run, but perhaps we ship this first with it in the github-linguist org, then follow on with a switch to that repo once we have had a chance to do some testing with it.

I'm going to issue the repo transfer now assuming you're able to accept. Thanks!

**Comment by lildude** [comment]
Sounds like a plan. Go for it. I'll deal with it tomorrow.

**Comment by bval** [comment]
> Sounds like a plan. Go for it. I'll deal with it tomorrow.

Immediately stopped in my tracks by my inability to issue a transfer request to an org I'm not a part of. You'd think I'd know that already. If you have the ability to add me as an org admin temporarily, I can knock that out and update the PR.

**Comment by bval** [comment]
image

✅

**Review by lildude — APPROVED** [review]

**Pull request merged**
