### PR TITLE
Add support for Futhark - futhark-lang.org

### PR DESCRIPTION
**Pull request by Ulrik-dk**
## Description

- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3A.fut+futhark+NOT+nothack
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - https://futhark-lang.org/
  <!-- Update the Lightshow URLs below to show the grammar in action if you included one.

### CODE REVIEW

**Comment by Ulrik-dk** [comment]
Duplicate request.

**Comment by Ulrik-dk** [comment]
This color is better, obviously

**Comment by Munksgaard** [comment]
Duplicate of https://github.com/github/linguist/pull/4842

**Comment by Alhadis** [comment]
Closing in favour of #4842, as @Munksgaard's submission is much more complete.

> This colour is better, obviously.

@Ulrik-dk Please read our [contributing guidelines](https://github.com/github/linguist/blob/b545f1c6befe87c2074e5e608f47ca0f6334d355/CONTRIBUTING.md#adding-a-language) on what we require of new language submissions. You might also want to read the section on [language colours](https://github.com/github/linguist/blob/b545f1c6befe87c2074e5e608f47ca0f6334d355/CONTRIBUTING.md#changing-the-color-associated-with-a-language); in particular, the rationale behind colour choices.

**Pull request closed without merging**
