### PR TITLE
Add carp language support (extension)

### PR DESCRIPTION
**Pull request by sheerun**
## Description
Add carp language support (extension)

https://github.com/carp-lang/Carp

## Checklist:

- [x] **I am associating a language with a new file extension.**
  - [x] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      
      - https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3Acarp%20loadq=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - https://raw.githubusercontent.com/CaptainLexington/diem/6c9f4150ded5a67548be4061486fffb982c3e9ff/src/resources.carp
    - Sample license(s): wtfpl
  - [x] I have included a change to the heuristics to distinguish my language from others using the same extension.
    - not applicable

### CODE REVIEW

**Comment by lildude** [comment]
Please follow the instructions on [Adding a language](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language), but before you do, take note of this requirement:

> we prefer that each new file extension be in use in hundreds of repositories before supporting them in Linguist.

A quick search of `.carp` suggests this may not be popular enough yet - you can use [Harvester](https://github.com/Alhadis/Harvester) to perform a more comprehensive search. Unless you expect the popularity to grow rapidly in the next month or so, I'd suggest you close this PR and open a new one, following the instructions, once `.carp` is more popular.

**Comment by sheerun** [comment]
I don't think github search works very well for extensions https://github.com/search?q=extension%3Acarp&type=Code returns zero results but 100% there tenths if not hundreds of repositories with .carp

**Comment by lildude** [comment]
> I don't think github search works very well for extensions https://github.com/search?q=extension%3Acarp&type=Code returns zero results but 100% there tenths if not hundreds of repositories with .carp

That's because you're not using the correct syntax. From the [docs](https://docs.github.com/en/github/searching-for-information-on-github/searching-code):

> Except with filename searches, you must always include at least one search term when searching source code. For example, searching for language:javascript is not valid, while amazing language:javascript is.

You've not included a search term. This is why we use `NOT nothack` in all our search queries.

**Comment by sheerun** [comment]
Okay I think you are right, sorry

**Pull request closed without merging**
