### PR TITLE
Add .plsql as extension for PL/SQL

### PR DESCRIPTION
**Pull request by chezwicker**
Adding .plsql as extension for PL/SQL

### CODE REVIEW

**Comment by arfon** [comment]
Hi @chezwicker - would you mind adding a sample file for this new extension. Also, please bring your branch up to date with master so the tests will pass.

**Comment by chezwicker** [comment]
Hi @arfon - I've added a new file based on an updated branch. Sorry, not really familiar with GitHub yet, thought there was automatic merging between forks for pull requests...

**Comment by chezwicker** [comment]
Hi @arfon - how can I see what makes the tests fail? When I navigate to travis, I seem to get no access to any information there ;-(

**Comment by chezwicker** [comment]
@arfon the test failure indicate by travis seems to be unconnected to what I am doing, I'm afraid I don't understand how the build can generally succeed! Here's what travis says:

```
1) Failure:
TestGrammars#test_local_scopes_are_in_sync [/home/travis/build/github/linguist/test/test_grammars.rb:62]:
The scopes listed for vendor/grammars/sublime_cobol in grammars.yml don't match the scopes found in that repository.
--- expected
+++ actual
@@ -1 +1 @@
-["source.acucobol", "source.cobol", "source.opencobol"]
+["source.acucobol", "source.cobol", "source.jcl", "source.opencobol"]
```

**Comment by arfon** [comment]
> @arfon the test failure indicate by travis seems to be unconnected to what I am doing, I'm afraid I don't understand how the build can generally succeed! Here's what travis says:

Yeah I broke master for a few hours this morning :-\

**Pull request merged**
