### PR TITLE
Support for Scilla smart contracts

### PR DESCRIPTION
**Pull request by as1ndu**
## Adding support for the Scilla programming language

Scilla, short for `Smart Contract Intermediate-Level Language`, is an intermediate-level smart contract language being developed for [Zilliqa](https://zilliqa.com/). 

Scilla has been designed as a principled language with smart contract safety in mind.

The official Scilla website is over at [https://scilla-lang.org/](https://scilla-lang.org/)

- [X] **I am adding a new language.**
  - [X] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  [https://github.com/search?q=extension%3Ascilla+%22transition%22&type=Code](https://github.com/search?q=extension%3Ascilla+%22transition%22&type=Code)
      -  [https://github.com/search?q=extension%3Ascillib+%22let%22&type=Code](https://github.com/search?q=extension%3Ascillib+%22let%22&type=Code)
  - [X] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [Hello World example in Scilla](https://github.com/as1ndu/linguist/blob/master/samples/Scilla/helloworld.scilla)
      - [Library example](https://github.com/as1ndu/linguist/blob/master/samples/Scilla/pairutils.scillib)
    - Sample license(s): https://github.com/as1ndu/scilla-grammar/blob/master/LICENSE
  
  - [x] I have included a syntax highlighting grammar: https://github.com/as1ndu/scilla-grammar

### CODE REVIEW

**Comment by as1ndu** [comment]
Scilla has been in development for over 2 years and just went live about [2 month ago (early July)](https://finance.yahoo.com/amphtml/news/zilliqa-passes-milestone-addition-smart-112051701.html)

I am confident the the number will grow significantly in the coming months. 

For instance the Scilla VScode plugin I am working on now has over [400 plus downloads](https://marketplace.visualstudio.com/items?itemName=as1ndu.scilla)yet it was just released early this year. 

There are also several independent  projects that rely on Scilla (tending to 100) [funded by their $5 million dollar grant](https://blog.zilliqa.com/buildonzil-introducing-the-zilliqa-ecosystem-grant-programme-6ccb98892712?gi=ef49aa9e1fb3)  program.

These projects are expected to go live OpenSource  by the end of the year.

There is also interest from large cooperations like [NASDAG](https://www.nasdaq.com/article/high-throughput-blockchain-developer-zilliqa-showcases-next-generation-smart-contracts-cm975003/amp) & [Pepsi Co](https://www.google.com/amp/s/www.coindesk.com/pepsico-blockchain-trial-brings-28-boost-in-supply-chain-efficiency%3famp)

**Comment by pchaigno** [comment]
@as1ndu Thanks for the information! I will add these extensions to #4219 to monitor in-the-wild usage.

**Comment by Elliott-Green** [comment]
Hey @pchaigno,

Could this be reviewed again? The language and adoption has grown since OP posted. Doing a manual search without harvester I'm getting 5k files returned so I think we're meeting the in-the-wild usage now.

Thanks.

**Comment by Elliott-Green** [comment]
@lildude

Please could you offer some guidance with regards to the above. Thanks!

**Pull request closed without merging**
