### PR TITLE
Display IntelliJ configurations files as XML

### PR DESCRIPTION
**Pull request by SimenB**
Sample file: https://github.com/OverZealous/gulp-task-listing/blob/43f766157cb892fd2d8f9322d85a9ac56960a14c/.idea/gulp-task-listing.iml

### CODE REVIEW

**Comment by pchaigno** [comment]
@SimenB Thanks for the pull request! Could you add the sample file in the `samples/XML/` in your branch?

For reviewers: [558,000 `.iml` files](https://github.com/search?utf8=%E2%9C%93&q=extension%3Aiml+NOT+fjgjdbfkdf), [526,000](https://github.com/search?utf8=%E2%9C%93&q=extension%3Aiml+xml&type=Code&ref=searchresults) appear to be XML files so I think it's safe to add it ;)

**Comment by SimenB** [comment]
@pchaigno Done :smile:

**Comment by pchaigno** [comment]
Awesome :+1:

**Comment by arfon** [comment]
:+1: thanks @SimenB. This will be live in the next release of Linguist.

**Pull request merged**
