### PR TITLE
Add codemirror's demo directory

### PR DESCRIPTION
**Pull request by BerkeleyTrue**
This accounts for about ~150 html files throwing off the statistics of one of my projects

### CODE REVIEW

**Comment by pchaigno** [comment]
I guess it doesn't hurt but is the `demo` directory really supposed to be copied over with the `lib` and other directories?

**Comment by BerkeleyTrue** [comment]
Not sure, its there. I'm looking to remove it but thought I would make a PR for others.

**Comment by pchaigno** [comment]
Oki :+1:

**Comment by arfon** [comment]
:+1:

**Comment by arfon** [comment]
This change will be live on GitHub in the next release.

**Pull request merged**
