### PR TITLE
Change color for Kotlin based on color in logo

### PR DESCRIPTION
**Pull request by bashor**
IMHO it's more suitable.

### CODE REVIEW

**Comment by pchaigno** [comment]
The Travis build is failing because this new color is too close to [Haxe's color](https://github.com/bashor/linguist/blob/patch-1/lib/linguist/languages.yml#L1348) ;)

**Comment by bkeepers** [comment]
@bashor The test is failing because the color is still too close to another one. Feel free to open another pull request with another color. You can see the existing colors here: http://github.github.io/linguist/

**Comment by bashor** [comment]
ok, thanks!

**Comment by bashor** [comment]
Do you have any advice how simpler choice a new color and check that it's ok?

**Comment by bkeepers** [comment]
@gjtirikian do you have any advice for that?

**Comment by gjtorikian** [comment]
I wrote up my process over here: https://github.com/github/linguist/pull/2298#issuecomment-90150424

I always recommend using official colors whenever possible.

Here's the proposed color for Kotlin in this PR: http://www.color-hex.com/color/f18e33

Here's the conflict, with [Haxe](http://haxe.org/): http://www.color-hex.com/color/f7941e

I'm not sure if Haxe has an official color but they do look awfully similar. In this case I'd opt to either lighten or darken the Haxe color to allow the Kotlin one to pass.

Gonna reopen this PR since @bashor has reemerged and it sounds like there's interest in fixing the test here.

**Comment by bashor** [comment]
Will be nice to have online tool for that :)

**Comment by bashor** [comment]
The problem for me is that I can't check changed colors  quickly :( Some time ago I tried to run tests locally but I failed on install dependencies.

**Comment by gjtorikian** [comment]
Given that the CLA was signed I just brought this in with an update to Haxe:

image 2015-06-20 at 9 56 08 am

**Comment by bashor** [comment]
Thanks a lot, @gjtorikian

**Pull request closed without merging**
