### PR TITLE
Add ISPC language

### LINKED ISSUE #5042: Add language: ISPC
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

[ISPC (Intel SPMD Program Compiler)](https://github.com/ispc/ispc) is a language designed for writing SIMD optimized programs. It is seeing more and more adoption in the game industry and I'm kind of surprised it isn't already detected.

Ispc uses two file extensions: `.ispc` for source files and `.isph` for headers. 

### URL of the affected repository:

https://github.com/BinomialLLC/bc7e  
https://github.com/GameTechDev/ISPCTextureCompressor  

There are many others: https://github.com/search?q=.ispc&type=code

### Last modified on:
2020-10-11

### Expected language:
ISPC

### Detected language:
None

### PR DESCRIPTION
**Pull request by Nixinova**
Adds the ISPC language, full name "Intel® Implicit SPMD Program Compiler" https://github.com/ispc/ispc, extension `.ispc`, along with its header files `.isph`.

Closes #5042

Color `#006ac8` taken from official site https://ispc.github.io/

Usage:
- [ispc](https://github.com/search?q=extension%3Aispc&type=code): 6K+
- [isph](https://github.com/search?q=extension%3Aisph&type=code): 3K+

Samples:
- [isph](https://github.com/ispc/ispc/blob/main/ispcrt/ispcrt.isph), BSD3 Clause
- [ispc](https://github.com/ispc/ispc/blob/main/examples/cpu/sort/sort.ispc), ditto

Using C grammar for now as I cannot find the source of https://pastebin.com/8aHLeWU7 (taken from intel-corporation.ispc@v1.1.0 in the VSCode Marketplace)

### CODE REVIEW

**Comment by Nixinova** [comment]
autolinker, fix #5042

**Comment by davidbrown2324** [comment]
@Nixinova 
Did you add syntax highlighting for the ISPC language? 
It looks like you can add the language without it. Is that right? 
Would be so much easier.
I hope your pull request gets approved soon.

**Comment by Nixinova** [comment]
No, I'm just using C grammar for now as I cant find the actual source of the proper grammar, and yes you can add a language without a new grammar.

**Comment by davidbrown2324** [comment]
> No, I'm just using C grammar for now as I cant find the actual source of the proper grammar, and yes you can add a language without a new grammar.

Thanks for all your help. I have been wanting to do this for a couple of months, you have been a big help.

**Comment by lildude** [comment]
Can you please state in the original note of this PR where the sample files came from and the license of each.

**Comment by Nixinova** [comment]
Done, both from https://github.com/ispc/ispc under BSD-3

**Comment by lildude** [comment]
Usage is a little short on both extensions at the moment:

- `.ispc`:

Total files found: 6790
Unique public user/repos: 142
Unique owners: 127

- `.isph`

Total files found: 3074
Unique public user/repos: 158
Unique owners: 143

We like to shoot for 200 unique user/repos. It doesn't look like we're far off either so it probably won't be long.

**Comment by Nixinova** [comment]
Closing until usage is reach.

**Comment by pbrubaker** [comment]
With both DreamWorks Moonray and Unreal 5 using it extensively, I'd ask for consideration on supporting the language now.

**Comment by pbrubaker** [comment]
Hey @lildude.  I am not able to get all the stats you posted here. so I would appreciate your help checking the current stats.

Also are you able to include private repos like Unreal?  As the evangelist for the compiler I know there's way more usage out there than is represented in the stats for public repos.

**Pull request closed without merging**
