### PR TITLE
Remove NANT grammar from CSharp

### PR DESCRIPTION
**Pull request by damieng**
We no longer include this grammar in atom/language-csharp as it caused issues with highlighting bash etc. and was unmaintained.

## Description
The NANT grammar is no [longer supplied in atom/language-csharp](https://github.com/atom/language-csharp/commit/25bf029d7b7f591f0b8e4c6b9e54c53111f162e5) where Linguist takes the other C# grammars from.

## Checklist:

- [ ] **I am associating a language with a new file extension.**
  - [ ] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      
      - https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am adding a new language.**
  - [ ] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a syntax highlighting grammar.
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am fixing a misclassified language**
  - [ ] I have included a new sample for the misclassified language:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am changing the source of a syntax highlighting grammar**
  
  - Old: https://github-lightshow.herokuapp.com/
  - New: https://github-lightshow.herokuapp.com/

- [ ] **I am adding new or changing current functionality**
  
  - [ ] I have added or updated the tests for the new or changed functionality.

### CODE REVIEW

**Comment by Alhadis** [comment]
Looks good, @damieng. You'll just need to sign the [CLA](https://cla.github.com/github/linguist/accept/damieng) and we can merge. :wink:

**Comment by pchaigno** [comment]
Is this actually required? We don't use the `source.nant-build` scope in any language, and it will be automatically removed with the next release, when we update the grammar submodules.

**Comment by lildude** [comment]
> Is this actually required? 

Nope. As @pchaigno pointed out, this will happen automagically when we make a new release.

**Comment by Alhadis** [comment]
Merge anyway. He's from the Atom team, and they've put up with so much of my shit. :green_heart:

**Comment by lildude** [comment]
> Merge anyway.

Yup. No harm in it. Failing tests are unrelated and will be fixed once https://github.com/github/linguist/pull/4037 has been merged.

**Comment by Alhadis** [comment]
@lildude I'll review your JSX fork once some loose ends are tied up with Atom's `file-icons` package (which was blocked for months due to no MacBook). Just an FYI. :wink:

**Comment by damieng** [comment]
@Alhadis of course I remember you!

Didn't realize it would be auto-removed, that's great. We just did a big overhaul of the C# grammar basing it on Microsoft's own work now so just trying to make sure this all goes through Linguist cleanly.  Will be doing some more testing today on that.

**Pull request merged**
