### PR TITLE
WIP: Add Terra programming language support

### PR DESCRIPTION
**Pull request by pyk**
I want to add [Terra](http://terralang.org/index.html) to linguist. But, I'm stuck at [adding grammar](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language) for Terra.

Terra have the same syntax as Lua. Is another grammar required?

I would like to use existing [lua grammar](https://github.com/textmate/lua.tmbundle) as terra grammar. But I don't know how to do it. Any help is appreciated.

Thanks!

Related #2820

### CODE REVIEW

**Comment by pyk** [comment]
Link to [Github search result](https://github.com/search?utf8=%E2%9C%93&q=extension%3At+terra&type=Code&ref=searchresults)

**Comment by pchaigno** [comment]
Is this still work in progress or do you need some help?

**Comment by arfon** [comment]
Hi @pyk, thanks for starting this. This PR is looking in pretty good shape but there are way too many samples - would you mid reducing this to ~3-5 reasonably-sized sample files?

**Comment by arfon** [comment]
:flags: flagging this as stale :flags:

**Comment by arfon** [comment]
Replaced by #2875

**Pull request closed without merging**
