### PR TITLE
Add ECR (Embedded Crystal)

### PR DESCRIPTION
**Pull request by keplersj**

### CODE REVIEW

**Comment by arfon** [comment]
Hi @keplersj, thanks for opening this Pull Request :zap:

Please take a look at our [contributing guidelines](https://github.com/github/linguist/blob/master/CONTRIBUTING.md) to finish up the additional steps required before review :smile:

**Comment by keplersj** [comment]
Sorry, totally forgot to provide a GitHub search showing in-the-wild usage.

[GitHub Search Showing existing ECR files.](https://github.com/search?utf8=%E2%9C%93&q=extension%3Aecr+NOT+nothack&type=Code&ref=searchresults)

**Comment by pchaigno** [comment]
FYI, that's about 490 repositories from 158 different users.

I also noticed some of these files have a different syntax (for instance, files from [the last page of results](https://github.com/search?p=36&q=extension%3Aecr+NOT+nothack&ref=searchresults&type=Code&utf8=%E2%9C%93)). Are these files ECR files too?

**Comment by keplersj** [comment]
Yes, the files on that last page are all files using ECR for templating. ECR is a lot like ERB in that it can be used for any file.

**Comment by arfon** [comment]
Thanks @keplersj. This will be live in the next release of Linguist (likely next week sometime).

**Pull request merged**
