### PR TITLE
Revert "Replace the tokenizer with a flex-based scanner"

### PR DESCRIPTION
**Pull request by kivikakk**
Reverts github/linguist#3846.

It went belly up! Currently looking at results from fuzzing but until it's fixed this isn't stable.

/cc @lildude

### CODE REVIEW

**Comment by kivikakk** [comment]
Why did this try to revert everything since this PR!? Agh.

**Comment by kivikakk** [comment]
and … why did it make it not based on the current master? oh my goodness.

**Comment by kivikakk** [comment]
WHATEVER. Fixed!

**Comment by lildude** [comment]
Approved though moot now I've seen #3900. I'll leave the choice up to you @kivikakk.

**Pull request closed without merging**
