### PR TITLE
Change source for svelte

### PR DESCRIPTION
**Pull request by 3ventic**
## Description
Changes the source for Svelte from a seemingly abandoned fork to the original, active, repository. This change is prompted by a bug in the grammar; the fork has disabled issues, and the original repository has since added a compatible license (MIT) and commits, which possibly fix my issue.

## Checklist:

- [x] **I am changing the source of a syntax highlighting grammar**
  - Old: https://github.com/umanghome/svelte-atom
  - New: https://github.com/sveltejs/svelte-atom

### CODE REVIEW

**Review by lildude — CHANGES_REQUESTED** [review]
Please use the `script/add-grammar` script to replace the grammar and add the updated cached license produced by that script to this PR.

**Comment by 3ventic** [comment]
@lildude That is what I did. Running the script only results in ordering difference in .gitmodules.

This was the exact command used with no further changes in the branch:
```
script/add-grammar --replace vendor/grammars/svelte-atom https://github.com/sveltejs/svelte-atom
```

**Review by lildude — APPROVED** [review]
🤷 Tests are passing so I'm happy 😁

**Review by jewell4003 — COMMENTED** [review]
Lisa snoore

**Pull request merged**
