### PR TITLE
Add Wollok educational language to linguist

### PR DESCRIPTION
**Pull request by fdodino**
Hi, @pchaigno, related to PR #2678 , I did a new PR to add just .wlk files (next year I will try to add .wtest too as usage grows).

Wollok is an educational OO language: http://www.wollok.org/en/
It is used in several matters of different universities: UTN Buenos Aires (thttp://pdep.com.ar), UTN Delta, UNSAM (www.unsam.edu.ar), UNQ (www.unq.edu.ar)

This year we are moving to github classroom instead of SVN, so visibility will increase.

Many thanks!
Have a nice week!
Fernando

### CODE REVIEW

**Comment by pchaigno** [comment]
Please make sure to follow the [guidelines to add support for a new language](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language). In particular, you'll need to run `script/set-language-ids --update`.

**Comment by fdodino** [comment]
Hi Paul,
          I'm sorry, I forgot that step. I will review all the  PR and come back.
Thanks
Fernando

**Comment by fdodino** [comment]
Well, I will close this PR and open a brand new, with all steps required. Sorry for wasting your time Paul.

**Comment by pchaigno** [comment]
You're not wasting my time :-)

**Pull request closed without merging**
