### PR TITLE
Add improved grammars for Yacc and Lex

### PR DESCRIPTION
**Pull request by Alhadis**
This PR adds a grammar for [Lex/Flex](https://en.wikipedia.org/wiki/Flex_(lexical_analyser_generator)), files, and replaces the one used to highlight [Yacc/Bison](https://en.wikipedia.org/wiki/GNU_Bison).

## Yacc/Bison
We're still using the old TextMate bundle, which hasn't had an update in [12 years](https://github.com/textmate/bison.tmbundle/commit/7ffa5216da9a62cda8cf8f544da8cf5752089366). Furthermore, the bundle was only an unfinished stub, according to the commit notes of [`textmate/bison.tmbundle@7ffa521`](https://github.com/textmate/bison.tmbundle/commit/7ffa5216da9a62cda8cf8f544da8cf5752089366):

> Commit a bare-bones start at a Bison bundle that I've had sitting around for a while
>
> git-svn-id: http://svn.textmate.org/trunk/Bundles/Bison.tmbundle@7733 dfb7d73b-c2ec-0310-8fea-fb051d288c6d

I've rewritten it from scratch. The improvements are immediately apparent; I doubt this PR will take very long to review. 😜

/cc @pchaigno

## Checklist:
- [x] **I am changing the source of a syntax highlighting grammar**
	- **Lex:** [Preview](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=cson&grammar_url=https%3A%2F%2Fgithub.com%2FAlhadis%2Flanguage-grammars%2Fblob%2Fmaster%2Fgrammars%2Flex.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fgithub%2Flinguist%2Fmaster%2Fext%2Flinguist%2Ftokenizer.l&code=)
	- **Yacc:** [Before](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=source.bison&grammar_format=auto&grammar_url=&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fbluerise%2Fopenbsd-xenocara%2Fraw%2F4977191542f3b3e27b2a6f6a9bc16ae6288d2649%2Flib%2Fmesa%2Fsrc%2Fcompiler%2Fglsl%2Fglsl_parser.yy&code=) | [After](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fgithub.com%2FAlhadis%2Flanguage-grammars%2Fblob%2Fmaster%2Fgrammars%2Fyacc.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fbluerise%2Fopenbsd-xenocara%2Fraw%2F4977191542f3b3e27b2a6f6a9bc16ae6288d2649%2Flib%2Fmesa%2Fsrc%2Fcompiler%2Fglsl%2Fglsl_parser.yy&code=)

### CODE REVIEW

**Comment by Alhadis** [comment]
On a sidenote, [I had](https://github.com/Alhadis/language-grammars/commit/72c972fb3a633bd9da9cdea398945be7d7bc9d7a) to use `source.c++` as the embedded grammar's scope, instead of `source.cpp`. The former is used by [the old TextMate bundle](https://github.com/textmate/c.tmbundle/blob/39898a8af42d2afa667ce5238e3765704d0d173e/Syntaxes/C%2B%2B.plist#L720); the latter by Atom (changed by @maxbrunsfeld in [`atom/language-c@f74f7b3`](https://github.com/atom/language-c/commit/f74f7b307105cd9ad0bfc3bac3f15cd7d828c2d4)).

I'd like the `language-grammars` package to support both GitHub and Atom users, but that would necessitate two different scope-names, which will raise a complaint [from our grammar compiler](https://github.com/github/linguist/issues/3924). @vmg, is this something we can avoid?

**Comment by pchaigno** [comment]
The Lex grammar seems to be having issues "parsing" the middle of [the preview file](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=cson&grammar_url=https%3A%2F%2Fgithub.com%2FAlhadis%2Flanguage-grammars%2Fblob%2Fmaster%2Fgrammars%2Fjlex.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2FCNR-ITTIG%2FxmLegesMarker%2F55c81c33791b324300f7152f21936561df84984a%2FxmLegesMarker%2FMarker_1.7%2Fprehtml.lex&code=). Is that expected?

**Comment by Alhadis** [comment]
(I see I was a bit too hasty with selecting a preview file...😂) Yes, that is to be expected, as the file isn't completely valid Lex source. In fact, it almost appears as if it were copied from an HTML rendering of a Lex file's source code... :confused:

I'll pick another...

**Comment by Alhadis** [comment]
I was also using the wrong highlighting grammar (`jlex.cson` instead of `lex.cson`), which probably wasn't helping...

**Pull request merged**
