### PR TITLE
Switch the Scheme repo

### PR DESCRIPTION
**Pull request by sorawee**
Switch the Scheme repo

## Description

The current Scheme repo is unmaintained. Several bug fixes PR
are left unmerged for years. We forked the repo and
incorporated the bug fixes. This PR switches the repo to ours.

## Checklist:

- [x] **I am changing the source of a syntax highlighting grammar**
  
  - Old: https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fgithub.com%2Ftextmate%2Fscheme.tmbundle%2Fblob%2Fmaster%2FSyntaxes%2FScheme.plist&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fracket%2Fracket%2Fblob%2Fmaster%2Fracket%2Fsrc%2Fcs%2Frumble%2Fdefine.ss&code=
  - New: https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fgithub.com%2Fsicp-lang%2Fscheme.tmbundle%2Fblob%2Fmaster%2FSyntaxes%2FScheme.plist&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fracket%2Fracket%2Fblob%2Fmaster%2Fracket%2Fsrc%2Fcs%2Frumble%2Fdefine.ss&code=

### CODE REVIEW

**Comment by sorawee** [comment]
I do not know why `solidity` and `conllu`, and `hy` are deleted, but they make Travis failing, so I'm gonna manually add them back.

**Comment by pchaigno** [comment]
Did you use the provided script? The submodule itself didn't change. Were there any error messages?

**Comment by sorawee** [comment]
@pchaigno I did use the script, but it erroneously deletes other grammars (see https://github.com/github/linguist/pull/4437/commits/113ea75bdc7355a209c93f6f70767191167b11b6). That's why I pushed another commit to bring them back.

Is the current state looking good?

**Comment by pchaigno** [comment]
> Is the current state looking good?

No, you're missing a change in vendor/grammars/. The previous commit was also missing it. Maybe you forgot to commit some changes?

**Comment by sorawee** [comment]
Interesting. Somehow the submodule was in the detached HEAD state. I checkout master and commit the change. Does this look good now?

**Comment by pchaigno** [comment]
The Travis CI build is failing because the cached license is outdated. [`add-grammar -r` should have updated that automatically](https://github.com/github/linguist/blob/e4560984058b4726010ca4b8f03ed9d0f8f464db/script/add-grammar#L112). Could you run `./script/licensed`?

**Comment by sorawee** [comment]
Done! Thanks so much for your help and for bearing with me.

It's really weird cause I did run `./script/add-grammar --replace scheme.tmbundle https://github.com/sicp-lang/scheme.tmbundle`. Not sure why it left the repo in this state.

**Comment by pchaigno** [comment]
Weird indeed. I'll try to reproduce in the evening if I get a chance.

**Comment by lildude** [comment]
> I do not know why `solidity` and `conllu`, and `hy` are deleted, but they make Travis failing, so I'm gonna manually add them back.

For `solidity` it's because the grammar changed from TextMate to an incompatible format - Sublime -  so the compiler can't/won't attempt to compile it. https://github.com/github/linguist/pull/3973#issuecomment-461802620 has more deets.  I aim to sort this out sometime this week or early next...

`conllu` and `hy` are known outliers caused by the fact their grammars aren't in one of the directories expected by https://github.com/github/linguist/blob/e4560984058b4726010ca4b8f03ed9d0f8f464db/tools/grammars/compiler/loader.go#L124-L125

I've been meaning to sort these two out too... hopefully this week too.

**Pull request merged**
