### PR TITLE
Release v7.2.0

### PR DESCRIPTION
**Pull request by lildude**
It's been a long time coming, but it's finally here... v7.2.0 which adds new languages and updates the grammars for all languages.

_[Template removed as it's not relevant]_

### CODE REVIEW

**Comment by lildude** [comment]
This is now live on GitHub.com

**Comment by SCKelemen** [comment]
This really confused me this morning... I saw the language colors change, and I thought something was awry

**Comment by Alhadis** [comment]
@SCKelemen Are you referring to the `.git*` highlighting?

Given how long those files have been unhighted for, the sudden colouration has probably caught a few users off-guard...

**Comment by SCKelemen** [comment]
@Alhadis 
That, and some of the language colors changed. The Go color, for example. 
screen shot 2019-02-08 at 1 57 07 pm

screen shot 2019-02-08 at 1 57 57 pm

**Pull request merged**
