### PR TITLE
Add `.pbt` as an extension for Protocol Buffer Text

### PR DESCRIPTION
**Pull request by Stanzilla**
## Checklist:

- [x] **I am associating a language with a new file extension.**
  - [x] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      
      - https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3Apbt+core+NOT+nothack
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s): 
      - https://github.com/coreslinkous/TeaShop/blob/main/Data/ProjectSettings.pbt
    - Sample license(s): https://github.com/coreslinkous/TeaShop/blob/main/LICENSE
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am adding a new language.**
  - [ ] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable] 
    - Sample license(s):
  
  - [ ] I have included a syntax highlighting grammar: https://github-lightshow.herokuapp.com/
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

- [ ] **I am fixing a misclassified language**
  - [ ] I have included a new sample for the misclassified language:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am changing the source of a syntax highlighting grammar**
  
  - Old: https://github-lightshow.herokuapp.com/
  - New: https://github-lightshow.herokuapp.com/

- [ ] **I am updating a grammar submodule**
  

- [ ] **I am adding new or changing current functionality**
  
  - [ ] I have added or updated the tests for the new or changed functionality.

- [ ] **I am changing the color associated with a language**
  
  - [ ] I have obtained agreement from the wider language community on this color change.
    - [URL to public discussion]
    - [Optional: URL to official branding guidelines for the language]

### CODE REVIEW

**Review by lildude — CHANGES_REQUESTED** [review]
Can you please add a sample for this extension too and update the OP to state where the file came from and the license that covers it.

**Comment by Stanzilla** [comment]
I'm unsure about how to best deal with the fact that PowerBuilder also uses pbt

**Comment by lildude** [comment]
> I'm unsure about how to best deal with the fact that PowerBuilder also uses pbt

We normally rely on heuristics if the structures of the languages are quite similar but have unique ways to distinguish them. In this case, I think they're sufficiently different that we can rely on the classifier. To increase the chances of the classifier getting it right, please add another Proto buffer `.pbt` sample. The "Classifier cross-validation" test should highlight if this is sufficient (it needs two samples per language).

**Review by lildude — APPROVED** [review]
Looks good.

**Comment by Stanzilla** [comment]
@lildude Sorry for the bump in here but is there a way to know which version of linguist is currently deployed on GitHub? I just want to make sure there was no issue with my PR because I don't see any of the repos using the new attribution yet.

**Comment by lildude** [comment]
> there a way to know which version of linguist is currently deployed on GitHub?

7.21.0... deployed this morning, however this PR shipped with [7.19.0](https://github.com/github/linguist/releases/tag/v7.19.0) which was deployed waaaaay back in February.

> I just want to make sure there was no issue with my PR because I don't see any of the repos using the new attribution yet.

You need to push a change for your repo to be re-analysed to pick up any new languages etc.

It would also only appear as the language in a list of repos if this were the primary language of the repo.

**Comment by lildude** [comment]
Oh yes, I also forgot to say: the language is "data" so won't show in the language stats unless someone explicitly sets the `linguist-detectable` override. This applies to all "data" languages.

Syntax highlighting is however working and easy to check.

**Comment by Stanzilla** [comment]
@lildude oh I see, thank you! I had assumed that it would be detectable by default, so I assume everyone who uses it will have to add the `linguist-detectable` attribute in their `.gitattributes` file still?

**Comment by lildude** [comment]
Yup, but only if they want it to show in their language stats.

**Pull request merged**
