### PR TITLE
Update Swift color to match the official Swift logo

### PR DESCRIPTION
**Pull request by eneko**
## Description
Update color for Swift programming language to match the orange from the official Swift logo (from swift.org)

Swift logo

Before: `#ffac45`
After: `#F05138`

## Checklist:
- [x] **I am changing the color associated with a language**
  - [x] I have obtained agreement from the wider language community on this color change. (working on it)
    - [Swift Forums Topic](https://forums.swift.org/t/update-swift-language-color-on-github-to-match-the-official-swift-logo/49113)
    - [Swift Logo Resources](https://developer.apple.com/swift/resources/)
    - [Swift Logo Guidelines (download link)](https://developer.apple.com/swift/downloads/swift-logo.zip)
    - [Swift Logo Guidelines.pdf](https://github.com/github/linguist/files/6580852/Swift.Logo.Guidelines.pdf)

### CODE REVIEW

**Comment by lildude** [comment]
🤔  this didn't appear to be getting much community support

**Comment by eneko** [comment]
Hi @lildude, unfortunately, not many hearts or thumbs up, agreed. But I haven't heard of anyone rejecting the change either.

I'll see if I can promote the change a bit more on Twitter and the forums, thank you.

**Comment by Trzyipolkostkicukru** [comment]
14 hearts isn't a tiny amount of hearts. Review for structured concurrency proposal received 19 hearts, and it's arguably the most exciting change to swift ever. 

The lack of comments is there because there's not much to say other than "+1" which is explicitly discouraged

**Comment by eneko** [comment]
@lildude seems like there is enough support now?

**Comment by lildude** [comment]
If you're confident about it and happy to field any complaints for the change, if there are any, I'm happy for it to be merged.

**Comment by lildude** [comment]
Gonna merge this now. If there are any objections with the colour choice, please discuss this on the forum topic referenced in the OP.

**Pull request merged**
