### PR TITLE
Add REXX.

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
Fixes and supercedes #3110.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
@idrougge I had to remove syntax highlighting, because http://github.com/mblocker/rexx-sublime/ doesn't have a license.

**Comment by arfon** [comment]
👍 looks good to me.

**Comment by idrougge** [comment]
@larsbrinkhoff @arfon Is this supposed to work now or must it be further integrated in Github's backend?

**Comment by Alhadis** [comment]
It'll take effect the next time there's a new release of Linguist, which usually happens every couple of weeks or so. =)

**Comment by larsbrinkhoff** [comment]
The Sublime grammar added a license.  In case someone wants to give it a stab.

**Comment by idrougge** [comment]
MIT licence, so that is compatible with Linguist, too.

**Pull request merged**
