### PR TITLE
Add support for DGLux5

### PR DESCRIPTION
**Pull request by kaendfinger**
This adds support for the file extensions used by [DGLux5](http://www.dglogik.com/dglux).

### CODE REVIEW

**Comment by pchaigno** [comment]
Please see the [requirements for adding a new language](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language). In particular, you'll need to link to search results on GitHub for each of these extensions.

**Comment by arfon** [comment]
@kaendfinger - please see @pchaigno's comments about the requirements for adding a new language.

**Comment by kaendfinger** [comment]
Thanks. If it's Ok, can we leave this pending in the meantime?

**Comment by pchaigno** [comment]
@kaendfinger Please reopen when the DGLux5 reaches the required numbers ([`.dg5`](https://github.com/search?utf8=%E2%9C%93&q=extension%3Adg5+NOT+fkfdkghdkgjfk) and [`.df5`](https://github.com/search?utf8=%E2%9C%93&q=extension%3Adf5+NOT+fkfdkghdkgjfk&type=Code&ref=searchresults)). You may have to rebase or open a new pull request at that time, since Linguist evolves pretty fast ;)

**Pull request closed without merging**
