### PR TITLE
Replace Batchfile grammar and cleanup submodule list

### PR DESCRIPTION
**Pull request by Alhadis**
After starting [work on this](https://github.com/github/linguist/issues/3186#issuecomment-244612496), I noticed some oddities in the grammar/submodule lists:

* There're two grammars that were accidentally commited to this repository after they were partially removed in favour of other grammars:
	* [`less.tmbundle`](https://github.com/github/linguist/tree/master/vendor/grammars/less.tmbundle)
	* [`Sublime-Inform`](https://github.com/github/linguist/tree/master/vendor/grammars/Sublime-Inform)

	<br/>Evidently, the submodules were deregistered without their corresponding contents removed from the working tree. So they were erroneously included in the next commit.

* Batchfile highlighting is provided by an [abandoned bundle](https://github.com/ericzou/ebundles) of grammars that hasn't been updated in 8 years. The grammar is buggy and unmaintained, and has [highlighting issues](https://github.com/github/linguist/issues/2748) that'll never be noticed by the author. I've found a [fresh, healthy replacement](https://github.com/mmims/language-batchfile) that [fixes the issues](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgithub.com%2Fmmims%2Flanguage-batchfile%2Fblob%2Fmaster%2Fgrammars%2Fbatchfile.cson&grammar_text=&code_source=from-text&code_url=&code=%40echo+off%0D%0Arem+this+text+should+be+green%0D%0Aecho+hello+world) previously reported.

Other than the egregious cases, I did some assorted tidy-up that would've been too trivial to warrant a separate pull request.

### CODE REVIEW

**Comment by Alhadis** [comment]
**NB:** You'll probably want to squash-merge these. @pchaigno, don't forget. =)

**Comment by pchaigno** [comment]
LGTM

> NB: You'll probably want to squash-merge these. @pchaigno, don't forget. =)

I think we should try to keep this pull request into at least a few separate commits (you introduce several independent changes). You could use `git rebase -i master` to squash:
- the three first commits and the last one
- 4c86a76 and ea000a8

You should have three commits after that.

**Comment by Alhadis** [comment]
Done. =)

**Comment by Alhadis** [comment]
FYI, I left those commits separate in case I had to roll some of 'em back... I wondered if what I was doing was too over-the-top or diff-noisy.

**Comment by pchaigno** [comment]
@arfon This looks ready to me.

**Pull request merged**
