### PR TITLE
Added support for Linux .desktop and .emacs.desktop files

### PR DESCRIPTION
**Pull request by Mailaender**
http://standards.freedesktop.org/desktop-entry-spec/latest/

### CODE REVIEW

**Comment by Mailaender** [comment]
Rebased and added support for Emacs desktop files as suggested.

**Comment by Mailaender** [comment]
Travis noped. I don't have an example. Will keep this to FreeDesktop standard adhering files.

**Comment by larsbrinkhoff** [comment]
Thanks for the effort to include Emacs in your PR.  The problem with multiple file extension segments seems fixed now.  Could you please try again?

(Speaking only as an individual; I'm not part of GitHub staff.)

**Comment by Mailaender** [comment]
I need an example file. Can you provide one?

**Comment by larsbrinkhoff** [comment]
Ok, hang on.

**Comment by larsbrinkhoff** [comment]
Or rather, I made one myself:
http://lars.nocrew.org/tmp/.emacs.desktop

**Comment by Mailaender** [comment]
Finally got it to work.

**Comment by pchaigno** [comment]
I'm surprised that

**Comment by pchaigno** [comment]
I'm surprised that a grammar different fro `source.ini` is needed. Are the specifications really different?

**Comment by Mailaender** [comment]
That is what I tested at first, but the `;` is a way to comment out and not a separation char for `INI`: [example](https://lightshow.githubapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Ftextmate%2Fini.tmbundle%2F7d8c7b5544c48069a246fd2f43e965f06d03d3da%2FSyntaxes%2FIni.plist&grammar_text=%3C%3Fxml+version%3D%221.0%22+encoding%3D%22UTF-8%22%3F%3E%0D%0A%3C%21DOCTYPE+plist+PUBLIC+%22-%2F%2FApple%2F%2FDTD+PLIST+1.0%2F%2FEN%22+%22http%3A%2F%2Fwww.apple.com%2FDTDs%2FPropertyList-1.0.dtd%22%3E%0D%0A%3Cplist+version%3D%221.0%22%3E%0D%0A%3Cdict%3E%0D%0A%09%3Ckey%3EfileTypes%3C%2Fkey%3E%0D%0A%09%3Carray%3E%0D%0A%09%09%3Cstring%3Edesktop%3C%2Fstring%3E%0D%0A%09%3C%2Farray%3E%0D%0A%09%3Ckey%3EkeyEquivalent%3C%2Fkey%3E%0D%0A%09%3Cstring%3E%5E~I%3C%2Fstring%3E%0D%0A%09%3Ckey%3Ename%3C%2Fkey%3E%0D%0A%09%3Cstring%3Edesktop%3C%2Fstring%3E%0D%0A%09%3Ckey%3Epatterns%3C%2Fkey%3E%0D%0A%09%3Carray%3E%0D%0A%09%09%3Cdict%3E%0D%0A%09%09%09%3Ckey%3Ebegin%3C%2Fkey%3E%0D%0A%09%09%09%3Cstring%3E%28%5E%5B+%5Ct%5D%2B%29%3F%28%3F%3D%23%29%3C%2Fstring%3E%0D%0A%09%09%09%3Ckey%3EbeginCaptures%3C%2Fkey%3E%0D%0A%09%09%09%3Cdict%3E%0D%0A%09%09%09%09%3Ckey%3E1%3C%2Fkey%3E%0D%0A%09%09%09%09%3Cdict%3E%0D%0A%09%09%09%09%09%3Ckey%3Ename%3C%2Fkey%3E%0D%0A%09%09%09%09%09%3Cstring%3Epunctuation.whitespace.comment.leading.ini%3C%2Fstring%3E%0D%0A%09%09%09%09%3C%2Fdict%3E%0D%0A%09%09%09%3C%2Fdict%3E%0D%0A%09%09%09%3Ckey%3Eend%3C%2Fkey%3E%0D%0A%09%09%09%3Cstring%3E%28%3F%21%5CG%29%3C%2Fstring%3E%0D%0A%09%09%09%3Ckey%3Epatterns%3C%2Fkey%3E%0D%0A%09%09%09%3Carray%3E%0D%0A%09%09%09%09%3Cdict%3E%0D%0A%09%09%09%09%09%3Ckey%3Ebegin%3C%2Fkey%3E%0D%0A%09%09%09%09%09%3Cstring%3E%23%3C%2Fstring%3E%0D%0A%09%09%09%09%09%3Ckey%3EbeginCaptures%3C%2Fkey%3E%0D%0A%09%09%09%09%09%3Cdict%3E%0D%0A%09%09%09%09%09%09%3Ckey%3E0%3C%2Fkey%3E%0D%0A%09%09%09%09%09%09%3Cdict%3E%0D%0A%09%09%09%09%09%09%09%3Ckey%3Ename%3C%2Fkey%3E%0D%0A%09%09%09%09%09%09%09%3Cstring%3Epunctuation.definition.comment.ini%3C%2Fstring%3E%0D%0A%09%09%09%09%09%09%3C%2Fdict%3E%0D%0A%09%09%09%09%09%3C%2Fdict%3E%0D%0A%09%09%09%09%09%3Ckey%3Eend%3C%2Fkey%3E%0D%0A%09%09%09%09%09%3Cstring%3E%5Cn%3C%2Fstring%3E%0D%0A%09%09%09%09%09%3Ckey%3Ename%3C%2Fkey%3E%0D%0A%09%09%09%09%09%3Cstring%3Ecomment.line.number-sign.ini%3C%2Fstring%3E%0D%0A%09%09%09%09%3C%2Fdict%3E%0D%0A%09%09%09%3C%2Farray%3E%0D%0A%09%09%3C%2Fdict%3E%0D%0A%09%09%3Cdict%3E%0D%0A%09%09%09%3Ckey%3Ecaptures%3C%2Fkey%3E%0D%0A%09%09%09%3Cdict%3E%0D%0A%09%09%09%09%3Ckey%3E1%3C%2Fkey%3E%0D%0A%09%09%09%09%3Cdict%3E%0D%0A%09%09%09%09%09%3Ckey%3Ename%3C%2Fkey%3E%0D%0A%09%09%09%09%09%3Cstring%3Ekeyword.other.defdesktoption.desktop%3C%2Fstring%3E%0D%0A%09%09%09%09%3C%2Fdict%3E%0D%0A%09%09%09%09%3Ckey%3E2%3C%2Fkey%3E%0D%0A%09%09%09%09%3Cdict%3E%0D%0A%09%09%09%09%09%3Ckey%3Ename%3C%2Fkey%3E%0D%0A%09%09%09%09%09%3Cstring%3Epunctuation.separator.key-value.desktop%3C%2Fstring%3E%0D%0A%09%09%09%09%3C%2Fdict%3E%0D%0A%09%09%09%3C%2Fdict%3E%0D%0A%09%09%09%3Ckey%3Ematch%3C%2Fkey%3E%0D%0A%09%09%09%3Cstring%3E%5Cb%28%5Ba-zA-Z0-9_.-%5D%2B%29%5Cb%5Cs*%28%3D%29%3C%2Fstring%3E%0D%0A%09%09%3C%2Fdict%3E%0D%0A%09%09%3Cdict%3E%0D%0A%09%09%09%3Ckey%3Ecaptures%3C%2Fkey%3E%0D%0A%09%09%09%3Cdict%3E%0D%0A%09%09%09%09%3Ckey%3E1%3C%2Fkey%3E%0D%0A%09%09%09%09%3Cdict%3E%0D%0A%09%09%09%09%09%3Ckey%3Ename%3C%2Fkey%3E%0D%0A%09%09%09%09%09%3Cstring%3Epunctuation.defdesktoption.entity.desktop%3C%2Fstring%3E%0D%0A%09%09%09%09%3C%2Fdict%3E%0D%0A%09%09%09%09%3Ckey%3E3%3C%2Fkey%3E%0D%0A%09%09%09%09%3Cdict%3E%0D%0A%09%09%09%09%09%3Ckey%3Ename%3C%2Fkey%3E%0D%0A%09%09%09%09%09%3Cstring%3Epunctuation.defdesktoption.entity.desktop%3C%2Fstring%3E%0D%0A%09%09%09%09%3C%2Fdict%3E%0D%0A%09%09%09%3C%2Fdict%3E%0D%0A%09%09%09%3Ckey%3Ematch%3C%2Fkey%3E%0D%0A%09%09%09%3Cstring%3E%5E%28%5C%5B%29%28.*%3F%29%28%5C%5D%29%3C%2Fstring%3E%0D%0A%09%09%09%3Ckey%3Ename%3C%2Fkey%3E%0D%0A%09%09%09%3Cstring%3Eentity.name.section.group-title.desktop%3C%2Fstring%3E%0D%0A%09%09%3C%2Fdict%3E%0D%0A%09%09%3Cdict%3E%0D%0A%09%09%09%3Ckey%3Ebegin%3C%2Fkey%3E%0D%0A%09%09%09%3Cstring%3E%27%3C%2Fstring%3E%0D%0A%09%09%09%3Ckey%3EbeginCaptures%3C%2Fkey%3E%0D%0A%09%09%09%3Cdict%3E%0D%0A%09%09%09%09%3Ckey%3E0%3C%2Fkey%3E%0D%0A%09%09%09%09%3Cdict%3E%0D%0A%09%09%09%09%09%3Ckey%3Ename%3C%2Fkey%3E%0D%0A%09%09%09%09%09%3Cstring%3Epunctuation.defdesktoption.string.begin.desktop%3C%2Fstring%3E%0D%0A%09%09%09%09%3C%2Fdict%3E%0D%0A%09%09%09%3C%2Fdict%3E%0D%0A%09%09%09%3Ckey%3Eend%3C%2Fkey%3E%0D%0A%09%09%09%3Cstring%3E%27%3C%2Fstring%3E%0D%0A%09%09%09%3Ckey%3EendCaptures%3C%2Fkey%3E%0D%0A%09%09%09%3Cdict%3E%0D%0A%09%09%09%09%3Ckey%3E0%3C%2Fkey%3E%0D%0A%09%09%09%09%3Cdict%3E%0D%0A%09%09%09%09%09%3Ckey%3Ename%3C%2Fkey%3E%0D%0A%09%09%09%09%09%3Cstring%3Epunctuation.defdesktoption.string.end.desktop%3C%2Fstring%3E%0D%0A%09%09%09%09%3C%2Fdict%3E%0D%0A%09%09%09%3C%2Fdict%3E%0D%0A%09%09%09%3Ckey%3Ename%3C%2Fkey%3E%0D%0A%09%09%09%3Cstring%3Estring.quoted.single.desktop%3C%2Fstring%3E%0D%0A%09%09%09%3Ckey%3Epatterns%3C%2Fkey%3E%0D%0A%09%09%09%3Carray%3E%0D%0A%09%09%09%09%3Cdict%3E%0D%0A%09%09%09%09%09%3Ckey%3Ematch%3C%2Fkey%3E%0D%0A%09%09%09%09%09%3Cstring%3E%5C%5C.%3C%2Fstring%3E%0D%0A%09%09%09%09%09%3Ckey%3Ename%3C%2Fkey%3E%0D%0A%09%09%09%09%09%3Cstring%3Econstant.character.escape.desktop%3C%2Fstring%3E%0D%0A%09%09%09%09%3C%2Fdict%3E%0D%0A%09%09%09%3C%2Farray%3E%0D%0A%09%09%3C%2Fdict%3E%0D%0A%09%09%3Cdict%3E%0D%0A%09%09%09%3Ckey%3Ebegin%3C%2Fkey%3E%0D%0A%09%09%09%3Cstring%3E%22%3C%2Fstring%3E%0D%0A%09%09%09%3Ckey%3EbeginCaptures%3C%2Fkey%3E%0D%0A%09%09%09%3Cdict%3E%0D%0A%09%09%09%09%3Ckey%3E0%3C%2Fkey%3E%0D%0A%09%09%09%09%3Cdict%3E%0D%0A%09%09%09%09%09%3Ckey%3Ename%3C%2Fkey%3E%0D%0A%09%09%09%09%09%3Cstring%3Epunctuation.defdesktoption.string.begin.desktop%3C%2Fstring%3E%0D%0A%09%09%09%09%3C%2Fdict%3E%0D%0A%09%09%09%3C%2Fdict%3E%0D%0A%09%09%09%3Ckey%3Eend%3C%2Fkey%3E%0D%0A%09%09%09%3Cstring%3E%22%3C%2Fstring%3E%0D%0A%09%09%09%3Ckey%3EendCaptures%3C%2Fkey%3E%0D%0A%09%09%09%3Cdict%3E%0D%0A%09%09%09%09%3Ckey%3E0%3C%2Fkey%3E%0D%0A%09%09%09%09%3Cdict%3E%0D%0A%09%09%09%09%09%3Ckey%3Ename%3C%2Fkey%3E%0D%0A%09%09%09%09%09%3Cstring%3Epunctuation.defdesktoption.string.end.desktop%3C%2Fstring%3E%0D%0A%09%09%09%09%3C%2Fdict%3E%0D%0A%09%09%09%3C%2Fdict%3E%0D%0A%09%09%09%3Ckey%3Ename%3C%2Fkey%3E%0D%0A%09%09%09%3Cstring%3Estring.quoted.double.desktop%3C%2Fstring%3E%0D%0A%09%09%3C%2Fdict%3E%0D%0A%09%3C%2Farray%3E%0D%0A%09%3Ckey%3EscopeName%3C%2Fkey%3E%0D%0A%09%3Cstring%3Esource.desktop%3C%2Fstring%3E%0D%0A%09%3Ckey%3Euuid%3C%2Fkey%3E%0D%0A%09%3Cstring%3E77DC23B6-8A90-11D9-BAA4-000A9584EC8C%3C%2Fstring%3E%0D%0A%3C%2Fdict%3E%0D%0A%3C%2Fplist%3E&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2FMailaender%2Flinguist%2Fdot-desktop-files%2Fsamples%2Fdesktop%2Fexample.desktop&code=)

**Comment by Mailaender** [comment]
The specifications sharing some syntactic elements may be just coincidental. `INI` vs `.desktop` is very much Windows vs Linux.

**Comment by pchaigno** [comment]
I see. Thanks for the explanation :+1:

**Comment by Mailaender** [comment]
Removed the `.emacs.desktop` file again. After all it seems to be unused here on GitHub.

**Comment by Mailaender** [comment]
And added it again to please the :church: of Emacs.

**Comment by pchaigno** [comment]
@Mailaender I was able to find [more than 180,000 of them](https://github.com/search?p=1&q=extension%3Adesktop+filename%3A.emacs.desktop+desktop&ref=searchresults&type=Code&utf8=%E2%9C%93) so I think it's a good thing you added `.emacs.desktop` ;)

**Comment by Mailaender** [comment]
Yep, searched the wrong way without the `filetype:` prefix.

**Comment by arfon** [comment]
:+1:

**Pull request merged**
