### PR TITLE
Remove last mentions of lexer

### PR DESCRIPTION
**Pull request by pchaigno**
This pull request removes the last mentions of `lexer` in `language.rb` and `languages.yml` and updates the comments.

### CODE REVIEW

**Comment by arfon** [comment]
/ cc @aroben

**Comment by aroben** [comment]
I guess this will require a major version bump, which will give us a chance to remove all the deprecated methods in language.rb too.

The changes here all look good. :+1:

**Comment by pchaigno** [comment]
I updated the PR to remove a mention of `lexer` introduced in #1523 for GAP.

**Comment by aroben** [comment]
Thanks @pchaigno!

**Pull request merged**
