### PR TITLE
Add language support for Hoon

### PR DESCRIPTION
**Pull request by seanptmaher**
## Description

This pull request adds support for Hoon, the purely functional language in which is written [Urbit](https://github.com/urbit/urbit).

## Checklist:

- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?q=extension%3Ahoon+hoon&type=Repositories
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - https://github.com/urbit/urbit/blob/master/pkg/arvo/app/acme.hoon
      - https://github.com/urbit/urbit/blob/master/pkg/arvo/app/clock.hoon
      - https://github.com/urbit/urbit/blob/master/pkg/arvo/app/hood.hoon
      - https://github.com/urbit/urbit/blob/master/pkg/arvo/app/chat-view.hoon
    - Sample license(s):
      - mit
  
  - [x] I have included a syntax highlighting grammar: https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fmahirvaluj%2Fhoon-hl%2Fmaster%2FSyntaxes%2Fhoon.tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Furbit%2Furbit%2Fmaster%2Fpkg%2Farvo%2Fapp%2Facme.hoon&code=
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension. (N/A)

### CODE REVIEW

**Comment by lildude** [comment]
The use of the `.hoon` extension doesn't appear to be popular enough for inclusion just yet with my tally coming at only 75 unique user/repo combinations.

**Comment by seanptmaher** [comment]
That... is actually true, I miscounted the last time that I did the searching. Guess the PR will be ready if it's popular enough in the future. 

Closing.

**Comment by seanptmaher** [comment]
Hello, 

Sorry to open this again, but I was reminded when looking at one of the repositories I was looking at earlier:
https://github.com/urbit/urbit/network/members

This counts 220 unique user/repo combinations for this one repository, not counting any other repositories.

The problem with searching for hoon files is that hoon does not use any keywords, the language is composed entirely of sets of two ascii glyphs. @lildude Change anything on your end?

**Comment by lildude** [comment]
> The problem with searching for hoon files is that hoon does not use any keywords, the language is composed entirely of sets of two ascii glyphs. @lildude Change anything on your end?

Unfortunately not. We primarily rely upon the popularity of the extension and in this case `.hoon` barely [tops 1000 files](https://github.com/search?q=extension%3Ahoon+NOT+nothack&type=code), regardless or actual language, spread across too few unique user/repos.  We don't count forks, which your link is pointing too, as that's not representative of the adoption of a language, but rather the popularity of a single repository. 

You can use [Harvester](https://github.com/Alhadis/Harvester) yourself to keep a tally of usage.

**Pull request closed without merging**
