### PR TITLE
add support for XPages

### PR DESCRIPTION
**Pull request by edm00se**
Adding [XPages](http://stackoverflow.com/tags/xpages/info) language( and XSP markup for the XPages runtime). Per [CONTRIBUTING.md](https://github.com/github/linguist/blob/master/CONTRIBUTING.md):

1. added entry to languages.yml
2. no public/licensed grammar definition, so not added
3. multiple samples from multiple authors and projects added to _samples/_, primarily within _.xsp_ extension files (and metadata and config files similarly name-spaced)
4. referencing [this GitHub search result](https://github.com/search?utf8=%E2%9C%93&q=extension%3Axsp+ibm.com%2Fxsp%2Fcore&type=Code&ref=searchresults) with 4,815 code results as of this PR (screen shot below) for 'in-the-wild' use on GH

<br />
screen shot 2015-06-04 at 10 24 07 pm

### CODE REVIEW

**Comment by edm00se** [comment]
I wasn't aware of the need to [set any environment variables](https://travis-ci.org/github/linguist/builds/65512854) for the Travis CI instance.

**Comment by pchaigno** [comment]
You don't need to set any environment variables normally. You have [two errors](https://travis-ci.org/github/linguist/jobs/65512858#L1507-L1516):
- file extensions need to be sorted in `languages.yml` (except for the first one)
- you need to set the `tm_scope` to `none` explicitly

**Comment by pchaigno** [comment]
Also, do you know what [these files](https://github.com/search?p=4&q=extension%3Axsp+code&ref=searchresults&type=Code&utf8=%E2%9C%93) are? With your pull request they would be detected as XPages :/

**Comment by edm00se** [comment]
Ah. I'll make adjustments accordingly both to languages.yml and the GH search.

Thank you.

**Comment by edm00se** [comment]
I made the changes to the languages.yml file, working on improving the search. It seems I can get a good set of results of _code_ as opposed to repository, which gives me more than I want.

**Comment by edm00se** [comment]
I think I'm at the limit of my GH advanced searching abilities. For repositories, I was able to come up with [this search](https://github.com/search?utf8=%E2%9C%93&q=xpages+in%3Areadme%2Cname%2Cdescription&type=Repositories&ref=searchresults), which isn't keying off of extensions, but reflects 140+ repos and 27k+ Code elements.

If the search is to just validate a certain popularity of the language, I think we have that.

**Comment by edm00se** [comment]
@pchaigno After looking at [another, completed PR's searches](https://github.com/github/linguist/pull/2388), I'm using a page from their PR for a breakdown by extension. This ought to be granular enough.

[.xsp](https://github.com/search?utf8=%E2%9C%93&q=extension%3Axsp+xp%3Aview&type=Code&ref=searchresults}
[.xsp-config](https://github.com/search?q=extension%3Axsp-config+ibm.com%2Fxsp&ref=searchresults&type=Code&utf8=%E2%9C%93)
[~~.xsp~~.metadata](https://github.com/search?utf8=%E2%9C%93&q=extension%3Ametadata+lotus.com%2Fdxl&type=Code&ref=searchresults)
[.form](https://github.com/search?utf8=%E2%9C%93&q=extension%3Aform+lotus.com%2Fdxl&type=Code&ref=searchresults)
[.view](https://github.com/search?utf8=%E2%9C%93&q=extension%3Aview+lotus.com%2Fdxl&type=Code&ref=searchresults)

**Comment by edm00se** [comment]
So, seeing how I've heard nothing further from @pchaigno, if anyone happens to know how I can filter the PR to be a bit more selective without a dictionary file I don't have, I would appreciate it. I think there's a viable PR here, it just needs to filter out another format or two that uses the same _.xsp_ file extension.

**Comment by pchaigno** [comment]
Sorry about this. I'm having very busy weeks lately :/

So I think have enough in-the-wild examples of XPages for each extension :+1: 
The issue now is that we'll have to identify the conflicting languages and maybe add support for them in Linguist. If we don't they will be recognized as XPages.

[`.xsp.metadata`](https://github.com/search?utf8=%E2%9C%93&q=extension%3Ametadata+filename%3Axsp&type=Code&ref=searchresults) and `.xsp-config` are very specific and I couldn't find any conflicting language. In contrast, `.xsp`, `.form` and `.view` have conflicting languages.

Unsurprisingly, [`.form` and `.view` are used by many other languages](https://github.com/search?utf8=%E2%9C%93&q=extension%3Aform+NOT+xml&type=Code&ref=searchresults) (JSON, HTML, PHP, etc.). I'm not sure it's a good idea to add them now. We may have, in the future, an option not-a-language for our classifier, and it could solve this issue.

@hoelzro I know you helped us before for Perl-specific issues. Would you happen to know what [these files](https://github.com/search?p=4&q=extension%3Axsp+code&ref=searchresults&type=Code&utf8=%E2%9C%93) are? It looks like they have something to do with Perl...

**Comment by edm00se** [comment]
No worries, I guess I'm just antsy. I totally understand the being busy
side of things.

I guess I had been expecting unique file extensions, which aren't the case.
My update w/ the by-extension examples should give some specifics as to
required inclusions in the XPages specific files. I'm not sure what further
I can do to delimit the files by content, though I know what are required
per-file extension (see mentioned by extension links). I'm fully willing to
learn and adjust my PR as needed, so if anyone has recommendations on that
from, I'd welcome it.

**Comment by arfon** [comment]
> .xsp, .form and .view have conflicting languages.

I agree with @pchaigno that it might be more trouble than it's worth to add these right now. @edm00se - what do you think about updating this Pull Request to only include `.xsp.metadata` and `.xsp-config` and then you can use the [Linguist Overrides](https://github.com/github/linguist#overrides) to manually set the language for `.xsp`, .`form` and `.view` in your repositories?

Unfortunately our classifier isn't sophisticated enough to return a "don't know" answer for a file so if we include `.form` etc at this point we're almost guaranteed to introduce issues for other community members not using XPages.

**Comment by edm00se** [comment]
@arfon I suppose this has some certain merit, as the `.xsp.metadata` and `.xsp-config` files will usually accompany the other files and should achieve what I'm looking for.

If I understand the Linguist Overrides correctly, then I would be able to correctly identify by adding a few lines in a `.gitattributes` file, specifying the file extensions and how to recognize them as project type. As for the syntax highlighting, I don't believe they would easily be added to the source files, as it wouldn't parse correctly in the IDE; would that be able to be set in the project, outside the source files?

**Comment by edm00se** [comment]
I've updated my Pull Request accordingly (removed the `.form`, `.view`, and `.xsp` files and removed the related samples). I also have specified what I believe [should be the correct Linguist Override for a given application of mine with the XPages runtime](https://github.com/edm00se/AnAppOfIceAndFire/blob/master/.gitattributes).

If anyone has any references on syntax highlighting overrides kept outside the main file, I would appreciate it.

**Comment by edm00se** [comment]
@pchaigno, @arfon, how do things look now to either/both of you?

**Comment by arfon** [comment]
Looks good. Thanks @edm00se!

Also, [this config](https://github.com/edm00se/AnAppOfIceAndFire/blob/737a623069bea3abe40d706e1a279612f29e8a36/.gitattributes) will work once this change is live in GitHub.

**Comment by arfon** [comment]
I plan to cut a new gem this week sometime which will include this change.

**Comment by edm00se** [comment]
Excellent news. Thank you.

**Pull request merged**
