### PR TITLE
Add support for Reason

### PR DESCRIPTION
**Pull request by freebroccolo**
This PR adds support for the Reason language using the official grammar from [facebook/reason](https://github.com/facebook/reason/blob/master/editorSupport/language-reason/grammars/reason.json).

Samples taken from

* [JSX.re](https://github.com/facebook/reason/blob/master/formatTest/typeCheckedTests/expected_output/jsx.re)
* [Layout.re](https://github.com/jordwalke/ReLayout/blob/master/src/Layout.re)
* [Machine.re](https://github.com/freebroccolo/yggdrasil/blob/master/src/lib/Yggdrasil/Machine.re)
* [SuperMerlin.re](https://github.com/facebook/reason/blob/master/editorSupport/atom-reason/src/SuperMerlin.re)
* [Syntax.re](https://github.com/facebook/reason/blob/c3c0579a8aad073c9374655327abaa764a543868/formatTest/unit_tests/expected_output/syntax.re)

@jordwalke @chenglou can you please take a look at this and let me know if there are any changes you would like to make?

### CODE REVIEW

**Comment by chenglou** [comment]
Looks good from Reason's side. I don't know too much about linguist though.

**Comment by freebroccolo** [comment]
I've switched the ace and codemirror settings to rust at the suggestion of @jordwalke since that should handle reason syntax better than treating it like ocaml.

**Comment by Alhadis** [comment]
Hey @freebroccolo,

Reason was [proposed quite recently](https://github.com/github/linguist/pull/3332), where another submitter mentioned that the language was a variant of OCaml, and could even be considered as such.

Having said that, I believe this needs to be added to Reason's entry in `languages.yml`:

```yml
  - group: OCaml
```

The samples look okay; I see Facebook's licensed Reason under the BSD-3-Clause, with the other sample being Apache-2 licensed.

**Comment by Alhadis** [comment]
I'm not sure why the build is failing...  @pchaigno, do you know much about [this](https://travis-ci.org/github/linguist/jobs/177157348#L1110)?

```
  1) Failure:
TestGrammars#test_whitelisted_submodules_dont_have_licenses [/home/travis/build/github/linguist/test/test_grammars.rb:136]:
The following whitelisted submodules have a license:
* vendor/grammars/ant.tmbundle
Please remove them from the project whitelist..
--- expected
+++ actual
@@ -1 +1 @@
-{}
+{"vendor/grammars/ant.tmbundle"=>"241e5ddbb4423d792216783e9f668bd670b026e4"}
```

I noticed you were the last one to [modify the whitelisted module test](https://github.com/github/linguist/blame/master/test/test_grammars.rb#L132-L137), and there's an [open PR](https://github.com/textmate/ant.tmbundle/pull/2) from you at the `ant.tmbundle` repository. I figure you'd know more about this than me.

FWIW, I can't reproduce this locally.

**Comment by brandonblack** [comment]
Hello @freebroccolo  👋   Thanks for the contribution.

If you can update your pull request with the latest from `master` it should resolve the Ant related issue in the failing build.

Once the build is ✅  we'll take another 👀  at this. Let us know when you're ready!

**Comment by freebroccolo** [comment]
@Alhadis @brandonblack thanks. Should be good to go now I think.

**Comment by Alhadis** [comment]
LGTM! 👍

**Comment by pchaigno** [comment]
[These](https://github.com/search?p=1&q=extension%3Are+include+define&ref=searchresults&type=Code&utf8=%E2%9C%93) don't look like Reason files... are they? If not, we'll need to identify the language and add it to Linguist.

**Comment by freebroccolo** [comment]
@pchaigno that is correct, most of those are not reason files.

**Comment by Alhadis** [comment]
[563 repositories by 516 users](https://raw.githubusercontent.com/Alhadis/Linguist-Silo/02e655108b5ca06f2340db2e8012d0a9d47cf74f/re-results.log). :S That's rather impossible to ignore..

**Comment by freebroccolo** [comment]
@Alhadis @pchaigno can you tell us how we should proceed with this? Thanks.

**Comment by chenglou** [comment]
These seem to be from `http://re2c.org/examples/example_01.html`? What are the possible heuristics we can use?

**Comment by Alhadis** [comment]
Sorry for the slow response, guys... didn't mean to keep you waiting.

Alright, here's what we should do. We include `.re` as a C++ extension, and [add a heuristic](https://github.com/github/linguist/blob/master/lib/linguist/heuristics.rb#L368-L382) for it:

```diff
diff --git a/lib/linguist/heuristics.rb b/lib/linguist/heuristics.rb
index 7216003f..257b6f9e 100644
--- a/lib/linguist/heuristics.rb
+++ b/lib/linguist/heuristics.rb
@@ -374,4 +374,10 @@ module Linguist
     end
 
+    disambiguate ".re" do |data|
+      if /^#\s*(?:define|include)\b|(?:\A|\s)\/\*!re2c\b/m.match(data)
+        Language["C++"]
+      end
+    end
+
     disambiguate ".rno" do |data|
       if /^\.!|^\.end lit(?:eral)?\b/i.match(data)
```

This asserts any `.re` file which contains `#include`, `#define` or `/*!re2c` is C++ source. Testing the heuristic on the [downloaded search results](https://github.com/Alhadis/Linguist-Silo/tree/re/files) yielded accurate results, though half the files had modelines which explicitly stated their languages. I doubt misclassification will be an issue here.

## Steps to be taken on your side
1. **Merge the latest changes from the master branch**
You'll need to resolve the conflicts in `.gitmodules`, as you can see.

2. **Ensure your local submodules are up-to-date**

3. **Add `.re` as a `C++` extension:**
```diff
@@ -507,6 +507,7 @@ C++:
   - ".inc"
   - ".inl"
   - ".ipp"
+  - ".re"
   - ".tcc"
   - ".tpp"
   language_id: 43
 C-ObjDump:
   type: data
   extensions:
```

4. **Add the following samples to `samples/C++/`:**
These are taken from the `re2c` project itself, which is released [to the public domain](http://re2c.org/about/about.html#license):
- [`bug1163046.--skeleton.re`](https://github.com/skvadrik/re2c/blob/master/re2c/test/bug1163046.--skeleton.re)
- [`cnokw.re`](https://github.com/skvadrik/re2c/blob/master/re2c/test/cnokw.re)
- [`cvsignore.re`](https://github.com/skvadrik/re2c/blob/master/re2c/test/cvsignore.re)
- [`simple.re`](https://github.com/skvadrik/re2c/blob/master/re2c/test/simple.re)

**Comment by freebroccolo** [comment]
@Alhadis Thanks. I have made the changes you suggested.

**Comment by chenglou** [comment]
Seems to still have conflicts?

**Comment by Alhadis** [comment]
Ah yeah, there was a release cut very recently (which involved the merging of several open pull requests).

Please try again.

**Comment by freebroccolo** [comment]
@Alhadis I have rebased the PR again. Can you please review? Thanks.

**Comment by Alhadis** [comment]
@brandonblack I think this is safe to merge.

**Comment by chenglou** [comment]
When will this go in? Merry late Christmas =)

**Comment by yunxing** [comment]
When will this appear on github? Happy new year!

**Comment by Alhadis** [comment]
Whose culture and calendar are we going by here? ;-) Happy new perennial cycle.

As for when to expect visible results on GitHub, that'd be when the next release of Linguist is cut. Exactly when that will be is known only to GitHub staff; so @brandonblack is the guy to issue a definitive answer.

I'm racing the next Linguist release against a [monolithic pull request](https://github.com/atom/language-css/pull/99) of mine that's taking ages to be reviewed... will be interesting to see which is first.

**Pull request merged**
