### PR TITLE
Extend vendor regex for /[Ee]xtern(als?)?/

### PR DESCRIPTION
**Pull request by ligfx**
Extends the vendor regex for `/extern(al)?/` to `/[Ee]xtern(als?)?/`

As used in projects such as [Dolphin](https://github.com/dolphin-emu/dolphin/tree/master/Externals).

## Checklist:
- [x] **I am adding new or changing current functionality**
  - [x] I have added or updated the tests for the new or changed functionality.

### CODE REVIEW

**Comment by Nixinova** [comment]
How about allowing "ext/" as a vendor folder as well? So `/Ee]xt(ern(als?)?)?/`

**Comment by ligfx** [comment]
> How about allowing "ext/" as a vendor folder as well? So `/[Ee]xt(ern(als?)?)?/`

Do you have an example of where that's used?

**Comment by Nixinova** [comment]
>Do you have an example of where that's used?

[Looks like lots of places](https://github.com/search?q=path%3Aext&type=Code), at a glance

**Comment by ligfx** [comment]
> > > How about allowing "ext/" as a vendor folder as well? So /[Ee]xt(ern(als?)?)?/
> >
> > Do you have an example of where that's used?
>
> Looks like lots of places, at a glance

Looks like Ruby uses `ext` as the standard directory for C extensions it will build as part of the project.

I'm going to keep this PR as-is just expanding the `extern(al)?` regex.

**Review by Alhadis — APPROVED** [review]

**Review by lildude — APPROVED** [review]

**Pull request merged**
