### PR TITLE
Add support for Wavefront OBJ/MTL files

### PR DESCRIPTION
**Pull request by Alhadis**
[Wavefront OBJ](https://en.wikipedia.org/wiki/Wavefront_.obj_file) is the closest thing the 3D world has to a Markdown: a venerable, nearly universally-supported format that's easy to write and parse (by both man and machine). This PR adds support for both `.obj` meshes and `.mtl` files, a complementary format for describing surface materials. The two formats are usually found bundled alongside each other.

Usage
-----
The extent of the format's usage on GitHub is hard to gauge. Searching for OBJ files yields nearly [1.5 million results](https://github.com/search?q=extension%3Aobj+NOT+nothack&type=Code), with many results consisting of binary/build files. I've corralled a list of unique repositories using the 3D format:

* [abeldella/JocsElectronics](https://github.com/abeldella/JocsElectronics/blob/02a36a7e2a0fc1357363a2884a68ffd67ef49afc/TJE_framework_2016/data/Bed.obj)
* [AdanBB/Project_Sapphire](https://github.com/AdanBB/Project_Sapphire/blob/0468f64b55a877aa8230f91e20c9382ae72c89d3/Assets/3D/Enemies/Boos/head.obj)
* [alexanderTex/belegUbungscodeCG](https://github.com/alexanderTex/belegUbungscodeCG/blob/b88d9d19a555109ee70aa5aaa1ec13ffb42d83a2/sogoAppOpenGL/sogoAppOpenGL/teapot.obj)
* [amecky/hex_minesweeper](https://github.com/amecky/hex_minesweeper/blob/e696f012cf8d2c7053be65013a838ec94bee0587/content/objects/ring.obj)
* [andresrcc/star-turpial](https://github.com/andresrcc/star-turpial/blob/d3cf8a0ecfbbf610ba6bbfadff32a40a7eefa07c/objetos/Feisar_Ship.obj)
* [anttisalonen/opengl-tests](https://github.com/anttisalonen/opengl-tests/blob/4178e8282a2362e3f19628548eb16be69274ae97/textured-cube.obj)
* [buttonsquared/towerdefence](https://github.com/buttonsquared/towerdefence/blob/0bbd1cbd73f07fea8fe9643efc1c40ad6f82fec8/towerdefence/Assets/AstarPathfindingProject/ExampleScenes/Example6_Navmesh/navmesh.obj)
* [Cal-El/HexPunk](https://github.com/Cal-El/HexPunk/blob/460c3702ee04e84206c744594beb1384f38f5d5e/UnityProject/Assets/Old%20Models/Room%202%20pressure%201.obj)
* [CollectiveTyranny/irrBullet](https://github.com/CollectiveTyranny/DMUX/blob/9f2c86408760beec64c047b6314cfd0bce7de88b/assets/chassis/el-camino-for-export.obj) (topkek @ [the commit message](https://github.com/CollectiveTyranny/DMUX/commit/9f2c86408760beec64c047b6314cfd0bce7de88b))
* [csepreghy/VR-Cinema-Website-with-React.js](https://github.com/csepreghy/VR-Cinema-Website-with-React.js/blob/e7d3f0d9b9d054c28b80ee734c59056a1b47115f/src/assets/models/grand-teatret.obj)
* [DhrubajitPC/capstone_prototype](https://github.com/DhrubajitPC/capstone_prototype/blob/c79c9f4f8aa13d1511aad658d14aa1809953b665/Assets/objects/Dining%20Kitchen.obj)
* [dweep123/graphics](https://github.com/dweep123/graphics/blob/84170f9bcfa540e9e857aafb561594c692ec6cba/submission/new/powergirl-hero156.obj)
* [electricFeel/BeatKeeperHRM](https://github.com/electricFeel/BeatKeeperHRM/blob/2c81efa525ccb5fd69594fc7f984d1da70529f4f/DataLogger/services/build/orange/Orange/OrangeWidgets/plot/primitives/sphere_hq.obj)
* [erlog/laughing-couscous](https://github.com/erlog/laughing-couscous/blob/42a54dc8ac1f737420614bcc3bae25098aacb1b3/objects/models/cube.obj)
* [Ethanthecrazy/CannonAide](https://github.com/Ethanthecrazy/CannonAide/blob/40dff6fefc764a53b8b0dcf24ebc88cbcaf4b018/resources/cube.obj)
* [Evilhexyon/Edze-v2](https://github.com/Evilhexyon/Edze-v2/blob/0ffb2f23b97217482b1ee31fd1678f6912fbbf0f/UnityProject/Assets/Art/Inside/Stair_Fence.obj)
* [EzraTan/Muffin-Warriors](https://github.com/EzraTan/Muffin-Warriors/blob/8ec2310763b3c05957384baed5c0c0cdd9c2e05c/ProjectFiles/Muffin%20Warriors/Assets/Art/3D%20models/lp%20cage.obj)
* [fabianin/As-aventuras-de-Lekinho](https://github.com/fabianin/As-aventuras-de-Lekinho/blob/2cdce2bd6081b4619df2bc54633c20a64cf8dca0/untitled.obj)
* [gentoomen/Ludum-Dare-22](https://github.com/gentoomen/Ludum-Dare-22/blob/afc1b5b949b0f3e6da7e7754e16512828f2620fc/resources/props/pencilpot.obj)
* [growingdever/guardian-of-yggdrasil](https://github.com/growingdever/guardian-of-yggdrasil/blob/28b598da349b7a5de1435175c683e305fe5d95cf/Assets/Droid%20Scout%20Ship/Droid_Scout_Ship.obj)
* [gudajan/Windsim](https://github.com/gudajan/Windsim/blob/6c0691065b26061075bfe307bb29d404414814c4/WindSim/fan4.obj)
* [hungnguyen94/ComputerGraphics](https://github.com/hungnguyen94/ComputerGraphics/blob/962bfbf5b04cc568dbb182d050288342da72eb11/CoffeeTable.obj)
* [imelendez/TheAmazeingRace](https://github.com/imelendez/TheAmazeingRace/blob/dd13ac8d8fa48a6e720e82f00d4e310f4dcf6e6f/models/blue1.obj)
* [IndieConstruction/EventHorizon_2016_404](https://github.com/IndieConstruction/EventHorizon_2016_404/blob/d3b53e2ff655aa671a1839541da36d2c383b6ce6/UnityProject/Assets/Project404/Inglobabili/Bottiglia.obj)
* [indyfind/Beat-Breakers](https://github.com/indyfind/Beat-Breakers/blob/773b7bf1b7613e1327f1107a0749c63a8dab006f/Beat%20Breakers%203D/Assets/Art/Models/eva_1.obj)
* [iwaken71/ActivityGame](https://github.com/iwaken71/ActivityGame/blob/254289d5f7689b637326d0c7bfeb6a5e56339409/Assets/Photon%20Unity%20Networking/Demos/DemoPickup/Assets/quad-mesh.obj)
* [Jolternauts/Jolternauts](https://github.com/Jolternauts/Jolternauts/blob/75d4b31499bc6d511fe8adb6448402f544e8a7e3/Assets/Models/Latest_Models/Station%20Parts/Corridor_Straight_Short.obj#L4)
* [Jonathan-Granier/Taluva](https://github.com/Jonathan-Granier/Taluva/blob/ee1249b6310fc7ab5eb8d04ee1b758264b8f6562/Taluva/Assets/OBJ/Tower.obj)
* [joshcutler/TheLand](https://github.com/joshcutler/TheLand/blob/aaea32d192da851b36b9f62320a456398c4f1eb5/assets/Models/Trees/tree.obj)
* [kirbyfr/Tomy](https://github.com/kirbyfr/Tomy/blob/40e209232fa047450e998fe3093d5911ea618fe1/Tomy/Assets/Resources/Objets/arrow03.obj)
* [kSkip/MereEngineDemo](https://github.com/kSkip/MereEngineDemo/blob/40a3da0e942d8fe54094027d2783c0b5e2c67a94/Data/Objects/Ground.obj)
* [LianeMakatura/Balancing_Act](https://github.com/LianeMakatura/Balancing_Act/blob/eccb687388ed5e0a035ea51bd6c3cc0b14264e5d/hierarchical_dolphin_test.obj)
* [Lyriix/colorDetectionCV](https://github.com/Lyriix/colorDetectionCV/blob/f7a03cdece00875550a428d000ae84e845a845ab/projet/data/cube.obj)
* [lwjglgamedev/lwjglbook](https://github.com/lwjglgamedev/lwjglbook/blob/fd8e5ddf1d5aefe9a5ec8a51f4235ad40c3eb925/chapter20/c20-p1/src/main/resources/models/quad.obj)
* [mandalorethx/SortDemo](https://github.com/mandalorethx/SortDemo/blob/0afb6cfa644b43eeef566858e61efc65be754e6c/RawAssets/Sphere.obj)
* [marso329/tsbk07](https://github.com/marso329/tsbk07/blob/b2fcd862214b8148b762dda5c67d62b2e6ef0781/projekt/resources/tests/%7B.obj)
* [mbroncano/swift-trace](https://github.com/mbroncano/swift-trace/blob/99badfff1d9968a9fcc17cd039de65201d45bac3/SwiftTraceWindow/bunny.obj)
* [mgottschlag/ShooterTestOld](https://github.com/mgottschlag/ShooterTestOld/blob/82e4fcffa49649c9c1176b9aa4eb6f29986d4d61/media/star.obj)
* [mikeschaekermann/qpt2a](https://github.com/mikeschaekermann/qpt2a/blob/213f3a18365207708bb4c927520aeb2217d82183/code/resources/models/attack.obj)
* [MinetestForFun/minercantile](https://github.com/MinetestForFun/minercantile/blob/ce3f17ca3507a105755106d782ae39b31d37ba40/models/minercantile_shop.obj)
* [Moises404/irl-3d](https://github.com/Moises404/irl-3d/blob/f196b8426082d200f2af27f0465c563daa382204/models/male02/male02.obj)
* [naufalkhalid/WordGame](https://github.com/naufalkhalid/WordGame/blob/fb41ca98d0fedf198551e27f5b15eecae1c436fe/Assets/Objects/Farmhouse%20OBJ.obj)
* [nebogeo/al-jazari2](https://github.com/nebogeo/al-jazari2/blob/0bd308ac9d35edf13b8325d863337f0619655de4/meshes/bot.obj)
* [noxo/jmonkey-engine-jogl-gles](https://github.com/noxo/jmonkey-engine-jogl-gles/blob/7175c2ebd7351278b9a0b47cc0cf74bbf0e91b6c/engine/test-data/Models/Teapot/Teapot.obj)
* [pabca/proyectoUnlam](https://github.com/pabca/proyectoUnlam/blob/dbfe3211e1650af334dc05a4cdb573ccf11c6450/aRSimpleNativeCars/src/main/assets/Data/models/Ferrari_Modena_Spider.obj)
* [pavelnedved/webglforfun](https://github.com/pavelnedved/webglforfun/blob/a7c5f9189b7cae3d73a1e12a0cba99e38698a8bf/teapotfun/teapot.obj)
* [pchernev/Zombayo](https://github.com/pchernev/Zombayo/blob/ce2a569cd22d6587a243e3376b0076ccda9ac65b/Assets/ExternalResources/Top%20Down%20Mobile/_TDM_Meshes/Lightshafts.obj)
* [PlatinumArts/PrincessRainbowface](https://github.com/PlatinumArts/PrincessRainbowface/blob/e6440110e079059434be1d05d03681b4b4a5311f/mods/portalgun/models/portalgun_button.obj)
* [pontusstjerna/ParaglideX](https://github.com/pontusstjerna/ParaglideX/blob/fe5a59b05e54e37d6a763cc7ef03d47e63ad49df/Blender/harness2.obj)
* [psy2/GraphicsTerm](https://github.com/psy2/GraphicsTerm/blob/128103f39900d7af1f19e0433dbb4337a36933e6/Mario.obj)
* [rachelwigell/AquiSim](https://github.com/rachelwigell/AquiSim/blob/5e99b967434def53b31bd4290b4158a803765596/graphics/guppy.obj)
* [redovic/Iterum_IM_DA_GALD](https://github.com/redovic/Iterum_IM_DA_GALD/blob/10dd1a2ba5683f81666b24944deda8d54c66d5a1/Assets/Models/Assets/tutorial_wall2_new.obj)
* [rein4ce/webcraft-engine](https://github.com/rein4ce/webcraft-engine/blob/8af6c9c50c40169e209066ce7b485505b4014782/models/tileset.obj)
* [RichardJCase/Swordf](https://github.com/RichardJCase/Swordf/blob/7d0aff14250d0e5dbb71e2bd725666eaa2463fa4/bin/objs/dog.obj)
* [risq/anamorph-unity](https://github.com/risq/anamorph-unity/blob/ab32405cdad38da43ecfeefff060d4fb23954a75/Assets/Models/Particles/cube-atom-ray_particle.obj)
* [Robzz/ter](https://github.com/Robzz/ter/blob/dca6aba8eb480d5f65fd7514e47c316ea8ea6568/assets/buddha_11k.obj)
* [sam6321/ICT371](https://github.com/sam6321/ICT371/blob/0b9a322f5834ff5e109feaa8a2015f8130cd330d/Assets/A%20Models%20-%20Textures/Kettle.obj)
* [sambthompson/spd](https://github.com/sambthompson/spd/blob/9e3a92d4edd44ef3fb057fd544e43fdd273abfb7/f15.obj)
* [samhuerzeler/RPGOpenGL](https://github.com/samhuerzeler/RPGOpenGL/blob/f7e597ee5653f6310e5ced77497d3aebd313118e/res/models/monkey.obj)
* [Samsung/GearVRf](https://github.com/Samsung/GearVRf/blob/11f3659351ad68b2f6218e60fc561ed4a9b06868/GVRf/Extensions/3DCursor/3DCursorLibrary/src/main/assets/cursor_sphere_default/cursor_sphere.obj)
* [sangh/LaserShow](https://github.com/sangh/LaserShow/blob/5882a8ea13b4f8db2b2d0a04247bd378412aa7a5/pyglet-hg/contrib/model/examples/rabbit.obj)
* [SerraPlo/JocsEnXarxa](https://github.com/SerraPlo/JocsEnXarxa/blob/fd500ba85c3b529b88fa2bf0f24cfc188f894ab7/assets/models/car/wheel.obj)
* [Skybladev2/TacticalRPG](https://github.com/Skybladev2/TacticalRPG/blob/e6504756b5485a28ff86d56d093ec849d9cf9eea/Assets/Codefarts%20Game/Grid%20Mapping/Resources/Codefarts.Unity/Source%20Meshes/2PolyPlane.obj)
* [syoyo/tinyobjloader](https://github.com/syoyo/tinyobjloader/blob/d6cd178d6a4c6f3082cf4731cf7d138f72eba53f/models/usemtl-issue-68.obj)
* [tdingsun/tdingsun.github.io](https://github.com/tdingsun/tdingsun.github.io/blob/b500881f9512cfef51010adad70bc51e3b0e47fd/tiger/laptopcharger.obj)
* [ThatZombieAlien/Laundry-World](https://github.com/ThatZombieAlien/Laundry-World/blob/a661b2b05dbb34e6d338c1f39217021fad9ea6af/Laundry%20World%20v.1/Assets/Tiled2Unity/Meshes/Villagemap.obj)
* [thepalebluedot/minimole-core](https://github.com/thepalebluedot/minimole-core/blob/194a7b6c746477fac9919be0d3d0e57a7e4a6949/examples/assets/room/room.obj)
* [tonyboyangie3/LegendsOfWar](https://github.com/tonyboyangie3/LegendsOfWar/blob/c5b066e6ff40afe7f24c12ce37c9bb961e71795b/Codebase/LegendsOfWar/Assets/oldAssets/objects/Rock6_LP.obj)
* [toyukan6/Offline](https://github.com/toyukan6/Offline/blob/183f0da574a8318620eda80fe4a5847c1b951a3b/Assets/240degrees/front.obj)
* [understreck/_](https://github.com/understreck/_/blob/5b690528f6301708513a66665d1d907a749c9c04/3d/primatives/home/home.obj)
* [vanstorm9/Yugioh-AR-Card-Mode](https://github.com/vanstorm9/Yugioh-AR-Card-Mode/blob/7ebba4c6dcdbb11c196a0f1f2e052d9c97483b6f/Assets/Models_Scripts/Models_Scripts/blue-eyes%20white%20dragon/Blue-Eyes%20White%20Dragon.obj)
* [VideoGameTeam/DAB-VideoGame](https://github.com/VideoGameTeam/DAB-VideoGame/blob/2d3a35e7fc44b3d513cfacf748d48e147b1e559e/Assets/Resources/Chameleon%20Medal/Chameleon%20Medal.obj)
* [vsingama/VirtualUMB](https://github.com/vsingama/VirtualUMB/blob/b381b59ecfd79c40f25280c2564b456c804c27d0/VirtualUMB/palm_tree.obj)
* [wienleung/bunnies](https://github.com/wienleung/bunnies/blob/4f06f79b9d0804ef4dc287e4bc5038925c9f22ba/res/rabbit/orig/rabbit_arm_high.obj)
* [wortelstoemp/BlackMesaResearch](https://github.com/wortelstoemp/BlackMesaResearch/blob/9e9f174b400dae61be0e85f8138ed335e261986c/data/meshes/sphere.obj)
* [xmaciek/starace](https://github.com/xmaciek/starace/blob/4863d87268cec11f5607fc721e6d86fa96aa01f6/models/a1.obj)
* [yanqinghuang/BehaviorDetection](https://github.com/yanqinghuang/BehaviorDetection/blob/054649a9042c674bccd56f604d3866fdba043260/ObjectTracking/Assets/3DTargetsCAD/CAD_rim_target/LineModel.obj)
* [ychding11/HelloWorld](https://github.com/ychding11/HelloWorld/blob/f38108adec1e7e0b4a764b08b69df3c6524517b5/misc/Path-Tracer/obj/dragon2.obj)
* [ZJUAdvancedCG2016FinalProject/ShapeDeformation](https://github.com/ZJUAdvancedCG2016FinalProject/ShapeDeformation/blob/c6e269b2a47cb555d2646fa90bd3314084e290f6/bunny.obj)
* [zsoxa/crosstown](https://github.com/zsoxa/crosstown/blob/3fa790507536aaed566c2af9a8d321711bb5e066/Assets/RoadTool/Example/Model/pb8420/pb8420.obj)
* [Zwiterrion/modelisation](https://github.com/Zwiterrion/modelisation/blob/0bddcfd312d27ff8b12e269af5461bf456cbabdd/DerivedData/Mod%C3%A9lisation/Build/Products/Debug/Base%20dorique.obj)

… and the list goes on.

Examples
--------
The sample files were ones I slapped together in 3DS Max earlier this afternoon. I kept them simple to avoid adding too much weight to the repository - OBJ files, like SVGs, can grow very large with too much detail.

Relevant
--------
I'm aware GitHub supports [3D models](https://github.com/blog/1465-stl-file-viewing), even going as far as [supporting geometry diffs](https://github.com/blog/1633-3d-file-diffs). However, this support is limited to STL files, which're mostly CAD-related. I understand if GitHub don't want to go too crazy with supporting so many different 3D formats, but if there's any format that deserves support in real-time previews, it's definitely OBJ.

I don't know who to ask or where to go to propose adding support for the format on the site. But I can tell you now, there'd be many users who'd appreciate it.

### CODE REVIEW

**Comment by Alhadis** [comment]
Conflicts fixed.

**Comment by Alhadis** [comment]
@arfon Any chance of getting this merged before the next release?

**Comment by arfon** [comment]
Superceded by #3034

**Comment by Alhadis** [comment]
I brought this on myself by not noticing ThomasWeiser's mistake and opting to instead make a dry-witted pun instead of actually helping the poor guy.

KARMA EXISTS, AND IT'S NOT JUST A TESTING FRAMEWORK.

**Comment by arfon** [comment]
> KARMA EXISTS, AND IT'S NOT JUST A TESTING FRAMEWORK.

Lol. Had to make a new PR to bring your branch up to date.

**Comment by Alhadis** [comment]
Yeah I know, haha. If I'd pointed out the mistake in `.gitmodules` and stuff, he might've fixed it before the merge and I might've had a chance to fix conflicts before you arrived.

Speaking of which, my fork's branches got totally mutilated when fixing the first bunch of conflicts, which is why I was getting anxious to put the poor thing out of its misery, hahaha.

**Pull request closed without merging**
