### PR TITLE
Revise pattern for Emacs modeline detection

### LINKED ISSUE #3018: Scheme misclassified as E
After putting

``` scheme
;;; -*- geiser-scheme-implementation: guile -*-
```

at the top of my file it is now being detected as "E".
The repository is https://github.com/Jonathan50/scheme-hashtable

### LINKED ISSUE #3226: Rails mime_type.rb considered as "E"?
Hey!

Why is [this file](https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/http/mime_type.rb) considered as "E"?

See the screenshots how I got this:

On the rails repo:
screen shot 2016-09-16 at 12 13 54

And by clicking the "E":
screen shot 2016-09-16 at 12 14 03

### PR DESCRIPTION
**Pull request by Alhadis**
This is a rewrite of the regex that handles Emacs modeline detection. The current one is a bit flaky, causing some files to be mistakenly classified. For instance, each of these files is misidentified as "E":

* [abbrev_defs](https://github.com/gorysko/emacs_conf/blob/d6e567c176b1409eec773b837c1d0ac5b98f1399/abbrev_defs)
* [Prot_PW2.tex](https://github.com/blackandcold/Phy-WS2013-Praktikum-1/blob/71b65d739a4a2a7eea97b398b796cf3e59aac976/Anfpra2/Prot_PW2.tex)
* [PW6_Prot.tex](https://github.com/blackandcold/Phy-WS2013-Praktikum-1/blob/71b65d739a4a2a7eea97b398b796cf3e59aac976/Anfpra6/PW6_Prot.tex)
* [mime_type.rb](https://github.com/seiya-koga/sample_app/blob/3da7ce7e115e02ba2fe32f6e994a6f37d1969492/workspace/CableChat/vendor/bundle/gems/actionpack-5.0.0.1/lib/action_dispatch/http/mime_type.rb)
* [test_rubyoptions.rb](https://github.com/lorenabento/shapado/blob/5fc0ba213df7b8a928fe05a38363de71b5579081/ruby-1.9.3-p362/test/ruby/test_rubyoptions.rb#L344)
* [parens.texi](https://github.com/zhoujd/zzemacs/blob/6402ed5178682533706180ee6367cdcdaec6022d/site-lisp/geiser/doc/parens.texi#L131)
* [zbx_multicheck](https://github.com/Farzy/zbx-multicheck/blob/7ee767d871550ec74f77eef4a6e32a94cdf6baa4/zbx_multicheck)
* [generator.lisp](https://github.com/vikram/lisplibraries/blob/105e3ef2d165275eb78f36f5090c9e2cdd0754dd/site/cl-python/core/generator.lisp)
* [redcarpet.rb](https://github.com/tekwiz/dionysus/blob/a90b13094178709b8c81b103e641c75c1baa96b5/lib/dionysus/redcarpet.rb)

It's worth noting that malformed modelines can still change a file's language in Emacs. Provided the `-*-` delimiters are intact, and the mode's name is decipherable, Emacs will set the language *and* complain about a malformed modeline.

# -*- foo-bar mode: ruby -*-

I took this into consideration when rewriting the pattern, sensing that not every user knows or cares if an Emacs modeline isn't being parsed correctly (so long as the correct highlighting is shown).

Closes #3018
Closes #3226

### CODE REVIEW

**Comment by Alhadis** [comment]
@arfon I could've added to #3197 (which hasn't been merged yet), but having a separate PR should make for cleaner reviewing and discussion.

/cc @tesch1, @pchaigno

**Comment by siegy22** [comment]
💚💪

**Comment by pchaigno** [comment]
Looks good to me :+1: 
Thank you @Alhadis!

**Comment by arfon** [comment]
👍 this looks good. Are the build failures from Licensee?

**Comment by Alhadis** [comment]
Yeah... :( I had to manually edit the confidence threshold in `vendor/gems/ruby/2.2.0/gems/licensee-8.4.0/lib/licensee.rb` to verify that the modeline tests passed.

**Comment by arfon** [comment]
Fingers-crossed we get that fixed up soon.

**Comment by arfon** [comment]
Superseded by #3237

**Comment by wikisity** [comment]
Looks good!

**Comment by Alhadis** [comment]
Thank you! :D

**Pull request closed without merging**
