### PR TITLE
The Perl 6 Syntax highlighter has changed repo URL's and is now an official Perl 6 Org project

### PR DESCRIPTION
**Pull request by samcv**
Update the URL's and add the repo.  Let me know if I did this right.

### CODE REVIEW

**Comment by pchaigno** [comment]
Hm. The old repository doesn't make any mention of the new location and the last commit is from only 9 days ago. Will development continue on the "old" repository? Was there any bug fixes or improvements from the old to the new?

/cc @MadcapJake

**Comment by samcv** [comment]
Yes there have been improvements:
https://github.com/perl6/atom-language-perl6/blob/master/CHANGELOG.md#v195

There are a huge number of improvements from 1.8 (that old repo) and the new one at 1.9.5

**Comment by zoffixznet** [comment]
To shed more light on the situation and to better answer @pchaigno question and perhaps better explain to @MadcapJake what's happening, if they ever happen to reappear.

1) @MadcapJake is the original developer of the `perl6fe` atom extension and the code that GitHub currently uses to highlight its Perl 6 gists and code. The community thanks @MadcapJake for that work, as outside of `vim`, this is currently the only way to get syntax highlighting for Perl 6 that's worth two bits.
2) Somewhere around middle of June 2016, @MadcapJake stopped responding to Issues on the repository, and so the problems stayed unfixed and the repository also accumulated a couple of PRs that remained unmerged
3) 5 months later, around the middle of November, @samcv started participating in the Perl 6 community, and unaware of @MadcapJake prolonged absence, started fixing the issues in the repository and creating PRs. Before the creation of the https://github.com/perl6/atom-language-perl6 fork, she [created 99 commits](https://github.com/samcv/language-perl6fe/compare/7f646ac...2c942d4) to the repo, fixing numerous issues
4) As a watcher of @MadcapJake's repo, I was receiving several notifications daily due to @samcv's work, so on November 22nd, 2016, I tracked down @MadcapJakes' Twitter account and [asked them to review the PRs accumulating in the repo as well as to give out commit bits so members of community could make updates](https://twitter.com/zoffix/status/801032888456269824). 
4) 6 days later, on November 28, 2016, @MadcapJake [responded](https://twitter.com/MadcapJake/status/803413162666102784), saying they've been busy and will merge PRs and hand out commit bits that same evening.
5) 3 days later, on December 1, 2016, @MadcapJake [indeed did have some activity](https://github.com/MadcapJake?tab=overview&from=2016-12-01) and merged a couple of PRs along with releasing version 1.8.0 of the Atom plugin. This is the activity @pchaigno pointed out, however, it was just a couple of commits over the past half a year. I'm unaware of anyone receiving commit bits during that period.
6) @MadcapJake's brief reappearance inspired @samcv [to fix a whole ton of Issues and make a PR](https://github.com/MadcapJake/language-perl6fe/pull/43). 
7) On December 2, 2016, @MadcapJake [commented on that PR](https://github.com/MadcapJake/language-perl6fe/pull/43#issuecomment-264517493) commending the work and promising to merge the PR within the next 10 hours.
8) 4 days later, on December 6, 2016, I [commented on the PR](https://github.com/MadcapJake/language-perl6fe/pull/43#issuecomment-265122270), imploring @MadcapJake to merge it
9) 4 days later, on December 10, 2016, seeing @MadcapJake is again being non-responsive, we forked @MadcapJake's repo into **perl6** org (the official org of the Perl 6 language), and applied [all 144 of unmerged @samcv's commits](https://github.com/perl6/atom-language-perl6/compare/180abe4...48b45d8).

So whether @MadcapJake will continue development of their fork is unknown to us. However, the **perl6** org has 263 members, as opposed to a single developer, and so it'd be a bit harder for it to bit rot. Currently, it's ~144 commits ahead of @MadcapJake's version, fixing numerous issues, which makes it more correct, and more suitable for use by GitHub to highlight its gists and perl 6 code.

Please merge this. Thanks.

**Comment by samcv** [comment]
Wow, that is pretty detailed, thanks for putting that together @zoffixznet
+1

**Comment by samcv** [comment]
Also to note, development continues at a rapid pace. v1.9.9 just got released as well.

The language now has a /spec folder for spec tests as well as having automated what was 1/4 of the code. If @MadcapJake sees this, thanks for all the work you put into the project.

**Comment by pchaigno** [comment]
@samcv Could you update the branch before we merge?

**Comment by samcv** [comment]
@pchaigno I have resolved the merge conflicts now.

**Comment by samcv** [comment]
Or did you want me to update the references too?

**Pull request merged**
