### PR TITLE
Added Blade

### PR DESCRIPTION
**Pull request by jbrooksuk**
This adds support for Laravel's Blade markup language.

### CODE REVIEW

**Comment by Alhadis** [comment]
You'll need to add a grammar for the language's highlighting on GitHub. [This would be a good one](https://github.com/jawee/language-blade), had the owner bothered to specify a license for it...

You can also set "tm_scope` to `none` in `languages.yml` to specify no highlighting, too.

**Comment by arfon** [comment]
Hi @jbrooksuk, thanks for opening this Pull Request :zap:

Please take a look at our [contributing guidelines](https://github.com/github/linguist/blob/master/CONTRIBUTING.md) to finish up the additional steps required before review :smile:

**Comment by jbrooksuk** [comment]
Thanks! I'll sort this on Tuesday :)

**Comment by Alhadis** [comment]
@jbrooksuk How did you go? =)

**Comment by jbrooksuk** [comment]
Right! I'm on this today now.

**Comment by jbrooksuk** [comment]
CLA is done!

**Comment by pchaigno** [comment]
Flagging as stale :flags:

**Comment by Alhadis** [comment]
Paging @jbrooksuk If this doesn't get sorted eventually, it'll be closed.

**Comment by jbrooksuk** [comment]
Will look into it today.

**Comment by Alhadis** [comment]
I'll hold you to that and check back in precisely 24 hours.

Don't think I won't.

**Comment by jbrooksuk** [comment]
😨 

I'm on it now!

**Comment by jbrooksuk** [comment]
Rebased.

**Comment by Alhadis** [comment]
James, you'll probably need to update your grammar submodules, as it's
likely they haven't been updated in your fork for a while.

Merge master branch into your branch from upstream, then try running these
steps:

1. `script/bootstrap`
2. `git submodule update --remote && git commit -a`
3, `bundle exec rake samples`

**Comment by jbrooksuk** [comment]
For the second step, the commit that is made, what do I do with that, my history would be too far forward?

**Comment by Alhadis** [comment]
Show me the output of `git status` and `git log`, please.

I'm not sure if you merged with a fast-forward or what.

**Comment by jbrooksuk** [comment]
Originally I did a `git reset --hard upstream/master`.

**Comment by Alhadis** [comment]
Eh? Why?

`git pull` should've been adequate. What's your working branch at now?

**Comment by jbrooksuk** [comment]
Habit I guess.

`git status` is outputting this:

```
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   vendor/grammars/MagicPython (new commits)
	modified:   vendor/grammars/NSIS (new commits)
	modified:   vendor/grammars/NimLime (new commits)
	modified:   vendor/grammars/PHP-Twig.tmbundle (new commits)
	modified:   vendor/grammars/TLA (new commits)
	modified:   vendor/grammars/atom-language-stan (new commits)
	modified:   vendor/grammars/awk-sublime (new commits)
	modified:   vendor/grammars/language-babel (new commits)
	modified:   vendor/grammars/language-clojure (new commits)
	modified:   vendor/grammars/language-coffee-script (new commits)
	modified:   vendor/grammars/language-csharp (new commits)
	modified:   vendor/grammars/language-csound (new commits)
	modified:   vendor/grammars/language-gfm (new commits)
	modified:   vendor/grammars/language-javascript (new commits)
	modified:   vendor/grammars/language-less (new commits)
	modified:   vendor/grammars/language-python (new commits)
	modified:   vendor/grammars/language-shellscript (new commits)
	modified:   vendor/grammars/language-yaml (new commits)
	modified:   vendor/grammars/latex.tmbundle (new commits)
	modified:   vendor/grammars/pawn-sublime-language (new commits)
	modified:   vendor/grammars/php.tmbundle (new commits)
	modified:   vendor/grammars/ruby-slim.tmbundle (new commits)
	modified:   vendor/grammars/sourcepawn (new commits)
	modified:   vendor/grammars/sublime-typescript (new commits)
	modified:   vendor/grammars/vue-syntax-highlight (new commits)

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	vendor/grammars/Elm.tmLanguage/
	vendor/grammars/blade/
	vendor/grammars/restructuredtext.tmbundle/

no changes added to commit (use "git add" and/or "git commit -a")

```

**Comment by Alhadis** [comment]
Ugh, bloody submodules. This is where I give up and call for help in grossly-mispronounced French.

@pchaigno, AIDER.

**Comment by Alhadis** [comment]
See, what I do in situations like this, is burn my entire branch, delete the freaking repo, and refork all over again. I've lost at least two followers who were probably sick of seeing this shit on their newsfeed every morning:



My understanding of submodules is embarrassingly shaky for a Git addict, probably because 99% of my exposure to them has been through Linguist. Even after so many pull requests, I swear I STILL have no frakking idea how the hell they exist-in-a-repo-sort-of-but-not-really.

**Comment by pchaigno** [comment]
Let's not resort to that just yet. I'll have a look.

**Comment by pchaigno** [comment]
@jbrooksuk Before everything else you should take a look at [the contribution guidelines to add a new language](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language), in particular the requirement on in-the-wild adoption. We'll need an estimation of the number of Blade files on github.com for each extension you add (I can help with the exact search queries if needed).

Now for the tests, I think the easiest way to fix it will be to undo your last commit and force repush it:
```bash
git checkout master # we'll need to update master's submodules first
git submodule update --init --recursive # get the same submodules as the master branch of Linguist
git checkout blade
git reset HEAD^ # undo the last commit
git add .gitmodules grammars.yml samples/Blade/ vendor/licenses/grammar/blade.txt # add only what's needed
git commit -m "Update Blade language support" # commit again
git push -f origin blade # force pushes and rewrite your last commit on the blade branch
```
The issue seems to be that you committed some changed submodules by mistake in your last commit ;)

**Comment by jbrooksuk** [comment]
@pchaigno I can't do a search for `blade.php`, https://github.com/search?utf8=%E2%9C%93&q=extension%3A%22blade.php%22&type=Code&ref=searchresults which is weird. But I imagine you'll be surprised, it's the templating language for Laravel, which is popular itself.

I'll follow your suggestions now.

**Comment by jbrooksuk** [comment]
Ping @pchaigno, @Alhadis?

**Comment by Alhadis** [comment]
`vendor/grammars/blade` should be `vendor/grammars/language-blade`.

It's `vendor/grammars/NAME_OF_REPOSITORY_AS_SEEN_IN_GRAMMAR_URL`.

**Comment by jbrooksuk** [comment]
Ah-ha! I'm on it.

**Comment by jbrooksuk** [comment]
I should change `grammars.yml` then.

**Comment by jbrooksuk** [comment]
I think it'd be easier if I start again :)

**Comment by Alhadis** [comment]
Yes, definitely.

**Comment by jbrooksuk** [comment]
I'll be back soon!

**Pull request closed without merging**
