### PR TITLE
Add Cypher Query Language syntax highlighting and file extension detection

### PR DESCRIPTION
**Pull request by 007vasy**
# Desciption
This ***PR*** adds the **_Cypher_** query language with the ```*.cyp``` and ```*.cypher``` extension. 

The language is a graph query language https://opencypher.org/ and it's ISO recognition is WIP

[There are already:](https://github.com/search?q=extension%3Acyp&type=code)
  - 1.4k code results
  - 382k package results
  - 895k topic results
  - 64586k user results

So It would be great to have syntax highlighting on github (and later search as well) :)

Godspeed!

## Checklist:

- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?q=extension%3Acyp&type=Code
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - https://github.com/opencypher/openCypher/blob/master/tck/graphs/yago/openCypher-yago-graph.cypher
      - https://github.com/opencypher/openCypher/blob/master/tck/graphs/binary-tree-1/binary-tree-1.cypher
      - https://github.com/opencypher/openCypher/blob/master/tck/graphs/binary-tree-2/binary-tree-2.cypher
      - https://github.com/neo4j/cypher-shell/blob/4.3/cypher-shell/src/test/resources/org/neo4j/shell/parser/graphgems.cypher
      - https://github.com/neo4j/cypher-shell/blob/4.3/cypher-shell/src/test/resources/org/neo4j/shell/parser/torture-test.cypher
      - https://github.com/neo4j/cypher-shell/blob/4.3/cypher-shell/src/test/resources/org/neo4j/shell/parser/small-test.cypher
    - Sample license(s):
      - https://github.com/opencypher/openCypher/blob/master/LICENSE
  - [x] I have included a syntax highlighting grammar: https://github.com/fredbenenson/sublime-cypher.git

### CODE REVIEW

**Comment by 007vasy** [comment]
@lildude 1.4k code snippets :) let me know how can I assist

**Comment by 007vasy** [comment]
@lildude can you help me run the test?

**Comment by lildude** [comment]
> @lildude can you help me run the test?

Sure, but I assume you already know the outcome as you'll have run these locally too, right? 😉 

This won't speed up the merging of this PR as I won't be merging any PRs that aren't bugfixes until I'm close to making a release which won't be until next month at the earliest.

**Comment by lildude** [comment]
Looks like you didn't follow the instructions for adding a grammar and the tests have just rumbled you 😁

**Comment by 007vasy** [comment]
my bad, thanks for the update will fix

**Comment by 007vasy** [comment]
I closing this and opened a new one:
https://github.com/github/linguist/pull/6027 with tests running green

**Pull request closed without merging**
