### PR TITLE
Remove samples/LANG/filenames as a source of truth

### PR DESCRIPTION
**Pull request by pchaigno**
All filenames must now be explicitly listed in `languages.yml`.

## Description

A recent classification error urged me to look into this. [rust-lang/crates.io-index](https://github.com/rust-lang/crates.io-index) was incorrectly recognized as C because of file [`sc/ri/script`](https://github.com/rust-lang/crates.io-index/blob/44befb6674c06850756c5181de95c5782a500377/sc/ri/script). Although we do not have a `script` filename listed in `languages.yml`, we do have a `script` sample file in `samples/C/filenames`. (I probably incorrectly put this sample file there because of its shebang and lack of extension.) Linguist uses the list of filenames from `samples/LANG/filenames/`, in addition to those defined in `languages.yml`, to determine which files belong to a language:
https://github.com/github/linguist/blob/dd3b1eec911072ca051ecccabc03a47bafa2c76c/lib/linguist/language.rb#L542-L548

I think it would be better to rely on `languages.yml` as the single source of truth for languages and their files. I removed the culprit lines and added the appropriate filenames to `languages.yml`.
I also moved `samples/C/filenames/script` to its correct location, thus solving the classification with rust-lang/crates.io-index.

## Checklist:

- [ ] **I am associating a language with a new file extension.**
  - [ ] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      
      - https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am adding a new language.**
  - [ ] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a syntax highlighting grammar.
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am fixing a misclassified language**
  - [ ] I have included a new sample for the misclassified language:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am changing the source of a syntax highlighting grammar**
  
  - Old: https://github-lightshow.herokuapp.com/
  - New: https://github-lightshow.herokuapp.com/

- [x] **I am adding new or changing current functionality**
  
  - [x] I have added or updated the tests for the new or changed functionality.

### CODE REVIEW

**Comment by pchaigno** [comment]
@lildude Should I remove or add them everywhere? Only in my modifications, or everywhere in the file? [`script/set-language-ids`](https://github.com/github/linguist/blob/dd3b1eec911072ca051ecccabc03a47bafa2c76c/script/set-language-ids) adds them everywhere I think; we didn't have any before this script existed.

**Comment by lildude** [comment]
So as not to deviate from the original intent of this PR, lets stick with adding the quotes to just the lines you're adding. We can come back and do the others later, or as other peeps touch the various sections, we can ask them to do it.

**Comment by lildude** [comment]
CI should pass once https://github.com/github/linguist/pull/4081 has been merged.

**Comment by pchaigno** [comment]
I updated the branch.

**Comment by lildude** [comment]
> @lildude Is anything else needed?

Yup, consistent quoting for the lines you're adding - https://github.com/github/linguist/pull/4078#issuecomment-376548340

**Comment by pchaigno** [comment]
Ah. Should have added a comment on that. I tried to be consistent with the remaining of the file: double quotes are only added ([by Ruby's YAML](https://github.com/github/linguist/blob/718c9efaca1530c04d38e3e5b0aa67096ea59b73/script/set-language-ids#L74)) when there's a dot, i.e., for file extensions and some filenames.

**Comment by lildude** [comment]
> Ah. Should have added a comment on that. I tried to be consistent with the remaining of the file: double quotes are only added (by Ruby's YAML) when there's a dot, i.e., for file extensions and some filenames.

Ah, I see now. 👍

**Pull request merged**
