### PR TITLE
Add file types for SmartBear:TestComplete

### PR DESCRIPTION
**Pull request by tx99gtp**
Add the ability for SmartBear's common file types to be indexed properly

Because SmartBear's file types are seemingly proprietary and the majority of our repo is made up of these file types, it would be beneficial for us to see how much of each file type is in the repo.

### CODE REVIEW

**Comment by arfon** [comment]
Hi @tx99gtp, thanks for opening up this Pull Request. Could you please take a look at the [contributing guidelines](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language) and link to search results showing 'in the wild' usage of these languages/extensions.

**Comment by tx99gtp** [comment]
@arfon, thank you for the quick assistance.  Below is a link to documentation that supports these file extensions/languages. Please let me know if I misunderstood your request.  
https://support.smartbear.com/viewarticle/74777/

**Comment by arfon** [comment]
> Below is a link to documentation that supports these file extensions/languages. Please let me know if I misunderstood your request.

Thanks for the link @tx99gtp. This isn't quite what I mean. A bit of background: as changes to Linguist affect how all users of GitHub experience the product we're relatively cautious about adding support for new languages (and extensions to existing ones). As part of the review process we ask contributors to include links to our search UI showing that the extension/language combination is already used by a significant number of individuals (typically many hundreds of files & repositories).

For example, this is a link to search for the string `xml` within `.tcScript` files: https://github.com/search?utf8=%E2%9C%93&q=xml+extension%3AtcScript&type=Code&ref=searchresults

By the looks of things SmartBear are the only people naming files this way (as there aren't any public results here) and so we wouldn't be able to merge this specific change (for `.tcScript` files).

The same seems to be true for `.tcNM`: https://github.com/search?utf8=%E2%9C%93&q=xml+extension%3AtcNM&type=Code&ref=searchresults files also.

Could you perhaps give a little more background about the languages and file extensions you're using here. Are they pretty much all unique to your organization?

**Comment by CStaplesLewis** [comment]
Arfon, 

If I’m understanding properly, the linguist repository should only be used specifically for changes that can aid some specific number of repositories?  Meaning, if we are the only ones with this filetype and extension, then the linguist repo isn’t the route we need to take?

I believe I can shed some light on these filetypes and extensions.  Our organization is utilizing an IDE provided by SmartBear called TestComplete.  Many of these filetypes are project files that are proprietary to SmartBears’ TestComplete and are not unique to our organization, rather to any organization using SmartBears’ TestComplete.  As we use a master project that contains our .tcNM file, it is very important to us that we be able to see that this file hasn’t grown to an irregular size, thus we need these filetypes indexed.  Any organization utilizing GitHub and SmartBear would be in the same situation.  

We realize that the [change currently under review](https://github.com/github/linguist/pull/2744/files?diff=split) is to allow linguist to recognize __3__ different 'categories' of files (JScript, NameMapping, TestComplete) but moving forward we do not want this.

To simplify, our goal is that:
* Our .sj’s be recognized as JScript.
* Our SmartBear proprietary filetypes to be recognized as XML
* Bonus: Our .tcNM file to be labeled NameMapping (if not, XML is fine)

> [Link to show that others are using the .sj extension](https://github.com/search?utf8=%E2%9C%93&q=sj+extension%3Asj&type=Code&ref=searchresults)

Our repo used to be indexed as Objective-J before we made the following changes to our .gitattributes file:
> *.sj linguist-language=JScript

> *.tcScript linguist-language=XML

> *.tcNM linguist-language=XML

Now it lists a large majority of our repo as SQLPL or PLSQL

> [Link to show our repo being indexed incorrectly](http://s8.postimg.org/wym1dfn05/Capture.png)

> [Link to show that our index bar doesn't match actual %'s or actual filetypes of the repo](http://s17.postimg.org/94blbsmhr/Capture3.png)

Beyond that, when the linguist is indexing our .sj's it indexes them as Objective-J:

> [Link to show the syntax of our .sj files](https://github.com/flowcal/linguist/blob/691a97b8db8bcec622c3a8bf7b3ff002f5d6faf7/samples/JScript/zFileSystem.sj)

> [Link to show the syntax of Objective-J](https://en.wikipedia.org/wiki/Objective-J)

In summation:

We can make changes to classify the TestComplete specific files as XML if you feel that this is the best route forward for us but either way our .sj's will need to be indexed as JScript.

**Comment by arfon** [comment]
> If I’m understanding properly, the linguist repository should only be used specifically for changes that can aid some specific number of repositories? Meaning, if we are the only ones with this filetype and extension, then the linguist repo isn’t the route we need to take?

Yes that's correct.

> To simplify, our goal is that:
> - Our .sj’s be recognized as JScript.

JScript currently isn't a language that Linguist supports and from [my albeit limited reading](https://en.wikipedia.org/wiki/JScript) around the subject it's not clear to me that we should add this as both JavaScript and JScript are essentially just implementations of ECMAScript right? We currently already have [`.sjs`](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L1668) listed as a JavaScript extension, would it be OK to just add `.sj` to JavaScript?

> Link to show that others are using the .sj extension

Thanks for sharing this. Looking at the search results it looks like there's a mix of languages in here (including Java?). Is there a way to construct a search query that only returns JScript files?

> - Our SmartBear proprietary filetypes to be recognized as XML

Is sounds like you've already tried this with `*.tcScript linguist-language=XML` in your `.gitattributes` data. Even if this 'worked' you wouldn't necessarily see the results in the language bar as XML is [defined as `data`](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L3656) by Linguist which means it doesn't contribute to repository language statistics.

> - Bonus: Our .tcNM file to be labeled NameMapping (if not, XML is fine)

To do this we'd need to go through the [aforementioned steps](https://github.com/github/linguist/pull/2744#issuecomment-159462798) in the contributing guidelines demonstrating wider usage on GitHub. 

>  (if not, XML is fine)

Again, this should be possible using `.gitattributes` data but with the same caveat about this not changing the repository statistics bar because of the `data` type.

I'm sorry that this isn't an easier process for you :-\ . Could you tell me what your overall goal is here? Is it to 'fix' the repository statistics (the coloured bar) or is it that you're getting unsatisfactory syntax-highlighting?

**Comment by CStaplesLewis** [comment]
> JScript currently isn't a language that Linguist supports and from my albeit limited reading around the subject it's not clear to me that we should add this as both JavaScript and JScript are essentially just implementations of ECMAScript right? We currently already have .sjs listed as a JavaScript extension, would it be OK to just add .sj to JavaScript?

Technically, JScript and JavaScript are the same language just relabeled for Microsofts copyright reasonings.  It would be more correct if we could not add .sj's to JavaScript and instead add JScript as a language the linguist supports.  Eitherway, currently our .sj's aren't being recognized as JavaScript at all.

> Thanks for sharing this. Looking at the search results it looks like there's a mix of languages in here (including Java?). Is there a way to construct a search query that only returns JScript files?

While its a much smaller sample, [this](https://github.com/search?utf8=%E2%9C%93&q=jscript+extension%3A.sj&type=Code&ref=searchresults) appears to be a more accurate result set. Notice, these .sj's are being indexed as Objective-J, this is incorrect.

> I'm sorry that this isn't an easier process for you :-\ . Could you tell me what your overall goal is here? Is it to 'fix' the repository statistics (the coloured bar) or is it that you're getting unsatisfactory syntax-highlighting?

It's okay. We knew we were going to have to go through conversations learning what we need to do to get our repository statistics 'fixed'.
Our goal is that our repo be indexed properly.  
* Our .sj's be indexed as JScript
* Our .tcNM be indexed as something other than 'data' because it would be ignored
* All other project files be indexed as data

We are also seeing unsatisfactory syntax highlighting but only in rare occasion.  It's a secondary issue that we arent currently focused on.

**Comment by arfon** [comment]
> Eitherway, currently our .sj's aren't being recognized as JavaScript at all.

I don't know if you've tried this already but you could use the [Linguist overrides](https://github.com/github/linguist#overrides) to 'force' GitHub into recognizing these files as JavaScript in your repository statistics. You need a `.gitattributes` file with the following:

```
*.sj linguist-language=JavaScript
```

> While its a much smaller sample, this appears to be a more accurate result set. Notice, these .sj's are being indexed as Objective-J, this is incorrect.

OK, that's useful thank you. Because both Objective-J and JavaScript (JScript) use `.sj` as an extension we're going to need to find a way to identify the two reliably and then [write a heuristic](https://github.com/github/linguist/blob/master/lib/linguist/heuristics.rb#L149-L159) to correctly assign them. In this process we'll also need to demonstrate that there are significant more than [two files](https://github.com/search?utf8=%E2%9C%93&q=jscript+extension%3A.sj&type=Code&ref=searchresults) written in JScript to meet our [contributing guidelines](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-an-extension-to-a-language).

> - Our .tcNM be indexed as something other than 'data' because it would be ignored

This is tricky because I simply cannot find *any* `.tcNM` files on GitHub in [public repositories](https://github.com/search?utf8=%E2%9C%93&q=NOT+arfon+extension%3AtcNM&type=Code&ref=searchresults) which means that the usage of this extension must be very low (i.e. just in some private repos).

Ideally for your use-case I think you need something like a custom language definition just for your repository but we currently don't support anything like this.

**Comment by CStaplesLewis** [comment]
> *.sj linguist-language=JavaScript

I'll try this as a last resort (considering these files aren't actually JavaScript). In the meantime:


> OK, that's useful thank you. Because both Objective-J and JavaScript (JScript) use .sj as an extension we're going to need to find a way to identify the two reliably and then write a heuristic to correctly assign them. In this process we'll also need to demonstrate that there are significant more than two files written in JScript to meet our contributing guidelines.

To focus our efforts, we'll begin by writing a heuristic for JScript.  But before that, it appears that your guidelines need 1000s of examples (if I'm reading that correctly).  I can definitely provide 1000s of examples from within our own repository, though I'm assuming you mean across multiple repositories.  
[Here's my best attempt to show dozens of examples](https://github.com/search?p=1&q=var+extension%3Asj+language%3AObjective-J+state%3Aopen+NOT+flowCal&ref=searchresults&type=Code&utf8=%E2%9C%93).

Note: Based on my [limited research](http://www.cappuccino-project.org/learn/objective-j.html) these code snippets do not look anything like Objective-J, yet their being indexed as Objective-J.  In fact, they look a whole lot more like JScript.

Let me know if this is enough example to warrant the creation of a JScript heuristic.

**Comment by CStaplesLewis** [comment]
Bump

**Comment by arfon** [comment]
Sorry for the delayed response @CStaplesLewis.

> To focus our efforts, we'll begin by writing a heuristic for JScript. But before that, it appears that your guidelines need 1000s of examples (if I'm reading that correctly). I can definitely provide 1000s of examples from within our own repository, though I'm assuming you mean across multiple repositories.

I think it's OK to pursue this strategy if you're confident that you can write an accurate heuristic to disambiguate `Objective-J` and `JScript`.

> To focus our efforts, we'll begin by writing a heuristic for JScript. But before that, it appears that your guidelines need 1000s of examples (if I'm reading that correctly). I can definitely provide 1000s of examples from within our own repository, though I'm assuming you mean across multiple repositories.

Yes, we ask that the language is being used in ['hundreds of repositories'](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language) before we will consider adding it.

[This search](https://github.com/search?utf8=%E2%9C%93&q=var+extension%3Asj+language%3AObjective-J+NOT+flowCal&type=Code&ref=searchresults) returns just over 1000 files but I'm not sure how many repos this represents - @pchaigno do you have a script that can calculate this?

Also, @CStaplesLewis looking at the results of the above search query I think we're going to need to find a more accurate search query as it includes files like [this](https://github.com/fordot-archipel/fordot-archipel.github.io/blob/7e9d3dd2f4f9efc900ff92f7f47629cfd06e6ee7/Modules/VirtualMachineScheduler/Browser.environment/VirtualMachineScheduler.sj) which appear to be correctly classified as `Objective-J`

**Comment by pchaigno** [comment]
> This search returns just over 1000 files but I'm not sure how many repos this represents - @pchaigno do you have a script that can calculate this?

220 repositories (I downloaded everything and used`ls -l * | grep 4096 | wc -l`).

**Comment by CStaplesLewis** [comment]
So where do we stand with this? WHat exactly do you need from me?

**Comment by CStaplesLewis** [comment]
@arfon @pchaigno - let me know exaclty what you're needing at this point and I can produce that

**Comment by pchaigno** [comment]
@CStaplesLewis The issue we're having here is to make a search that only returns JScript `.sj` files (in order to estimate their number on GitHub). Do you know a couple keywords common in JScript (and unused in Objective-J)?

**Comment by arfon** [comment]
:flags: flagging this as stale :flags:

**Comment by CStaplesLewis** [comment]
Arfon, I think this went stale becasue we overcomplicated the issue we were originally were seeing.  

We have two issues.

1. GitHub does not diff our .sj's properly.  Instead, it recognizes them as binary files, when they should be treated as plain text.  We have added *.sj diff into out .gitattributes file, but it did not correct our issue.

2. GitHub does not index our .sj's properly. Instead they are indexed as SQLPL.  

Our original thought was that these two issues were related.  Our hope was that correcting the indexing of our .sj's might make them diff properly.

All we really need is for them to diff properly.  I realize that might not be your field of expertise.  If not, whom should I talk to?

**Comment by arfon** [comment]
Hi @CStaplesLewis - thanks for the update.

> 1. GitHub does not diff our .sj's properly. Instead, it recognizes them as binary files, when they should be treated as plain text. We have added *.sj diff into out .gitattributes file, but it did not correct our issue.

This is unfortunately an issue your file encoding (UTF-16) and with the way git decides if something is 'binary'. See this comment on a related issue here: https://github.com/github/linguist/issues/2088#issuecomment-73402700

I believe the only way to fix this is for your files to be UTF-8 encoded.

> 2. GitHub does not index our .sj's properly. Instead they are indexed as SQLPL.

Based on my comments here: https://github.com/github/linguist/pull/2744#issuecomment-164746698 and @pchaigno's comments here: https://github.com/github/linguist/pull/2744#issuecomment-171380686 there's still some work to do to try and reliably identify `JScript`.

> All we really need is for them to diff properly. I realize that might not be your field of expertise. If not, whom should I talk to?

If this is the immediate/only priority then please take a look at saving your files in a different encoding (if that's possible for you?)

**Comment by CStaplesLewis** [comment]
Getting closer!

I found a file that wouldn't diff properly and changed it to UTF-8.  Locally, it diffed properly in GixExtensions (our git GUI tool) but when pushed up to GitHub, it was still recognized as a binary. 

Git Extensions:
gitext

GItHub:
github

I have attached the file here:
[_availableExports.txt](https://github.com/github/linguist/files/167467/_availableExports.txt)

Note, this file should be changed to a .sj.  GitHub wouldn't host it as a .sj so i converted it to a .txt

**Comment by arfon** [comment]
@CStaplesLewis - is the diff where the `_availableExports.sj` file is being shown as binary public (i.e. can you share the URL?)

I've downloaded the file and added it to a repo here but can't seem to replicate the issue :-\ https://github.com/arfon/test/pull/1/files

Would you mind trying to fork https://github.com/arfon/test and add one of these `.sj` files to a Pull Request to see if we can replicate this issue?

**Comment by CStaplesLewis** [comment]
@arfon Weird. I see that it works in your test branch AND it works when i fork it.
It's like it just doesn't diff within our repo.  

I'm not sure if the link to the pull request is public.  Try [this](https://github.com/flowcal/TQM/pull/141).

**Comment by arfon** [comment]
> @arfon Weird. I see that it works in your test branch AND it works when i fork it. It's like it just doesn't diff within our repo.

Did you try adding a `.sj` file to your fork of my repo? That might be worth trying?

**Comment by CStaplesLewis** [comment]
@arfon Looks like it shows up in your repo if i click the name of the file, but when I click "Added files via upload" right next to the name of the file, it shows "Binary file not shown."

Side-note: It's also indexed as Objective-J even though it isn't Objective-J.

**Comment by arfon** [comment]
> but when I click "Added files via upload" right next to the name of the file, it shows "Binary file not shown."

Could you take a screenshot of what you're clicking on here? I'm afraid I can't seem to find what you're clicking on :-\

**Comment by CStaplesLewis** [comment]
@arfon Sorry!

When I click here:
capture

I get this:
capture2

**Comment by pchaigno** [comment]
That looks like an issue with github.com rather than Linguist itself.
@CStaplesLewis If you still have this issue you should contact support@github.com. They'll be better able to help you.

**Comment by CStaplesLewis** [comment]
We tried that first. This was the response from @jhosman 

> Thanks for sending the additional info. The language bar doesn't show anything classified as type: data by Linguist. XML is classified as data, which is why your overrides to tcScript and tcNM aren't showing up:
> https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L3645
> If you take a look through that same languages file, you'll find that JScript doesn't exist there, which is why your .sj override isn't changing anything. You would need to submit an Issue or Pull Request in the Linguist repository to request having it added, so that it can show in the languages bar on GitHub.
> Sorry for any confusion there! Let us know if you have other questions.
> Cheers,
> Jess

We went down a long and windy road to finally determine our issue is the GitHub doesnt diff our .sj's.

Thus this thread was created.

**Comment by jhosman** [comment]
👋  @CStaplesLewis Could you reach out to [GitHub Support](https://github.com/contact) again -- This seems like a slightly different issue than what was discussed in that previous thread. Please mention me there, so my coworkers know to ping me into the conversation. Thanks!

**Comment by CStaplesLewis** [comment]
Opened a new ticket with GitHub Support and mentioned you.

**Comment by arfon** [comment]
@CStaplesLewis - I think the latest on this issue with the diff was this comment: https://github.com/CStaplesLewis/test/commit/0b7c3533489a156976aba8d4ae3318fdff13f150#commitcomment-17032168

Did you get a chance to try this?

**Comment by CStaplesLewis** [comment]
@arfon  i have not, i do not have that repo available any longer and cnanot remember the steps to reproduce.

WHat should i be doing to reproduce this issue? then i can try to remove the UTF8-BOM

**Comment by arfon** [comment]
> @arfon i have not, i do not have that repo available any longer and cnanot remember the steps to reproduce.

😞 I'm afraid I don't really know what to suggest here. I couldn't replicate the diffing issue myself so it was probably something specific to your development environment introducing the `UTF8-BOM` stuff.

Given the age of this thread and the fact the the changes proposed in this thread aren't really what we're discussing here I'd suggest closing this pull request and starting with a new issue describing the issue/bug. How does that sound?

**Comment by CStaplesLewis** [comment]
soudns great. i'll let me issue open to @jhosman stand as our current issue.

**Pull request closed without merging**
