### PR TITLE
Add ".plt" to Prolog extensions

### LINKED ISSUE #5074: .plt files recognized as "Gnuplot", but they're also unit test files for Prolog
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

As per the title.
 - Prolog is the most used logic programming language
 - SWI-Prolog is the most widespread compiler and framework for Prolog
 - .plt files are unit test files in SWI-Prolog (and maybe other Prolog systems)

I get "Gnuplot" for .plt files. I would like them to be listed as Prolog.
These are the current extensions for Prolog in _languages.yml_:
  - ".pl"
  - ".pro"
  - ".prolog"
  - ".yap"

Reference (point 3): https://www.swi-prolog.org/pldoc/doc_for?object=section(%27packages/plunit.html%27)

### Expected language:

Prolog

### Detected language:

Gnuplot

### PR DESCRIPTION
**Pull request by GeoffChurch**
.plt files are used by Gnuplot for saved plots, and by SWI-Prolog (and probably SICSTUS Prolog) for PlUnit tests. Most seem to be misclassified as Gnuplot.

We can try a simple ":-\s?begin_tests" heuristic, but hopefully the classifier will pick up on the vastly different syntax.

I wrote a Prolog .plt sample, and copied an existing Gnuplot sample to have the .plt extension.

Fixes #5074

## Checklist:
- [x] **I am associating a language with a new file extension.**
  - [x] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      - https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3Aplt+begin_tests+NOT+nothack
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s): I wrote the sample Prolog .plt for this PR, so it can fall under linguist's license.
  - [x] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [x] **I am fixing a misclassified language**
  - [ ] I have included a new sample for the misclassified language:
    - Sample source(s):
      - [samples/Gnuplot/defense_plotter.p](https://github.com/github/linguist/blob/32ec19c013a7f81ffaeead25e6e8f9668c7ed574/samples/Gnuplot/defense_plotter.p)
    - Sample license(s): MIT
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

### CODE REVIEW

**Comment by lildude** [comment]
Please update the OP to link to the source of the GNUplot sample and state the license.

**Comment by GeoffChurch** [comment]
Done

**Comment by Alhadis** [comment]
> We can try a simple ":-\s?begin_tests" heuristic, but hopefully the classifier will pick up on the vastly different syntax.

Why not both? The heuristic will catch the most obvious Prolog cases, and any file not containing a `:-` token will fall through to the classifier strategy.

~~~diff
diff --git a/lib/linguist/heuristics.yml b/lib/linguist/heuristics.yml
index d948886c..449de061 100644
--- a/lib/linguist/heuristics.yml
+++ b/lib/linguist/heuristics.yml
@@ -485,6 +485,10 @@ disambiguations:
     named_pattern: perl5
   - language: Raku
     named_pattern: perl6
+- extensions: ['.plt']
+  rules:
+  - language: Prolog
+    pattern: '^\s*:-'
 - extensions: ['.plist']
   rules:
   - language: XML Property List
~~~

**Comment by GeoffChurch** [comment]
Is there anything remaining to be done before this can be merged?

**Comment by lildude** [comment]
> Is there anything remaining to be done before this can be merged?

Yup. You need to fix the failing test 😉

**Comment by GeoffChurch** [comment]
@lildude okay hopefully that does it!

**Comment by GeoffChurch** [comment]
Hi, can this get merged now? I think it's good-to-go

**Review by Alhadis — APPROVED** [review]
@lildude, this LGTM. 👍

**Pull request merged**
