### PR TITLE
Better SASS (indented) highlighting

### PR DESCRIPTION
**Pull request by pzi**
Using a different SASS highlighter by @nathos: https://github.com/nathos/sass-textmate-bundle

[A highlighter example](https://lightshow.githubapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fnathos%2Fsass-textmate-bundle%2Fmaster%2FSyntaxes%2FSass.tmLanguage&grammar_text=&code_source=from-text&code_url=&code=%40import+%22variables%22%2C+%22mixins%22%2C+%22fonts%22%0D%0A%0D%0A.testing-syntax-highlighting%0D%0A++font-size%3A+16px%0D%0A++width%3A+55px%0D%0A++height%3A+55px%0D%0A++display%3A+inline-block%0D%0A++h3%0D%0A++++font-size%3A+14px%0D%0A++++background-color%3A+%23000+%2F%2F+just+because%0D%0A++++color%3A+%23fff%0D%0A++++%26.something%0D%0A++++++background-repeat%3A+no-repeat%0D%0A++++.blurb+%26%0D%0A++++++position%3A+relative%0D%0A++++++z-index%3A+0%0D%0A++img%2C%0D%0A++video%2C%0D%0A++embed%2C%0D%0A++object%2C%0D%0A++.size-auto%2C%0D%0A++.size-full%2C%0D%0A++.size-large%2C%0D%0A++.size-medium%2C%0D%0A++.size-thumbnail%0D%0A++++height%3A+auto%0D%0A++++max-width%3A+100%25%0D%0A%0D%0A*%2C+body%2C+input%2C+button%2C+select%2C+textarea%0D%0A++-webkit-font-smoothing%3A+antialiased%0D%0A%0D%0Ah1%0D%0A++font-size%3A+%24base-fontsize+*+2%0D%0A%0D%0Ah2%0D%0A++font-size%3A+%24base-fontsize+*+1.5%0D%0A%0D%0Ah3%0D%0A++font-size%3A+%24base-fontsize+*+1.3%0D%0A%0D%0Ah4%0D%0A++font-size%3A+%24base-fontsize+*+1.3%0D%0A++font-weight%3A+normal%0D%0A++%2Bpie-clearfix%0D%0A%0D%0Ah5%2C+h6%0D%0A++font-size%3A+%24base-fontsize+*+1.1%0D%0A)

Compared to the highlighter that is used currently: [Highlighter example](https://lightshow.githubapp.com/?utf8=%E2%9C%93&scope=source.sass&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fnathos%2Fsass-textmate-bundle%2Fmaster%2FSyntaxes%2FSass.tmLanguage&grammar_text=&code_source=from-text&code_url=&code=%40import+%22variables%22%2C+%22mixins%22%2C+%22fonts%22%0D%0A%0D%0A.testing-syntax-highlighting%0D%0A++font-size%3A+16px%0D%0A++width%3A+55px%0D%0A++height%3A+55px%0D%0A++display%3A+inline-block%0D%0A++h3%0D%0A++++font-size%3A+14px%0D%0A++++background-color%3A+%23000+%2F%2F+just+because%0D%0A++++color%3A+%23fff%0D%0A++++%26.something%0D%0A++++++background-repeat%3A+no-repeat%0D%0A++++.blurb+%26%0D%0A++++++position%3A+relative%0D%0A++++++z-index%3A+0%0D%0A++img%2C%0D%0A++video%2C%0D%0A++embed%2C%0D%0A++object%2C%0D%0A++.size-auto%2C%0D%0A++.size-full%2C%0D%0A++.size-large%2C%0D%0A++.size-medium%2C%0D%0A++.size-thumbnail%0D%0A++++height%3A+auto%0D%0A++++max-width%3A+100%25%0D%0A%0D%0A*%2C+body%2C+input%2C+button%2C+select%2C+textarea%0D%0A++-webkit-font-smoothing%3A+antialiased%0D%0A%0D%0Ah1%0D%0A++font-size%3A+%24base-fontsize+*+2%0D%0A%0D%0Ah2%0D%0A++font-size%3A+%24base-fontsize+*+1.5%0D%0A%0D%0Ah3%0D%0A++font-size%3A+%24base-fontsize+*+1.3%0D%0A%0D%0Ah4%0D%0A++font-size%3A+%24base-fontsize+*+1.3%0D%0A++font-weight%3A+normal%0D%0A++%2Bpie-clearfix%0D%0A%0D%0Ah5%2C+h6%0D%0A++font-size%3A+%24base-fontsize+*+1.1%0D%0A).

### CODE REVIEW

**Comment by pzi** [comment]
Hello! Happy New Year! 

Back from holidays... will do that asap :)

Also, there is one issue I found with the current highlighter for sass (indented) when using apostrophe in a single line comment:

apostrophe

**Comment by pchaigno** [comment]
> @pzi - would you mind opening an issue on those repos asking for the maintainers to add a license?

@arfon - @aroben added a grammar for Sass at #1860, does @pzi still need to ask for a license on the two other grammars (though it won't hurt :-)?
<br/>

> Also, there is one issue I found with the current highlighter for sass (indented) when using apostrophe in a single line comment:

@pzi I think it relates to the issue @aroben found about inline comments not being highlighted. You should probably open an issue for that on the grammar's repo ;)

**Comment by pzi** [comment]
I've seen #1860 :)
However, I will ask for the license because, personally, I prefer the other grammars more still :) Thought the current one was only an ad interim solution until the other one has a license.

**Comment by aroben** [comment]
If we want to switch to another grammar we should absolutely get a license added to it and switch. Thanks for getting that started @pzi.

And as @pchaigno said, if there are bugs in the current grammar it would be great to open issues in the appropriate repository.

**Comment by pzi** [comment]
Houst... Err @aroben, we have a license :)

**Comment by aroben** [comment]
I took care of this over in #1956. Thanks @pzi!

**Comment by pzi** [comment]
Great stuff @aroben, my pleasure :)

**Pull request closed without merging**
