### PR TITLE
Add MLIR grammar

### PR DESCRIPTION
**Pull request by jpienaar**
Add support for MLIR

## Description
Add support for [MLIR](https://github.com/tensorflow/mlir).

## Checklist:

- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?q=extension%3Amlir+NOT+nothack&type=Code
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [const-fold.mlir](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/mlir/lite/tests/const-fold.mlir)
      - [core-ops.mlir](https://github.com/tensorflow/mlir/blob/master/test/IR/core-ops.mlir)
      - [executor_to_control_dialect.mlir](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/mlir/tensorflow/tests/executor_to_control_dialect.mlir)
      - [sample.mlir](https://github.com/jpienaar/mlir-grammar/blob/master/sample.mlir)
    - Sample license(s): Apache-2.0
  
  - [x] I have included a syntax highlighting grammar: 
    [core-ops](https://github-lightshow.herokuapp.com/?utf8=✓&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fjpienaar%2Fmlir-grammar%2Fmaster%2Fgrammars%2Fmlir.json&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Ftensorflow%2Fmlir%2Fmaster%2Ftest%2FIR%2Fcore-ops.mlir&code=)

### CODE REVIEW

**Comment by jpienaar** [comment]
@pchaigno Thanks! I combined it from multiple of the unit tests to get something a bit more interesting mix of types (all from the same repo and with same license). Would you prefer if I use one/more exact file instead?

**Comment by jpienaar** [comment]
Updated template to point to exact file instead.

**Comment by pchaigno** [comment]
> I combined it from multiple of the unit tests to get something a bit more interesting mix of types (all from the same repo and with same license).

Thanks for the explanation. Including a few files instead of a single one would have been fine too.

**Comment by jpienaar** [comment]
> > I combined it from multiple of the unit tests to get something a bit more interesting mix of types (all from the same repo and with same license).
> 
> Thanks for the explanation. Including a few files instead of a single one would have been fine too.

Sounds good to me, added a few more (exact samples from real usage). Let me know if anything else is needed. Thanks

**Comment by jpienaar** [comment]
> The test failure here is legit:
> 
> ```
> /home/runner/work/linguist/linguist/vendor/licenses/grammar/mlir-grammar.txt:
>   - cached license data out of date
> ```
> 
> You'll need to run `script/licensed` (which should update the `version` in the license) and commit the updated file. You might need to manually add back the license text though, so feel free to.

Updated, that did it thanks

**Comment by jpienaar** [comment]
This seems to have stopped working (previously highlighted file no longer works), I don't see anything in the commit logs that would indicate a change though.

**Comment by lildude** [comment]
I've taken a look into this as this appears to only affect languages or grammars added in v7.6.0.  Work is underway to improved the syntax highlighting service used by GitHub and I suspect it has missed the v7.6.0 update. I've opened an issue to bring this to the attention of the team responsible for the improvements.

I'll update when I know more or when things are working as expected again.

**Comment by lildude** [comment]
> Work is underway to improved the syntax highlighting service used by GitHub and I suspect it has missed the v7.6.0 update.

All sorted. This was indeed the case.

**Comment by jpienaar** [comment]
> > Work is underway to improved the syntax highlighting service used by GitHub and I suspect it has missed the v7.6.0 update.
> 
> All sorted. This was indeed the case.

Great, thanks!

**Pull request merged**
