### PR TITLE
Add support for the Pic language

### PR DESCRIPTION
**Pull request by Alhadis**
**[Pic](https://en.wikipedia.org/wiki/Pic_language)** is a procedural DSL to generate simple drawings in Roff or TeX, such as flowcharts and diagrams. The language is closely tied with Roff, but its syntax and semantics are very different. Pic is also equipped with Turing-complete programming facilities, such as loops, conditionals, variables and macro definitions, making it a decidedly complex language.

**Extensions:**
- [`.pic`](https://github.com/Alhadis/Linguist-Silo/tree/pic): [21,862 results](https://github.com/search?q=extension%3Apic+NOT+nothack&type=Code)
- [`.chem`](https://github.com/Alhadis/Linguist-Silo/tree/chem): [2,547 results](https://github.com/search?q=extension%3Achem+NOT+nothack&type=Code)

Understandably, most results for `.pic` were binary files. Of the 3,000 files I collated from search results, 43% of the text files were Pic source (the remainder being project-languages or files with weird extensions).

### CODE REVIEW

**Comment by pchaigno** [comment]
Many of these files are tagged as 1C Enterprise. Do you know why?

> Of the 3,000 files I collated from search results, 43% of the text files were Pic source (the remainder being project-languages or files with weird extensions).

So that's about 1,500 files. Do you know how many repositories for each file extension?

**Comment by pchaigno** [comment]
> Many of these files are tagged as 1C Enterprise. Do you know why?

This looks like a generalized issue on github.com. @arfon Could this be related to the recent reindexing?

**Comment by arfon** [comment]
> This looks like a generalized issue on github.com. @arfon Could this be related to the recent reindexing?

Weird, I don't see any tagged as such. Can you grab a screenshot/share a URL where you're seeing this @pchaigno?

**Comment by pchaigno** [comment]
Next to each file, on the right end side, under the sort options.

**Comment by Alhadis** [comment]
> So that's about 1,500 files. Do you know how many repositories for each file extension?

[`.pic`](https://github.com/Alhadis/Linguist-Silo/blob/pic/summary.txt) has 326 unique repositories, and [`.chem](https://github.com/Alhadis/Linguist-Silo/blob/chem/summary.txt) has 90.

> Many of these files are tagged as 1C Enterprise. Do you know why?

Uh, they weren't tagged as anything several hours ago. :|

If I were to guess, I'd say that's because `1C Enterprise` has a language ID of 0... zero being a falsey-value. Go figure.

**Comment by arfon** [comment]
> If I were to guess, I'd say that's because `1C Enterprise` has a language ID of 0... zero being a falsey-value. Go figure.

This certainly smells like a bug. @chrismwendt - would you be able to take a look at this. Basically files that currently don't have a Linguist-recognized language are being reported as `1C Enterprise` (which [has `language_id=0`](https://github.com/github/linguist/blob/22c2cf4967773224339ba672c473c340f84d3fdb/lib/linguist/languages.yml#L44))  on dotcom :

screen_shot_2016-10-11_at_4_55_36_pm

What does the search index return for the view if there's no language detected? Is it `0`?

**Comment by arfon** [comment]
> .pic has 326 unique repositories, and .chem has 90.

@Alhadis are you using [this script](https://github.com/Alhadis/Harvester/blob/js/harvester.js) to generate these result?

**Comment by Alhadis** [comment]
Only for scraping the URLs. They were then dumped into a text file and run through `wget`, with duplicates removed (based on MD5 checksum).

**Comment by chrismwendt** [comment]
@arfon This is definitely a bug, and is somehow slipping through the logic where we show `Unknown` if there is no mapping from language ID to name. Thank you for reporting this - I'm :eyes:ing into it.

**Comment by chrismwendt** [comment]
I fixed this issue and added a regression test. My apologies for the weird site behavior :bug:

**Comment by arfon** [comment]
> I fixed this issue and added a regression test. My apologies for the weird site behavior 🐛

💖 thanks @chrismwendt!

**Pull request merged**
