### PR TITLE
Create tex-to-python

### PR DESCRIPTION
**Pull request by meghdadFar**
The Language of my Python repo (https://github.com/meghdadFar/SDMA) is incorrectly identified as Tex.

### CODE REVIEW

**Comment by Alhadis** [comment]
Why did you delete the template? It had links to the answers to your problem.

**Comment by meghdadFar** [comment]
Where can I get the template now?

**Comment by Alhadis** [comment]
I didn't notice this was a pull-request... why didn't you [submit an issue](https://github.com/github/linguist/issues) instead?

I see you added a [`.gitattributes` file](https://github.com/meghdadFar/SDMA/blob/b7a22ced319b29cee096e5226111615816f32e21/.gitattributes) to your repository, but there's two problems with it:

1.	You've specified `.bib`, which will only affect files that are *literally* named `.bib`. This should be `*.bib` instead (the `*` being a wildcard).
2.	You're marking [TeX files](https://github.com/meghdadFar/SDMA/blob/2bcc6cbb383d38fe5ad67a192812f4654b2f973b/notebook/ipython.bib) as Python, but what you meant to do is mark them as "vendored":
	
	~~~gitattributes
	*.bib linguist-vendored
	~~~
	
	"Vendored" means *"I didn't write this"*, so GitHub excludes it from a project's language statistics.

For more information, see the [section on overrides](https://github.com/github/linguist#overrides) in Linguist's readme.

**Comment by meghdadFar** [comment]
I just followed this project's description "If your repository's language is being reported incorrectly, send us a pull request!" 
Thanks for the correction. It worked and now the language is detected correctly.

**Pull request closed without merging**
