### PR TITLE
Add support for the BASIC family of programming languages

### PR DESCRIPTION
**Pull request by telnet23**
## Description

As I reported in #5156, many BASIC programs have been incorrectly labeled as VBA (or Visual Basic .NET if they have not been updated since #4725). There are numerous dialects of [BASIC](https://en.wikipedia.org/wiki/BASIC) (e.g. AppleSoft, Commodore, GW-BASIC), but most dialects share similar syntax and reserved words, and all dialects are collectively known as BASIC. At the very least, a file with the extension `.bas` and line numbering should be labeled as BASIC rather than Visual Basic .NET or VBA. Therefore, I have added a BASIC language along with an appropriate grammar and sample, and I have added a heuristic to check for line numbering.

## Checklist

- [x] **I am adding a new language**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com
    * https://github.com/search?q=10+20+30+GOTO+extension%3Abas&type=Code
  - [x] I have included a real-world usage sample for all extensions added in this PR
    * https://github.com/telnet23/bas/blob/master/mandelbrot.bas
  - [x]  I have included a syntax highlighting grammar
    * https://github.com/telnet23/language-basic
  - [x] I have updated the heuristics to distinguish my language from others using the same extension
    * Added a heuristic to check for line numbering

### CODE REVIEW

**Comment by zspitz** [comment]
Your query searches for `GOTO`, but AFAICT the search is case-insensitive.  `GoTo` is a keyword (albeit an infrequently used one) in [VBA](https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/goto-statement) and [VB.NET](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/goto-statement).

Do members of the BASIC family generally use all-caps `GOTO`? Would it be worth adding `GOTO` to the heuristic for BASIC languages and `GoTo` for VBA and VB.NET, as a last-case heuristic?

**Comment by telnet23** [comment]
@zspitz Correct, the GitHub search is case-insensitive, which is why I also included 10 20 30 in the search. Line numbers in BASIC programs are often (but certainly not always) chosen to be multiples of 10. The search is not all-inclusive but it does provide clear evidence that BASIC programs have been incorrectly labeled as Visual Basic .NET or VBA.

Some dialects of BASIC are case-insensitive while others are case-sensitive, requiring uppercase keywords. Even in dialects of BASIC that are case-insensitive, programs are sometimes written entirely in uppercase anyway.

**Comment by telnet23** [comment]
@lildude Any update on this pull request?

**Comment by lildude** [comment]
> @lildude Any update on this pull request?

I was waiting for you to address the failing tests as the PR isn't complete whilst they're failing.

**Comment by telnet23** [comment]
@lildude OK, all checks have passed now.

**Review by lildude — APPROVED** [review]
LGTM 🙇

**Pull request merged**
