### PR TITLE
Adding ATS language support by converting existing SublimeText syntax def

### PR DESCRIPTION
**Pull request by steinwaywhw**
Originally, ATS is parsed as OCaml. Now we have a dedicated ATS syntax definition converted from ATS SublimeText syntax def. But I removed ".atxt" support. And the ACE Mode is still in OCaml.

### CODE REVIEW

**Comment by githwxi** [comment]
This is great for our small but vibrant ats-lang-users community :)

Cheers!

**Comment by pchaigno** [comment]
Hi @steinwaywhw - You can use [Lightshow](https://lightshow.githubapp.com/) to demonstrate the improvement with the new grammar. It usually makes things clearer for reviewers.

Also, I'm not familiar with ATS and I was wondering why you chose to remove support for `.atxt` files? There seems to be [a good number of them on GitHub](https://github.com/search?o=desc&q=extension%3Aatxt+NOT+dhjdhfjdengf&s=indexed&type=Code&utf8=%E2%9C%93).

**Comment by steinwaywhw** [comment]
Hi @pchaigno, thanks for the tool. [Lightshow Demo](https://lightshow.githubapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgithub.com%2Fsteinwaywhw%2Fats-mode-sublimetext%2Fblob%2Fmaster%2Fats.tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fsteinwaywhw%2Flinguist%2Fblob%2Fmaster%2Fsamples%2FATS%2FYonedaLemma.dats&code=) is here. Basically, it is dedicated for handling ATS files, instead of borrowing OCaml definition. It works much better now. 

`.atxt` file is sort of a template language, that will be further compiled into `.dats/.sats` or even `.html` files. It is not defined by ATS syntax. The support of `.atxt` might be added later. But for the moment, I don't think my syntax file will present any nice looking `.atxt` files at all.

**Comment by pchaigno** [comment]
Okay, thanks for the explanations!
I'm not from GitHub but I looks good to me, shouldn't be long before it's merged ;)

**Comment by arfon** [comment]
Hi @steinwaywhw - would you mind brining this branch up to date with `master` so it will cleanly merge?

**Comment by steinwaywhw** [comment]
Hi @arfon, merged with upstream/master.

**Comment by arfon** [comment]
:+1: thanks @steinwaywhw. This should be live on GitHub in the next week or so.

**Comment by bbarker** [comment]
thanks all!

**Pull request merged**
