### PR TITLE
Adding some words about maintainers

### PR DESCRIPTION
**Pull request by arfon**
/ cc @pchaigno @larsbrinkhoff @bkeepers

### CODE REVIEW

**Comment by bkeepers** [comment]
I pushed a change to move it to the bottom, since it's probably not the most important information for new  contributors. Thoughts?

**Comment by arfon** [comment]
> I pushed a change to move it to the bottom, since it's probably not the most important information for new contributors. Thoughts?

Makes sense to me.

**Comment by arfon** [comment]
🎉 welcome to the club @pchaigno and @larsbrinkhoff :zap:

**Comment by larsbrinkhoff** [comment]
Thank you!

**Comment by ChinoJones** [comment]
hello maintainers

**Pull request merged**
