### PR TITLE
Add support for Texinfo documents

### PR DESCRIPTION
**Pull request by Alhadis**
This PR adds support for [Texinfo](https://www.gnu.org/software/texinfo/manual/texinfo/), a lightweight markup language chiefly used by GNU projects.

Fixes: #4479.

## Checklist:
- [x] **I am adding a new language.**
	- [x] **The extensions are used in hundreds of repositories on GitHub.com**
		- `.texinfo`: [~26,875 results](https://github.com/search?q=extension%3Atexinfo+NOT+nothack&type=Code)
		- `.texi`:    [~647,762 results](https://github.com/search?q=extension%3Atexi+NOT+nothack&type=Code)
		- `.txi`:     [~6,509 results](https://github.com/search?q=extension%3Atxi+NOT+nothack&type=Code)
	- [x] **I have included a real-world usage sample**
		- `protocol-spec.texi`: [Source](https://github.com/ruby-debug/ruby-debug-ide/blob/c14e867c33be0d6f5fd7ea0ffab9b0eaf4b24cff/doc/protocol-spec.texi) | [MIT license](https://github.com/ruby-debug/ruby-debug-ide/blob/8add0a9cee3a09ef3996c2b349fdf41df10f5cb7/MIT-LICENSE)
	- [x] **I have included a syntax highlighting grammar:**
		- [`Alhadis/language-texinfo`](https://github.com/Alhadis/language-texinfo)
		- [Lightshow preview](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=cson&grammar_url=https%3A%2F%2Fgithub.com%2FAlhadis%2Flanguage-texinfo%2Fblob%2Fmaster%2Fgrammars%2Ftexinfo.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fruby-debug%2Fruby-debug-ide%2Fmaster%2Fdoc%2Fprotocol-spec.texi&code=)

### CODE REVIEW

**Comment by idrougge** [comment]
When will this PR come into effect? No Textinfo files I have seen have been rendered with syntax highlighting.

**Comment by FranklinYu** [comment]
@idrougge This is weird. I think I saw it deployed before and confirmed it with the file mentioned above. I guess it is disabled for some reason.

**Comment by Alhadis** [comment]
@idrougge, @FranklinYu There appear to be some issues with GitHub's syntax highlighter at the moment. A number of languages are being affected; only thing we can really do at this point is report the problem to site support and wait. 😞

**Comment by lildude** [comment]
I've taken a look into this as this appears to only affect languages or grammars added in v7.6.0.  Work is underway to improved the syntax highlighting service used by GitHub and I suspect it has missed the v7.6.0 update. I've opened an issue to bring this to the attention of the team responsible for the improvements.

I'll update when I know more or when things are working as expected again.

**Comment by lildude** [comment]
> Work is underway to improved the syntax highlighting service used by GitHub and I suspect it has missed the v7.6.0 update.

All sorted. This was indeed the case.

**Pull request merged**
