### PR TITLE
Add support for HEY language

### PR DESCRIPTION
**Pull request by enty8080**
**Add support for HEY programming language.**

## Description

HEY is a lightweight **dynamically** typed embedded scripting language with **simple** and **natural** syntax. HEY supports **imperative programming**, **object-oriented programming** and **functional programming**.

URL to the project, compiled binaries, online compiler and reference manual of HEY is here:
https://enty8080.github.io/hey

Test the power of HEY language at **HEY online**:
https://enty8080.github.io/hey/online

**highlighting grammar coming soon, idk how to add it**

## Checklist:

- [x] **I am adding a new language.**
  - [x] I have included a real-world usage sample for all extensions added in this PR:
  - [ ] I have included a syntax highlighting grammar: https://github-lightshow.herokuapp.com/ **idk how to do it :(**
  - [x] I have updated the heuristics to distinguish my language from others using the same extension.

### CODE REVIEW

**Comment by lildude** [comment]
In your excitement, I think you missed the most important part before we'd even consider this PR:

> We try only to add languages once they have some usage on GitHub. In most cases we prefer that each new file extension be in use in hundreds of repositories before supporting them in Linguist.

There are only _22_ files on the whole of GitHub: https://github.com/search?q=extension%3Ahey+NOT+nothack

You also seemed to have missed other parts of the documentation on how to add a language, but that's not really relevant at this point.

**Comment by enty8080** [comment]
@lildude if i will create 100 files `.hey` will you add language?

**Comment by lildude** [comment]
How about with some emphasis:

> In most cases we prefer that each new file extension be in use in **hundreds of repositories** before supporting them in Linguist.

These would need to be unique user/repo combos too. Gaming the system is not going to do you any favours either 😉

**Comment by enty8080** [comment]
Ok, idk how to make people use my language because there are a lot of other languages like HEY, for example python or ruby. HEY is like python or ruby. How can this programming language be promoted?

**Comment by Alhadis** [comment]
> How can this programming language be promoted?

Think of some groundbreaking, genius features that haven't been thought of yet, then demonstrate some practical uses for them that give users incentive to use your language. :wink:

**Comment by enty8080** [comment]
Thanks.

**Comment by enty8080** [comment]
@lildude Can I rename my language to NEO and rePR?

**Comment by lildude** [comment]
Sure, but you're still going to have to meet the overall usage requirements for your new PR to be accepted.

**Comment by enty8080** [comment]
@lildude How can I remove this PR?

**Comment by lildude** [comment]
Close it. You've already removed your fork.

**Comment by lildude** [comment]
Done 😄

**Pull request closed without merging**
