### PR TITLE
Add .nasm extension for Assembly files.

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
There is exactly one file with the `.nasm` extension hosted ad GitHub, so feel free to close this if it's too insignificant.  On the other hand, Assembly do have "nasm" as an alias and search term, so it's not too far fetched to add the extension.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
Ping @arfon @bkeepers 

I'll totally close this if you make that call.,

**Comment by aroben** [comment]
This is now live on github.com.

**Comment by larsbrinkhoff** [comment]
Thanks! :+1:

**Comment by larsbrinkhoff** [comment]
Either usage has exploded, or the search index now includes many more `.nasm` files.

https://github.com/search?q=extension%3Anasm+NOT+slartibartfast

**Pull request merged**
