### PR TITLE
Add Cairo language support

### PR DESCRIPTION
**Pull request by rajivpo**
Syntax highlighting support for [Cairo Language](https://www.cairo-lang.org/). Can't see exactly how many repos the language is currently being used but have the relevant query below.

## Description
Happy to add a different, simpler example if that would be relevant.

## Checklist:

- [x] **I am adding a new language.**
  - [] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3Acairo
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
          - [Dope Wars](https://github.com/dopedao/RYO/tree/main/contracts)
    - Sample license(s):
  
  - [x] I have included a syntax highlighting grammar: https://github-lightshow.herokuapp.com/
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

### CODE REVIEW

**Review by lildude — CHANGES_REQUESTED** [review]
I've not looked at usage yet but I know for sure we can't accept this PR because of the grammar licence. Please find another grammar licensed by one of [these](https://github.com/github/linguist/blob/257425141d4e2a5232786bf0b13c901ada075f93/vendor/licenses/config.yml#L2-L11) licences or close this PR if you can't.

**Comment by rajivpo** [comment]
The license has been updated to MIT

**Comment by rajivpo** [comment]
@lildude just wanted to follow up here to see what else can/should be done to help get this merged 😄

**Comment by lildude** [comment]
As pointed out to me in https://github.com/github/linguist/pull/5661 the grammar here isn't an actual TextMate-compatible grammar. https://github.com/github/linguist/pull/5661 is ready to merge, so if you're happy with it @rajivpo, we can close this PR in favour of that one?

**Comment by Nixinova** [comment]
#5751, you mean?

**Comment by lildude** [comment]
> #5751, you mean?

🤦 I do. #5661 is this PR 🤭

**Comment by lildude** [comment]
Closing in favour of https://github.com/github/linguist/pull/5751

**Pull request closed without merging**
