### PR TITLE
Update the `Instrumenter` doc

### PR DESCRIPTION
**Pull request by javierhonduco**
Updates the instrumenter doc, initializing it.

### CODE REVIEW

**Comment by Alhadis** [comment]
qué

**Comment by javierhonduco** [comment]
The existing docs suggest setting `Linguist.instrument` to the Instrumenter class: `Linguist.instrumenter = CustomInstrumenter`. 

That's not going to work as the `instrument` method calls [`instrumenter.instrument(*args, &bk)`](https://github.com/linguist/linguist/blob/716498e63561e8844f68b68b1fd9c716f2748272/lib/linguist.rb#L94), which is an instance method.

I think that doc embedded in the comments may be confusing as it doesn't work as stated. That's why I created this small PR.

**Comment by Alhadis** [comment]
Ah, veo!

/cc @pchaigno @kivikakk

**Comment by javierhonduco** [comment]
Practising languages on a code collaboration tool, we are living in the future ✨ ✨  

PS: Sounds more natural if you say "entiendo" instead of "veo" 😃

**Comment by Alhadis** [comment]
I pretend to contribute to this repo, but I'm really using the name `Linguist` as a rabid excuse to shit-talk in as many world languages as possible.

**Pull request merged**
