### PR TITLE
Add ArnoldC

### PR DESCRIPTION
**Pull request by gadhagod**
## Description

Added ArnoldC to languages.yml.

## Checklist:
- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  
  - [ ] I have included a syntax highlighting grammar: https://github-lightshow.herokuapp.com/
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

### CODE REVIEW

**Comment by gadhagod** [comment]
This is my first time contributing to lingust, so please let me know if I did anything wrong.

**Comment by lildude** [comment]
@gadhagod Please review and follow _all_ of the steps for adding a new language detailed in CONTRIBUTING.md and ensure the template in the OP of this PR has been filled in correctly... hint: you need to do more than tick the boxes 😉 

One thing to pay special attention to is the minimum popularity requirements needed for inclusion.

**Comment by gadhagod** [comment]
Thanks for the response @lildude. 
The only step I didn't do in the contributing guidelines was adding grammar, but that is optional right? 
Also, ArnoldC is used in 128 repositories, passing the requirement of hundred.

**Comment by lildude** [comment]
> The only step I didn't do in the contributing guidelines was adding grammar, but that is optional right?

Almost. You've not filled in the template as detailed, and yes, a grammar is not needed.

> Also, ArnoldC is used in 128 repositories, passing the requirement of hundred.

Not quite. There are only 138 `.arnoldc` files. This is not the same as the required "hundreds of repositories". At the moment we require this to be more than 200 unique user/repo combos.

**Comment by gadhagod** [comment]
Whoops, I read it as a hundred repos. My bad and thanks.

**Comment by Alhadis** [comment]
@gadhagod You can resubmit Arnold once he reaches sufficient popularity. 👍

**Comment by gadhagod** [comment]
Definitely! I hope sometime soon.

**Pull request closed without merging**
