### PR TITLE
Instructions to add a new extension to a language

### PR DESCRIPTION
**Pull request by pchaigno**
This pull request adds a new entry in `CONTRIBUTING.md` on how to add a new extension to a language.

It's mostly the same as `Adding a language` but, in many cases, new contributors don't seem to feel concerned by the existing instructions/requirements when they just add an extension. It will also give us something we can directly point to when necessary.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
> We try only to add new extensions once they have some usage on GitHub. In most cases we prefer that extensions be in use in hundreds of repositories before supporting them in Linguist.

There seem to be ample precedent for adding a new extension to popular languages, even though the new extension aren't used in hundreds of repositories.

**Comment by pchaigno** [comment]
I thought that *In most cases we prefer* was sufficient to describe this. Do you think we should change this is both *Adding an extension to a language* and *Adding a language*?

**Comment by larsbrinkhoff** [comment]
I think a case could be made for having less strict requirements for individual extensions, than for new languages.

I suggest: "We prefer that extensions are used in hundreds of *files* before supporting them in Linguist."  This also has the benefit of being easy to verify with a code search.

**Comment by arfon** [comment]
:+1: thanks for this @pchaigno.

**Pull request merged**
