### PR TITLE
Add missing Gerber extensions and heuristics

### PR DESCRIPTION
**Pull request by smola**
## Description

There are a few additional extensions for Gerber (`.cmp`, `.crc`, `.crs`, `.ncl`). See: http://cirqwizard.org/docs/gerber.html

We had a Gerber sample in `samples/Text/LIDARLite.ncl` which is now moved to `samples/Gerber Image`.

~Updated heuristic for `.ncl`, and added new ones for `.cmp`, `.crc` and `.crs`, which are marked as Generic extensions.~

~`.cmp` is certainly common, but `.crc`. `.crs` and `.ncl` not so much. An alternative to this PR would be removing the `LIDARLite.ncl` sample and adding just the `.cmp` extension Gerber Image.~

UPDATE: Updated heuristic for `.ncl`, and added a new one `.cmp`. Other extensions are left out because of lack of popularity.

It's quite hard to find any sample with a liberal license, so tests are just reusing all Gerber samples using the `alt_name` trick to simulate the extension.

## Checklist:
- [x] **I am associating a language with a new file extension.**
  - The new extension is used in hundreds of repositories on GitHub.com
    - [x] `.cmp`: https://github.com/search?q=extension%3Acmp+%28Gerber+OR+Ultiboard+OR+LPD+OR+MOIN+OR+M02%29+NOT+nothack&type=Code
    - [ ] `.ncl`: https://github.com/search?q=extension%3Ancl+%28Gerber+OR+Ultiboard+OR+LPD+OR+MOIN+OR+M02%29+NOT+nothack&type=Code
  - I have included a real-world usage sample for all extensions added in this PR:
    - [x] `.ncl`: `samples/Gerber Image/LIDARLite.ncl`, previously present as `samples/Text/LIDARLite.ncl`
    - [ ] `.cmp`: not found so far, simulated in tests
  - [x] I have included a change to the heuristics to distinguish my language from others using the same extension.

### CODE REVIEW

**Comment by smola** [comment]
cc @Alhadis per #3744

**Comment by Alhadis** [comment]
> with a catch-all fallback to Text.

Wouldn't it be better to mark said extensions as [generic](https://github.com/github/linguist/pull/4936) instead?

**Comment by smola** [comment]
> > with a catch-all fallback to Text.
> 
> Wouldn't it be better to mark said extensions as [generic](https://github.com/github/linguist/pull/4936) instead?

Sure! I missed that feature.

**Comment by smola** [comment]
Done. We still need to decide whether any of these extensions belong to Linguist (re. popularity).

**Review by Alhadis — COMMENTED** [review]
`.crc` looks fine to me, but with `.crs` might be pushing it:

<details><summary><code>.crc</code>: <b>162 users</b></summary>

```
aaronwubshet
AdrianoRuseler
alexbhandari
ArduinoHannover
ARTEMIS-UPenn
assr01
astronewts
atang618
avnishks
azya52
baseapp
Beat707
BelaPlatform
bemxgm
bgkatz
blinken
bojack5
bozotics
cadsoftcomputer
CalPlug
ChaceAshcraft
chateau86
chow004
cirqoid
comcat
Cougar
CrackberryPi
crice009
critterandguitari
curtfs
danysantiago
dbdxnuliba
DC801
diarsabri
diyaudiocircuits
domino-team
dragino
drgroovestarr
DroningOn
dsky7
dvjcodec
eddiechen1008
ekloiber
engaging-computing
estel1
FabAcademyPortugal2017
fcl015
fgentili
flexSD
formtapez
FormulaU
Franzininho
FrauBluher
FritzenLab
germanespinosa
ghislainborremans
gregaiello
gtjennings1
guitchounts
helena-project
Herushan
htbrdd
huarui1q
Huzuri
imaveek
ingelectronicadj
IngmarVerheij
intelligent-agent
irllabs
IronHeartConsulting
ISpeak2myHouse
jagannath-sahoo
jankae
jiegoguanzon
jonntee
josephvoss
JQIamo
jufranz
Jugbot
kbarbee95
kelflanagan
kicksat
kiwiai
krs013
LeeCheongAh
Li-Nayu
likapateknoloji
liujiaq1
lolomolo
lyf8118
MadlyFX
martin-c
mathew-kurian
mel00010
mettworks
MisterHW
mocalab
mocona05
msinvent
mureytasroc
mWorkVN
NeuronRobotics
nmori613
noduino
NoelGaspar
NormanBrandon
oelprinz-org
open-ephys
OpenROV
osegouin
phase4ground
pillforge
poseidon-neptune-project
pscholl
rajulg92
ralph-sj
reiser4
RFMicron
robthepyro
rodrigosilvaluz
RoyOltmans
russells
ryanjulian
sabSAThai
samuel-feibel
sbelectronics
SeerLikeJazz
ShaastraWebops
shohei
siggiorn
simonbb4
singhalanirudh18
spaceconcordia
SPECNOW
ssenkus
st3fan
svenpetersen1965
Taris9047
texas-guadaloop
the-positive-charge
TheFwGuy
TNEL-UCSD
tristantech
trougnouf
tsukolsky
tvikneshwar
UA-Robotics
uazipsev
ucam-comparch
UltimateCyclingTrainingSystem
UOERacing
vaginessa
vha3
vladimiroltean
walc1
xpix
xz-group
zackbloom
zacmanchester
Zeepro
zhagan
zrecore
```

</details>

<details><summary><code>.crs</code>: <b>118 users</b></summary>

```
aaronwubshet
alexbhandari
ARTEMIS-UPenn
astronewts
atang618
avnishks
baseapp
BelaPlatform
bgkatz
blinken
bozotics
cadsoftcomputer
CalPlug
chow004
comcat
ContainerDroid
danysantiago
dbdxnuliba
DC801
delta-leonis
diarsabri
diyaudiocircuits
domino-team
dragino
drgroovestarr
DroningOn
dsky7
eddiechen1008
ekloiber
engaging-computing
estel1
fcl015
flexSD
formtapez
FormulaU
FrauBluher
germanespinosa
gregaiello
gtjennings1
guitchounts
helena-project
Herushan
huarui1q
imaveek
infocelab
ingelectronicadj
intelligent-agent
IronHeartConsulting
jankae
jiegoguanzon
JQIamo
jufranz
kbarbee95
kicksat
kiwiai
LeeCheongAh
likapateknoloji
liujiaq1
lyf8118
MadlyFX
martin-c
mel00010
mettworks
MisterHW
mocalab
mocona05
mWorkVN
NeuronRobotics
nevros
nmori613
noduino
NoelGaspar
NormanBrandon
oelprinz-org
open-ephys
OpenROV
osegouin
pillforge
poseidon-neptune-project
rajulg92
ralph-sj
reiser4
RFMicron
russells
ryanjulian
sabSAThai
samuel-feibel
sbelectronics
SeerLikeJazz
ShaastraWebops
siggiorn
simonbb4
singhalanirudh18
spaceconcordia
SPECNOW
ssenkus
st3fan
Taris9047
the-positive-charge
tinypico
TNEL-UCSD
tristantech
trougnouf
tsukolsky
tvikneshwar
UA-Robotics
uazipsev
ucam-comparch
UOERacing
vaginessa
vha3
vladimiroltean
walc1
zackbloom
zacmanchester
Zeepro
zhagan
zrecore
```

</details>

**Comment by lildude** [comment]
> 162 users is high enough to qualify as a plural w.r.t. @lildude's _"hundreds of users"_ requirement. 😉

To remain consistent, it's a "not yet".

**Comment by smola** [comment]
Rebased and removed `.crs` and `.crc` extensions.

**Review by lildude — APPROVED** [review]
LGTM

**Review by lildude — APPROVED** [review]

**Pull request merged**
