### PR TITLE
Treat Xamarin .workbook files as markdown

### PR DESCRIPTION
**Pull request by sandyarmstrong**
Xamarin Workbook files are interactive coding documents for C#, serialized as
markdown files. They include a YAML front matter header block with some
metadata. Interactive code cells are included as `csharp` fenced code blocks.

An example can be found here:
https://github.com/xamarin/Workbooks/blob/master/csharp/csharp6/csharp6.workbook

Treated as markdown, it would appear like so:
https://gist.github.com/sandyarmstrong/e331dfeaf89cbce89043a1c31faa1297

They are becoming increasingly popular as teaching documents. There are a few hundred already in GitHub today: https://github.com/search?utf8=%E2%9C%93&q=extension%3Aworkbook+NOT+nothack&type=Code&ref=searchresults .

### CODE REVIEW

**Comment by sandyarmstrong** [comment]
Oh, I see that samples are required now. I will add one.

**Comment by sandyarmstrong** [comment]
I do not believe the Travis build issues have anything to do with my commit?

**Comment by lildude** [comment]
> I do not believe the Travis build issues have anything to do with my commit?

@sandyarmstrong nope, doesn't look like it. Can you please merge in master and we'll see how things play out.

**Comment by sandyarmstrong** [comment]
@lildude rebased on latest master. Looks like the build passed!

**Comment by sandyarmstrong** [comment]
Thanks! Any idea when this will hit github.com?

**Comment by lildude** [comment]
When I build the next release gem and create & merge the PR that updates github.com 😁.  I've merged in quite a few things today and am waiting on a few nudges, so it'll probably be early next week before I even start.

One thing is for sure: it'll be before 9 May.

**Pull request merged**
