### PR TITLE
Add solidity language

### PR DESCRIPTION
**Pull request by oktapodia**
The main reason there's still no Solidity syntax highlighting on GitHub is that the `.sol` extension is too generic.

Then, following [this thread](https://github.com/ethereum/solidity/issues/2681#issuecomment-355277311), having the extension `.solidity` for now and use the `.gitattributes` file to set manually the `.sol` extension on our side is the easiest way for now
  
Current public usage is over 400k hits, see [here](https://github.com/search?utf8=%E2%9C%93&q=extension%3Asol+NOT+nothack&type=Code) and [here](https://github.com/search?utf8=%E2%9C%93&q=extension%3Asolidity+NOT+nothack&type=Code)

Solidity is actively developed, used to manage the ethereum smart contract and it has been published by [Ethereum](https://github.com/ethereum).
  
Closes #3755 as superceded. PR #3755 fails CI due to a color proximity warning.
The [sample file](https://github.com/OpenZeppelin/zeppelin-solidity/blob/b50391862c42857e3ff2388598e52ebab92fc9fa/contracts/crowdsale/RefundVault.sol) comes from OpenZeppelin and is licensed under the [MIT license](https://github.com/OpenZeppelin/zeppelin-solidity/blob/b50391862c42857e3ff2388598e52ebab92fc9fa/LICENSE). The file has been edited to reflect the fact.

### CODE REVIEW

**Comment by oktapodia** [comment]
Fix https://github.com/ethereum/solidity/issues/2681

**Comment by oktapodia** [comment]
@pchaigno can you review it, please?

**Comment by veox** [comment]
Note that this PR (#3973) is the 7th in the Solidity series.

PR #3755 is the 6th. PR #3560 was the 5th, and has a reference for earlier ones.

> * ethereum/solidity#2681 hasn't been merged. Has the proposal been accepted by the upstream project?

No, it hasn't been accepted, neither by the team maintaining the compiler, [nor the community at large](https://github.com/search?utf8=%E2%9C%93&q=extension%3Asolidity+NOT+nothack&type=Code). (As a social-first approach to issue resolution, it may never come to fruition; and that is fine.)

> * On the topic of syntax highlighting... you've not added a syntax highlighting grammar.

One is [already present in `.gitmodules`](https://github.com/github/linguist/blob/bee7e5561849055cd2f9c0a88c6b6b1a1b8e792b/.gitmodules#L784) (link to current `master` HEAD) - `davidhq/SublimeEthereum`. See PR #3161 (the grammar was added manually).

**Comment by oktapodia** [comment]
Thanks for your answer

* Sorry about the description, I updated it!
* I based my pull request on is fork, then rebased, then pushed into my repository (I could not update his PR because I don't have a write access to his repository)

@veox already answered many of your questions and I think the syntax highlighter is already [here](https://github.com/github/linguist/blob/master/grammars.yml#L117)

**Comment by oktapodia** [comment]
I added a comment to ask one of the solidity member to approve it [here](https://github.com/ethereum/solidity/issues/2681#issuecomment-356327070)

**Comment by veox** [comment]
@oktapodia The sample you've included is [from ethereum/solidity](https://github.com/ethereum/solidity/), which [falls under GPLv3](https://github.com/ethereum/solidity/blob/develop/LICENSE.txt) AFAIK. 

May I suggest something [from OpenZeppelin/zeppelin-solidity](https://github.com/OpenZeppelin/zeppelin-solidity/), which is [under an MIT license](https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/LICENSE)?.. In particular, OZ token implementations are quite rampant.

**Comment by oktapodia** [comment]
@veox sure, send me the link of the example you prefer and I will add it :)

**Comment by lildude** [comment]
> One is already present in .gitmodules (link to current master HEAD) - davidhq/SublimeEthereum.

Ah, I missed that as it isn't currently referenced in the `vendor/README.md`, but this PR now updates that. 🙇.

**Comment by veox** [comment]
@oktapodia You have previously included [a `RefundVault.sol` from OZ](https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/crowdsale/RefundVault.sol), which IMO is a good fit.

(The file does not have a license header, so you'll need to include a statement in the OP.)

**Comment by oktapodia** [comment]
@veox Done

**Comment by veox** [comment]
@oktapodia It would be nice if you addressed @lildude's points in the PR summary. Adding something like:

> * Closes #3755 as superceded. PR #3755 fails CI due to a color proximity warning.
> * The sample file comes from OpenZeppelin [link-to-file-at-commit] and is licensed under the MIT license [link-to-license-at-same-commit]. The file has been edited to reflect the fact.

Link helper: [`RefundVault.sol`](https://github.com/OpenZeppelin/zeppelin-solidity/blob/b50391862c42857e3ff2388598e52ebab92fc9fa/contracts/crowdsale/RefundVault.sol) and [`LICENSE`](https://github.com/OpenZeppelin/zeppelin-solidity/blob/b50391862c42857e3ff2388598e52ebab92fc9fa/LICENSE).

**Comment by veox** [comment]
@oktapodia The blob links I've suggested are for the latest current `RefundVault.sol`. The file included as part of this PR seems to be for an earlier version.

**Comment by veox** [comment]
@lildude:

The two most pressing issues from your list - lack of license statement for the sample file, and missing reference to existing PR - have been addressed in the PR summary.

The rest have been addressed in comments.

**Comment by lildude** [comment]
> The two most pressing issues from your list - lack of license statement for the sample file, and missing reference to existing PR - have been addressed in the PR summary.
> 
> The rest have been addressed in comments.

Perfect! Thanks. I really appreciate your work.

I prefer to give my final sign off once one of the non-GitHub maintainers has reviewed and given their approval.

**Comment by oktapodia** [comment]
Thanks @veox for your help!

**Comment by lildude** [comment]
Approving now so when @pchaigno or @Alhadis get around to reviewing, they can merge without waiting for me to unblock things.

**Comment by pchaigno** [comment]
@lildude Not sure if you've seen this and decided it was ok, or not---The `.solidity` extension has only [40 files on github.com](https://github.com/search?utf8=%E2%9C%93&q=extension%3Asolidity+NOT+nothack&type=Code). Given the extension, it's unlikely to conflict with another, but it's still a new extension. The alternative would be to add Solidity without any extension for now.

**Comment by oktapodia** [comment]
Thanks for your answer@pchaigno.

That will be possible with your solution to manually set the language into the `.gitattributes` file?

**Comment by pchaigno** [comment]
> That will be possible with your solution to manually set the language into the .gitattributes file to enable the syntax highlighter?

Yes, that would still enable manual override to Solidity.

**Comment by oktapodia** [comment]
Ok, do you want me to remove the extension in my pull request and then, we could merge it? (The pull request will be similar to the other one but with the test fixed :/ apologies @frangio)

**Comment by lildude** [comment]
@pchaigno Yeah, I saw that. I went with making an exception for this case as we'd already agreed to allow it without an extension and it seemed simpler to implement than the extension-less attempt from a quick glance at https://github.com/github/linguist/pull/3755.

I've now experimented and looked more closely and I realise I was wrong about implementing it without an extension... provided we don't include any samples or fixtures, it'll do the trick.

@oktapodia Yup:

```
$ cat .gitattributes
*.sol linguist-language=Solidity
$ ls -l
total 8
-rw-r--r--  1 lildude  staff  13 12 Jan 14:05 foo.sol
$ ../oktapodia-linguist/bin/linguist
100.00% Solidity
$
```

I retract my approval 😄  Thanks for encouraging me to rethink it @pchaigno 🙇 .

@oktapodia can you please remove the extension and samples.

**Comment by oktapodia** [comment]
Ok @lildude do you want me to move back the samples into the `test/fixtures` folder either?

**Comment by veox** [comment]
@oktapodia I'd guess no - see one comment earlier:

> provided we don't include any samples or fixtures, it'll do the trick.

**Comment by oktapodia** [comment]
I'm asking for a double check because this is against this comment:
"The two `.solidity` files need to be moved to samples. The previous suggestion of moving them to test/fixtures was because that PR was attempting to add support for Solidity without an extension. This PR is providing support with an extension so normal locations apply."

**Comment by oktapodia** [comment]
Ok then this is done

**Comment by pchaigno** [comment]
Thank you @oktapodia, @veox, @frangio, @whitj00, @cjgdev, @LogvinovLeon, and all who worked on this for your patience!
With the next Linguist release you should be able to count and highlight your `.sol` files  (or any other files for that matter) as Solidity with the following in a `.gitattribute` file in your repository:
```
*.sol linguist-language=Solidity
```
I'm hoping we can improve the situation in the future and automatically classify `.sol`, `.solidity`, `.sold`, or `.solid` files.

**Comment by LefterisJP** [comment]
@pchaigno I suppose you mean `.gitattributes` and not `.gitattribute` right? At least manual [seems to suggest](https://www.git-scm.com/docs/gitattributes) plural

**Comment by pchaigno** [comment]
@LefterisJP Yes, exactly! I fixed the above comment.

**Comment by LefterisJP** [comment]
@pchaigno Just to check if I understand correctly. If in a repository some files gets highlighted but some don't then it's not a github or linguist problem but a problem of the underlying grammar that is used? In our case the SublimeEthereum repo?

**Comment by lildude** [comment]
Normally yes, but in the case of the file you've pointed out in https://github.com/davidhq/SublimeEthereum/issues/21, I think this may be a caching issue on GitHub's side as Lightshow does highlight it correctly: [see me](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=source.solidity&grammar_format=auto&grammar_url=&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Flildude%2Fraiden%2Fmaster%2Fraiden%2Fsmart_contracts%2FStandard_Token.sol&code=) and GitHub is correctly identifying the language as Solidity.

I forked the repo and saw the same issue in my fork, but found simply [adding a space](https://github.com/lildude/raiden/commit/3eaf5e231b0efe6d0bef1fc100576516e201d2bc) and updating the file was sufficient to get GitHub to update the highlighting: https://github.com/lildude/raiden/blob/master/raiden/smart_contracts/Standard_Token.sol

Removing that space then re-introduced the lack of highlighting.

Try it for yourself.

It's probably worth logging a ticket with our support team to look into the caching issue as I'm not sure why this is happening. Our support folks will be able to refer to the peeps more au fait with that side of things.

**Comment by LefterisJP** [comment]
Oh thanks for the lightshow link. Did not know how to test the grammar for myself. This will make it easier to determine where the fault lies. When you say log an issue with your support team I suppose you mean opening a ticket in github?

**Comment by lildude** [comment]
> When you say log an issue with your support team I suppose you mean opening a ticket in github?

Yup. Hit the "Contact GitHub" link at the bottom of any page on GitHub.com.

**Comment by postables** [comment]
Does this seemingly not work at random times for anyone else? In some of my repositories files with the .sol extension that are most definitely solidity source code files don't get highlighted

**Comment by pchaigno** [comment]
@postables [In case you missed it](https://github.com/github/linguist/pull/3973#issuecomment-357507741), you need to explicitly tell Linguist to classify `.sol` files as Solidity. If you already tried that and it didn't work, please open an issue (make sure to fill out the issue template) and we'll look into it.

**Comment by veox** [comment]
@postables If it doesn't work even with a `.gitattributes`, do try pushing a commit that touches one of these files first. (This helps at least with language detection in the "language bar".)

**Comment by asymmetric** [comment]
I can't see the highlights (anymore? not sure) even on [files in repos](https://github.com/makerdao/dss/blob/8ae9a4489a0849d06d159efd2428a9adb4213fc4/src/vat.sol) that have the special [linguist configuration set](https://github.com/makerdao/dss/blob/8ae9a4489a0849d06d159efd2428a9adb4213fc4/.gitattributes). These files have been written to a lot since the configuration was set so I don't think @veox's [comment](https://github.com/github/linguist/pull/3973#issuecomment-383326684) would help.

Has something changed?

**Comment by lildude** [comment]
> Something to do with the recent release?

Oooof, yes. 

I released Linguist v7.2.0 this morning which included an update to all grammars including SublimeEthereum which is used for Solidity highlighting, but now I look at it, I can [see the problem](https://github.com/github/linguist/pull/4408/files#diff-130afe32a5902f82b34dd031e38a3564):

screenshot 2019-02-08 at 13 25 43

The grammar has switched from a TextMate compatible grammar to a Sublime Text compatible grammar - Linguist does _not_ support `.sublime-syntax` grammars: 

https://github.com/github/linguist/blob/e4560984058b4726010ca4b8f03ed9d0f8f464db/tools/grammars/compiler/loader_fs.go#L18-L23

This wasn't picked up when I built the release because unsupported formats are silently ignored as many grammars include both Sublime and TextMate compatible grammars.

**Comment by veox** [comment]
The last tagged release of `davidhq/SublimeEthereum` to have `.tmLanguage` is [`v1.0.3`](https://github.com/davidhq/SublimeEthereum/tree/v1.0.3).

Ping @davidhq: see comment above: `.sublime-syntax` is not supported. Will also open issue in the repo.

**Comment by veox** [comment]
@lildude Are there any other grammars besides Solidity that are now silently failing?..

`sublimehq/Packages`, for example, seems to have [converted everything it had to `.sublime-syntax`](https://github.com/sublimehq/Packages/commit/585e986e926be96c1d1bd886497cc0f409097c51); luckily, that repo is not listed in [`linguist`'s `.gitmodules`](https://github.com/github/linguist/blob/master/.gitmodules).

**Comment by lildude** [comment]
> @lildude Are there any other grammars besides Solidity that are now silently ignored?..

I've just double-checked and it's not actually failing silently... it's just lost in the other noise caused by the many known grammar issues as documented in https://github.com/github/linguist/issues/3924 which we ignore.

Running it again, I've just spotted:

```
- [ ] repository `vendor/grammars/SublimeEthereum` (from https://github.com/davidhq/SublimeEthereum.git) (1 errors)
    - [ ] Missing scope in repository: `source.solidity` is listed in grammars.yml but cannot be found
```

Looking through that output, no other grammars are reporting this that are not already known, so I don't think anything else has slipped past.

**Comment by davidhq** [comment]
Hi, I couldn't figure out if Linguist supports .sublime-syntax or not and indeed I removed .tmLanguage and was waiting for a report like this one :/ sorry about that... we can solve as you suggest - both options... what would be the best? I'd rather not add it back to master because of possible confusion... you suggested branch "linguist" in SublimeEthereum repo, I created it: https://github.com/davidhq/SublimeEthereum/tree/linguist ... does this remedy the issue for now?

**Comment by davidhq** [comment]
of course .tmLanguage was removed because of rewrite... also wasn't sure if all versions of SublimeText would pick up the correct syntax if both were included... 

let me know if for now I can help with anything else

**Comment by davidhq** [comment]
PS: https://github.com/davidhq/SublimeEthereum/issues/29 ← any tips here would be welcome

**Comment by pchaigno** [comment]
@lildude Should we do a quick release to fix this?

**Comment by lildude** [comment]
> @lildude Should we do a quick release to fix this?

I'll try squeeze it in sometime this week.

**Comment by davidhq** [comment]
@lildude .sol still broken

**Comment by lildude** [comment]
> @lildude .sol still broken

Still haven't had time to make a new release 😉

**Comment by dmdque** [comment]
I'm hoping you can get it in soon, since it's making reading Solidity code difficult across all projects in the Ethereum ecosystem.

**Comment by dmdque** [comment]
I noticed both PRs were merged 🎉 but syntax highlighting is still broken. Any idea when the changes will take effect?

**Comment by lildude** [comment]
@dmdque same as usual... when I make a release 😀. As you've seen, I've been working on a few improvements this week related to the grammar compiler so unexpected upstream changes outside of the control of Linguist are less likely to slip through the net in future. I'm not quite finished, but when I am, I'll make a release. My aim is for next week.

**Comment by davidhq** [comment]
I would say this is great ;) In fact I expected this to already be the case and that it would be impossible to break syntax over entire GitHub... Resilience is very important.

When it's finished and in particular the solidity syntax is back online, we can perhaps talk some more on how to bring separate project branch linguist will (?) be using more up to date with latest version which is improving every day - one that uses stack based `.sublime-syntax`... If this is not planned to be supported inside linguist anytime soon, I will update the linguist branch with as many recent changes as I can but I won't be able to do a perfect job just with regexes :/ As said: debate for a bit later, for now the priority should rightfully be to improve your release mechanism and point linguist to the `linguist` branch of SublimeEthereum project.

**Pull request merged**
