### PR TITLE
Add sproto language

### PR DESCRIPTION
**Pull request by m2q1n9**
Add [sproto](https://github.com/cloudwu/sproto) new language syntax highlighting support.
see also:
https://github.com/m2q1n9/atom-sproto-syntax
https://github.com/m2q1n9/sproto-mode

### CODE REVIEW

**Comment by pchaigno** [comment]
There are only [36 `.proto` files on GitHub](https://github.com/search?utf8=%E2%9C%93&q=extension%3Asproto+NOT+djfhdkfhdjf). It will probably not meet the [requirements](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language) yet.

**Comment by m2q1n9** [comment]
Waitting more... How many at least? :)

**Comment by davidzchen** [comment]
From Linguist's [Contribution Guidelines](https://github.com/github/linguist/blob/master/CONTRIBUTING.md):

> In most cases we prefer that extensions be in use in hundreds of repositories before supporting them in Linguist.

**Comment by pchaigno** [comment]
> How many at least? :)

To add on @davidzchen's response, we can check again for the number of repositories when there are at least 1,000 `.proto` files. That usually does the trick.

**Comment by arfon** [comment]
I'm going to close this for now as `Sproto`'s usage doesn't currently meet our contribution guidelines. Feel free to re-open in the future @m2q1n9

**Pull request closed without merging**
