### PR TITLE
Add nearley language definition

### PR DESCRIPTION
**Pull request by Hardmath123**
Hi everyone! I added a language definition for the [nearley parser generator](http://github.com/Hardmath123/nearley). In particular, I

- [x] Added the definition in languages.yml; the extension does not conflict with any other language
- [x] Picked a distinct-enough color
- [x] Added a grammar (.tmLanguage), which is Unlicensed
- [x] Added a large sample `.ne` file
- [x] Added a language ID using the script
- [x] Ran the tests; all pass on my machine

Here is a [search result](https://github.com/search?utf8=✓&q=extension%3Ane+NOT+nothack&type=Code) showing around 4.9k nearley files "in the wild". In addition, the [nearley homepage](https://nearley.js.org) explicitly curates 50 nearley-based projects, all hosted on Github.

Please let me know if there's anything else I need to do. Thanks for your time!

(I'm going to CC the other nearley maintainer, @tjvr.)

EDIT: I also accepted the CLA for github/linguist.

### CODE REVIEW

**Comment by Hardmath123** [comment]
Thanks for the review, Paul!

May I ask what the timeline for merging and deploying the changes would be? No rush, of course — I'm just curious/excited. :-)

**Comment by lildude** [comment]
> May I ask what the timeline for merging and deploying the changes would be? No rush, of course — I'm just curious/excited. :-)

I bet. I'm always excited about seeing my first contribution to a project go live. Thanks for the great PR.

Well I've just merged so that answers that part 😄. 

Deployment to GitHub.com won't happen until I make the next release. There's no set frequency on that at the moment and tends to be determined on a "I think we've got enough changes for a new release", or "it's been a while, lets release" or "Ooops, something is broken, need a fix soon/ASAP" basis.

v5.2.0 was released a week ago so unless something major comes up, I don't anticipate another release until next month... probably about a week before the next release of GitHub Enterprise flies the coop.

**Comment by Hardmath123** [comment]
Fantastic! Looking forward to seeing it live, and thanks for all your help. :-)

**Comment by Alhadis** [comment]
Don't worry, we're **Nearley** there. ;)

(I apologise if somebody here has already made that pun, haha)

**Comment by Hardmath123** [comment]
Looks like this finally got pushed out! :D

However, the little language bar on top of repos containing .ne files (e.g. https://github.com/raymond-h/node-dmi) doesn't yet show any nearley sources… are there more steps I need to take to make that happen?

**Comment by Alhadis** [comment]
@Hardmath123 Those statistics are cached and get recalculate when new commits are pushed. =) Since that repository hasn't been updated since late 2014, the old result is still being displayed. You can force GitHub to reindex your repository by publishing any sort of trivial change.

**Comment by Hardmath123** [comment]
Aha! It worked! Thanks. :-)

**Pull request merged**
