### PR TITLE
Update list of popular languages

### PR DESCRIPTION
**Pull request by lildude**
## Description

As per the title, this updates the list of popular languages to those most popular today. The list was last updated over 6 years ago in https://github.com/github/linguist/pull/2207.

Fixes https://github.com/github/linguist/issues/4966

_Template removed as it doesn't apply_

### CODE REVIEW

**Review by Alhadis — APPROVED** [review]
I still long for the day when APL and Brainfuck make it to this list.

**Comment by sheerun** [comment]
DM?

**Comment by lildude** [comment]
Yes, I was surprised by that too. I have no idea why it's showing up as really popular.

**Comment by sheerun** [comment]
maybe it's bug. syntax is similar to c++

**Comment by Alhadis** [comment]
The 'hell is DM?

**Comment by lildude** [comment]
Possibly, though it is a language Linguist supports and has for a very very long time.  The extension is incredibly popular too so I can only think there's a renaissance or something has started using the `.dm` extension and peeps are happy with the syntax highlighting and identification. 🤷

**Comment by pietroppeter** [comment]
is this true about DM language being really popular? I do not see many repos using DM: https://github.com/search?q=language%3Adm

I did see 1 example of a Markdown only repo marked as DM (because of a wrongly named extension) but I am not sure how many more there could be of those: https://github.com/EBB26/datasciencecoursera

also, what is the use of this list of popular languages?

**Comment by PJB3005** [comment]
In case anybody is curious: DM is the language used by the BYOND game engine which hosts Space Station 13, which is open source and one of the forks was #7 most commented on all of GitHub in 2017. 

Just figured I should say that because we just found out about this PR and we're all laughing our asses off about the confusion in here.

**Pull request merged**
