### PR TITLE
Set interpreters for Julia

### PR DESCRIPTION
**Pull request by JoshCheek**
Eg [this](https://github.com/JoshCheek/language-sampler-for-fullpath/blob/b766dcdbd249ec63516f491390a75315e78cba95/julia/fullpath#L1) file is not currently highlighted.

### CODE REVIEW

**Comment by Alhadis** [comment]
You'll need to accept the [GitHub Contributor License Agreement](https://cla.github.com/github/linguist/accept/JoshCheek) before a pull request can be accepted, mate. :-) Think of it as like an EULA.

**Comment by pchaigno** [comment]
Thanks for the pull request @JoshCheek!

Could you add the file you linked to as a sample in `samples/Julia/filenames/`?

**Comment by JoshCheek** [comment]
@pchaigno does it go under filenames? That looks like it matches up with the filenames key. Eg [these](https://github.com/github/linguist/tree/39ea9be5f8aa96e4dab10567feb26b799a35af0a/samples/Ruby/filenames) are the entries for Ruby, and [these](https://github.com/github/linguist/blob/39ea9be5f8aa96e4dab10567feb26b799a35af0a/lib/linguist/languages.yml#L3508-L3526) are Ruby's `filenames` entries. Ruby has entries in its main samples dir for the [`ruby` shebang](https://github.com/github/linguist/blob/39ea9be5f8aa96e4dab10567feb26b799a35af0a/samples/Ruby/ruby#L1), the [`jruby` shebang](https://github.com/github/linguist/blob/39ea9be5f8aa96e4dab10567feb26b799a35af0a/samples/Ruby/shoes-swt#L1), the [`macruby` shebang](https://github.com/github/linguist/blob/39ea9be5f8aa96e4dab10567feb26b799a35af0a/samples/Ruby/macruby#L1), and others.

So, based on their naming, it seems like I should put it in something like `samples/Julia/julia`, or a name that would make more sense to me as someone w/o project familiarity would be `samples/Julia/julia-shebang` or `samples/Julia/julia-interpreter`.

Also, do you want me to put the entirety of the file in there?

**Comment by pchaigno** [comment]
> So, based on their naming, it seems like I should put it in something like `samples/Julia/julia`, or a name that would make more sense to me as someone w/o project familiarity would be `samples/Julia/julia-shebang` or `samples/Julia/julia-interpreter`.

Yes, you're absolutely right, my mistake.

> Also, do you want me to put the entirety of the file in there?

Yes. These files are used to train the Bayesian classifier as well as for certain tests. We try to keep the files as-is as much as possible.

**Comment by pchaigno** [comment]
@arfon I think this is ready to :ship:

**Pull request merged**
