### PR TITLE
Added a few Monkey2 examples 

### PR DESCRIPTION
**Pull request by DoctorWhoof**
These compile with the latest Monkey2 release (V1.1.06).

Don't know how to add a Public Domain license, but I made those from scratch so, yes, they're public domain.

### CODE REVIEW

**Comment by lildude** [comment]
Can you please merge master into your branch so we can see if that allows the build to pass. We need it to pass before we can merge this PR.

**Comment by lildude** [comment]
Friendly nudge.

**Comment by lildude** [comment]
Nudgy nudge nudge @DoctorWhoof - we won't merge this until all tests are green which won't happen until you update your fork with the master branch from linguist.

**Comment by pchaigno** [comment]
@lildude Looks like a Travis-CI rerun was enough. Good to merge for me!

**Pull request merged**
