### PR TITLE
Remove Text filenames with insufficient usage

### PR DESCRIPTION
**Pull request by Nixinova**
## Description

Removes `test.me` filename as it only had [228 files](https://github.com/search?q=filename%3Atest.me+extension%3Ame&type=Code) on GitHub, of which only [110 are relevant](https://github.com/search?q=filename%3Atest.me+extension%3Ame+language%3Atext&type=Code)

Also removes a duplicate filename entry.

The other entries should be investigated for usage.

### Filenames checked for usage:
search query e g. `filename:read.me language:text extension:me`
  - [x] = removed in this PR
  - [ ] :+1: duh COPYING
  - [ ] ❗ 66 COPYING.regex
  - [ ] :+1: 2.4K COPYRIGHT.regex
  - [ ] ❗ 90 FONTLOG
  - [ ] :+1: duh INSTALL
  - [ ] ❗ 22  INSTALL.mysql
  - [ ] :+1: duh LICENSE
  - [ ] ❗ 52 LICENSE.mysql
  - [ ] :+1: duh NEWS
  - [x] ➖ README.1ST
  - [ ] :+1: 2.5K README.me
  - [ ] ❓ 316 README.mysql
  - [ ] ❗ 22 README.nss
  - [ ] :+1: 3.6K click.me
  - [ ] :+1: 6.9K delete.me
  - [ ] ❓580 keep.me
  - [ ] :+1: 1.9K package.mask
  - [ ] :+1: 1.1K package.use.mask
  - [ ] ❗ 173 package.use.stable.mask
  - [ ] :+1: 7K read.me
  - [ ] :+1: 1.6K readme.1st
  - [x] ❗ 110 test.me
  - [ ] ❔ 830 use.mask - [search throws a fit though][usedotmask]
  - [ ] ❗ 162 use.stable.mask - ditto

## Checklist:

- [x] **I am associating a language with a new file extension.**

- [x] **I am adding new or changing current functionality**
  
  - [ ] I have added or updated the tests for the new or changed functionality.

[usedotmask]: https://github.com/search?q=filename%3Ause.mask+language%3Atext+extension%3Amask+-filename%3Apackage.use.mask+-filename%3Ause.stable.mask+-filename%3Apackage.use.stable.mask&type=Code

### CODE REVIEW

**Comment by Alhadis** [comment]
I automatically recognised [README.nss](https://github.com/github/linguist/pull/5064) and [COPYRIGHT.regex](https://github.com/github/linguist/pull/3441/files#diff-9c337ec09ccaaa1374713aad9ba26cdc1308586a27cb309a883a0b19bde663d8R4312) as my handiwork; note that running

~~~console
$ git blame -L 6033,6074 lib/linguist/languages.yml
~~~

may expedite review of the other filenames.

**Comment by Nixinova** [comment]
I recall seeing most of them are tagged as "6 years ago" while removing the go.mod filenames.

Here's the git blame:





Un-PR'd commit is https://github.com/github/linguist/commit/b032886c21d8397ca0be56fa91b5454e2f16d7c1

**Comment by Nixinova** [comment]
Went through all of them, ❗= not enough, ❓ = possibly not enough

**Comment by Nixinova** [comment]
Alright

**Pull request closed without merging**
