### PR TITLE
Create xojo.JSON-tmLanguage

### PR DESCRIPTION
**Pull request by ArturViader**
Xojo is very similar to vbnet. Codehighlight works with ```vbnet. But when you add a WHILE WEND bucle on the code highlight disappears.
This is for try fix this.

### CODE REVIEW

**Comment by pchaigno** [comment]
Grammars are usually hosted in their own repositories. I don't know if it's okay to keep it directly in Linguist...

/cc @bkeepers @arfon

**Comment by bkeepers** [comment]
@ArturViader Thanks for the contribution! As @pchaigno suggets, we'd like to keep the grammars in their own repositories so that people can reuse them in their editors.

Would you be interested in pushing the grammar to a new repository, and then following the [docs on adding a grammar](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#i-want-to-add-support-for-the-x-programming-language)?  Thanks!

**Comment by arfon** [comment]
:flags: as stale. @ArturViader - do you think you can do as @bkeepers asked above?

**Comment by arfon** [comment]
Please feel free to open another PR if this is still something you're interested in working on.

**Pull request closed without merging**
