### PR TITLE
Update languages.yml

### PR DESCRIPTION
**Pull request by kirillDanshin**
Improved PHP detection (not tested yet)

### CODE REVIEW

**Comment by arfon** [comment]
Please take a look at these contributing guidelines for these new extensions: https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language

**Comment by kirillDanshin** [comment]
@arfon where did I go wrong?

**Comment by arfon** [comment]
@kirillDanshin could you link to some [search results](https://github.com/search/advanced) showing that these are widely used extensions for PHP?

Also, for good housekeeping could you please add a sample file for each of these extensions?

**Comment by arfon** [comment]
:flags: flagging this as stale :flags:

**Pull request closed without merging**
