### PR TITLE
Add test to keep grammar-list synced with submodules

### PR DESCRIPTION
**Pull request by Alhadis**
We're constantly forgetting to update [`vendor/README.md`](https://github.com/github/linguist/blob/grammar-list-test/vendor/README.md) whenever we add or change a grammar, and it's no wonder why. The [`script/add-grammar`](https://github.com/github/linguist/blob/4fd1dd7f6cf3934a704f36a9120e2d856f3e0821/script/add-grammar#L104) tool is the only thing that's currently updating the list at the moment... and it doesn't even get used that often.

This PR adds a test to make sure the list stays updated with submodule removals or additions.

**References:** #3192, #3307

### CODE REVIEW

**Comment by lildude** [comment]
@Alhadis CI should start passing once you pull the current linguist/master into your branch.

**Comment by Alhadis** [comment]
All done!

Bye bye, `byebug` bug!

**Comment by lildude** [comment]
What's the problem with the punctuation that necessitates stripping off the full stops?

**Comment by Alhadis** [comment]
Oh! Sorry, should have explained that... it's just a minor (read: completely pedantic) polish to remove the double full-stop that's appended to some error messages. Since the `minitest` gem's methods automatically add a full-stop to the end of an error message...

**Pull request merged**
