### PR TITLE
Update URL for AutoHotkey grammar

### PR DESCRIPTION
**Pull request by pchaigno**
The grammar for AutoHotkey moved from [robertcollier4/AutoHotkey](https://github.com/robertcollier4/AutoHotkey) to [ahkscript/AutoHotkey](https://github.com/ahkscript/AutoHotkey).

/cc @robertcollier4

### CODE REVIEW

**Comment by arfon** [comment]
@pchaigno - would you mind updating this so we have a clean merge with master?

**Comment by pchaigno** [comment]
@arfon Done.

**Comment by arfon** [comment]
:+1: thanks!

**Comment by robertcollier4** [comment]
Seems like the location has changed again, it is now https://github.com/ahkscript/SublimeAutoHotkey - this should be the final location

**Comment by pchaigno** [comment]
@robertcollier4 I'll make a PR to update it. Is the discussion about changing the location public somewhere?

**Comment by robertcollier4** [comment]
Yes, the location for the repo was changed due to this discussion:
https://github.com/ahkscript/SublimeAutoHotkey/issues/15

**Pull request merged**
