### PR TITLE
Add file extensions for Raku according to current conventions: https:…

### PR DESCRIPTION
**Pull request by ash**
Adding .raku, .rakumod, .rakutest, and .rakudoc as they are present-days standard extensions for Raku

## Description
The languages.yml file already has an entry for Raku, but for some reason, the current extensions were not added there. There is a lis of official extensions at https://github.com/Raku/problem-solving/blob/master/solutions/language/Path-to-Raku.md#extensions

## Checklist:

- [x] **I am associating a language with a new file extension.**
  - [ ] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      
      - https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am adding a new language.**
  - [ ] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  
  - [ ] I have included a syntax highlighting grammar: https://github-lightshow.herokuapp.com/
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

- [ ] **I am fixing a misclassified language**
  - [ ] I have included a new sample for the misclassified language:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am changing the source of a syntax highlighting grammar**
  
  - Old: https://github-lightshow.herokuapp.com/
  - New: https://github-lightshow.herokuapp.com/

- [ ] **I am updating a grammar submodule**
  

- [ ] **I am adding new or changing current functionality**
  
  - [ ] I have added or updated the tests for the new or changed functionality.

- [ ] **I am changing the color associated with a language**
  
  - [ ] I have obtained agreement from the wider language community on this color change.
    - [URL to public discussion]
    - [Optional: URL to official branding guidelines for the language]

### CODE REVIEW

**Review by lildude — CHANGES_REQUESTED** [review]
> The languages.yml file already has an entry for Raku, but for some reason, the current extensions were not added there.

The reason they weren't added was because the general usage on GitHub.com didn't meet the documented requirements at the time. See https://github.com/github/linguist/pull/4731#discussion_r359659357

If any of these extensions now meet the "hundreds of repos" requirement... ie more than 200 unique user/repos for each, please add a real-world sample for each new extension and then update the template with search results for each new extension and link to the source of each sample and state the license for each sample, ie fill in the fields in the first section of the template... we need more than just the boxes ticked 😉

**Comment by raiph** [comment]
How do you search to see how many users are using an extension?

I tried using the search link included in the checklist but the result page for me for https://github.com/search?q=extension%3Arakumod+NOT+nothack&type=Code looks like nonsense, listing 63m users on the left, but only 3K matches / 100 pages.

I've searched the github doc pages on search and do not understand what I'm doing wrong or if the search is (currently?) borked.

**Comment by codesections** [comment]
@raiph
> How do you search to see how many users are using a [file] extension?

From the linked issue, my understanding is that GitHub's interactive web search does not display these results; the issue mentions using [Alhadis/Harvester](https://github.com/Alhadis/Harvester) to determine the counts, which is significantly slower.

Using that tool, I produced the following updated counts:

*    `.raku`: 2,068 files, 287 repos, 152 users
*    .rakumod: 2,065 files, 250 repos, 87 users
*    .rakutest: 325 files, 77 repos, 30 users

[The policy](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-an-extension-to-a-language) states

> We try only to add languages once they have some usage on GitHub. In most cases we prefer that each new file extension be in use in hundreds of repositories before supporting them in Linguist.

So it looks like `.raku` and `.rakumod` are both well over the "hundreds of repos" threshold.  I suppose that means it's time to move on to the other steps @lildude outlined above?

**Comment by lildude** [comment]
Closing in favour of https://github.com/github/linguist/pull/5168 as it's ready to go and I'm starting to get things in order for a new release.

**Pull request closed without merging**
