### PR TITLE
Add TSV data language

### PR DESCRIPTION
**Pull request by sheerun**
## Description
Adds tsv data language

## Checklist:

- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
https://github.com/search?p=2&q=extension%3Atsv+id&type=Code
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
https://github.com/eBay/tsv-utils/blob/master/tsv-filter/tests/input4.tsv
    - Sample license(s):
https://github.com/eBay/tsv-utils/blob/master/LICENSE.txt
  - [ ] I have included a syntax highlighting grammar: https://github-lightshow.herokuapp.com/
Does not apply (the same as CSV)
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.
Does not apply

### CODE REVIEW

**Review by lildude — APPROVED** [review]
LGTM

**Comment by Alhadis** [comment]
[There's a grammar you can use for highlighting](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=cson&grammar_url=https%3A%2F%2Fgithub.com%2FAlhadis%2Flanguage-etc%2Fblob%2Fmaster%2Fgrammars%2Fgeneric-db.cson&grammar_text=&code_source=from-text&code_url=&code=%23%09name%09file%09start%09end%09size%09row%09column%09sha256%09%23+vim%3Ats%3D10%0D%0A1%09playSound%09test.mjs%0928%09129%09101%091%098%09d7c5302e404683fa36ab94bdf4cd9ddcccc38ac63dd44fa62c5b4aa845a4d10a%0D%0A), if you want it. It technically targets any tab- and newline-separated record file, and supports colon delimiters too.

Support is already there, just add `source.generic-db` to the entry's `tm_scope`.

**Comment by sheerun** [comment]
@Alhadis Should I also add it to CSV?

**Comment by Alhadis** [comment]
No, the grammar tokenises semicolons as fields, not separators.

Support for colons was added so files like `/usr/share/misc/birthtoken` could be highlighted:

~~~
# Birthday : Birth Stone : Birth Flower
#	@(#)birthtoken	8.1 (Berkeley) 6/8/93
January:Garnet:Carnation
February:Amethyst:Violet
March:Aquamarine:Jonquil
April:Diamond:Sweetpea
May:Emerald:Lily Of The Valley
June:Pearl:Rose
July:Ruby:Larkspur
August:Peridot:Gladiolus
September:Sapphire:Aster
October:Opal:Calendula
November:Topaz:Chrysanthemum
December:Turquoise:Narcissus
~~~

It's a fairly common choice of delimiter when whitespace can't be used (probably due to its use in `$PATH` and `$PATH`-like environment variables...

**Comment by sheerun** [comment]
@Alhadis OK it's updated now

**Comment by sheerun** [comment]
um... sec

**Comment by sheerun** [comment]
ok now

**Review by Alhadis — APPROVED** [review]

**Pull request merged**
