### PR TITLE
Add support for Promela

### PR DESCRIPTION
**Pull request by ishowta**
## Checklist:
- [x] **I am adding a new language.**
	- [x] **The extension of the new language is used in hundreds of repositories on GitHub**
		- [~53,535 search results](https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3Apml+NOT+nothack)
	- [x] **I have included real-world usage samples in this PR:**
		* [`attacker_4_FINITE.pml`](https://github.com/maxvonhippel/AttackerSynthesis/blob/f027e77005c72d253d527eb03de8c737e0baeda5/results/experiment1/with/experiment1_4_True_True/attacker_4_FINITE.pml): [MIT](https://github.com/maxvonhippel/AttackerSynthesis/blob/6b08d73de6f5c1c2cfe914a28b40212b4657ba7e/LICENSE)
		* [`bare_signals.pml`](https://github.com/n7space/sdl2promela/blob/3bce9079d23e3d81ff65eedf46887fead2e177e9/tests/translator/resources/bare_signals.pml): [GPL v3](https://github.com/n7space/sdl2promela/blob/fe8c1fd294edd9b76178b6d6112dd74798ffb185/LICENSE)
		* [`ex.1.pml`](https://github.com/dsvictor94/vscode-promela/blob/a2066406260b9aeaf796f53bc461084775846052/example/ex.1.pml): [MIT](https://github.com/dsvictor94/vscode-promela/blob/a2066406260b9aeaf796f53bc461084775846052/LICENSE)
		* [`TCP.pml`](https://github.com/maxvonhippel/AttackerSynthesis/blob/f027e77005c72d253d527eb03de8c737e0baeda5/demo/TCP/TCP.pml): [MIT](https://github.com/maxvonhippel/AttackerSynthesis/blob/6b08d73de6f5c1c2cfe914a28b40212b4657ba7e/LICENSE)
		* [`Thread.pml`, `Supervisor.pml`, `Session.pml`](https://gitlab.com/jllang/adapro/-/tree/master/models/promela): [Apache 2.0](https://gitlab.com/jllang/adapro/-/blob/master/LICENSE)
	- [x] **I have included a syntax highlighting grammar**  
		[Preview](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fgithub.com%2Fcorbanmailloux%2Fsublime-promela-spin%2Fblob%2Fmaster%2FSyntaxes%2FPromela.tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fdsvictor94%2Fvscode-promela%2Fa2066406260b9aeaf796f53bc461084775846052%2Fexample%2Fex.1.pml&code=)

### CODE REVIEW

**Review by lildude — CHANGES_REQUESTED** [review]
Usage looks widespread enough for inclusion, however your last two samples aren't examples of real-world representative usage of the language.

Please replace these with real-world files.

**Comment by Alhadis** [comment]
> Please replace these with real-world files.

@lildude I went and collected the samples for him, as it was particularly difficult to find real-world uses that weren't university coursework (and students hardly _ever_ elucidate the license of their assignments… given that that would be kinda weird and all…)

**Comment by ishowta** [comment]
I added the source code used in the paper that was linked from the official Promela website.

**Comment by Alhadis** [comment]
> I added the source code used in the paper that was linked from the official Promela website.

Can you confirm this was released under a license that permits redistribution? Though Linguist's licensing requirements are less strict for language samples than they are for grammars, we still need to assert that these samples aren't copyrighted (non-free) material.

**Comment by ishowta** [comment]
These source codes are under the Apache 2.0 license (added to the checklist).

[`Thread.pml`, `Supervisor.pml`, `Session.pml`](https://gitlab.com/jllang/adapro/-/tree/master/models/promela): [Apache 2.0](https://gitlab.com/jllang/adapro/-/blob/master/LICENSE)

**Comment by Alhadis** [comment]
@ishowta What do you think about using `#de0000` for the language colour? I couldn't find any logos or branding related to Promela at _all_, but the program it's interpreted by certainly does:

**Comment by ishowta** [comment]
I couldn't find the Promela logo either, but I think its color is good.

**Review by lildude — APPROVED** [review]

**Pull request merged**
