### PR TITLE
Add FreeCAD Macro language

### PR DESCRIPTION
**Pull request by Symbian9**
## Checklist:

- [ ] **I am associating a language with a new file extension.**
  - [ ] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      
      - https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s): 
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s): https://github.com/Symbian9/linguist/blob/patch-1/samples/FreeCAD%20Macro/legify-technic-pin.FCMacro
      - https://github.com/vectronic/freecad-legify-macros/blob/master/legify-technic-pin.FCMacro
    - Sample license(s): MIT
  - [ ] I have included a syntax highlighting grammar: [URL to grammar repo]
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

- [ ] **I am fixing a misclassified language**
  - [ ] I have included a new sample for the misclassified language:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am changing the source of a syntax highlighting grammar**
  - Old: [URL to grammar repo]
  - New: [URL to grammar repo]

- [ ] **I am updating a grammar submodule**
  

- [ ] **I am adding new or changing current functionality**
  
  - [ ] I have added or updated the tests for the new or changed functionality.

- [ ] **I am changing the color associated with a language**
  
  - [ ] I have obtained agreement from the wider language community on this color change.
    - [URL to public discussion]
    - [Optional: URL to official branding guidelines for the language]

### CODE REVIEW

**Comment by Symbian9** [comment]
A note for reviewers: I had not set `language_id:` just because can't run Ruby scripts myself on my PC.

So, requesting generating `language_id:` by reviewers and adding it into this pull request as additional edit.

**Comment by lildude** [comment]
> A note for reviewers: I had not set `language_id:` just because can't run Ruby scripts myself on my PC.
> 
> So, requesting generating `language_id:` by reviewers and adding it into this pull request as additional edit.

You need much more than just the `language_id` set. You've barely done anything in the steps of adding a language as so many other files that should be updated by the scripts haven't been updated. 

I'm afraid you're going to need to run these scripts yourself or get someone else in the FreeCAD community to do it for you.

If you have VSCode and Docker installed on your PC, you can use [Microsoft Remote Containers](https://code.visualstudio.com/docs/devcontainers/containers) to get a Linux dev env (The "Default Linux Universal" container works a treat as that's what is selected by default on Codespaces which I use all the time) in which you can run all the steps detailed in the CONTRIBUTING.md file. You can do this in [Codespaces](https://github.com/features/codespaces) too, and for free too.

But before go to the effort, I can tell you it's probably not worth it right now. From a very quick look, it looks like the `.FCMacro` extension doesn't meet our documented, nor temporarily relaxed, usage requirements so this PR wouldn't be accepted right away in any case.

**Review by lildude — CHANGES_REQUESTED** [review]
See previous comment

**Comment by Symbian9** [comment]
> get someone else in the FreeCAD community to do it for you.

OK, I will close it for now.

**Pull request closed without merging**
