### PR TITLE
Add Loli programming language

### PR DESCRIPTION
**Pull request by MWGuy**
Add Loli programming language https://github.com/loli-foundation/loli

## Checklist:
- [x] **I am adding a new language.**
   - [ ] The extension of the new language is used in hundreds of repositories on GitHub.com.
        - Search results for each extension:
             - li: <https://github.com/search?q=extension%3Ali+sayln&type=Code>

  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source:
      - <https://github.com/loli-foundation/loli-json-parser>
    - Sample license:
      - MIT

### CODE REVIEW

**Comment by TheMRLokopOff** [comment]
<3

**Comment by pchaigno** [comment]
@MWGuy Hi! There were other check boxes for "I am adding a new language". Could you please add them back? At least the sample one is mandatory.

**Comment by MWGuy** [comment]
@pchaigno fixed

**Comment by pchaigno** [comment]
Please check the contribution guidelines. You need to add the sample file in `samples/`.

**Comment by MWGuy** [comment]
@pchaigno added

**Comment by pchaigno** [comment]
Where's the second sample from? What's its license?

Also, your search query returns lots of files that don't appear to be Loli. Could you use some keywords specific to Loli to refine it?

**Comment by AlekSi** [comment]
https://github.com/loli-foundation/loli/issues/10

**Comment by funny-falcon** [comment]
Looks like original language is by other author:
https://github.com/FascinatedBox/lily
https://gitlab.com/FascinatedBox/lily

loli has very similar set of files and very close internal file content. Also it has very similar syntax. Very strange syntax decision `if condition : { then_statement ; else: else_statement }` could not be same by accident.

**Pull request closed without merging**
