### PR TITLE
File extension .me

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
Pulled out the `.me` changes from #2383 "More file extensions for Groff".

Some `.me` files are Groff.  Some are MakeMe.  Plenty are Text files like "read.me".

Discuss!

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
E.g are all [these filenames](https://github.com/larsbrinkhoff/linguist/blob/8436fe9643e4f75590e48fee663df706482ca6ab/lib/linguist/languages.yml#L3265-L3275) in the `Text` language ok?

**Comment by arfon** [comment]
Hey @larsbrinkhoff - just doing some housekeeping on Linguist. What's the status of this PR? There seems to be a bunch of filenames commented out here. Was that intentional?

**Comment by larsbrinkhoff** [comment]
@arfon, I asked about about those filenames.  I think `read.me` is quite clearly most likely a text file, as well as the usualy licensing files, but the other `.me` may be questionable.  It's your call.

**Comment by arfon** [comment]
> COPYING
> INSTALL
> LICENSE
> NEWS
> README
> click.me
> delete.me
> keep.me
> read.me
> readme.me
> test.me

This list looks good to me. Could you update the PR to include them (they look commented out right now)

**Comment by larsbrinkhoff** [comment]
@arfon Done.

I had to drop `README`, because it's hardcoded into `test_file_blob.rb` in so many places.

**Comment by arfon** [comment]
Closing in favour of #2873

**Pull request closed without merging**
