### PR TITLE
Add new extension .tsx for TypeScript

### PR DESCRIPTION
**Pull request by wizawu**
[TypeScript 1.6 has introduced a new .tsx file extension.](http://blogs.msdn.com/b/typescript/archive/2015/09/02/announcing-typescript-1-6-beta-react-jsx-better-error-checking-and-more.aspx)

Here is the [GitHub search result](https://github.com/search?utf8=%E2%9C%93&q=extension%3Atsx+React&type=Code&ref=searchresults).

### CODE REVIEW

**Comment by pchaigno** [comment]
@wizawu Could you please add a sample file in `samples/TypeScript` as per [the contribution guidelines](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-an-extension-to-a-language)?

Also, there seem to be [a lot of XML files on GitHub](https://github.com/search?utf8=%E2%9C%93&q=extension%3Atsx+xml&type=Code&ref=searchresults). Do you know what those are? Are they related to TypeScript?

**Comment by deathbeam** [comment]
`.tsx` are tileset files for [Tiled Map Editor](http://www.mapeditor.org/)

**Comment by pchaigno** [comment]
In that case, @wizawu could you also link to a search on GitHub showing as many examples of TypeScript `.tsx` files as possible?

**Comment by arfon** [comment]
> .tsx are tileset files for Tiled Map Editor

I think we're going to need to make sure we can correctly identify these two. Happy to provide some samples for analysis if that's useful, otherwise I will try and get to this later in the week.

**Comment by wizawu** [comment]
@pchaigno
I have updated the [sample](https://github.com/wizawu/linguist/blob/master/samples/TypeScript/app.tsx) and the [search result](https://github.com/search?utf8=%E2%9C%93&q=extension%3Atsx+React&type=Code&ref=searchresults).

I also have no idea about the _Tiled Map Editor_.

**Comment by pchaigno** [comment]
Thanks @wizawu!
Though, it's better if the sample is from a real application since it will be used to train the Bayesian classifier ;)

For Tiled Map Editor files, could you add `.tsx` to the list of extensions for XML along with a sample (you'll need to find one under an open source license)?

**Comment by wizawu** [comment]
@pchaigno 
I just added the `.tsx` to XML (along with the sample).

> Though, it's better if the sample is from a real application since it will be used to train the Bayesian classifier

As for this, I suggest you to try these files:
https://github.com/Microsoft/TypeScript/tree/master/tests/cases/conformance/jsx

**Comment by pchaigno** [comment]
> I just added the .tsx to XML (along with the sample).

Okay, great!

> As for this, I suggest you to try these files:
https://github.com/Microsoft/TypeScript/tree/master/tests/cases/conformance/jsx

Could you replace your current sample with [this one](https://github.com/Microsoft/TypeScript/blob/master/tests/cases/conformance/jsx/jsxReactTestSuite.tsx) (I chose based on the size, which seems correct. If you think there's a more representative file please use it)?

**Comment by wizawu** [comment]
I got one from searching "[declare module interface class React.component extension:tsx](https://github.com/search?utf8=%E2%9C%93&q=declare+module+interface+class+React.component+extension%3Atsx&type=Code&ref=advsearch&l=&l=)".

**Comment by arfon** [comment]
:+1: thanks folks.

**Comment by arfon** [comment]
This will be live in the next release of Linguist (hopefully later this week)

**Pull request merged**
