### PR TITLE
Release v7.24.0

### PR DESCRIPTION
**Pull request by lildude**
Time for a new release, just in time to squeeze into the next GitHub Enterprise release.

- [ ] Gem pushed to RubyGems & GitHub Package Registry 
- [ ] Deployed to GitHub.com
- [ ] Grammars deployed to Syntax highlighting service - highlighting won't be 💯 up-to-date until this happens

I'm also taking this opportunity to squash a regularly asked question with an addition to the troubleshooting docs and adding links to it in the contributing doc.

### CODE REVIEW

**Comment by lildude** [comment]
This is now live.

**Comment by adriens** [comment]
:bird:  [Tweeted](https://twitter.com/rastadidi/status/1592613195310825472)

**Comment by adriens** [comment]
Thanks a lot guys :pray:

**Review by Viiviagstna — COMMENTED** [review]
.

**Review by FELIXTHECAT420 — COMMENTED** [review]
Screenshot_20240407_165428_Chrome
Screenshot_20240407_165348_Chrome
Screenshot_20240407_162742_Chrome

**Comment by FELIXTHECAT420** [comment]
I should have no run ends getting access

**Comment by FELIXTHECAT420** [comment]
Please put 01ec327dd52cb48e23a9649ee27d70e836f6269d22be2eda514c9af55e270e82

As mine FelixTheCat22

**Comment by FELIXTHECAT420** [comment]
All funds go to FelixTheCat22 0x5dA1CD01B5d373b1B9Ca25d46660b51708D1dFc8

**Pull request merged**
