### PR TITLE
Support for Type Language

### PR DESCRIPTION
**Pull request by goodmind**
https://core.telegram.org/mtproto/TL
which used in [Telegram](telegram.org)

### Uses
https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/Resources/scheme.tl
https://github.com/vysheng/tgl/search?utf8=%E2%9C%93&q=extension%3Atl+NOT+nothack&type=

### Search results
https://github.com/search?utf8=%E2%9C%93&q=extension%3Atl+NOT+nothack&type=

It looks like extension `.tl` clashes with DustJS templates
https://github.com/linkedin/venus.js/blob/d84e8963e0c7a2c67436e3d7eb99476de0caabf9/.venus/templates/default.tl

### CODE REVIEW

**Comment by goodmind** [comment]
@pchaigno why this can't be merged?

**Comment by lildude** [comment]
@goodmind because I hadn't approved my request for changes yet and GitHub has an overriding authority on merges. Sorry about the delay. Will approve and merge now.

**Comment by goodmind** [comment]
@lildude How long it takes to the next release?

**Comment by lildude** [comment]
@goodmind I'm currently on holiday in 🇿🇦 and mostly using my iPad/phone to keep up to date as and when I fancy a bit of tech so it won't be until early July before I make the next release.

**Comment by goodmind** [comment]
@lildude ok. thanks

**Pull request merged**
