### PR TITLE
Add fontello CSS files to vendor.yml

### PR DESCRIPTION
**Pull request by sahildua2305**
- Added fontello.css with all it's possible(known) variants
- Added corresponding exhaustive tests

### CODE REVIEW

**Comment by pchaigno** [comment]
@sahildua2305 Thanks for the pull request!

It looks like `fontello.css` is sometimes accompanied by [other `fontello-*.css` files](https://github.com/alfredkam/PHYLO/tree/880f2d2e776e8ac62d28c194cb69f6119fe58e94/assets/css/icons/fontello/css) (for instance, [`fontello-ie7.css`](https://github.com/search?utf8=%E2%9C%93&q=filename%3Afontello-ie7.css&type=Code&ref=searchresults)). Is there a finite list of these extensions? Should we extend the regular expression to recognize those as well?

**Comment by sahildua2305** [comment]
@pchaigno Good point!

I am able to find these similar extensions:
- fontello.css
- fontello-ie7.css
- fontello-codes.css
- fontello-codes-ie7.css
- fontello-embedded.css
- fontello.eot
- fontello.svg
- fontello.ttf
- fontello.woff

Let me know if you find any more extension other than these.

[[Source]](https://github.com/fontello/fontello/tree/master/support/font-templates)

**Comment by arfon** [comment]
Looks good to me 👍

**Comment by sahildua2305** [comment]
@arfon @pchaigno Thanks!

Can you please point me to some 'easy pick' bugs/fixes so that I can get started with more code and start contributing significantly? :)

**Comment by arfon** [comment]
@sahildua2305 - this will be live on GitHub in the next couple of weeks with the next release of Linguist.

> Can you please point me to some 'easy pick' bugs/fixes so that I can get started with more code and start contributing significantly? :)

😻 it's always work looking through old issues, we sometimes don't clean those up very well. That said here are some that would love to see addressed:

- https://github.com/github/linguist/issues/3057 - basically we need to find all the obviously GPL-licensed sample files and swap them for ones with more permissive license (MIT, Apache-2, BSD)
- https://github.com/github/linguist/issues/3014 may be relatively straightforward

**Comment by sahildua2305** [comment]
@arfon Thanks for the pointers!

#3057 should be fairly easy one to get started. :smile:

**Pull request merged**
