### PR TITLE
Added grammar submodule for Red language

### PR DESCRIPTION
**Pull request by Oldes**

### CODE REVIEW

**Comment by arfon** [comment]
:+1: thanks fort this. It'll probably be another week before this is live on GitHub.com

**Comment by Oldes** [comment]
Fine.. it's there, but for example here is highlighted word *datatype!* which should not be.
https://github.com/red/red/blob/master/environment/datatypes.red#L32

The same code in my Sublime editor is correct and there should not be any magic in highlighting simple word, which is used many times in the code. So it's really strange.

Also, do you think it will be possible to support also different and more colors in near future? Current state does not look much colorized.

**Comment by arfon** [comment]
> Fine.. it's there, but for example here is highlighted word datatype! which should not be.
https://github.com/red/red/blob/master/environment/datatypes.red#L32

Sorry to hear this isn't looking great. You can test how a grammar is working using the [Lightshow app here](https://github-lightshow.herokuapp.com/) - I'm not sure if you've already done this?

**Comment by Oldes** [comment]
@arfon isn't possible, that you have some bug in lookbehind implementation? To me the rule looks correct and it's working fine in Sublime. I've created a [test here](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2FOldes%2FSublime-Red%2Fmaster%2FRed.JSON-tmLanguage&grammar_text=&code_source=from-text&code_url=&code=string%21%0D%0A+string%21++++%3B%3C----+this+one+is+wrong%21%0D%0Astring%21%0D%0A%5Bstring%21%5D%0D%0A%5B+string%21%5D++%3B%3C----+this+one+is+wrong%21%0D%0A%3Aboo%0D%0A+%3Aboo%0D%0A%0D%0A%0D%0A)

**Comment by arfon** [comment]
I'm not sure what's going on here sorry. I've created a demonstration of the problem using [Lightshow here](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2FOldes%2FSublime-Red%2Fmaster%2FRed.JSON-tmLanguage&grammar_text=&code_source=from-text&code_url=&code=Red+%5B%0D%0A%09Title%3A+++%22Red+base+environment+definitions%22%0D%0A%09Author%3A++%22Nenad+Rakocevic%22%0D%0A%09File%3A+%09+%25boot.red%0D%0A%09Tabs%3A%09+4%0D%0A%09Rights%3A++%22Copyright+%28C%29+2011-2013+Nenad+Rakocevic.+All+rights+reserved.%22%0D%0A%09License%3A+%7B%0D%0A%09%09Distributed+under+the+Boost+Software+License%2C+Version+1.0.%0D%0A%09%09See+https%3A%2F%2Fgithub.com%2Fdockimbel%2FRed%2Fblob%2Fmaster%2FBSL-License.txt%0D%0A%09%7D%0D%0A%5D%0D%0A%0D%0A%3B--+datatype%21+is+not+defined+here+for+obvious+circular+reference+issue%0D%0A%0D%0Aunset%21%3A%09%09%09make+datatype%21+%23get-definition+TYPE_UNSET%0D%0Anone%21%3A%09%09%09make+datatype%21+%23get-definition+TYPE_NONE%0D%0Alogic%21%3A%09%09%09make+datatype%21+%23get-definition+TYPE_LOGIC%0D%0Ablock%21%3A%09%09%09make+datatype%21+%23get-definition+TYPE_BLOCK%0D%0Astring%21%3A%09%09make+datatype%21+%23get-definition+TYPE_STRING%0D%0Ainteger%21%3A%09%09make+datatype%21+%23get-definition+TYPE_INTEGER%0D%0A%3Bsymbol%21%3A%09%09make+datatype%21+%23get-definition+TYPE_SYMBOL%0D%0A%3Bcontext%21%3A%09%09make+datatype%21+%23get-definition+TYPE_CONTEXT%0D%0Aword%21%3A%09%09%09make+datatype%21+%23get-definition+TYPE_WORD%0D%0Aerror%21%3A%09%09%09make+datatype%21+%23get-definition+TYPE_ERROR%0D%0Atypeset%21%3A%09%09make+datatype%21+%23get-definition+TYPE_TYPESET%0D%0Afile%21%3A%09%09%09make+datatype%21+%23get-definition+TYPE_FILE%0D%0Aurl%21%3A%09%09%09make+datatype%21+%23get-definition+TYPE_URL%0D%0A%0D%0Aset-word%21%3A%09%09make+datatype%21+%23get-definition+TYPE_SET_WORD%0D%0Aget-word%21%3A%09%09make+datatype%21+%23get-definition+TYPE_GET_WORD%0D%0Alit-word%21%3A%09%09make+datatype%21+%23get-definition+TYPE_LIT_WORD%0D%0Arefinement%21%3A%09make+datatype%21+%23get-definition+TYPE_REFINEMENT%0D%0A%3Bbinary%21%3A%09%09make+datatype%21+%23get-definition+TYPE_BINARY%0D%0Aparen%21%3A%09%09%09make+datatype%21+%23get-definition+TYPE_PAREN%0D%0Achar%21%3A%09%09%09make+datatype%21+%23get-definition+TYPE_CHAR%0D%0Aissue%21%3A%09%09%09make+datatype%21+%23get-definition+TYPE_ISSUE%0D%0Apath%21%3A%09%09%09make+datatype%21+%23get-definition+TYPE_PATH%0D%0Aset-path%21%3A%09%09make+datatype%21+%23get-definition+TYPE_SET_PATH%0D%0Aget-path%21%3A%09%09make+datatype%21+%23get-definition+TYPE_GET_PATH%0D%0Alit-path%21%3A%09%09make+datatype%21+%23get-definition+TYPE_LIT_PATH%0D%0Anative%21%3A%09%09make+datatype%21+%23get-definition+TYPE_NATIVE%0D%0Aaction%21%3A%09%09make+datatype%21+%23get-definition+TYPE_ACTION%0D%0Aop%21%3A%09%09%09make+datatype%21+%23get-definition+TYPE_OP%0D%0Afunction%21%3A%09%09make+datatype%21+%23get-definition+TYPE_FUNCTION%0D%0A%3Bclosure%21%3A%09%09make+datatype%21+%23get-definition+TYPE_CLOSURE%0D%0Aroutine%21%3A%09%09make+datatype%21+%23get-definition+TYPE_ROUTINE%0D%0Aobject%21%3A%09%09make+datatype%21+%23get-definition+TYPE_OBJECT%0D%0A%3Bport%21%3A%09%09%09make+datatype%21+%23get-definition+TYPE_PORT%0D%0Abitset%21%3A%09%09make+datatype%21+%23get-definition+TYPE_BITSET%0D%0Afloat%21%3A%09%09%09make+datatype%21+%23get-definition+TYPE_FLOAT%0D%0Apoint%21%3A%09%09%09make+datatype%21+%23get-definition+TYPE_POINT%0D%0Avector%21%3A%09%09make+datatype%21+%23get-definition+TYPE_VECTOR%0D%0A%0D%0Anone%3A++%09%09%09make+none%21+0%0D%0Atrue%3A++%09%09%09make+logic%21+1%0D%0Afalse%3A+%09%09%09make+logic%21+0).

@aroben - any chance you could take a look into this?

**Comment by aroben** [comment]
@Oldes Is this the rule that should be highlighting `string!` on the identified lines in your example? https://github.com/Oldes/Sublime-Red/blob/4c84201cd2e25d4c2b714358110fae7488c65593/Red.JSON-tmLanguage#L407-L410

It looks like the problem is that the regex contains an extra pipe character. The basic form is this: `(a|b|c|)`. That last pipe causes the regex not to match.

**Comment by Oldes** [comment]
Thank you very much, indeed it fixed the issue. Interesting that Sublime is fine with such a typo:) I guess that I must update the submodule, right?

**Comment by aroben** [comment]
> Interesting that Sublime is fine with such a typo:)

My guess is that Sublime is using Oniguruma, while github.com uses PCRE. There are a few differences like this we've seen crop up. We use PCRE because it's faster.

> I guess that I must update the submodule, right?

It'll get updated the next time we update Linguist; you don't need to do anything.

**Pull request merged**
