### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by jwilk**

### CODE REVIEW

**Comment by Alhadis** [comment]
You need to [accept the license agreement](https://cla.github.com/github/linguist/accept/jwilk) before you can fix that typo.

**Comment by jwilk** [comment]
LOL, that's not going to happen.

**Comment by arfon** [comment]
`¯\_(ツ)_/¯`

**Comment by Alhadis** [comment]
I'd love to know how this guy installs software without clicking past an EULA, hahahahahah.

**Comment by pchaigno** [comment]
@Alhadis You want to fix this or should I? :smile:

**Comment by Alhadis** [comment]
I'll fix it, because I clearly haven't submitted enough pull requests today.

**Pull request closed without merging**
