### PR TITLE
Add 1C (BSL) language support

### PR DESCRIPTION
**Pull request by nixel2007**
Hi there!

I would like to add 1C:Enterprise 8 (BSL) language.
1C:Enterprise is a very commonly used platform for automating a company’s financial and wider operational activities in CIS.  
Official site (english version): http://1c-dn.com/1c_enterprise/what_is_1c_enterprise/
Russian version: http://v8.1c.ru/

As a grammar i used [this](https://github.com/xDrivenDevelopment/atom-language-1c-bsl) Atom package developed by me as a part of [xDrivenDevelopment community](https://github.com/xDrivenDevelopment).

1C:Enterprise uses many file extensions. The main ones are `.bsl` for modules and `.xml` for metadata and config-stuff (actually it's an XML files). Those extensions were introdused this autumn, so it's not so much search results (so far) [link](https://github.com/search?l=&q=%D0%BF%D1%80%D0%BE%D1%86%D0%B5%D0%B4%D1%83%D1%80%D0%B0+extension%3A.bsl&ref=advsearch&type=Code&utf8=%E2%9C%93), but the number of repos will grow fast.

`.os` extenstion used by external scripts written in 1C (BSL) language as part of `OneScript` project (no english link, sorry. [russian one](http://oscript.io/)). 

Samples are included for bsl and os.

### CODE REVIEW

**Comment by pchaigno** [comment]
Please see the [guidelines to add a new language](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language). In particular, could you link to a search on GitHub showing as many examples of this language as possible, for each file extension?

**Comment by nixel2007** [comment]
.bsl - [link1](https://github.com/search?utf8=%E2%9C%93&q=%D0%BF%D1%80%D0%BE%D1%86%D0%B5%D0%B4%D1%83%D1%80%D0%B0+extension%3Absl&type=Code&ref=searchresults) [link2](https://github.com/search?utf8=%E2%9C%93&q=%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D1%8F+extension%3Absl&type=Code&ref=searchresults)
.os [link1](https://github.com/search?utf8=%E2%9C%93&q=%D0%BF%D1%80%D0%BE%D1%86%D0%B5%D0%B4%D1%83%D1%80%D0%B0+extension%3Aos&type=Code&ref=searchresults) [link2](https://github.com/search?utf8=%E2%9C%93&q=%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D1%8F+extension%3Aos&type=Code&ref=searchresults)

And looks like 1C company removed `mdo` and `form` extensions and changed it to regular xml.
I'll remove them by new commit in few minutes.

**Comment by nixel2007** [comment]
`mdo` and `form` are removed.

**Comment by nixel2007** [comment]
@pchaigno ping?

**Comment by pchaigno** [comment]
I counted the number of users and repositories for both file extensions:

File extension | Number of users | Number of repositories
---|---|---
`.os` | 10 | 18
`.bsl` | 11 | 14

Despite the large number of `.bsl` files (around 8,000) there does not seem to be many users.

**Comment by nixel2007** [comment]
There are two things about `bsl`
1) As I said it's a pretty young format of source storage for 1C. Up to this autumn 1C used the 'txt' extention. Tools for git-flow are in active development and code highlighting in github may greatly stimulate the further growth and popularity on github.
2) Some apps written on 1C are not allowed to have public access, so they may be hidden as private repos.

**Comment by pchaigno** [comment]
First, I'm not from GitHub, so I won't be making any decision here ;)

Second, while I understand your arguments, there has to be some minimum requirements to add new languages. Linguist has its own limits, in terms of maintainability, memory usage and performance.

> Up to this autumn 1C used the 'txt' extention.

This makes me think we could wait a few months for `.bsl` to gain popularity on GitHub.

**Comment by nixel2007** [comment]
@arfon please give any feedback about this PR.
Alos I can rebase or make another PR with non-master branch if you need.

**Comment by arfon** [comment]
> This makes me think we could wait a few months for .bsl to gain popularity on GitHub.

Agreed. @nixel2007 - I'm afraid the level of adoption here is too low to be added to Linguist right now. I suggest revisiting this in a few months time.

**Comment by nixel2007** [comment]
@pchaigno can you share a script, which downloads repos, please? i want to check number of repos periodicaly.

**Comment by allustin** [comment]
Raise discussion. 

what we have for now:

1. before GitHub linguist does not support BSL lang 1C programmers did not want to use GitHub for there code hosting
1. linguist engine did not want add support for 1C lang because there is no BSL repo on GitHub
1. 

we have a deadlock ;-)

Thats why many 1C programmers use there own GitLab and Gogs Servers
and thants why we can not implement GitHub Enterprise in large companies wich use 1C for internal ERP systems

at this point we have to make the mirroring of our repository into an internal gitlab server for code review's, but it's somehow strange

@arfon can you can add language support in order to popularize GitHub for 1C ?

**Comment by allustin** [comment]
**without much hope I shall ask - any news ?**  

@nixel2007 may be we need a new pull request ? 

currently we have

99 users with 179 repositories

BSL - 114 repos
OS - 66 repos

based on our nigth search https://github.com/allustin/awesome-1c/tree/master/data

@arfon it is enough to prove the usefulness ?

P.S. the worst thing that I can not normally promote Enterprise version for large corporations in Russia...

**Comment by nixel2007** [comment]
I can rebase a PR and add some heuristic, if @arfon gives me a green light

**Comment by arfon** [comment]
> @arfon it is enough to prove the usefulness ?

With my GitHub staff privileges, I'm able to get broad statistics for file extensions on private repos too (I'm not able to view individual files/repos of course) and it looks like there's an order of magnitude more `.bsl` and `.os` files on GitHub in private repositories.

I think we should add BSL at this point. @nixel2007 - would you be able to update this PR with the latest changes from `master`?

**Comment by nixel2007** [comment]
@arfon i've rebased and squashed my commits on current `master`. Also i've added a heuristic for `.bsl` and `.os` files to reduce false-positives (mostly for `.os`).

Travis reports all green. Is current version OK for you?

P.S. I've added licence file manualy cause i can't figure how to run script/licensed without closed source gem :)
/cc @allustin

**Comment by pchaigno** [comment]
@nixel2007 Thanks for your patience and the quick rebase :zap:
Could you add a test for the heuristic in [`test_heuristics.rb`](https://github.com/github/linguist/blob/master/test/test_heuristics.rb)?

**Comment by nixel2007** [comment]
@pchaigno done.

**Comment by pchaigno** [comment]
Uh, wait. There's no conflict on these extensions so we won't need heuristic rules (all `.os` and `.bsl` files will be associated to 1C anyway). Sorry, I should have checked that first :bow:

**Comment by nixel2007** [comment]
@pchaigno i've added a heurestic because there are a lot `os` non-`1C (BSL)`-files. will it help?

**Comment by pchaigno** [comment]
Not unless we can identify what is their language and add support for it. Linguist doesn't have a default or not-a-language option.

**Comment by nixel2007** [comment]
@pchaigno should i add an `else` section with em... `Text` language or remove test completly?
As I can see `Text` is not a programming language, so it may be a solution (no statistic at language bar, etc...)

**Comment by nixel2007** [comment]
or we can just leave it as is and add those languages in future

**Comment by arfon** [comment]
> @pchaigno should i add an else section in heurestic (language.yml?) with em... Text language or remove test and heurestic completly?

We should probably remove this completely.

**Comment by nixel2007** [comment]
@arfon done

**Comment by arfon** [comment]
:+1: thanks for this @nixel2007! This will be live with the next release of Linguist (next week sometime)

**Comment by nixel2007** [comment]
Thanks a lot, @arfon and @pchaigno!

**Pull request merged**
