### PR TITLE
Release v5.3.4

### PR DESCRIPTION
**Pull request by kivikakk**
* New grammars compiler (#3915)
* Add error output to the compiler (#3935)
* Vendor CSS files in font-awesome directory (#3932)
* Improve Prolog .pro heuristic to avoid false positives (#3931)
* Limit tokens to 32 characters or less (#3922, #3925)
* Add Carthage/Build to generated list so it doesn't show in PR diffs (#3920)
* Changed Carthage vendor regex to allow folder in any subdirectory (#3921)
* Add Cocoapods to generated list so it doesn't show in PR diffs (#3865)
* Unvendor `tools/` (#3919)
* Add PostCSS syntaxes support (#3916)
* Test Perl before Turing when running heuristics (#3880)
* Add YARA language (#3877) 
* Add the Common Workflow Language standard (#3902) 
* Fix failing edges on leading commas in args (#3905)
* Add BUILD.bazel to Python filenames (#3907) 
* Add color for LFE language. (#3895) 
* Update grammars.

### CODE REVIEW

**Comment by lildude** [comment]
I really wanted to hold off on a release until https://github.com/github/linguist/pull/3807 was merged and then do a major v6.0.0 release as it introduces new functionality.

I also hope to get https://github.com/github/linguist/pull/3930 in the next release as it does affect .com /cc @carlosmn 

If you really need a release now, we can. 

As we're updating and adding new grammars, a minor version bump (v5.4.0) is probably more apt.

**Comment by kivikakk** [comment]
Thanks @lildude! Totally happy to hold off until the new year in this case. 😸

**Comment by freak4pc** [comment]
Exciting !! 🎉

**Comment by lildude** [comment]
Closing this as I'm going to make a new release :soon:

**Pull request closed without merging**
