### PR TITLE
Add Futhark language support

### PR DESCRIPTION
**Pull request by Munksgaard**
## Description

This PR adds support for Futhark, a language for ["high-performance purely functional data-parallel array programming on the GPU"](https://futhark-lang.org/)

## Checklist:

- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3Afut+NOT+nothack
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - https://github.com/diku-dk/futhark-website/blob/master/examples/gaussian-blur.fut
    - Sample license(s):
      - ISC
  
  - [x] I have included a syntax highlighting grammar: [here](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=cson&grammar_url=https%3A%2F%2Fgithub.com%2FAlhadis%2Flanguage-etc%2Fblob%2Fmaster%2Fgrammars%2Ffuthark.cson&grammar_text=&code_source=from-text&code_url=&code=let+foo+%28%29+%3D%0D%0A++if+x+then+x+else+x%0D%0A%0D%0Alet+foo+%28%29+%3D%0D%0A++if+x%0D%0A++then+x%0D%0A++else+x%0D%0A%0D%0Alet+foo+%28%29+%3D%0D%0A++if+x%0D%0A++then+x%0D%0A++else+if+x%0D%0A++then+x+else+x%0D%0A%0D%0Alet+foo+%28%29+%3D%0D%0A++if+x+then+x%0D%0A++else+if+x+then+x%0D%0A++else+x%0D%0A%0D%0Alet+foo+%28%29+%3D%0D%0A++if+a+%3C+b%0D%0A++then+if+a+%3C+c+then+a+else+c%0D%0A++else+if+b+%3C+c+then+b+else+c%0D%0A%0D%0Alet+foo+%28%29+%3D%0D%0A++if+a+%3C+b%0D%0A++then+if+a+%3C+c%0D%0A+++++++then+a%0D%0A+++++++else+c%0D%0A++else+if+b+%3C+c%0D%0A++then+b%0D%0A++else+c%0D%0A%0D%0Alet+foo+%28%29+%3D%0D%0A++let+x+%3D%0D%0A++++if+a+then+b+else%0D%0A++++let+x+%3D+2+in+x%0D%0A++in+x%0D%0A%0D%0Alet+foo+%28%29+%3D%0D%0A++if+x+then+y+else%0D%0A++if+x+then+y+else%0D%0A++++x%0D%0A%0D%0Alet+foo+%28%29+%3D%0D%0A++if+x%0D%0A++then+y%0D%0A++else%0D%0A++let+z+%3D+3%0D%0A++in+z%0D%0A%0D%0Alet+foo+%28%29+%3D%0D%0A++if+x+then+y%0D%0A++else+if+x+then+y%0D%0A++else+if+x+then+z%0D%0A++else+0%0D%0A%0D%0Alet+foo+%5Bm%5D+%5Bn%5D+%28%29+%3D%0D%0A++if+x%0D%0A++then+y%0D%0A++else+if+x%0D%0A++then+if+a%0D%0A+++++++then+b%0D%0A+++++++else+c%0D%0A++else+if+x%0D%0A++then+z%0D%0A++else+0%0D%0A%0D%0Alet+foo+%28%29+%3D%0D%0A++if+cond%0D%0A++then%0D%0A++let+cost%5Bid%5D+%3D+cost%5Btid%5D+%2B+1%0D%0A++let+updating_graph_mask%5Bid%5D+%3D+true%0D%0A++in+%28cost%2C+updating_graph_mask%29%0D%0A++else+baz%0D%0A)
  - [x] I have updated the heuristics to distinguish my language from others using the same extension.
    - There are no other languages using the same extension.

### CODE REVIEW

**Comment by Munksgaard** [comment]
There is an emacs-mode that provides highlighting (and I think perhaps a gedit-grammar file or something), but Futhark doesn't currently have a TextMate syntax highlighting grammar. Is it required, and if so, any tips on how to get started? I don't have TextMate unfortunately (or a Mac)...

**Comment by Munksgaard** [comment]
> Please follow the instructions in CONTRIBUTING.md for adding a new language.

I see I was treating the language_id incorrectly. That has been fixed. The only other thing I can think of that's missing is the grammar. Is that required?

**Comment by Alhadis** [comment]
👋 Hey @Munksgaard, apologies for the slow response.

> The only other thing I can think of that's missing is the grammar. Is that required?

No, it's not required. Grammars are only used to provide syntax highlighting, which is a nice-to-have, but entirely optional. Many languages recognised on GitHub lack grammars of their own, or use the grammar of a syntactically-similar language as a compromise.

I could write you one if you provided a definitive language specification (preferably one with an ABNF or EBNF grammar).

**Comment by Munksgaard** [comment]
> wave Hey @Munksgaard, apologies for the slow response.
> 

Hi @Alhadis, no worries at all! I realize this is a busy project :-)

> > The only other thing I can think of that's missing is the grammar. Is that required?
> 
> No, it's not required. Grammars are only used to provide syntax highlighting, which is a nice-to-have, but entirely optional. Many languages recognised on GitHub lack grammars of their own, or use the grammar of a syntactically-similar language as a compromise.
> 
> I could write you one if you provided a definitive language specification (preferably one with an ABNF or EBNF grammar).

The closest we have is the one defined here: https://futhark.readthedocs.io/en/latest/language-reference.html

It's missing some keywords though, but we currently have the following: "true", "false", "if", "then", "else", "let", "loop", "in", "val", "for", "do", "with", "local", "open", "include", "import", "type", "entry", "module", "while", "unsafe", "assert", "match", "case"

**Comment by Alhadis** [comment]
Actually wait, I missed [your earlier comment](https://github.com/github/linguist/pull/4842#issuecomment-613348575) about an Emacs `futhark-mode`… I was going to use it as a loose reference, but noticed it's released under a [permissive license](https://github.com/diku-dk/futhark-mode/blob/ca22b1e5fe46125b968c3da46e0bc9780b32e346/futhark-highlight.el). 😁 Normally these things are GPL/copyleft, which requires me to write an entirely new grammar from scratch (to eliminate any "issues" with licensing and distribution, as Linguist is permissively-licensed). But because [`futhark-mode`](https://github.com/diku-dk/futhark-mode/blob/master/futhark-highlight.el) is ISC-licensed, I can skip the research and just port the thing by hand. 😀

BTW, you see that Emacs Lisp file's highlighting? [You're welcome](https://github.com/Alhadis/language-emacs-lisp). 😉

**Comment by Munksgaard** [comment]
> Actually wait, I missed [your earlier comment](https://github.com/github/linguist/pull/4842#issuecomment-613348575) about an Emacs `futhark-mode`… I was going to use it as a loose reference, but noticed it's released under a [permissive license](https://github.com/diku-dk/futhark-mode/blob/ca22b1e5fe46125b968c3da46e0bc9780b32e346/futhark-highlight.el). grin Normally these things are GPL/copyleft, which requires me to write an entirely new grammar from scratch (to eliminate any "issues" with licensing and distribution, as Linguist is permissively-licensed). But because [`futhark-mode`](https://github.com/diku-dk/futhark-mode/blob/master/futhark-highlight.el) is ISC-licensed, I can skip the research and just port the thing by hand. 
> 
> **EDIT:** Hrm, that Emacs mode has a lot of discrepancies with the official specification… I'll take what I can from both, but it seems I haven't entirely skipped the reading/research phase book

Hm, good point. We should probably see about updating that emacs mode as well at some point. Thanks for pointing it out for us!

> BTW, you see that Emacs Lisp file's highlighting? [You're welcome](https://github.com/Alhadis/language-emacs-lisp). wink
> 

Haha, that's great :smile:

**Comment by Alhadis** [comment]
Alright, [try this](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=cson&grammar_url=https%3A%2F%2Fgithub.com%2FAlhadis%2Flanguage-etc%2Fblob%2Fmaster%2Fgrammars%2Ffuthark.cson&grammar_text=&code_source=from-text&code_url=&code=let+foo+%28%29+%3D%0D%0A++if+x+then+x+else+x%0D%0A%0D%0Alet+foo+%28%29+%3D%0D%0A++if+x%0D%0A++then+x%0D%0A++else+x%0D%0A%0D%0Alet+foo+%28%29+%3D%0D%0A++if+x%0D%0A++then+x%0D%0A++else+if+x%0D%0A++then+x+else+x%0D%0A%0D%0Alet+foo+%28%29+%3D%0D%0A++if+x+then+x%0D%0A++else+if+x+then+x%0D%0A++else+x%0D%0A%0D%0Alet+foo+%28%29+%3D%0D%0A++if+a+%3C+b%0D%0A++then+if+a+%3C+c+then+a+else+c%0D%0A++else+if+b+%3C+c+then+b+else+c%0D%0A%0D%0Alet+foo+%28%29+%3D%0D%0A++if+a+%3C+b%0D%0A++then+if+a+%3C+c%0D%0A+++++++then+a%0D%0A+++++++else+c%0D%0A++else+if+b+%3C+c%0D%0A++then+b%0D%0A++else+c%0D%0A%0D%0Alet+foo+%28%29+%3D%0D%0A++let+x+%3D%0D%0A++++if+a+then+b+else%0D%0A++++let+x+%3D+2+in+x%0D%0A++in+x%0D%0A%0D%0Alet+foo+%28%29+%3D%0D%0A++if+x+then+y+else%0D%0A++if+x+then+y+else%0D%0A++++x%0D%0A%0D%0Alet+foo+%28%29+%3D%0D%0A++if+x%0D%0A++then+y%0D%0A++else%0D%0A++let+z+%3D+3%0D%0A++in+z%0D%0A%0D%0Alet+foo+%28%29+%3D%0D%0A++if+x+then+y%0D%0A++else+if+x+then+y%0D%0A++else+if+x+then+z%0D%0A++else+0%0D%0A%0D%0Alet+foo+%5Bm%5D+%5Bn%5D+%28%29+%3D%0D%0A++if+x%0D%0A++then+y%0D%0A++else+if+x%0D%0A++then+if+a%0D%0A+++++++then+b%0D%0A+++++++else+c%0D%0A++else+if+x%0D%0A++then+z%0D%0A++else+0%0D%0A%0D%0Alet+foo+%28%29+%3D%0D%0A++if+cond%0D%0A++then%0D%0A++let+cost%5Bid%5D+%3D+cost%5Btid%5D+%2B+1%0D%0A++let+updating_graph_mask%5Bid%5D+%3D+true%0D%0A++in+%28cost%2C+updating_graph_mask%29%0D%0A++else+baz%0D%0A). It's pretty much a one-to-one translation of `futhark-mode`'s pattern-matching, albeit with a few corrections I spotted while perusing the spec.

Let me know if that looks good to you.

**Comment by Munksgaard** [comment]
That looks great @Alhadis, thank you so much!

**Comment by Munksgaard** [comment]
Hm, I'm not sure how to add the grammar, doing `./script/add-grammar https://github.com/Alhadis/language-etc` doesn't seem to do much, perhaps because your repository is already being used?

**Comment by Alhadis** [comment]
Ah, that merits an explanation. Normally, we add new grammars by registering a new submodule with Linguist, a process that `add-grammar` exists to simplify. As you guessed, this only works if a module hasn't already been added. We don't expect users will need to manually-update an existing submodule to add a grammar that was recently added upstream.

After publishing [~20 different grammar repositories](https://github.com/Alhadis?tab=repositories&q=language&type=&language=), I've now taken to adding new grammars to a [single monolithic collection](https://github.com/Alhadis/language-etc/tree/master/grammars), which is easier for me to maintain and keep track of. Unfortunately, it does make situations like these tricky....

**Comment by Alhadis** [comment]
@Munksgaard I've pushed a manual update to your branch. Should be okay now. 👍

**Comment by Munksgaard** [comment]
> @Munksgaard I've pushed a manual update to your branch. Should be okay now. +1

That's so nice of you, thank you for all your hard work!

**Comment by Munksgaard** [comment]
@lildude I believe I've followed the instructions in CONTRIBUTING.md now. Is there anything else I need to do?

**Comment by lildude** [comment]
Nope. LGTM now.

**Pull request merged**
