### PR TITLE
Elixir: Add mix.lock filename

### PR DESCRIPTION
**Pull request by lpil**
#2260 

[An example `mix.lock` file](https://github.com/lpil/elixre/blob/ddabcb13a3242f855781e0b8d920f3a8b985f10f/mix.lock)

### CODE REVIEW

**Comment by arfon** [comment]
Hi @lpil, thanks for this. The build is currently failing with:

```
  1) Failure:
TestSamples#test_Elixir_has_samples [/home/travis/build/github/linguist/test/test_samples.rb:79]:
Missing sample in "samples/Elixir/filenames/mix.lock". See https://github.com/github/linguist/blob/master/CONTRIBUTING.md
```
Basically  we just need an example `mix.lock` file added to `samples/Elixir/filenames/`

**Comment by lpil** [comment]
Ah, thank you @arfon. I've updated my commit.

**Comment by arfon** [comment]
:+1: thanks. Support for this new file type will go live next week sometime.

**Comment by lpil** [comment]
Marvellous. Thank you :)

**Pull request merged**
