### PR TITLE
Added support for Mono .dll.config XML files

### PR DESCRIPTION
**Pull request by Mailaender**
Reference: http://www.mono-project.com/docs/advanced/pinvoke/dllmap/#example

Example: https://github.com/OpenRA/OpenRA/blob/release-20141029/thirdparty/SharpFont.dll.config

### CODE REVIEW

**Comment by arfon** [comment]
@Mailaender - would you mind adding this example file to the `samples` directory?

**Comment by Mailaender** [comment]
Done.

**Comment by bkeepers** [comment]
> @bkeepers - this PR means we support this kind of extension now right?

Theoretically, but we have not added one yet, so it looks like there are still some issues with it. I'll get it fixed up.

**Comment by bkeepers** [comment]
Fixed in https://github.com/github/linguist/pull/1940. If you merge master the tests should be green.

**Comment by Mailaender** [comment]
Rebased.

**Comment by arfon** [comment]
:+1: thanks @Mailaender & @bkeepers

**Comment by arfon** [comment]
@Mailaender it will likely be another couple of weeks before this change is live on GitHub as we'll need to cut a new Linguist gem.

**Comment by aroben** [comment]
This is now live on github.com.

**Comment by Mailaender** [comment]
Thanks!

**Pull request merged**
