### PR TITLE
Support for the Click modular router language

### PR DESCRIPTION
**Pull request by pchaigno**
[Click](http://www.read.cs.ucla.edu/click/docs/language) is a configuration language for the Click modular router.
There are [around 5,500 `.click` files on GitHub](https://github.com/search?utf8=%E2%9C%93&q=extension%3Aclick+NOT+djfhdfhdkfj). I quickly went through these files and they all seem to be Click files. There are at least 138 users of the Click language with 170 repositories.

I used [this Atom grammar](https://github.com/stenverbois/language-click) for syntax highlighting. A possible alternative is [drbarrett/click-sublime](https://github.com/drbarrett/click-sublime):
- [stenverbois/language-click](https://github.com/stenverbois/language-click): [example in Lightshow](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgithub.com%2Fstenverbois%2Flanguage-click%2Fblob%2Fmaster%2Fgrammars%2Fclick.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fpchaigno%2Flinguist%2Fblob%2Fclick%2Fsamples%2FClick%2Fthomer-nat.click&code=)
- [drbarrett/click-sublime](https://github.com/drbarrett/click-sublime): [example in Ligthshow](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgithub.com%2Fdrbarrett%2Fclick-sublime%2Fblob%2Fmaster%2Fclick.tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fpchaigno%2Flinguist%2Fblob%2Fclick%2Fsamples%2FClick%2Fthomer-nat.click&code=)

The color comes from this logo (grey):
Click modular router logo

### CODE REVIEW

**Comment by arfon** [comment]
Thanks for this @pchaigno. Any chance you could bring this up to date with master?

**Comment by pchaigno** [comment]
@arfon Done :-)

**Comment by arfon** [comment]
:+1: thanks @pchaigno

**Comment by pchaigno** [comment]
@arfon If I sent you a list of Click repositories would it be possible to update them?

**Comment by arfon** [comment]
Sure!

**Pull request merged**
