### PR TITLE
Add Kerboscript and Kickstart language

### PR DESCRIPTION
**Pull request by Janik-ux**
## Description
I have added the KerboScript language to the repository. It is the programming language of a mod of Kerbal Space Program called Kerbal Operating System. This mod is widely used under Kerbal Space Program players.
Some other files on github use `.ks` for example "image kickstart files". Linguist classifies them as KerboScript but I do not know how to write heuristics rules to approach this. These "image kickstart files" are not in the database of linguist and the extension is not anywhere else in languages.yml so I ignored this for now.

## Checklist:

- [X] **I am adding a new language.**
  - [X] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3Aks+THROTTLE+NOT+nothack
  - [X] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - https://github.com/ayybradleyjh/kOS-Hoverslam/blob/master/hoverslam.ks
      - https://github.com/KSP-KOS/KSLib/blob/master/library/lib_pid.ks
      - https://ksp-kos.github.io/KOS/tutorials/quickstart.html
    - Sample license(s):
      - MIT (https://github.com/ayybradleyjh/kOS-Hoverslam/blob/master/LICENSE)
      - MIT (https://github.com/KSP-KOS/KSLib/blob/master/LICENSE)
      - GPLv3 (https://ksp-kos.github.io/KOS/copyright.html)
  - [X] I have included a syntax highlighting grammar: https://github.com/KSP-KOS/language-kerboscript
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

### CODE REVIEW

**Review by lildude — CHANGES_REQUESTED** [review]
> Some other files on github use .ks for example "image kickstart files". Linguist classifies them as KerboScript but I do not know how to write heuristics rules to approach this. These "image kickstart files" are not in the database of linguist and the extension is not anywhere else in languages.yml so I ignored this for now.

We can't ignore this. There are way too many files that will be misclassified if we do. You're going to need to identify at least one other user of this extension that is popular enough and as it as part of this PR. If the languages are sufficiently different we can rely on samples and the classifier. If not we'll need heuristics which are just regexes.

**Comment by lildude** [comment]
There's no need to keep merging in master. It'll get done just before merging, which won't be happening until you've addressed the point I raised before.

**Comment by Janik-ux** [comment]
I've now added the Kickstart language myself. Unfortunately I didn't find an user who wanted to contribute to this PR.   
The `ks`-extension is also used in `Keystore Files`, but they are binary and I didn't know how or if at all I should add these files. At the moment linguist does not output any language for keystore files. Maybe this is enough.  
The other file types are well classified as far is I have tested.

I have classified the type of kickstart as "data" in languages.yml because it is mainly used to "configure". For that reason I have not set the color.
  - Sample source(s):
    - https://github.com/ycollet/fedora-spec/blob/master/kickstart/fedora-32-live-jam-xfce-pipewire.ks
    - https://github.com/xiaomatech/cobbler/blob/master/kickstarts/mysql.ks
    - https://github.com/ssalevan/cobbler/blob/master/kickstarts/sample_end.ks
  - Sample license(s):
    - GPL-3.0 (https://github.com/ycollet/fedora-spec/blob/master/LICENSE)
    - MIT (https://github.com/xiaomatech/cobbler/blob/master/LICENSE)
    - GPL-2.0 (https://github.com/ssalevan/cobbler/blob/master/COPYING)

I have included syntax highlighting grammar from @wgwoods https://github.com/wgwoods/language-kickstart

Sorry for the mess with merging and pushing, I'm relatively new to git...

**Review by lildude — APPROVED** [review]
Thanks for addressing my comments. This looks good to go now 👍

**Pull request merged**
