### PR TITLE
[Add Language] Jolie

### PR DESCRIPTION
**Pull request by thesave**
[Jolie](http://jolie-lang.org) is a general-purpose service-oriented language, mainly used for the development of microservices. The language is currently used in [industry](http://www.italianasoftware.com/) and [taught](http://www.jolie-lang.org/academia.html) in Danish, Italian, and Russian Universities.

In the wild there are more than 3k Jolie files ([.ol](https://github.com/search?o=asc&p=3&q=extension%3Aol+NOT+nothack&type=Code) and [.iol](https://github.com/search?utf8=%E2%9C%93&q=extension%3Aiol+NOT+nothack&type=Code) files - raw files should be excluded).

The [language repository](https://github.com/jolie/jolie) is hosted on GitHub, has a growing community of contributors, and steady-paced releases.

Thanks and please let me know if additional changes are required.

### CODE REVIEW

**Comment by pchaigno** [comment]
@lildude There seem to be a lot of Git LFS `.hfst.ol` files. Is that going to be an issue if we add support for the `.ol` extension or will github.com ignore them when running Linguist?

**Comment by lildude** [comment]
@pchaigno Good question. I don't know off the top of my head. I'll have to do some digging.

**Comment by lildude** [comment]
@pchaigno I think this PR may cause those files to be reclassified. Can you link to a few examples so I can see them in context.  Thx.

**Comment by pchaigno** [comment]
Actually, they're not all Git LFS files: https://github.com/search?p=1&q=extension%3Aol+filename%3Ahfst+NOT+nothack&type=Code&utf8=%E2%9C%93.

**Comment by lildude** [comment]
@pchaigno I think we may be 🆗 with those `hsft.ol` files.  I've not looked at all of them...

aintnobody

... but I have looked at quite a few and they're all currently detected as binaries and the changes in this PR don't change that classification.

**Pull request merged**
